### ISSUE TITLE
Charging player-to-player proximity

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#10]
When charging a player that stands still (note: not moving is important here) you get _really_ close to him. This is because the bounding box of players are really small. Is this wrong?

**Comment by ccshiro** [comment]
Chulain gave me a video that seems to answer this nicely:
https://www.youtube.com/watch?v=ysH5NC0aPeQ#t=91

**Comment by Sakatoro** [comment]
Perhaps this Video can help you

http://youtu.be/-2blpf3A0zo?t=2m13s

min 2:13 warri charge to druid

**Comment by ccshiro** [comment]
Will consider this proven by the videos linked. Thanks guys.
