### ISSUE TITLE
Mages Should Be Able To Blink While Silenced When Stunned

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1002]
Currently, they can't.  As long as a stun is on the mage, he should be able to blink, even if he's silenced.  This doesn't apply to immobilizing effects.

Evidence of stun (possible):
https://www.youtube.com/watch?v=JTVjH-WI7ZI&feature=youtu.be&t=48s

Evidence of immobilize (not possible):
http://youtu.be/tYYK9ykH1bU?t=6m48s

CC test:
![wowscrnshot_070615_143749](https://cloud.githubusercontent.com/assets/13057166/8534016/9751f114-23ed-11e5-9338-11476e4c025a.jpg)

It might actually be Immobilize + Stun + Silence that's required, but I'm not positive.

**Comment by Ickler** [comment]
This is -not- correct. If the mage is silenced, he should absolutely not be able to use blink.

**Comment by YourNewfriend** [comment]
whatever you say

**Comment by Ickler** [comment]
You can find counterproof to this in several rogue movies from TBC, where the rogue Garrotes - CS out of a sap (CS lands before breaking sap), to ensure mage can't blink out. 
Common strategy vs deep fire mages especially, due to them having blazing speed.

**Comment by YourNewfriend** [comment]
Perhaps it's "Immobilize + Stun + Silence" rather than "Stun + Silence" then, and I'd like to see what you have.

**Comment by Ickler** [comment]
I am not sure where that video is from, but it looks wonky to me. 

However I can refer to 1000s of duels and fights VS mages from retail TBC where that was the go-to opener. Also, having a mage myself I know how the Garrote into CS opener would force an early IB. 
I also mained mage in vanilla, and I never heard of this. If this video is indeed from retail (sceptic), could it be after a patch where something was broken. 
We all know Blizzard messed up from time to time :P 
Do you have a vid from TBC where you can see the same? I could start going through some old Mage / Rog movies to find something that probably proves the opposite.

**Comment by YourNewfriend** [comment]
Source: http://www.shadowsongeurope.com/forum/archive/index.php/t-16645.html

25-03-2008, 10:06 PM Warlee writes:

"And sadly they have added another bug by fixing it.

I will explain it here as its not that useful. Basicaly when you are silenced by garrote, improved counterspell or spellock you cannot cast blink. The thing is that when you are silenced(only by spells that I have mentioned before) AND stunned - you can. By using this tonk you can force yourself to be stunned.

Source: 
http://vurtneforum.net/general-chat-f1/don-t-throw-away-your-steam-tonks-t1086.htm"

Also, the video I provided is indeed from retail 2006.

**Comment by Ickler** [comment]
So only counterspell / spell lock etc. That would exclude most situations where I silenced / stunned as part of a tactical approach. A few scenarios that come to mind, all uses physical silence (garrote, imp kick). 

2v2 as Feral Rog, common to open mages with garrote / pounce. Almost guaranteed to force a block, or at least force the mage / XX team into complete defensive mode.
Same when running rog/rog, CS / Garrote openings. 

The question should be then, is it even intended by Blizzard? It appears like a mistake to me, should it then be implemented?

**Comment by YourNewfriend** [comment]
You're selectively reading, and if it existed for the course of the classical game and an expansion, I think it's fine to implement, but it's up to the devs.

**Comment by Peonstomperx** [comment]
I found this comment "pre 3.0 if stunned while silenced you could blink, post 3.0 you can't blink silenced stunned" but no patch notes regarding it.
http://www.mmo-champion.com/threads/628279-blink-no-longer-removes-you-from-stun

@Ickler less ranting more evidence, post this "counterproof to this in several rogue movies from TBC"

**Comment by PatchnotesTBC** [comment]
This might been a possible bug from retail. Can it have been patched? Is there any note on any of the patches from vanilla?

**Comment by darkcranio** [comment]
Blizzbuglike isn't it?

**Comment by YourNewfriend** [comment]
The only doubt remaining is if stun has to come after silence.

**Comment by Dethepwnz** [comment]
I know a 100% that mages are NOT able to blink while silenced. This has NEVER been the case since vanilla up till now. Mages are just able to blink stuns like Cheap shot, Kidney Shot, Shadow Fury etc. BUT NOT WHILE ANY SILENCE WAS APPLIED.

**Comment by YourNewfriend** [comment]
lol

**Comment by darkcranio** [comment]
Oh really? That's not what the videos showed... well maybe not inteded but was there from vanilla til bc.

**Comment by YourNewfriend** [comment]
WOTLK*

**Comment by YourNewfriend** [comment]
Existed from the implementation of blink to WOTLK.

**Comment by ccshiro** [comment]
It seems pretty clear that you're right that it did work. However, surely it has to have been a bug. One could speculate that it might come about from some wonky code path that exists to allow blink during stun. Either way, it's very counterintuitive and overall seems to have a mainly negative effect on gameplay. We've opted out of blizzlike before with things that are likely to be bugs, and I think this is another case where not doing it the blizzlike way is the better solution.

As such, I will put this to wontfix. If any of you feel our decision is incorrect and you have some persuasive arguments, feel free to hit me up on irc or reply to this topic.

**Comment by YourNewfriend** [comment]
Obviously a very.. questionable decision.  Since it's a mechanic that existed for 3.5 years until WOTLK, I personally don't consider it to be a bug.

**Comment by darkcranio** [comment]
Well, as a mage, I don't really care, but Newfriend is right that it was part of PVP ranking in vanilla as well as ladders in TBC.

**Comment by Ickler** [comment]
It's not a mechanic that existed, I think Shiro's right and it's a bug. There are several accounts of other bugs, that I can recall existing for a long time (Seal twisting for one). 
Also, they were even mentioned in blue posts (Blizzard knew about them, yet didn't fix). I can't recall anything about this particular one though, but it's definitely never worked for Physical Silences. The scenarios where this applied is very limited, and it can't be intended in my opinion at least.

I don't think it's a questionable decision at all, why on earth should a silence effect still allow you to blink if you're stunned? The logic is just not there... Blink negates stuns and roots, it seems logical to me that something bugged out. 

Claiming that it's a part of Vanilla PvP ranking is quite the overreach, and ladders in TBC? Well, I for one will be glad this doesn't make it in. To me it's obviously not intended.

**Comment by YourNewfriend** [comment]
Seal Twisting was a somewhat elaborate thing; this on the other hand is the way one of the basic class mechanics worked, and applied to every retail mage's career during those periods.

If I choose to play a mage on Corecraft, I would most likely feel  a bit derisive if I were to be stunned + silenced, knowing full-well how I should've been able to escape.

I also imagined that this change could have a somewhat negative impact on gameplay, so I suspected that the devs might choose to not correct it, but we don't really know the outcome until we try it in my opinion.

**Comment by darkcranio** [comment]
http://www.wowhead.com/spell=45438/ice-block#comments
By eveline (114 – 0) on 2008/02/01 (Patch 2.3.3)  
Can the mage , when silenced , do ice-block ????

1

Atshlupa on 2008/02/06 (Patch 2.3.3)
no. Mage can't cast Ice Block when silenced.

16

PiratePants on 2008/03/20 (Patch 2.3.3)
Ice block works much the same as a Paladin's Divine Intervention. Flat silences will not stop the mage from ice blocking. However, if your frost school gets locked out, then no you cannot use ice block. For instances, Shadow priest 'X' silences Mage 'Y', the mage can still iceblock Mage 'X' counterspells Mage 'Y' while casting a frostbolt. Mage 'Y' has his frost spells locked out, he cannot cast ice block

Working with the same logic until today, so why not this?

**Comment by Ickler** [comment]
Mage can cast IB when silenced, but not when interrupted on Frost spells. 

Seal twisting was a bug, and GC even talked about it in a Blue post. You had the same issue with double potting, they were all bugs that lasted a long time, Blizzard knew about them. And they still never fixed them. 
I played a mage through most of vanilla, as well as having an alt mage in TBC that I did fairly well on, and I never even knew you could do this (mainly because I never even tried to blink when silenced). I suppose if I played it as a main, I would've noticed it at some point. 
Now that I am aware I do spot it, on rare occasions in TBC PvP vids, but I can't help but to strongly feel like that's a bug, and a rather big impact one at that... It completely contradicts game mechanics, if anything.

And as for your ad hominem YourNewFriend, I don't mind :) I've been online long enough to not take offense. If you need to attack my person, do so in a PM on IRC please.

**Comment by warlee** [comment]
"Source: http://www.shadowsongeurope.com/forum/archive/index.php/t-16645.html

25-03-2008, 10:06 PM Warlee writes:

"And sadly they have added another bug by fixing it.

I will explain it here as its not that useful. Basicaly when you are silenced by garrote, improved counterspell or spellock you cannot cast blink. The thing is that when you are silenced(only by spells that I have mentioned before) AND stunned - you can. By using this tonk you can force yourself to be stunned.

Source: 
http://vurtneforum.net/general-chat-f1/don-t-throw-away-your-steam-tonks-t1086.htm"

Also, the video I provided is indeed from retail 2006. "

^
Warlee here, this was a retail bug abuse, I reported it and it was fixed shortly after ;) It must have been reverted with wotlk patch update, because it did not exist in 2.4 in TBC.
Thanks for Ickler to direct me here. Cheers

**Comment by YourNewfriend** [comment]
@warlee 

Are you referring to the steam tonks, or blinking while stunned?
