### ISSUE TITLE
Last boss of Steam Vaults interrupts channelling his drain coilfang cystern ability by casting spell reflect (prevent himself from triggering his enrage ability)

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1007]
Last boss of coilfang reservoir interrupts channelling his drain coilfang cystern ability by casting spell reflect (prevent himself from triggering his enrage ability).

**Comment by petaal** [comment]
Duplicate of https://github.com/ccshiro/cc-buglist/issues/936

**Comment by rylaiii** [comment]
Hey, This it what you like, you just have to take a look! Info here http://new.flexdriver.com/lnyvf

Warmest regards, ross.porto@rocketmail.com

**Comment by rylaiii** [comment]
Hey,

This stuff is really crazy, you've got  to see  that for sure!  Just take  a look here http://new.htciaontario.org/lnxbrnkn

Good wishes, ross.porto@rocketmail.com
