### ISSUE TITLE
Defence Rating not calculating

### ISSUE THREAD

**Issue by halotestin** [ccshiro/cc-buglist#1008]
http://s24.postimg.org/nxuex2zt0/bug.jpg

41 Defence, yet the tooltip says 0.00% decrease to get critically hit. Should be 1,64% I think according to the numbers below:

---Defence---

= ~2.4 rating per skill, 1 skill = 0.04% dodge, miss, anti-crit ((25 defence, or ~59.15 rating, for 1% less crit/more dodge/more miss))

**Comment by ghost** [comment]
It appears to be because you instantly leveled to 70 so your defense skill is probably 1. Select yourself and type .maxskill and it should fix it. I tested this on a fresh 70 paladin with 5/5 anticipation (+20 def talent).

**Comment by halotestin** [comment]
yeah my bad, .maxskill /facepalm
