### ISSUE TITLE
Pit Commander Rain of Fire

### ISSUE THREAD

**Issue by ebonywolf** [ccshiro/cc-buglist#1015]
The pit commander in stair of destiny is dealing around 800-900 per tick damage on his rain of fire. I remember it dealing 15k+ per tick on retail. Although sources say it deals 50k+ damage per tick.
http://wowwiki.wikia.com/Pit_Commander

**Comment by darkcranio** [comment]
By didron (2,664 – 12·21) on 2007/02/10 (Patch 2.0.6)  
"You suffer 59696 Fire damage from Pit Commander's Rain of Fire. You die."

That was at lvl 70..., no Fire resistance gear on though.
