### ISSUE TITLE
Mages Can't See Hunters Who've Applied Hunter's Mark To Them

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1019]
http://wowwiki.wikia.com/Patch_2.4.3
Patch 2.4.3: Invisible players with Hunter’s Mark can see the hunter that put the mark on them.

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/582 is related.

**Comment by Dethepwnz** [comment]
I know a 100% that mages are NOT able to blink while silenced. This has NEVER been the case since vanilla up till now. Mages are just able to blink stuns like Cheap shot, Kidney Shot, Shadow Fury etc. BUT NOT WHILE ANY SILENCE WAS APPLIED.
