### ISSUE TITLE
Cabal Assassin spawns in Shadow Labyrinth

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1020]
Only saw two Cabal Assassins while clearing the room the second boss is in. Fairly sure this is inaccurate to how it worked at launch. I could not find any videos from the relevant period but I have found some more information that gives some insight about how they appeared to work.

2.1.0 test realm notes that say http://web.archive.org/web/20070306012912/http://www.wow-europe.com/en/info/underdev/testrealm.html:
Shadow Labyrinth
- Reduced the chance of Cabal Assassin ambush

WoW Wiki also notes them spawning more the longer you take http://wowwiki.wikia.com/Shadow_Labyrinth:
"Spawns during the pulls prior to Blackheart the Inciter. Assassins appear to spawn periodically; the longer you spend in the entry to Blackheart's room, the more times you will see them spawn. There are reports of them spawning two at a time on occasion."

They were also renowned for killing cloth users http://www.wowhead.com/npc=18636/cabal-assassin#comments

Interestingly the maps for wowhead and wowdb show them being found in the corridor leading up to the first boss as well: 
- http://www.wowhead.com/npc=18636/cabal-assassin#comments
- http://www.wowdb.com/npcs/18636-cabal-assassin

My guess at how it worked is that there was a random spawn timer, that begins when you kill the first boss and when they spawn they follow from the entrance to the room of the first boss in to the second bosses room. This would establish their apparent bias towards cloth users as they would often stand back during the pull and be the first players encountered as they patrol towards the second boss. My guess is that the timer was somewhere in the range of 2-5 minutes since you would often encounter them during the first couple of pulls, and sometimes multiple ones before having cleared the centre of the room.

I'm also fairly sure there were assassins set to patrol the left and right hand sides of the doors since when I tanked the heroic I would check near the rocks on either side to bait them out and try and prevent them from killing the casters during the fight. By this reasoning I think it's unlikely the first bosses room was the only spawn point since they would have attacked the casters on the way in. So it's likely there were either static spawns inside the second room or perhaps they were randomly timed spawns in the second room as well. I'm slightly biassed towards saying that the ones to the sides were static spawns since it was very rare that I would encounter multiple assassins in a single fight (I'm thinking perhaps this is due to the fact I would check for the ones at the sides first).

Also, since I would run on to the rocks to the left and right hand side of the door to check for them, this would mean that I would have had to have cleared the pulls to the left and right hand sides of the centre of the room to check. Making me think they don't patrol to close to the doorway of the room.

Sorry for going in to so much detail on the subject, but I remember the room being a pain even with decently geared people due to random clothie deaths. I want the citizens of corecraft to know my pain!

**Comment by ghost** [comment]
Made a quick sketch of how I think it worked

http://i.imgur.com/4oAJopd.jpg

**Comment by ccnim** [comment]
That's more or less how it's working at the moment.
