### ISSUE TITLE
Mages being able to move and cast in Ice block

### ISSUE THREAD

**Issue by brum21** [ccshiro/cc-buglist#1026]
I encountered a bug while dueling a warrior on my mage. I Ice blocked and accidentally casted spellsteal directly after and it let me move around and cast while I was still in the Ice Block effect. The warrior couldn't damage me while this persisted. I am trying to reproduce this bug and get footage of it. I'll report back with any updates.

**Comment by sverkersham** [comment]
Probably connected to the CC bugs. If you're stunned and get cycloned for example you can move around and cast, same with fear, roots, disorients etc.

**Comment by Ickler** [comment]
Yeah double CC is bugged, I think it was presumed fixed. But something happened I suppose. But this is connected to it, as Iceblock is considered a loss of control over character.

**Comment by Ensipid** [comment]
Occurs due to a movegen bug regarding stuns #1009
