### ISSUE TITLE
Doomsayer Jurim drops no loot

### ISSUE THREAD

**Issue by MorbidMike** [ccshiro/cc-buglist#1027]
Doomsayer Jurim dropped no loot when I killed him.
NPC: http://www.wowhead.com/npc=18686/doomsayer-jurim#comments
He should have a 100% chance to drop a blue.

From Wowhead:
JyL1 on 2007/07/14 (Patch 2.1.3)
Has a 100% chance to drop a blue. Should be 1/4 chance for each armor type, but for some reason it seems he drops mail more and cloth less. An interesting fight if not a little easy. Just pretend he's a warlock player and fight accordingly. Somewhat easier than a human target since he doesn't move, just stands and casts. Be ready to break fear and interrupt his shadow bolts if you can, which deal around 900 damage. Other than that there's not much to it, I don't think he ever melees, maybe if he's fully silenced.

**Comment by PatchnotesTBC** [comment]
Added in patch 2.2.0

he should not even be ingame

**Comment by Leprechaunius** [comment]
@PatchnotesTBC Patch

**Comment by mdindoffer** [comment]
@PatchnotesTBC that's BS, don't rely on wowhead data, it is incorrect a lot of times. If you look at stacks's comment, it is from 2.0.6 period.

**Comment by MorbidMike** [comment]
When trying to reproduce you might want to try this with a pet class. I could not find who did the "killing blow" in the combat log, perhaps it was my pet that got the killing blow and this disabled the loot, or perhaps this mob has some mechanic that makes it damage itself, killing itself and thereby not granting loot.
![wowscrnshot_070715_122903](https://cloud.githubusercontent.com/assets/2880791/8568121/3b1cd8d0-256b-11e5-8fa0-d024d158283d.jpg)
Included is my screenshot of the dead mob, unable to be looted, and a small portion of the combat log.

**Comment by ccnim** [comment]
We have an implementation that makes it so if the pet(or guard for example) does >50% damage you get no loot or experience, however we got a report saying that it shouldn't work like this for pets. Basically this is the "bug" you are experiencing.

I do believe that this will be removed next test and as long as you've hit the unit that your pet is attacking you will be able to get loot.
