### ISSUE TITLE
Void Star Talisman Warlock Class Trinket

### ISSUE THREAD

**Issue by MorbidMike** [ccshiro/cc-buglist#1028]
The Void Star Talisman (http://www.wowhead.com/item=30449/void-star-talisman#comments) does not function properly. 
Currently, each time your pet "appears" the 130 Resistance bonus is removed. The actions I could find that break the Resistance bonus are: relogging, resummoning (during and out of combat), and mounting/dismounting (this includes Flight Paths). Each time your pet "reappears" the Void Star Talisman must be re-equipped to gain the 130 Resistance bonus.
This is particularly bad during raids, since if your pet dies and you must resummon it in combat, it will not get the bonus resistance and the VST cannot be re-equipped until out of combat.

**Comment by ccshiro** [comment]
This item was fixed a while back, fix apparently broke in the grid rewrite.
