### ISSUE TITLE
No NPCs in Blackwind Valley 

### ISSUE THREAD

**Issue by HorneTheThird** [ccshiro/cc-buglist#1029]
There doesn't seem to be any NPCs in Blackwind Landing
Pic: http://i.imgur.com/HDBh9Qp.jpg
Retail*: http://vignette4.wikia.nocookie.net/wowwiki/images/f/f6/Blackwind_Landing.jpg/revision/latest?cb=20070528094954

Cheers

**Comment by lynxzor** [comment]
Because Skyguard content wasn't available at launch.
