### ISSUE TITLE
Missing Arena Popup ending in 1v2

### ISSUE THREAD

**Issue by Bugreporta** [ccshiro/cc-buglist#103]
Bug occurs when this happens:

I Queue up as the leader right after we finish a match where my partner is about to get out of the arena we just finished. 
If the queue finds a game for us immediately, usually around 0-2 seconds right after i queue,
my partner will not receive the popup for the game, (at this point my partner is still leaving the previous arena game, while i receive the invite for the game). When this occurs my partner does not get invited to the game. (He hears the sound but does not receive the invite) Ending up in a 1v2.

Tested this quite a few times, happened several times

**Comment by Bugreporta** [comment]
I'd imagine this could occur for 3v3 and 5v5 aswell

**Comment by Iliana-sc** [comment]
Does this happen on rated and skirmish or did you only try one of the two?

**Comment by Bugreporta** [comment]
Rated, could imagine this being a problem in skirmish aswell havent tested

**Comment by DaRealBoss** [comment]
Pretty sure that this is blizzlike. I remember this happening in retail. You're supposed to wait for your partner to get out if you want him to get the queue. Have you any evidence that suggests this isnt blizzlike?

**Comment by Bugreporta** [comment]
First of all, you aren't able to queue if your teammate is in the previous arena, which is working just as it should, you are however able to queue when they are in loading screen, that's when this bug happens.

I played arena for 1 day on Corecraft; i played arena for more then a year back in TBC, including arena tournament i don't remember ever having this issue appear several times during one day, so no this is not blizzlike,

To avoid this bug u would basicly have to ask your teammate if hes out of the loading screen after every single match u play, before u queue up, just to make sure he gets the queue for the game if it happens to pop instantly while he's still stuck in loading screen.

**Comment by Klimpb** [comment]
My memory of retail is that you couldn't queue when your partner was in the arena, but as soon as he was on the loading screen that takes him out of the arena, you were able to queue and your partner would get the queue too.

I remember this quite well because I was on a shitty pc so the loading screens took forever. When I got out of arena the pop for the next arena was already up on my screen and my partner was already in the next arena & waiting for me.

This is quite a minor bug though.
