### ISSUE TITLE
Pets lose buffs/debuffs when dismissed

### ISSUE THREAD

**Issue by Mephisto22** [ccshiro/cc-buglist#1031]
How to reproduce: Have your pet buffed or debuffed and dismiss him. Summon again and all his buffs and debuffs are lost. Tested with warlock pets, but should apply to hunter pets as well.

Proof: https://www.youtube.com/watch?v=yva7MbQy11g  0:46 

Proof 2: http://www.wowmb.net/forums/f165/17405-raiding_felguard_ssc_tk_hyjal_bt/
"Keep your resummon pet macro ready here to save your pets buffs in case pet starts taking arcane orbs AND pounding at the same time, that is too much for SP / pet to handle."

**Comment by YourNewfriend** [comment]
I did this, and it worked fine for my hunter pet with Power Word: Fortitude and Gift of the Wild.

Also, if it's actually bugged for locks: https://youtu.be/yva7MbQy11g?t=1m54s
