### ISSUE TITLE
[Eagle Eye] chaining does not work at Terrace of Light

### ISSUE THREAD

**Issue by mdindoffer** [ccshiro/cc-buglist#1032]
Back in the TBC days (not sure if still), hunters could chain Eagle eye spell. This allowed them to see behind corners ("override" original los) and aim it at very long distances.
All you need is a simple macro /cast !eagle eye, but here on CC it doesn't ignore original Point of view (and therefore you can't cast it around corners etc.).
Proof:
1st comment on wowhead (edit 2.3.3)  http://www.wowhead.com/spell=6197/eagle-eye#comments
discussion on cata http://us.battle.net/wow/en/forum/topic/2926885698
twink guide http://wowwiki.wikia.com/Level_19_hunter_twinking_guide
reddit disc. http://www.reddit.com/r/wow/comments/25wljp/going_past_stratholmes_smoke_wall_or_how_i/

EDIT:
Allright, tested it in Hellfire, where it works just fine. It seems the problem is dependent on the location. It doesn't work at the Terrace of light in Sh.
![wowscrnshot_070715_170012](https://cloud.githubusercontent.com/assets/12681399/8549241/1076afda-24ca-11e5-991e-5aa366b0d519.jpg)

**Comment by YourNewfriend** [comment]
This happened on retail too, and it was pretty random where people could and couldn't chain vision spells like Farsight and Eagle Eye.
