### ISSUE TITLE
[Wands] Wand attack bug

### ISSUE THREAD

**Issue by lorino** [ccshiro/cc-buglist#1035]
I tested this on the wolfs and the guards in the entrance of shattrath city, there are several bugs:

When you start attacking (channeling) with the wand to an enemy, you can click at a neutral (not mob, neutral as reputation with a mob) or ally target and can shoot him regardless of if hes in range or not (havent tested in a party, but it seems it has to be in the distance you can see)
Also theres no need for the target ally or neutral to be in LoS (Line of sight) you can shoot through walls.

The only thing that it needs to be in order to shoot allies and neutral (reputations) is that the enemy target needs to be in LoS and you have to be able to shoot him with a wand.

Also I can hit the enemy with AoE's (like Psychic scream or Holy nova) but not with single target (like smite or Shadow word:Pain)

Steps I followed to reproduce it:
http://imgur.com/gallery/qeAZ9/new

**Comment by ccshiro** [comment]
duplicate #915
