### ISSUE TITLE
Taken in the Night is still partially bugged

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1037]
When you break the cocoon while staying close enough to it (~5-20 yd I guess) it works just fine, but if you stay at the big range (~30-35 yd and it's normal if you're mage) the quest credit is still not given to you.
Also, IIRC aggressive mobs spawned from the cocoons should immediately attack you.

**Comment by ccnim** [comment]
"Also, IIRC aggressive mobs spawned from the cocoons should immediately attack you." - Comments suggested otherwise so I did not implement this.

**Comment by darkcranio** [comment]
By lollash (674 – 2·6) on 2007/01/20 (Patch 2.0.5)  
If your a caster, i suggest standing as fare away from the eggs as possible. And then destroy them from there, cause if theres a mob inside. You dont have to fight it.

By Median (194 – 1·1) on 2007/01/24 (Patch 2.0.6)  
Range it down, and you wont have to fight the bad spawns!

Means they aggro normally, not aggressively.
