### ISSUE TITLE
Murkblood Plans keep dropping after you already got one.

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1038]
![wowscrnshot_070715_134218](https://cloud.githubusercontent.com/assets/5777848/8550294/6d12507e-24d8-11e5-9ff2-d414e2899e57.jpg)

**Comment by ccnim** [comment]
The plans are seen because the condition is not checked upon looting only on death.

**Comment by KimmoKM** [comment]
I'm not 100% sure they shouldn't drop if you already have the quest, but it seems to be the same issue with [Incriminating Documents](http://www.wowhead.com/quest=8482/incriminating-documents) and [Captain Kelisendra's Lost Rutters](http://www.wowhead.com/quest=8887/captain-kelisendras-lost-rutters). They drop even after you've accepted the quest.
