### ISSUE TITLE
Frostbite is bugged

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1039]
Bugged in a 'positive' way :)
When Frostbite procs and the mob becomes afflicted by the Frostbite debuff, everything works properly.
However, when the debuff fades the mob keeps staying in place like it's still Frostbitten.
Not that I don't like this bug (I really do!), but I guess it has to be fixed :)

![wowscrnshot_070715_135657](https://cloud.githubusercontent.com/assets/5777848/8550348/c0517116-24d8-11e5-8992-3295150f406d.jpg)

**Comment by Qxcr** [comment]
Seems like root abilities in general are broken in that manner #783 #819 #984.
