### ISSUE TITLE
Resting everywhere

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1043]
I don't know whether it's only a visual bug or a real one but I was having "zzz" icon at my character portrait everywhere.

![wowscrnshot_070715_134214](https://cloud.githubusercontent.com/assets/5777848/8551912/49f2a968-24e2-11e5-9496-552e37737b35.jpg)
![wowscrnshot_070715_135657](https://cloud.githubusercontent.com/assets/5777848/8551900/3b6cdc24-24e2-11e5-9656-0da73dd50896.jpg)

**Comment by Krack3n77** [comment]
This was also happening to myself in all of booty bay.

**Comment by ccshiro** [comment]
This bug was a bit strange. Hopefully I got it (in any case, can't seem to make it trigger any more), in case I didn't and it still remains please reopen this.
