### ISSUE TITLE
Controlling my MC

### ISSUE THREAD

**Issue by ebonywolf** [ccshiro/cc-buglist#1047]
in the last room of Shadow lab(heroic), The is a mind controllable mob Cabal Summoner

I mind controlled him and started casting shadowbolt, however he occasionally interrupted my actions and started to summon the dude( which is hostile even when I do it). I can cancel the summon by moving though.

Reproducing: He was constantly interruption my shadowbolt and trying to summon. And happened to all summoners I MC.

**Comment by ccshiro** [comment]
@ccnim I've fixed the bug now. However, it means that some mobs will need their AI events marked (and tested so it works) to be able to be used while possessed. Like Teron Gorefiend and Eye of Kilrog.
