### ISSUE TITLE
Shadow Sight

### ISSUE THREAD

**Issue by asdsha** [ccshiro/cc-buglist#1062]
shadow sight in the arena should be a debuff rather than buff

**Comment by ccshiro** [comment]
Shadow sight, if I remember correctly, used to do damage while active (which would likely make it a debuff). However, once the damage was removed there's no reason to assume that it was still a debuff (it's not marked as one in the spell data). So this would need supporting evidence (needs to be from after the change, patch 2.4 or later).

**Comment by acttca** [comment]
Shadow sight was changed in 2.4 from damaging over time to 5% increased damage
http://us.battle.net/wow/en/game/patch-notes/2-4-0
http://wowwiki.wikia.com/Shadow_Sight
http://wowwiki.wikia.com/Patch_2.4.0

**Comment by ceyscro** [comment]
https://www.youtube.com/watch?v=MqwDtSRL4gQ

6:26    >   Debuff

Tabard of the Shattered Sun, and no damages on the rogue = 2.4
