### ISSUE TITLE
Wrong value on Mana Tap (and Arcane Torrent?)

### ISSUE THREAD

**Issue by Hogbobson** [ccshiro/cc-buglist#1075]
So the source for correction is terrible, but I do find the listed value on mana tap to be very low. Wowwiki says it should be 50+level. Right now it says 50.

![skaermbillede 2015-08-06 22 39 10](https://cloud.githubusercontent.com/assets/13675374/9123029/276953ca-3c8d-11e5-825d-e65abb85065b.png)

http://wowwiki.wikia.com/Mana_Tap

Also arcane torrent says it replenishes 10 mana per stack of mana tap, which seems low as well - however, I have no recollection nor proof of this, and I have yet to take a screencap.
This might be merely a visual bug. I haven't had the chance to test in combat.

Should be easily found by creating a female blood elf Priest, perhaps on other types of blood elves, too.

**Comment by nz54445** [comment]
Should test it in combat, #175 might apply here. Post your findings after testing it to make sure it restores the scaled mana, if it doesn't then it should be flagged as a bug.

**Comment by Hogbobson** [comment]
In combat worked wonderfully. Three stacks restored 483 mana, and using mana tap on a mob seemed to remove ~130 mana.

Edit: 161 mana per stack. Not bad. (The math adds up too!)

**Comment by Lephidiles** [comment]
https://github.com/ccshiro/cc-buglist/issues/175

EDIT: to late
