### ISSUE TITLE
Tailoring Trainer "Snang" has wrong icon for Brown Linen Shirt

### ISSUE THREAD

**Issue by Deluge9** [ccshiro/cc-buglist#1078]
Ok, maybe not the most game breaking bug, BUT STILL:
The tailoring trainer in org called Snang teaches brown linen shirt. But the icon for said spell is that red faced placeholder guy... if you click the other tailoring trainer who also teaches brown linen shirt, the icon is the correct brown shirt icon. This bug persists even if you train the recipe.
Screenshots included. No proof has been found to support this claim, but I highly doubt it is necessary (?)

**Comment by Deluge9** [comment]
Without tailoring:
http://i.imgur.com/uD09MqY.jpg

With tailoring:
http://i.imgur.com/uipxToo.jpg

How it looks at the other tailoring trainer:
http://i.imgur.com/aN5Gq15.jpg

**Comment by ccnim** [comment]
Due to the 2.3 removing the apprentice tailors ability to teach tailoring and me not seeing them as very useful since they always stand next to a real trainer, I shall remove their ability to teach.
