### ISSUE TITLE
[BG/WSG] Death on Server Crash

### ISSUE THREAD

**Issue by nullfoxh** [ccshiro/cc-buglist#1080]
If you are in a battleground (WSG, in this case) when the server crashes, you spawn in your starting zone (eg Shadow Grave, Tirisfal Glades) and die immediately when logging back in. This happens regardless of your hearthstone location.

How to reproduce:
1. Join WSG
2. Wait for server crash
3. Log back in
4. Get ported and die

**Comment by nullfoxh** [comment]
Happened again. Combat log says I fell to my death. This time I spawned next to the battleground master in Shatt. My HS was also set to Shattrath this time, so I guess it plays a role after all.

**Comment by Doope** [comment]
I died the same way
