### ISSUE TITLE
[Quest @ Terokkar Forest] The Big Bone Worm

### ISSUE THREAD

**Issue by Sakatoro** [ccshiro/cc-buglist#1081]
I had tried this quest last test and forgot it to report.

The NPC/Worm did not spawn after we used Fumper. We tried it around 30min, but he did not spawn. Every time there spawned the gnoms. And we had 2-3 times there nothing happenend and no npc spawned, perhaps than the big elite worm should spawned.

http://www.wowhead.com/quest=10930/the-big-bone-worm#screenshots

**Comment by ccnim** [comment]
He spawned for me on the test server. He has like a 5% chance to spawn though so expect killing an average of 20 clefthoofs.
