### ISSUE TITLE
Pet casts+Stealth

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1082]
Pet casts don't get interrupted if target stealths.

How to reproduce:
Duel warlock vs rogue
Start casting seduction
Stealth once cast has started
Get seduced while stealthed

**Comment by YourNewfriend** [comment]
Are you sure that's an issue?  As far as I know, pets should still be locked on to targets that merely stealth.

**Comment by SuddenDeath** [comment]
Not a bug: https://youtu.be/EQ_rrjzYImg?t=7m18s

**Comment by Peonstomperx** [comment]
rofl ok
