### ISSUE TITLE
Falling and taking falling damage on a flying mount

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#1085]
This bug can reproduced in the following way. I get on my flying mount, fly to the bottom part of the Mechanar (or any other instance of Tempest Keep), go the the bottom point of a crystal and fly upwards along it. As some point I fall from it (without dismounting; I can't do anything when falling) and at some point I reach the "ground" in the air. When it takes longer, I get the falling damage.

Images: http://postimg.org/gallery/2qiy2qivu/9a9a10d8/

**Comment by ccnim** [comment]
This is how it works on retail as well. Your mount gets into it's ground mode and since you are now falling you can't do anything.
