### ISSUE TITLE
[ROGUE] Vile Poisons doesn't give addicional chance to resist dispel effects

### ISSUE THREAD

**Issue by CarboCorecraft** [ccshiro/cc-buglist#1086]
I think that Vile Poison is bugged (at least partially) in the way that it doesn't give addicional chance to resist dispel effects. I have specced my rogue toon 5/5 Vile Poison and should have 40% chance to resist dispel effects, but it didn't resist at all.

Tested with druid and shaman.

**Comment by Deluge9** [comment]
I can confirm this. I tried this with a 70 paladin and I could dispel Wounding Poison 100% of the time. HOWEVER Vile Poisons did seem to work on Crippling, Deadly and Mind numbing poison. It was only bugged when it came to Wounding Poison.

**Comment by Schaka** [comment]
I can confirm this, as I was the rogue testing this with Deluge9 and also noticed it during arenas.
My guess is that the spell_affect table is missing the correct, see here for the correct mask:
https://code.google.com/p/trinitycore/source/detail?r=2797d699363396c215cf5ecd603f7fae56cbc39d

**Comment by CarboCorecraft** [comment]
@Deluge9 
Thx for info, tested Crippling, Mind-numbing and Deadly Poison today with paladin and shaman (he used Cure Poison only) and these poisons appear to be correct, only Wound Poison wasn't affected by Vile poisons.
