### ISSUE TITLE
[Hunter] Scorpid poison

### ISSUE THREAD

**Issue by DaRealBoss** [ccshiro/cc-buglist#1087]
Doesn't deal dmg after the 4th and/or 5th stack is applied. Deals no dmg after the pet keeps refreshing the 5 stacks up. Tested on a target dummy and mobs.

Also not sure if this is an issue but i thought this was funny:

http://imgur.com/Y8ZveM5

Scorpid poison can be dodged? haha

**Comment by justinbeaver** [comment]
yep, stops doing dmg after 3 stacks. tested in duel
scrn: http://imgur.com/1Re7xuM
