### ISSUE TITLE
Arena Lost Before Death

### ISSUE THREAD

**Issue by Crylawns** [ccshiro/cc-buglist#1089]
A 2v2 arena skirmish ended before my character was dead. I was thrown in with a random warrior that I think was named Darts. He died and I was left facing 2 opponents. During my 2v1, the warrior either logged off or left the arena forcing the arena game to abruptly end while I still had around 75% health.

**Comment by Crylawns** [comment]
I managed to reproduce the same bug on Blade's Edge Arena (idk if this matters), and I had my partner log out while I was still fighting the other player. This caused me to lose the skirmish.

**Comment by Schaka** [comment]
I can confirm this, as I was one of the opponents. I thought you just left the arena, actually.

**Comment by nullfoxh** [comment]
To clarify, I logged out after dying, didn't test logging out while still alive. Not sure if it's relevant to the bug but wanted to throw it out there.

**Comment by Crylawns** [comment]
This bug might need to be tested in 3v3 as well as in 5v5.
