### ISSUE TITLE
Flying straight down doesn't make you automatically land

### ISSUE THREAD

**Issue by cmlord0** [ccshiro/cc-buglist#1093]
I may be wrong about this, but I believe that on live if you fly straight down, you instantaneously land. 

![corecraftbug](https://cloud.githubusercontent.com/assets/13701559/9148430/ca4b72e0-3d40-11e5-8cdf-844ef7ef1324.gif)

This can be recreated by simply flying straight down into the ground.

**Comment by ccnim** [comment]
Client side.
