### ISSUE TITLE
Blessing Of Freedom not granting immunity

### ISSUE THREAD

**Issue by Deluge9** [ccshiro/cc-buglist#1094]
Blessing of freedom seems to remove all movement impairing effects just fine, but it does NOT give you immunity for most of them.

I've been hit by Frost Nova, Hamstring and Wing clip while under the effect of Blessing Of Freedom (I've heard frost shock also works through BoF). I've tried this repeatedly with wing clip both with and without Guardian's Favor talent (increased duration). I've only tried this as lvl 70 wearing pvp gear.

I tried to replicate this with crippling poison, but it seems that Blessing Of Freedom DOES give immunity towards crippling poison as intended. Not quite sure what to make of that, but I'm sure you guys can.

LE PROOF:
http://i.imgur.com/TS4hojf.jpg

**Comment by Doope** [comment]
The slow stacking system is broken, and you are right it should remove every slow + frost nova and feral charge

**Comment by Deluge9** [comment]
To be clear, it does remove them upon being cast. It just doesn't grant immunity. So if a mage casts frost nova during your BoF time, you get frozen as if you didn't have BoF on at all.

**Comment by Deluge9** [comment]
Same bug mechanic as hunter's bestial wrath / beast within:
https://github.com/ccshiro/cc-buglist/issues/1097

**Comment by Deluge9** [comment]
Just tested it with Earthbind totem and it turns out that BoF gives immunity as it should towards it. This bug seems to be exactly the same as the Bestial wrath / Beast within bug:
https://github.com/ccshiro/cc-buglist/issues/1097
I'm thinking the fix is probably the same for both.
I'll try this out with Ornate Mithril Boots, Spider Belt and Free Action Potion, if I can get my hands on them.

**Comment by Deluge9** [comment]
Back from more testing. I made a Spider belt and some Free Action Potions, they all seem to be bugged in the same way.
Spider belt:
http://i.imgur.com/mXEMs8l.jpg
http://i.imgur.com/pDFk7sZ.jpg
As spider belt does say it only gives immunity to Immobilizing effects, I made sure to test with frost nova. I didn't get a screen shot of the buff active at the same time as frost nova, but you can see from the combat log that it is indeed bugged just like everything else.

Free Action Potion:
http://i.imgur.com/jOWzg6D.jpg
Immune to earthbind

http://i.imgur.com/2tj0R9y.jpg
Not immune to frost shock. I haven't tested it with other things like hamstring, wingclip or crippling, but I have a feeling that it's the same pattern as above.

**Comment by Schaka** [comment]
It goes give immunity to crippling poison too. So I suspect this is about not giving immunity to non-triggered roots/slows.

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/1287
