### ISSUE TITLE
(Hunter) Bestial Wrath/Beast Within

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#1097]
both can snared/slowed but can't be polymorphed while having the bestial wrath/beast withing effects.

**Comment by Deluge9** [comment]
This is probably related to the Blessing of Freedom bug, where BoF doesn't give immunity.
https://github.com/ccshiro/cc-buglist/issues/1094

I did some testing on this and it's the exact same thing. Both hunter and pet removes all movement impairing effects upon cast, but they can still be slowed or snared during the bestial wrath/beast within effect.

http://i.imgur.com/iAnglJp.jpg
http://i.imgur.com/X3LKqTN.jpg
As you can see both hunter and pet are correctly immune to my Earthbind totem effect, but they are incorrectly NOT immune to my frost shock.

**Comment by ccshiro** [comment]
Same bug as #1094.
