### ISSUE TITLE
(UI) Nameplates casting

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#1098]
the nameplate castbar seems to be completely broken you can see the spell they are casting but not the progress of it.

**Comment by Jigodian** [comment]
Happened to me. After that I clean installed TBC again and it worked fine again. It's a client side problem for sure.

**Comment by Bzmode** [comment]
ok i'll leave this open for now let shiro decide what to do with that information might help other people having the same problem I am

**Comment by Schaka** [comment]
This was a common bug during retail, where the castbar on nameplates would sometimes just break. There is even an addon around that can fix this.

**Comment by nullfoxh** [comment]
Duplicate of your other report? https://github.com/ccshiro/cc-buglist/issues/686
