### ISSUE TITLE
Ferocious bite, AP coefficient

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#11]
The AP coefficient is documented as 0.1526 on wowwiki for rank 5. Is the coefficient for AP the same for all ranks? If not, what is it for rank 6?

wowwiki link: http://www.wowwiki.com/Ferocious_Bite?oldid=1202085

**Comment by Barroth** [comment]
The scaling should be 3% attackpower scaling each combo point, leading up to 15% at 5 combopoints.

http://druid.wikispaces.com/page/diff/Druid_Game_Mechanics/26507261#Druid%20Game%20Mechanics-Scaling%20Mechanics-Melee%20abilities

Addon DrDamage: Got 3% each combopoint aswell
http://www.wowace.com/addons/dr-damage/files/29-drdamage-r78735/

If I remember right, thats already the way it works on corecraft (// Ferocious Bite in SpellEffects.cpp)

**Comment by ccshiro** [comment]
@Barroth, it keeps getting reported each test so I figured starting the research topic was just as well.

Input by Fuerrrr:
02:10 <Fuerrrr> Hi, I did some research on Ferocious Bite AP coefficient. It seems, from what I found, that the AP coefficient is same for all ranks of FB. I managed to find
                only 2 sources and both of them state that it is 0.15 (0.03 for every combo point). The first source is from second comment at
                http://druid.wikispaces.com/share/view/3390361?replyId=3405083, and the second source is from source codes for
02:10 <Fuerrrr> Druid DPS calculation at http://tangedyn.pbworks.com/w/page/19362769/DPS%20Calculator%20%28Burning%20Crusades%29 (note that there are 2 versions, one for
                level 60 and another for level 70). I hope it helps, I couldn't find anything better
03:42 <Fuerrrr> I managed to find another forum post about Ferocious Bite. Unfortunately there is no follow up to the post (whether it is correct or not) that I could find,
                and all spreadsheets in the topic are no longer available for download. Check post #564 by BurninSun at
                http://forums.elitistjerks.com/topic/16773-feral-megathread/page-29#entry532748. According to him, the AP multiplier is 0.25, but I haven't
03:42 <Fuerrrr> checked the math.

**Comment by ccshiro** [comment]
Should work correctly now. Thanks for the help guys.
