### ISSUE TITLE
Spirit of Redemption counter spell

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#110]
After being counter spell an holy spell, then getting killed, while being is SoR it's impossible to cast any heal for the time remaining of the CS, as if we didn't die. Is it normal ?

**Comment by Bearmanpig** [comment]
Wowhead comment from 3.0.3:

"I'm not sure if this is a bug or not, but in some cases if you die with a stun type debuff your spirit continues to be stunned and thus cannot heal. If the debuff lasts 20 seconds, you will not be able to do anything as it is longer than the duration of the spirit."

Reply to the above comment:

"Meggie on 2009/07/26 (Patch 3.1.3)
This also applies to counterspells, where the spirit continues to be spell locked. Considering this 'feature' exists for more than half a year I consider this purposely broken."

Also, from patch 2.3.3:

"By Aestu (24,973 – 4·34·193) on 2008/03/16 (Patch 2.3.3)
You can use Stoneform in this form if you are a dwarf.

Also, if you were counterspelled or spelllocked in human form then died, the interrupt will carry over into SoR."

Source: http://www.wowhead.com/spell=20711/spirit-of-redemption#comments:0

Seems to be working as intended :)

**Comment by r00ty-tc** [comment]
I had it happened to me a couple of times on retail. I cannot say if it was during 2.x or 3.x though. I don't think it happened for stuns etc. But any kind of silence or spell lock used to persist into SoR very annoyingly wasting a large portion of the buff.

**Comment by Bearmanpig** [comment]
I've been thinking, the 'stun' that the guy on WoWhead mentioned might be refering to pacify effects, like Gruuls shatter for instance. I can't see it happening to actual stuns like Kidney Shot or Cheap Shot, and the WoWhead post might simply be wrong on the stun part.

**Comment by ccshiro** [comment]
@Bearmanpig thank you for the research.
