### ISSUE TITLE
Infernal Is Broken

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1106]
Break down:
-Does not patrol when idle
-Bugs out when resetting after a secondary (pvp flagged) target is too close (stack both players when testing this)
-It's sometimes invisible for the summoner, but not other players

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/1197

**Comment by ccnim** [comment]
Can't reproduce the last 2 bugs.
