### ISSUE TITLE
Shadowmeld to avoid moving projectile/spell

### ISSUE THREAD

**Issue by Masu1** [ccshiro/cc-buglist#111]
I tried dueling a warlock and found that I was able to shadowmeld while a shadowbolt was moving towards me to negate the damage. Whether that should be possible or not I have no idea, haven't been able to find evidence for either claim in the past. But when I did use shadowmeld the warlock's target of me was not dropped and he was able to see me in stealth. He was also able to continue casting shadowbolts at me, but they did no damage. As soon as the warlock dropped the target of me, I would disappear.
I imagine the warlock's target should be dropped if the target goes into stealth, even if a projectile is moving towards the target.

**Comment by ccshiro** [comment]
This working sort of came along with our understanding of Vanish and travel-time spells. I do agree it sounds a bit strange from a game-play point of view, but it does make sense given our current technical understanding of it. Maybe it'd be best to actually put some research time into it, however.

**Comment by solowt** [comment]
Vanish and shadowmeld/stealth are different.

Shadowmeld and Stealth can be grouped into one category.  Neither of them negates/dodges spells/attack projectiles that are in the air.  If you stealth while a fireball is coming toward you, it will hit you and destealth you.

On the other hand, vanish does (and is supposed to) negate spells and projectiles that are in the air.  

This changed in WOTLK but I'm confident this is the correct behavior during TBC.

**Comment by solowt** [comment]
Here is evidence: http://youtu.be/7LWJBWi0zB0?t=28s

In the video, the warrior throws at the rogue, the rogue restealths, then the ranged projectile hits the rogue causing the rogue to leave stealth.

Same deal with shadowmeld.  Vanish, of course, is different.

**Comment by tedrasiel** [comment]
Also shadowmelt is only usable out of combat in BC. so it doesnt fit in the same category as vanish. dmg breaks it and shadowmelt doesnt "absorb" the dmg of a flying projectile or cast. that changed in wotlk. so this is clearly a bug :) also the target should be gone when he goes shadowmelt.

**Comment by KuroiKensai** [comment]
https://www.youtube.com/watch?v=7Vy67FWLVB4
This is video from vanilla, but you can clearly see that there is "Night Elf cant use shadow meld in combat either" in description. I dont think Blizzard changed that at BC, but we can look at patch notes to be sure. And also I clearly remember that it works just like stealth - if you are hit by projectile - it will do damage and reveal your position.

**Comment by KuroiKensai** [comment]
Got it:  Patch 3.0.2 (14-Oct-2008): Cooldown increased to 2 minutes, able to use in combat. Can no longer eat while in Shadowmeld. If you are eating and/or drinking and then Shadowmeld, you stop eating/drinking

So, verdict is: 
- Shadowmeld cant be used in combat.
- Shadowmeld doesn't allow you to dodge already flying projectiles.
- Movement or damage will cause Shadowmeld to deactivate. 
- You can eat or drink in Shadowmeld and you can Shadowmeld while eating or drinking.
- You can't cast long spells in Shadowmeld, the moment when you start will broke Shadowmeld
- When player is using Shadowmeld he disappears from another player target, including friendly one.
  (  Patch 3.1.0 (14-Apr-2009): Using this ability will no longer cause friendly players to deselect the night elf. )

**Comment by dmsolow** [comment]
The above is correct, and it goes for rogue stealth and druid prowl as well (aside from movement breaking them). These are very important things to get right for PvP.

**Comment by KuroiKensai** [comment]
Agreed, same is true for slealth mechanics.

**Comment by FurioCC** [comment]
Should deselection happen regardless even if stealthing/shadowmelding happens right in front of you and you see  stealthied person through stealth? Or due to level difference?

**Comment by tedrasiel** [comment]
yes it should. if u still can see him u have to retarget him manually.

**Comment by ccshiro** [comment]
@dutifulbetatester That video proves it pretty clearly. Thanks.
