### ISSUE TITLE
Trade Chat Is Visible From Everywhere

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1110]
![image](https://cloud.githubusercontent.com/assets/13057166/9149044/3c06c5c0-3d4a-11e5-8da5-c37305d0792f.png)

**Comment by ccshiro** [comment]
Not a bug. Here's a screenshot from current retail showing the exact same behavior: http://i.imgur.com/LZZ01Y9.png

EDIT: Nvm, I should've expanded the screenshot, you're actually getting trade messages? That's odd.
