### ISSUE TITLE
[Druid] Healing touch rank 3 and lower is healing double what it should be

### ISSUE THREAD

**Issue by venturafonso** [ccshiro/cc-buglist#1116]
So i was testing downranking when I noticed rank 3 and 4 of healing touch are healing about the same, and i believe this to be completely broken.

Rank 3 HT : 100 mana, 2.5s cast time - 195-243 base healing

5 casts average heal: 
![2015-08-08_10-55-41](https://cloud.githubusercontent.com/assets/7500708/9149998/3ba24ab0-3dbc-11e5-9890-6d180493d02a.jpg)

Rank 4 HT: 168 mana, 3s cast time - 363-445 base healing

5 casts average heal:
![2015-08-08_10-56-18](https://cloud.githubusercontent.com/assets/7500708/9150004/4c44e6d4-3dbc-11e5-8365-2f408fa46c05.jpg)

Just by looking at this it's more than obvious something is not correct, the addon i am using for the tooltip(drdamage) predicts the exact values of every other healing spell correctly other than rank 3 and lower healing touch & rejuvenation, as you can see it's predicting that the value of HT 3 should be about half of HT 4, which sounds pretty right to me.

I am almost sure the problem lies with the healing coefficient of the lower ranks, talents don't seem to affect anything(i tested with and without talents) and it made no difference.

When i tested with my char completely naked i found that the base healing values were correct, it's only when i started adding +heal bonus that the predicted values from the addon and the actual healing value started drifting apart, hence why I think it's a wrong coefficient.

How to reproduce: make a druid, get 1000+ healing bonus

Rejuvenation suffers from the exact same problem on rank 3 and lower, probably should make a different report for that.

**Comment by matalm** [comment]
Shaman's Healing wave has the same behaviour.
Rank 1, 2 and 3 heals too much.
I compared the values i got on the test server with the correct ones from this guide: 
http://web.archive.org/web/20080913121625/http://elitistjerks.com/f47/t24796-shaman_restoration/

Rank 4 and above seems correct.

**Comment by Qxcr** [comment]
Can also confirm the issue for Priest's Lesser Healing Ranks aswell as Renew Rank 1 and 2.

**Comment by YourNewfriend** [comment]
http://wowwiki.wikia.com/wiki/Downranking

**Comment by Kall-DestinyAwaits** [comment]
I done some calc how it suppose to work [but im not sure i done it correctly]:
Healing bonus 1000

Casting time:
Healing Touch rank 3: 2.5s cast time [base]
Healing Touch rank 4: 3s cast time [base]

Healing bonus coefficient:
Healing Touch Rank 3: 2,5/3,5 = 0,714 
Healing Touch Rank 4: 3/3,5 = 0,857

So if you have 1000 Healing bonus you will get:
Healing Touch Rank 3: 1000 \* 0,714=714 Healing bonus
Healing Touch Rank 4: 1000 \* 0,857=857 Healing bonus
Healing Touch Rank 3: 1200 \* 0,714= 856 [with talent Empowered Touch 2/2]
Healing Touch Rank 4: 1200 \* 0,857= 1028 [with talent Empowered Touch 2/2]

Healing bonus penalty:
Healing Touch Rank 3 you can learn at lvl 14
Healing Touch Rank 4 you can learn at lvl 20

Calculation:
sLvl = Level that the rank of this spell can first be learned
cLvl = Caster's Current Level
Downranking Multiplier = Min(1, (sLvL + 6) / cLvl) 

Healing Touch Rank 3: (14 + 6) / 70 = 0,285
Healing Touch Rank 4: (20 + 6) / 70 = 0,371

Final ammounts of healing bonus with penalty
Healing Touch Rank 3: 714 \* 0,285 = 204
Healing Touch Rank 4: 857 \* 0,371 = 318
Healing Touch Rank 3: 856 \* 0,285 = 244 [with talent Empowered Touch 2/2]
Healing Touch Rank 4: 1028 \* 0,371 = 382  [with talent Empowered Touch 2/2]

Final amount of healing with 1000 healing bonus [without 5/5 Gift of Nature]:
Healing Touch Rank 3: 195-243 + 204 = 399-  447
Healing Touch Rank 4: 363-445 + 318 = 681-763
Healing Touch Rank 3: 195-243 + 244 = 439-487 [with talent Empowered Touch 2/2]
Healing Touch Rank 4: 363-445 +382 = 745-827 [with talent Empowered Touch 2/2]

Final amount of healing with 1000 healing bonus [with 5/5 Gift of Nature]:
Healing Touch Rank 3: 399-447 \* 1,1 = 439-491
Healing Touch Rank 4: 681-763 \* 1,1 = 749-839
Healing Touch Rank 3: 439-487 \* 1,1 = 483-536 [with talent Empowered Touch 2/2]
Healing Touch Rank 4: 745-827 \* 1,1 = 819-909 [with talent Empowered Touch 2/2]
