### ISSUE TITLE
[WSG] The "Recently Dropped Flag" debuff is present

### ISSUE THREAD

**Issue by venturafonso** [ccshiro/cc-buglist#1117]
In this https://www.worldofcorecraft.com/content/alterac-valley-battlegrounds-our-plans blogpost:

"There are two changes in Warsong Gulch that has changed the tactical play of it. One is the fact that some time after the flag is picked up, its position is displayed on the map. The other is that you can't repick a flag you dropped for 3 seconds. Both these changes we think have made the battleground worse, and our current plan is to not implement them."

As it stands, you get the mentioned debuff and cannot pick a flag for 3 seconds after you drop it, not sure if you have changed your stance on this but thought i should report it.

**Comment by Klimpb** [comment]
Would be nice if someone could confirm if it's the same case for the EotS flag.

**Comment by YourNewfriend** [comment]
Does EoTS even have an original iteration without this mechanic
