### ISSUE TITLE
Paladin - Blessing of Protection - Immune to some spells

### ISSUE THREAD

**Issue by Jonssown** [ccshiro/cc-buglist#1123]
A Paladin with BoP shouldn't be immune to Blind, which is the case in the current build.

**Comment by Doope** [comment]
Working as intended

**Comment by Stoffetest** [comment]
No, that's a bug.

**Comment by Jonssown** [comment]
Wowwiki aint the best source, but here we go: http://wowwiki.wikia.com/wiki/Talk:Blessing_of_Protection

**Comment by Doope** [comment]
Im 100% sure its not a bug

**Comment by DarkenRal** [comment]
@Jonssown , you forgot that blind was changed from poison to physical attack in 2.3.0 patch:

> Blind is now a physical (no longer a poison) attack. Reagent requirement removed. Now shares the same diminish category as Cyclone and is now diminished in PvE as well as PvP.

http://wowwiki.wikia.com/wiki/Patch_2.3.0#Rogues _(Release (US) 13 November 2007)_

And in your link the date is _07:37, 20 July 2007 (UTC)_
