### ISSUE TITLE
Facing issues for Ambush & Backstab

### ISSUE THREAD

**Issue by Stoffetest** [ccshiro/cc-buglist#1124]
Backstab and Ambush is impossible to perform at times, telling me I have to be behind the target even if I am. This happened in Warsong Gulch, on several occasions. Dunno whether this is due to server lag or bugged mechanics.

**Comment by ccshiro** [comment]
A video would work good as reproduction steps.

**Comment by ccshiro** [comment]
Probably same issue as was affecting #1980.
