### ISSUE TITLE
[Rogue] Distorted distract's aoe

### ISSUE THREAD

**Issue by CarboCorecraft** [ccshiro/cc-buglist#1125]
The rogue spell distract has an aoe range, which is distorted depending on whether it's cast on a flat ground or on a hilly ground.

Example No 1 (hilly ground):

![wowscrnshot_080815_134404](https://cloud.githubusercontent.com/assets/13622223/9150398/eb9c0dba-3dd6-11e5-8e5f-c2c60477b66b.jpg)

![wowscrnshot_080815_134427](https://cloud.githubusercontent.com/assets/13622223/9150399/f3ddecc8-3dd6-11e5-9287-f3215d47535e.jpg)

Example No 2 (slightly bumpy ground):

![wowscrnshot_080815_134438](https://cloud.githubusercontent.com/assets/13622223/9150411/c22d14fa-3dd7-11e5-800c-651ed2d06202.jpg)

But even on slightly bumpy grounds i was able to find areas where distract's aoe was correct:

![wowscrnshot_080815_134453](https://cloud.githubusercontent.com/assets/13622223/9150417/df089036-3dd7-11e5-829e-4f00a0c59817.jpg)

If a rogue casts distract on someone's toon standing in the distorted part of distract's aoe, that toon will not be affected by distract spell.

**Comment by ccnim** [comment]
Works fine, the visual is client side.
