### ISSUE TITLE
Negraton quest event

### ISSUE THREAD

**Issue by zoofCC** [ccshiro/cc-buglist#113]
Negatron is a level 69 elite fel reaver from the quest [You, Robot]:
http://www.wowhead.com/quest=10248/you-robot
When you fail at this quest(by getting killed or not engaging him) he climbs his way up to Area52 where he is supposed to try to destroy the giant rocket that is located at this town. 

Doing this quest in the test server and failing it, makes this mob go to area52 till he reaches one point where he stops his running(A) and teleports next to the rocket inside the village(B). Besides this malcfunctioning, guards dont attack him.
http://oi59.tinypic.com/2wcef4p.jpg
http://oi62.tinypic.com/2qics46.jpg

Correct scripting:  He should walk all the way to the rocket and there, start attacking the guards that try to kill him.

**Comment by ccnim** [comment]
This is actually correct he even has an animation for it.
