### ISSUE TITLE
Nameplate castbar

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1131]
![wowscrnshot_080815_174242](https://cloud.githubusercontent.com/assets/12783794/9151069/7bd00b3e-3df5-11e5-84ac-22532a72f221.jpg)
![wowscrnshot_080815_174304](https://cloud.githubusercontent.com/assets/12783794/9151068/7bced962-3df5-11e5-89ec-cd8cb182db15.jpg)
![wowscrnshot_080815_174315](https://cloud.githubusercontent.com/assets/12783794/9151070/7bd270cc-3df5-11e5-98dd-b9d3882f5b79.jpg)

**Comment by ccnim** [comment]
#686 duplicate
