### ISSUE TITLE
Mage immune (to stun) after Blink

### ISSUE THREAD

**Issue by ceyscro** [ccshiro/cc-buglist#1142]
When a mage use his Blink ability, he's immune to all stun for few seconds.

We should be able to stun a mage directly after a transfer.

https://www.youtube.com/watch?v=Ba6Ty72eSH8
3:51 ; 5:34 ; 5:54 ; 7:17

Acrono uses cheap shot, mage blink then acrono shadowstep and kidney him, it works all the time.
On corecraft if you do that the mage will be insensible to the kidney shot.

**Comment by YourNewfriend** [comment]
You mean Blink?  Yea, I've noticed that.  For some reason, mages remain immune to whatever they should be immune to during a blink for a second or two after the blink has completed.

**Comment by darkcranio** [comment]
There is a talent for it in arcane, isn't it?

**Comment by nz54445** [comment]
@darkcranio There isn't a talent specifically for blink/stun, but there is one for reducing the % of getting hit by attacks.

According to wowiki and memory, mages can blink out of stun and are immune to stuns after blinking for < 1 second. Basically going into and coming out of blink has the stun immunity, but not for long.

@ceyscro

Did you miss? If you miss with kidney shot you shouldn't be able to stun. The miss chance lasts for 4 seconds.

**Comment by darkcranio** [comment]
Maybe it has to do with the implented delay.

**Comment by ceyscro** [comment]
Oh yeah it's Blink ofc, sorry the french word used is "Transfert". And I also correct insensible for Immune, you should understand now.

So it's not a miss, the mage have immunity to all stuns after a Blink for a little time. You can see the same issue on many other private servers.

**Comment by brndd** [comment]
Blink gives you a short 1-second buff during which you're immune to stuns, I believe. In the video you linked he stuns the mage after the buff.

Just something to keep in mind. I'm not saying there's no bug here, because I haven't tried it myself, and if they're indeed immune to stuns for more than one second then chances are it is a bug.

**Comment by ccshiro** [comment]
Blink is a 1 sec duration making you immune to stun while it's up.
