### ISSUE TITLE
Crowd Control not breaking when damage is absorbed

### ISSUE THREAD

**Issue by Schaka** [ccshiro/cc-buglist#1146]
Is: 
See title. Had a rogue blinded, while he was shielded by a priest. Some mage hit him with Cone of Cold, but Blind remained intact.

Should:
Regardless of damage being absorbed or not, crowd control should always break on damage, with the exception of random break effects like roots and fear.

**Comment by Aasamath** [comment]
About fear, with the tbc formula, fear could break on absorbed damaged.
https://www.youtube.com/watch?v=GRwGLp1fzo8   0:45 and 0:55
2 fears end prematuraly while the lock has the blue pet sacrifice shield on him.

about spells that break on damage, i found a shadow word death/sheep while the priest has his shield up. Even with the damage from swd being absorbed, the polymorph breaks.
https://youtu.be/QyTyNaiEJKs?t=82

**Comment by Evolvee** [comment]
It MUST break. Imagine Rogue blinding priest who SW:Ded into it... It must break the blind no matter if he has absorb(power word shield) or not... same with poly... tons of material on wcm (btw same with rogue in stealth with dot + absorb)--> this was changed in wotlk

**Comment by ccshiro** [comment]
This was fixed at some point it seems, but the issue not closed. Just tested on the test server and my auto attack broke blind despite priest having power word: shield on him.
