### ISSUE TITLE
[Quest] Zuluhed the Whacked - Q-mob isn't spawning

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1148]
the quest "Zuluhed the Whacked" of the Netherwing Q-chain is not working.
The Elite-mob is not spawning as you can see here:
![wowscrnshot_080815_180941](https://cloud.githubusercontent.com/assets/12044027/9152007/cf21f400-3e18-11e5-83df-5c263b5c3c3e.jpg)

it should look like that:
https://www.youtube.com/watch?v=dBK3JRLr08Y

**Comment by shadowraider** [comment]
in private servers i think he is spawning on the the left wall on the very edge, have you tried to /target him ?

**Comment by Peter1337** [comment]
oh damn you're right :+1: . couldn't see him because he spawned inside a mob and no emoticons e.g. were shown:
![wowscrnshot_080915_085004](https://cloud.githubusercontent.com/assets/12044027/9153849/f1d21420-3e73-11e5-96f1-9faa8de5ab6e.jpg)

/closed

**Comment by ccnim** [comment]
#738
