### ISSUE TITLE
Prayer of Spirit doesn't override Divine Spirit

### ISSUE THREAD

**Issue by rylaiii** [ccshiro/cc-buglist#115]
here are some images of it working correctly(Image1) and it working incorrectly(Image2).
i did make sure to use the corresponding ranks.
https://imgur.com/a/poUz6

**Comment by Iliana-sc** [comment]
Was able to confirm this.

**Comment by Lephidiles** [comment]
the prayer of sprit is cast over Divine Sprit. but the buff is not updated (you do not get an error message casting this way as you do the other way)

**Comment by ccshiro** [comment]
@ccnim spell_chain is wrong for these spells (note: check other AoE buffs too in case they have the same stuff).

**Comment by ccnim** [comment]
Corrected the spell_chain but you cannot override Prayer of Spirit rank 1 with Divine Spirit rank 5.
