### ISSUE TITLE
rest paladin blessing of freedom bug

### ISSUE THREAD

**Issue by chhayra** [ccshiro/cc-buglist#1163]
the bug is while under the effect blessing of freedom if i get slowing effect it wil still slow me is a bug i shouldt be immune to snares and slowing effects while under the effect of blessing of freedom

**Comment by Deluge9** [comment]
https://github.com/ccshiro/cc-buglist/issues/1094

**Comment by Deluge9** [comment]
Same post as https://github.com/ccshiro/cc-buglist/issues/1094
