### ISSUE TITLE
Can't use trinket when some specific CCs overlap

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1166]
https://www.youtube.com/watch?v=PQ0EHbIMdXQ&hd=1

Only one I've noticed so far is gauge & blind

**Comment by nullfoxh** [comment]
Can confirm. Happened twice to me in BGs.
Think I was feared and gouged one of the times.

**Comment by Peter1337** [comment]
i can confirm it too. though i use the macro "/cast [exists, harm] Medallion of the Alliance"
happened ~5 times in BGs

**Comment by Peonstomperx** [comment]
just happened with nova+poly for me in skirmish

**Comment by Klimpb** [comment]
Seem to be fixed
