### ISSUE TITLE
[Hunter] Pet spawns after player dies

### ISSUE THREAD

**Issue by nullfoxh** [ccshiro/cc-buglist#1171]
If you kill a mounted hunter his pet will spawn once the hunter dies (at the same time dismounting).
The pet will remain until hunter releases or it gets killed.

Happened twice in WSG, might be related to the hunter being stunned as he was stunned both times.
![wowscrnshot_080915_032553](https://cloud.githubusercontent.com/assets/12772977/9152946/406f9e2c-3e47-11e5-8768-c452f7ef678c.jpg)

**Comment by Johe123** [comment]
ill come again on hunter try without stuns while mounted
