### ISSUE TITLE
Hunter Pet issues

### ISSUE THREAD

**Issue by Johe123** [ccshiro/cc-buglist#1172]
When killed while mounted my pet appears and then runs off to attack people.
Should despawn on my death.
Pet correctly despawns when i am killed while not mounted.

Pet name coming up as unknown. Emotes use its correct name and other players can see its name.

**Comment by nullfoxh** [comment]
Hi! I posted this same bug 5 seconds before you :)
So we have duplicates :)
https://github.com/ccshiro/cc-buglist/issues/1171

**Comment by Johe123** [comment]
duplicate closed :D
