### ISSUE TITLE
Scarlet Monastery Cathedral - Mograine - Whole room does not pull

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1176]
Problem: When Mograine is pulled in Scarlet Monastery, the whole room does not pull with him.

MISC NOTE: When the priest aggros after Mograines' death, she sometimes will go back into her room and de-aggro if the players are not close enough to her. She should run into battle no matter where the players are (even if Mograine dies at the start of the instance, for example).

How to reproduce: Attack Mograine.
Solution: Tether all mobs in that room to him.
Proof: http://www.twitch.tv/hatefiend/c/7017088?t=6m02s
Burning crusade proof: https://youtu.be/EN7KfJ7ZKXc?t=344

**Comment by ccshiro** [comment]
Will be fixed when #397 is resolved.
