### ISSUE TITLE
Seal of command can be dodged, parried, blocked. 

### ISSUE THREAD

**Issue by kamil87** [ccshiro/cc-buglist#1177]
Seal of command shouldn't be able to be dodged or parried or blocked as of patch 1.3 
http://wowwiki.wikia.com/wiki/Patch_1.3.0
 [Seal of Command] - The damage effects can now be resisted instead of dodged, blocked, or parried.
![wowscrnshot_080815_200014](https://cloud.githubusercontent.com/assets/13708928/9153164/72614404-3e14-11e5-8238-8dc627c0a6d0.jpg)
Here you can see the rogue dodging my seal of command. SoC can be resisted but can't be dodged blocked or parried.

**Comment by Doppelmoral** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2705#issuecomment-16786893

Can be locked.

**Comment by ccshiro** [comment]
Wowwiki is referencing a change that never went through.

You can see the patch notes wowwiki is referencing here (notice that these are notes for some development version that lies between 1.2.4 and 1.3.0 and was never live):
https://web.archive.org/web/20071221213919/http://www.worldofwarcraft.com/patchnotes/patch-05-03-04.html

To quote the paladin part:

> Paladin
> - Training costs adjusted. Total training cost was decreased.
> - Seal of Command - The damage effects can now be resisted instead of dodged, blocked, or parried.
> - Blessing of Protection - Now castable on all raid targets.
> - Blessing of Sacrifice - Now castable on all raid targets.
> - Blessing of Salvation - Now castable on all raid targets.
> - Divine Intervention - Now castable on all raid targets.

That change never got pushed to live, however, and if you read your Patch.txt (which have all patch notes pushed to the live server), you see that Paladin for 1.3.0 got these changes:

> Paladin
> - Training costs adjusted. Total training cost was decreased.
> - Blessing of Protection - Now castable on all raid targets.
> - Blessing of Sacrifice - Now castable on all raid targets.
> - Blessing of Salvation - Now castable on all raid targets.
> - Divine Intervention - Now castable on all raid targets.

The Seal of Command change was abandoned and never made live.

There are also plenty of sources stating how it can be dodged, parried and blocked, one such source being: http://wowwiki.wikia.com/wiki/Seal_of_Command_%28old%29?oldid=1400971 Which says:

> The actual attack made when Seal of Command procs is resolved as a separate melee special-attack that deals holy damage. It is resolved identically to any Instant Attack -- it can miss, be dodged, be parried, and be blocked, and will do double damage on a crit (rather than 1.5x damage as a normal spell crit would).
