### ISSUE TITLE
Shattrath City Peacekeeper halfway in the ground

### ISSUE THREAD

**Issue by Deluge9** [ccshiro/cc-buglist#1178]
I aggro'ed the Shattrath City Peacekeepers and when they returned from chasing me, they had chopped off the legs of their elephants in pure anger. I will not stand for this animal cruelty! Please fire these guards and restore the elephants' legs immediately!
Reproduce: Aggro the guards. Run away. When they return they look like this.
http://i.imgur.com/slzgazC.jpg

**Comment by Deluge9** [comment]
Update: I found out that the guards doesn't fall into the ground by themselves, you have to run far enough away from them, to be out of your render distance. When you run back to them, they can fall into the ground. I managed to make another guard do it as well, and I had another player confirm that it wasn't just my screen seeing things:
http://i.imgur.com/KnpEZqF.jpg

These guards were both standing completely normal before I made them run after me, now one of them is in the ground. They still act normal, it just looks stupid:
http://i.imgur.com/VvVdZni.jpg

**Comment by nz54445** [comment]
Probably related to #204, seems like an identical problem.

**Comment by ConfusedCC** [comment]
![wowscrnshot_080915_150151](https://cloud.githubusercontent.com/assets/10581981/9154972/cffae4d8-3ea7-11e5-8b04-452155146e70.jpg)
![wowscrnshot_080915_150152](https://cloud.githubusercontent.com/assets/10581981/9154971/cffa79f8-3ea7-11e5-8d3b-211e99066b6e.jpg)

i followed the recepie and pulled the guards away with a aggroed mob, then ran until end of render distance, when i returned they where sunk into the ground. 

I left a seccond character to observe what happened at their original position and for that character all seems normal until i log out and in with that char
![wowscrnshot_080915_150821](https://cloud.githubusercontent.com/assets/10581981/9154990/9408417c-3ea8-11e5-935a-d22fde25197a.jpg)
