### ISSUE TITLE
Quest bugs, "The Force of Neltharaku" and "Zuluhed the Whacked"

### ISSUE THREAD

**Issue by Goldenhand14** [ccshiro/cc-buglist#118]
While I was attempting to complete the Netherwing faction prequests I noticed several issue with two of the quests in the chain.

The first "The Force of Neltharaku" has two distinct issues, one that I feel is a bug (not how I remember it to be) and one which is definitely a bug.

The first issue is that after using the provided quest item (Enchanted Nethervine Crystal) which in my recollection should make the drakes immediately fly away, the freed drakes will instead attack anything in the immediate vicinity. This cause two problems, one is that any other drakes which the first drake engages will be unaffected by the crystal, and the second is that this engagement allows the cooldown timer on the crystal to run out, letting you use it more than once on the same drake and getting credit for having freed a drake every time despite only using freeing one drake, the credit for using the crystal is only given after the drake has stopped fighting other mobs and starts flying away.

The second issue, which is definitely a bug, is that the drake do not despawn and disappear once you free them, instead they will start flying away, and once they reach the point at which they should despawn they instead return to the ground, staying friendly to you and never ever going away (I've been staring at one for 30 minutes at this point, Screenshot: http://pbrd.co/1KSWCOR) unless they are within aggro range of enough other mobs to get killed that way.

The second to last quest in the chain "Zuluhed the Whacked" is also bugged. When you accept the quest Zuluhed is meant to come flying onto the ground, hold a short speech and then start an event.

Instead of doing this he simply spawns on top of this ledge (Screenshot: http://pbrd.co/1KSWKxH) and stands there for 2 or so minutes before despawning, never coming down into the courtyard and starting his event. The quest is still possible to complete, as you can attack him while he is on that ledge, but it is a rather far cry from how this encounter is meant to play out, and also a deal harder as you are in a more restricted space and you are unable to kite him between the rooms two rooms near the courtyard which is how undergeared groups in retail usually dealt with the demons he spawns.

**Comment by ccnim** [comment]
Fixed "The Force of Neltharaku". Some of the issues you mention with the quests are non-issues such as it attacking a nearby mob. Also they cannot be in combat when you tag them, this is how it is supposed to work. 

The other quest has not been implemented yet.
