### ISSUE TITLE
Charge / Intercept animation is wrong when using from a flying mount

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#1185]
Charge:
http://i.imgur.com/hrqCeB4.jpg

Intercept:
http://i.imgur.com/PZVGZqF.jpg

So you just mount up on a Flying mount get into range of a mob and press charge or Intercept and he will swim towards the target instead of running.

The animation is correct when doing this from a ground mount but not Flying mount.

**Comment by Peter1337** [comment]
The animation is correct by (female) gnomes and (male) orcs.
Did it while moving on the ground with the Rocket and while flying -> cancel Flying Mount to fall -> charge/intercept

**Comment by ccshiro** [comment]
Should be client-side, if you have proof of this actually being a bug you can reopen this issue.
