### ISSUE TITLE
Murloc loot

### ISSUE THREAD

**Issue by testiecc** [ccshiro/cc-buglist#119]
Murlocs drop clothes(linen, wool, silk etc.) murlocs shouldn't drop raw cloth materials

**Comment by Iliana-sc** [comment]
they do (at least now) according to http://www.wowhead.com/npc=171/murloc-warrior#drops:mode=
don't all humanoids drop cloth?

**Comment by testiecc** [comment]
the link you showed does not contain any clothes. I mean profession materials for example linen cloth http://www.wowhead.com/item=2589/linen-cloth
