### ISSUE TITLE
Socket Bonus Issue

### ISSUE THREAD

**Issue by Crylawns** [ccshiro/cc-buglist#1190]
I have the t5 mage leggings, and the socket bonus isn't showing up on my spell hit numbers. Take a look at these screenshots.
![wowscrnshot_080915_050717](https://cloud.githubusercontent.com/assets/13701464/9154470/9c0044a0-3e54-11e5-9534-f3a4e038f665.jpg)

![wowscrnshot_080915_050746](https://cloud.githubusercontent.com/assets/13701464/9154472/b155373e-3e54-11e5-9cb4-03be8721024e.jpg)

You can see that after refreshing my character pane, my spell hit only moves from 72-76 instead of from 72-78.

**Comment by lazermon** [comment]
The same issue (socket bonus not applying) seems to apply to Spaulders of Oblivion. Easily reproduced, correctly socket them and equip, no additional +3 hit rating is acquired.

**Comment by ccshiro** [comment]
Same issue as #1970.
