### ISSUE TITLE
NPC : Withered Giant

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#1191]
Withered Giant's (http://wowwiki.wikia.com/wiki/Withered_Giant) spell "Osmosis (http://www.wowhead.com/spell=35235/osmosis) keeps being channeled when the player gets a few yards away, but it doesn't make damage anymore.

**Comment by shadowraider** [comment]
because this is not a single target drain, this is aoe drain, you just stepped from the radius, thats why it didnt do any damage

**Comment by Whatsthis880** [comment]
You're right ! Nothing else to add, close topic
