### ISSUE TITLE
Spell casting while moving

### ISSUE THREAD

**Issue by Catfishs** [ccshiro/cc-buglist#1198]
Currently you can start moving before a spell has finished it's casting and the cast will still be successful. This is a major bug since you can start moving when the spell cast is around 50% complete and the cast will still successfully cast and land. I'm not sure if this is related to the spell delay but I'm fairly certain this wasn't possible, because currently you can start moving way before your spell has finished casting and it will still be successfully cast.

**Comment by Chulain** [comment]
did you check your latency?

was fine for me

**Comment by braide** [comment]
had the same issue.
https://dl.dropboxusercontent.com/u/66253091/Run_and_cast.mp4
