### ISSUE TITLE
NPC spreading

### ISSUE THREAD

**Issue by testiecc** [ccshiro/cc-buglist#120]
NPC's were supposed to  spread when multiple are attacking? I had 5 stacked on same spot without any movement to sides by npc's.

**Comment by FurioCC** [comment]
I do not want to sound as that guy, but when you report something as incorrect behaviour you got to prove it and provide of evidence of how it is supposed to be, instead of just throwing something and expecting developers checking it for you.

**Comment by testiecc** [comment]
you are right, but I felt like this is easy to understand. But maybe my english failed.
here is what it is supposed to be: 
https://www.youtube.com/watch?v=Ru4rDxSu7pc
and here is what I got:
http://i.imgur.com/jF590jl.jpg
There is stack of three (3)

**Comment by ccshiro** [comment]
This is an error we're aware of, and I've been wanting to fix it for quite some time now, but haven't gotten around to yet.

**Comment by ccshiro** [comment]
I intend to fix this before release, but I am unmarking it as part of the jan17 milestone as it might not be fixed before next test.

**Comment by ccshiro** [comment]
Also check out #548.

**Comment by ccshiro** [comment]
#829 is also related.

**Comment by YourNewfriend** [comment]
https://youtu.be/SwLjJH8LXfc?t=44m45s these two NPCs don't seem to care about eachother.
