### ISSUE TITLE
aggro of certain spawned mobs

### ISSUE THREAD

**Issue by Catfishs** [ccshiro/cc-buglist#1208]
Adds spawned by mobs like Raging Colossus in Hellfire Peninsula, when they get on low HP and start to shatter (spawn smaller adds), wont aggro automatically, you have to be close to them for them to actually aggro. 

Same for example with the shaman guys like Haalum in Shadowmoon Valley with the totems around him that make him immune, that have to be destroyed before you can attack him, when you destroy one of those totems using ranged attacks the adds that spawn wont aggro to you if you aren't close enough. Upon destroying them, they should aggro to the player that destroyed the totem, no matter the range, and after destroying the totems Haalum should also aggro, currently he does not. Same thing with the Raging Colossus' adds. I'm not sure if there are more mobs like that but there might be.

**Comment by ccnim** [comment]
When I did the AI for these I tested them thoroughly and noticed this behavior and specifically made it work like this. If you have evidence to prove me otherwise you can reopen this.
