### ISSUE TITLE
Falling damage after BG

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1213]
self explanatory.

Steps:
1.go BG
2.server crash
3.log in and take fall damage

![fallingdamage](https://cloud.githubusercontent.com/assets/13721369/9156710/fb2e4e4c-3ee3-11e5-98af-6b3c6b342f7f.png)

**Comment by nullfoxh** [comment]
https://github.com/ccshiro/cc-buglist/issues/1080

**Comment by ccshiro** [comment]
We fixed this, can you retry and see if it still happens? Not sure if your report is before or after we applied the fix.

**Comment by ghost** [comment]
didndt see this notification, sorry ,ill review all of them now.
this SS are from the first hours of the Test session, so probably before the fix was applied :), i will retry this later on today (if theres people) or at next test
