### ISSUE TITLE
[Dungeon] Player not being ported away

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1215]
Our tank was not ported away after server restart and dindt get "timer countdown" to be ported away.

Steps to reproduce(what we did):
1.have a party and progress through dungeon
2.at some point ask Nim to trigger a server restart for 10 minutes (time can vary, possibly)
3.when the countdown reaches 40 secs to restart, have the tank(or anyone) log out (we did this to "maybe" save instance progress)
4.server restart
5.log back in, warrior will still be inside(outside the party) with no countdown to get ported or having been ported away.
6.we then reinvited him, he said he dindt have any countdown or anything, so he proceeded to leave the group again
7.once again, the countdown dindt show up on his screen.

![notported](https://cloud.githubusercontent.com/assets/13721369/9156726/70c551be-3ee4-11e5-842d-1f4262bc4adf.png)
![notported2](https://cloud.githubusercontent.com/assets/13721369/9156727/70c762e2-3ee4-11e5-92b2-64c9c139b57e.png)
![notported3](https://cloud.githubusercontent.com/assets/13721369/9156728/70e32cca-3ee4-11e5-84c5-61ca255db2b8.png)

**Comment by ccshiro** [comment]
Looks like you're playing heroic and killed a boss already. If he was part of that he will have obtained a bind to the instance, and leave the group won't make him be ported out, since he has a permanent bind to it. Can you confirm/deny?

**Comment by ghost** [comment]
@ccshiro I can confirm this, he was part of the inst nxe the whole time, however, what would happen in case we wanted to kick a party member to invite someone else? Would the timer start of the /leaveparty is triggered by a party leader uninvite?

**Comment by ccshiro** [comment]
If he has a bind to the instance in his Raid Info there's nothing you can do to prevent him from entering, short of filling the instance so there's no more room for additional people to enter. This doesn't happen in normals, but in heroics and raids. The suggestion being; don't PUG with people you don't trust if you're doing raids.
