### ISSUE TITLE
NPC not moving in caves

### ISSUE THREAD

**Issue by testiecc** [ccshiro/cc-buglist#122]
In every cave or house I went, NPC's stood still and did not attack. Sometimes they also froze in place outside, maybe there was a tree above them or something to do with terrain I believe.
For example if I went to cold coast guarry in westfall, defias looter in the entrance freezes and other mobs aswell in the cave if I went any further.

Also I went inside kobold mine in elwyn forest and I saw one kobold FALL through levels. He fell from upstairs and aggroed other mobs on that level instance and when I got outside there was pack of 5-7 kobolds waiting for me in stack. This happened in the southernmost entrance towards river

**Comment by testiecc** [comment]
I have to specify a little, many outland caves seems to be working much better. But all vanilla caves had this bug for me.

**Comment by testiecc** [comment]
also if I remember right they worked OK first couble of hours server went online, but after awhile they bugged. Was something changed or was I lucky first time?

EDIT: yes after a restart at 17:35 gmt+2 the mobs in caves began to work once again.
EDIT2: After awhile 18:20~~ gmt+2 they started to bug in caves . Also my pet stopped following me temporarily atleast.  So again the npc's in vanilla caves bug.

**Comment by ccshiro** [comment]
Probably the same bug as reported in #92.
