### ISSUE TITLE
[Dungeon] Heroic instance auto-reseted

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1222]
So this one is a bit hard to explain, in short: We wiped, the isntance reseted itself allowing us to kill first boss twice. On the SS it can be seen that i am saved to the instance (triggered by killing the first boss) and the boss is walking (and being targeted) which suggests a reset.

note: Tank was Leader before the wipe

Steps:(what we did)
1.clear the first rooms and kill 1st boss
2.have trouble while clearing the room after (the one with all the benches and stuff)
3.wipe
4.all release except tank(lazy ass)
5.while we are corpse running, have someone leave the party, ask tank to give leader to someone else(in this case me--the healer)
6.receive leader and invite a fifth person into the part BEFORE entering the dungeon
7.go in and the instance should be reset

NOTE: we are not sure if the tank gave me leader before or after he released his spirit.

![sl reset](https://cloud.githubusercontent.com/assets/13721369/9156778/f3841224-3ee5-11e5-8be2-3338e2c72e7e.png)

**Comment by ccnim** [comment]
#1206 duplicate
