### ISSUE TITLE
[Old Hillsbrad Foothills] Incendiary bombs disappear

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1224]
If you've been a ghost, the incendiary bomb packs are removed upon entering the instance. Either by ress (after having released, thus being ghost), or by running in. We did this on Heroic, not sure about normal difficulty.

**Comment by Doope** [comment]
I reported the same thing but they said its the intended behaviour

**Comment by Chulain** [comment]
http://www.wowhead.com/item=25853/pack-of-incendiary-bombs
 on 2007/04/14 (Patch 2.0.12)
These seem to despawn from your inventory if you are rezzed. Possibly any time you wipe. So if you are recovering from a wipe, make sure you pick some up on the way into the instance.
