### ISSUE TITLE
Brazier Environmental Damage Cannot Be Absorbed

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1229]
![image](https://cloud.githubusercontent.com/assets/13057166/9157174/77c496dc-3ea8-11e5-80e4-a68c1f357407.png)

**Comment by demerda22** [comment]
Woooooooow!!!
This is such a great report! Thanks for reporting and making sure they waste even more time
with useless stuff that nobody cares.
It is because CUNTS like you that they haven't released yet.
Such a game breaking bug!

**Comment by Shakeandbake** [comment]
This bug might point towards a yet unknown bug relating to fireward having no affect to enviromental fire damage in a raid encounter we are not able to test yet. So take your shitty attitude and kill yourself with it.

**Comment by demerda22** [comment]
u maaaaaaaaaaaaad?

**Comment by demerda23** [comment]
Sometimes I browse the gay porn category

**Comment by Bloker997** [comment]
It seems, it penetrate all of the damage absorbtion spells as it also penetrate priest power shield

**Comment by Stoney21** [comment]
OMFG! WHO CARES!? Give these developers a break! This report is an inside joke for sure, people can't be that freaking stupid.

**Comment by Chulain** [comment]
stoney is a stoner :(

**Comment by Stoney21** [comment]
If you don't see the irony of this thread then there's no hope for you Chulain.

**Comment by ameliandra** [comment]
+1 for filing the small things. File everything you see and let the progs decide what is worth their time.

**Comment by ccshiro** [comment]
Wasn't a serious underlying issue, but I fixed it since I had located it anyway.
