### ISSUE TITLE
Anger Management not generating rage (until deal damage?)

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1232]
Problem: Anger Management was not generating rage even though I was in combat. When I swung at a mob, only THEN did anger management correctly function properly. 

NOTE: These mobs attacking me did not yield rage. I am pretty sure that no matter what level mobs engaged you, you'd still get rage upon being attacked. Anyone have any proof of this?

How to reproduce: get into combat without fighting back (supposed)
Solution: Make Anger Management yield rage no matter if you are attacking or not
Proof: http://www.twitch.tv/hatefiend/c/7018623
Burning crusade proof: Not needed, ability clearly is not doing what the talent says it should.

**Comment by Iliana-sc** [comment]
It's not because you haven't attacked the mob yet, it's because you had 0 rage. The talent tooltip on AM has been wrong for all of vanilla, then they tried to fix it with the release of TBC but it was still wrong.

**Comment by KevinTyrrell** [comment]
^ Do you have proof of this? Also I was not gaining rage (normally i mean, forget about AM) when attacked by enemies even when I attacked them.

**Comment by ccshiro** [comment]
Working as intended atm. Would need proof that the intended workings are wrong (the tooltip isn't sufficient enough in this case imho) -- I too remember it being like @iliana-sc says, and the tooltip was admittedly bugged.
