### ISSUE TITLE
Dressing Room Off Hand Weapon Display Issue

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1236]
I can't force a class without the necessary proficiency to equip an off hand weapon + MH at the same time in the dressing room, but I can make them equip a shield + mainhand without a hitch.

I can force a class with the necessary proficiency to equip an off hand weapon + MH in the dressing room, and I can also make them equip a shield if they don't have the proficiency for it.

![image](https://cloud.githubusercontent.com/assets/13057166/9157901/79cda8a0-3ec2-11e5-8211-a96192911d90.png)

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/1229

**Comment by RigidDirigible** [comment]
I was able to do this as both a hunter (the class the OP used) and a priest.

![wowscrnshot_081015_042545](https://cloud.githubusercontent.com/assets/13709059/9159086/c193960c-3f19-11e5-91ae-9f7b6989b01a.jpg)
![wowscrnshot_081015_043623](https://cloud.githubusercontent.com/assets/13709059/9159063/7eb4d08a-3f19-11e5-9169-5e5b14010a9d.jpg)
![wowscrnshot_081015_043741](https://cloud.githubusercontent.com/assets/13709059/9159079/a8107d44-3f19-11e5-9b07-7d7248396eae.jpg)

**Comment by YourNewfriend** [comment]
I should've been more clear.  The issue is that it's not possible to have both hands occupied like this with certain classes.

**Comment by ccshiro** [comment]
This should be client side behavior, would need proof to suggest otherwise.

**Comment by Aasamath** [comment]
Can do it on my warlock but i remember trying and failing at it a few days ago.
![wowscrnshot_090315_095245](https://cloud.githubusercontent.com/assets/13113093/9653184/e641a26c-5221-11e5-88f0-38b394278372.jpg)
