### ISSUE TITLE
Test of Endurance - Odd behavior with crates

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1238]
Problem: When approaching the crates for Test of Endurance, they respawn so quickly that clicking away all three is almost impossible. The correct mob does not spawn and the quest is just very clunky. See video for more. 
How to reproduce: shown in video
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/c/7018702
Burning crusade proof: cannot find, Joana's leveling guide does not cover this quest.

**Comment by ccshiro** [comment]
Will be fixed when #383 is resolved.
