### ISSUE TITLE
night web 

### ISSUE THREAD

**Issue by xato519** [ccshiro/cc-buglist#124]
![wowscrnshot_011715_113259](https://cloud.githubusercontent.com/assets/10579923/5791297/aa8f3aa4-9e80-11e4-9c87-eaeb7e5778d9.jpg)
went to try out the undead starting zone and noticed that spiders don't  move even after they are aggroed to you

**Comment by Iliana-sc** [comment]
duplicate of #122? Possibly others reported earlier too
