### ISSUE TITLE
[Blood Furnace] Keli'dan the Breaker trash doesn't chain aggro

### ISSUE THREAD

**Issue by Shakeandbake** [ccshiro/cc-buglist#1242]
Attacking one of the 5 casters surrounding Keli'dan should trigger all 5 to attack the player. Currently only what you hit attacks you.

**Comment by Shakeandbake** [comment]
#1339

**Comment by AT-Studio** [comment]
![wowscrnshot_082815_221313](https://cloud.githubusercontent.com/assets/13983344/9556234/890a74cc-4dd3-11e5-9e85-50e04d5a609a.jpg)

**Comment by Ickler** [comment]
This issue occurs in Normal mode too.

**Comment by venturafonso** [comment]
Did furnace heroic yesterday, they weren't linked when you pulled them and they also weren't doing that channeling animation where they make a pentagram: http://i.imgur.com/Xqya4Go.png (ss taken from a retail video).

Actual boss worked fine
