### ISSUE TITLE
[Shattered Halls] Blood Guard Porung didn't drop a Badge of Justice

### ISSUE THREAD

**Issue by RigidDirigible** [ccshiro/cc-buglist#1245]
Blood Guard Porung did not drop a Badge of Justice for any member of my party in Shattered Halls heroic.

![wowscrnshot_081015_040009](https://cloud.githubusercontent.com/assets/13709059/9158921/ca67fe1a-3f16-11e5-9ed7-7dfa0c1952e2.jpg)

**Comment by Iliana-sc** [comment]
duplicate of #1253
