### ISSUE TITLE
[Black Morass] issues

### ISSUE THREAD

**Issue by Catfishs** [ccshiro/cc-buglist#125]
All waves of mobs that spawn from the portal walk towards medivh, I remember them running towards him.

**Comment by Iliana-sc** [comment]
mobs just ignoring players unless you hit them is definitely how I remember it. not sure about walking.

**Comment by FurioCC** [comment]
https://www.youtube.com/watch?v=tn1rYHbRzVw&feature=player_detailpage#t=274
You can see mobs that spawn from portal **running** towards Medivh

**Comment by Kall-DestinyAwaits** [comment]
Yes they move to slow (walk - should run) but when you atack them they start move correctly.
Second bug is that you dont need Old Hillsbrad Thrall release chain quest to go inside Black Moras instance

**Comment by ccshiro** [comment]
@FurioCC The video is sped up. Look at the animations of the small ones (not the main mob) and you can clearly, with no doubt, see that it's using the walk animation.

**Comment by FurioCC** [comment]
I confess of sin of not doing BM on CC (if there will be one more test i swear i will, for the sake of reporting trinket not dropping off 2nd boss).
Seriously though, i just know that speed of NPC's moving to Medivh was way faster then ordinary walk speed that some of us enable for RP purposes (by default numpad "/") so i assumed issue author was referencing this type of walking in his post.
If i had to describe out of the blue the speed of spawned mobs as it supposed to be i'd say it should be slower then general character runnig speed but not by much and definitely not "general NPC walk speed".
