### ISSUE TITLE
[Dungeon] Heroic boss not dropping Badge of Justice

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1253]
Blood guard porung did not drop BoJ in HC difficulty, for anyone in the party.

steps:
1.make a party
2.advance and kill blood guard porung (second boss) 
3. loot
4.find no boj
![no boj](https://cloud.githubusercontent.com/assets/13721369/9173273/5c4d54c6-3f79-11e5-9ed5-595d9760084a.png)

**Comment by ccshiro** [comment]
Proof that it should drop: https://www.youtube.com/watch?v=PzBQx7mBJjc#t=2m15s
