### ISSUE TITLE
[Dungeon] Evade -- Shattered halls

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1255]
Mob evaded in shattered halls, self explanatory, both SS correspond to the same mob

Steps to reproduce:
1.get into the shattered halls and prodceed to gauntlet after first boss (the one between the 1st warlock boss and blood guard porung --same place where fire arrows are shot)
2.pull mobs, hide in the "holes" and jump down to the lava spaces inside those wholes
3.mobs should evade

(description of the places might seem innacurate, but looking at the SS and following the instruccitions it should be understandable -- the "holes" are right behind zwox in the first screenshot) 

![los1](https://cloud.githubusercontent.com/assets/13721369/9173461/82822a4e-3f7a-11e5-8e5b-03c8957c9cca.png)
![los2](https://cloud.githubusercontent.com/assets/13721369/9173460/82823d4a-3f7a-11e5-87e7-7d12d1c5a7ab.png)

**Comment by ccshiro** [comment]
All the lava holes seem to be pathable for me. Maybe it got fixed in some other bug. If you see it again please make a new issue.
