### ISSUE TITLE
[First Aid] Doctor Gregory Victor does not teach recipes

### ISSUE THREAD

**Issue by opzor** [ccshiro/cc-buglist#1257]
Doctor Gregory Victor does not teach recipes for Mageweave and Runecloth bandages.
When you click dialog options nothing is happening.

![dr gregory victor](https://cloud.githubusercontent.com/assets/13710937/9175517/7172aaf6-3f86-11e5-9e50-135c135afff6.png)

**Comment by lynxzor** [comment]
#1138
