### ISSUE TITLE
[NPC]Blackwind Lake Pathing/Glitch

### ISSUE THREAD

**Issue by jlavier9359** [ccshiro/cc-buglist#126]
I noticed this earlier today and recorded the behavior that some of the npc's were doing. I did attack them but that did not seem to help since they were immune. 

Here is the link:
https://www.youtube.com/watch?v=3FMYZQxCKok&feature=youtu.be

**Comment by Catfishs** [comment]
I noticed this aswell on that particular place. Also it's BlackWIND not wing lake.
