### ISSUE TITLE
[Visual] Dead mob hidden under furniture"

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1260]
The mob died and he "fell" under the furniture in the botanica, i believe he should have just died and laid down on top of the furniture

![mob escondido](https://cloud.githubusercontent.com/assets/13721369/9178024/45d94256-3f95-11e5-9f8d-3de9be608bbd.png)

![mob esconcido](https://cloud.githubusercontent.com/assets/13721369/9178016/396d7e42-3f95-11e5-8c5b-fac66c472270.png)

**Comment by ccnim** [comment]
client side
