### ISSUE TITLE
[Visual] Spirit healer can be seen after death - netherstorm

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1261]
Self explanatory, after releasing spirit from death ina  TK dungeon (we were doing botanica) you can still see the spirit healer

![spirit1](https://cloud.githubusercontent.com/assets/13721369/9178028/50b85b3a-3f95-11e5-8ca5-f768ac1b7c48.png)
![spirit2](https://cloud.githubusercontent.com/assets/13721369/9178029/50d9bf50-3f95-11e5-82cd-e8f9977a2c31.png)

**Comment by lynxzor** [comment]
#1088
