### ISSUE TITLE
Neutral AH

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#1264]
Not sure how big this bug is (if it is only alliance / horde transfere or all AH transfer)

Tried to sell an item at the neutral AH in booty bay to transfer the item to my horde. 
Was unable to buyout or bid on the item with the horde char.

Got a video of it if needed

**Comment by Iliana-sc** [comment]
What was the error? Was it that you can't buyout your own items? I don't think that's a bug, you won't be able to create characters on both sides outside of the test realm.

**Comment by ConfusedCC** [comment]
checked this now, and worked fine when using different accounts

**Comment by RigidDirigible** [comment]
Yeah, you're not supposed to be able to buy an item from the same account. You'll need a friend to transfer items cross-faction.

**Comment by Lephidiles** [comment]
i did not think of that. yes they are both on the same account
