### ISSUE TITLE
[Profession] Tailoring - Shadowcloth Missing Buff

### ISSUE THREAD

**Issue by DeeMarie** [ccshiro/cc-buglist#1267]
http://wowwiki.wikia.com/wiki/Shadoweave_Tailoring

"After crafting, the tailor will receive a "Shadowy Fortitude" buff which provides +25 stamina for one hour. "

This appears to be missing. However, the Primal Mooncloth version does grant the Moonwell Restoration buff.

(Specced as Shadowweave Tailoring)

**Comment by ccnim** [comment]
Works fine for me, did you have power word: fortitude on you perhaps?

**Comment by DeeMarie** [comment]
Yes you're right! It doesn't overwrite PW: Fort which I believe is the stronger spell. And they don't (and shouldn't) stack.
