### ISSUE TITLE
AoE Spell Range Check

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1269]
The marker turns red immediately after 30.0 yards, but spells can be casted at +1-2 yards away.  
![image](https://cloud.githubusercontent.com/assets/13057166/9185665/9df8080a-3f72-11e5-978b-33b883f9cfe1.png)

Should the marker actually turn red so early, and not match the full range of AoE spells?  I believe it makes sense for there to be some leeway in the distance, but I don't know if it should or shouldn't display on the ground as castable for the entire real range.

**Comment by Klimpb** [comment]
After a fix it seem to be the opposite now.
Sometimes the indicator will be green but it will say out of range.

**Comment by Peonstomperx** [comment]
Couldn't this be because of the hitbox granting ~2 yards tho? #2494
as in client displays 30 while server grants 32

**Comment by Klimpb** [comment]
@Peonstomperx I don't think so, AoE spells doesn't take the bounding radius into account.

**Comment by Peonstomperx** [comment]
@SuddenDeath well I mean there's a difference between the placement of the aoe and the radius of aoe

**Comment by Evolvee** [comment]
https://github.com/ccshiro/cc-buglist/issues/2158
similar

**Comment by ccshiro** [comment]
Fixed in #2158.
