### ISSUE TITLE
[Hellfire Peninsula] Quest items for "I Work...For the Horde!" sometimes bug when picked up

### ISSUE THREAD

**Issue by RigidDirigible** [ccshiro/cc-buglist#1275]
Twice while doing the quest "I Work...For the Horde!", after picking up "salvageable wood", the item not only failed to appear in my inventory, but failed to disappear from the ground for a good 10-20 seconds, remaining visible and sparkling but no longer selectable. No issue appeared with "salvageable metal".

I took a screenshot with my cursor over the object showing it not changing to the golden cog like it's supposed to over an interact-able object, forgetting cursors don't appear on screenshots, so the shot doesn't provide any proof; it just looks like I'm standing beside a normal interact-able object.

**Comment by lynxzor** [comment]
#434

**Comment by RigidDirigible** [comment]
Interesting. I guess it's both the wood and the metal, then; that fellow had the opposite problem to the one I did.
