### ISSUE TITLE
[Druid] Tranquility healing for too much

### ISSUE THREAD

**Issue by Javas-Lal** [ccshiro/cc-buglist#1281]
Current situation: Tranquility heals for roughly twice the amount it should. 
![sdfsdf](https://cloud.githubusercontent.com/assets/5626556/9187497/4a71f196-3f9f-11e5-93f9-6877c0ad0517.JPG)
It should be ticking for less than 1700 per tick at 918 healing, but it ends up ticking for more than 3k.
![sdfsd](https://cloud.githubusercontent.com/assets/5626556/9187538/efb0d3fc-3f9f-11e5-8b83-f8c05a7f421d.JPG)
Desired situation: Tranquility should tick for roughly half the amount it is now, barring Restoration talents.

**Comment by shadowraider** [comment]
Do you have any coefficient calculation to prove your statement?
I think the heal is just fine. Look at the TBC patch notes.

Patch 2.3.0 (13-Nov-2007): Tranquility now gains additional benefit from spell damage and healing bonuses.
Patch 2.0.3 (09-Jan-2007): The "Tranquility" base amount healed per second has increased by approximately 273%. The radius of effect has increased from 20 yards 30 yards. Mana cost has increased by 40%. The Cooldown has increased from 5 minutes to 10 minutes. The Duration has decreased from 10 seconds to 8 seconds.

**Comment by Javas-Lal** [comment]
The calculation is in the screenshot. Let me write it out.
(1518)(4)=6072 total healing done for Tranq rank 5.
(918 spell healing)(.762)=696.5 healing added to the spell.
(6072+696.5)/4=1692.125 - what it should be ticking for at 918 healing, as Tranq has 4 ticks for its duration.
This is from live, phase 3 of RoS has no healing reduction, and his tranq spell is ticking for 2.5k on a BT geared druid. https://youtu.be/dA4cY7VG5hQ?t=4m8s

**Comment by shadowraider** [comment]
yeah i think you are right
