### ISSUE TITLE
It's Possible To Equip Multiple Quivers

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1283]
There's only one method I've established.  They all stack +attackspeed

![image](https://cloud.githubusercontent.com/assets/13057166/9188097/25b8a9ba-3f8d-11e5-8f90-6291abf5c8b4.png)

Reproduction Guide:
Drag an equipped bag over a quiver.  It can't be done in reverse.

![image](https://cloud.githubusercontent.com/assets/13057166/9188083/f6335ece-3f8c-11e5-9269-edb3e205df97.png)

**Comment by Argonn** [comment]
This also counts for Ammo pouches. I was able to combine a Knothide Ammo Pouch with a Small Shot Pouch (same named items don't seem to work). This can only be done by moving the equiped BAG onto a pouch or quiver INSIDE an other bag!
