### ISSUE TITLE
[Vanilla?] Neutral Guards Don't Use Their Knockback Ability

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1285]
Most should knock back players at a distance.

http://www.warcraftpets.com/guides/other/bloodsail-faction/
"When fighting bruisers, you'll ideally want to engage them one-on-one at close-range. Because of their toughness, it's best to take them one at a time. Furthermore, if there are more than 20 or so yards between you and the bruiser, he'll pull out his rifle. This rifle is the bruiser's primary weapon used to neutralize "unauthorized" PvP combat in town. It quickly fires shots with a spell-interrupting knock-back effect. So if you get hit, you can be repeated knocked across Booty Bay in a matter of moments, pulling additional bruisers as you go. Thus, for most classes, when a bruiser starts firing his knock-back rifle, be prepared to meet your maker."

http://wow.gamepedia.com/Bloodsail_Buccaneers_reputation_guide
"The Bruisers have a ranged knockback attack that can be quite difficult to deal with but currently they will not use this on a player unless they can't reach them due to being on a roof or a different level of the town. They will not use it if simply rooted in place by a spell. They also use it on players that PvP in Booty Bay while at neutral or lower reputation. It is not a huge concern for normal reputation farming but one has to be careful not to aggro a Bruiser that is on a higher or lower platform as sometimes they will start shooting instead of running up to melee range."

**Comment by ccshiro** [comment]
Added a guard issues -- #1397.
