### ISSUE TITLE
[hunter] melee and ranged swing

### ISSUE THREAD

**Issue by Aasamath** [ccshiro/cc-buglist#1286]
Melee swing and ranged swing are on different timer.
Meaning you can shoot a dummy at close range, make a few steps to hit with melee weapon, then come back to range just in time for your ranged swing.
If you use 2 low speed weapon this means you can do double the damage by using both your weapon swings.
Note that for other classes the swing is shared on the server. Warrior uses throw then charges, no melee swing happening once he reaches target.

I have absolutely no idea if that's the correct behavior or not (in either case). I've seen server working like this and others where swing is common for both ranged and melee weapon. Just thought i'd put it up to discussion.

**Comment by justinbeaver** [comment]
Works as intended.

proof:
https://www.youtube.com/watch?v=usg3FLP8tlQ

hunters prefer OH with 2.6 speed, to make most possible dmg when coming in melee for wing clip, and then back to range

**Comment by Aasamath** [comment]
Ah nice :) thanks for finding that.
