### ISSUE TITLE
Killing Grey Players Doesn't Award Any Kills

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1290]
When a grey player is killed, they should at least contribute to the kill counts in the PvP tab as of the 2.0 honour system changes.

![image](https://cloud.githubusercontent.com/assets/13057166/9193206/96b62712-3fc6-11e5-90c3-a5b5faa28ce9.png)

Evidence: none yet

**Comment by Aasamath** [comment]
I don't think so since killing grey player isn't an honorable kill.

**Comment by YourNewfriend** [comment]
I can clearly remember having 13k from Elwynn Forest PKing alone in WoTLK.

**Comment by Chulain** [comment]
that doesn't make sense tho

**Comment by tedrasiel** [comment]
as far as im concerned, its honorable kills that get counted. killing a grey player isnt.

**Comment by Astixium** [comment]
http://wowwiki.wikia.com/wiki/Level
Honor, PvP & XP Edit
Gray level players do not give you any Honorable kills.

http://www.wowgold.hk/honor-guide.htm
1. Your victim's level: 
Killing a "grey" player gives no Honor

http://m.gold-shop-test.com/wk18.htm
What is an honorable kill? 
The color system for players works the same as it does for monsters. Grey level players will not yield an honorable kill.

Killing grey level players grants nothing more than a pat in the back for being an arse.

**Comment by KimmoKM** [comment]
Maybe you're thinking of achievements or statistics? What TBC shows is honorable kills only.

**Comment by Astixium** [comment]
Even the achievement needs honorable kills. 
http://www.wowhead.com/achievement=870/100000-honorable-kills

Not a single thing in WoW ever suggested that killing grey level players is healthy or even rewarding for that matter.

**Comment by ccshiro** [comment]
I consider what @Astixium linked good enough evidence to disregard this claim until it has proof backing it up.
