### ISSUE TITLE
Pet dont have abilites

### ISSUE THREAD

**Issue by Magnumspb** [ccshiro/cc-buglist#1293]
![wowscrnshot_081115_120313](https://cloud.githubusercontent.com/assets/13726581/9194113/80ec7f98-4021-11e5-97d0-ab6d157b0e24.jpg)
![wowscrnshot_081115_120454](https://cloud.githubusercontent.com/assets/13726581/9194112/80ebeb00-4021-11e5-8c6b-aa90bf57c2b1.jpg)
![wowscrnshot_081115_120501](https://cloud.githubusercontent.com/assets/13726581/9194114/80ef65d2-4021-11e5-9577-5d3cb496a108.jpg)

**Comment by YourNewfriend** [comment]
Use the beast-training menu
