### ISSUE TITLE
Stealth doesn't interrupt channeled spells.

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1296]
Drain Soul doesn't get interrupted when target stealths, couldn't find any complaints with google.

Drain Soul leaving combat is working as intended;
Cataclysm-Logo-Small Patch 4.2.0 (28-Jun-2011): It is no longer possible to leave combat while channeling Drain Soul.

**Comment by SuddenDeath** [comment]
Worth noticing is that drain life, drain mana, etc do not keep players in combat either. Not sure if it's blizzlike or not, shouldn't be too difficult to find proof.

**Comment by Aasamath** [comment]
Patch 1.10.0 Channelled spells are cancelled when a rogue vanishes
http://wowwiki.wikia.com/wiki/Patch_1.10.0http://wowwiki.wikia.com/wiki/Patch_1.10.0

**Comment by Chulain** [comment]
@Aasamath link broken btw

**Comment by ccshiro** [comment]
@Aasamath vanish already work like this. Will close as no proof was provided for stealth.
