### ISSUE TITLE
Polymorph regeneration tick

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#13]
Polymorph's regeneration was reported as too often/potent. The correct regeneration interval and % health needs to be figured out.

The below videos were linked to me by Sd:
http://youtu.be/VFTGsRMfH48?t=19m2s
http://www.warcraftmovies.com/movieview.php?id=86343 6:44 & 7:22

**Comment by Barroth** [comment]
http://www.warcraftmovies.com/movieview.php?id=55762 at 2:35 you can see the warrior going from 61% to 71% to 81%, ticking each second. you see the pala in the back is still casting his heals.

Ticks each second, confirmed via frame to frame
