### ISSUE TITLE
Hellfire NPC minons not de-aggroing

### ISSUE THREAD

**Issue by SeanTheOriginal** [ccshiro/cc-buglist#130]
Literally ran a Bleeding Hollow Skeleton from Zeth'Gor to Falcon Watch without it de-aggroing. Also had a Cursed Scarab chase me just past Broken Hill until it died.

**Comment by FurioCC** [comment]
Think it's deagroing issue with pets in general but i do not know if deagroing is correct behaviour, when  pet owner is dead.

**Comment by ccshiro** [comment]
Guardian seem to not get the evade event until owner reached home.
Also on leash evading it seems to not get it at all.
