### ISSUE TITLE
Battleground queue doesn't drop when logging out

### ISSUE THREAD

**Issue by Thraenth** [ccshiro/cc-buglist#1303]
The battleground queue doesn't drop when logging out on your character and logging back in. For example, I logged out for the night and logged in the next day to find I was still in queue for a little over 13 hours.
![wowscrnshot_081115_100829](https://cloud.githubusercontent.com/assets/3233233/9206582/b6af0c58-4036-11e5-9ed5-980c7e4a5df5.jpg)

**Comment by Peter1337** [comment]
saw this too. also, the queue does not disappear after joining and after finishing a bg.

**Comment by InvisibleJon** [comment]
Queues for other battlegrounds should not disappear when joining a battleground, I am 99% sure of this.
If that's what you implied, Peter1337.

**Comment by Chulain** [comment]
pretty sure this is intended, so you remain in queue when relogging/dcing for a short time

and im 100% sure you wouldn't drop other queues when entering a BG

**Comment by Thraenth** [comment]
For 13 hours? I sure don't remember logging off for the night and coming back the next day and still be in queue in retail TBC

**Comment by ConfusedCC** [comment]
that could be because a bg that you would have been elegible for had popped during the night, while here the chance that there is a 13 hour gap between the larger bgs is greater.
being qued while offline wont affect bgs anyhow, they only populate their lists with online players.

**Comment by tedrasiel** [comment]
As i made millions of bgs back then, it didnt drop when u relogged. It did drop when i was offline for a longer time, i dont know if either the bg i was queued in popped or if i have been removed after some unspecific amount of time. 

You dont leave the queue when joining a bg. U could switch between bgs back then, so while beeing in ws, arathi could pop and u where able to join and leave ws without getting deserter. They removed that during wrath i guess. In early wrath footage it still was like this, like in classic and bc.

**Comment by ccshiro** [comment]
Working as intended. It doesn't drop by logging out. You get removed from the queue if the queue system intended to select you, but you were ineligible (offline) at the time.
