### ISSUE TITLE
Questitem grouploot

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#1309]
Hey, I don't know if it's bugged here but as it's bugged on any other server, I want to mention that "group loot" function doesn't apply on questitems which is pretty nasty. Maybe someone can say something on that topic if it's working in here.

**Comment by Peonstomperx** [comment]
also 2 players looting quest items(has to be some speficic type of quest items I think) at the same time dupes it, fairly common on private servers if someone wants to test it

**Comment by RigidDirigible** [comment]
The two issues mentioned above also happen with Scourgestones for Argent Dawn rep on at least one server. Not a high priority for Corecraft, obviously, but worth mentioning.

It gives a very nasty privilege to melee characters, causing them to ninja loot all quest items, and definitely needs fixing as a high priority.
