### ISSUE TITLE
Not joining general of "shattrath" again

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#1311]
If u leave shattrath and enter terokkar forest and go back to shattrath, u don't join the channels that belong to shattrath like trad, general...

**Comment by ccshiro** [comment]
Works for me.

**Comment by magikalCC** [comment]
One thing that always bugs the channels for me is hearthing from a dungeon. Relogging doesn't fix it, have to wait for a server restart.

**Comment by Divinicus** [comment]
Did some testing on this.  Rode out of shatt, flew out of shatt, walked out of shat....all works.  However, I went into a Heroic, then hearthed back to shatt, and it didn't update channels.  Doing /1 brings up Terrokar General chat.  Attempting to talk says I'm not in that channel.  Screen shot attached.  Logged out and back in and I had no channels set.  Flew into Terrokar and my channels updated, back into Shatt and the channels did not update, went back to the you are not in this channel setup.  Logged out, deleted Cache folder in WoW directory.  Logged back in, same issues.  Logged into a different character on the same account and the issue does not carry over.
![untitled](https://cloud.githubusercontent.com/assets/13889021/9398136/ad09f1f8-4758-11e5-9bdf-461b08caebe0.png)

**Comment by ccshiro** [comment]
Most likely same bug as #1110, with current channel not updating correctly on area switch.
