### ISSUE TITLE
Death Coil didn't break Vanish

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1316]
Casted after vanish ofc

**Comment by justinbeaver** [comment]
Arcane Shot don't break vanish but it should.
![2_2](https://cloud.githubusercontent.com/assets/13700367/9430193/c12adffe-49a0-11e5-9942-03ba96a99cb1.jpg)
Didn't deal any damage and nothing about it in combat log, was it successful or something. Like UFO.
