### ISSUE TITLE
[Underbog] [Swamplord Musel'ek] and [Claw] major

### ISSUE THREAD

**Issue by Catfishs** [ccshiro/cc-buglist#132]
![image](https://cloud.githubusercontent.com/assets/10578563/5791713/a5ddd3be-9ef1-11e4-9b47-4943e6c9f658.png)

We were killing the Claw and Swamplord Musel'ek and Musel'ek  resetted after Musel'ek knocked our tank to the water, but Claw didn't reset and we could kill him without Musel'ek engaging us, they should both be linked to each other at all times. After that we engaged him again and Claw as transformed druid started attacking us but we couldn't attack him back.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10578563/5791721/4f30c480-9ef2-11e4-9a52-266bff828fb2.png)

**Comment by abuescher** [comment]
Can confirm this was still an issue yday (7th September) in our run. We were able to pull Claw without starting the encounter. Both should be linked to each other permanently tho.
