### ISSUE TITLE
Accented Letters Can't Be Used In Character Names

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1321]
It could be bugged for guild names too.

![image](https://cloud.githubusercontent.com/assets/13057166/9215821/c17a543e-4064-11e5-9ca3-5e38a42ef74a.png)

http://casualwow.blogspot.ca/2006/11/alt-codes.html
"Here is a table of special characters you may find useful if you ever have to type a character's name that includes a special character(s):" - March 2007

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/186597-alt-special-characters-list-of-ones-work-game.html - April 2008

**Comment by Chulain** [comment]
intended, devs said they won't have this on corecraft

on irc i believe, a while ago

**Comment by ccshiro** [comment]
This is intended.

**Comment by mdindoffer** [comment]
What? Why? I couldn't think of a reason this should stay the way it is. Don't you already have utf8 & unicode collation on the names column? Performance overhead vs ascii is insignificant. Most of the player-oriented stuff is done with the IDs anyway, isn't it?
Every other pserver I've played on supports this, doesn't seem to match with CC's philosophy.

**Comment by netherspite** [comment]
I'm happy this won't be allowed on CC. It's impossible to type /w name or /who name if 'name' contains non-ASCII characters and you're using default english keyboard layout.
Yes, I know about Shift+Click, but it's still pain in the butt if you can't type the name directly.
