### ISSUE TITLE
Intended evade mechanics while on roofs?

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1323]
Problem: This is hard to describe, but is the following evade mechanics shown in this video the intended behavior these ranged mobs should take retarding a target who is both out of line of sight and on impassible terrain (roof)?
How to reproduce: shown in video
Solution: n/a
Proof: http://www.twitch.tv/hatefiend/c/7022351
Burning crusade proof: n/a

**Comment by KevinTyrrell** [comment]
Notice how at around 1:00, I'm clearly in range of the Rifleman who is on the upper ledge but he does not shoot me.

**Comment by ccshiro** [comment]
What's looking at you from across the wall at 1 minute is a Durnholde Sentry, they're melee mobs: http://www.wowhead.com/npc=17819/durnholde-sentry#abilities
