### ISSUE TITLE
Strange audio/chat spamming from Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1324]
Problem: Grand Warlock Nethekurse yells out constantly when nearing his room. Seems very odd, the frequency and timing of some of his chat messages. Sometimes he even talks over his own chat messages.
How to reproduce: approach Grand Warlock Nethekurse's room from the sewers (perhaps from the other room as well?)
Solution: n/a
Proof: http://www.twitch.tv/hatefiend/c/7022384
Burning crusade proof: https://www.youtube.com/watch?v=PvMfIQFPPI8 (not really the correct moment), https://www.youtube.com/watch?v=HAh5irnDer8 (note here: you can see one of the minions being enhanced by the shadow spell, not sure how this interaction truly works), https://youtu.be/luwriRn_eQ8?t=59 (not sure what this video might prove, but notice how the boss doesn't yell out before they are in his room, but he went in through a different door, not the sewers)

**Comment by ccshiro** [comment]
He tortures the orc underlings as a pre-event. It's very frequent and spammy on retail, we just took the same timers they had when we made it.
