### ISSUE TITLE
[Hunters] Bestial Wrath and mount.

### ISSUE THREAD

**Issue by rsheep** [ccshiro/cc-buglist#1325]
1) Cast Bestial Wrath with your pet summoned.
2) Mount up before the buff expires.
3) Pet will disappear while mounted keeping Bestial Wrath buff.
4) Wait for Bestial Wrath buff to wear off (16s?) then Dismount.
5) Pet will reappear (it will still be enraged). Owner will gain another full-lenght Bestial Wrath buff (16s?)

You can dismount/remount/regain_buff again, till pet's buff will wear off.

**Comment by KevinTyrrell** [comment]
I do remember sometimes calling my pet on retail back in Burning Crusade and it would still be in the Bestial Wrath state because I had died before it had a chance to expire. However, this should not be giving YOU bestial wrath all over again.

**Comment by TheRaduki** [comment]
Can confirm that this isn't just limited to mounts but also dismissing your pet. Mounting and dismounting seems to spam my buffs with bestial wraths
![ont9bhw 1](https://cloud.githubusercontent.com/assets/14163268/10264771/630a3d48-6a16-11e5-91b9-1b1ed3470fbc.jpg)
