### ISSUE TITLE
Can't talk on cities' global chat channels

### ISSUE THREAD

**Issue by Tietovallu** [ccshiro/cc-buglist#1328]
As the title says I can't talk at all on global channels (general, trade, localdefense) in cities, tested in Shattrath and Orgrimmar. These channels don't show at all in the global chat channel menu of the chat window. I can see other people talk though. They are only broken on one character. All other channels including guildrecruitment, battleground and party for example and custom channels work.

Joining them doesn't give me any message, leaving doesn't either. Leaving and joining them doesn't give any message either. Global channels in non-city zones work fine though. It gives me the message that I have joined those channels when I exit a city. When I go to back to a city from a non-city zone it doesn't give me any message that I have left or joined any of those global channels. After going to a city from a non-city zone and typing "/1" for example it opens up the chat thing from that previous zone saying "[1. General - Terokkar Forest]:" but I can't write anything on the channel because I'm not in that zone.

I did /resetchat, /reloadui, deleted my WTF, Cache and Interface folders. I also relogged and exited the game multiple times obviously. Also tried it on another computer but it's the same. I read probably over 20 threads from the internet about this issue but any or a combination of those above methods have worked for people (as far as I could tell).

I honestly have no idea what might have caused this or when it happened, because I don't remember when or if I have used any of those global channels in a city. It's not really a big deal for me or to anyone because it's a test server but there might be some underlying issues or someone else might get it too. So if someone else gets this problem at least we have someone who tested everything he could think of and documented it.

I can of course do some more testing on this character if the devs think this issue warrants it.

Edit: I didn't notice the issue was closed before I referenced it.

**Comment by Tietovallu** [comment]
Just happened on my other character as well. I remember it working before I went to do an instance and when I HS'd back I noticed it didn't work. May be connected to HS somehow. Not sure though. Can't see people talk in those channels though.

**Comment by Lephidiles** [comment]
Got a simular issue although i cant see people talking in the channels either and i don't get a Joined channel [1. General - City] message when changing zone.

Like Tietovallu above i also got summoned right before this happened. although I am more inclined to think it has to do with the server still thinks you are in the channel so it does not send you a package to join the channel. as it work when you log out for a long time (if there has not been a crash as well since yesterday)

**Comment by Tietovallu** [comment]
Disregard what I said, I can see people talk in channels.

Edit: just noticed that I could see trade chat outside of cities as well, at least when this bug persists.

**Comment by ConfusedCC** [comment]
you can provoke this state by killing your connection as described in #1195

**Comment by Tietovallu** [comment]
I managed to somewhat reproduce this:
1. Go to an instance, I went to Sethekk Halls (made a new character for this)
2. HS back ( I HS'd to UD starting place)
3. General chat doesn't work in Tirisfal Glades

A thing of note was that it showed me Terokkar Forest in the chat window like in Shattrath when it was bugged for my 2 other characters (because I had to go through Terokkar to Sethekk Halls), but not Sethekk Halls. I remember instances having their own general chat channels. General, LocalDefense (and Trade) started working when I rode to Undercity and when I turned back to Tirisfall Glades it showed UC instead of Terokkar in the chat window so it's consistent with how it was bugged yesterday. One different thing is that it still shows me channels 1 and 3 in chat window general config's global channels tab like normal when the chat is bugged in Tirisfal.

On my two bugged characters it looks like this:
![globalchatchannelsbug](https://cloud.githubusercontent.com/assets/10575254/9243110/e9166768-4194-11e5-8979-8f71a806c3bc.png)

Edit: did some more testing and found out the following:
1. If a zone/channel channel glitches it will stay fucked up forever.
2. I don't think it's related to some instances not having a general channel (not implemented?), HS'd from SM (has a general channel) to UC and the chats were bugged even though they worked in UC before I went to SM.
3. It's definitely connected to teleporting. That's the only time it ever happened to me.
4. If a channel exists on both zones you're teleporting between, it won't fuck up. Remember that every General and LocalDefense channel for each zone are different channels. Portaled multiple times from Shattrath to Orgrimmar and trade chat kept working. 
5. Tested more based on 4. and I discovered that it probably only bugs when you teleport from a city or to a city. HS'd from Shattrath to Eversong woods, went to Silvermoon all chats worked all the way. Teleported to UC and Trade only worked. Went to Tirisfal and it joined me on General and LocalDefense of that zone. Then I turned around and teleported back to Silvermoon and it still said I was still in Tirisfal on my chat window. Trade still worked.
6. I only managed to destroy trade by HS'ing from an instance (went to Sethekk Halls) to a city (Shattrath). HS'd from Terokkar to Shattrath and nothing broke.
