### ISSUE TITLE
[Hunter's Pet] Can't learn spell [Dash Rank 3] from Scythetoot Raptor in Netherstorm

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#1329]
Hi there,

i'm writing this report after trying learning 2 spells from Scythetoot Raptor in Netherstorm (Bite Rank 9 and Dash Rank 3). I went to Netherstorm inside Eco-Dome Farfield, tamed 1 Raptor, feeded him till 100% happyness and then i've started farming raptors nearby. In the pet bar the 2 spells are correctly shown. After a few raptor slain i gained the Bite rank 9 spell. But after 20 minutes of farming using every time (when not in cd) the Dash spell, i couldn't learn it. I remember it faster during TBC time on official servers.

To reproduce:

With Hunter character go without pet in Eco-Dome Farfield.
Tame a Scythetoot Raptor
Feed him till 100% happyness
Start farming nearby raptors
No Dash spell learned.

**Comment by ConfusedCC** [comment]
tried to learn dash with theese raptors just now and had a similar experience, bite r 9 came pretty fast and dash 3 just didnt pop ,
i hs to durotar to speed up the process and got the dash 3 on the 2nd mob, 
![wowscrnshot_081315_001145](https://cloud.githubusercontent.com/assets/10581981/9238506/1561dd94-4153-11e5-8aba-b93b8c6ac767.jpg)
tested again with another hunter, killed one raptor and got bite then went straight to starter mobs and got the skills on the 3rd mob.
![wowscrnshot_081315_002844](https://cloud.githubusercontent.com/assets/10581981/9238508/1a268816-4153-11e5-9cb9-f0397b5acf68.jpg)

sample size is low so could be a bad case of RNG

**Comment by rsheep** [comment]
You need to count in the Cooldown of the ability.
For example, you will learn Claw quite fast as it has no Cooldown at all.
Dash, on the other had has a 10s (?) CD.
Same goes for any ability with a CD....yes, RNG is NOT your friend.

Also, I believe "happiness" isn't a factor about learning a pet-ability.

**Comment by Summoning01** [comment]
Took me 150+ casts on my Frostsaber Stalker to learn it.
