### ISSUE TITLE
[Group] Leader going offline

### ISSUE THREAD

**Issue by Catfishs** [ccshiro/cc-buglist#133]
When a leader of a group goes offline the party leader isn't passed on to another member as it should. Can be very annoying at times when a group leader goes offline.

**Comment by FurioCC** [comment]
Leader supposed to be passed after some times passing like 5 minutes, not instantly for sure.

**Comment by Pronator** [comment]
Yep, def not instant but something like 5 mins

**Comment by Escape243** [comment]
Is it really not immediately?
