### ISSUE TITLE
[Movement] - Mangy Wolf

### ISSUE THREAD

**Issue by DeeMarie** [ccshiro/cc-buglist#1337]
(Yeah I know it's not TBC content and it's just a wolf but it said in the pastebin to SS so...)

http://postimg.org/image/7ko3kruaz/

Not sure if it's a movement bug because one of the SW guards was targeting it.

**Comment by Barroth** [comment]
hm you might want to explain how he moved and what seems bugged, since the screenshot looks pretty normal to me :)

**Comment by DeeMarie** [comment]
At the moment it's just going round in jerky circles. I think because the guard is targeting it, but not in range of actually killing it, it's resetting.

**Comment by ccshiro** [comment]
Guard AI behaving oddly, will be fixed with #1397.
