### ISSUE TITLE
Hammer of Wrath, Execute, etc

### ISSUE THREAD

**Issue by Maelareth** [ccshiro/cc-buglist#134]
As a lvl 60 holy paladin (probably the same despite lvl and specc) I get the screen notification that Hammer of Justice is available when looting corpses. I guess that is because the target is at 0% hp and  under the required percent for HoJ to be used? I'm not sure if this was supposed to be this way in TBC but I thought it wasn't.

First bug report! Yey!

**Comment by Iliana-sc** [comment]
This is about hammer of wrath right? that sounds like it's a default UI issue, or did this really not happen on retail?

**Comment by Maelareth** [comment]
Yeah Hammer of Wrath is what I meant. I am not sure, I just thought it seemed wierd to show up when looting.

**Comment by Bearmanpig** [comment]
Same thing happened for me on warrior. When using the addon Scrolling Combat Text it would flash ' Execute!'  as if the skill became available whenever I targeted a corpse, and the skill would actually show as being available on the actionbar.

Of course the skill should be unavailable if the target is dead.

Proof: http://youtu.be/MUG_nVpHkWc?t=2m6s
At 2:08 execute becomes unavailable on his actionbar (4th skill on his lower bar from left to right), while he has a corpse targeted.

**Comment by ccnim** [comment]
https://www.youtube.com/watch?v=uqil91lzNV4#t=256 Another video showing this but on a mob instead.
