### ISSUE TITLE
[visual][Dungeon] Mob inside "green" canister -- the blood furnace

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1341]
casted mind vision on one of he mobs inside the green cannisters in blood furnace, apparently he was halfway in-out of the cannister, refer to screenshots

![mobagua3](https://cloud.githubusercontent.com/assets/13721369/9238969/68d2f086-4157-11e5-8093-77a7824a2c43.png)
![mobagua1](https://cloud.githubusercontent.com/assets/13721369/9238970/68d6d64c-4157-11e5-8b17-38bf05544d57.png)
![mobagua2](https://cloud.githubusercontent.com/assets/13721369/9238971/68d9c528-4157-11e5-90a1-4510b67e5637.png)

**Comment by ccshiro** [comment]
Should be a duplicate of #1178.
