### ISSUE TITLE
[Dungeon] Missing emote on proximity mine -- blood furnace

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1342]
Blood furnace mines dont show up the /emote "proximity mine will be armed in X seconds" and "proximity mine is now armed"
![proximity mine](https://cloud.githubusercontent.com/assets/13721369/9238977/8855f0fc-4157-11e5-87a6-a5fc6749742a.png)

**Comment by ccnim** [comment]
The emote only shows up in normal.
