### ISSUE TITLE
[Loot] Some G-Objects of Bogblossom haven't loot

### ISSUE THREAD

**Issue by Nonstopich** [ccshiro/cc-buglist#1348]
For Druid Quest  [The Ward of Wakening] i need to bring 10x [Bogblossom]
Some of Nodes haven't drop.
Some of Nodes do not disappear after looting.
Somf oe Nodes "hanging in the air"
![wowscrnshot_081315_103203](https://cloud.githubusercontent.com/assets/6273420/9244824/909f73b4-41a7-11e5-95b7-7747cb61cfac.jpg)
![wowscrnshot_081315_103231](https://cloud.githubusercontent.com/assets/6273420/9244825/90a21434-41a7-11e5-952e-56cf275ed7dc.jpg)

BR,
Lavrushka

**Comment by Chulain** [comment]
take a print screen of ur map so they can find it

**Comment by Nonstopich** [comment]
It will be a lot of screenshots, 
because most of nodes in Zangramash have these problems

**Comment by ccnim** [comment]
Removed them since they were 2.1
