### ISSUE TITLE
[Quest] No Mere Dream

### ISSUE THREAD

**Issue by Nonstopich** [ccshiro/cc-buglist#1349]
For this quest Must run an event
This video can say more than me:
http://www.youtube.com/watch?v=spbnY2bglFg

Quest is autocomplete now.

Before i accept this quest i saw NPCs, like Manifest NightMare and Aspect of the Raven.
But in retail this NPCs can be abserved only under Debuff.

Buff is cancelable Buff now.

**Comment by ccnim** [comment]
removed since it was added with 2.1
