### ISSUE TITLE
[Quest] NPC Sai'kkal dont abserved

### ISSUE THREAD

**Issue by Nonstopich** [ccshiro/cc-buglist#1351]
This NPC http://www.wowhead.com/npc=22932/saikkal-the-elder#comments dont Abserved for Quest [The Book of the Raven]

As u can see, first comment (from patch 2.1.0) 
This NPC can be found roaming the plains around 30,55 in the Blade's Edge Mts with other Arakkoa Spirits

Second problem: An Aether Ray Eye should drop from this NPC http://www.wowhead.com/npc=22181/aether-ray, but no one of them dont stand on there places

I Found an guide http://www.tentonhammer.com/wow/guides/classes/druid/quests
Step 7: Notes: Fly to Vortex Pinnacle and find an Aethor Ray to kill, found around 32,50.

As u can see I have debuff (I found Aether Ray near 70,10 o.O) and i can't see any spirit.
![wowscrnshot_081315_125558](https://cloud.githubusercontent.com/assets/6273420/9247320/b3fd4648-41ba-11e5-9bb4-6b3b08bb54d8.jpg)
![wowscrnshot_081315_125604](https://cloud.githubusercontent.com/assets/6273420/9247318/b3f759d6-41ba-11e5-9c8f-ca2bad3cea47.jpg)
![wowscrnshot_081315_125605](https://cloud.githubusercontent.com/assets/6273420/9247321/b3fecaae-41ba-11e5-883b-3759eb396cfc.jpg)
![wowscrnshot_081315_125607](https://cloud.githubusercontent.com/assets/6273420/9247319/b3fb2444-41ba-11e5-930a-e1bd3e027db5.jpg)

BR,

Lavrushka

**Comment by ccnim** [comment]
Only in 2.1. I'm assuming you are trying to do the epic flight form quest which should not exist in 2.1 so that in itself is a bug.

**Comment by Nonstopich** [comment]
It will be a problem, when 2.1 patch will be released in CoreCraft, I think.
Then you should close quests in this questline before The Book of the Raven, but i can test all quests from this Line, and the problem will be solved
