### ISSUE TITLE
Neutral Auction House Not Working?

### ISSUE THREAD

**Issue by noyze00** [ccshiro/cc-buglist#1352]
I made 2 characters, one horde and one alliance. I flew to Gadgetzan and put an item up on the auction House there. I then tried to buy the item from a character of the opposite faction and it did not work. I tried the 12 hour and 24 hour setting, I also tried to bid and buyout. I canceled the auction and tried to put it up for a more expensive price. Nothing worked and no messages came up. I did not try to auction house in STV.

**Comment by Chulain** [comment]
did you use 2 account? i think you cant buy/bid on your own auctions

**Comment by Chulain** [comment]
did you use 2 account? you cant buy/bid on your own auctions

a message should pop up tho (i think)

**Comment by noyze00** [comment]
No just 1 account :)

**Comment by Chulain** [comment]
http://www.wowhead.com/forums&topic=160464/neutral-auction-house-gold-moving
2010/06/20 at 11:32 PM (Patch 3.3.3)
To expand a bit more. Two accounts are needed because you can't buy your own auctions.

**Comment by ccshiro** [comment]
What @Chulain said.
