### ISSUE TITLE
Pet Accelerated Follow Mechanic

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1359]
https://youtu.be/YPsnRtXudxc?t=2m53s

Appears to be missing

**Comment by Barroth** [comment]
would be cool if someone found a video showing this in tbc times, not retail. pets got changed quite a bit.

**Comment by ccshiro** [comment]
I thought this speedup when far away was added in later expansions.

**Comment by YourNewfriend** [comment]
perhaps.  it shouldn't be difficult to prove.

**Comment by Aasamath** [comment]
https://www.youtube.com/watch?v=lLcazvAGtOM
the video is accelerated x2 so just put speed a 0.5 on youtube.
I don't see any acceleration, unless i'm mistaken.
(name of server at the end of arena so it"s retail, and drood alive seem to be wearing s3 head, so season is at least s3)

**Comment by Peonstomperx** [comment]
@Aasamath arena is probably an exception tho, like mounting with pet

**Comment by YourNewfriend** [comment]
The pet in your video is in attack mode, and not follow mode.

**Comment by Aasamath** [comment]
damn yeah, sorry about that. Thinking about it, being in combat (pet or master) might also cancel the accelerated follow. Gotta watch out for that,or find a video of both situation.

**Comment by Klimpb** [comment]
I'm fairly sure that the only time a pet runs faster in TBC is when you are mounted in Arena(since your pet stays with you when mounted in arena)

Also, assume everything that Nostalrius has implemented is wrong.

**Comment by Aasamath** [comment]
only thing i found yet is:
Patch 1.5.0 (2005-06-07): Pet speed has been increased when out of combat and following their master.
Edit: https://www.youtube.com/watch?v=XHntKytYDBI
3:00 succubus doesn't have accelerated mechanic
3:47 neither the flying serpent thingy in the back
12:48 the hunter's bird here neither (this one is definetly an out of combat situation for both pet and master)
This is filmed prior to 2.4.3 though  (warlock still has "curse of shadow")

https://www.youtube.com/watch?v=BHu0H__CP6A 3:35 
mechanic is present here, this is at least patch 3.3.0 (icc gear on warlock)

**Comment by justinbeaver** [comment]
afaik in vanilla if you're mounted pet is always out and following you, and their speed scales with hunter mounted speed. that is what patch note about. in BC times blizz has added fly mounts, and pet out with mounted master can be seen only in arena.

but i guess we are missing the point, it is possible this mechanic was in early wow, when out of combat, on follow, and most important when hunter and pet on different ground levels. for example, in WSG when hunter is jumping from second or third level in base down, it will take forever for pet to come. would be nice if someone will find such a video.

**Comment by ccshiro** [comment]
@Aasamath that seems to prove it wasn't a thing pre 2.4.3 (but still TBC), and that's good enough for me. If someone wants to claim this was a thing in 2.4.3 they'll have to reopen this with evidence.
