### ISSUE TITLE
Line of Sight World Objects

### ISSUE THREAD

**Issue by Pronator** [ccshiro/cc-buglist#136]
I tested this with my friend in Netherstorm, Blades Edge Mountains, Nagrand, and Terokkar Forrest and the issue is shown in the video attached.  Basically, you can still attack mobs as well as dueling (assume world pvp) people through all terrain objects such as rocks, trees, and hills in the world.  We did test some buildings and we were not able to attack through them.  All the terrain however seems like you can attack.
https://www.youtube.com/watch?v=GFjjqgQ83XU&feature=youtu.be

**Comment by Iliana-sc** [comment]
not a bug
