### ISSUE TITLE
Mobs Flee Very Slowly In Fear Sometimes

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#1361]
![wowscrnshot_081315_113207](https://cloud.githubusercontent.com/assets/13057166/9258422/59bed340-41b0-11e5-8dca-68647c30dca1.jpg)

It seems to happen randomly.  Refreshing the fear doesn't help.  The monster will move at its normal walking pace while fleeing.

I'm not sure if this is even a bug, but you can decide based on what's below or whatever you have.

Monster:
https://youtu.be/V8U7YWp01H0?t=58s
https://youtu.be/V8U7YWp01H0?t=12s
https://www.youtube.com/watch?v=iDENDAnaHiw
https://www.youtube.com/watch?v=wyEen8__Ueg
https://www.youtube.com/watch?v=zL4Um9lShS4
https://www.youtube.com/watch?v=Gp9NKSdvM68

Player:
https://youtu.be/NZIg4OZlA-4?t=2m20s

**Comment by Aasamath** [comment]
On your screenshot the mob is pretty low hp, and if i'm not mistaken low hp mob run slower, or at least flee slower. That could be the reason, in that particular case.
(i can't check the videos now to verify that, would make my roommate lag on CS^^)

**Comment by YourNewfriend** [comment]
yes, that could be the reason.

**Comment by ccshiro** [comment]
NPCs have lower momvement speed when low health. Needs proof that the reduction shouldn't apply to them being feared, as it applied both when they're chasing and fleeing.

**Comment by Aasamath** [comment]
This is a vanilla video but i guess it works
https://www.youtube.com/watch?v=Qp3atf58gQg
when mob has high hp the fear puts him in run animation 
but when low hp, even feared he still walks.

Also on the video @YourNewfriend  posted you see one mob fleeing faster than the others, cause he has a lot more hp left
https://youtu.be/V8U7YWp01H0?t=58s
