### ISSUE TITLE
[Dungeon] BF HC 2nd boss event bugged

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#1368]
One of the adds was attackable but not in sight.
was able to pull him with consecration through the door wich bugged the event.
https://www.youtube.com/watch?v=utd_AaTQRXg&feature=youtu.be&t=92
the other doors opend up slowly but the boss door didn't open.
we had to ask Nim to port us through.

**Comment by Aprics** [comment]
the mob was pulled previously with another mob that was feared in the box.
the bug originally started with that fear that made a mob walk in there.
the mob that was pulled with the feared mob was untargetable in the first run we died as he should not be free by then. he then resetet and went targetable inside the box.

**Comment by Sakatoro** [comment]
+the npcs @ the last boss are not linked

**Comment by Lephidiles** [comment]
@Aprics: i think it was the other way around. although my video is broken of it so can not go back and see. But there was a mob from inside the room you pulled from that got feared and pulled a mob from the other room on the same side. so it was not the untargetable creature that turned into a targetable creature (this came from the other room)

looked at part one of the videos but you can not see it here either.

**Comment by Lephidiles** [comment]
after doing this a second time i noticed after a wipe that the mobs inside the closed rooms spawned as target able.
