### ISSUE TITLE
[Dungeon] Old Hillsbrad Foothills: Epoch Hunter

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1373]
After doing Sand Breath, the Epoch Hunter did three swings in one second, for a total of 11016 damage; on top of the 2923 from his Sand Breath. An effective "one-shot".

Combat Log:
![epoch hunter 1](https://cloud.githubusercontent.com/assets/13790554/9270621/f825b892-4227-11e5-9e3c-c22f9337c1c4.png)

Recount:
![epoch hunter 2](https://cloud.githubusercontent.com/assets/13790554/9270626/04d16938-4228-11e5-9fa1-3d779866a10d.png)

**Comment by Doppelmoral** [comment]
http://www.wowhead.com/spell=3391/thrash

Thrash
Instant
Gives the caster 2 extra attacks.

Many bosses have this mechanic (most notoriously Prince Malchezaar), we just have to figure out whether Epoch Hunter is supposed to do that. (Btw one of the many reasons why Warriors best tanks.)

Edit: It's not explicitly listed in the "Used by" chart but still a rather common attack type, needs more research.)

**Comment by ccnim** [comment]
Epoch Hunter has thrash.
