### ISSUE TITLE
Goblin engineering card display issue

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1379]
![](https://i.gyazo.com/0672b7d47cac290b71c3ed1b3290d341.png)
Don't think it should have a duration at all.

**Comment by Krack3n77** [comment]
It is supposed to be 14 days.

Edit
http://db.lastwow.com/?quest=3639
http://db.lastwow.com/?quest=3644

**Comment by Doppelmoral** [comment]
Another half-assed report ffs.

It is supposed to have a duration. The duration is btw DAYS /PLAYED TIME. If 14 days is correct then it should be 14 days played time of the character. Hence it's no biggie.

**Comment by ccshiro** [comment]
Duplicate of #1268.
