### ISSUE TITLE
Camouflage (Rogue Talent)

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1380]
Doesn't reduce cooldown of stealth.

![wowscrnshot_081515_004420](https://cloud.githubusercontent.com/assets/12783794/9285580/8dda0cb6-42e7-11e5-9594-9b11f39f1b81.jpg)

It got fixed after I relogged

**Comment by Chulain** [comment]
strange something must've caused this, working just fine for me :o

**Comment by rezzybaws** [comment]
Was exposed to this earlier, too. Gotta find out how to reproduce it

**Comment by Doppelmoral** [comment]
Did you clear Cache and relog before reproduction after the respec ?

**Comment by ccnim** [comment]
Seems like this has been fixed with some other fix.
