### ISSUE TITLE
Blink is not working as it should

### ISSUE THREAD

**Issue by Jigodian** [ccshiro/cc-buglist#1384]
The ol' uphill blink bug plus some other problems that make me a sad mage :(
https://www.youtube.com/watch?v=Vdm2pA0FNJI&feature=youtu.be

A fine example of how it should work:
https://www.youtube.com/watch?v=Ny2Hogb_k98

**Comment by Chulain** [comment]
nostal is a garbage can, don't use it as evidence

**Comment by Jigodian** [comment]
I don't think they deserve to be called garbage in this case since their server is one of the very few that actually have blink working correctly.

**Comment by PatchnotesTBC** [comment]
Nostalrius blink do not work as retail got over 22 days played on my mage

**Comment by Jigodian** [comment]
@PatchnotesTBC You may be right, but other than that I have never encountered a private server that has blink working half decently. (except maybe AT)

**Comment by darkcranio** [comment]
This was working 1 test ago.

**Comment by ConfusedCC** [comment]
vicu suggested i post https://youtu.be/Be00nb46jp8?t=15m59s , this might be a reupload from tbc.
i then went on the test server and recreated it, seems there are some areas you can blink up slope in the arena and others that stop you https://www.youtube.com/watch?v=gR1LX8wVnPQ

more videos (from tbc) with different blink locations is needed to confirm this as a bug

I did some further testing of up slope blinking you can bling upslope from green dots, red dots not
![ramp grid](https://cloud.githubusercontent.com/assets/10581981/9396141/14962a1e-4793-11e5-9023-ab717a557a1d.jpg)

**Comment by ccshiro** [comment]
@ConfusedCC Not being able to blink in the middle of that ramp sounds wrong, will look into it.

**Comment by ccshiro** [comment]
Fixed the case in @ConfusedCC's screenshot.

**Comment by justinbeaver** [comment]
Pretty obvious, but still I'll leave it here.
Mage used blink at the edge and it moved him slightly back
<b>Cheapshot3.wmv</b>
<b>10:34</b>
![cheapshot3 wmv_snapshot_10 35_ 2015 08 29_17 26 43](https://cloud.githubusercontent.com/assets/13700367/9562654/ccf84f5e-4e7a-11e5-9664-aba150e5e1c6.jpg)
![cheapshot3 wmv_snapshot_10 36_ 2015 08 29_17 27 06](https://cloud.githubusercontent.com/assets/13700367/9562655/d1279742-4e7a-11e5-81fd-44b1331d5dd9.jpg)
WCM link: <I>http://www.warcraftmovies.com/movieview.php?id=69243</i>
Gamefront download: <i>http://www.gamefront.com/files/Cheapshot3wmv/;9921794;/fileinfo.html</i>
