### ISSUE TITLE
#Сharge #Exclusion

### ISSUE THREAD

**Issue by ASrozaev** [ccshiro/cc-buglist#1386]
charging to target (jumping sideways,running,flying) -> charging character to start point of jump
@ retail : will charge to the model of the target and will interrupt any movement (end effects of movement) of target(jumping,running,flying)

**Comment by Aasamath** [comment]
This is untrue about the jumping part 
https://youtu.be/9DA10SgPsj4?t=162
this was changed at MoP or wod i don't remenber, before that taking a cc while jumping in a direction wouldn't stop the jump trajectory.
About the running and fllying, there is a delay beewteen the charge starting and the stun being applied. meaning you don't arrive at the same distance of the target if it's moving.
Lagging a lot amplifies those phenomenons
https://youtu.be/efC4c0nCR6c?t=142 chinese players on tawain servers

**Comment by ASrozaev** [comment]
I will agree
Patch 4.3.0 (29-Nov-2011): Charge (and related abilities) should now correctly path to a target even if the target moves during the Charge. This change should decrease the likelihood of the warrior Charging to a different location than the target.

close the thread plz
P.S. : it's real shit
