### ISSUE TITLE
npc - Azaloth

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#1389]
![wow_2015_08_15_14_41_06_817](https://cloud.githubusercontent.com/assets/10247793/9288854/fae38bce-435b-11e5-9a51-2eac82858179.jpg)

http://www.wowhead.com/npc=21506/azaloth

looks like theres an issue with this guy again, the warlocks dont rebanish him i think, i found him like this and when i came back 1h later he still wasn't banished

yep today after server restart i've managed to get rid of his banish simply by resetting him (just like before: https://github.com/ccshiro/cc-buglist/issues/595)

**Comment by Chulain** [comment]
also if you attack him while he's banished you'll be in combat till you reset him

**Comment by Chulain** [comment]
also the Sunfury Warlocks weren't channeling
http://www.wowhead.com/npc=21503/sunfury-warlock

they should: https://youtu.be/1pTminRkW68?t=21

**Comment by Lumber-Jack-2** [comment]
they will channel it every 2 minutes
