### ISSUE TITLE
Prayer of Fortitude Rank 3

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#139]
This is available from priest trainer. should be a world drop (this was added before this test so i guess you are aware of it)

**Comment by FurioCC** [comment]
Its added to trainers for test purposes. Same for other party wide buffs like Gift of the Wild for druids etc.

**Comment by ccshiro** [comment]
Some spells are purposely kept in trainers that shouldn't be for testing. This will be changed before release.
