### ISSUE TITLE
Elites in Auchenai Crypts are spawning adds at the wrong place

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1391]
Elite draenei mobs in Auchenai Crypts who spawn adds do it in the wrong place.
If you pull them from where they stay/walk they will still spawn adds at that place instead of their current place.

On the screenshot you can see the add close to the sheep. He was spawned by one of the mobs lying dead around us while that mob was tanked at our place. He stood still at its spawn point (where we pulled that spawner mob from) until we came closer and pulled him.
![wowscrnshot_081515_174659](https://cloud.githubusercontent.com/assets/5777848/9289710/7599c060-4382-11e5-8f5f-db579ac39b9f.jpg)

**Comment by ccnim** [comment]
Works fine for me.
