### ISSUE TITLE
Mobs evaded after tank got knocked from the bridge in Auchenai Crypts

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1393]
On the bridge there are mobs that explode knocking you far away. They can drop you from the bridge.
Our tank got knocked down while tanking a group of elite mobs.
The whole group kept staying here for a while saying 'evade' when we tried to attack them.
Later they reset.

I believe they should switch to another target if they can't reach highest threat one.

![wowscrnshot_081515_183056](https://cloud.githubusercontent.com/assets/5777848/9289746/1d1d881c-4383-11e5-938a-1f98c763fbd8.jpg)

**Comment by opzor** [comment]
related:
https://github.com/ccshiro/cc-buglist/issues/1412

**Comment by ccshiro** [comment]
As opzor said the bug is actually what is in #1412. NPCs should change target if the main tank actually disappears from their threat list (which he should have in your image). Will close this one and use #1412 instead.
