### ISSUE TITLE
[Hunter/Warlock] slow pets

### ISSUE THREAD

**Issue by justinbeaver** [ccshiro/cc-buglist#1395]
![wowscrnshot_081515_084405](https://cloud.githubusercontent.com/assets/13700367/9289796/34b14854-4330-11e5-9f7e-7adb10a7e615.jpg)
![wowscrnshot_081515_084045](https://cloud.githubusercontent.com/assets/13700367/9289802/4985f900-4330-11e5-896e-f4619c795e57.jpg)
![wowscrnshot_081515_084210](https://cloud.githubusercontent.com/assets/13700367/9289804/534051b6-4330-11e5-971c-9c3e69ca4be9.jpg)
![wowscrnshot_081515_084216](https://cloud.githubusercontent.com/assets/13700367/9289806/55d255d2-4330-11e5-8560-43520d0b5b10.jpg)
vids:
https://www.youtube.com/watch?v=T7ZUnT9Uzss&feature=youtu.be&t=46
https://youtu.be/9qv4nbt-NNk?t=822
https://youtu.be/m8nOaNMHZIQ?t=245
https://youtu.be/m8nOaNMHZIQ?t=344
https://youtu.be/m8nOaNMHZIQ?t=572
pets are moving with every master step, not wait for distance to start moving. sometimes they are running even ahead of master and overall doing much more movement

added:
looks the same not from hunter POV
https://youtu.be/VhCI3DDvGGU?t=247

**Comment by ccshiro** [comment]
Will fix this when I look at #548.
