### ISSUE TITLE
There should be a small delay before an arena ends

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1400]
https://youtu.be/ETeGCih50HU?t=6m6s

will find more videos.

**Comment by Peonstomperx** [comment]
what if you die from a dot tick or projectile in that delay, is it a draw?

**Comment by Schaka** [comment]
Can confirm what @Peonstomperx said.
See, actual screenshot of me being shit in S3 and losing to LD:
http://i.imgur.com/QOAL30J.jpg
vs what it looks like to win a lowrated team and gain 0 rating
http://i.imgur.com/Z1Qxklv.jpg

The reason I can see their rating is I used SSPvP back then. Shadowed wrote a lot of addons that made these things possible back in the day.

**Comment by Klimpb** [comment]
delay should be about 2 seconds
https://youtu.be/tcIS5yRUDD8?t=1m23s

**Comment by ccshiro** [comment]
Fixed this because it turned out to be the easiest way to fix #2278 and any bug that might behave like #2278.

**Comment by Evolvee** [comment]
@Peonstomperx Do you still have any evidence if you could cast spells during this delay? I see you could freely move...
