### ISSUE TITLE
Loottable Dark Conclave mobs in Shadowmoonvalley

### ISSUE THREAD

**Issue by abuescher** [ccshiro/cc-buglist#1401]
Appears to be bugged. They only drop money and light feathers and uncommon stuff. Killed about 30, didnt get a single common loot. 

http://imgur.com/RqJ6WAc

Took the hellground database as confirmation:

http://db.hellground.net/?npc=21386

May also be super unlucky, but possibilites are given that loottable is bugged. May also be linked to issue  #1350

**Comment by abuescher** [comment]
Ok, apparently it was only bugged while I was on the quest "The Sketh'lon Wrackage" and had part 2 and 3 in my back. didnt get any "white" loot (also not part 1 of the quest) so I had to reset it. Now it worked finde - strange.

**Comment by ccnim** [comment]
Note to self: Cloth didn't drop at all and we need to implement the potions and scrolls into the loot selection.
