### ISSUE TITLE
Another movement bugg

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1408]
Mob is accidentally jumping.
![wowscrnshot_081715_084214](https://cloud.githubusercontent.com/assets/13764565/9295747/24d90114-44bc-11e5-9e4f-0a125e36c1f9.jpg)

**Comment by ASrozaev** [comment]
I see plainstrider staying one leg

**Comment by ccshiro** [comment]
Duplicate of #1225.
