### ISSUE TITLE
[Undead] racial Will of the Forsaken is grayed out while you are fleeing.

### ISSUE THREAD

**Issue by opzor** [ccshiro/cc-buglist#1415]
Whats wrong:
Undead racial "Will of the Forsaken" (http://wowwiki.wikia.com/wiki/Will_of_the_Forsaken)
does not work (cant use - is grayed out) when player is feared by physical fear (warrior/some heroic mobs)

How it should be:
Will of the Forsaken should remove ANY Charm, Fear, or Sleep effect.

---

EDIT:
it appears that "Will of the Forsaken" is also grayed out when player is feared by mobs in Underbog, spell those mobs cast is named Psychic Scream (not physical) and can be dispelled by priest.

---

Sources:
Patch 1.2.0 (18-Dec-2004): Will of the Forsaken is no longer grayed out on the action bar while you are fleeing.

![1](https://cloud.githubusercontent.com/assets/13710937/9307690/44936cc6-4500-11e5-8d0c-2d3c651faf77.png)
http://wowwiki.wikia.com/wiki/Will_of_the_Forsaken

![2](https://cloud.githubusercontent.com/assets/13710937/9307696/4ed73730-4500-11e5-9868-c81dceb59d16.png)
https://web.archive.org/web/20100703011709/http://www.wowhead.com/spell=7744/will-of-the-forsaken

**Comment by Chulain** [comment]
This effect shares a 30 sec cooldown with other similar effects.

fix pls

**Comment by opzor** [comment]
## In tbc this spell had no shared cooldown.

---

By Koolkidzklub (117 – 0) on 2010/05/05 (Patch 3.3.3)  
This nerf really made me put on my rageface. I don't care what anyone says, a cooldown is a cooldown. It may only be 45 seconds, but the same people .....

---

 Patch 3.3.0 (08-Dec-2009): Now shares a 45-second cooldown with similar effects, including the [Medallion of the Horde], Titan-Forged runes, [Insignia of the Horde], etc.

---

By Kanariya (28,057 – 6·27·236) on 2010/12/22 (Patch 4.0.3)
WotF once again claims superiority to the not-so-recently nerfed Emfh, and buffed to a 30 second shared CD.

**Comment by Chulain** [comment]
fix pls this is very bug

**Comment by opzor** [comment]
seems to be fixed.
closing.
