### ISSUE TITLE
UNIT_SPELLCAST_SUCCEEDED

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#1418]
### Bug

Your target's cast bar can continue despite cast having finished server side, this is especially noticeable on interrupts that happen just as the cast finishes. The caster sees the cast bar update correctly (turns green to indicate success), but the target does not (it continues for a split second despite the interrupt, creating the strange looking visual effect where it appears as if your interrupt had no effect and the cast just continues).
### Data

On casting frostbolt the following events trigger:

| Server | Caster | Target |
| --- | --- | --- |
| Start cast | UNIT_SPELLCAST_START | UNIT_SPELLCAST_START |
| Release spell* | UNIT_SPELLCAST_SUCCEEDED | Nothing |

\* This is when your cast bar turns green to indicate a successful cast, and the spell leaves your hands.

UNIT_SPELLCAST_START is noticeably missing, most likely being the culprit as it is what lets the caster know the cast is done. However, the packet is sent to the target, and indeed it has a noticeable effect (without it the target never stops playing the visual hands glowing and waving cast animation). We believe this event should trigger for the target (see links below) and is a likely culprit to this bug, but we currently do not know how to fix it.
### Finding info

To figure out how to fix it we'd need a packet dump from retail TBC, or reversing the client. The latter takes time, but is probably the only option, as we've exhausted other avenues. This seems to work in TrinityCore, but the packet has changed from TBC to WotLK, and there seems to be nothing different about the components that are the same. It's possible the error is unrelated to the packet itself, however, and happens earlier for some reason?
### Links

This describes that UNIT_SPELLCAST_START should not be present on instant spells (incorrect atm):
http://wow.gamepedia.com/index.php?title=Detecting_an_instant_cast_spell&oldid=1545585

We believe UNIT_SPELLCAST_SUCCEEDED should trigger for the target because:
- The above gamepedia would indicate it, since instants apparently don't use start events.
- The UNIT_SPELLCAST_SUCCEEDED API has a target parameter.
- Code using it seems to check the target: https://gist.github.com/tekkub/30085
- Code using it seems to check the target: http://www.arenajunkies.com/topic/34778-msbt-pet-cooldown-notifications/
- Code using it seems to check the target: http://www.wowinterface.com/forums/showpost.php?p=90118&postcount=1
- Discussion about how some addons use it for cooldown tracking (presumably not only for self): http://maintankadin.failsafedesign.com/forum/viewtopic.php?f=9&t=30183&start=15#p628030
### Addon

Here's the code of the addon I used for testing, in case anyone's interested to try it themselves: https://gist.github.com/ccshiro/612281b4201e93dbb313

**Comment by Sakatoro** [comment]
Sounds like a lot of work :/

**Comment by opzor** [comment]
COMBAT_LOG_EVENT_UNFILTERED = CLEU

#### Spell cast detection:

normal: SPELL_CAST_START (CLEU)
instant: SPELL_CAST_SUCCESS (CLEU)
totems/pets: SPELL_SUMMON (CLEU)

#### Cast finish detection:

normal: UNIT_SPELLCAST_SUCCEEDED
(captured as separate event - not as agrument of CLEU - only for player)
instant: SPELL_CAST_SUCCESS, SPELL_CAST_MISS (CLEU)
totems/pets: ? dont remember

#### Cast interruption detection:

interrupted by external sources: SPELL_INTERRUPT (CLEU)
interrupted by player - fakecasting/jumping etc: SPELL_CAST_FAILED (CLEU)

this is what im using in my addon that detects who,when and with what broke my CC...
it was made on another server but it is working fine here as well.

---

this is how it was on another p server.

SPELL_CAST_START was triggered for player and target.
(you can get spell_name and ?rank ?casttime as a arguments to make castbar - need to confirm)

UNIT_SPELLCAST_SUCCEEDED was triggered only on casts from player.
thats why i had to detect SPELL_DAMAGE,AURA_APPLIED(dots) etc. to confirm target finished casting.

---

dont think that helps but just for info that it is working the same on another p servers.

oh and btw:
UNIT_SPELLCAST_SUCCESS
("unitID", "spell", "rank", lineID, spellID)

there is no target here... just unitID... source
UNIT_SPELLCAST_START also does not have target argument

---

for me it looks like client is recieving spell ID and rank and draw a castbar
and then he should react to all event that change it like:
UNIT_SPELLCAST_DELAYED
UNIT_SPELLCAST_FAILED
UNIT_SPELLCAST_INTERRUPTED
etc

**Comment by opzor** [comment]
Quartz (castbar addon) does not use UNIT_SPELLCAST_SUCCEEDED at all

to draw castbar its using
spell, rank, displayName, icon, startTime, endTime = UnitCastingInfo(unit)
http://wowprogramming.com/docs/api/UnitCastingInfo

and then reacts to
UNIT_SPELLCAST_START, 
UNIT_SPELLCAST_CHANNEL_START, 
UNIT_SPELLCAST_STOP, 
UNIT_SPELLCAST_FAILED, 
UNIT_SPELLCAST_DELAYED,
UNIT_SPELLCAST_CHANNEL_UPDATE, 
UNIT_SPELLCAST_CHANNEL_STOP, 
UNIT_SPELLCAST_INTERRUPTED, 
UNIT_SPELLCAST_CHANNEL_INTERRUPTED, 
UNIT_SPELLCAST_INTERRUPTED

**Comment by ccshiro** [comment]
@opzor that quartz isn't using is for its castbar is peculiar.

### Quart for 2.4.3 (release 3)

I checked the 2.4.3 release (http://www.wowace.com/addons/quartz/files/206-r3/) and it only appears twice:

```
+shiro@shiro-desktop:/tmp/quartz$ ack "UNIT_SPELLCAST_SUCCEEDED"
Quartz_Tradeskill/Tradeskill.lua
83: self:RegisterEvent("UNIT_SPELLCAST_SUCCEEDED")
130:function QuartzTradeskill:UNIT_SPELLCAST_SUCCEEDED(unit, spell)

Quartz_Swing/Swing.lua
95: self:RegisterEvent("UNIT_SPELLCAST_SUCCEEDED")
161:function QuartzSwing:UNIT_SPELLCAST_SUCCEEDED(unit, spell)
```

Both components that track stuff only for yourself, I think?

The tradeskill code does this:

``` lua
function QuartzTradeskill:UNIT_SPELLCAST_SUCCEEDED(unit, spell)
    if unit ~= 'player' then
        return
    end
    if castname == spell then
        completedcasts = completedcasts + 1
    end
end
```

The check that unit is player is interesting, I suppose.

``` lua
function QuartzSwing:UNIT_SPELLCAST_SUCCEEDED(unit, spell)
    if swingmode == 0 then
        if resetspells[spell] then
            self:MeleeSwing()
        end
    elseif swingmode == 1 then
        if spell == autoshotname then
            self:Shoot()
        end
    end
    if resetautoshotspells[spell] then
        swingmode = 1
        self:Shoot()
    end
end
```

The swing code on the other hand does not check for this. This one is peculiar as well, and almost suggests you didn't get this event triggered, at least not for the set of spells he's listening to (i.e., auto shot, cleave, heroic strike, maul, raptor strike, slam and aimed shot). Unless I'm missing something else the code does (I'm completely unfamiliar with the wow lua api and lua itself) it seems like it would reset your swing timer when your target triggers said event, if it did indeed get triggered.

### Quartz for 3.3.5 (release 3.0.3.1)

Looking at the 3.3.5 version (http://www.wowace.com/addons/quartz/files/837-3-0-3-1/) we see that the same modules use the event (tradeskill, swing), along with the GCD module. In 3.3.5 we have decent indication that the SUCCEEDED event triggered for target as well, not just player. And indeed the swing code has been updated for that:

``` lua
function Swing:UNIT_SPELLCAST_SUCCEEDED(event, unit, spell)
    if unit ~= "player" then return end
    if swingmode == 0 then
        if resetspells[spell] then
            self:MeleeSwing()
        elseif spell == slam and slamstart then
            starttime = starttime + GetTime() - slamstart
            slamstart = nil
        end
    elseif swingmode == 1 then
        if spell == autoshotname then
            self:Shoot()
        end
    end
    if resetautoshotspells[spell] then
        swingmode = 1
        self:Shoot()
    end
end
```

### Checking some more versions:

Trying to determine when that change was added, and if it has some interesting changelog:
- It was still not changed in r23, which was game version 3.2.0.
- It was changed in 3.0.2, which is game version 3.3.0, and the next version after r23 labelled release.

Quartz 3.0.2 has the following mentions of the swing module (that I can see):
- Swing: Properly handle Slam
- Swing: Try to account for parry haste
- Fix the Swing Timer and some other config related breakages
- clean up module options a bit more, looks like Swing is still tossing errors though, ymmv.
- Add Rune Strike to the auto-attack swing list

All in all, guess it doesn't tell us anything about the event itself.

### Conclusion

Unless we find patch notes of the event changing in 3.3.0, I guess it's hard to draw any conclusions, as the check was not in all the way up to 3.2

**Comment by brndd** [comment]
As for the Quartz swing timer bit, it's possible the spells on the list just don't fire the event (although Aimed Shot not firing it sounds very odd). It's also possible that the unit check missing is simply a bug in Quartz.

The Maintankadin thread in the OP says this:

> *MOST* spells fire a UNIT_SPELLCAST_SUCCEEDED event. But, yup you guessed it. Not all of them.

So it was definitely the case that some spells don't fire the event.

What we do know is that a lot of code check the unit UNIT_SPELLCAST_SUCCEEDED is fired for, which in almost all the cases it seems to be the player themselves. In my opinion this suggests that it should fire for other units too, such as target and perhaps focus (I honestly can't remember if focustarget is supposed to have a cast bar in TBC).

**Comment by opzor** [comment]
Got currently more than 100 tbc addons and only around 7 of them make reference to UNIT_SPELLCAST_SUCCEEDED but in all cases its always to register self cast.

in case of DiamondThreatMetter its nicely renamed :)
DTM_Engine_RegisterEvent("UNIT_SPELLCAST_SUCCEEDED", DTM_SelfCast_Success);

As i have seen some addons just simply connect to default interface castbar to display its own version... like Aloft.

i will check later other addons...
like proximo... or another arena helper.

**Comment by opzor** [comment]
Swing is instant... UNIT_SPELLCAST_SUCCEEDED is not firing on instant cast spells.

btw.
Does some spells resets swings (white dmg)?
or does instant spells that trigger GCD reset swing timer?

###PROXIMO

---

function Proximo:RegisterSpells()
  COMBAT_EVENTS["SPELL_CAST_START"] = "CASTSTART"
  COMBAT_EVENTS["SPELL_SUMMON"] = "CASTSTART"
  COMBAT_EVENTS["SPELL_CREATE"] = "CASTSTART"
  COMBAT_EVENTS["SPELL_CAST_SUCCESS"] = "CASTEND"
  COMBAT_EVENTS["SPELL_CAST_FAILED"] = "CASTEND"
  COMBAT_EVENTS["SPELL_INTERRUPT"] = "INTERRUPT"
  self:RegisterEvent("UNIT_SPELLCAST_START")
  self:RegisterEvent("UNIT_SPELLCAST_CHANNEL_START", "UNIT_SPELLCAST_START")
  self:RegisterEvent("UNIT_SPELLCAST_STOP")
  self:RegisterEvent("UNIT_SPELLCAST_FAILED", "UNIT_SPELLCAST_STOP")
  self:RegisterEvent("UNIT_SPELLCAST_CHANNEL_STOP", "UNIT_SPELLCAST_STOP")
  self:RegisterEvent("UNIT_SPELLCAST_INTERRUPTED", "UNIT_SPELLCAST_STOP")
  self:RegisterEvent("UNIT_SPELLCAST_CHANNEL_INTERRUPTED", "UNIT_SPELLCAST_STOP")
  self:RegisterEvent("UNIT_SPELLCAST_DELAYED")
  self:RegisterEvent("UNIT_SPELLCAST_CHANNEL_UPDATE", "UNIT_SPELLCAST_DELAYED")
  if not prox_list then prox_list = self:GetList() end
end 

there is no reference to UNIT_SPELLCAST_SUCCEEDED what so ever

**Comment by tedrasiel** [comment]
"Does some spells resets swings (white dmg)?" heroic stike

**Comment by opzor** [comment]
DBM also uses also everything beside UNIT_SPELLCAST_SUCCEEDED....

only thing i was able to find in changelogs was: 

There are a number of new events:
UNIT_SPELLCAST_SUCCEEDED, "player", spell, rank
http://wowwiki.wikia.com/wiki/Patch_2.0.1/API_changes

but after that there is nothing about it, even tho i found this:

Those events only fire if a valid unit token (target, focus, partyNtarget, player, etc) can be associated with the event.
http://eu.battle.net/wow/en/forum/topic/3225624461

but its from 2012 :/

**Comment by opzor** [comment]
DBM starts to use UNIT_SPELLCAST_SUCCEEDED from

Deadly Boss Mods 4.41-beta-r3466    [wow3.3.0]
http://wow.curseforge.com/addons/deadly-boss-mods/files/?page=2&sort=date

**Comment by Lephidiles** [comment]
https://code.google.com/p/stasiscl/issues/detail?id=39

Download the combatlog file

looks like an entire Black temple raid

19.00 - 22.00 or 3hrs of raiding

http://www.curse.com/addons/wow/wcardioraid#t1:other-downloads
version 1.07 seems to parse it quite good

**Comment by Schaka** [comment]
Going through the code the default UI uses, I found CastBarFrame.lua. Checking TargetFrame.xml for "SpellCastingBar" lead me to believe this is the code used in castbar templates. The event was nowhere to be found here. To confirm, I took a look at XPerl castbars and "PartyCastingBars" to see how they handled party and enemy events. Again, not UNIT_SPELLCAST_SUCCEEDED was made use of.

However, I know for a fact, that PartyAbilityBars in 3.x made use of UNIT_SPELLCAST_SUCCEEDED to track instant casts by your party members and worked flawlessly that way. If someone could find a 2.x version of it (there is one, I've just never found it), we might be able to shed more light on how it was handled in TBC. To my personal knowledge, it never fired for instant casts though.

I am almost certain though, that for casts with an actual bar (channel or not) did fire that event. Maybe it incorrectly fired on some TBC servers and I just got too used to reading it, I couldn't say for sure.

As for the target parameter, I have just noticed when working on SoundAlerter, that some combatlog events like SPELL_CAST_START do not have a target, whereas SPELL_AURA_APPLIED always comes with a target. The latter makes sense, whereas the correct behavior for the former I couldn't say.

**Comment by brndd** [comment]
[Patch 2.0.1 API notes](http://wow.gamepedia.com/Patch_2.0.1/API_changes#Event_Changes):

> There are a number of new events:
> UNIT_SPELLCAST_DELAYED, unit
> [...]
> UNIT_SPELLCAST_SUCCEEDED, "player", spell, rank
> UNIT_SPELLCAST_CHANNEL_START, unit

Note how UNIT_SPELLCAST_SUCCEEDED has "player" listed as the first argument, while every other event has unit.

This probably suggests that it only fired for the player themselves.

**Comment by ccshiro** [comment]
Another event that has the same type of documentation:

```
UNIT_SPELLCAST_SENT, "player", spell, rank, target
```

Which is an event that only triggers for you. The conclusion being that this probably is not a bug.

If someone finds something more conclusive I'll reopen the issue at that point.
