### ISSUE TITLE
Shadow Embrace not working ?

### ISSUE THREAD

**Issue by bloodfirst92** [ccshiro/cc-buglist#1423]
I got Shadow Embrace (affliction talent) rank 1/5 and when I put my dots on a mob ( I tried on maybe 15-20 different mobs for sure ) the shadow embrace debuff doesn't appear anywhere ( combat log / recount / dotimer ).

I used it on my affli spec to boost my drain life (every affliction debuff on the target, and not only the player debuff but all affliction debuff add+5% to drain life / drain mana damage thx to Soul siphon ).

My spec when I tried : http://calculators.iradei.eu/talents/warlock.htm?5502220502031105510312350030023000000000000000000000000000000000

![wowscrnshot_081815_160155](https://cloud.githubusercontent.com/assets/13852586/9333145/847566d2-45c8-11e5-9ea2-3ed1b286ba33.jpg)

**Comment by opzor** [comment]
i guess its your addon ?quartz? ignoring and not displaying it.
try without addons

![333](https://cloud.githubusercontent.com/assets/13710937/9333413/159ae532-45ca-11e5-823b-eea38b8f26e2.png)

**Comment by bloodfirst92** [comment]
Yeah maybe Quartz or Dotimer ignoring it that's what I though but why it isn't display in the combatlog ? You got the 5/5 shadow embrace ?

Btw this is not related to the bug but what's your nameplate addon ?

**Comment by opzor** [comment]
4/5

http://calculators.iradei.eu/talents/warlock.htm?5502200102234105500310300000000000000000000505020500000000000000

self modified Aloft.
target nameplate gets bigger than other mobs :) easier to notice when it gets messy

**Comment by bloodfirst92** [comment]
I wasn't looking the good tab on combat log...\* facepalm \* my bad. It works actually, however didn't check if the soul siphon was working on it.
