### ISSUE TITLE
Kazzak's aggro.

### ISSUE THREAD

**Issue by bloodfirst92** [ccshiro/cc-buglist#1425]
On corecraft, if you're not grounded, he will get out of combat immediatly, except if you are on those pillars around him, making him staring at you and doing nothing ( probably in evade mode ). Or I actually remember really well ( and it's still the case in retail, unfortunetaly I can't fraps myself because he's overfarmed and very very rare ) that kazzak could hit you even on a flying mount and even cast spells at you. 

"The bastard can hit flying mounts- did 12200 dam to me while I was on my epic hovering in front fo him - just took 2 steps and hit me with the big sword of his. " -Runen (2.1.0)

Source : http://www.wowhead.com/npc=18728/doom-lord-kazzak#comments

**Comment by Aprics** [comment]
same with doomwalker. you can fly through him but you only get aggro on the ground.
Doomwalker should also use his stomp while patroling.
http://wowwiki.wikia.com/wiki/Doomwalker  Notes of interest

**Comment by ccnim** [comment]
Works fine atm, got hit while I was flying through him.
