### ISSUE TITLE
Pet warping up to the platform above for a split second and going in combat.

### ISSUE THREAD

**Issue by Iglooz** [ccshiro/cc-buglist#1428]
While in a steamvaults group my pet managed to warp up to the bridge above me when we swam under it, pulling a couple of mobs. This is probably just because pet pathing hasn't been perfected yet and I'm not even sure if this bug will be easy to recreate but decided to put this here regardless. Hope it helps.

**Comment by ccshiro** [comment]
As the paste said, for movement bugs you need a screenshot where the bug happens, and you've targeted the pet and written ".movegens --verbose" (without quotes) in the chat.

**Comment by ccshiro** [comment]
Will close as no further input has been provided.
