### ISSUE TITLE
[Dungeon/Visual] BM event bugged after killing the last boss(and maybe hitbox too small).

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#1432]
After killing the last boss of BM HC the event with the orcs coming out of the dark portal didn't work properly. They appeared in the portal but didn't really move out of the portal.

Also the hitbox of the last boss seemed ridiculously small. Somebody knows how big his hitbox should be? Warrior said he had to stand in the dragon to hit him.

**Comment by ccnim** [comment]
Fixed hitbox
