### ISSUE TITLE
Cursed Spirits are too weak

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1434]
In quest "Curse Upon Both of Your Clans!" when you use the Wicked Strong Fetish for the second time on the building that still is under the effect from the previous use, two spirits are spawning instead of one: "<clanname> Evil Spirit" (which is giving the quest credit on kill) and "Cursed Spirit" (additional spirit for the second use of a stick only).
According to the comments on the wowhead: http://www.wowhead.com/quest=10544/a-curse-upon-both-of-your-clans#comments
http://www.wowhead.com/npc=21449/cursed-spirit#comments
Cursed Spirit should be stronger and more annoying than the first spirit (<clanname> Evil Spirit).
However, it seems that it's really way more weak than the first spirit and the first spirit is too strong (the first spirit does ~325 dmg on cloth and hits fast while the second one does ~70 dmg on cloth and hits slow). I guess their damage and attack speeds should be swapped. Or may be that 70 dmg is completely wrong.

![wowscrnshot_081915_193847](https://cloud.githubusercontent.com/assets/5777848/9363695/8c38ae54-46b0-11e5-8a73-e011c31b7688.jpg)

**Comment by ccnim** [comment]
Fixed the values, I also made the cursed spirit a stronger version than the bladespire evil spirit due to the comment he left on the wowhead.
