### ISSUE TITLE
Spell & debuff delay/batch discussion

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1438]
## Spell & Debuff delay/batch discussion.

Link to a video and include the time and explain what happens, include frames like in the examples below.

---

https://www.youtube.com/watch?v=mj1jYoBWm3s&hd=1 
5:28 - Watch the focus target, he Counterspell the mage, takes 1-2 frames until his Arcane Missiles is interrupted, and an additional 12-13 frames until he receives a Winter's chill debuff and a Counterspell debuff.

5:37 - Cone of cold and Counterspell is cast at the exact same frame
8 frames later text indicates that Cone of cold does 476 damage
8 frames later Cone of cold debuff is applied to target and Counterspell debuff is received & target loses 5% hp from Cone of cold

05:44 - Enemy Mage finishes Polymorph cast on Mage
seems to be able to run normally for 6 frames
1 frame later he makes a sudden left move
2 frames later he is turned around facing the opposite direction and all of his spells become uncastable, even Ice Block
12 frames later mage receives the polymorph debuff and is now able to use Ice Block

07:38 - Mage casts Frost nova
16 frames later all enemies around him receives the debuff and stops moving. in the same frame the mage starts moving in the opposite direction and all of his spells becomes uncastable, even Ice Block
13 frames later the mage receives the debuff Intimidating Shout and is now able to cast Ice Block

Note that the mage in this movie seem to have 100+ ms latency, or at least at times.

---

Here's some more material:
https://www.youtube.com/watch?v=mj1jYoBWm3s&hd=1 (HD)
https://www.youtube.com/watch?v=PXCdVZeP0IYx&hd=1 (HD)
https://www.youtube.com/watch?v=YiGFcmohUcc&hd=1 (HD)
https://www.youtube.com/watch?v=4lk65YaaLzA&hd=1 (HD)
https://www.youtube.com/watch?v=AEuHcfl-3z4&hd=1 (HD)
https://www.youtube.com/watch?v=eOOUuZn5meQ
https://www.youtube.com/watch?v=sFr9MZ68zB4
https://www.youtube.com/watch?v=hPR-14dVJdc
https://www.youtube.com/watch?v=UHIIXJ8kc58

If you need a video from WCM that is available with premium only, then just let me know.

**Comment by Klimpb** [comment]
Currently on Corecraft it seems like Counterspell & Spell Lock's silence effect/debuff has got some custom delay implementation on top of the spell itself. I'm assuming the reason for this is because that's how it looked like it was on retail, however as you can see in the above examples, something similar does indeed seem to be the case. The Counterspell silence/debuff lands approximately 1 batch after the interrupt effect.

However this also seems to be the case with Intimidating shout, Polymorph, Frost Nova, Cone of Cold and many others(probably all spells?) which does not have the same "fix" as Counterspell & Spell Lock on Corecraft

Now you've also got to ask yourself if implementing something that would create/mimic this is actually desirable?

Also, is having 400ms batch intervals entirely desirable? Is it something that a lot of people will enjoy? My experience of it on Corecraft is that it feels great most of the time, but the few times where your spell lands right after a flush and you have to wait some 350+ms for it to land. That's when things can feel wrong/bad/strange, this is only the case with crowd control spells and interrupts though.

I think modifying it slightly should be considered. Reducing the batch intervals by 25% or so could reduce the amount of "weird" moments by a lot, while still remaining most of the balancing effect it has on the game.

But who knows, maybe I've just gotten used to playing on private servers where everything has been instant for these 4½ years that I haven't played retail.

**Comment by Klimpb** [comment]
Fixed links.

**Comment by Klimpb** [comment]
An interesting scenario that I thought of, trying to find retail examples of things that are possible on Corecraft.

Such as seeing a kick go off on interruptbar when you're dueling a rogue, without it interrupting you instantly. I'm interested if anyone is able to find something similar in a retail video.

Cases where it could've happened: 
https://youtu.be/mj1jYoBWm3s?t=13m9s
https://youtu.be/mj1jYoBWm3s?t=9m25s

I'm just wondering if anyone has ever seen it actually happen in a retail video?

EDIT: lol, kept watching the same video and found this:
https://youtu.be/mj1jYoBWm3s?t=13m19s

Seems like it proves that it is in fact working correctly on Corecraft. I was looking for the opposite perspective though, would be interesting as well.

There's still the debuff delay and what not going on in the retail videos though.

**Comment by dylanraga** [comment]
The delay you see with the CS/Spell Lock debuff are due to triggers being delayed. Triggered effects invoke themselves upon the next batch, as most videos will show. The problem I had with this issue is that it doesn't ALWAYS do this; sometimes the triggered effect happens the same batch as the source, and I could never really find a way to explain how or why this occurs.

**Comment by Evolvee** [comment]
Just a question: right now, if u click some channeling/casting spell (mind flay/mind vision) and in the same time jump(or interrupt it by movement), it will trigger GCD,it does not consume mana and doesnt do any effect on enemy.. just that GCD consume... this is correct?

**Comment by Klimpb** [comment]
@Evolvee Most likely no.

**Comment by Klimpb** [comment]
This has been resolved
