### ISSUE TITLE
NPC Oronok Torn-heart

### ISSUE THREAD

**Issue by klobas** [ccshiro/cc-buglist#144]
Oronok should heal you for 3500 (healing wave) when you get to 20-30%
his Domesticated Felboars should have about 30s respawn, so you can grind knothide leather, since patch 2.4 give no exp

http://www.wowhead.com/npc=21183/oronok-torn-heart#comments

http://www.wowhead.com/npc=21195/domesticated-felboar#comments

http://www.elitepvpers.com/forum/wow-guides-templates/86684-shadowmoon-npc-helps-you-grind-out-64-67-a.html

**Comment by ghost** [comment]
Currently he only heals about 2000 (tested many times), wrong rank of spell maybe? Should heal around 3000-3500 And you have to move your character for him to register that you are at low health so that he can start casting healing wave, you should be able to stand still.
