### ISSUE TITLE
Cross-faction Auctionhouse

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1450]
So I wanted to give my horde char some crafted BOE items, because no alliance players are online. I went to booty bay and was able to do 2 out of 3 auctions of interest (don't know why the third item didnt work).
I saw the auctions with my horde char, but wasn't able to buy them.
However, I've been able to cancel my auctions and receive the items via mail (though sending mails to other characters isn't possible, this works)

**Comment by lynxzor** [comment]
Did you make two accounts? You can't buy/bid on your own auctions.

**Comment by Peter1337** [comment]
Oh. I did not.Gott check this out :s

EDIT: you're right. my bad
