### ISSUE TITLE
Reflective Shield

### ISSUE THREAD

**Issue by Barroth** [ccshiro/cc-buglist#1453]
The reflect damage is way too high atm, reflects like 3k+ dmg on an ungeared priest.

**Comment by Aasamath** [comment]
Played some arena's with a priest who had 4/5 points in holy shield.
here's the result
![wowscrnshot_082315_095155](https://cloud.githubusercontent.com/assets/13113093/9427443/b15e8530-497d-11e5-9c1b-d4e82aa29364.jpg)
