### ISSUE TITLE
[Buff Stacking] Soul stone stacks on players

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1456]
Whenever two or more locks casts soulstone on the same player the buffs doesn't overlap, but stack giving the player multiple soulstones at the same time. Cannot provide proof from retail on this, but I don't think it's supposed to be like this.

**Comment by Doppelmoral** [comment]
I believe warlock no. 2 should receive an "A more powerful spell is already active" error. Couldn't find evidence myself though.

**Comment by Aprics** [comment]
here is the screen. the addon top left corner doesn't react to the 2nd SS.
![wowscrnshot_082115_161449](https://cloud.githubusercontent.com/assets/13718317/9426830/cf87fe0c-4959-11e5-94d9-08ddae6a10b0.jpg)

**Comment by Aprics** [comment]
It behaves like a spell.
shouldn't a spell of equal power reset the spell instead of giving the " A more powerful spell is already active"  error ? 
So the SS should go back to a 30 min duration on use by a second warlock.

**Comment by Ickler** [comment]
I thought I remembered -dkp for the lock that overwrote a soulstone from retail? Very vague recollection though.. But in any case, it's not supposed to stack on more Soulstones I think.
