### ISSUE TITLE
Critters keep people in combat.

### ISSUE THREAD

**Issue by GogoCC** [ccshiro/cc-buglist#1460]
Critters engaged with party keep players in combat, but do not attack. This makes it hard to find out why people are in combat and exactly which one snake or rat is "guilty". They stay in the corner or near the walls after being aoe-feared, for example. So you have to search for and kill every little creature to get out. Shattered Halls would be a nice example, though I'm not sure if Ickler's report is related as the party had "my" issue before and after gauntlet event.

**Comment by blazingsolos** [comment]
As far as I know, this is correct behavior;  If you apply a debuff to a critter (e.g. demoralizing shout, howl of terror, psychic scream), but don't kill it, it will keep members of the party in combat.  Some critters attack back, which makes it easier to get rid of them, while others simply flee.

It should however, drop combat after a certain distance is reached between the player and critter.

**Comment by Aprics** [comment]
Yes. before the first boss in SH it is obvious and likely to get the combat bug.
Either the mob stays in combat and attacks the player with the highest aggro or the mob goes out of combat (and so does the party).

**Comment by nullfoxh** [comment]
Search for "critter" 
Find https://github.com/ccshiro/cc-buglist/issues/715

**Comment by Ickler** [comment]
Apparently critters are supposed to drop combat after a while, + it appears evident that their AI broke at some point. Since I've yet to see a critter attack or flee at all on this test.

**Comment by ccshiro** [comment]
As @Ickler says seems the critter AI has broken. It's supposed to actually attack you if you aggro it indirectly.
