### ISSUE TITLE
[Underbog] Claw not behaving correctly

### ISSUE THREAD

**Issue by Balthimer** [ccshiro/cc-buglist#1463]
Claw the feral druid can be pulled separately without the boss coming. After killing him he went neutral and went and sat in the corner doing nothing. Until we killed the boss, then he went bananas on our tank and could not be targeted.

![wowscrnshot_082215_100256](https://cloud.githubusercontent.com/assets/13915057/9423117/a261634e-48b6-11e5-89b8-9f6e8cee5ba9.jpg)
![wowscrnshot_082215_100346](https://cloud.githubusercontent.com/assets/13915057/9423124/e3d872b8-48b6-11e5-8edf-80b3bd36b23b.jpg)

**Comment by ghost** [comment]
happened to us yesterday. 

The SS i provided shows the exact spot from where Claw(boss bear) was pulled by our druid tank (Verbz)

![captura de pantalla 2015-08-31 a las 20 31 00](https://cloud.githubusercontent.com/assets/13721369/9602936/fba41a2a-50ac-11e5-9e52-2767637ddd7f.png)

**Comment by petaal** [comment]
Was able to reproduce this. Claw can be pulled and killed seperately. After that he turns friendly and goes sitting by the boss. After we aggroed the boss, Windcaller Claw (in tauren form) started to attack a member of our group and didn't stop until his target was dead. We couldn't do anything to him as he was friendly.
![wowscrnshot_090315_163420](https://cloud.githubusercontent.com/assets/11743711/9662211/26d2e152-5267-11e5-8a9e-a9b39573cb56.jpg)
