### ISSUE TITLE
[Warlock][Hunter] can't send pet at Summoner Kanthin or his elemental

### ISSUE THREAD

**Issue by magikalCC** [ccshiro/cc-buglist#1465]

**Comment by Chulain** [comment]
master http://www.wowhead.com/npc=19657/summoner-kanthin
pet http://www.wowhead.com/npc=19653/glacius

confirmed, couldn't send my pet either
also tried in defensive stance

**Comment by Chulain** [comment]
2007/04/19 (Patch 2.0.12)		
The elemental now despawns when you defeat him.

3

	

snowgoon on 2007/04/19 (Patch 2.0.12)
it didn't despawn for me

12

	

doown on 2007/06/01 (Patch 2.1.0)
seems that if you don't damage the elemental, it despawns at Kanthin's death.

0

	

warlow on 2008/09/30 (Patch 2.4.3)
The elemental did not despawn for me even though I killed Kanthin without dmging the elemental

0

	

Chrome166 on 2010/08/10 (Patch 3.3.5)
Pets despawn if you kill their owners from range in one hit. In other words, kill the owner without causing the pet to aggro.
