### ISSUE TITLE
[Aura] Oil of Immolation 

### ISSUE THREAD

**Issue by Yagsick** [ccshiro/cc-buglist#1466]
http://wowwiki.wikia.com/wiki/Oil_of_Immolation
(Patch 1.6.1 (02-Aug-2005): The Oil of Immolation effect is no longer affected by bonuses to spell damage from items.)

http://imgur.com/BKxPepM

As you can see from the SS it is indeed scaling with Spellpower it should just hit for 50. Also, I can't find if flamecap scales but it should be researched because it can be abused. This damage was recorded on a 60 prot paladin vs 64 mob with 336 spell power.

**Comment by AraelWindwings** [comment]
Confirmed.
