### ISSUE TITLE
Curse of Weakness & Tainted Blood can't stack

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1468]
http://youtu.be/imUlzBojYPI

When Curse of Weakness was present on the target then my pet would never apply Tainted Blood debuffs.

Probably related to #1136 & #1133

**Comment by ccshiro** [comment]
Would be nice if we could get a video where we see them stack or such before I change it.

**Comment by Mephisto22** [comment]
I couldn't find such situation in a video but I found many statements from different people in retail-TBC era which all claim that they do stack:

http://wow.allakhazam.com/forum.html?forum=243&mid=120699942050673206   2nd and 6th post

http://www.arenajunkies.com/topic/29426-curse-of-weaknes/   10th post

http://www.arenajunkies.com/topic/27815-video-pyrilus-3-2s-and-3s/   16th post

**Comment by Klimpb** [comment]
This has been resolved, 
#1914 is a duplicate, should also be closed.
