### ISSUE TITLE
Turn Evil lasts full duration on warlock pets

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1469]
should only last 10 seconds

**Comment by Doope** [comment]
It works correctly if im not mistaken, it should last 20 sec in BC

**Comment by Klimpb** [comment]
@Doope hmm well, I'm not sure about it. Just seems strange that all other ccs lasts 10 seconds on pets, banish etc. Why would Turn Evil last 20 seconds? Tried to look for it on arenajunkies, found nothing. Haven't really seen it in any video yet.

**Comment by Chulain** [comment]
http://wowwiki.wikia.com/wiki/2.40
Turn Undead(Rank 3):This spell has been reworked and has been renamed to “Turn Evil”. It will now work on Demons in addition to Undead. Turn Evil is subject to diminishing returns, and lasts 10 seconds in PvP.
