### ISSUE TITLE
Character stuck flying upwards

### ISSUE THREAD

**Issue by Gehenas** [ccshiro/cc-buglist#147]
On a multi-monitor setup my game client is running in windowed fullscreen mode. I was on a flying mount in Outland, flying upwards by holding "space". While doing that I clicked out of the client (on the other monitor not running WoW). My character continued flying up, and when I clicked back into the game he kept doing that even when I wanted to change flying direction, I was unable to cancel flying upwards. Only solution was to press "space" once. Reproduced it several times.

**Comment by Iliana-sc** [comment]
not a bug on the server, input getting "stuck" happens on almost every game when tabbing in and out of windows
