### ISSUE TITLE
Drain spells keeps draining for full duration even after pushbacks

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1470]
https://youtu.be/II2hjUBzqDM

The debuff is supposed to shorten itself for every pushback you receive. Can be seen quite clearly in a lot of warlock videos.

**Comment by Raiilan** [comment]
With about the warlock talent "fel concentration" in affliction tree,

( 5/5 talented it give a 70% chanse of avoiding interuption caused by damage  while channeling drain life,mana,soul,

Or do i missunderstod this issue?

**Comment by Klimpb** [comment]
@raiilan keep an eye on the drain life debuff on my target, after my drain is finished the debuff is still there draining.

Has nothing to do with that talent.

**Comment by Raiilan** [comment]
Oh right,
