### ISSUE TITLE
Netherstorm: The Heap

### ISSUE THREAD

**Issue by blazingsolos** [ccshiro/cc-buglist#1472]
In The Heap, just south of Area 52;  The Zaxxis mobs are:

1: Not correctly dropping netherweave cloth.

2: The Zaxxis stalkers are Teleporting and breaking immobilizing effects when they should not.

Untested elements:  They should also be dropping Zaxxis insignias, however I haven't completed enough prerequisite quests to test this.

Corecraft: https://www.youtube.com/watch?v=piPcSIsebWU&t=19s

Retail: https://www.youtube.com/watch?v=Xl_xY7QCI5Y&t=40s

More supporting evidence: https://www.youtube.com/watch?v=beyRXulvycI&t=2m51s

**Comment by ccnim** [comment]
Fixed the netherweave and sort of fixed the teleport issue
