### ISSUE TITLE
Tenacious Earthstorm Diamond

### ISSUE THREAD

**Issue by magikalCC** [ccshiro/cc-buglist#1474]
If you inspect a player with this meta gem, and they have 5 blue gems socketed, it will appear grey. It appears green to the player wearing it.

**Comment by ConfusedCC** [comment]
If your own character meets the requirements of the meta, 5 blue gems equipped, it will appear white when you inspect the other player. 
http://i.imgur.com/1zYE8T0.jpg 
http://i.imgur.com/d3zjq9W.jpg

edited for clarity*

**Comment by magikalCC** [comment]
Yeah, should have said white.

**Comment by ccshiro** [comment]
As @ConfusedCC says, it depends on your character's requirements, not the guy you're inspecting. What you see in @ConfusedCC's screen is the intended & correct behavior. Will close this as invalid as it seems to work in those SSs.
