### ISSUE TITLE
Spellstrike Hood and Pants set bonus appears grey to everyone but the player wearing it

### ISSUE THREAD

**Issue by magikalCC** [ccshiro/cc-buglist#1475]
Even if they have 350 tailoring.

**Comment by Doppelmoral** [comment]
I haven't yet researched that but I'm confident that's how it was during retail TBC. I recall confusion about active/inactive meta gems etc. The inspected player's meta gem appears inactive for you if you as inspecting player don't meet the requirements.

**Comment by Chulain** [comment]
https://github.com/ccshiro/cc-buglist/issues/1474 related?

**Comment by ccshiro** [comment]
The expected outcome is that the set bonus is gray if you don't have 350 tailoring (even if you're inspecting someone that does), but green if you do. And that's how it works for me atm. As in it's green for me when inspecting, and I have 350 tailoring.

**Comment by ccshiro** [comment]
Will close as there's been no further input.
