### ISSUE TITLE
[Arcatraz] Wall jump/Invisible walls

### ISSUE THREAD

**Issue by Horvic** [ccshiro/cc-buglist#1487]
You are able to jump up on the bridge at the two sentinels after the second and third boss.
No invisible walls to prevent falling down.
https://www.youtube.com/watch?v=l0TWl8R0dH8

You can also run along and evade bug the two sentinels, potentially making the most difficult part of the instance trivial.
https://www.youtube.com/watch?v=b8cZ2S5A2Xo&feature=youtu.be

**Comment by ccshiro** [comment]
Client-side behavior.
