### ISSUE TITLE
Movement speed effects stacking

### ISSUE THREAD

**Issue by CarboCorecraft** [ccshiro/cc-buglist#1488]
In retail TBC there were few movement speed effects that would stack each other. Rogue class for example could stack Sprint (on-foot movement speed increased by 70%) with meta gem/feet enchant (on-foot movement speed increased by 8%) which allowed the Rogue to run with 183,6% on-foot movement speed.

Proof (https://web.archive.org/web/20080914135007/http://www.wowwiki.com/Speed):

> The highest rank of Sprint, for example, temporarily increases a Rogue's movement speed by 70% (that is, the Rogue is moving 170% of the speed of an unmodified character). If this Rogue got the Minor Speed enchantment on his boots, which gives an 8% speed bonus (allowing the Rogue to run 108% of the speed of an unmodified character when not Sprinting), he could then Sprint at 183.6% of the speed of an unmodified character (because 1.70 \* 1.08 = 1.836).

I did some testing today and these movement speed effects (both Sprint + meta gem and Sprint + feet enchant) currently don't stack each other: https://www.youtube.com/watch?v=OE6X19yCKRU 

I measured the speed with an addon called Monkey Speed (you can see it near my minimap).

p.s.:
I also have a request to a person playing hunter toon, to test whether it's possible to reach 151.6% on-foot movement speed with:

> The fastest sustainable speed on foot, not in a travel form, might consist of a Hunter with a Runeblade and the Minor Speed enchant under the influence of Aspect of the Cheetah, which would lead to a total of 151.6%

**Comment by ASrozaev** [comment]
meta gem/feet enchant 8% will add to your movement

u will get 100%+70%(sprint)+8%(chant/gem)=178%

**Comment by InvisibleJon** [comment]
@killas077  
The base movement speed 108 then, and Sprint would increase it by 70%. '' (allowing the Rogue to run 108% of the speed of an unmodified character when not Sprinting), he could then Sprint at 183.6% of the speed of an unmodified character (because 1.70 \* 1.08 = 1.836).'' As @CarboCorecraft mentioned.

**Comment by robinsch** [comment]
Are you sure this was still the case in 2.4.3?

According to SpellWork following auras should stack with other speed bonuses:
![](https://i.gyazo.com/bd2a5478ccecd402b3afd623d84627cc.png)

**Comment by CarboCorecraft** [comment]
> According to SpellWork following auras should stack with other speed bonuses
> -  robinsch

Hm, what do you mean by "other speed bonuses" ?

**Comment by robinsch** [comment]
There are 3 types of speed increases:
- main speed bonus (this will only take the highest bonus)
  for example Sprint, Ghost Wolf, Boots enchants
- stacking speed bonus
  ![](https://camo.githubusercontent.com/2eafeb27a218d4f5b3c5627131eb799ffb31ceed/68747470733a2f2f692e6779617a6f2e636f6d2f62643261353437386363656364343032623361666436323364383436323763632e706e67)
- non stacking speed bonus
  some event spells like Brewfest Ram spell (do not stack with normal movement speed or anything)
