### ISSUE TITLE
Double quest object in There Can Be Only One Response

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1490]
When you kill the Nexus-Prince Razaan and use the Collection of souls object that appears after his death, the animation of the object is shown correctly but duplicate copy of the object keeps lying on the ground.
![wowscrnshot_082215_102555](https://cloud.githubusercontent.com/assets/5777848/9429761/f490c1a8-49e4-11e5-86fe-3a1c449b74f4.jpg)

**Comment by Chulain** [comment]
http://www.wowhead.com/object=185033/collection-of-souls

also, just me or missing glowing effect on corecraft?

**Comment by netherspite** [comment]
IIRC the glowing effect was there until I looted it.
