### ISSUE TITLE
One of Ruuan'ok Ravenguards has too fast respawn timer

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1491]
This one has too fast respawn timer (~5x faster than other mobs around):
![wowscrnshot_082315_181007](https://cloud.githubusercontent.com/assets/5777848/9429770/1b7019e0-49e5-11e5-9f08-6f7d937a816d.jpg)

Or there are two spawn points because you can even get two of them at the same time:
![wowscrnshot_082315_181532](https://cloud.githubusercontent.com/assets/5777848/9429781/3b4d990e-49e5-11e5-9712-7fe58758a1be.jpg)

**Comment by netherspite** [comment]
http://www.wowhead.com/npc=19987/ruuanok-ravenguard

**Comment by ccnim** [comment]
There are 2 mobs close to each other there but both of them have the same respawn timer as the rest of the ravenguards.
