### ISSUE TITLE
A Heap of Ethereals quest cannot be accepted

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1504]
It says "You don't meet the requirements for that quest" when you attempt to take it (however it is initially displayed after you complete the previous quest in the chain).

The quest link: http://www.wowhead.com/quest=10262/a-heap-of-ethereals

![wowscrnshot_082415_115322](https://cloud.githubusercontent.com/assets/5777848/9436556/eafdb47e-4a58-11e5-8398-c7f693567c17.jpg)

**Comment by lynxzor** [comment]
#1481 
#524

**Comment by netherspite** [comment]
Yes, seems to be duplicate. Sorry.
