### ISSUE TITLE
Bessy is such unforgiving and revengeful cow

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1505]
Bessy in "When the Cows Come Home" quest can become angry at you and attack you while staying friendly (green).
Steps to reproduce:
1. Take the quest.
2. Manage her to aggro any Tormented Soul NPC.
3. Wait for the NPC to turn into Kirin'var Ghost and cast "Soulbind" on the cow.
4. Damage the NPC.
5. Let the NPC die somehow (kill it or let the cow do it).
6. Enjoy your friendly cow getting her revenge on you!
P.S. The cow can be evaded by running away and the escort can be continued after that but the bug is annoying :D

![wowscrnshot_082415_151127](https://cloud.githubusercontent.com/assets/5777848/9442743/1e7ad66a-4a86-11e5-98e0-ee95a6ab86d4.jpg)

**Comment by Chulain** [comment]
http://www.wowhead.com/npc=20415/bessy

**Comment by lynxzor** [comment]
Maybe related #1463
