### ISSUE TITLE
Mobs are staying in place instead of running to you if they can't cast their ability on you sometimes

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1506]
It's happening rarely.
And every time it happened I was forgetting or being too late in typing the movegens command or screening it.
Finally I got 2 screens with movegens verbose dump.
What exactly happens:
After you counterspell caster mob that's frozen by Frostbite or something, sometimes after the frozen debuff wears off the mob keeps staying in place instead of trying to reach you and melee you despite he can't cast anything yet.

The whelp on the first screen is already casting but he was staying in place just 0.5s ago and movegens was captured before he started to cast.

![wowscrnshot_082315_231012](https://cloud.githubusercontent.com/assets/5777848/9442868/b2cd7322-4a86-11e5-8fb8-480c485f728a.jpg)
![wowscrnshot_082415_164639](https://cloud.githubusercontent.com/assets/5777848/9442886/c42dec78-4a86-11e5-8b5e-524f2f728103.jpg)

**Comment by netherspite** [comment]
Managed to capture 1 more today.

![wowscrnshot_082515_170557](https://cloud.githubusercontent.com/assets/5777848/9469724/5891063c-4b51-11e5-994e-396b79a76214.jpg)

**Comment by ccshiro** [comment]
I think this bug should be gone now, if it still exists I'll assume someone either comments here or makes a new issue.
