### ISSUE TITLE
quest The Cipher of Damnation - Ar'tor's Charge

### ISSUE THREAD

**Issue by klobas** [ccshiro/cc-buglist#151]
mob 
http://www.wowhead.com/npc=20427/veneratus-the-many 
is not spawned by NPC following you, so it is impossible to complete the quest. Should spawn around 30,57

http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge
" After you get the quest from the hunter guy (be sure you are not mounted), he's supposed to follow you to the quest site and you'll kill a boss together (the boss looks like one of those one-eyed mobs found in Arc), which will spawn once you get to the correct location (be ready)"

npc 
http://www.wowhead.com/npc=21332/spirit-hunter
which is following you, does only 1dmg/hit. shoul have some hunter skills.

**Comment by ccnim** [comment]
Fixed the last bug and made him follow you but the script needs to be fixed so veneratus the many spawns. I think the issue lies in the script npc_veneratus_spawn_node.

**Comment by ccshiro** [comment]
@ccnim no script with that name exists.
