### ISSUE TITLE
Dr.Boom quest is not working properly

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1512]
~70% of the time when you hit him with the Bomb it does not actually damage him.
May be the target area that needs to be hit is just at the wrong location but I didn't manage to find it.
Out of 17 bombs I thrown only 3-4 damaged him.
I tried throwing bombs so he will be in the middle of the green target circle, I tried throwing bombs a little behind him and at other places. Still no luck with getting reliable hits.
He's practically unkillable as you have only 10 bomb charges on you (even if you manage somehow to heal the dynamite throw damage).
Also it seems that he throws the dynamite too often. Not sure how it was on retail but even with Ice Barrier I get 1 dynamite hit going through (1 is absorbed) while I'm staying still to cast the bomb throw.

**Comment by Kplz** [comment]
I killed him without a problem few weeks ago. Every bombs hit him, he throw dynamite when u are close to him. bomb bots working fine too.

**Comment by netherspite** [comment]
Idk about few weeks ago but right now you can't get close enough to hit him without getting hit by the dynamite + bombs do not hit him 70% of the time.

**Comment by Kplz** [comment]
I died first time, tried it again and  every bomb hit him but range looks like shorter than before.

**Comment by netherspite** [comment]
I spent a whole 30 minutes there + 3 corpseruns trying to get him below 75%.
I trust my eyes and I know I hit him with the very middle of the green circle when he didn't get any damage.

**Comment by ccshiro** [comment]
@netherspite We pushed a fix that should've solved this last night. Mind testing again, please?

**Comment by netherspite** [comment]
Just killed him, now every bomb that hits him visually damages him correctly.
