### ISSUE TITLE
Failed spells now appear as successful; out of range behavior is now wrong

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1516]
Since some of the last hotfixes, there are two new issues with the spell casting:
1. If you start to cast a spell while the target is in range and it goes out of range during the cast it should go through anyway (unless the target went too far away). It was working like that correctly but now the cast does not go through even if the target went just 1 extra yard out of range.
2. If the spell cast is failed due to out of range issue it still being shown as cast successfully by the client; but it does not damage/affect the target.

**Comment by ccshiro** [comment]
Seems to work for me. We pushed some new fixes that could've affected this last night. Could you recheck your issue, please?

**Comment by netherspite** [comment]
Works fine now, thanks.
