### ISSUE TITLE
2 Problems with tanking Shadow Labyrinth as Prot Pala

### ISSUE THREAD

**Issue by MazgarStocic** [ccshiro/cc-buglist#1517]
The first bug was that if i tried to pull the mobs that are on the 1st boss and after it with avenger's shield, it did no damage to them and it didnt actually pull them.

The only thing that happens is the animation they get hit by the shield but take no damage and get no debuff, dont get pulled or get me into combat, very bad because its the best way to pull mobs as a prot pala. 

Second one i noticed, whenever a mage polymorphed a mob in the same instance when i use judgment on them the same thing happens, they take no damage, the polymorph doesnt get broken and just the visual animation goes off. 

I dont have a video of this but I had these problems today, if u make a prot pala u can check this very fast

**Comment by ccshiro** [comment]
This should've been fixed last night. Also seems to work for me atm. Could you recheck if it works for you now, please?
