### ISSUE TITLE
Pet unresponsive

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1518]
![wowscrnshot_082615_020211](https://cloud.githubusercontent.com/assets/12783794/9482689/ea53fda0-4b96-11e5-8890-111fc2a00f3c.jpg)

was duelling and feldom pet with macro

gouge fixed it later

**Comment by ccnim** [comment]
Can't reproduce, but it's very strange that it only has the idle move gen. Should have stopped, chase or follow. See if you can reproduce it.

**Comment by ccshiro** [comment]
Some pets bugs where fixed about a month back, one of them looks very similar to this. I'll assume they were indeed the same.
