### ISSUE TITLE
Doomforge Engineer wierd combo

### ISSUE THREAD

**Issue by Saxyy** [ccshiro/cc-buglist#152]
So if you fight a Doomforge Engineer, when he slams the ground, most of the time his gonna do his Chemical Flames spell, right afterwards. When he does this, the flames gets up in the air, having no effect on the player.

I am not entirely sure that the engineer's is supposed to slam the player upwards instead of away. But the flames atleast have no effect when this happens, and it happens pretty regularly.

So definatly check out this mob. I could not find a video with a fight that lasted long enough for him to do this combo, so could not find evidence that this was not retail.

**Comment by ccnim** [comment]
Spell damage calculations doesn't seem to work on the spell either

**Comment by ccnim** [comment]
Tested this on retail and confirmed that this is actually not a bug. The damage still needs to be looked at however.
