### ISSUE TITLE
[Quest] He will walk with the earth - gives no Experience upon delivery

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1520]
The quest as mentioned above gives no experience as reward when turned in. http://www.wowhead.com/quest=9866/he-will-walk-the-earth If this is correct at least it's supposed to give some?

**Comment by Chulain** [comment]
http://db.lastwow.com/?quest=9866
0 exp

probably wrong tho

**Comment by Ickler** [comment]
If you go back to 2010 on Webarchive you get this: http://web.archive.org/web/20100502060952/http://www.wowhead.com/quest=9866/he-will-walk-the-earth

Where it gives XP + 75 rep. I'm not sure which is correct, and which is wrong. 

Nowadays Thottbot: http://www.thottbot.com/quest=9866/he-will-walk-the-earth
