### ISSUE TITLE
Shadowmoon Slayers at BT

### ISSUE THREAD

**Issue by AT-Studio** [ccshiro/cc-buglist#1523]
A pair of Shadowmoon Slayers seem to have incorrect positioning/pathing when they engage each other to fight.  They move on top of each other and face the same direction instead of facing each other with the appropriate distance between them.  There's only one pair that seems to do that, I don't have coords but they are easy to spot.

**Comment by ConfusedCC** [comment]
Looks like any pair that has to move towards eachother to enter melee range, has a chance of ending up in a wierdly looking dueling position
found 3 pairs that end up inside eachother regularly
![wowscrnshot_082615_193300](https://cloud.githubusercontent.com/assets/10581981/9501108/7c510580-4c29-11e5-92c0-952159d3a4d0.jpg)

![wowscrnshot_082615_194009](https://cloud.githubusercontent.com/assets/10581981/9501248/66b86014-4c2a-11e5-9dbf-ebfa596522da.jpg)
![wowscrnshot_082615_195751](https://cloud.githubusercontent.com/assets/10581981/9501645/c902c636-4c2c-11e5-85a2-484e88710aa6.jpg)

**Comment by KimmoKM** [comment]
There's several other (possible) issues:

I have seen the slayers killing each other, I don't think that should be able to happen:
![2015-08-31-080901_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/9572369/b1700bd0-4fb7-11e5-87c1-cd3a8d47fd5b.png)

Also, two possible issues are seen in this [video](https://www.youtube.com/watch?v=J1ZH5kIBd2E):

Firstly, the duelling slayers often (but not always) come one at a time. [Wowhead](http://www.wowhead.com/quest=10817/the-great-retribution#comments:id=75923) [comments](http://www.wowhead.com/quest=10817/the-great-retribution#comments:id=120104) mention locations where you can get single pulls so it stands to reason the duelling ones weren't single pulls.

In addition, there's the evade issue. Yes, it's actually well-documented on Wowhead comments of both the [quest](http://www.wowhead.com/quest=10817/the-great-retribution) and the [mob](http://www.wowhead.com/npc=22082/shadowmoon-slayer), but comments (and my memory) also seem to suggest it was fixed during the expansion.
