### ISSUE TITLE
Hellfire Peninsula : Zeth'Gor : Aggro through the wall 

### ISSUE THREAD

**Issue by Mechaning** [ccshiro/cc-buglist#1527]
*\* I saw that you closed a case on this issue but it's still problematic. **
https://github.com/ccshiro/cc-buglist/issues/927

Basically, the western palisade in Zeth'Gor doesn't act like a wall. Pretty much the same for the other structures in the area.  Got a nifty video for ye.
https://youtu.be/WvJxQ6bgm5o

**Comment by ccnim** [comment]
It was closed as invalid because this happened and happens on retail.
