### ISSUE TITLE
NPC Summon creature agro

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#153]
When range pulling Bonechewer Raider (npc=16925) in HFP. He summons his mount as a pet.
The pet does not start attacking the player right away (just standing there). When you cast the next spell on the Bonechewer Raider it will start attacking you.

I think this is related to all summons

**Comment by Lephidiles** [comment]
http://imgur.com/3tzqpg0,DO3Efys,zEYLRWk

**Comment by lynxzor** [comment]
Bleeding Hollow tormentors 19424 also had the same problem but the pet wolfs wouldn't do anything unless you went in range or attacked it.

**Comment by Lephidiles** [comment]
I wrote this a little bad... When you cast the next spell on Bonechewer Raider it will start attacking you if you chain pull it other vice it will just stand there until it despawns (The pictures show this just figured i update the text)

**Comment by ccshiro** [comment]
@ccnim Both of these mobs summon units with the assist summoner boolean set to false.

EDIT: Nvm, saw it wrong. It's actually the core derping it.

**Comment by Barroth** [comment]
could be sth similar to creatures not attacking, after they respawn, until the player moves
