### ISSUE TITLE
Sunfury Blood Knight's Blood Heal ability is not interruptible as it should be

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1536]
Proof: http://www.wowhead.com/npc=21089/sunfury-blood-knight#comments

**Comment by Doppelmoral** [comment]
How is his wowhead comment from 2.0.x viable proof ? I recall those mobs being immune to interrupts/kicks. There have been mobs which could not be pummeled - to avoid the heal they had to be bursted down (or, like in this case, they received a penalty which was speeding up their demise after an inevitable heal). Needs more supporting evidence.

**Comment by ghost** [comment]
Your retort was based on even less, your personal experience from half a decade ago. Wowhead is the best source of proof when a video can't be found, and that looks like it might be the case here seeing as they don't appear to be a part of a quest and thus probably don't have a video with them.

You can interrupt it on retail.
https://www.youtube.com/watch?v=FtnIS4I2kuk

**Comment by ccnim** [comment]
You cannot interrupt it, you can only silence it. Imp. kick would work for example.
