### ISSUE TITLE
[Hunter] Frost trap debuff fades too fast

### ISSUE THREAD

**Issue by justinbeaver** [ccshiro/cc-buglist#1539]
Debuff from frost trap fades too fast when you left frost trap area.

---

<b>Avada Kedavra vs Nihilum</b>
<b>00:28</b>
On the edge
![akvsnihi wmv_snapshot_00 33_ 2015 08 29_14 10 02](https://cloud.githubusercontent.com/assets/13700367/9561740/17be0526-4e5b-11e5-912e-d71b073ac78f.jpg)
![akvsnihi wmv_snapshot_00 35_ 2015 08 29_14 10 14](https://cloud.githubusercontent.com/assets/13700367/9561741/1994eb08-4e5b-11e5-976d-48bd010523fd.jpg)
Far from frost trap
![akvsnihi wmv_snapshot_00 36_ 2015 08 29_14 10 19](https://cloud.githubusercontent.com/assets/13700367/9561742/1af74cd4-4e5b-11e5-994b-894d98576fad.jpg)

<b>01:17</b>
Here you can see how pheno run out from trap area, and come back while debuff was still on him
![akvsnihi wmv_snapshot_01 17_ 2015 08 29_14 11 54](https://cloud.githubusercontent.com/assets/13700367/9561749/5df158e0-4e5b-11e5-9ff0-64641d695ec1.jpg)
![akvsnihi wmv_snapshot_01 18_ 2015 08 29_14 12 00](https://cloud.githubusercontent.com/assets/13700367/9561750/60255486-4e5b-11e5-8f0c-8fe9e885e728.jpg)
![akvsnihi wmv_snapshot_01 18_ 2015 08 29_14 12 07](https://cloud.githubusercontent.com/assets/13700367/9561751/61ecfd96-4e5b-11e5-8146-bd71fa31e2fa.jpg)
![akvsnihi wmv_snapshot_01 19_ 2015 08 29_14 12 13](https://cloud.githubusercontent.com/assets/13700367/9561752/63576e3c-4e5b-11e5-8a1a-c0ac02ccdc07.jpg)

<b>01:25</b>
![akvsnihi wmv_snapshot_01 31_ 2015 08 29_14 12 30](https://cloud.githubusercontent.com/assets/13700367/9561755/8712add2-4e5b-11e5-9b38-f66b090e5b28.jpg)
![akvsnihi wmv_snapshot_01 33_ 2015 08 29_14 12 36](https://cloud.githubusercontent.com/assets/13700367/9561756/88bd1be0-4e5b-11e5-9c61-fbced62674b0.jpg)

Frost trap is working with pulses, that's why you can run first couple yards of trap without slowing effect, and run out from trap area while slowing debuff still last for some time.

![akvsnihi wmv_snapshot_01 09_ 2015 08 29_14 11 08](https://cloud.githubusercontent.com/assets/13700367/9561774/b01a6ade-4e5c-11e5-830b-7ecdcc0f04c4.jpg)
![akvsnihi wmv_snapshot_01 09_ 2015 08 29_14 11 13](https://cloud.githubusercontent.com/assets/13700367/9561778/b240128c-4e5c-11e5-8e02-e1101ef6fe19.jpg)
![akvsnihi wmv_snapshot_01 10_ 2015 08 29_14 11 22](https://cloud.githubusercontent.com/assets/13700367/9561779/b3afe822-4e5c-11e5-93c6-156f55ae49c1.jpg)

Stream: <i>http://www.sk-gaming.com/video/766-Avada_Kedavra_vs_Nihilum</i>
SK download: <i>http://www.sk-gaming.com/file/5982-Avada_vs_Nihilum</i>

---

<b>Fauxy2 - Shadow Priest / Rogue 2v2 Arenas</b>
![untitled](https://cloud.githubusercontent.com/assets/13700367/9561799/c347aabc-4e5d-11e5-8763-72dce5db8353.png)
![untitled2](https://cloud.githubusercontent.com/assets/13700367/9561800/c6d1f9d0-4e5d-11e5-8c81-82d899d0de33.png)
![untitled4](https://cloud.githubusercontent.com/assets/13700367/9561801/c9e2d4aa-4e5d-11e5-9028-94d10c4fe280.png)
<i>https://youtu.be/qcpxr4WisKM?list=WL&t=304</i>

---

<b>Korea Starcraft Players vs Ocean Madness</b>
<b>03:10</b>
![ksp_vs_ocean_madness_cyclonetour2 avi_snapshot_03 15_ 2015 08 29_14 17 59](https://cloud.githubusercontent.com/assets/13700367/9561837/36c2407c-4e60-11e5-83b0-86c9cf2d8f00.jpg)
![ksp_vs_ocean_madness_cyclonetour2 avi_snapshot_03 16_ 2015 08 29_14 18 24](https://cloud.githubusercontent.com/assets/13700367/9561839/39157ee8-4e60-11e5-999f-7dcfab94ef0d.jpg)
![ksp_vs_ocean_madness_cyclonetour2 avi_snapshot_03 16_ 2015 08 29_14 18 31](https://cloud.githubusercontent.com/assets/13700367/9561840/3acc577a-4e60-11e5-9b46-905cdb360624.jpg)
SK download: <i>http://www.sk-gaming.com/file/6422-KSP_vs_Ocean_Mad</I>

---

<b>Some random screens</b>
Far from trap area
![akvscfr wmv_snapshot_01 01_ 2015 08 29_15 49 14](https://cloud.githubusercontent.com/assets/13700367/9561977/84663530-4e66-11e5-9294-9f4041145965.jpg)
![avada_kedavra_vs_nihilum_v wmv_snapshot_02 24_ 2015 08 29_15 51 09](https://cloud.githubusercontent.com/assets/13700367/9561979/8618eae4-4e66-11e5-8104-dd843fae27d3.jpg)
![swarm3 wmv_snapshot_04 02_ 2015 08 29_15 53 20](https://cloud.githubusercontent.com/assets/13700367/9561980/87195b18-4e66-11e5-9008-25bfad69d9cf.jpg)
from this movies and random 5v5 movies where you can see frost trap, you have to download them (except the first one)
<i>http://www.sk-gaming.com/file/5970-Avada_vs_CHICKEN
http://www.sk-gaming.com/download/6950
http://www.sk-gaming.com/download/5939
http://www.sk-gaming.com/download/5981
http://www.sk-gaming.com/file/6229-Swarm_3__BG9_5v5</i>

---

<b>Right now it fades immediately</b>
1.
![wowscrnshot_082915_150216](https://cloud.githubusercontent.com/assets/13700367/9561878/243681f0-4e62-11e5-9749-ed14c19b28f2.jpg)
![wowscrnshot_082915_150219](https://cloud.githubusercontent.com/assets/13700367/9561879/2681be8e-4e62-11e5-92eb-93d524edd1c4.jpg)
2.
![wowscrnshot_082915_150222](https://cloud.githubusercontent.com/assets/13700367/9561883/2cadad18-4e62-11e5-9bc5-1ead2a333028.jpg)
![wowscrnshot_082915_150226](https://cloud.githubusercontent.com/assets/13700367/9561884/2ee6170a-4e62-11e5-94dd-4c33b67b171d.jpg)
<b>When you're pass this spot, it fades immediately</b>, that's why such a big steps at screens above
![wowscrnshot_081231232915_150155](https://cloud.githubusercontent.com/assets/13700367/9561888/60697d08-4e62-11e5-9064-822992ddfb01.jpg)

---

With debuff will be more fair, when opponent kiting you over the pillar.
He will pass first couple yards without slowing, but he will be slowed for some yards after he left the trap.

**Comment by ccshiro** [comment]
This is due to the affected target check timer being too frequent on mangos. This was fixed some time back on another issue (can't remember which). Should be working now.
