### ISSUE TITLE
[Mage] Serpent-Coil Band not affecting mana emerald

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1544]
As title says, the Serpent-Coil Band doesn't affect the mana return of Mana Emerald. It's supposed to increase by 25%, but I received a close to minimal (2925) mana back when using it.

**Comment by ccshiro** [comment]
Actually, the trinket works fine. What confused me, and I'm assuming yourself as well, is that the tooltip on the mana gem actually updates when you equip the trinket. Mana Emerald does 2340-2460 without the trinket, when you equip it the tooltip (and effect) updates to 2925-3075.
