### ISSUE TITLE
[Botanica] Warp Splinter

### ISSUE THREAD

**Issue by opzor** [ccshiro/cc-buglist#1548]
His ability Arcane Volley hits the players in 360 degrees circle if they stand less than 30yrs from boss.

---

Some of the strategy for this boss is to:
"The Arcane Volley can be avoided by clever positioning of the DPS. If he is turned around and his back faces the group, those directly behind will not be hit; people off to the side (in the grass) will still be hit."
http://wowwiki.wikia.com/wiki/Warp_Splinter

Problem on corecraft is that it only works if you are standing more than 30yards from boss.

We got everyone stand behind him (dps max range >30yrds) and a healer (<30yrds) and healer was getting hit by Arcane Volley.

It may be related somehow to Warstomp ability because healer was hit by it (correct) and DPS not.

**Comment by ConfusedCC** [comment]
Here is a video showing two rogues in slightly different positions behind warp splinter , where they both are getting first warstomped 3:45 then arcane volleyed 3:47 .
the other rogue in the party seems to be stationed pretty perfectly behind the boss(and he still gets hit).
https://youtu.be/kIdFNRxptEU?t=3m44s

**Comment by opzor** [comment]
And here is a video showing that only mele got hit by arcane voley.
https://youtu.be/6tdg8WqK2hg?t=2m35s

**Comment by ccnim** [comment]
This is client side.

**Comment by opzor** [comment]
range of spells and arc they do damage in is client side?
