### ISSUE TITLE
[Warlock] Succubus Seduction

### ISSUE THREAD

**Issue by opzor** [ccshiro/cc-buglist#1549]
Succubus Seduction ability works only if mob have Mana Bar. 

If mob does not have mana bar succubus just run behind this mob and starts to mele... does not even try to cast seduction.

Noticed on mobs in SH (hellfire) and Mechnar. (think this is global issue and not only those 2 instances)

Reproduction:
Can reproduce it fast on first group in Mechnar since there is group of 3 mobs mixed melee/casters.
Bloodwarder Physician (caster) - Seduce is working
Sunseeker Netherbinder (caster) - Seduce is working
Bloodwarder Centurion (mele) - Seduce is NOT working  (but FEAR is working so it is possible to CC this mob)

**Comment by opzor** [comment]
Steamvault
Coilfang Engineer (mele) - seduce is working
Coilfang Warrior (mele) - seduce is NOT working (but FEAR is working so it is possible to CC this mob)

**Comment by opzor** [comment]
It appears that seduction is conditioned as a Mind Control because same mobs that cannot be MCed also cannot be Seduced.... (noticed in SH Helfire) which by itself can be a problem with Mind Control.

but in patch notes it states:
http://wowwiki.wikia.com/wiki/Patch_1.4.0
Seduction (Succubus) - Is now considered a Fear effect for purposes of diminishing returns.

in theory you should be able to Seduce whichever mob you can Fear.

**Comment by ccshiro** [comment]
DR has nothing to do with mechanic immunities. Seduction counts as a charm effect and NPCs that are immune to charm will be immune to seduction. Bloodwarder Centurion is an NPC immune to charm (on heroic, not normal). In other words, working as intended.

**Comment by opzor** [comment]
thanks for the info. you are right, it is a charm....

but still it appears that immunities are not consistent with those of Mind Control. 
It seems that you are able to seduce mobs that are susceptible to being Frozen (and are humanoids).

i will make list of mobs that we should be able to seduce (with some proof) and post as a new issue.
