### ISSUE TITLE
[Hunter] Pet pathing on Circle of Blood/Blade's Edge Arena

### ISSUE THREAD

**Issue by justinbeaver** [ccshiro/cc-buglist#1556]
Tested on Circle of Blood.
Not sure if they share the same geodata.

Pet going on the rope only if enemy staying on it, if enemy not on the rope then pet don't go over it.
He stay at the bottom of the pillar, sometimes running by air if enemy close to the edge.
He don't attack enemy on the same pillar.

Lots of screenshots, sorry for that
http://imgur.com/a/2lloN
And I'll leave some here
![wowscrnshot_083015_010538](https://cloud.githubusercontent.com/assets/13700367/9564648/a94a3ee6-4eb6-11e5-82f2-018e43c4c72a.jpg)
![wowscrnshot_083015_010640](https://cloud.githubusercontent.com/assets/13700367/9564650/af96fba4-4eb6-11e5-9369-39dc334ac0af.jpg)
![wowscrnshot_083015_010722](https://cloud.githubusercontent.com/assets/13700367/9564653/bf5437be-4eb6-11e5-8c65-bfba5b190ba0.jpg)
![wowscrnshot_083015_010744](https://cloud.githubusercontent.com/assets/13700367/9564654/c5ab75be-4eb6-11e5-99de-78c567647025.jpg)
![wowscrnshot_083015_011026](https://cloud.githubusercontent.com/assets/13700367/9564656/d59ac128-4eb6-11e5-9d51-760ba7469c9d.jpg)

**Comment by justinbeaver** [comment]
Pet pathing from retail movies on BGs

Not sure how it works on CC right now, but I'll leave it here could be useful

![1](https://cloud.githubusercontent.com/assets/13700367/9564661/243c6d86-4eb7-11e5-8a4e-15ba19ea2ad4.png)
<i>https://youtu.be/6WHcQwl7Nd0?t=102</i>

![2](https://cloud.githubusercontent.com/assets/13700367/9564662/289b3560-4eb7-11e5-8bae-e0db52ffdcd8.png)
<i>https://youtu.be/6WHcQwl7Nd0?t=286</i>

![3](https://cloud.githubusercontent.com/assets/13700367/9564663/2bdde7e0-4eb7-11e5-99e4-1fd6ba7cda98.png)
<i>https://youtu.be/o-S9sDhN5IY?t=84</i>

Maybe if hunter can jump over an obstacle then pet can run over it too

**Comment by ccshiro** [comment]
The data in the arena is different. Could you open a new one if it works the same in the actual arena?
