### ISSUE TITLE
[Dungeon] Heroic boss not dropping Badge of Justice

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#1558]
As for issue #1253 (labeled as closed and solved 3 days ago) the boss "Blood Guard Porung" didn't drop any Badge of Justice after defeating him in heroic mode. I forgot to provide evidence with a screenshot, and for that I am really sorry, but I hope you guys can trust me enough to double check the problem again.

Thanks a lot

**Comment by ccnim** [comment]
This hasn't been applied to the server yet.
