### ISSUE TITLE
[Dungeon] Heroic Shattered Halls combat bug.

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#1559]
During "Blood Guard Porung" event we experienced (all party members) a "still in combat" situation. We tryed to kill all the critters in the area after the boss event, they sometimes are the cause for it, but not in this case. We had to logout with alt+f4 and then log back in. The event went well, the scripting was ok. Just this combat bug after killing the boss was the problem.

Thank you.

**Comment by ccnim** [comment]
#1458
