### ISSUE TITLE
Forged Illidari Bane Blade world object

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1564]
As you can see from the following screenshot, object Forged Illidari Bane Blade is present in the world. It's supposed to be involved in quest [Quenching the Blade](http://www.wowhead.com/quest=10679/quenching-the-blade) in which a quest item is provided and the player is supposed to use it at the pools before looting it. By the looks of it the object is already there, most likely without anyone having done the quest.

![2015-08-31-071945_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/9572091/ee0ffa06-4fb1-11e5-8bb0-d29ae9691d8a.png)

**Comment by ghost** [comment]
maybe someone did the quest before you and it dindt despawn?

**Comment by KimmoKM** [comment]
Possible, will be easy to check after server restart
