### ISSUE TITLE
[Spell][Dungeon] Fear Ward being bypassed in underbog

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1567]
The stingers Psychic scream bypasses Fear Ward as can be seen in the screenshots

steps to reproduce:
1.cast fear ward on tank
2.wait for stingers to cast psychic scream
3.tank gets feared

![captura de pantalla 2015-08-31 a las 20 27 02](https://cloud.githubusercontent.com/assets/13721369/9588031/1b92cebc-5026-11e5-95f9-04e71317d50b.png)
![captura de pantalla 2015-08-31 a las 20 27 38](https://cloud.githubusercontent.com/assets/13721369/9588032/1ba0069a-5026-11e5-9d40-0bcfe128e234.png)

**Comment by Barroth** [comment]
looks like this is actually correct, see http://www.wowhead.com/npc=17731/fen-ray#comments

Apparently it is an horror effect that won't be affected by fear immunities/dispels

**Comment by ghost** [comment]
you are right, closing this
