### ISSUE TITLE
Weird Gouge behaviour

### ISSUE THREAD

**Issue by Mustonen1** [ccshiro/cc-buglist#157]
https://www.youtube.com/watch?v=9CXDK3nyhDM

Video shows it pretty well. Can't use positional skills like mutilate while seemingly being behind the target. Doesn't happen very often though.

**Comment by Mustonen1** [comment]
Duplicate of #141 and possibly #96

**Comment by Lobogo** [comment]
Actually, the only broken thing there is that after gouge, the mob should NOT turn around
but it looks like just visual bug - the mob appears turned around but he is not in fact
