### ISSUE TITLE
[Spell] Will of the Forsaken does not break Charm in Arcatraz

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1580]
WoTF wil not break charm effect casted by Spiteful mistress (screen)

steps to reproduce:
1.go arca being undead
2.confront this mob
3.wait for charm effect
4. try to WoTF out of it
5. error
![captura de pantalla 2015-09-01 a las 17 51 21](https://cloud.githubusercontent.com/assets/13721369/9620327/5381baba-5119-11e5-8749-c08885afc6a1.png)

**Comment by Chulain** [comment]
npc: http://www.wowhead.com/npc=20883/spiteful-temptress
spell: http://www.wowhead.com/spell=36866/domination

Apply Aura: Charm
Value: 70
