### ISSUE TITLE
[Halaa] Empty and not capturable

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1582]
self explanatory. no idea what caused this

steps to reproduce:
1. fly to halaa
2. freak out
![captura de pantalla 2015-09-02 a las 0 40 10](https://cloud.githubusercontent.com/assets/13721369/9620485/e1534e84-511a-11e5-87ed-6991732c26f4.png)
![captura de pantalla 2015-09-02 a las 0 41 01](https://cloud.githubusercontent.com/assets/13721369/9620494/f83b35c6-511a-11e5-90a5-de838b7158d8.png)
![Uploading Captura de pantalla 2015-09-02 a las 0.41.04.png…]()

**Comment by ccnim** [comment]
You cannot capture it while flying. Were you flying when you tried to capture it?

**Comment by Aasamath** [comment]
Just captured it on horde, working on foot and ground mount. Not working on flying mount even while landed.
Gonna take it back on Alliance, but so far so good.

**Comment by ghost** [comment]
dindt try to capture it since i dindt feel it was possible. as can be seen on the first SS, the bomb cartridges to get on the flying wyvern and capture was not visible, i dindt land, however i dont think landing would make the bomb cartridges appear.

then i proceeded into halaa into my flying mount (without dismounting) to find it EMPTY, while i dindt try to capture it, it should not be empty.

@Aasamath there has been some crashes between my SSs and today, so prolly the server restarted halaa too

**Comment by Aasamath** [comment]
Yes i think the empty city is due to restart. About the bombs it might be because the "attack" phase was ended. So you didn't gets bombs since the city was already in "capture " phase. I'm attacking Halaa at the moment and i get bomb everytime (unlless i got some left on me), i'll check if i still get any once all guards are dead.
Could also be  a bug due to the city being neutral, since it ain't suppose to happen.

**Comment by ghost** [comment]
i guess this can remain "dormant" until someone claims the happening again? since i cant really provide any more info about this =(

**Comment by Aasamath** [comment]
yeah i'll try to remember to go there, after next crash.

**Comment by ghost** [comment]
i think you got me wrong, this state (empty) happened BEFORE the crashes, something might have triggered it, and when the server crashed, halaa got restarted and back to working

**Comment by Aasamath** [comment]
Ah ok, my bad. Halaa was also empty when i arrived, but flag was horde, and city was capped just an inch for horde too.

**Comment by netherspite** [comment]
Was it red horde flag or grey horde flag?
IIRC it will become 'horde' grey flag when horde starts capturing it but it won't be captured completely until progress bar reaches its horde end.

**Comment by ghost** [comment]
tbh i could swear the map showed halaa as alliance. dindt really notice that the flag was actually grey

**Comment by Aasamath** [comment]
@netherspite I"m pretty sure flag was already red even if the capture wasn't finished (on cc). I didn't come across a flag like Sergio's screenshot.
When i captured it later on alliance, horde flag changed to alliance but didn't go grey at any time.

**Comment by Barroth** [comment]
The flag immediatly changes to horde/alliance flag, see here: https://www.youtube.com/watch?v=USPHP6a9IaI
