### ISSUE TITLE
Resistance abnormally high?

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#1599]
I was doing the Noggenfogger Quest today, thought I'd just mindblast some guys in tanaris but no deal.
Couldn't believe my eyes when i only hit for 300-500. Checked Combat log, seems mobs 25 lvls below mine can resist 80% of my spell.

![low level resist](https://cloud.githubusercontent.com/assets/14063689/9648663/1fbea38c-51eb-11e5-8d55-75c70849b928.jpg)

Sorry the combatlog is german, couldn't figure out how to make the entire game english. Shouldn't be too hard to interpret though.
Resisting my spell didn't happen only 1 out of 2 times, but most of the time. I got pretty lucky to at least hit SW:D fully.

![low level resist 2](https://cloud.githubusercontent.com/assets/14063689/9648754/4241e6b6-51ec-11e5-9839-339bbb9a6372.jpg)

Shouldn't make a difference one way or the other, but just to show the shitty pre70 blues weren't responsible. Interestingly enough, while it does happen to SW:P and VT as well (to much lesser effect), Mind Flay does not seem to suffer from the issue:

![low level resist 3](https://cloud.githubusercontent.com/assets/14063689/9648807/da8e94fa-51ec-11e5-9467-2b85b826785c.jpg)

![low level resist 4](https://cloud.githubusercontent.com/assets/14063689/9648832/29698a44-51ed-11e5-8d43-5601c4008861.jpg)

edit: This seems to be an issue with those specific mobs, as I could hit and damage other mobs in Tanaris normally.

**Comment by Barroth** [comment]
that npc got 96 on all resistances

**Comment by Doppelmoral** [comment]
^ That would make it practically immune at its respective level range no ?

**Comment by Barroth** [comment]
Against a level 70 caster the spells are by average reduced by 20.57%
(see http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance?oldid=1561356)

Which leads to the mob having a big 25% resist chance, a little 50% resist chance and a very small 75% resist chance to partially resist a nonbinary spell.

Since Binary spells cannot be partially resisted, you won't see it happen on the Mindflay damage. Instead Mindflay has a higher chance to be completly resisted.

**Comment by Ickler** [comment]
If these were like that, I would make a guess that the same type of mobs in Wailing Caverns are the same. At least I've seen that on other servers.
