### ISSUE TITLE
Ghost Wolf & Weapon Imbues

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#16]
Report: "Enhancement Weapon Imbues: should not proc of attacks done in ghost wolf".

Question: Is this correct? A video, screenshot or reliable textual source would be sufficient to prove this.

**Comment by FurioCC** [comment]
WoWWiki 2007-Oct-27
http://www.wowwiki.com/Ghost_Wolf?oldid=1647530
"Some weapon buffs' effect are not active (like Flametongue Weapon, Windfury Weapon and Frostbrand Weapon."
"If Rockbiter Weapon has been cast prior to becoming a wolf and the shaman keeps that weapon equipped, it will significantly increase the damage done with each bite."

**Comment by Doppelmoral** [comment]
Sidenote: The same should apply to enchantment procs (Mongoose, etc) - as it counts for druid shapeshifts and weapon proccs. They need to be disabled while under Ghostwolf
