### ISSUE TITLE
NPC : Kirin'Var Ghost

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#160]
The NPC "Kirin'Var Ghost" in Netherstorm, Chapel Yard, cast the spell "Soulbind", but it doesn't do anything (neither to me or the NPC) ==> http://snag.gy/BvbiC.jpg (combat log)

**Comment by FurioCC** [comment]
Tested it, confirming, players not getting debuff when NPC completes cast.

**Comment by ccnim** [comment]
Script effect needs implementing. spellid: 36153.
