### ISSUE TITLE
[Hunter] macro "/cast !auto shot"

### ISSUE THREAD

**Issue by TheVcelar** [ccshiro/cc-buglist#1602]
macro "/cast !auto shot" is broken

what should happen:
when you spam this macro, auto shots should normaly go off

whats the problem:
the exclamation mark in macro is ignored and when you spam macro, you keep arming and disarming your range weapon you does not shoot

**Comment by Aasamath** [comment]
It's the same for wands. the !  should prevent the toggle on and toggle off of the spell. But i don't know if it should reset the arming animation.
