### ISSUE TITLE
[Shaman] Earth shield should be able to crit

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1604]
Tested on more than 100 procs, not a single one was a crit.

http://www.wowhead.com/spell=974/earth-shield#comments
http://wowwiki.wikia.com/wiki/Earth_Shield

EDIT: But ES crits shouldn't proc Ancestral Healing

**Comment by Peonstomperx** [comment]
It should use the targets spell crit?

 Wrath-Logo-Small Patch 3.0.8 (2009-01-20): Now correctly uses the Shaman’s own spell critical strike chance to determine the chance of a critical heal.

**Comment by Jumpka** [comment]
Ye, well according to this it used the target's spell crit on retail, but it looks like a mistake and since they won't even implement sealtwisting because they refer to it as a bug, who knows what will they do with this. 
(btw tested it selfcasted, got about 15 healing wave crits and no ES crit in the same number of casts/procs)
