### ISSUE TITLE
The Art of Fel Reaver Maintenance should drop from the chest and not from the mobs

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1605]
According to the quest text and comments on wowhead: http://www.wowhead.com/quest=10606/the-art-of-fel-reaver-maintenance#comments
Quest item should drop from the chest only, not from the mobs.
I've got the drop from Gan'arg Technician.

![wowscrnshot_090315_154724](https://cloud.githubusercontent.com/assets/5777848/9668943/0790ae70-528d-11e5-9595-0612d5da901f.jpg)

**Comment by KimmoKM** [comment]
If you look at the [item](http://www.wowhead.com/item=30713/the-art-of-fel-reaver-maintenance), Wowhead seems to think it can drop from the mobs. Doesn't make sense considering the quest description, I don't recall it ever dropping and I would expect such a thing being mentioned in quest description if it was the case, though.

**Comment by netherspite** [comment]
May be it was added later at the retail or it's the wrong information from private servers.
Also comments on wowhead say that it drops from the chest.
Why would one open the chest if you just need to kill the mob?

**Comment by KimmoKM** [comment]
@netherspite 
True, it's hardly unprecedented for Wowhead to display incorrect information. I agree the functionality in TBC probably required you to loot the chest with no alternative ways for getting the manual.
