### ISSUE TITLE
I Was A Lot Of Things... is broken

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1607]
I tried using the whistle many times at many tubers but felboars didn't come.
Tried clearing the place of flayers - didn't help.

![wowscrnshot_090315_155817](https://cloud.githubusercontent.com/assets/5777848/9669035/8cf2184c-528d-11e5-89c4-3dd9fb0a21b1.jpg)

**Comment by KimmoKM** [comment]
The range of the whistle might be too low, I didn't have any issue when the boars were close by (<15yd from the tuber).

**Comment by netherspite** [comment]
You mean there should be a felboar close to the tuber when you use the whistle?
In that case I'm wrong and there's no issue. Will check that again.

**Comment by KimmoKM** [comment]
[Comments](http://www.wowhead.com/quest=10514/i-was-a-lot-of-things#comments:id=26528) in Wowhead seem to suggest you have to be close to the boars (and right on top of the tuber) when using the whistle. Commentary to quest video in https://youtu.be/5Tdchy-zSY4?t=1m6s also mentions boars have to be "quite close by".

Regardless of if the maximum range is correct on CC or not (I wouldn't rule out the possibility the range is too short), I haven't seen any issue if the boars were near the tuber, it worked every time for me.

**Comment by netherspite** [comment]
Yes it works. However there is another issue. I'll close this one and create new.
