### ISSUE TITLE
[PvE Mechanics] Mob's attack too fast

### ISSUE THREAD

**Issue by Thimtheslim** [ccshiro/cc-buglist#161]
It seems the damage you take from mobs (I tested in Hellfire and Forest) is higher than retail (or other servers). It's not the actual damage they do, but the attack speed.

For example: I'm being used to get hit every 1 or 1.5 seconds.
On Corecraft you get multiple hits (2-4) in 1-2 seconds, meaning you get hit every 0.5 or 1 second.

Big problem for melee. Needs further research.

**Comment by ccshiro** [comment]
You need actual examples. Almost all mobs have the correct attack speed, but of course some mobs might still be wrong.

**Comment by Thimtheslim** [comment]
From what I felt (very obvious) the following mob's had to high attack speed:
All mobs from the quest http://www.wowhead.com/quest=9747/the-umbrafen-tribe
Alls mobs from the quest http://www.wowhead.com/quest=10868/arakkoa-war-path

Haven't had other obvious encounters where I took way too much damage. (The orc's and wrathguards in Hellfire seemed fine)

**Comment by Piranhaz** [comment]
Tested SL(normal difficult) with 3 ppl in t5 for fun. 1Pala tank, 1War, 1RSham. We took a lot of dmg from trash mobs that made me think: wow this can't be real, maybe they got too high attack speed too, i don't know, but the dmg felt insane.

**Comment by ccnim** [comment]
It seems to be working correctly, there are some weird moments when the mob is dual wielding where it will hit 2 times, 2 times, 3 times, 1 time.

**Comment by Thimtheslim** [comment]
Make a warrior on corecraft and another private server ~ level 60 - 62. You will find that you will take a lot more damage on corecraft. I can't remember taking this much damage on retail. On corecraft you can kill 2-3 mobs with full Nax/AQ40 geared fury warrior without drinking. On retail you could kill a lot more (5-7).
Need some more reports.

**Comment by ccnim** [comment]
All mobs have been fixed and therefor do more damage as a result. Maybe you forgot to .maxskill yourself and ran around with low defense skill?

**Comment by ccshiro** [comment]
Did some debugging, swing timer seems to work as intended.
