### ISSUE TITLE
One of the Ashtongue Handler + Elekk Demolisher groups in Ruins of Baa'ri has weird waypoints

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1610]
They seem to be patrolling back and forth between two points.
However, they waypoints seem to be wrong.

![wowscrnshot_090315_161616_edited](https://cloud.githubusercontent.com/assets/5777848/9669254/8e445de4-528e-11e5-9460-2925d492ec7f.jpg)

They walk from point A to point B then to point C correctly.
After that they _run_ back to point B and walk to point C again.
After that they correctly walk back to point B and then to point A.
After that they again _run_ back to point B and walk to point A one more time.
(then the loop repeats)

**Comment by ccnim** [comment]
only one of the mobs is running to try and get in formation.
