### ISSUE TITLE
[BRD] Bosses & mobs that dont use abilities

### ISSUE THREAD

**Issue by Soyoen** [ccshiro/cc-buglist#1615]
Lord Incendius
Fineous Darkvire (who also doesn't go along his basic patrol route and just stand still)
Twilight Emissary
Twilight Bodyguard
Warder Stilgiss
Verek
Pyromancer Loregrain
Ring of Law boss spawns

**Comment by ccnim** [comment]
Vanilla dungeons are not yet done
