### ISSUE TITLE
[BRD] Bridge guard spawn trigger

### ISSUE THREAD

**Issue by Soyoen** [ccshiro/cc-buglist#1617]
The brdge between the arena and the vault area is missing the trigger to spawn the dual guards, instead they are spawned and hid away in the corner from the getgo. Both should spawn and run towards the middle of the bridge after you pass a certain trigger point midbridge.

In combination the fireguard destroyer is missing his patrol on the same bridge.

**Comment by ccshiro** [comment]
There's no point in reporting individual bugs in BRD, the task for the instance is still open which means it has not been looked at yet: #403.
