### ISSUE TITLE
[PvP Mechanics] Delay on interrupt

### ISSUE THREAD

**Issue by Thimtheslim** [ccshiro/cc-buglist#162]
It seems there is a delay on the server concerning interrupts (sometimes also other spells). When you interrupt (I tried counterspell and pummel) it still takes a few milliseconds for it to cause effect (like .3 - .5 seconds), meaning you sometimes don't interrupt at all.

Generally the server doesn't really feel 'smooth' even though I have low ms (ingame-bar: 34, quartz: <50) and high fps (>60).

**Comment by Iliana-sc** [comment]
not a bug, worked the same on retail from vanilla up to and including mists of pandaria

**Comment by braide** [comment]
I agree with Thimtheslim. I know there was a little delay on retail, but not close to the current one regarding interrupts. I remember interrupting at the last 0.2-0.1 seconds to counter fake casting a bit. The delay also feels inconsistent, as in sometimes it feels like it's longer. Might have to do something with the server but it also said that I had good ms. The old retail delay is not a good thing, the blizz devs said so themselves so I don't fully agree on implementing it.

The server does not feel smooth at all, more like inconsistent with attack delays.

**Comment by jessyo** [comment]
I agree with Thimtheslim and Braide.

This is pretty much very related to my ticket (https://github.com/ccshiro/cc-buglist/issues/168).
