### ISSUE TITLE
[NPC] Collidus the Warp-Watcher

### ISSUE THREAD

**Issue by Azubal** [ccshiro/cc-buglist#1622]
his abilitie '' Focused Bursts '' Does no damage, and he should be Immune to snares and slowing effects, his blink abilitie still missing too + he's got low HP

Note : many of Elite rares have been nerfed in the past ( from what i read in multiple wowhead comments ) in the past for example in the 2.0.6 version rare elite where 5 man fight and had like + 75k HP each one of them ), and players should be able to kite them like shown in this video https://www.youtube.com/watch?v=CEYbOA54KhE

Actually on CC : https://www.youtube.com/watch?v=BxYuSajRoRA&feature=youtu.be

Source > wowhead comments : http://www.wowhead.com/npc=18694/collidus-the-warp-watcher#comments

**Comment by ccnim** [comment]
#1103
