### ISSUE TITLE
Horde trauma quest glitch

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1636]
Can't interact with NPC to comlete Horde Trauma quest (First Aid 225+ quest). I'am in dialoge range, press mouse right button and nothing happens, no message, no NPC respond, nothing.
![wowscrnshot_090415_224029](https://cloud.githubusercontent.com/assets/13764565/9686462/b8ef10e8-5356-11e5-85ee-6589e51ef633.jpg)
![wowscrnshot_090415_223806](https://cloud.githubusercontent.com/assets/13764565/9686424/8e2ae83c-5356-11e5-899e-1d9f78dd4eec.jpg)

**Comment by KimmoKM** [comment]
#1138 shows at least someone was able to interact with the NPC. I couldn't either, however.
