### ISSUE TITLE
Kraator rare elite should not be slowable

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1637]
He was affected by my frostbolt debuff.
He should be immune to snares according to wowhead comment from patch 2.0.8:
http://www.wowhead.com/npc=18696/kraator#comments
He was later nerfed (in 2.4) but in 2.0.1 state it should not be slowable.

**Comment by demerda22** [comment]
Omfg nobody cares!!!
Just let them release this shit already

**Comment by netherspite** [comment]
And let you solo farm that rare elite?
