### ISSUE TITLE
Creature AI should prioritize unfeared targets

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1638]
He should prioritize attacking other targets when the tank is feared according to wowhead comments:
http://www.wowhead.com/npc=21102/uvuros#comments

**Comment by KimmoKM** [comment]
2.3.0 patch notes: "Creature AI has been changed to no longer prioritize attacking unfeared targets over feared targets."

Comments advising special measures seem to be from earlier than that.

**Comment by netherspite** [comment]
Server will be in 2.0.1 state so this should be changed.

**Comment by KimmoKM** [comment]
In that case it'd probably be a mechanics issue, not related to Uvuros specifically.

**Comment by ghost** [comment]
@KimmoKM 
You may be correct in that it is not specific to Uvuros but there may be a special case. Blood Guard Porung, of heroic Shattered Halls, has a fear ability that he casts on the tank. When we were fighting him last night he feared me (tank) and went to attack other members of the group (during the duration of the fear).

**Comment by Azubal** [comment]
there is a similair issue with Kraator ( a rare elite in SMV ) who keep's hitting the conflagged tank.
