### ISSUE TITLE
Umbrafen Village multiple bugs - Zangarmarsh

### ISSUE THREAD

**Issue by Sinergyy** [ccshiro/cc-buglist#164]
Hello. I was investigating a bug regarding fear and dropping through the ground and found out other bugs. 

Location: http://i.imgur.com/EqoJTR6.jpg

Basically some of the mobs put down a "Terror Totem". The biggest problem here is that they fear people around it and during that 1 second fear you get to run such a long distance. Sometimes it's just as you blink from one position to another and back, and other times it's like you have some kind of speed buff on you and you run like crazy.  

Something is definitely not right with it. Tested it with my friend multiple times and the movement from that fear is just crazy. 

The second bug here is that they should cast a buff named "Umbrafen Buff". Link to wowhead: http://www.wowhead.com/spell=34871/umbrafen-buff#comments

Well, this buff should give +3 Stamina to allies (that means to other mobs) but instead they give +47 Stamina to the others. Which for a player lvl 61 is a huge amount to deal with as they have fear+stun and there are multiple mobs. 

Third bug: Sometimes you are dazed and feared in the same time. If you are dazed, how can you move? But instead, sometimes the animation goes crazy and visually is just like you blink from here to there, back and forth. 

4th bug: Umbrafen Witchdoctor (http://www.wowhead.com/npc=20115/umbrafen-witchdoctor) should drop Netherweave Cloth with a 76% chance of dropping, but instead it gaved me 2x Runecloth. And if you check the mob in wowhead, they should not even drop runecloths like at all.  

Regards,
Sinergyy

**Comment by ccnim** [comment]
The umbrafen buff uses this formula to determine how much stamina to give: 3 + Level \* 0.75.

**Comment by Sinergyy** [comment]
I forgot to mention that I started investigating this area as someone posted how they fell from the ground here. And watching at how you get feared from the terror totems, this is really possible.

**Comment by ccnim** [comment]
Going to make a new report for the last bug.
