### ISSUE TITLE
Warlock's Imp pet is talking too much

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1642]
He seems to be saying something every time he casts a fireball.
Most of the time it's just his normal sound (without words) but occasionally he also says something.
I've heard his whole repertoire within 3 minutes or so.
IIRC he should say something or play his sound only when you send him to attack something, not on every cast.

**Comment by netherspite** [comment]
Actually he should even say different phrases on different events.
http://wow.gamepedia.com/Imp_(warlock_minion)
At the moment he just spams random phrases from any list on every cast.

**Comment by KimmoKM** [comment]
It's a bit jarring indeed, particularly

> "You know, we've had a lot of fun together, it's been really special, but I think it's time I should start seeing other warlocks. Just a little on the side. No no no it's not you, it's not you, it's me. I just need my space, it's nobody's fault."

that I've heard several times within minutes and that, according to that Wowpedia article, should only be played when he's dismissed.
