### ISSUE TITLE
manafiend targets friendly player after dungeon mind control

### ISSUE THREAD

**Issue by pjcevans** [ccshiro/cc-buglist#1643]
- mind controlled in dungeon
- manafiend is cast by mind control GREMLIN
- mind control broken by totem getting knocked out
- manafiend still going after a good friend after MC expired

Still trying to get a vid of this -.-

**Comment by KimmoKM** [comment]
Why did you close this issue? While I have no direct evidence of the claim, my intuition also says Shadow Fiend summoned during MC probably shouldn't be hostile after MC ends.

**Comment by pjcevans** [comment]
Made in error, think this works as intended
