### ISSUE TITLE
Gordo has wrong waypoints

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1644]
According to leveling guides (and my memory) he never should come to the Deathknell's gates:
http://www.almarsguides.com/wow/leveling/undead.cfm
However he currently does:
![wowscrnshot_090515_131149](https://cloud.githubusercontent.com/assets/5777848/9699004/74853710-53d9-11e5-92f7-3d7b4a8c4aa1.jpg)

Also he is leaving the road further for some reason:
![wowscrnshot_090515_132047](https://cloud.githubusercontent.com/assets/5777848/9699014/a8f161ea-53d9-11e5-91ff-52edf16adc1f.jpg)

**Comment by ccnim** [comment]
There was a video of him being there in some leveling video so I made him move all the way there.
