### ISSUE TITLE
[Inventory] Unlearning profession deletes equiped items.

### ISSUE THREAD

**Issue by opzor** [ccshiro/cc-buglist#1647]
Found on Tailoring (not tested other professions)

If you unlearn Tailoring while wearing Shadoweave Set and then relog character, then items are deleted (there was empty space in bags). 

as far as i know those items should be UNEQUIPED from character and placed in the bags (or send via email if there is no place in bags).

reproduction steps:
learn tailoring
learn shadoweave tailoring
make shadoweave set (robe/shoulders/boots)
equip those items
unlearn tailoring
relog
your items are gone

**Comment by ccshiro** [comment]
I think the code handles it by sending them to your mail at the moment, did you check that they weren't there?

**Comment by opzor** [comment]
you right, they came with mail. Closing.
