### ISSUE TITLE
Shield Bash ability of Captain Vachon in Tirisfal Glades hits for too much

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1651]
Literally oneshotting anyone of appropriate level.
![wowscrnshot_090515_213011](https://cloud.githubusercontent.com/assets/5777848/9700707/bc399bfa-5415-11e5-8905-5fc44a0fd7e7.jpg)

**Comment by Sleekcrush** [comment]
I completed this quest and didn't get by his Shield Bash for anywhere near that amount. It seemed appropriate towards my level.

**Comment by netherspite** [comment]
I tried it two times and both times got oneshotted.

**Comment by netherspite** [comment]
He seems to be using that ability only when you're casting something.
So basically tanking him with VW solves the issue.
However I doubt mage would kill him.

**Comment by Sleekcrush** [comment]
Alright well maybe I didn't notice it as I was playing a warrior, so that was probably the case.
