### ISSUE TITLE
Tirisfal Glades Mob Movement Bugs

### ISSUE THREAD

**Issue by Sleekcrush** [ccshiro/cc-buglist#1657]
Movement Bug

• Cursed Darkhound 
o   http://i.imgur.com/AjuOttM.jpg
o   https://youtu.be/ysnM95ksMHM

• Decrepit Darkhound
o   http://i.imgur.com/xbfb2yQ.jpg
o   https://youtu.be/k5GEoRd0L8A

• Deathguard Terrence
o   When attacking a mob off his path, he will kill an enemy and stay in combat and try to kill another nearby as shown in the video. Deathguard Terrence and another Decrepit Darkhound are engaged in combat but are not moving to each other to engage in combat. Deathguard Terrence will stay in the location that he killed the first mob while the second mob will move very rapidly in place, spinning around.
o   He will not reset his path until I engage the enemy (Entering Combat), then he will assist. Until that happens, they seem to stay there forever.
o   I have seen another guard do this in the same area, but do not have video evidence of it.
o   https://youtu.be/I9ia4w6AtIw

**Comment by ccnim** [comment]
Fixed the first one. The Guard AI is making the mobs bug in the last 2 which will get fixed once we fix guards.
