### ISSUE TITLE
[Item] Leg enchant / socketbonus

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#1659]
When equipping this item i get more healing than expected

EDIT: Will add a bit more info when i understand what is happening as of now it varies to much

Seems like i am missing the socket bonus on the item not enchanted with the blue healing thread from Aldor

Then it is probably related to other legs as well although have not had the possibility to test this

**Comment by Liesara** [comment]
This seems to be a bug with socketing: If you socket the item while wearing it, everything's fine. If you socket it in your inventory and then equip it, you're missing the socketing bonus, at least in your stats.  I've tested with 2 different pants now, so it's not related to a single item, though theoretically it might still be related to the pants slot as i did not test with other armor.

As you can see i reset my talents before testing so calculation is easier and more precise. I have four pants in my inventory and am wearing one. The left ones were socketed while i was wearing them. The right ones were socketed in my inventory.

Switching the left Pontifex Kilt yields the expected result:

![wowscrnshot_090615_211958](https://cloud.githubusercontent.com/assets/14063689/9706166/1d27f844-54de-11e5-8ad7-b5ae1bd7476f.jpg)
![wowscrnshot_090615_212004](https://cloud.githubusercontent.com/assets/14063689/9706167/1ef1fcb0-54de-11e5-8313-e35ccc69bc5a.jpg)

Switching the right one does not; it is missing the 9 healing socket bonus:

![wowscrnshot_090615_212010](https://cloud.githubusercontent.com/assets/14063689/9706176/6031884e-54de-11e5-9a5e-7f90e120bb5a.jpg)
![wowscrnshot_090615_212016](https://cloud.githubusercontent.com/assets/14063689/9706177/61d53f7e-54de-11e5-832b-a364740491e6.jpg)

Same thing with the Trousers of the Astromancer. Left:

![wowscrnshot_090615_212023](https://cloud.githubusercontent.com/assets/14063689/9706181/7d9dec9c-54de-11e5-81de-8698ac3c9265.jpg)
![wowscrnshot_090615_212027](https://cloud.githubusercontent.com/assets/14063689/9706182/7fb6c332-54de-11e5-8665-cca8babcc5dc.jpg)

Right:

![wowscrnshot_090615_212030](https://cloud.githubusercontent.com/assets/14063689/9706189/a26124e0-54de-11e5-9914-82f619ab23cf.jpg)
![wowscrnshot_090615_212032](https://cloud.githubusercontent.com/assets/14063689/9706190/a416cd30-54de-11e5-91ce-cf682e7d3599.jpg)

Even switching from one Pontifex Kilt to another will result in the difference of 9 healing:

![wowscrnshot_090615_213534](https://cloud.githubusercontent.com/assets/14063689/9706214/81454dda-54df-11e5-8d8a-eb23fa95c68a.jpg)
![wowscrnshot_090615_213539](https://cloud.githubusercontent.com/assets/14063689/9706215/8342dc38-54df-11e5-9828-5dcfa647a50f.jpg)
