### ISSUE TITLE
Mage water elemental attack when opponent goes out of LoS.

### ISSUE THREAD

**Issue by Yzivv** [ccshiro/cc-buglist#1664]
When you use water elemental pets attack on an opponent and they run behind a pillar the pet does not follow the enemy. If the enemy comes back into the line of sight it will resume attacking. If I instead use pet follow first and then pet attack the pet will run to the enemy and start attacking when it gets in LoS. Pretty sure the pet should automatically try to follow the enemy after it fails to cast once.
This is very easy to reproduce on nagrand arena.

(I also noticed that when you disable the water bolt the pet will do nothing at all when ordered to attack. Just stands still. It should have a melee attack too.)
Edit: I am actually not sure if the pet has a melee attack in TBC i have been told by some others that it doesnt.

**Comment by ccshiro** [comment]
Works fine for me. Make sure you have waterbolt on auto-cast, and try again. If it still happens make a new report with a video showing the bug.

**Comment by Jumpka** [comment]
I was the guy testing it in nagrand arena (the one in nagrand, not an actual arena match if it makes difference) with Yzivv, and I know for sure he had water bolt set to auto cast. I was hiding behind the pillar in the middle of waterbolt cast and it would always try to finish the cast, fail, and tehn stand there doing nothing but having me in the "target" and as soon as I came back into LoS it would start casting. We we're testing it multiple times and always got the same result.
Trying to find someone to test it now.
