### ISSUE TITLE
I was able to cast Fear & Throw while CCed

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1667]
Fear: https://www.youtube.com/watch?v=0W_sdJnga6w
Throw: https://www.youtube.com/watch?v=uh2-0MlcyQo

Could not reproduce, only tried 2 times though.

EDIT: Probably related to having 2 overlapping CC effects on yourself & #1666

**Comment by ccshiro** [comment]
I've fixed #1666, but I'm not sure if this has been fixed with that or not. Think you could help me out and try it on the test server?

**Comment by Klimpb** [comment]
Never happened since this day and have not been able to reproduce it
