### ISSUE TITLE
Can't use Intercept with felguard "Target too close"

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1668]
https://www.youtube.com/watch?v=maBs9kY7d2Q

Target is definitely not too close.

**Comment by shadowraider** [comment]
have you tried to test it with warrior charge/intercept in a duel? this video isnt enough

**Comment by bloodfirst92** [comment]
I can confirm I've got the same error. 

How to reproduce : maccro the intercept -> use it -> "target is too close" regardless the distance between the target and the Felguard. He can only use it on auto-cast.

**Comment by opzor** [comment]
it works fine for me.

**Comment by Klimpb** [comment]
Closing this because felguard seem to have had a different type of bounding box/Hitbox on retail compared to players. Making him not able to charge at a range that you'd think would be 8 yards.

Can be seen a few times in this video: http://www.warcraftmovies.com/movieview.php?id=81117
