### ISSUE TITLE
dimensius the all-devouring, quest

### ISSUE THREAD

**Issue by LuteroDestinyAwaits** [ccshiro/cc-buglist#167]
http://www.wowhead.com/quest=10439/dimensius-the-all-devouring

Its a little problem when u must talk to http://www.wowhead.com/npc=20985/captain-saeed .

When u speak with him, event dont start. When u talk to him he should go with u to Dimensiusm if u dont talk to him Dimensius dont appear and u cant complete that quest.

**Comment by ccshiro** [comment]
We're aware that this event is not implemented. The reason being it's rather complex to do. Moving this to Low Priority for now.

**Comment by ccshiro** [comment]
There now exists a task for this quest - #733 - will close this issue in favor of the task.
