### ISSUE TITLE
[NPC] Vacillating Voidwalker have no abilities

### ISSUE THREAD

**Issue by Plazmawave** [ccshiro/cc-buglist#1677]
These mobs in void ridge don't do anything/have their abilities, (gain resistance to a spell, then fire that type of spell). 
Notoriously annoying mobs on retail.
http://www.wowhead.com/npc=19527/vacillating-voidcaller#comments

**Comment by ccnim** [comment]
#1557 Same issue, will close this and fix it when I fix these other mobs.
