### ISSUE TITLE
[PvP Mechanics] Trouble hitting players that are running in melee range

### ISSUE THREAD

**Issue by jessyo** [ccshiro/cc-buglist#168]
Hello

I play a rogue and I have a stable 30-40ms latency.

The issue I experienced is that most of the time when I'm trying to hit another player, my abilities don't trigger if the player is running away, not snared/stunned, even though I'm in the 5 meters melee range.

I recorded it here : http://youtu.be/wDRrA75u4fc

Notice how, from 0:15 to 0:20, I am in the melee range (my melee abilities aren't "red", as in too far away from the target) facing my target and spamming hemorrhage but it takes 5sec to cast the ability (and about 10+ spams), until I'm actually on top of it (~1 meter close to it).
Not to mention the melee white hits that won't hit the target until the hemorrhage goes off.

This happens with any melee ability, not just hemorrhage.

My guess is that this is somehow caused by the spells delay. But I don't know how, I'm just reporting it because it feels gamebreaking for melee classes.

**Comment by ccshiro** [comment]
> My guess is that this is somehow caused by the spells delay. But I don't know how, I'm just reporting it because it feels gamebreaking for melee classes.

This is unrelated to what you're describing. Spell delay has zero effect on you **casting** a spell.

Also it's a bit hard to see what's happening exactly since you don't display errors, but I will take a look at it myself.

**Comment by Sakatoro** [comment]
I got exactly the same problem as a warrior

**Comment by jessyo** [comment]
"Also it's a bit hard to see what's happening exactly since you don't display errors, but I will take a look at it myself."

I simply get the error "Out of range.".

**Comment by Piranhaz** [comment]
Warrior same problem, gamebreaking meele delay/lags. Can't get a harmstring on targets in arena. Always "out of range", spell delay EVEN chat delay and warping players...pvp is not possible like this as meele...last test it seemed WAY better

**Comment by jessyo** [comment]
The issue seems fixed since the server restart that occured 5min ago.

**Comment by kikomir** [comment]
I also played a rogue on the test and even though my latency was a constant 50-60 ms I found that sometimes all my abilities "lagged" a bit and at other times they worked just fine (cheap/kidney shot, shiv applying poison etc.) with no lagging. To me it seems it's more of an issue with server lagging rather than a core mechanics one but do test it out more thoroughly.

**Comment by Leolb** [comment]
Most private servers are very forgiving when it comes to melee range(or bugged?). It was very strict on retail and it can be seen any almost every pvp video at some point, perhaps someone could find one that displays is more clearly but I found some stuff:

https://www.youtube.com/watch?v=6cMJFN-eNRU Woundman 1 @ 2:56, 3:23, 4:18, watch in slowmo or frame by frame.. Happened 2+ times when his actionbars said he was in range but it said out of range. It happens almost every time you ran to a target and started attacking on retail, couldn't bother to check more times in the video.

Here is also a screenshot from Acrono T.A.R 0/31/30 where he was this close to a resto druid and got out of range indication 3 times in a row: http://i.imgur.com/D0xwurg.png, can watch it yourself.

It still is like this on retail now, it's just that every class has sprint so you dont notice as much.

But your example looks pretty extreme, but like you said it got fixed after the restart.

**Comment by ccshiro** [comment]
What @Leolb says about your action bar being able to claim you're in range but the server disagreeing (and it being common back in vanilla/tbc) is correct. However, in this case it was caused by a resource leak in the server making it gradually more and more unplayable over time.
