### ISSUE TITLE
Mobs critting with spells

### ISSUE THREAD

**Issue by tinvujasinovic1** [ccshiro/cc-buglist#1680]
As far as I remember, mobs arent suposed to crit with spells
Got crit for 1.5k by a tunneler in HFP
Proof: http://imagizer.imageshack.us/a/img673/6600/cwYFKa.jpg

**Comment by ccnim** [comment]
This is a ranged spell(shoot, throw) and not a magic spell. According to our rules this spell should therefore be able to crit.

**Comment by Aasamath** [comment]
"Mobs are unable to get critical strikes with spells"
http://wow.gamepedia.com/Spell_critical_strike
"Mobs indeed cannot crit with spells. There may be some specific mob spell somewhere that can crit, but the general rule is that spells used by mobs can never crit"
http://wowwiki.wikia.com/wiki/Talk:Spell_critical_strike

On the other hand , a GM on this thread talks about a spell crit being normal
http://eu.battle.net/wow/en/forum/topic/3225373112
