### ISSUE TITLE
[Shaman] Grounding totem should be able to absorb multiple projectile spells

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1682]
As the title says, Grounding totem should redirect all spells casts before the first one hits it, right now it always absorbs only one spell, so if you for example use grounding totem to absorb shatter, you will still take ice lance. Worst and most obvious one is when mage wants to CS you, he can simply use ice lance and CS at the same moment and CS will always land on the shaman.

http://wowwiki.wikia.com/wiki/Grounding_Totem
"It is rare for a totem to absorb more than one direct damage spell. This can happen if the two spells finish casting before the totem is hit by the initial spell. Spells with a travel time do not damage the target until the projectile hits; the totem will redirect any of these types of spells until it takes damage and summarily is destroyed."

**Comment by opzor** [comment]
From the 2.3 patch notes:
Grounding Totem: This totem is now destroyed upon redirecting any spell to itself.

**Comment by Jumpka** [comment]
Ye, for those who didn't know that, pre 2.3, Grounding would absorb any amount of non-damaging spells, so for example you could spam fear on shaman and they wouldn't destroy the totem, only damaging spells would kill it. This change ("Grounding Totem: This totem is now destroyed upon redirecting any spell to itself.") is refering only to this, so it gets destroyed by even non-damaging spells, but the thing about absorbing multiple spells still stays the same. It also had a CD on the buff reaplication before 2.3, so you would cast it, absorb a fear, and then 5-10 sec later if nothing else destroyed the totem, you would gain the redirection buff again but this CD meant that you wouldn't be able to abbsorb two spells immidiately anyway, if it wasn't for the travel time.

Proof:
http://wow.allakhazam.com/forum.html?forum=243&mid=1192395324321965172
"Groudning Totem still works, however, in that a spell with travel time (shadowbolt), followed by an instant-cast, instant-landing spell (shadowburn, most DoT's) will eat both of them."
(btw, he says it's a bug, but we know now that it stayed like this in the game for all those years till now, so it's clearly intentional)
Also, if you go trough history of http://wow.gamepedia.com/index.php?title=Grounding_Totem&action=history , you can see the that the tip stayed there all the time (even rewritten on some revisions, so it's not that they just foregot to remove it for 8 years)
If you still aren't sure, you can find plenty of vids where you will see shatters grounded

**Comment by Chulain** [comment]
https://youtu.be/EvmxORefCss?t=618

the first grounding totem soaks 2x wisdom AND the Eye for an Eye damage
so i'm not so sure about that 2.3 patch note
- judgement of wisdom failed. Grounding Totem was immune
- judgement of wisdom failed. Grounding Totem was immune
- slain Grounding Totem
- Eye for an Eye hits Grounding Totem for 695 Holy.

---

also

if you keep watching you'll see grounding totem soaking judgement refresh from auto attacks

Grounding totem is currently not being removed by:
- Vindication (not sure if it should tho, but it's "magic")
- refreshing a judgement debuff (auto attacks nor casts)
- Eye for an Eye
