### ISSUE TITLE
[Priest] Aegis of Preservation shouldn't take bonus from bonus healing

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1686]
I know it's Blackwing lair drop so it probably won't be even avalible, just want to make sure someone doesn't get it for free wins against comps like feral druid in the future.

Right now, Aegis of Preservation ( http://www.wowhead.com/item=19345/aegis-of-preservation#comments ) takes pretty big bonus from Bonus healing / damge ( not sure, tested it only on priest with shadow gear, but it's not important) while it shouldn't probably take any bonus at all (if it took any, it had to be small, since as you can see in comments, even posts from TBC say it's pretty bad trinket, while I was able to get it proc for about 500 on every melee hit with disc talents proced (+30% healing) and very little bonus healing (less than 1000).I popped this trinket against rogue/druid (in nagrand arena) when at like 30%HP and 20 sec later I had full HP. I'm typing all this since I can't find if there was some coefficient on it in 2.4 but I think if it worked like that on retail, the comments on wowhead would be a bit different.

**Comment by ccshiro** [comment]
@ccnim spell id 23781 should not scale with spell power
