### ISSUE TITLE
Controlled stuns and Random stuns shouldn't share DR

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1690]
Right now, if you get Deep Thunder stun proc, next HoJ will be only 3 sec because they share DR.

http://forums.elitistjerks.com/topic/9156-diminishing-returns-on-weapon-proc-stuns/
"There are two general sets of diminishing returns - "controlled" stuns, and "chance" stuns. Controlled stuns include all 100% chance abilities like Charge, Intercept, HoJ, Bash, and the like. Chance stuns are everything that has a less-than-100% chance to proc - things like Revenge Stun, Mace Spec, Seal of Justice, and weapon Chance on Hit: Stuns target effects."

http://wow.gamepedia.com/index.php?title=Stun&oldid=2084859
" There are however two diminishing returns categories, one for activated stuns, which include most stun effects, and one for proc stuns..."

http://forum.resolute-guild.com/viewtopic.php?style=6&f=7&t=20398&sid=824d2df67e70cf6c9bd35c3de325359c
"Controlled stuns have always had a separate DR than uncontrolled stuns."

**Comment by robinsch** [comment]
Issue is caused because spell is casted by item - needs triggered flag.
