### ISSUE TITLE
Classic [Quest] Red Linen Goods

### ISSUE THREAD

**Issue by RealZwox** [ccshiro/cc-buglist#1697]
Elwynn Forest 

You can collect more than 6 Bandana's

This ONLY happens when: You have 7/8 on the Tracker. Then you kill 2 mobs and both have this item in the Loot. After turning in the Quest, the rest of the Quest are still in the Bag.

**Comment by ccshiro** [comment]
#1694 (no need to make multiple reports for different quests when it's the same issue)
