### ISSUE TITLE
Flasks and Elixiers

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#1699]
Currently Flasks can be stacked with guardian elixiers and battle elixiers, one of each. Using another of any will overwrite the old one, however one of each type may be used together, whereas flasks should be counting as both guardian and battle elixiers and thus not be usable together with them.

![wowscrnshot_090715_213026](https://cloud.githubusercontent.com/assets/14063689/9722211/135bebce-55a9-11e5-9746-efc4fbc397d3.jpg)

**Comment by Skibbli** [comment]
I'm not sure what the CC stance is for elixirs but according to the 2.1 patch notes the battle/guardian elixir change was in that patch so it should be possible to have multiple elixirs active at once.

**Comment by Liesara** [comment]
It's not about multiple elixiers though but about flask + elixiers. The Flasks (Item) even state they count as both guardian and battle elixier. Granted, the buff does not.

**Comment by Skibbli** [comment]
The change to flasks counting as both battle and guardian elixirs also came at the same time as the change to elixirs so the patch CC is using for item states would have players able to have multiple elixirs and a flask active at the same time.

From what I've seen from looking around elixirs of the same type wouldn't stack e.g. mongoose and major agi. You could have both active but only one of them would count for your stats. Also if you used a greater int pot it wouldn't stack with Arcane Intellect as it's mentioned in the 2.1 patch notes that it was fixed so they would stack, following the battle/guardian elixir change. That may or may not be the case with other class buffs too.

Some of this is from memory so some supporting information would be useful to clear this up.

EDIT - http://vanillagaming.org/forum/index.php?topic=13869.0 mentions some of this. Granted it is from a private vanilla server but they do have some evidence in there already so we can at least read the evidence they have found. It is unlikely that consumable stacking was changed before the 2.1 overhaul so the vanilla state is likely to be accurate.

**Comment by Ickler** [comment]
This is a clear bug, it's only the content that are 2.0.x. If you undo the Alchemy nerf, you have to re-work talents too - so it's a non-option. 

Flask should overwrite all elixirs, and applying an elixir before cancelling flask should give you the "A more powerful blabla active" error IIRC.
