### ISSUE TITLE
Vanish in Flare

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#17]
Question: Should a rogue be able to use vanish in a hunter's flare? In MoP you couldn't, but reports suggests in TBC you could. A video of this happening would be sufficient evidence.

**Comment by Pyrossword** [comment]
I'll need someone else to confirm this to me, but I checked all patch changes in TBC and have not seen mention of Rogues vanishing in Hunters flare.

**Comment by ccshiro** [comment]
Penol linked this video to me: http://www.youtube.com/watch?v=srwTw3BoU3s#t=27

It's 3.3, however, and while I think it's a fairly strong indication, if someone is able to find a TBC video that would settle the issue once and for all.

**Comment by Pyrossword** [comment]
I will try to surf YT for the video and hopefully will find it.

**Comment by Pyrossword** [comment]
I don't know if you read the description of the video Shiro but this caught my eye.

'Edit: As of 10/25/2009 this change has been reverted and no longer works'

**Comment by MakDizdar** [comment]
No, you could not.
You are stealthed for 0.5 seconds, that is not enough for a cheap shot considering that the global cooldown is 0.5 seconds. The amount of time you have to cheapshot collides with the global cooldown.

To sum up: No, i have no evidence of this and my memory could fail but I am quite sure that you could not vanish in a flare. You could still cast vanish but you got immediately revealed, maybe just enough time to escape a flare.

**Comment by Skibbli** [comment]
http://www.youtube.com/watch?v=EbwetgVudCM - at 6:35 you see Neilyo use vanish with the flare debuff on him (middle left of the screen) and immune pops up. He stays visible but the slow is removed.

**Comment by huggarn** [comment]
MakDizar Vanish caused GCD? On AT they could insta vanish/sap you.

**Comment by Lobogo** [comment]
Yes indeed you COULD use vanish in a flare, but all it did was remove the slowing effects (if any) and you would be insta revealed again
And as said above, due to global CD you wouldnt be able to use any opening moves

**Comment by Barroth** [comment]
nice find Skibbli so he gets a immune message when stealth/vanish buffs should get applied, drops combat and only removes snare

**Comment by pnoia** [comment]
Vanish doesnt trigger GCD so the reasoning behind not being able to use any opening moves is false. The explanation to this would be flare revealing the rogue instantly thereby removing the stealth effect before being unable to perform any action.

Here is a video of vanish not triggering the GCD. You can see the rogue uses garrote instantly after using vanish.

5:08 http://youtu.be/2rmCkvpyzEw?t=5m8s

**Comment by Lobogo** [comment]
in that case, yes, its the insta reveal that prevents you from using openers while under flare effect

**Comment by ccshiro** [comment]
Guess that settles it. Thanks.
