### ISSUE TITLE
Unlearning talents without having spent a single point

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#1701]
Currently you can go to your classtrainer and unlearn your talents while having spent not a single point:

![wowscrnshot_090715_235605](https://cloud.githubusercontent.com/assets/14063689/9723200/4ba51574-55bc-11e5-8342-3f1a2877d81e.jpg)

Not sure this is a bug, as I can find no evidence except for this one forum post where one guy's wondering why he can't unlearn talents and another one asks him if he actually spent points:

http://www.gamefaqs.com/boards/534914-world-of-warcraft/57792779

Krozard5 years ago#4
No, that's not really normal...maybe that one is bugged though.

Although I do have a stupid question, but I feel it needs to be asked.
You actually spent the talent points right? If you have the talent preview on you have to put the points in and then click learn. This may seem pretty basic...but you never know

Of course that seems to have been during a later expansion.

**Comment by Shanghi** [comment]
The "You have not spent any talent points" error already happens if you pick Accept on that popup. This seems normal to me, especially since money is only checked after clicking to accept too.

**Comment by ccnim** [comment]
Seems fine the way it is.
