### ISSUE TITLE
Double rare mob Warord Kolkaris

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1705]
I killed one of them (as recount on a screenshot suggests) at another tent and after 5 more minutes this one was here.

![wowscrnshot_090715_152727](https://cloud.githubusercontent.com/assets/5777848/9729494/74b6ee90-5618-11e5-8a19-88d537ae7229.jpg)

**Comment by ccnim** [comment]
Seems like once the rare mob has despawned the corpse of another rare mob in the same pool should spawn(hidden) but instead it spawns alive with it's respawn timer ticking down.
