### ISSUE TITLE
Double rare mob Gazz'uz in Skull Rock

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1715]
![wowscrnshot_090815_160011](https://cloud.githubusercontent.com/assets/5777848/9736559/993086fa-564a-11e5-826d-ebe07551c152.jpg)

**Comment by ccnim** [comment]
That's just a named mob? I'm not following at all.

**Comment by netherspite** [comment]
Hmm I thought I've seen a rare silver dragon around his portrait.
Seems I'm wrong, sorry.
