### ISSUE TITLE
Broken weapons are still used visually

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1717]
Not a big deal but still.
If your weapon is broken but you didn't unequip it the character will keep visually using it and the sounds will be like you're still using that weapon.
![wowscrnshot_090815_163515](https://cloud.githubusercontent.com/assets/5777848/9736625/fccc397a-564a-11e5-9f7c-6c483c8f77cd.jpg)

**Comment by ccshiro** [comment]
I think that's the correct behavior.

**Comment by netherspite** [comment]
After some research I came to the same conclusion.
No direct proofs for this being correct or incorrect behavior though (and I doubt they can be found).
