### ISSUE TITLE
Thrall not yet fixed with mind control issue.

### ISSUE THREAD

**Issue by H4Z3R** [ccshiro/cc-buglist#1719]
Tried Old Hillsbrad HC today with a priest and after MC'ing an enemy, Thrall started attacking him. 
I noticed that there is an old thread about this issue, however it was marked as fixed which it obviously isn't.

**Comment by H4Z3R** [comment]
Actually this is a bad description. What I intended to say is that Thrall attacks the priest after the priest stops mindcontrolling the enemy. Thrall won't stop until the priest (who mind controlled the enemy) is dead.

**Comment by ccshiro** [comment]
All the various mind control hostility bugs should (hopefully) be gone now.
