### ISSUE TITLE
[NPC] Marauding Crust Burster - Damage 

### ISSUE THREAD

**Issue by jlavier9359** [ccshiro/cc-buglist#1721]
![wowscrnshot_090815_140110](https://cloud.githubusercontent.com/assets/5779320/9744572/43bfc1f8-5632-11e5-93a5-4c4f5cb11ff7.jpg)

If you check the second to last comment from this link: http://www.wowhead.com/npc=16857/marauding-crust-burster#comments

You can see a post at the bottom of the comments by ov3rk11l during patch 2.4.3 explaining how the damage normally hits around 300+. 

I'm not sure if this is intended but as you can see it only took about 6-8 hits to kill me which seems interesting.

**Comment by netherspite** [comment]
Duplicate: https://github.com/ccshiro/cc-buglist/issues/49
