### ISSUE TITLE
Plainstrider Meat and Plainstrider Feather drop rate is too high

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1724]
I got 7/7 on both of them after killing just 7 plainstriders.
I guess the droprate is too high.
Not sure where find the correct droprate though :(

![wowscrnshot_090815_194849](https://cloud.githubusercontent.com/assets/5777848/9757495/ac4cecc0-56e9-11e5-9f64-19428e4cce38.jpg)

**Comment by KimmoKM** [comment]
I don't recall that quest ever being too troublesome. The 80% droprate that stock servers seem to have seems about right, and with sample size of 7, getting it every time isn't too unlikely.

**Comment by netherspite** [comment]
Sample size is 14 (since there is 7 of each item).
However, 80% is may be correct.
