### ISSUE TITLE
Mountain Cougar Pelt droprate is too high

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1725]
Got 10 of them from 10-11 cougars.
Not sure where to find correct droprate for this one either.

![wowscrnshot_090815_195709](https://cloud.githubusercontent.com/assets/5777848/9757518/cb3b84d4-56e9-11e5-823d-12c41ff0abf8.jpg)

**Comment by KimmoKM** [comment]
If droprates for Red Cloud Mesa were low, taurens would probably have started entering Bloodhoof Village at level 6, which wasn't the case. I'm quite convinced it was level 5ish, same as on other starting areas. I believe the droprate should be something like 80%, but even 100% might be correct.

I recall some of the quests in Mulgore proper were bullshit (not the infamous raptor eye level of, but still annoying), but I don't ever recall having trouble in the starting area.

**Comment by netherspite** [comment]
May be you're right, however 100% is not correct indeed. I'm sure I sometimes didn't get the drop.
