### ISSUE TITLE
When dying in Brambleblade Ravine your ghost appears at Bloodhoof Village

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1727]
The closest graveyard seems to be at the Camp Narache.
Not sure if this is correct behavior.

**Comment by H4Z3R** [comment]
Because the location of Camp Narache graveyard being further to the east than Bloodhoof Village graveyard, dying in northern Brambleblade Ravine might cause your ghost to warp to Bloodhoof Village instead due to it being slightly closer to your corpse.
