### ISSUE TITLE
Well Stones are still usable when you already gathered 2 of them

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1729]
![wowscrnshot_090915_122349](https://cloud.githubusercontent.com/assets/5777848/9760993/7961763c-5702-11e5-8a40-9c830b770b6a.jpg)

**Comment by ccshiro** [comment]
Self-note: look at #1038 as well.

**Comment by ccshiro** [comment]
Probably same as #1694 actually.
