### ISSUE TITLE
NPC missing : Mortog Steamhead

### ISSUE THREAD

**Issue by FurioCC** [ccshiro/cc-buglist#173]
NPC vendor outside Serpentshrine Cavern named Mortog Steamhead (http://wow.gamepedia.com/Mortog_Steamhead http://www.wowhead.com/npc=23373) that supposed to be outside of Serpentshrine Cavern is missing.
Sources claim he was present from release as reagent poison and ammo vendor and in patch 2.1 he also got ability to repair and trading coilfang armaments for cenarian salves (hp and mana pots).

**Comment by ccnim** [comment]
This NPC was added in 2.1.
