### ISSUE TITLE
Quest items drop for Mazzranache is 100%

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1730]
I remember spending a while getting drops for it.
Also all the other quest drops from the same mobs seem to be 100% as well which is wrong.

![wowscrnshot_090915_122430](https://cloud.githubusercontent.com/assets/5777848/9761016/9fccdd7a-5702-11e5-8bb8-af31206f2324.jpg)
![wowscrnshot_090915_122548](https://cloud.githubusercontent.com/assets/5777848/9761020/a2726f54-5702-11e5-83b9-59afa112c145.jpg)
![wowscrnshot_090915_122623](https://cloud.githubusercontent.com/assets/5777848/9761023/a5275282-5702-11e5-96dd-dd2296e562e6.jpg)

**Comment by KimmoKM** [comment]
This one I can agree with, I recall having some trouble with this quest, particularly the Gizzard. Several comments in [Wowhead](http://www.wowhead.com/quest=766/mazzranache#comments) imply low droprate, aside from the one from 3.2.0. Maybe it was buffed at some point?
