### ISSUE TITLE
[Quest] Quest progress not being updated

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1733]
im not sure if this is only happening addonwise or it is caused by the server not sending the "quest progress tag" ( <-- i made that up out of ignorance)

steps to reproduce:
1.have a quest for looting stuff ( Shaleskin flayer on my case)
2. loot one
3.look at addon quest tracker -- no progress-- 

addionatly TinyTip (the one who shows a bigger enemy tooltip when hovering the cursor) does not update either

![captura de pantalla 2015-09-09 a las 16 14 55](https://cloud.githubusercontent.com/assets/13721369/9765881/ace69af0-5716-11e5-972f-717d69e0cfcc.png)
![captura de pantalla 2015-09-09 a las 16 31 04](https://cloud.githubusercontent.com/assets/13721369/9765880/ace214da-5716-11e5-988f-4ddc3a673cd0.png)
![captura de pantalla 2015-09-09 a las 16 14 58](https://cloud.githubusercontent.com/assets/13721369/9765882/ace7dd0c-5716-11e5-8873-2104249c475d.png)

**Comment by netherspite** [comment]
Duplicate: #533
