### ISSUE TITLE
[Quest][Netherstorm] Zaxxis insignia quest -- Dont meet the requirements

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1734]
So, i handed the previous quest to the NPC, he insta offered me the "Get 10 zaxxis insignia quest" and as soon as i tried to accept it, he gave me error "you dont meet the requirements for the quest"

Steps to reproduce:
1. do the quest before
2. try to get next

Note: what i mean by he insta offered me the next quest is that as soon as i handed in the previous, without the NPC dialog closing, he gave me the following

![captura de pantalla 2015-09-09 a las 16 50 04](https://cloud.githubusercontent.com/assets/13721369/9765949/ed685cc6-5716-11e5-8b9b-802215f83b79.png)

**Comment by ccnim** [comment]
The patch for it was most likely not in when you tested it, if you can test again that would be cool. I'll close this and if it is indeed still bugged then you can reopen it again.
