### ISSUE TITLE
Deeprun Rat Roundabout

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1735]
When using the quest item on the rats in [Deeprun Rat Roundabout](http://www.wowhead.com/quest=6661/deeprun-rat-roundup), instead of providing credit and charming them, it does nothing.

https://www.youtube.com/watch?v=U11BArF432g shows how the quest is ought to work.

I'm not sure if this is the kind of issue I'm supposed to be reporting, but Ironforge and Stormwind zones are marked as finished and there's not one marked for the Tram.

**Comment by LC-LC** [comment]
# Quest Issues
- **Deeprun Rat Roundup** [Confirm this is bugged. Also, I don't believe player should emote /train when using the flute.]
