### ISSUE TITLE
Possible issue with randomized item statistics

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1736]
To be frank, I don't know how "of the X" item stat allocation is really supposed to work precisely, but I encountered two seemingly identical items, except that one has better statistics, and that seemed weird to me and worth reporting in case it's a part of a larger issue.

![2015-09-09-190509_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/9767305/477a9508-5726-11e5-92ce-620038ef787d.png)

**Comment by ccnim** [comment]
http://wowwiki.wikia.com/wiki/Severing_Axe

Seems like it is working as it should.
