### ISSUE TITLE
Nascent Fel Orc Concussion Blow range

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1738]
Nascent Fel Orcs in Blood Furnace can use their Concussion Blow ability well beyond melee range. Example (the mob didn't move after the screenshot being taken):

![mpv-shot0001](https://cloud.githubusercontent.com/assets/1533992/9775343/15609be0-5757-11e5-8936-4289b07f8206.jpg)

I can't find any proof it's definitely a melee range ability, but considering the its name and the fact that warriors have the same ability, I'd be incredibly surprised if it actually could be used at ranged targets.

**Comment by ccnim** [comment]
Client data
