### ISSUE TITLE
[PvE Mechanic] Botanica heroic buggs

### ISSUE THREAD

**Issue by descendance** [ccshiro/cc-buglist#174]
Commander Sarannis- this boss did not spawn his adds correctly.
How it should work: At 30-50% and 15-20% health she will spawn 3 adds.
How it works now: She spawned both group of adds when she was at around 5% of hp.

---

Laj- adds spawning bugg
How it should work:He should spawn 2 adds on the pedastals in front of him
## How it works: He does spawn 2 adds BUT they sometimes do not spawn at the same time

Flower NPC's that come with Sunseeker Geomancer do not grow in size and damage over time
How it should work: if not killed quckly they should grow in size and do more damage
source: https://web.archive.org/web/20070416015522/http://www.wowwiki.com/Botanica

---

Frayer Wildling-trash pack of mobs before the last boss
These mobs evade out in a weird way so you can not attack them,
Sometimes they reset, and sometimes they just follow you around until they start attacking again.
We did nothing special while pulling them so should be easy to reproduce

---

Warp Splinter-Arcane Volley
How it should work: He throws as many bolts as there are players/pets in front of him. Those bolts can hit people who are behind him. 
So as an example if the tank were tanking him face away from the party he should throw only 1 bolt at a random person.
How it works now: he throws bolts at the entire party no matter how many people are in front of him

source:
https://web.archive.org/web/20070509055450/http://www.wowwiki.com/Warp_Splinter#Heroic_mode
https://www.youtube.com/watch?v=KGFrSMBMXzM
https://web.archive.org/web/20070503012812/http://www.ampwow.com/wow/viewNewCreatures/17977-Warp+Splinter.php#startContent

Also i am not so sure that the healing that occurs after the adds despawn is right. Did not fully investigate it but it did seem a bit low to me.

**Comment by Gehenas** [comment]
Commander Sarannis:
- According to wowhead, on heroic she spawns the first wave of adds 30 seconds into the fight. Not at a certain % of life. My group nuked her down pretty fast, never spawned any adds. The problem could be the double add spawning, not the timing in your case.
- We encountered an other bug with her. Half of the mob packs were cleaned on the right side of the bridge. When she reached the right end side of the bridge and turned back, she only went like 3 yards and then turned back again, reached the right end side and turned back to walk an other 3 yards. After several small circles she finally continued her way to the far left side of the bridge as intended.

**Comment by descendance** [comment]
Regarding commander Sarannis:

here is a video heroic mode after patch 2.1.0 showing only 1 pack of adds being spawned
https://www.youtube.com/watch?v=YHongC-h1x4

and here is a link to wowiki from before patch 2.1.0 (9 may 2007) saying that she should spawn 2 pack of adds on heroic mode. One at 50-30% and the other at 15-20%
https://web.archive.org/web/20070509062806/http://www.wowwiki.com/Commander_Sarannis

Regardles it being one or two stacks we still had 2 stacks being spawned at the same time one on top of the other.

**Comment by ccnim** [comment]
Could not reproduce the Commander Sarannis bug.

"Flower NPC's that come with Sunseeker Geomancer do not grow in size and damage over time"
could not reproduce this either, it worked as it should. On further inspection the mob is using a dated AI and this might've caused some bug so I will remake this mob in our current AI.

**Comment by ccnim** [comment]
Reimplented the Botanist so she should no longer bug out.

I can not reproduce the Laj bug, I'm guessing the server lag might've had something to do with it.

The warp splinter spell is a bit confusing but according to the spell data from the time and now, nothing has changed except for the damage. It is possible the spell changed during an early patch and then changed back again.

**Comment by ccshiro** [comment]
Warp Splinter's volley is a spell that has been puzzling us in the past. We've seen the video you linked and many other s. However, in the end we couldn't explain how it ought to work (if I remember correctly videos were disagreeing with eachother, and the stated theory did not hold up scrutiny -- unfortunately we didn't document our work into it, so I cannot recite or remember the details). However, we decided back then that the spell data is what we ought to go on ultimately as it's closest to what we have of an official source.

**Comment by evobcn** [comment]
"Frayer Wildling-trash pack of mobs before the last boss
These mobs evade out in a weird way so you can not attack them,
Sometimes they reset, and sometimes they just follow you around until they start attacking again.
We did nothing special while pulling them so should be easy to reproduce"
- We noticed this as well today, and tried to figure out what caused it. It seems like it's a certain positioning/locations where they evade. I've recorded a video of me AoEing on top of them, while another guy moves them back and forth.
  https://www.youtube.com/watch?v=byusGH4k88Q

**Comment by KimmoKM** [comment]
#688 has an open issue of this problem.
