### ISSUE TITLE
All Honor Gear is lvl 70

### ISSUE THREAD

**Issue by Rafuros** [ccshiro/cc-buglist#1741]
All the Lvl 60 Honor gear like the High Warlord Gear is required to be level 70 instead of 60. this includes the weapons. 
Reproducable by going to the Hall of Legends in Orgrimmar and looking at the items the vendors are selling.

**Comment by Sakatoro** [comment]
Omg...

**Comment by ccnim** [comment]
That would be the blue 70 pvp gear
