### ISSUE TITLE
Xeleth

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1745]
[Xeleth](http://www.wowhead.com/npc=21894/xeleth), a summoned quest mob for [Against All Odds](http://www.wowhead.com/quest=10669/against-all-odds) seems reluctant to use his Focused Bursts ability. I killed once but after researching the mob, turns out he has several abilities so I summoned him again to determine if they work. It took quite a while for him to ever use the Eye Beam, while https://www.youtube.com/watch?v=9QaFufUk0WI&feature=youtu.be&t=1m33s shows he can use it instantly as he spawns.

**Comment by ccnim** [comment]
Does he always cast it instantly when you aggro?

**Comment by KimmoKM** [comment]
On Corecraft, he appears very reluctant to use the spell, I tried resummoning him and he used the eye beam so late he'd ordinarily be dead by then. As far as retail functionality goes, I only have evidence from that one video where he does use it instantly and I can't prove he does it every time.

However, I've been lead to believe the spell system specifies a minimum amount of time that needs to be elapsed before mobs use their abilities and unless I was outrageously unlucky when testing the mob, that value probably is too high (because the video demonstrates it CAN occur instantly and that never happened in my testing, not even close).
