### ISSUE TITLE
[Q-chain of Altruis the Sufferer] Elite mobs do not deal appropriate damage

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1747]
[Q] Patience and Understanding: Sal'salabim only hits for ~200 dmg by 9k armor
[Follow-Q] Crackin' Some Skulls: All 3 Elite mobs (Raliq, Coosh'coosh, Floon) hit for about 150-250 dmg by 9 k armor, spells deal about 400 dmg.

This is way too low from what i remember and read for example in the comments of wowhead

**Comment by ccnim** [comment]
Fixed sal'salabim, but the other ones are supposed to be very weak from what I found.
