### ISSUE TITLE
[Quest] Blood Oath of the Netherwing not available

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1748]
The follow-up quest of the netherwing faction questline should be able to be picked up by Mordenai, if one has level 300 flying skill.

I couldn't find any informations about it, but I believe this quest should be implented in 2.1

![wowscrnshot_091115_102859](https://cloud.githubusercontent.com/assets/12044027/9813776/d9dca84c-5888-11e5-92e6-ad730c166d1b.jpg)
-> neutral for netherwing, riding skill 300 learned

**Comment by netherspite** [comment]
The server will be in 2.0 state so the chain should not be there yet.

**Comment by Ickler** [comment]
What netherspite said :) This is added in 2.1, and will come later on with a content patch. Shouldn't be available now.
