### ISSUE TITLE
[Quest] Dimensius the All-Devouring - Event cannot be started

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1749]
to start the quest event, one has to talk to a NPC (Captain Saeed) which leads his small group to dimensius -> he spawns and the fight begins.

However, there is no such dialogue option while talking to this NPC as shown here:
![wowscrnshot_091115_111804](https://cloud.githubusercontent.com/assets/12044027/9811383/34711b56-5877-11e5-931e-43a1b1a3d4b7.jpg)
but: as you can see, the quest part "talk to saeed" is fulfilled. still, entering the manaforge dimensius is not spawning

it should work like this:
https://www.youtube.com/watch?v=HYuilDCG34Q

**Comment by netherspite** [comment]
Duplicate: https://github.com/ccshiro/cc-buglist/issues/733
