### ISSUE TITLE
[Warrior] Victory Rush activates after killing NPC which do not yield EXP

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1751]
as the title says

**Comment by ccshiro** [comment]
Tried it. Victory rush does not trigger for me on gray NPCs. Need further info.

**Comment by Peter1337** [comment]
happened during quests with a lvl 70 warrior on hellfire peninsula by killing lvl 60/61 mobs, f.e. scavengers

however, I wasn't able to reproduce it right now, too. strange.
