### ISSUE TITLE
Ferocitas the Dream Eater

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1752]
In quest [Ferocitas the Dream Eater](http://www.wowhead.com/quest=2459/ferocitas-the-dream-eater), you are supposed to kill Ferocitas, loot Gnarlpine necklace and open it to get the quest item. However, after having killed Ferocitas twice, the necklace contained nothing. The jewel should be contained 100% of the time.

**Comment by ccnim** [comment]
same issue http://wowwiki.wikia.com/wiki/Quest:The_Shattered_Hand_(2)
