### ISSUE TITLE
Blacksmith Hammer dropping from mobs

### ISSUE THREAD

**Issue by Zindai** [ccshiro/cc-buglist#1756]
I've found no record on Wowhead / Wowwiki / Thottbot of anyone having the profession item "Blacksmith Hammer" drop for them - it's always sold by a vendor. On the Corecraft test realm I had one drop from a Mottled Boar.

![](http://i.imgur.com/p7Uacg3.jpg)

**Comment by netherspite** [comment]
Hmm there is the same issue with Mining Pick, I got it from some random mob in Mulgore and wowhead says it should not drop:
http://www.wowhead.com/item=2901/mining-pick
