### ISSUE TITLE
[Vanilla][Durotar] Mob: Scorpid Worker

### ISSUE THREAD

**Issue by Zindai** [ccshiro/cc-buglist#1760]
The Scorpid Worker is supposed to occasionally cast Weak Poison, as mentioned on [Wowwiki](http://wowwiki.wikia.com/wiki/Scorpid_Worker?oldid=938396) - but not too frequently or instantly, which [Joana's (vanilla) video guide](https://youtu.be/jTSyexUNN9E?t=9m22s) proves. On the Corecraft test realm, Scorpid Workers never cast it.

The WotLK tooltip for Weak Poison says:
_Inflicts 1 Nature damage to an enemy every 3 sec. for 12 sec._
This is most likely the case for TBC as well.

**Comment by KimmoKM** [comment]
Related to #1744
