### ISSUE TITLE
[Mage] Rank 1 Frostbolt on target with high rank Frostbolt slow doesnt refresh slow.

### ISSUE THREAD

**Issue by Yzivv** [ccshiro/cc-buglist#1765]
If your target is affected by your max rank (or any rank higher then the second shot) frostbolt slow and you fire a lower rank (mainly important for rank 1) it will not refresh the slow. It should refresh. If you use the same rank twice it does refresh as it should.

**Comment by Ickler** [comment]
Yes this is correct, lower rank has the same slow and should re-apply the buff / refresh it. I noticed this awhile back too, didn't get around to report it yet :)
