### ISSUE TITLE
The Tome of Valor (Alliance paladin class quest)

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1769]
The quest is functional, but not polished (mobs spawn close by rather than running from a distance way, they don't use stances or battle shout, they say nothing, Daphne disappears and has to respawn instead of just walking back to the orchard).

A video of the quest: https://www.youtube.com/watch?v=-_4saHR9ZMk

**Comment by ccnim** [comment]
#357 will fix when I do westfall
