### ISSUE TITLE
Spirit healer interaction

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#177]
Npc Bug: Talking to the Spirit healers while dead and pressing cancel to decline their offer to resurrect you causes the healers to not be able to be spoken too again unless you move out and in of their range.

**Comment by ccshiro** [comment]
Looked at what happens. The communication goes something like this:

```
Client: interact with spirit healer.
Server: Sure.
""on accept twice:""
  Client: Okay, ress me.
  Server: Sure, you're alive buddy.
""on cancel:""
  Client: *Silence*
```

Which makes me think this could be a bug that exited on retail too, or maybe there's some extra communication details missing. Given you can like walk a yard away and it solves itself I'm not willing to spend hours debugging it. Aka, won't fix this.
