### ISSUE TITLE
[VANILLA][WARLOCK] Dreadsteed quest not working

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1773]
Like the title says, the dreadsteed questline is a bit bugged. It is completable, however not all parts work as they are supposed to. You may already be aware of this as the Immol'thar area in DM looks like a massive debug-playground, but I couldn't find an open issue so here it is.

The first bug in the questline is the quest given by Lord Banehollow in Jaedenar. You're supposed to kill a suspected orc traitor, who at first is meant to be friendly until you through dialogue turn him hostile, allowing you to kill him and loot his heart (which is the quest objective). There are no dialogue options available whatsoever, currently however you can complete the quest by disabling the potion that makes you friendly to Jaedenar mobs, allowing you to kill him and loot the heart.

Pretty much the entire part in Scholomance (where you summon an imp and have him conjure a parchment) is broken. The imp spawns, but is hostile, and killing him grants quest completion.

Finally, the routine in Dire Maul, where you summon the imp (hostile here as well), and he's supposed to start conjuring a master summoning circle. It consists of chevrons activating in the circle one by one, and with Xoroth mobs spawning to stop the process. You have an item to restore a failing chevron if overwhelmed, but that was not at all necessary as the entire process just went by itself until the master circle was completed, regardless of interference by mobs. Finally, once the circle completes, a dreadlord boss is supposed to spawn, after which you can use your scroll to summon the horse. The dreadlord did not spawn but the scroll was very much usable anyway. I don't think the spirit of the horse spawned properly after being killed but there was one placed right next to the area in beforehand allowing for quest turn-in.

Hope this has been helpful.

**Comment by ccnim** [comment]
#405, #409, #370 will fix when one of these are being done
