### ISSUE TITLE
Blade of Wizardry dropped from Illidari Taskmaster (level 70 epic BoE from level 63 normal mob)

### ISSUE THREAD

**Issue by Vemme** [ccshiro/cc-buglist#1774]
http://imgur.com/jU85aKL

So this just happened while I was leveling in Hellfire. As far as I can see, this item should not drop from these mobs..

**Comment by muusbolla** [comment]
We had a level 69 req gray item (mail shoulders maybe) drop in normal Ramparts. Possibly related.
