### ISSUE TITLE
[Quest] The Cipher of Damnation - Artor's Charge

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1775]
In comparison to #1630 , the NPC spirit itself spawned quickly after turning in previous quests, however, after starting "Artor's Charge", no NPC spirit which follows the player spawns and so I wasn't able to complete the quest at all.

tried it 5 times.

compare with this: https://www.youtube.com/watch?v=LP1cA0bfNhg

**Comment by ccnim** [comment]
Is it possible you were mounted?

**Comment by Peter1337** [comment]
oh yeah, I was. thanks!
I restarted the quest unmounted and could complete it (any explanation why it isn't working mounted?)

the spirit that follows one attacked all nearby NPCs in a range of 30+yards. is that meant to be?

**Comment by KimmoKM** [comment]
[This video](https://www.youtube.com/watch?v=6CCletaQvM8) shows the player getting the quest while mounted and and the NPC following him beneath the flying mount without doing a thing. However, that might not be how it worked in retail TBC (I think Cataclysm introduced new follower AI to be used in quests like J.J. Keeshan chain in Redridge and that might have affected older quests).

For example, [this Wowhead comment](http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge#comments:id=26820) from 2.0.6 says you are "meant to walk with your spirit" and [this one](http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge#comments:id=53409) suggests clearing the route in preparation. There's also [reports](http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge#comments:id=65767) of the NPC aggroing mobs on his own.

On the other hand, there are TBC era comments like [this](http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge#comments:id=26350:reply=43016) that say it should be doable while mounted. It almost seems as though the quest was changed mid-expansion  (2.3 or 2.4), but I suppose it's not unreasonable to think players unaccustomed to flying mounts might not even have though they could skip the hard part of the quest (or they did it before getting one).

**Comment by ccnim** [comment]
#1631
