### ISSUE TITLE
Greater Crust Burster deal too much damage (?)

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1781]
The mobs with the name "Greater Crust Burster" in "Blade's Edge Mountains" cast a poison spell which cannot be interrupted (I am not sure if this should be the case, the cast of smaller Crust Burster can be interrupted) and deal 1.4k damage as you can see in the screenshot:

![wowscrnshot_091415_124359](https://cloud.githubusercontent.com/assets/12044027/9848673/90fb178c-5ae3-11e5-8d3b-13dbe3dc2f4c.jpg)

**Comment by netherspite** [comment]
All the big worms in Outland are doing insane amount of damage.
Devs already said that it was like this at 2.0 patch time and thus it won't be changed.
