### ISSUE TITLE
"Repolarized Magneto Sphere" can only be deactivated via mounting

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1782]
In the Quest "Ride the Lightnin" in "Blade's Edge Mountains" one get's a Q-item called "Repolarized Magneto Sphere". Clicking on it gives the player a debuff which slows and allows collecting lightning bolts from Q-mobs. 
One should be able to remove the debuff anytime (that's at least what the item description is saying). Only mounting removed the debuff for me.

![wowscrnshot_091415_113417](https://cloud.githubusercontent.com/assets/12044027/9848774/937607c8-5ae4-11e5-9a7c-af1620330a6d.jpg)
sorry for the german client :>

**Comment by Sder3** [comment]
The effect is supposed to be a buff, not a debuff. That is why it can't be removed except by mounting.

https://www.youtube.com/watch?v=r5oxaD9E0Ek
