### ISSUE TITLE
Important Vanilla Quest: Badlands Reagent Run II

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#1783]
I know most Vanilla things have low priority, but this quest teaches the [Restorative Potion](http://www.wowhead.com/spell=11452/restorative-potion) recipe that's useful even at level 70.

Zone: Badlands

Expected:
1. Opening the [Thaumaturgy Vessel Lockbox](http://www.wowhead.com/item=7870) that's provided by the quest giver should give 3 [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866)s.
2. Using an [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866) on a [Scorched Guardian](http://www.wowhead.com/npc=2726) should start the channeling spell and enter into combat with them.
3. When the channeling is over, the [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866) should be replaced with a [Vessel of Dragon's Blood](http://www.wowhead.com/item=7867).

Actual result:
1. You only get 1 [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866) from the lockbox.
2. The [Scorched Guardian](http://www.wowhead.com/npc=2726) doesn't attack you when you use the [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866) to start the channeling spell.
3. When the channeling is over, the message "Scorched Guardian creates Vessel of Dragon's Blood." is shown as a tradeskill message, you don't get a [Vessel of Dragon's Blood](http://www.wowhead.com/item=7867) (I also tried killing/looting it just in case), and the [Empty Thaumaturgy Vessel](http://www.wowhead.com/item=7866) isn't removed.

Other Notes:
Different ranges were tested, from the max possible to standing inside the dragon.

External/Related Links:
Horde quest: http://www.wowhead.com/quest=2203
Horde quest giver (Jarkal Mossmeld): http://www.wowhead.com/npc=6868
Alliance quest: http://www.wowhead.com/quest=2501
Foolish Alliance quest giver (Ghak Healtouch): http://www.wowhead.com/npc=1470
Thaumaturgy Vessel Lockbox: http://www.wowhead.com/item=7870
Empty Thaumaturgy Vessel: http://www.wowhead.com/item=7866
Thaumaturgy Channel (channeling spell when using an empty vessel): http://www.wowhead.com/spell=9712/thaumaturgy-channel
Thaumaturgy Channel (just guessing, but maybe the spell used when channeling is over): http://www.wowhead.com/spell=21029
Vessel of Dragon's Blood: http://www.wowhead.com/item=7867
Scorched Guardian: http://www.wowhead.com/npc=2726

**Comment by ccnim** [comment]
#349 Will fix with badlands.
