### ISSUE TITLE
Free Action Potion Dispellability

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#1790]
http://wow.gamepedia.com/Free_Action_Potion

Patch 1.7.0 (2005-09-22): Free Action Potions can now be dispelled.

They currently cannot be dispelled by shamans Purge and priests Dispel and Mass Dispel.
They also cannot be spellstolen by a mage, if anyone wondered.

**Comment by ccshiro** [comment]
Patch 2.3.0 (2007-11-13): Free Action Potion: The buff from this potion can no longer be dispelled or taken via Spellsteal.

Source: Patch.txt in your WoW folder (P.S., you should use that not gamepedia or wowwiki for patch sources.)
