### ISSUE TITLE
Starving Fungal Giant behaviours

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1796]
https://www.youtube.com/watch?v=ESGg3NwOmfw

In this video you can see two weird behaviours from Zangarmarsh Fungal Giants. The second one (starting from 1:08) is obvious: One of the giants spins and moves around as it fights one of the sporelings. I saw this behaviour twice in roughly the same spot, seems to me it's just this one mob having this behaviour.

The second issue (the first minute of the video) I'm not certain about. A group of clumped up giants runs to Quagg Ridge and then despawns. I recall Watcher Leesha'oh being attacked, but I don't ever recall seeing this kind of migration, certainly not without just disappearing afterwards. However, even if their movement is a part of some event I'm not aware of, it certainly looks weird and probably is working incorrectly.

**Comment by ccnim** [comment]
The first part of the video is correct.

**Comment by ccshiro** [comment]
The pathing bug you reported is what I'm marking this issue as bugged for, and will fix.
