### ISSUE TITLE
[Paladin] Crusader Strike

### ISSUE THREAD

**Issue by krambulli** [ccshiro/cc-buglist#1804]
Crusader Strike does not proc any active Seals. 
Seal of Blood for example says: "All melee attacks deal additional Holy Damage...", which includes Crusader Strike, as it is a melee attack.
It also does not proc Seal of Command

**Comment by chhayra** [comment]
Crusader Strike started to proc Sob and Soc in WOTLK not tbc

**Comment by Jumpka** [comment]
Ye, http://wowwiki.wikia.com/wiki/Crusader_Strike?oldid=1521728 for proof:
"It is an instant weapon strike that can activate procs (excluding damage dealing Seals)"
It definitely shouldn't proc SoB/SoC in TBC.
