### ISSUE TITLE
[QUEST] Hilary's Necklage [QUEST COMPLETE EVENT MISSING]

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1815]
The quest Hilary's Necklage is missing an event upon completion. When this quest is completed, the cat Effsee right next to her should say "Meow!" and Hilary should say "I know how to speak kitty, and Effsee said thank you."

Documentation is right here. I know this clip is from Cata, but the quest haven't changed.
https://www.youtube.com/watch?v=_SQhFiR6IA0#t=1m48s

**Comment by ccnim** [comment]
#352 will fix this when I fix Redridge.
