### ISSUE TITLE
Npc: 14428 Uruson

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#1818]
This npc patrols very fast (movement speed) not sure if this is intended

**Comment by KimmoKM** [comment]
The fast movement speed does seem uncanny. Uruson walks slowly in this video that appears to have been recorded before Cataclysm pre-patch: https://www.youtube.com/watch?v=2yuz3g9VFsE

Same goes for this one definitely recorded in Cataclysm: https://www.youtube.com/watch?v=ub0UOMdZ5K8&feature=youtu.be&t=88
