### ISSUE TITLE
[Mage] Impact not working at all

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1825]
I've seen some report in https://github.com/ccshiro/cc-buglist/issues/984 that it sometimes worked, sometimes didn't, testing it right now, I got no Impat proc from any fire spell in both PvP and PvE

**Comment by ccshiro** [comment]
I tried fireball, scorch and fire blast, they all procd impact for me. What spell are you using?

**Comment by Jumpka** [comment]
As I've said, pretty much any fire spell, Fireball (rank 1 and max), Scorch (rank 1 and max), Fireblast (only max rank), Molten Armor. I think it's simillar issue like https://github.com/ccshiro/cc-buglist/issues/984
"Also, i don't know if this is intended behaviour, but it seems that Impact will not proc while the mage is being hit in melee range.

350 scorch(rank 1) casts, 0 Impact procs.
70 fire blast(rank 1) casts, 0 Impact procs.
110 scorch(rank 9) casts, 0 Impact procs.
Molten Armor was also on the whole time.
mobs were the same as in the previous post.

edit: today it appeared to work normally unlike yesterday."

Just to clarify, I was testing it both in melee range and 30-ish yard range and got no procs at all
Edit: I will go and test it again today, to get more info, but I know that at the time of making my original report it was definitelly bugged and not working.

EDIT2: Right now it's working fine

**Comment by Jumpka** [comment]
It's probably a rare bug where talents don't work at all sometimes, I wasn't able to reproduce this impact bug again.
