### ISSUE TITLE
[missing] No link between 'Young Wolves' and 'Mangy Wolves' [Elwynn Forest]

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1831]
As the title states there is no link between Young Wolves and 'Mangy Wolves' as it can be seen in this youtube video.
https://youtu.be/80LKgOeiBMU
It should apply in and around this area:
![elwynnforest](https://cloud.githubusercontent.com/assets/8980273/10011835/bfdb3910-6100-11e5-8255-7fefb20a6436.jpg)

Documentation: 
From wowhead this can be read:
![elwynnforest_yw_mw](https://cloud.githubusercontent.com/assets/8980273/10011849/e7734da0-6100-11e5-8d7d-74fa6bb3830a.jpg)
Source: http://www.wowhead.com/npc=299/young-wolf#comments
And my memories about this is still crystal clear.

**Comment by ccnim** [comment]
Should they attack together or should the faction change?

**Comment by ghost** [comment]
They should attack together.
e.g
- If you attack the "Mangy Wolf" or aggro the "Young Wolf" should come to aid it, but the faction should stay the same.
- You can't aggro the "Young Wolf" by body pull since it is neutral, but if you attack it, the "Mangy Wolf" will come to aid it.

**Comment by RealZwox** [comment]
they should attack together i can confirm dat.
