### ISSUE TITLE
[Quest] [Daily] Hellfire Fortifications appears as a repeatable turn-in quest

### ISSUE THREAD

**Issue by TheRaduki** [ccshiro/cc-buglist#1832]
The quest doesn't appear as a normal daily quest. It doesn't show up on the minimap either.
![wowscrnshot_090915_190138](https://cloud.githubusercontent.com/assets/14163268/9768756/03143e82-5726-11e5-9219-8ae19830fb46.jpg)
![wowscrnshot_090915_190218](https://cloud.githubusercontent.com/assets/14163268/9768759/054807b0-5726-11e5-87df-8f980a0ae814.jpg)
![wowscrnshot_090915_190225](https://cloud.githubusercontent.com/assets/14163268/9768761/06720410-5726-11e5-8fa8-4e6b72d8d7e2.jpg)

**Comment by mara1987** [comment]
This is in fact very blizzlike, as back in the day. I think that they chose this sign because it's not just a daily quest. With the completition you obtain expendable items to buy cool stuffs.
This is no issue at all.

**Comment by KimmoKM** [comment]
"Patch 2.1.0 (22-May-2007): Hellfire Fortifications is now a daily quest, and worth 150 reputation through revered."

I don't know if it appeared like that in 2.0.3, but since it was changed in 2.1, maybe it's correct as it is.
