### ISSUE TITLE
Thrown weapon, no durability loss.

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1835]
As the title there is no durability loss from throwing trown weapons. As far as I can see, the durability is currently linked to the durability loss you suffers from getting hit by NPC.
Furthermore, it is possible to repair the thrown weapon at a blacksmith. This should not be the case.

Video:
https://youtu.be/p31Zbs3xCWo

Here is some information regarding thrown weapons, though this is a question, it contains information about how thrown weapons worked in 2.4.3.
http://www.wowhead.com/forums&topic=33912/hunter-ranged-thrown

**Comment by BifrostRocks** [comment]
Still not fixed, since it is still possible to visit a smith and have it repaired :)

**Comment by BifrostRocks** [comment]
http://wow.gamepedia.com/Thrown 

# History

Although Thrown weapons never used ammo (which was removed in 4.0.1), there has been different attempts at making thrown weapons "limited" in a similar manner to how the usage of a gun was limited to the number of bullets the player had. Among the ways Throw-weapons have functioned are:

    Charges: Often, a purchased common-quality weapon would have 200 charges, losing one charge each time the player threw it.
    Durability: The weapon would use its own durability as "charges", losing one point of durability each time the player threw it. It could thus be "recharged" by repairing it.
    Invulnerability: Current thrown weapons have no durability, no charges, and does not suffer any kind of reduction or damage when being used."

**Comment by KimmoKM** [comment]
[WoWBlueTracker](http://blue.cardplace.com/newcache/us/33203320.htm) mentions a change being made in the expansion (TBC)

> The mechanic of thrown weapons is being changed in the expansion to be similar to a normal weapon. Once a stack is used it will remain in your inventory and can then be repaired to refill the stack, similar to repairing broken armor or weapons. This allows us to put stats on thrown weapons and itemize them as we would any other weapon.
