### ISSUE TITLE
Players desyncing at a certain flying height / distance?

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#1837]
We coincidentally noticed weird things occurring when flying straight up above each others heads.
There seems to be a point of desync at a certain height (height difference?). For example, when flying straight up, the one flying up, from the perspective of the other person, stops moving further up at some point. He will still do his idle movements (as druid in birdform flap his wings etc) but will not change height anymore. Didn't test if he would change position at all, but I'd assume not.
Also, if you use a Flask of Petrification above that point to fall down without dying, for the other person you will either start falling down once you reach the desync point, which happened a few times and we were not sure why, or you will just suddenly appear on the ground once you've reached it, however without the flask debuff and with "unupdated Bufficons". Meaning there will still be a rocketmount icon or birdform icon, but if the character was on a rocket, the actual rocket will be gone. In birdform, the birdform persists however. Once the flask expires or is cancelled via the currently existing bug by rightclicking a dummy for example (we tested this only in front of the scryer bank in shattrath), and buffs are in any way updated, either by receiving a buff or killing the old buffs, the rocketicon and birdform icon will correctly update and disappear, however in the case of birdform, birdform itself will still persist, leading to some hilarious visuals. All of this is only from the perspective of the player that stayed on the ground. The druid in this case perceives everything as normal.
To reproduce get two different players to stand next to each other, one gets on his flying mount or into birdform and flies straight up until the guy on the ground can not see him flying further up. Now the upper guy uses a flask of petrification. Once he reaches the ground, waits for it to expire or cancels it via rightclick on attackable target. Update buffs by Buffing or killing buffs. Behold weirdness.
I assume this works as well with levitate and slow fall as long as you use those spell above the desync point (as otherwise the buffs would update) and pala bubble.

Here's a video with us doing it with druid's birdform:
https://youtu.be/enSn1lExJdg

Hilarious bird riding a rocket:
https://youtu.be/Hy2MlAuAawc

**Comment by zoofCC** [comment]
As far as i know, stock mangos core updates vertical position when the player spins and not when vertical coord changes.
