### ISSUE TITLE
Daily cooking quest Super Hot Stew - works but with a few details wrong

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#1838]
[Super Hot Stew](http://www.wowhead.com/quest=11379/super-hot-stew):
You need to use this [Cooking Pot](http://www.wowhead.com/item=33852/cooking-pot) with 2 [Mok'Nathal Shortribs](http://www.wowhead.com/item=31672/moknathal-shortribs) and 1 [Crunchy Serpent](http://www.wowhead.com/item=31673/crunchy-serpent) at the corpse of an [Abyssal Flamebringer](http://www.wowhead.com/npc=19973/abyssal-flamebringer). Currently:
1. You can use the pot nearby an alive Abyssal Flamebringer.
2. When using it somewhere else, you don't get an error message like how another quest pot shows "You need to be in Ancestral Grounds."
3. There's an instant cast time instead of 3 seconds.

Quest text: "...and broil it over an abyssal's corpse..."

Someone from a later patch doing it at about 3:28:
https://www.youtube.com/watch?v=HxiW4xAz-kg#t=3m25s

**Comment by ccnim** [comment]
2.3 so will have to do it when we introduce these mobs
