### ISSUE TITLE
Daily cooking quest Revenge is Tasty - Monstrous Kaliri birds aren't spawned

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#1839]
[Revenge is Tasty](http://www.wowhead.com/quest=11377/revenge-is-tasty)
[Monstrous Kaliri](http://www.wowhead.com/npc=23051/monstrous-kaliri)

This quest requires a quest item looted from those. I couldn't find any when flying around spamming to /target them. I'm not sure if they're purposefully being left out until a later content patch, but if they are then maybe the quest giver [The Rokk](http://www.wowhead.com/npc=24393/the-rokk) should be removed for now.

**Comment by ccnim** [comment]
The cooking mobs in Shattrath were added in 2.3 it seems.
