### ISSUE TITLE
[Mage] Invisibility fade time should be 5 seconds but is 6 instead.

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1841]
As the title says, Invisibilty's tooltip says you should be fading for 5 seconds, here on CC it's 6.

**Comment by ccshiro** [comment]
The spell data, which is directly from the client, has the spell set to 6 seconds. Tooltips are known to be inaccurate, spell data not. As such this claim needs supporting evidence.

Also I guess the tooltip is kind of vague, it could be interpreted as, for 5 seconds you lose aggro each second, and then you fade to invisibility (on the 6th second).

**Comment by Jumpka** [comment]
Ok, mb, I will look in some vids, but I guess it should be 6 then
EDIT: hmm, In this video it's definitely 5-ish seconds, not 6.
https://www.youtube.com/watch?v=0zsAENMgCwk

**Comment by ConfusedCC** [comment]
here is a comparison between testrealm and jumpkas video
https://youtu.be/2j95i4-L4ZI

**Comment by Jumpka** [comment]
Also in the video, the guy has high ping. You can see the buff / CD going off later
