### ISSUE TITLE
- QUESTION -  2.01 or 2.4.3 in PvP

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1846]
Please mark invalid right away, just have a question about bug reports in general.
Today I've realized that all PvE related things are being fixed to match 2.0.1 patch, but things as resilience and PvP trinkets are in 2.4.3 state, so how exactly is this split, or will everything change to 2.0.1 state?

**Comment by ta55el** [comment]
Classes and items mechanics will work as it was in 2.4.3 but items etc will be added like it was on retail with properly introduced patches. Similar will be with PvE, instances and raids will be introduced one by one and bosses skills and mechanics will be all pre-nerf. It also relates to loot dropped from raids and isntances.

**Comment by ccshiro** [comment]
Please ask questions on irc. Posting your question on the bug tracker is just littering an already hard to organize issue tracker.
