### ISSUE TITLE
Mob tagging experience penalty

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#185]
Currently, if an ungrouped low level character tags a monster and another player then kills it, dealing most of the damage to it, the tagger still gets full experience for the monster.

The experience they gain should be penalized if a player outside of the group did most of the damage. This should, as far as I know, be based on the percentage of damage dealt to the monster.

I'm sure most people know the mechanic, but more info on it can be found on Wowwiki at the very least:
http://www.wowwiki.com/Formulas:Mob_XP
See: Solo Experience Modifiers.

**Comment by Barroth** [comment]
we already have that mechanic implemented, apparently sth broke it

**Comment by Argonn** [comment]
This XP modifier on % damage was added in Wotlk, as result of the 'fastest level 80' doing this trick with dungeons monsters and a team of 4 helping him. Getting him banned as result.
This was still in TBC.

**Comment by ccshiro** [comment]
@Barroth we nerver implemented this (we did discuss it though).

Some research about how it worked, and if it was in fact a thing in TBC needed (my memory is hazy, but I think there was a period when it didn't exist, we used to do xp grinding with high levels in SM at some point in time).

**Comment by exltus** [comment]
very easy answer. I mined backup of [mentioned ](http://www.wowwiki.com/Formulas:Mob_XP) wiki page  [from july 2007](http://web.archive.org/web/20070717103946/http://www.wowwiki.com/Formulas:Mob_XP#Two_Character_Groups) (1 ,month before release wotlk) In this backup is lot of informations, mainly in paragraphs 7, 9 and 9.1 I think, that it is fully answering to your question

**Comment by Barroth** [comment]
https://www.youtube.com/watch?v=3NsVuRePVJ They have pala pull the whole instance, with the low-level player and a high level mage in his group. The mage then leaves the group, the pala starts dpsing the mobs down to 30%. Then the pala leaves the instance, the mage finishes the mobs and the low level player who's still in the pala's group. 

I think this indicates, that the group of the low level player needs to do the dmg to make him eligible for the experience gain. Why else would the pala have to do 70% dmg before the mage aoes them down. 
It is not clear though, wether it is a set threshold like >50% dmg will give full xp and below less or it is in direct relation to the % of dmg someone did.

**Comment by exltus** [comment]
I was leveling all my alts on retail on TbC this way: for example in Stockade - I pulled whole dungeon with my prot palla, but did not do any dmg. Next I healed myself few times to make some threat. Next I leave group with pala and makes low AoE dmg with my alt. Mobs were still attacking my pala but mobs was "grayed" for him. Next I killed all mobs with pala and my alt gained 100% of experiences even if he did like 0,5% of total damage.

**Comment by Iliana-sc** [comment]
I remember (yes, memory is useless but maybe this helps finding evidence) that when a hunter pet kills a mob on its own without help from the hunter you would not get loot or experience from that mob. I played a hunter in wrath and vanilla, but I don't recall when I had this happen to me.

My memory lines up with @Barroth's video and assessment of the video. I'm not sure if there is a real penalty in Vanilla and TBC though, perhaps there is just a minimum damage you need to do before you are eligible for rewards.

Perhaps it's possible to find more references to the hunter pet anecdote or even a video showing it?

**Comment by Klimpb** [comment]
Wotlk, but still:
http://youtu.be/ibSWooWOiO0?t=6m

From that video it does seem like the max exp penalty is 50%, then depending on the amount of damage you do to the mob the penalty will decrease.

**Comment by Argonn** [comment]
Penalty was added in Wotlk, like i stated before. Before that i have done that trick many times in deadmines.

**Comment by exltus** [comment]
Got it! Here is [video](https://www.youtube.com/watch?v=3NsVuRePVJw), that is showing power-leveling in exactly same way how I always was doing it too on retail. In this video you can see whole process. Is not hard to deduce formula from it. Formula is: YOU HAVE TO PUT 70% OF TOTAL DAMAGE TO GET 100% OF EXP. Unfortunately I don't know how many you will get if you will not put 70% of damage :(
in this video they outsmart game and put damage by group, but they do not let pala to reduce experience gained by do not allowing him to be enough close to death of the mob - because game know, that he was main damage dealer, but when he is not even in same instance his damage is credited only to his group (this was bug and was fixed in 2.4.2)

Important comments under video:

> something about patch 2.4.2, made it so u get group bonus XP only. no more of the all the XP for the >kill.
> 
> sucks but got nerfed since 2.4.2

Never mind, even if they fixed this kind of "bug" main thing is, that 70% of total damage was milestone to get 100% of exp on TBC
So final XP math:
1)  If you will deal 70% of damage you will gain 100% of XP
2)  All other important mechanics like Basic XP Formula, Group Experience, atc. Are described [here](http://web.archive.org/web/20081013102414/http://www.wowwiki.com/Formulas:Mob_XP)

**Comment by exltus** [comment]
I made another research and find this:
1)  You will get no penalty if someone else (ungrouped) will heal you [source](http://www.dual-boxing.com/threads/3260-WOW-XP-gain-penalty-question)
2)  If you attacked mob and anyone (ungrouped), who is able to get exp (is 4 levels higher or 9 levels lower of attacked mob) from this mob, will help you with damage dealing, **you will get full amount of possible experiences**. If is other player, that is helping you with damage, unable to get experiences from this mob (is 10 levels higher that mob, that youre attacking) you will get a **tiny fraction**. 
I was searching a lot about what exactly means „**tiny fraction**“ and I found [this source](http://www.wowhead.com/forums&topic=24780/power-leveling-a-friend#p236769) 
In this comment is this quote:

> A lvl 10-12 char in Westfall can expect to gain an avg of around 100-115 exp per kill on mobs the same lvl.
> If you get a lvl 70 with you, that exp drops to 12 per mob.

Regarding to this quote it looks, that „**tiny fraction**“ means **10%**

3)  All other formulas are described [here](http://web.archive.org/web/20081013102414/http://www.wowwiki.com/Formulas:Mob_XP)

**Comment by Ickler** [comment]
Mob tagging was used to get world first 70, by the french mage. The video is available on Youtube.
Not original uploader tho (in this one): https://www.youtube.com/watch?v=ubZJHTYAQUU

As I recall a mob tagged being killed by someone out of party would only reduce XP by a very small amount. Athene used mob tagging to get to 70 in his record of fastest leveler. He also as has been mentioned above used it in WotLK.

**Comment by exltus** [comment]
@Ickler
Yes, but because of this 70 lvls are able to gain exp from this mobs (they are green for them) thats why there is no penalty. If they will far mobs level 50 for example, there will be penalty. Whole experience system is described in my comment above.
