### ISSUE TITLE
Mobs aggroing from different floors

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1850]
I was going to report the Duskwither Spire case separately, but for me this appears a more universal issue (possibly related to #1716, I suppose Lord Melenas in #1759 is the same issue, for example): mobs often don't respect differences in height and can be aggroed from different floors/from ledges/etc.

For example, in Duskwither Spire at the first power source, as I entered the area, all mobs from upstairs suddenly [rushed down](https://www.youtube.com/watch?v=5aPw-ibck44&feature=youtu.be), which is clearly wrong. Similarly, in one of the buildings in Goldenmist Village, one of the mobs from the outside was pulled even though I was inside the building (definitely seems wrong, but I'm not 100% certain).

**Comment by ccshiro** [comment]
We noticed the same thing in deadmines.
