### ISSUE TITLE
[Mechanic] Using stun into already existing stun

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1851]
UPDATE: Gonna summarize everything in this post, some of the things in the comments aren't right etc. and there's lot of poinless stuff in them. 

EDIT: FOUND SOMETHING VERY IMPORTANT FOR THIS ISSUE > HoJ (and probably other stuns) and Kidney shot could be active on the same target at the same time. Proof: https://www.youtube.com/watch?v=OveRM0T6_ls#t=18m10s
(Rorgue has ShStep so definitelly no improved KS or something like that)

First off, theres a strange bug with Stormherald / deep thunder: After the last fix it is in the correct DR group (random stuns), but the proc itself ignores it, that means when you get stormherald proc and then do some other random stun, the second random stun will be DRed by the stormherald proc, but the stormherald proc will ALWAYS be 4 seconds no matter what.

The bug that this title is reffering to is stunning into Kidney shot (or Stromherald proc), which will end up doing nothing. Shiro said that it might be caused by the existance of talent improved kidney shot, that makes kidney shot stronger effect than other stuns and that it may be active with 0% multiplier even if you don't have this talent (this bug is the same with or without imrpoved KS). The game then won't replace kidney shot with other longer duration stuns because of this.

The fact that Stormherald proc behaves the same way as KS is strange, but as pointed in the first paragraph, Stromherald proc is very messed up right now. I remember that before the fix that moved stormherald DR from controled stuns to random stuns, after which the "always 4 seconds stormherald proc" bug happened, you could stun into last one second or so of stormherald proc and the new stun would happen without any problems (except for the obvious fact that the stun was halved by the wrong DR group of stormherald). The point is, Stormherald is very strange right now and maybe it won't behave like kidney shot after fixing it.

**Comment by Peter1337** [comment]
well i got a Stormherald and no DR bars, however during duels (me as warrior) I might have experienced no DRs between Stormherald and mace specialization stuns on my target when they procced back to back.

EDIT: Stormherald procs -> 4 sec stun on lvl 70 dummy (=target) -> 
1. if I intercept during the stun duration, nothing happens. 
2. if I intercept right after the 4 sec stun, my target is affected by a 3 sec stun (DR = 0) like it should be #1690 
3. two consecutive stormherald procs resulted in 2x 4sec stuns -> no DR ! [however, sometimes a DR is applied]

mace specialization stuns:
1. do NOT share the DR with intercept - correct #1690 
2. share the DR with mace specialization stuns - correct
3. seem NOT / rarely to share the DR with stormherald stuns - incorrect

intercept stun:
1. shares the DR with intercept (just "spam" intercept on CD, talent + gladiator 4 set bonus = 15sec)
2. does NOT share the DR with mace specialization stuns - correct
3. does NOT share the DR with stormherald stuns - correct

short: all 3 stuns seem to have different DR timers and are not or rarely connected with each other

EDIT 2:
so I did some more testing and now it seems that sometimes the DRs overlap. its really confusing.
I intercepted (3 sec stun = 0 DR) -> instant stormherald stun (2 sec = 1/2 DR) -> consecutive mace specialization (1,5sec = 1/2 DR) -> instant mace specialization overwriting the existing specialization stun (0,75sec = 1/4 DR)
That's some odd behaviour.

EDIT 3:
intercept (3sec stun = 0 DR), shortly after the stun, stormherald procs (2sec = 1/2 DR), 2 hits later it procs again (2sec =1/2 DR), 3 hits later it procs a third time (4sec = 0 DR).

EDIT 4:
confirmed it via duels, too

For me, it looks like the DR system regarding those 3 stuns is sometimes randomly linked, for most part the DR for Intercept is correct!
Further tests showed that "intercept" and "charge" share the same DR as intended

**Comment by Jumpka** [comment]
Wait Peter, what did you mean by: "2. if I intercept right after the 4 sec stun, my target is still no affected by a 1,5sec intercept stun (3sec \* 1/2 DR)" ?

**Comment by Peter1337** [comment]
twice, the dummy was stunned for 4 seconds due to the Stormherald proc. During the stun, I went in range to perform a intercept and did it right after the 4 second stun was over. Interestingly, no Intercept stun was applied to the dummy.
Doing the same thing, sometimes I had a 1/2 DR (1,5sec) stun after an intercept on the dummy - and sometimes I had a full stun duration (3sec).

**Comment by Jumpka** [comment]
Are you sure you didn't intercept too early when the "no stun" happened? Also, are you sure there wasn't some other source of DR when you got your 1.5 sec stun? So far for me it has been pretty consistent, HoJ after Deep Thunder proc was always 6 sec.

**Comment by Peter1337** [comment]
I am sure. Waited for 1 second after the prior stun went off.
Furthermore there haven't been any other DR effects on the target. The proc rate for Stormherald and the mace specialization are rather low - though sometimes they proc on consecutive hits.
To reproduce: equip Stormherald -> hit dummy till its stunned for 4 seconds (you can do this w/o mace specialization) and cancel your attack -> wait 6 seconds -> intercept the same target

EDIT: can't really reproduce it atm. might have been stun "resists" that weren't shown like an "immune" would've been. the combat log doesn't state anything in this special cases.

**Comment by Jumpka** [comment]
We have retested it with Peter1337 and he has the same results as I do, all intercepts AFTER stormherald stun are 3 sec, so this part is working correctly. Stormherald appears to be off DR completely and eats any stun that is casted into it.

**Comment by opzor** [comment]
check on players.
dummy may be considered as a pve target and therefore not affected by DR.

**Comment by Jumpka** [comment]
@opzor ye sure I did test everything before creating this report, works the same on dummy, PvP and also mobs outside shatt
