### ISSUE TITLE
Ratchet to Booty Bay boat dissappears after 5 seconds

### ISSUE THREAD

**Issue by sabromex** [ccshiro/cc-buglist#1857]
The boat from Ratchet to Booty Bay doesn't idle correctly prior to the loading screen between zones. The result is the inability to move whilst waiting the remainder of the duration between zones.
To make matters worse, you only have 5 seconds to get off of the boat before it repeats the same scenario.

**Comment by ConfusedCC** [comment]
duplicate #262
