### ISSUE TITLE
[Diminishing returns] Nature's grasp / entangling roots doesn't share DR

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1861]
I found out today that Nature's grasp and entangling roots doesn't share DR. Meaning you can effectively root someone for 20 seconds straight (28 if you count 2 more roots at the end). 

Nature's grasp and entangling roots should share DR.

**Comment by ghost** [comment]
#1126
Someone highlighted in the comments that they do not share the same deminishing returns.
