### ISSUE TITLE
Control+run

### ISSUE THREAD

**Issue by ASrozaev** [ccshiro/cc-buglist#1866]
read once more and use trinket when feared
https://github.com/ccshiro/cc-buglist/issues/1370

**Comment by Jumpka** [comment]
Pretty sure it's exactly retail like, if you press W right AFTER poly/fear ends (or you trinket it) you will start running. Going trought old TBC vids like hydra, you can see people standing still for a brief moment right after fear ends even tho they will move immediately after stuns end, so just close it...
