### ISSUE TITLE
[Item] Tabards

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1868]
I'm fairly certain this isn't how tabards should appear on your character when wearing leggings:
![wowscrnshot_090815_210921](https://cloud.githubusercontent.com/assets/13790554/10184828/20479b18-66f6-11e5-9756-c82890ba082e.jpg)
![wowscrnshot_090815_210926](https://cloud.githubusercontent.com/assets/13790554/10184830/23c9333c-66f6-11e5-8bc4-a66e49bd8535.jpg)

Disregard the commentary, this occurs even if you equip the tabard after equipping your leggings.

**Comment by ccnim** [comment]
Client side
