### ISSUE TITLE
[Quest] Sunfury Briefings

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1870]
While doing the Sunfury Briefings quest, I was able to loot multiples of the quest objective, despite only needing one. I'm sure this issue isn't specific to this quest:

Sunfury Military Briefing:
![wowscrnshot_090615_222944](https://cloud.githubusercontent.com/assets/13790554/10184929/5aa5d67a-66f7-11e5-8b25-0c3c19859069.jpg)

Sunfury Arcane Briefing:
![wowscrnshot_090615_223001](https://cloud.githubusercontent.com/assets/13790554/10184933/67780418-66f7-11e5-8d4b-6f7fb1dfd8e9.jpg)

**Comment by ccnim** [comment]
seems like it got fixed by some other fix.
