### ISSUE TITLE
[Vanilla][Quest] Eitrigg's Wisdom

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1871]
It is not possible to talk to Eitrigg in order to turn in the quest. While this is considered Vanilla content, the trinket is very relevant to level 70 Feral Druid tanks.
![wowscrnshot_090615_123754](https://cloud.githubusercontent.com/assets/13790554/10185079/0d27dc52-66f9-11e5-9179-cfd8f4e79337.jpg)

**Comment by Ickler** [comment]
- 1, that trinket is one of the best alternatives you'll have early TBC.

**Comment by ghost** [comment]
Correct, it is pre-raid best-in-slot.
