### ISSUE TITLE
[Quest] Getting Down to Business

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1872]
After collecting 8 Nether Drake essence and returning to turn in the quest, the image is no longer available:
![wowscrnshot_092915_223339](https://cloud.githubusercontent.com/assets/13790554/10185205/52686f10-66fa-11e5-8c1d-c55cc3d613f0.jpg)

As you can see on the mini-map, I should be able to turn in the quest.

**Comment by ccnim** [comment]
the mob is behind the crystals
