### ISSUE TITLE
Ironspine Forcelord and Mind-control

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1874]
While attempting to do the Teleport This! quest, I mind-controlled an Ironspine Forgelord and began attacking the Cyber-Rage Forgelord I aggro'd. After a few seconds I dismissed the Ironspine Forgelord. Instead of it going to attack me, it continued to attack the other Forgelord, despite it no longer being under my control.
![wowscrnshot_092915_225957](https://cloud.githubusercontent.com/assets/13790554/10185757/6d98dfee-6700-11e5-8c0e-448f445bcb5b.jpg)
![wowscrnshot_092915_230001](https://cloud.githubusercontent.com/assets/13790554/10185760/715cc410-6700-11e5-8f77-d8bf80946b79.jpg)

**Comment by ccnim** [comment]
#1542
