### ISSUE TITLE
[Enchant] Mongoose Proc results in less attacks per minute.

### ISSUE THREAD

**Issue by Dallal92** [ccshiro/cc-buglist#1889]
The weapon enchant Mongoose affect occasionally gives +120 Agility and attack speed slightly.
When the proc happens it is displayed correctly in your character sheet. However after several hours of testing my brother and I have found that you have a less melee attacks registered (via recount) than a character with no enchant at all (also tested with +20 on each weapon).

My brother and I made identical characters, same race, class, talents, gear, gems. However we had different weapon enchants. We tested on Orc Warriors, and Orc Rogues. Both had same problems with and without gear, talents (Fury Warrior 'Flurry'), ect. 

Make sure to have a program or add-on that records character combat data.
1. Have 1 character dual weild weapons, both enchanted with mongoose.

Have another identical character dual wield the same weapons with a different enchant, i.e. +20 Strength, or no enchant at all.
1. Have both characters auto attack a target dummy at the same time.
2. Attack for at least several minutes to let multiple Mongoose Procs happen over time.
3. Stop auto attacking and see results in recount, or any other combat log parser.

The character that has Mongoose should have less auto attacks registered than the character with different weapon enchants, or none at all. 

Me and my brothers findings below:
(Combat was started at stopped at the same time, we we sitting at our computers side by side for the test.)

**Control Test**
The first 2 pictures are a control test we did. We did this test to make sure there was not any problems from out recount programs collecting incorrect data. Both characters are 100% identical; stats, gear (lack thereof), weapons, no talents, no enchants.

Rogue A, me. 99 hits.
![wowscrnshot_100315_021238](https://cloud.githubusercontent.com/assets/14064652/10262193/2ed93a2a-697a-11e5-812e-09b5993dd79b.jpg)

Rogue B, my brother. 99 hits.
![wowscrnshot_100315_021236](https://cloud.githubusercontent.com/assets/14064652/10262196/45801294-697a-11e5-8e9f-c20ced2f001b.jpg)
**End of Control Test**

Warrior A, +20 Str on both Weapons. 556 auto attacks registered.
![wowscrnshot_100315_001540](https://cloud.githubusercontent.com/assets/14064652/10262117/ff5ff2f4-6977-11e5-9b15-b4b177615856.jpg)

Warrior B, Mongoose on both Weapons. 523 auto attacks registered.
2.6/2.6 weapon speed. 
2.55/2.55 with 1 Mongoose Proc.
2.50/2.50 with 2 Mongoose Procs.
![wowscrnshot_100315_001537](https://cloud.githubusercontent.com/assets/14064652/10262138/94c693b6-6978-11e5-9bde-815127da49b2.jpg)

Rogue A, No weapon Enchants. 430 auto attacks registered.
![wowscrnshot_100315_022128](https://cloud.githubusercontent.com/assets/14064652/10262172/4f2060a2-6979-11e5-9799-c3a128bc6dcb.jpg)

Rogue B, Mongoose on both Weapons. 419 auto attacks registered.
2.7/1.8 weapon speeds.
2.65/1.76 with 1 Mongoose Proc.
2.60/1.73 with 2 Mongoose Procs.
![wowscrnshot_100315_022121](https://cloud.githubusercontent.com/assets/14064652/10262153/f26995fe-6978-11e5-86ae-84d71dc9d2f4.jpg)

We did not think to record the length of each test, or the number of mongoose procs. We also did my different tests with different talents selected. We can try to provide any additional information.

**Comment by Liesara** [comment]
This is probably related to the currently existing, lately patched-in haste bug, which makes the swing timer reset anytime haste is added or subtracted. This has been confirmed via testing with Dragonspine Trophy, Seal of the Crusader, Divine Shield, Haste Potion, Slice and Dice.

Related issue: #1876

**Comment by ccshiro** [comment]
Indeed, same issue as #1876.
