### ISSUE TITLE
[Shadow Labyrinth]

### ISSUE THREAD

**Issue by Fordehlulz** [ccshiro/cc-buglist#1893]
Shadow Labyrinth non Heroic
Mage, Lock, Shaman, Druid, Warrior

Cabal Ritualist hitting caster (Mage, WL, HShaman) 3 times in a second (onehit)

3 Boss Grandmaster Vorpil: small adds running too fast

**Comment by ccshiro** [comment]
The Ritualist thing is not a bug, and the second issue exists a report for: #1925.
