### ISSUE TITLE
[Vanilla][NPC:Boss] Taerar Debuff is removable

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1896]
As the tittle states, the debuff is removable by clicking, voiding the whole concept of the debuff :)

![captura de pantalla 2015-09-29 a las 18 17 07](https://cloud.githubusercontent.com/assets/13721369/10267875/e24a54f0-6aa5-11e5-80ec-ff031e9946c9.png)

**Comment by ccshiro** [comment]
I'd say these dragons will be fixed along with the zones they reside in: #373, #345, #356, #379.
