### ISSUE TITLE
[Combat log] Self tab is  -- showing not self things

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1898]
I dindt put much effort into looking for evidence on this one but i feel that "Someone crafting boots" is not much of my (Self) concern right?

![captura de pantalla 2015-10-04 a las 16 14 57](https://cloud.githubusercontent.com/assets/13721369/10268280/ee70503c-6ab3-11e5-8e38-b9b10fbdb80d.png)

**Comment by Jumpka** [comment]
http://us.battle.net/wow/en/forum/topic/1772570109
so I guess it's blizzlike
