### ISSUE TITLE
[Talent] Imp scorch is not working as intended

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1910]
Improved Scorch only stacks two times, and even at two stacks it doesn't refresh the buff from another scorch. 

Edit: the same seems to happen for Winter's Chill talent (Frost)

**Comment by KimmoKM** [comment]
Probably the same issue as #1908

**Comment by Ickler** [comment]
Yeah probably the same with all aura's :)

**Comment by Ickler** [comment]
Fixed in this update that was applied.
