### ISSUE TITLE
Quagmirran

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1916]
Quagmirran currently stands in front of his pool. Retail videos show him patrolling underwater.

https://www.youtube.com/watch?v=14gtyqyVwx4
https://www.youtube.com/watch?v=QWa_6fWhpT0

**Comment by Aprics** [comment]
He walks out of the water once you get close to the pool.
Once he is out of the pool he just wait there for the fight to start.

https://www.youtube.com/watch?v=uVNb6pxL-1w

**Comment by KimmoKM** [comment]
Damnit, could it be that I've been too unobservant to notice him in the pool while going to clear the side area for resistance buff? I guess that's possible.

**Comment by ccshiro** [comment]
@KimmoKM most likely, the implementation does what @Aprics says (or it's supposed to do that, if we not count for the possibility of bugs). Guess you could close this if you figure out if it works.

**Comment by KimmoKM** [comment]
I haven't been to SP since to double-check but I guess it's safe to say I wasn't paying enough attention when entering the room. If I do SP again, I'll make sure to check how it works, but I'll close the issue for now.

**Comment by KimmoKM** [comment]
I just did SP again and I can now confirm it was a false report, he starts in the pool and then walks up as you enter.
