### ISSUE TITLE
Seed of Corruption detonation

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#1920]
SoC should ignore damage from other SoC detonations.

_"If a target afflicted by Seed of Corruption takes damage from another target's SoC detonation and_ _survives, it will not have its own SoC detonate. The DoT will continue ticking until the required amount_ _of damage has been done, or the target is killed. Only then does its own SoC explosion actually_ _occur."_ (from http://wowwiki.wikia.com/wiki/Seed_of_Corruption?oldid=1432437)

_"Seed of corruption cannot proc off of its own damage. It used to go off when another seed_ _exploded. Now it doesn't react to other seeds. Shadowfury and rain of fire work to proc them_ _though."_ (Patch 2.0.7 Undocumented changes)

https://www.youtube.com/watch?v=ETCOwlzGuOE
https://www.youtube.com/watch?v=tIUO__0YqvA
https://www.youtube.com/watch?v=8sQbzQQiAaE
https://www.youtube.com/watch?v=R2i2xSitljQ
https://www.youtube.com/watch?v=aTJa3DgCgYQ

Also it explodes through walls and other obstacles (it shouldn't).
- _"Patch 2.3.0 (2007-11-13): Seed of Corruption detonation will now obey line of sight."_
- _"By littlidabbi (23,379 – 5·32·160) on 2007/06/18 (Patch 2.1.1)_ 
  _Warning : Seed of Corruption explodes through floors and walls and can pull mobs from other_ _levels and rooms(Common in Scholo pulling the basement and mobs in rooms below u at_ _Gandling). So avoid using Seed of Corruption in instances with 2 levels or rooms close to each_ _other._
  
  _Tarquin on 2007/06/19 (Patch 2.1.2)_
  _Frequently happens in Kara outside the Maiden's section, too._
  
  _Stryik on 2007/10/11 (Patch 2.2.3)_
  _Set to be fixed in 2.3._
  
  _Lukrid on 2008/08/15 (Patch 2.4.3)_
  _yup currently the explosion effect on SoC follows LoS rules. Basically, no more pulling aggro_ _from nearby rooms when the bomb goes off."_

**Comment by ccboygirl** [comment]
[recorded today](https://www.youtube.com/watch?v=YppLl8jxiKo)
- 0:00 - 1:15 (detonations still trigger each other)
- 1:14 (howl of terror bug)
- 1:39 - 1:58 (soc detonates despite the targets not being damaged)
- 1:59 - end (a bit of los testing. seems to be fine)

**Comment by ccnim** [comment]
fixes are not on the server yet.
