### ISSUE TITLE
Getting stats from gem bonuses despite not fulfilling the requirements

### ISSUE THREAD

**Issue by Kuvis** [ccshiro/cc-buglist#1921]
Long story short, I have a belt that whose socket bonus grants 3 resilience. I get the bonus despite having gemmed it with two blue gems, not a red+blue gem as the belt requires. Possibly related to the fact I had gemmed the belt with proper gems before, fulfilling the requirements.

Video:
http://ponkolauta.net/WoW/src/1444245000044.webm/resilience.webm

**Comment by ccshiro** [comment]
Same issue as #1970.
