### ISSUE TITLE
Grandmaster Vorpil adds movement is broken

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1925]
Most of the time they just run to him like crazy (very fast).
At one of the tries they were initially moving slowly (correctly) but after the first teleport & Rain of Fire they started to move very fast again.
Sometimes they come to some point instead of the boss and stay here for a while but eventually they'll just come to him and explode.

This issue makes the boss practically unkillable on heroic without heavy overgear.

**Comment by opzor** [comment]
this must be recent issue. done it multiple times month ago and was working good.

**Comment by netherspite** [comment]
Yes, I did it before as well. It is something new.
