### ISSUE TITLE
Nagrand - Kil'sorrow Deathsworn

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1930]
[Kil'sorrow Deathsworns](http://www.wowhead.com/npc=17148/kilsorrow-deathsworn#abilities) at Kil'sorrow Fortress in Nagrand use their [Bloodthirst](http://www.wowhead.com/spell=31996/bloodthirst) ability correctly, but the afterwards healing effect of the ability does not work. The tooltip of the buff is also blank, but I do not know if it is related to the issue or not.

![wowscrnshot_100615_162413](https://cloud.githubusercontent.com/assets/9568075/10364498/2b447546-6dbc-11e5-9033-90f1c76e27d3.jpg)

**Comment by ccnim** [comment]
Same as the earlier issue, the healing effect is like +60 per swing.

**Comment by Canderous** [comment]
Right, it was my MobInfo2 addon that did not display the health correctly.
