### ISSUE TITLE
Hellfire Peninsula - Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1931]
[Bleeding Hollow Tormentors](http://www.wowhead.com/npc=19424/bleeding-hollow-tormentor#abilities) do not use their [Fear](http://www.wowhead.com/spell=33924/fear) or [Hamstring](http://www.wowhead.com/spell=31553/hamstring) abilities.

**Comment by ccnim** [comment]
Fear is only used on non main targets. The hamstring seems broken however.
