### ISSUE TITLE
Terokkar Forest - Sharth Voldoun

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1933]
1) [Sharth Voldoun's](http://www.wowhead.com/npc=18554/sharth-voldoun#abilities) [Seal of Reckoning](http://www.wowhead.com/spell=15277/seal-of-reckoning) ability does not work. He does not gain health when he successfully strikes an opponent.
![wowscrnshot_100715_080650](https://cloud.githubusercontent.com/assets/9568075/10364899/7ea9607c-6dbf-11e5-964c-5e31dac3ecc2.jpg)

2) During the event that plays with [Pathaleon the Calculator's Image](http://www.wowhead.com/npc=21504/pathaleon-the-calculators-image), Pathaleon does not speak, only Sharth's lines are displayed. (NOTE: he does not appear on the screenshots because he was gone by the time I captured them; he does appear normally, he just doesn't speak)
![wowscrnshot_100815_132016](https://cloud.githubusercontent.com/assets/9568075/10364936/be7351a4-6dbf-11e5-81d2-b9f1661f6fae.jpg)
![wowscrnshot_100815_132017](https://cloud.githubusercontent.com/assets/9568075/10364938/c0c9b68c-6dbf-11e5-9b80-530422fe776d.jpg)

**Comment by ccnim** [comment]
The healing is very small that's why you didn't notice it.
