### ISSUE TITLE
Shadowmoon Valley - Earthmender Sophurus RP Event

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1934]
During the event that plays between [Earthmender Sophurus](http://www.wowhead.com/npc=21937/earthmender-sophurus) and [Thane Yoregar](http://www.wowhead.com/npc=21773/thane-yoregar), Sophurus does not deliver any of his lines, only Yoregar speaks.
![wowscrnshot_100715_194350](https://cloud.githubusercontent.com/assets/9568075/10365016/3cb59d38-6dc0-11e5-8b99-878154f47db4.jpg)

**Comment by ccnim** [comment]
He's not supposed to say anything.
