### ISSUE TITLE
Hellfire Peninsula - Vorakem Doomspeaker's RP text

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1937]
[Vorakem Doomspeaker](http://www.wowhead.com/npc=18679/vorakem-doomspeaker) has a typo in his text: "thru" should be "through".
![wowscrnshot_100415_211017](https://cloud.githubusercontent.com/assets/9568075/10365375/3be09e96-6dc3-11e5-966b-ae0248422046.jpg)

**Comment by helion84** [comment]
http://wow.zamimg.com/uploads/screenshots/normal/262172.jpg taken from WoWhead

**Comment by Canderous** [comment]
It seems like "thru" is also a valid word, just very rarely used (which I did not know about), so closing it then.
