### ISSUE TITLE
Incorrect Breath Timer

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#194]
Characters can hold their breath for too long underwater. Prior to patch 3.0.2 the limit was 1 minute (3 for Forsaken). Currently Wotlk timers are in place. 3 minutes for regular races.

http://www.wowwiki.com/Underwater_Breathing

**Comment by ghost** [comment]
Other page with confirmation:
http://www.wowwiki.com/Breath?oldid=1432601
" It is a blue meter that has a duration of 60 seconds."
"The Forsaken can hold their breath three times longer than other races."
