### ISSUE TITLE
Resistance spells overwrite each other

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#1940]
Spells that give resistance do not stack and they overwrite each other. Items and enchants seem to be not affected by this. The spells we tested that behaved this way were Mark of the Wild, Gift of the Wild, all paladin auras and priest's Shadow Protection, but there may be more, like shaman's resistance totems.

You can see an example of Mark of the Wild and Fire Resistance Aura on the two pictures below:
![wowscrnshot_100715_201126](https://cloud.githubusercontent.com/assets/9568075/10367064/862896c4-6dce-11e5-9cbd-9f9d8e18525a.jpg)
![wowscrnshot_100715_201128](https://cloud.githubusercontent.com/assets/9568075/10367071/93843396-6dce-11e5-86cc-aed5e5c6b399.jpg)

The paladin has 7 to all resists from his cloak enchant and + 33 to all resists from a talented Mark of the Wild, which is a total of 40 to all resists, that stacks and is shown correctly. However, once he activates the Fire Resistance Aura (which gives 70 fire res), he has 77 fire resistance, which comes in the form of +70 from the aura and + 7 from the cloak enchant, meaning that it overwrites Mark of the Wild's effect.

**Comment by Sder3** [comment]
They're not supposed to stack.

http://wowwiki.wikia.com/wiki/Resistance_buffs?oldid=1285313

"Note: Player-cast group buffs do not stack. This includes Druid's Mark of the Wild, Paladin's resistance auras, Shaman's resistance totems, Priest's Shadow Protection and Hunter's Aspect of the Wild. Solo buffs, such as Mage Armor and Warlock's Demon Armor, and non-player-cast buffs do stack, however. "

**Comment by Canderous** [comment]
I see, closing it then.
