### ISSUE TITLE
Quest: Who Are They?

### ISSUE THREAD

**Issue by Sder3** [ccshiro/cc-buglist#1942]
Private Weeks should offer you a new disguise if you happen to lose it. Currently he doesn't.

![wowscrnshot_100915_203437](https://cloud.githubusercontent.com/assets/13728979/10401086/4c4d5898-6ec5-11e5-96bc-4ae82251a588.jpg)

http://www.wowhead.com/quest=10040/who-are-they#comments
If you get spotted by a hunter and lose your disguise, you can talk to Private Weeks again to get another one.

https://youtu.be/jOW4XQgqcXg?t=102
Video of the horde version of the quest, showing the dialogue option. I assume it's also broken on horde side, but I haven't tested it.

**Comment by ikabob** [comment]
![wowscrnshot_102615_152234](https://cloud.githubusercontent.com/assets/15333150/10745319/e8c87424-7bfd-11e5-8791-0c38e5f388c9.jpg)
![wowscrnshot_102615_152240](https://cloud.githubusercontent.com/assets/15333150/10745321/ea1db4d8-7bfd-11e5-8998-88753fae4767.jpg)
![wowscrnshot_102615_152245](https://cloud.githubusercontent.com/assets/15333150/10745322/ec391118-7bfd-11e5-9e52-d70830da057c.jpg)
Horde Version is working correctly
