### ISSUE TITLE
Bloodlust spell effect on dead players

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1946]
A visual bug of bloodlust (likely heroism as well) being applied to corpses

![2015-10-10-093649_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/10409683/d20f3de4-6f32-11e5-8044-b93b0ea78cdb.png)

**Comment by Doppelmoral** [comment]
Maybe you should check for similar aura type spells such as totems / aspect (hunter) / paladin aura and accordingly submit another report for that. Think I saw totem buffs on corpses but might be mistaken.
