### ISSUE TITLE
[Paladin] Vengeance not stacking from correct sources

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#1949]
Vengeance is supposed to apply a stack / renew stack with every critical, spell or melee or ability.

Currently seal of blood proccs and Crusader strike does not procc it. Judgement of Blood does though.

**Comment by Jumpka** [comment]
I am pretty confused by this report, since my Crusader strike procs it and always did.

**Comment by Ickler** [comment]
I cannot reproduce this atm, will close this until I can retest with the same group / buffs etc.
