### ISSUE TITLE
Demonic Embrace

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#1957]
Increases/decreases total stamina/spirit instead of base.
http://wowwiki.wikia.com/wiki/Demonic_Embrace?oldid=1444434
tooltip says total tho :confused:

**Comment by Jumpka** [comment]
I don't get this report, it should increase/decrease TOTAL stamina/spirit, thats what the tooltip says and what it also does here, no bug there IMO.

**Comment by Summoning01** [comment]
"The increase applies only to your base stamina, not any additional stamina you get **from items and buffs.**"
perhaps it's just bad wording from whoever wrote the article.

**Comment by Jumpka** [comment]
Ye, thats strange, but let's be honest, lock has like 77 base stamina at level 70, that would be the most useless talent ever made (and the spirit removal part would remove like 2-3 spirit), even tho I hate locks with passion (cough\* LD cancer comp cough*), I'm pretty sure that note is wrong, no idea why would someone take his time and write it when it's not true tho, kinda weird.
