### ISSUE TITLE
Pet aggro range seems to high

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#1961]
I've cleared the first room with the trash before Moroes in Karazhan many times on retail but I never seen the Attendants/Retainer packs being bodypulled when every player hugs the wall.
Currently on CC however it seems pets can aggro these packs even if the hunter hugs the wall.

**Comment by brndd** [comment]
You need to backpedal so the pet goes closer to (or inside of, depending on pathing) the wall, otherwise it kinda lies out to the side and gets too close to the mobs.

**Comment by ccshiro** [comment]
Aggro ranges where actually broken (more generally than pets though), it was resolved in #2307.
