### ISSUE TITLE
stay -> passive stance

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#1963]
stay command followed by a switch to passive stance causes pets/minions to stop attacking and follow (while stay is still highlighted on the pet action bar).
"_Stay can be used in combination with Attack and Passive to temporarily clear a quest object or_ _gatherable resource. For the best results, station the pet (Ctrl+3 by default) as far from its owner as_ _possible. Then, order the attack (Ctrl+1) on the object-guarding mob. As soon as the mob targets the_ _pet, order a retreat (Ctrl+0) and run in yourself!_"
this paragraph suggests that the pet would return to where it was stationed before the attack command. in that case, when set to passive, the pet should only stop attacking and resume to either follow or stay (depending on what was commanded before the attack).
if passive stance indeed includes follow command, then there's still the minor bug of stay command being highlighted.

**Comment by ccshiro** [comment]
Had missed this report previously. This bug was fixed some time ago, so should be working as you describe on the server atm.
