### ISSUE TITLE
[Mechanic] Switching between 2hand and DW

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#1964]
I think there should be 1.5 sec cooldown for each weapon slot after you change weapon before you can change it again.
Right now, there is this strange thing that you can do on any class that can DW and use 2handed weapons (well, mostly arms warrs),where you can use 2handed weapon, switch to DW for like 0.01 sec to get instant off hand swing, and then switch back to 2hand. 
If you do this after using a spell (in that spell's GCD) there is no downside to it (other than you having to press two buttons I guess) and you basically gain offhand swing for free (It's pretty big on warrior since you get like 150-400 free DMG, 6-12 rage, chance to get mace stun proc, chance to get weapon procs like battlemaster or +5rage from Rod of the Sun King).
I'm not sure how exactly it worked on retail, but definitely not how it's working right now on CC (I think that the 1.5 sec CD per weapon slot that we talked about with Shiro is correct, not 100% tho)

**Comment by Klimpb** [comment]
This can be closed since the issue is this #2401
