### ISSUE TITLE
Curse of Recklessness only lasts 10 seconds vs players

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#1967]
It should last for the full duration of 2 minutes, I think.

The only proof I've found so far is:
http://www.locksucks.com/2007/12/25-awesome-warlock-tricks/ (23 in the list)
http://www.arenajunkies.com/topic/217-warlock-tip/
http://www.arenajunkies.com/topic/80404-warlock-some-useful-macros/#entry975230

**Comment by Aasamath** [comment]
You are right
https://youtu.be/eJX6gX4roCU?t=197
this clip shows the duration of the curse, apllied on the warrior filming (also shows the effect of the curse when a fear is applied on it, CC does it right)
