### ISSUE TITLE
Fel Orc Corpse in The Assassin is not really corpse

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#197]
The target you have to turn the quest "The Assassin" in should be a corpse but he is not really a corpse.
Screenshot attached

**Comment by netherspite** [comment]
![wowscrnshot_011815_122729](https://cloud.githubusercontent.com/assets/5777848/5793239/30b6dc08-9f45-11e4-8099-4059a08e9b13.jpg)

**Comment by Mustonen1** [comment]
Duplicate of #60

**Comment by netherspite** [comment]
True, had to write in comments to that issue. Thanks.
