### ISSUE TITLE
Blade of Wizardry seems to have no internal proc rate

### ISSUE THREAD

**Issue by lazermon** [ccshiro/cc-buglist#1973]
wowhead comment by tricksy regarding blade of wizardry:
By Tricksy (654 – 8·5) on 2007/02/27 (Patch 2.0.8)  
It does have a 15% procrate however it can proc no more often than every 30 seconds.

I tested it manually by casting a few thousand Polymorph Rank 1 with an addon timing and counting everything.

This leads to an actual procrate significantly lower than 15%, the faster your spell of choise the lower the procrate. Since you will be casting more spells during the 30 seconds where it cannot proc.
||
||
It procs around every 20 seconds on the test server (spamming frostbolts), so either the internal cooldown is wrong or just isn't there at all. I've digged around on the internet for anyone else talking about the proc and internal cd of blade of wizardry, and I'm not finding anything anywhere near as reliable as that comment.

**Comment by PatchnotesTBC** [comment]
This item is indeed bugged on Mangos.

**Comment by Barroth** [comment]
This item was fixed/researched some years ago, it is set to 15 second internal cd.
In the elitist jerk thread was done some research on it and they concluded that 30s was wrong. At wowhead there was a comment aswell saying that. Looks like the sources aren't fully aviable anymore :/
http://web.archive.org/web/20130511155353/http://elitistjerks.com/f31/t10096-haste_magical_dps/
http://www.wowhead.com/item=31336#comments:40

So this is working as intended.

**Comment by lazermon** [comment]
Sweet! Close this issue then.
