### ISSUE TITLE
Shaman - Earthshock - Not Interupting Spell.

### ISSUE THREAD

**Issue by Obamashaman** [ccshiro/cc-buglist#1974]
Tested it about ten times on Coilskar Siren in Shadowmoon Valley. My earthshock would do nothing to interrupt their frostbolt cast.

**Comment by KimmoKM** [comment]
You picked a mob that can't be interrupted (see: #1632 )

**Comment by Obamashaman** [comment]
Sorry for double post thanks ill check forum first before i post again so i dont again

**Comment by Chulain** [comment]
you can close your own reports btw
