### ISSUE TITLE
[Warlock] Spellstrike Set proc does not apply when Fel Armor is on

### ISSUE THREAD

**Issue by venturafonso** [ccshiro/cc-buglist#1975]
The Buff from spellstrike set proc does not apply on warlocks with fel armor on, you get the little lightning animation but the buff never applies, the combat log doesn't show anything.

WIthout Fel armor on it works properly.

Casting Fel armor when you have the proc buff(lesser spell blasting) causes the proc buff to disappear:

![llgkq3y](https://cloud.githubusercontent.com/assets/7500708/10713283/6a9fffe0-7aae-11e5-94f8-6a18d46648e4.png)

**Comment by lazermon** [comment]
Same issue appears with Destruction potion, using a destruction potion with the spellstrike proc up will remove the proc.
![](http://puu.sh/kWlbd/264133f2b8.jpg)
![](http://puu.sh/kWncy/45b98db7cb.jpg)

This is naturally not a warlock-only issue. Anyone with the spellstrike set will encounter this when using a destruction potion.

**Comment by Barroth** [comment]
This is a buffstacking issue, probably all the spellpower/spellhaste buffs should stack
