### ISSUE TITLE
Ghaz'an Swimming

### ISSUE THREAD

**Issue by InvisibleJon** [ccshiro/cc-buglist#198]
If you want it to be exactly like the very start of TBC release.
This NPC should also be a part of the Ghaz'an encounter: http://www.wowwiki.com/Overseer_Tidewrath

The boss in Underbog ''Ghaz'an'', did not seem to swim correctly.
http://www.wowwiki.com/Ghaz%27an
He was half walking/flying just above the water clipping through the air.
He should rather be swimming in the water. (This seems to be reported already)

**Comment by FurioCC** [comment]
Same issue as #86

**Comment by InvisibleJon** [comment]
I'll change it slightly then.

**Comment by FurioCC** [comment]
Overseer Tidewrath never came live, it was removed during TBC beta stage, referenced information is incorrect.

**Comment by ccnim** [comment]
Duplicate issue of #86.
