### ISSUE TITLE
[NPC][Nagrand] kill Sorrow Agent pathing #duplicate

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1982]
The mobs channeling the green spell wont follow you if attacked from range, they will just "look" at you but dont go out of the cicle. they DO NOT evade though, so they can be easily killed. 

I believe though that they can melee if you get close enough

![captura de pantalla 2015-10-28 a las 16 04 53](https://cloud.githubusercontent.com/assets/13721369/10794141/049d55ec-7d94-11e5-883a-98c163406edc.png)
![captura de pantalla 2015-10-28 a las 16 04 09](https://cloud.githubusercontent.com/assets/13721369/10794143/04a4683c-7d94-11e5-8e20-3c6863afdda7.png)
![captura de pantalla 2015-10-28 a las 16 03 59](https://cloud.githubusercontent.com/assets/13721369/10794142/04a316da-7d94-11e5-8868-ca5443a38584.png)
![captura de pantalla 2015-10-28 a las 16 04 04](https://cloud.githubusercontent.com/assets/13721369/10794144/04a61ec0-7d94-11e5-9d6e-ff4e91fc8519.png)
![captura de pantalla 2015-10-28 a las 16 04 10](https://cloud.githubusercontent.com/assets/13721369/10794145/04b14674-7d94-11e5-9546-ccbfc184b729.png)

**Comment by Sder3** [comment]
https://github.com/ccshiro/cc-buglist/issues/1895

**Comment by ghost** [comment]
labelled as duplicate and closed
