### ISSUE TITLE
[Quest][Nagrand] Lump goes to sleep midquest #duplicate

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1983]
You are supposed to attack him until he turns friendly and speakable, right now, when u get him low, he will get to sleep instantly but he will be talkable to (refer to SS).

He should /SIT

proof:
comment by garret: http://www.wowhead.com/npc=18351/lump#comments

![captura de pantalla 2015-10-28 a las 15 52 27](https://cloud.githubusercontent.com/assets/13721369/10794211/39ea0ce0-7d94-11e5-8093-9bc84f7efa2c.png)

**Comment by Sder3** [comment]
https://github.com/ccshiro/cc-buglist/issues/1894

**Comment by ghost** [comment]
label as duplicate + close
