### ISSUE TITLE
[Quest] All quest hubs open before "relay" quest.

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1984]
Ive seen various of this happenings (tbh i think it happens on every quest hub) but ive only SSed the one in nesynwary.

so what happens is that you can grab  all the quests(provided compliance of level req) of every questhub before handing in the "opener" quest. 

for example, in the SS, i can get the clefthoof, windroc and elekk quests before having handed in the "the nesynwary safari" which is the quests that makes you go there

![captura de pantalla 2015-10-28 a las 16 35 44](https://cloud.githubusercontent.com/assets/13721369/10796096/dfadd17c-7d9c-11e5-86de-3074a365f287.png)

**Comment by ghost** [comment]
closed. working as intented

**Comment by Chulain** [comment]
they're breadcrumb quests, working as intended
on 2010/02/07 (Patch 3.3.2)
It's possible that you cannot complete this quest if you have already done the quests at the nesingwary safari. Im atm trying to complete more quests in nagrand for the loremaster achivement, and Everyquest says i have'nt completed this quest but i cannot pick it up from the questgiver. Can anyone confirm this?

also see: https://github.com/ccshiro/cc-buglist/issues/730
