### ISSUE TITLE
Wrath of Air stacking

### ISSUE THREAD

**Issue by Kiszh** [ccshiro/cc-buglist#1987]
http://imgur.com/a/Xe7dD

as you can see on the screenshots wrath of air totems are stacking and giving increasing spellpower during the TK test on 29/10-15

We tested out mana spring aswell, which did not work like that.

**Comment by KimmoKM** [comment]
Similar issues: #1975 #1951

**Comment by Ickler** [comment]
Same case for Battleshout as displayed in #1951. They also give you the benefit of both, aka not just visual.

**Comment by Barroth** [comment]
it should indeed not stack, here is an overview for totem stacking: 
http://www.twentytotems.com/2007/11/stackable-totems-guide_27.html

**Comment by ccshiro** [comment]
@Barroth Fixed up all totem stacking to behave like your post describes. Thanks for the link.
