### ISSUE TITLE
[Dr Boom] [Dynamite range]

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1989]
Dr Booms [Throw Dynamite] ability has too long range. It should be way lower, currently he can throw dynamites as far as his bomb bots can walk until they explode themselves, which makes doing the encounter in intended way very very hard. I think the range should be something like ~5 yards. Currently you can't attack him with bombs from the Barrel next to him without getting thrown by dynamites like you could on retail.

Also, if you hit Dr Boom with a spell2 or a bomb you are stuck in combat with him until you run too far enough to drop combat.

**Comment by KimmoKM** [comment]
Seems to be the same as #1588
