### ISSUE TITLE
party members kills are reported on combat log from faar away

### ISSUE THREAD

**Issue by tests1500** [ccshiro/cc-buglist#1990]
reproduction:
1.invite player to group
2. go different zone, like zangarmarsh and terrokar forest ( this is where I spotted this)
3. party members combat kills are reported on my combat log. From very far away

**Comment by tests1500** [comment]
I've heard that the range should be only 200yd. Not sure which is the correct distance. pls respond for additional info

**Comment by SergioCC** [comment]
Could have posted the urls i gave u on irc maybe...
