### ISSUE TITLE
"Skettis - Invis Raven Stone" mob isn't invisible

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#1991]
It's at 66.6, 68.5 in Terokkar Forest.

![wowscrnshot_110415_201341](https://github-cloud.s3.amazonaws.com/assets%2F2672633%2F10957335%2F4544725e-8331-11e5-9fc7-76338f0f164e.jpg)

**Comment by Chulain** [comment]
maybe he just wants to be seen?

**Comment by Shanghi** [comment]
He knew what he was getting into when he signed the contract.

**Comment by Lumber-Jack-2** [comment]
:dancer:
