### ISSUE TITLE
Mind Controlling Enemies Issue (PRIEST)

### ISSUE THREAD

**Issue by BrunoAlves90** [ccshiro/cc-buglist#1994]
When Mind Controlling an Orc , Right of the entrance to hellfire Ramparts, and making him jump off the platform, he stood still in mid air (( at around the max range for MC ) and was Evading.
he then disappeared after a short while and respawned back at his original place.

**Comment by ccshiro** [comment]
I don't see what the bug is. If a mob can't path to you (which seems reasonable if it's mid air and can't fly) it'll evade. I'll mark as invalid, please reopen with further info if I'm missing something.
