### ISSUE TITLE
Vanndar/Drek'thar tower marshal/warmaster buffs

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#20]
Report: "Vanndar dont have the Towers buffs on him. Even tho the towers arent destroyed yet."

Note: Nim and I seem to recall this not being a thing from the start, and was trying to find out when it was added or if we're misremembering.

**Comment by rsheep** [comment]
from http://www.wowwiki.com/Patch_2.4
Warmasters/marshals in Alterac Valley now increase each other's maximum health and damage by 25%. This is a stacking effect.

**Comment by Raiilan** [comment]
As of Patch 2.4.0 (25-Mar-2008) the following was added:

Major buffs have been applied to Warmasters and Marshalls; Warmasters and Marshalls now increase each other's maximum health and maximum damage by 25%. This is a stacking buff.

And if the AV on corecraft is a Tbc mirror of patch 1.9 those buffs should't be aplied on CC?

Under patch changes section:

http://www.wowwiki.com/Alterac_Valley

**Comment by ccshiro** [comment]
@rsheep  @Raiilan Thanks!
