### ISSUE TITLE
Pet command lag

### ISSUE THREAD

**Issue by zyde** [ccshiro/cc-buglist#200]
Warlock pet Attack and Follow commands have a lag that is greater (300-1000 ms) than client's latency (80 ms). Possibly because of the pathfinding written for CoreCraft?
I compared against Smolderforge where pet commands seem to activate with same latency as client latency (same as instant cast spells basically).

**Comment by Klimpb** [comment]
Other private servers got it wrong, pet commands are not supposed to be instant, there was always a delay on retail however how long this delay was I'm not sure since it's quite difficult to measure because it depends on latency as well.

**Comment by ccshiro** [comment]
@SuddenDeath That is correct. I spent time looking at videos etc, but indeed the value could be slightly off (although I think I got it down to were it matches TBC retail quite well).

Note also that it's not enforced delay, just a higher update timer (compared to mangos) on the AI on retail, making it react a bit slower.
