### ISSUE TITLE
Desync after Arenamatch (skirmish 2v2) and apparently Bgs as well

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#2003]
On testing another bug we found out that players that leave the arena "involuntarily" desync from the other players. Involuntarily means waiting for the match to end and automatically being kicked out after viewing the details for the match. Upon using the leave button, you do not desync.

We tested killing one of each team and then one of the remaining players leaving via leave button. This made everyone but the player that left desync. We tested completely killing one team which made everyone desync. We tested one team leaving via button which made the other team desync.

How desyncing looks:
A player that was desynced this way seems to take into account his relative position to the other players in the arena at the moment the arena ended for chat purposes. That means if everyone started their arena match while standing right on the same spot but ending the arena match while standing at different corners of the arena, none of them will be able to see each other type in /s once they're outside of the arena again. Note that you still need to actually desync in order for this to happen, meaning you need to get kicked out of the arena and not use the leave button. Players that were in jumping motion when the arena ended won't be able to use anything or any spell that requires casting either. A player that desynced will not appear to move, lose or gain buffs from the perspective of other players. A paladin I did this with stood there with wings and glowing red from his trinket until he relogged. As mentioned, the desynced player relogging solves the issue.
A desynced player can still queue for another arena. He will see his desynced teammate spawn in the arena but will have the same issue as outside: restrictions on the /s chat and both won't see each other move, though they are able to. Upon start of the match the arena doors may or may not open (seems random to me, they opened once and did not on the second try). If they open he may walk across the arena to the spawning room of the opposing team and will discover it is empty, even though the (desynced) enemies confirm to be there. If the enemy team is not desynced, the desynced player will see them coming and they will be able to hit the desynced player at the point he spawned at when he joined the arena, no matter where he runs.
A desynced player will see other non-desynced players act normally.

**Comment by Jumpka** [comment]
Just happened after AV test, so I guess it's global for BGs/Arenas.

PS. Are you happy now Lianna? Will you edit the title now or do you want me to do something else MLADY?

**Comment by Liesara** [comment]
There ye go mate
