### ISSUE TITLE
[Mechanic] MotW + Frost armor can't stack

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2004]
This one is low priority I guess, but maybe something similar hapens with more important buffs.

Frost armor (the low lvl armor for mages, not Ice armor which gives frost resistances) can't be used with MotW. It treats both buffs as pure +armor buffs and the one with higher + armor will replace the one with lower +armor.
Proof that it should be possible to have both at the same time (ty KimmoKM):
https://www.youtube.com/watch?v=msR9xrYQQ6o

**Comment by Chulain** [comment]
this is kinda high priority tho (as in "fix before release")

**Comment by KimmoKM** [comment]
Not really, it's the low-level version. High-level version (Ice armor) seems to stack.

**Comment by Chulain** [comment]
don't mages use downranked spells in pvp?

**Comment by KimmoKM** [comment]
I was thinking the exact same thing but turns out armor spells aren't magic and can't be dispelled and as such recasting a cheaper version won't be needed.
