### ISSUE TITLE
[Priest] Mind control

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2007]
Might be related to https://github.com/ccshiro/cc-buglist/issues/2003 since this bug also wasn't there like a month ago or so.
When you mind control someone as a priest and move, only you see him moving, for everyone else the target of MC stays still (For the player casting MC that is moving the target, when the MC ends, the target reappears on the spot where he was before MC)

(ps. fucked and cucked liesara https://github.com/ccshiro/cc-buglist/issues/2008)

**Comment by Summoning01** [comment]
> 3.1.0 PTR Patch Notes Update - Mind Control: This spell can no longer be cast while it is already active.
> In TBC i could start Mind Controling a mob even though i was allready Mind Controling one.It just broke the first Mind Control when the second landed on the target
> 
> By loragheta (4,988 – 1·3·9) on 2007/08/11 (Patch 2.1.3)
> You can mind control members of the oppisite faction and if they can buff they can buff u or u could buff them which is really fun cause once i came upon a 10 man horde group i got mced and fully buffed which really helped me out :P
> By draguna3115 (190 – 1) on 2010/03/13 (Patch 3.3.2)
> if your in a good mood and on a pvp server you can cast this on a horde/allie then buff them its good to be nice
> By Felborn (10,440 – 2·10·85) on 2009/02/21 (Patch 3.0.9)
> Buff the opposite faction if you're feeling nice. MC them, then hit PW:F, PW:S, Shadow Protection, basically any instant-cast while you have them targeted. They'll be buffed right before Mind Control is broken.
> taohinton on 2012/01/05 (Patch 4.3.0)
> Hard as it is to believe, I can confirm this still works in 4.3.0. What happens it that the priest casts the spell on the target in the split-second for which it is still considered an ally, so be very careful if shielding straight from MC :P However, you need LoS for this to work!

these problems also occur with eyes of the beast, eye of kilrogg etc. ,abilities are greyed out when channeling

**Comment by Chulain** [comment]
@ccshiro i hope he'll notice the post above

@Soyeon1 you might want to create a new issue
