### ISSUE TITLE
Can't distinct valid targets for the cure in Administering the Salve quest

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#201]
Valid targets of the cure in Administering the Salve quest are not distinguishable from the normal orcs.
Some of the orcs who are kneeled down are valid targets (most of them) while some are not.
According to the wowhead: http://www.wowhead.com/npc=16847/debilitated-maghar-grunt#comments
They should be:
a) kneeled down
b) not wearing shoulderpads
to spot them easier.

**Comment by FurioCC** [comment]
If i recall correctly, those grunts that were applied the salve are getting buff that you could see when targeting them. Someone should check this on retail.

**Comment by ccnim** [comment]
I'm a bit confused as to what you mean but, basically you can cast it on any target is that what you mean? Because there are many debilitated orcs spread out across the area with no shoulder pads that are kneeling.

**Comment by netherspite** [comment]
There were some kneeled orcs who I was able to use cure on, but it didn't have any effect.
May be it was my bad though and they in fact had the shoulderpads.

Also there was no debuff on the orcs when I applied the cure even when I got the credit towards quest objective.

**Comment by ccnim** [comment]
Ok, fixed a few issues that I noticed but nothing of the sort that you described, I'll keep trying.

**Comment by ccnim** [comment]
Ok. I managed to find the bug and fix it.
