### ISSUE TITLE
[Priest] Fear Ward Blizzlike bug 

### ISSUE THREAD

**Issue by Mephisto22** [ccshiro/cc-buglist#2014]
There was this weird bug during TBC. If you had Fear Ward buff on yourself as a priest and sat down before a fear landed, you were immune to that fear and the Fear Ward was not consumed.

It was hotfixed in WotLK as you can see in this link: http://wowwiki.wikia.com/wiki/Fear_Ward

" Hotfix (2009-04-23): "Fear Ward will now properly be consumed whether a player is sitting or standing. [1]" "

I don't know how could Blizzard overlook this but it could've been abused during the whole TBC expansion: 

http://www.arenajunkies.com/topic/23284-101-priest-tips-and-tricks-some-you-never-knew/
"osted 08 June 2008 - 12:29 PM: if you have fear ward and sit down before being feared, the fear ward won't be consumed, essentialy making it last forever (as long as you dont stand up when the fear lands)"

Currently the Fear Ward is removed whether your character is sitting or standing. Now the question is: do we want to implement blizzard bugs like this or not?

**Comment by Jumpka** [comment]
We don't approve of retail bugs here, this is no bug zone m8.
RIP sealtwisting 2007- 2039 you will be missed.

**Comment by Mephisto22** [comment]
after reading #1002 I close this issue as well

**Comment by Schaka** [comment]
There was also another common "trick" where if you applied fear ward after a fear had already been casted on you but not yet applied to your character, you would gained the immunity AND the buff wasn't removed.

Probably due to spell delay.

**Comment by Mephisto22** [comment]
@Schaka I remember nn retail during Wotlk I could get the same effect while casting Fear Ward cca 0,3s BEFORE warlock finished casting fear. I was able to do it 100% of the time if I wasn't caught in GCD.

**Comment by Jumpka** [comment]
@Schaka @Mephisto22  you are talking about https://github.com/ccshiro/cc-buglist/issues/1479
