### ISSUE TITLE
[Priest][Talent] Silent Resolve doesn't work with shadow spells

### ISSUE THREAD

**Issue by Mephisto22** [ccshiro/cc-buglist#2015]
Priest's Tier 2 talent in discipline tree Silent Resolve doesn't increase dispel resistance for shadow spells. It shouldn't reduce the threat generation, just increase dispel resistance for shadow spells. That's what the tooltip says anyway.

http://wowwiki.wikia.com/wiki/Silent_Resolve

"As of Patch 2.0.10, Silent Resolve no longer reduces threat generated by Shadow spells."
"As of Patch 2.4, Silent Resolve affects Surge of Light, Power Infusion, Inspiration, Spirit Tap, Blackout, Levitiate, Shackle Undead, Touch of Weakness, Hex of Weakness, and Symbol of Hope."

In 2.4 they patched an issue with some spells not working with this talent and you can clearly see that there are shadow spells as well - both buffs and debuffs. I remember PvP shadow priests specing into this talent during TBC.

**Comment by ccshiro** [comment]
Actually, upon checking affected spells shadow spells are marked as affected. And trying in-game paladin cleanse failed several times over some 20-30 tries to remove my SWP.
