### ISSUE TITLE
[Paladin] Seal of the crusader + Crusader strike

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2019]
This is low priority one, since nobody really uses Seal of the Crusader when they already have Crusader strike (lvl 50+), but since 2.4.2 Crusader strike should deal 40% more damage with SotC up. This is just to compensate for the damage reduction you get from SotC, not to make it stronger than without a seal or so. Right now, if you have SotC up and use Crusader strike, it will deal like 60% of the normal damage.
Proof:
http://us.battle.net/wow/en/game/patch-notes/2-4-2

> Seal of the Crusader: This ability now increases the damage dealt by Crusader Strike by 40%.

**Comment by Chulain** [comment]
this kinda makes sense, any proof?

**Comment by Jumpka** [comment]
Oh, I'm sorry, somehow I foregot to put the proof link in the post, edited it now

**Comment by Jumpka** [comment]
https://github.com/ccshiro/cc-buglist/issues/2092 my fuckup, sry
