### ISSUE TITLE
[Priest][Spell] Spirit of Redemption bugging out

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2021]
While in Kaels fight, after dying SoR procced, once the effect was clicked off or finished. my character (and other priets) got stuck at 1hp without being able to move/cast anything.

how to reproducce:
honestly no idea

![captura de pantalla 2015-11-10 a las 21 07 49](https://cloud.githubusercontent.com/assets/13721369/11148860/aa94e7ca-8a1f-11e5-885e-3d18f1f362d3.png)
![captura de pantalla 2015-11-10 a las 21 07 25](https://cloud.githubusercontent.com/assets/13721369/11148861/aa9da090-8a1f-11e5-8f22-411ce907754d.png)

**Comment by Jumpka** [comment]
https://github.com/ccshiro/cc-buglist/issues/1672

**Comment by ghost** [comment]
happened again in AQ40,

i THINK the trigger is getting killed by something (i think only aoe spells can kill you) while SoR triggers, this has to happen really fast. like die due to some kind of debuff, and instantly get attacked by AoE (sartura whirlwind)

Also, this ONLY HAPPENED in sartura, i was able to keep healing, though i had no mana regen or could be killed or anything

![cthun alive](https://cloud.githubusercontent.com/assets/13721369/12929864/6dbb0de8-cf75-11e5-87f0-cb8c92e87fd1.png)
![cthunalive2](https://cloud.githubusercontent.com/assets/13721369/12929865/6dbbe75e-cf75-11e5-9fab-b7127fff7e24.png)

**Comment by ccshiro** [comment]
Looked at the issue, same bug as #1672.
