### ISSUE TITLE
water elemental (and possibly all pets)

### ISSUE THREAD

**Issue by jipples** [ccshiro/cc-buglist#2029]
While leveling up on a mage, whenever your water elemental does more than a certain threshold of damage (25% i believe), it will take away a percentage of your experience based on the damage it deals. This functions much like it would if a player helped you kill a mob but did a significant portion of the damage.

**Comment by Chulain** [comment]
related: https://github.com/ccshiro/cc-buglist/issues/995

**Comment by Klimpb** [comment]
Feels like something's not 100% right at the moment, though I may be wrong but leveling from 1-9, it's almost impossible to not lose a significant amount of experience if you just let your pet auto-cast while you try to kill a target.

example(same mob, first solo & the other with pet helping): https://youtu.be/pfMctIZqKnU
