### ISSUE TITLE
Pladin ret aura stacking 

### ISSUE THREAD

**Issue by gabi33** [ccshiro/cc-buglist#2032]
Swapping from paladin t5 2 set bonus to no set bonus makes ret aura recast,stacking it 2 times on the player. It is not only a visual bug,as we tested it,and it does damage with both auras.

In order to reproduce this bug you need to have 2 t5 paladin pieces->no ret aura->cast ret aura->unequip the 2 part set bonus of t5.

EDIT: can not reproduce the bug anymore after my first respec,eventhough none of the specs had any pts in imp ret aura.

**Comment by ccnim** [comment]
#2326
