### ISSUE TITLE
Silence effects shouldn't be affected by DRs.

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2033]
As the title says, DR on silence effects was introduced in patch 3.0.8
http://wowwiki.wikia.com/wiki/Patch_3.0.8

> All Silence spells now have diminishing returns. This includes: Arcane Torrent, Garrote silence effect, Improved Counterspell effect, Improved Kick effect, Silence, Gag Order, Silencing Shot, Spell Lock, and Strangulate.

Apperantly it was tested on 2.3 PTR server, but didn't make it to live
http://www.mmo-champion.com/threads/603067-Dim-returns-on-silence-removed-TCG-loot

> After further discussion about the change in patch 2.3 which adds diminishing returns to silencing effects, we've decided to revert the change.

Videos from TBC showing no DRs on silence effects:
https://www.youtube.com/watch?v=jD7R0WZiV0U#t=8m30s spell lock + full silence
https://www.youtube.com/watch?v=gx9_yykxk3k#t=14m6s spell lock + full second spell lock
http://www.warcraftmovies.com/movieview.php?id=55762 full of double Counterspells

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=T8x3337ffwg

**Comment by DarkenRal** [comment]
There are actually 1 silence that should be affected by DRs. Warlock's Unstable Affliction. It should have DR with itself but not with other silences. http://wowwiki.wikia.com/wiki/Patch_2.3.0#Warlock

> Unstable Affliction: The silence from this ability is now subject to diminishing returns.
