### ISSUE TITLE
[Karazhan] Swapping ring once exalted 

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#2034]
So when you're exalted with Violet Eye there's a repeatable "quest" that allows you to pay 75 gold and swap the ring. 

However when I try to do this, I get "You don't have enough money". I have plenty of gold. 

Reproduce:
Exalted with violet eye, choose a ring.
Attempt to talk to Archmage Leryda to swap to another ring.

**Comment by ghost** [comment]
Rings plx

**Comment by Ickler** [comment]
No idea why I was so set on trinkets while doing this -_- In any case, edited.
