### ISSUE TITLE
[Instance][NPC][Spell] Cant break charm casted by coilfang sorcerer(or witch or whatever) with WoTF

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2040]
Clearly explained in the title

![captura de pantalla 2015-11-17 a las 21 17 33](https://cloud.githubusercontent.com/assets/13721369/11269262/313037ae-8eb6-11e5-9058-ab5629cee81f.png)

**Comment by Chulain** [comment]
it's enchantress and name does matter :p
npc: http://www.wowhead.com/npc=17961/coilfang-enchantress

altho they dont appear to have the spell on wowhead (comments say they do), they're likely using the same spell as the Soothsayers
npc: http://www.wowhead.com/npc=17960/coilfang-soothsayer
spell: http://www.wowhead.com/spell=30923/domination

Apply Aura: Charm
Value: 70

**Comment by ghost** [comment]
@chulain thing is I don't really know if it was the mob I was targeting the one that casted the mind control and I haven't had the time.to check the spells of each one , anyhow thank you for your help :)

**Comment by ccshiro** [comment]
Their domination is not mechanic charm, so you shouldn't be able to break it with WotF.
