### ISSUE TITLE
[Azeroth][NPC] Mob walking under the ground in tanaris

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2041]
I know its missing the .movegen, i simply dindt have time to type it since it got out of the ground and never got back in again (for the minute or 2 i took watching it)

![captura de pantalla 2015-11-19 a las 21 31 59](https://cloud.githubusercontent.com/assets/13721369/11287512/7061d3e0-8f1c-11e5-8836-b69993b38b80.png)
![captura de pantalla 2015-11-19 a las 21 32 00](https://cloud.githubusercontent.com/assets/13721369/11287511/70605f88-8f1c-11e5-82c8-f6a2e7993698.png)

**Comment by ccshiro** [comment]
Think this is the same as #2039.
