### ISSUE TITLE
[Instance][NPC] Erozion wants me to carry bombs no matter what

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2042]
After we cleared the instance on heroic mode, he still wanted to hand me some bombs, i dindt have any on my inventory since i had already used them. once i took them, he allowed me to travel back to my time (second screenshot)

![captura de pantalla 2015-11-19 a las 23 46 36](https://cloud.githubusercontent.com/assets/13721369/11287534/acc572ec-8f1c-11e5-9e5f-276f936a7ecd.png)
![captura de pantalla 2015-11-19 a las 23 47 37](https://cloud.githubusercontent.com/assets/13721369/11287535/acc92040-8f1c-11e5-8deb-37df8273b89c.png)

**Comment by ccshiro** [comment]
The RP event was not finished yet, which means the dungeon is still waiting to complete. If you wait for the Erizon RP to finish, the event will be marked as complete and he'll stop trying to give you a bomb.
