### ISSUE TITLE
Broggok 2nd boss Heroic Blood Furnace Bugged

### ISSUE THREAD

**Issue by whitestar87** [ccshiro/cc-buglist#2045]
My group tried to do blood furnace on heroic mode today.  We pulled the lever and had 2 of the compartments aggro in order, and then there was a pause before the next two - we couldn't remember if there was time to drink between each of the rooms.  After we cleared all of the orcs, the Boss did not open the gate to aggro us, nor did the gate behind us open.  We were unable to finish the dungeon.

**Comment by KimmoKM** [comment]
Unless something has changed during the past month or so (I did BF quite recently and had no issue), this is a one-time glitch (maybe two players clicked the lever simultaneously or something?)

**Comment by whitestar87** [comment]
I don't believe that's what happened, the tank was by himself when he pulled the lever.  I will see if I can get back in there to test it again.

**Comment by Lephidiles** [comment]
i Guess her. But we had a similar issue: sometimes you can target npcs while in the "cage" and pull them out. If you do this it will bug out like you said... opening the remaining gates on a timer
 and never relasing the boss.

For this to happen though you usually need to wipe one time first

This issue should be reported if it is this

**Comment by ccshiro** [comment]
Probably same cause as #1368.
