### ISSUE TITLE
[Mage] Water Elemental HP and Mana

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2052]
First off I'm not 100% sure that this is how it should be in 2.4.3, but I think I have proof that the low HP was still present at least in 2.4.2. I think that the HP buff happened in the 3.0.2 WotLK pre-patch, and that's why I couldn't find any mention of it, since most of the spells were completely rebalanced.

3.0.2 https://www.youtube.com/watch?v=mhOlbOsEC6c#t=14m47s around 7k HP
2.4.2+ https://www.youtube.com/watch?v=VoOQx-0AuMU#t=1m40s around 3800 HP (if you count the damage up you get 3620 + around 140 or so)

Now to the actual HP values: 
EDITED, SHOULD BE 100% CORRECT NOW
Big thanks to Barroth for telling me that the Mage to Pet stamina ratio is always 0.3, the only thing that changes is the Pet stamina to Pet HP ration.
Thanks to bug on retail, where elemental gained HP from stats after 1 sec or so, you can see in many videos that the base HP is 2126. Using linear regression on the data I got yielded 2.247 coef on Mage stam to Pet's HP, now knowing the stuff Barroth pointed out that pet's always get constant 30% of masters stamina, the only thing that changes it stamina to HP ration for pet's, so in this case it should be 1 stam = 7.49 hp. 
Since blizzard probably didn't use such strange value, I rounded it to 7.5 and checked, what kind of rounding has to be used to get all those values. To get everything correctly, I had to round down pet's stamina and round normally (or up since the number will be always .0 or .5) his final HP (did basically the same shit for the Mana part):

**Pet HP = Round(2126 + 7.5*Math.floor(Mage Stam \* 0.3))**
**Pet Mana = Math.floor(2375 + 4.95*Math.floor(Mage Int \* 0.3))**

(not sure why there/s different rounding for both, I would need more data, but I think the pet HP might be something like Math.floor(2126.5 + 7.5*Math.floor(Mage Stam \* 0.3)) which would give the same result)

https://www.youtube.com/watch?v=K4WR0JW5jWM#t=1m24
https://www.youtube.com/watch?v=K4WR0JW5jWM#t=8m1
https://www.youtube.com/watch?v=zSYOBLu14Ac#t=1m10s
https://www.youtube.com/watch?v=Be00nb46jp8#t=1m53s

(Note: I will go trough the Mana part later when I'll have more time)

**Comment by Jumpka** [comment]
Just a bit of Maths:

HP:
Pet Base HP = 2126
Mage stam to Pet stam = 0.3
Pet stam to Pet HP = 7.5
Mage base HP = 3393
Mage base Stam = 18 (the one that doesn't count towards your max HP but shows in stats)

Mana:
Pet Base mana = 2375
Mage int to Pet int = 0.3
Pet Int to Pet mana = 4.95
Mage base Mana = 1961

https://www.youtube.com/watch?v=K4WR0JW5jWM#t=1m24
HP:
HP mage  =9623      HP pet = 3566
Stamina in char sheet = ((9623-3393)/10)+18 = 641
Pet Stam = Math.floor(641_0.3) = 192
Pet HP = Round(2126+7.5_192) = 3566
Mana:
Mana mage = 8272   Mana pet = 2998
Int in char sheet = (8272-1961)/15 = 421
Pet Int - Math.floor(421_0.3) = 126
Pet Mana = Math.floor(2375+4.95_126) = 2998

https://www.youtube.com/watch?v=K4WR0JW5jWM#t=8m1
HP mage  =9723      HP pet = 3589
Stamina in char sheet = ((9723-3393)/10)+18 = 651
Pet Stam = Math.floor(651_0.3) = 195
Pet HP =Round(2126+7.5_195) = 3589
Mana:
Mana mage = 8951   Mana pet = 3063
Int in char sheet = (8951-1961)/15 = 466
Pet Int - Math.floor(466_0.3) = 139
Pet Mana = Math.floor(2375+4.95_139) = 3063

https://www.youtube.com/watch?v=zSYOBLu14Ac#t=1m10s
HP mage  =10033      HP pet = 3656
Stamina in char sheet = ((10033-3393)/10)+18 = 682
Pet Stam = Math.floor(682_0.3) = 204
Pet HP =Round(2126+7.5_204) = 3656
Mana:
Mana mage = 8981   Mana pet = 3068
Int in char sheet = (8981-1961)/15 = 468
Pet Int - Math.floor(468_0.3) = 140
Pet Mana = Math.floor(2375+4.95_140) = 3068

https://www.youtube.com/watch?v=Be00nb46jp8#t=1m53s
HP mage  =10243      HP pet = 3701
Stamina in char sheet = ((10243-3393)/10)+18 = 703
Pet Stam = Math.floor(703_0.3) = 210
Pet HP =Round(2126+7.5_210) = 3701
Mana:
Mana mage = 9266   Mana pet = 3097
Int in char sheet = (9266-1961)/15 = 487
Pet Int - Math.floor(487_0.3) = 146
Pet Mana = Math.floor(2375+4.95_146) = 3097

**Comment by Barroth** [comment]
The values above are nice, seems like the pet should have a 7.5 modifier on stamina to health.
All \* are missing though, so it is hard to read. 6510.3 for example is 651 \* 0.3

Screenshot from Noone 2
Should be interesting, the hp the elemental currently has is the base hp, the missing hp are the 35% of masters stamina. Blizz hackfixed it and the pet isn't summoned with full life, but instead it gets healed to full shortly after summoning.

![vlcsnap-2015-11-21-19h15m37s709](https://cloud.githubusercontent.com/assets/9391338/11319820/726dfdd0-9084-11e5-8c53-ddeb981bb18d.png)
