### ISSUE TITLE
Helboars do not change model when transforming into Dreadtusk

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#206]
In the quest Testing the Antidote you're using the Cenarion Antidote on a Hulking Helboar.
It should be transformed into Dreadtusk changing its model into something greeny: http://www.wowhead.com/npc=16992/dreadtusk
However, they change only the name, leaving model the same.
Initially I even thought the Antidote didn't work, but it's just hard to notice that it had worked.

**Comment by netherspite** [comment]
![wowscrnshot_011815_184708](https://cloud.githubusercontent.com/assets/5777848/5793311/91d20b64-9f47-11e4-87eb-5acb54c2623c.jpg)

**Comment by Grzmociarz** [comment]
model is fine "As of patch 4.0.1, these mobs are now gray with green toxic spikes."

**Comment by netherspite** [comment]
My bad, I believed it should differ better than just by name.
