### ISSUE TITLE
Minor Socket bonus bug on Cyclone Faceguard

### ISSUE THREAD

**Issue by nognig** [ccshiro/cc-buglist#2060]
Socketing Cyclone Faceguard with a Gleaming Dawnstone seems to work fine initially, but changing the socket to a potent Noble Topaz does not grant me the extra spellpower. I can't say if it is an issue with socket bonuses in general or just this one item. May require further testing.

**Comment by Jumpka** [comment]
nognig are you sure it's not some of the alredy reported socked bugs?

**Comment by Liesara** [comment]
https://github.com/ccshiro/cc-buglist/issues/1190
https://github.com/ccshiro/cc-buglist/issues/1659
https://github.com/ccshiro/cc-buglist/issues/1970
