### ISSUE TITLE
[Druid][Rogue] Stealth fades when opening raid panel

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2064]
Edit : scratch all I said before editing this, I was probably mistaken for most of it.

Also good news, it's not that random.
- Stealth fades when opening the raid panel. You don't have to be in a raid for this to work.
- Play a rogue or druid, go in stealth, open raid panel, get unstealthed.
- Other factors may be at play. I believe I got unstealthed when I grouped with someone, but it happened only once. I tried again with someone else and it didn't work. I may be mistaken but I don't have anyone "new" to try it on. (I believe it only works if you group with someone you haven't grouped with before)

**Comment by Jumpka** [comment]
Easiest find of my life kek - it's opening the raid tab
EDIT: As pointed out by Pyralis, it's actually /run RequestRaidInfo() which cancels it.

STEPS TO REPRODUCE:
Cast stealth on rogue / druid prowl
Open raid tab or do /run RequestRaidInfo()
Stealth will cancel

**Comment by ghost** [comment]
Nice find. Any idea if grouping with someone automatically runs the same script that does when you open the raid panel ? (could it be xperl running it for example ?)

I remember clearly getting unstealthed when grouping with somebody. I also have some recallings of getting unstealthed randomly, without opening the raid panel ... could an addon (like xperl again) be running the script every now and then ? That'd explain a lot of the frustration I had to go through to find the origin of this one.

**Comment by Jumpka** [comment]
Ye, I was just joking in that post, there definitelly might be something else to it, but so far it seems that only the RequestRaidInfo causes that, it would be good to know the full list of your addons that you had turned on (besides already mentioned x-perl), so I could try to reproduce it the way it happened to you and see if it's something else. (I have x-perl and the only thing that unstealthed me so far was the raid info request thing)
