### ISSUE TITLE
[Mechanic] Some spells shouldn't be affected twice by spelldelay

### ISSUE THREAD

**Issue by Jumpka** [ccshiro/cc-buglist#2067]
Right now on CC, if let's say you use a hemorrhage on someone and that hemo procs a poision, it will be 0-400ms delay on hemo + 400 MS delay on the poison proc. Same goes with for example improved hamstring / wing clip, which will always be 400ms delayed after the (already delayed by 0-400ms spelldelay) normal hamstring/wing clip. On the other hand it seems that Winter's chill was delayed on retail the same way it is on CC right now.
Source video (already with a dank frame by frame function thanks to Pyralis, just keep in mind it's only for moving by one frame, the time it shows for the frames is not exactly correct since it's not stable FPS): 

http://anilyzer.com/?page_id=7&type=youtube&vId=IB7bUNWTlh4#playbackRate=1&seekTo=0
10:13 Frost bolt + Frost bite at the same time when damage happens, Winter's chill later
23:55 Hamstring + Improved hamstring at the same time
4:26 Cheap shot + poison at the same time

(I will try to find as much things as possible and post it here)

**Comment by ccshiro** [comment]
I've fixed the cases you listed, if you find any other you can just reopen the issue.

**Comment by Klimpb** [comment]
#1526 is another one.

**Comment by Evolvee** [comment]
same with shadow weaving talent(dot delay--> shadow weaving talent proc delay) but how can u be sure its not blizzlike -.- you would have to test every single class spell in this game and every single spell interaction and then compare to retail videos.. gl
