### ISSUE TITLE
[Spell][Class:Mage] Recasting Mana shield + Ice barrier does not refresh the duration of the buff

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2068]
So like the tittle says, recasting the spells does not refresh the duration of the debuff.

steps to reproduce:
1. create a mage and get ice barrier
2.cast ice barrier (duration:1 min, CD: 30 secs)
3. when the CD is ready again, you should have 30 secs left on the buff
4. wait 5 seconds, recast ice barrier
5. icebarrier duration will be 25 seconds.

it should go back up to the full minute since its recasting the spell again.

![captura de pantalla 2015-11-27 a las 13 21 05](https://cloud.githubusercontent.com/assets/13721369/11454062/0babd2c2-9622-11e5-805d-a03739da3a0a.png)
![captura de pantalla 2015-11-27 a las 13 21 10](https://cloud.githubusercontent.com/assets/13721369/11454063/0bc6a55c-9622-11e5-9f9e-80303c2510c8.png)

**Comment by Liesara** [comment]
https://github.com/ccshiro/cc-buglist/issues/2030
