### ISSUE TITLE
Vile Familiars

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2071]
Currently, orc warlocks can get their class quest [Vile Familiars](http://wowwiki.wikia.com/wiki/Quest:Vile_Familiars_%28Warlock%29) immediately. I was unable to find retail videos showing level 1 locks in Valley of Trials, but considering the quest replaces [another quest with the same name](http://wowwiki.wikia.com/wiki/Quest:Vile_Familiars) that isn't available for other classes until some prerequisites, I think it's pretty clear this shouldn't be the case.

**Comment by ccnim** [comment]
This actually should be the case oddly enough.
