### ISSUE TITLE
Zepelins Animation

### ISSUE THREAD

**Issue by Pinhastest** [ccshiro/cc-buglist#2079]
Zepelins from ogrimar to STV and from STV to ogrimar have some weird behavior after loading screen.
Showing us under the floor, at weird locations.
![captura de ecra 2015-12-05 as 22 46 23](https://cloud.githubusercontent.com/assets/10587278/11610654/112c04f8-9ba2-11e5-98ff-83c7f6bf7aed.png)
![captura de ecra 2015-12-05 as 22 48 12](https://cloud.githubusercontent.com/assets/10587278/11610661/5927aece-9ba2-11e5-8b6c-4e80b8ea2fc0.png)

**Comment by KimmoKM** [comment]
#114
