### ISSUE TITLE
Arena ranking seem to be counting the opposite way.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#208]
Our rank seemed to have been 130 or so, then we won a few games and when I checked again we were rank 144.
![](http://i.gyazo.com/48c0bbb843ce207ffa1c38373dd72c3c.png)

**Comment by ratman2** [comment]
maybe because other teams also played some games in the meantime?

**Comment by sirdouchelton** [comment]
Can confirm. Our arena rank went up instead of down after each game. Went 19-0 and there were only us and the other 2vs2 team playing at that time.

**Comment by ccshiro** [comment]
The rank does seem to behave strangely, will check through the code.
