### ISSUE TITLE
Epoch Hunter in OHF hc

### ISSUE THREAD

**Issue by gabi33** [ccshiro/cc-buglist#2080]
Thrall's speech was not working durring the 3rd try.

Thrall also attacked our hunter's pet and after that the hunter himself after finnishing combat with the guards near the tower,on the way to tarren mill.

Also,durring all of our tries a bunch of mobs from nearby would aggro on us.The mobs were  just like the humans before epoch hunter transforms them in dragonkins,they still casted their dragonkin spells while being in human form.
Also,both of our mages spell stealed the aura from the boss (the aura has 45 yards range) so we belive this is the cause for the pulls.
The aura is supposed to be spell stealable,but he should not instantly recast it,as he did on our trys.

As a note,i did OHF hc yesterday (5/12/2015) and none of these issues were present at that time.(not sure about thrall's speech working durring 3rd try,as we killed it on our 1st.)

**Comment by ghost** [comment]
adding on the "The aura is supposed to be spell stealable,but he should not instantly recast it,as he did on our trys"

The aura is supposed to be stealable as seen on http://wowwiki.wikia.com/wiki/Epoch_Hunter?oldid=511115 and many other revisions of the boss fight. however he should only recast it every 10 seconds, on the CC test server he recasts its almost isntantly which is a bug

also, adding this SS to support the first claim, "humanoids"(most likely aggroed by the 45yard range of the dispell aura) casting spells whcih should only be avaible on the "morphed" state
![captura de pantalla 2015-12-06 a las 23 11 39](https://cloud.githubusercontent.com/assets/13721369/11616049/38ad0b10-9c71-11e5-82af-64cce2b2b238.png)

**Comment by Aprics** [comment]
The speech seems to bug in multiple ways but only if you wipe on the boss .Never on the first try.
I believe Ickler opened one where Thrall spammed the chat.
