### ISSUE TITLE
Zeppelin from Orgrimmar to Grom'Gol

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#2085]
I just took the Zeppelin from Orgrimmar to Grom'Gol, and didn't saw the zeppelin going out (I went straight to the loading page) and got stuck in Alterac Mountains. After 30seconds+, I was in Grom'Gol.
Good ending, but through a strange journey !
(Btw isn't the NPC on top of Zeppelin tower supposed to /yield when Zeppelin just arrived ?)

**Comment by Liesara** [comment]
https://github.com/ccshiro/cc-buglist/issues/114
https://github.com/ccshiro/cc-buglist/issues/1845
https://github.com/ccshiro/cc-buglist/issues/2079

There's been a ton of duplicates the last few weeks. Can't anyone use the search function? The last Zeppelin one is just 6 posts earlier...

**Comment by Summoning01** [comment]
atm orgrimmar-grom'gol zeppelin is not showing up at all at orgrimmar tower
