### ISSUE TITLE
Expertise

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#2091]
Expertise needed for dodge cap seems to be 1% lower for yellow hits than it is for White hits

From a test with 1368 White melee hit from behind and 1000 Yellow hits from behind i got the following
Tested with orc using an axe and 20 Expertise rating (2.50% reduction)
White dodges: 3,1%
Yellow dodges: 2,1%

Will upload some pictures afterwards

**Comment by Lephidiles** [comment]
http://imgur.com/a/1rOVL

Might just be that the sample size is to small

**Comment by Lephidiles** [comment]
http://imgur.com/nqIU8r1

**Comment by ccshiro** [comment]
The dodge chance is calculated the same way for both cases. Attached the debugger to make sure, and it ends up being the same. Unless something else goes wrong to cause a difference (don't see anything that looks odd), I think it's just a case of too small sample size.
