### ISSUE TITLE
Ring - Stats Formula

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2093]
http://www.wowhead.com/item=22538/formula-enchant-ring-stats#comments 

The formula should be 2.1 as it is obtainable through The Scale of the Sands reputation.
It is apprently sold by Andormu

**Comment by ASrozaev** [comment]
bullshit, fix еvеrything to 2.1
all skills and talents to 2.1

**Comment by ghost** [comment]
nobody knows the exact state of 2.1 talents/skills since most mechanic changes don't get into the official blizzard changelogs, your argument is invalid
