### ISSUE TITLE
Enchant Shield - Resistance

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2095]
The mats needed for enchant Shield - Resistance got reduced in 2.4

http://www.wowhead.com/item=22541/formula-enchant-shield-resistance#comments

The original mats were 3 fire-, air-, water- and earthmotes instead of just 1 each.
Also 6 Large Prismatic Shards instead of only 2

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
