### ISSUE TITLE
Enchant Boots - Surefooted

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2096]
The enchant Sureffoted took a  Runed Eternium Rod in 2.0.3

http://www.wowhead.com/spell=27954/surefooted#comments

This is kinda stupid by Blizzard because the Encahnt has a lower skill lvl (370) than the rod needed to enchant it (375). That is probably the reason they changed it later on to the Runed Fel Iron Rod

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
