### ISSUE TITLE
Enchant Weapon - Sunfire

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2097]
Mats changed in 2.2

http://www.wowhead.com/spell=27981/sunfire#comments

6 Void Crystals
10 Large Prismatic Shards
8 Greater Planar Essence
10 Primal Fire
2 Primal Might

were the original mats

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
