### ISSUE TITLE
Classic Enchants updated to TBC

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2098]
Some old classic enchants from ahn'qiraj got updated in 2.2 and added to the TBC reputation vendors with new mats (TBC mats instead of classic mats).

Gloves - Superior Agility 
http://www.wowhead.com/spell=25080/superior-agility#comments
8x Large Brilliant Shard
3x Nexus Crystal
4x Essence of Air

Gloves - Threat 
http://www.wowhead.com/item=33153/formula-enchant-gloves-threat#comments
4x Nexus Crystal
6x Large Brilliant Shard
8x Larval Acid

Cloak - Subtlety
http://www.wowhead.com/spell=25084/subtlety#comments
4x Nexus Crystal
6x Large Brilliant Shard
2x Black Diamond

Cloak - Stealth
http://www.wowhead.com/spell=25083/stealth#comments
3x Nexus Crystal
8x Large Brilliant Shard
2x Black Lotus

Cloak - Dodge
http://www.wowhead.com/spell=25086/dodge#comments
3x Nexus Crystal
8x Large Brilliant Shard
8x Guardian Stone

Cloak - Greater Nature Resistance
http://www.wowhead.com/item=20733/formula-enchant-cloak-greater-nature-resistance#comments
2x Nexus Crystal
8x Large Brilliant Shard
4x Living Essence

Cloak - Greater Fire Resistance
http://www.wowhead.com/item=20732/formula-enchant-cloak-greater-fire-resistance#comments
3x Nexus Crystal
8x Large Brilliant Shard
4x Essence of Fire

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.

Nim has changed the source of these items, though to reflect the pre 2.2 state.
