### ISSUE TITLE
BG regeneration buff

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#21]
Report:
"Hello

The Health Regeneration buff is removed by DoTS.
It is supposed to only be removed by Direct Damage.

I have tried desperately to find proper video confirmation, but wasted an hour doing so."

Note: we're inclined to remember that the regeneration buffs in WSG broke on any damage, even DoTs. Need some evidence in either direction.

**Comment by Georgerrrrr** [comment]
http://eu.battle.net/wow/en/forum/topic/2690869962

**Comment by kolchax** [comment]
It's not removed by DoTS. That's just a bug on 90% of the private servers.

**Comment by Doppelmoral** [comment]
http://www.wowwiki.com/Warsong_Gulch

"Restoration - Restores 10% of your health and mana every second for 10 seconds. Attacking or being attacked will cancel the effect."

The statement reflects (in conformity with retail experience) that only active HARMFUL actions cast while under the effect will cancel the buff.

Casting or receiving a DoT will remove Restoration. Already active debuff ticking, however, will not ('attacking or being attacked' -> a casted DoT will put you infight, but you leave combat after 5 seconds even while the DoT is ticking, means a tick per se is not considered an individual attack). Sidenote: Even healing or buffing oneself, or others, will not affect this Power-Up. Only restriction was indeed the involvement of harmful abilities actively used or received after picking up Restoration. (Which was, to my knowledge, never changed throughout the patches and updates, if you can please try to reproduce on retail WoD !)

**Comment by Pammelton** [comment]
This was a bitch to find out so I'm going to post all the information and sources I found in case any further questions or reports are made about it.

This I believe answers the question, I tried my best to analyse it as thoroughly as I could, someone else is free to try also: http://www.youtube.com/watch?v=eQhSz-qYgN4&t=1m53s - The warrior here has 2 serpent sting effects on them at 1:53, they grab the restoration buff and it continues to heal them as the DoTs tick. It isn't removed until the player intercepts at 1:57. The hunter's pet seems to hit them during this time but it doesn't take away the restoration buff, meaning perhaps only actions caused and received by players removes the buff? After the DoTs deal damage at 1:56 when the buff is clearly active, the warrior seems to gain one more tick of restoration before it fades, bringing their health bar to a darker green colour. 

The numbers I've managed to vaguely make out are that they grab the buff with 5500 HP at 1:54 and take a total amount of 373 damage (207+166) from the serpent stings in addition to some damage caused elsewhere, taking them down to around 5000 HP, the restoration buff then heals up to 5900 at 1:55 and then Blood Craze ticks taking it up to 6000, they take damage taking them to 5300 and then are healed to 6070, at this point they clearly take damage from the serpent stings (yellow damage on the portrait) and their health raises twice more, one 7021, and lastly to 8013 before fading, it does this with help of the second tick from blood craze. On the players portrait, white damage is the pet damage, yellow damage is serpent sting.

Restoration breaks on ANY sort of combat effect, here's proof that cheap shot (which does no damage) removes the effect: https://www.youtube.com/watch?v=_9MOyED5KSo&t=2m23s at 2:23 they grab the restoration buff, at 2:28 the rogue cheap shots them and the buff fades, that's 5 seconds of restoration. It fades before any further damage from the rogue is caused. 

And here's some bonus sources I found which are already known; regeneration breaks on direct damage caused: https://www.youtube.com/watch?v=hJHqj1859YY&t=7m45s - 7:45, breaks on direct damage caused from fire blast

definitely breaks on damaging crowd control https://www.youtube.com/watch?v=r1IYrvBArCk&t=3m56s - starts at 3:56, they gain the buff at 3:56, hit with a scatter shot at 4:00, buff fades, that's 4 seconds of regeneration (vanilla video but it's very clear and I don't think it changed)

**Comment by Doppelmoral** [comment]
When I posted my comment I tried to emphasize the "attack" rather than "damage".

It should break on (active) damage, no arguing there - but as said previously any ATTACK, which is not a heal or buff, should cancel it all the same. Cheap Shot, Charge / Intercept are active, nondamagedealing attacks, thus should break it.

The question is if an attack done previously ( a DoT in this case) would cancel Restoration if still active, which I believe should not be the case (therein lies the power of Restoration, it can heal through DoTs, else you could just get out of combat with DoTs and start eating food to restore Healthpoints)

**Comment by Pammelton** [comment]
Hm? That's what the video I posted shows. It shows the warrior went to get the restoration buff with DoTs on him, and the healing persisted through the damage. It didn't cancel the effect until an attack was used. Watch it at 0.25 of the speed (press the cog in the corner and select speed).

**Comment by Doppelmoral** [comment]
Yes, you are right. (Btw I am sure any interaction with a pet would have the same effect as if with a player)

Just pointing out that the emphasis is indeed on 'attack' rather than 'damage' (->harmful)

**Comment by ccshiro** [comment]
@Pammelton Thank you for that thorough write-up.

@Everyone Thanks for the help.
