### ISSUE TITLE
Vanish stealth level added appears wrong (PvE)

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#210]
The level of stealth vanish adds seems to be off. After distracting 70-71 mobs away and approaching from side with a pre-vanish condition they spotted me very easily. From my knowledge this was a perfectly doable sap on retail, but was not even close to possible on this test.

**Comment by ccshiro** [comment]
The formula for stealth and vanish is correct (we implemented that just a few months back after a lot of research), but the effect of both of them is behaving oddly atm when I'm testing.
