### ISSUE TITLE
Enchant Bracer - Spellpower

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2100]
The materials needed for this enchant have been changed in 2.1

http://www.wowhead.com/spell=27917/spellpower#comments

pre 2.1
6xLarge Prismatic Shards, 8x Primal Fire and 8x Primal Water

post 2.1
6xLarge Prismatic Shards, 6x Primal Fire and 6x Primal Water

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
