### ISSUE TITLE
Enchant Ring - Spellpower 

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2101]
http://www.wowhead.com/item=22536/formula-enchant-ring-minor-intellect#comments

mats got changed in 2.2 

pre 2.2 it was:
8x Large Prismatic
8x Greater Planar

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
