### ISSUE TITLE
Enchant Ring - Healing Power

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2102]
Before Patch 2.2.0 the components used to be:

8x [Large Prismatic Shard]
10x [Greater Planar Essence]
20x [Arcane Dust]

http://wowwiki.wikia.com/wiki/Formula:_Enchant_Ring_-_Healing_Power
http://www.wowhead.com/item=22537/formula-enchant-ring-healing-power

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
