### ISSUE TITLE
Enchant Ring - Striking

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2103]
Prior to patch 2.2 this enchant required:

8x [Large Prismatic Shard]  
24x [Arcane Dust]

http://wowwiki.wikia.com/wiki/Enchant_Ring_-_Striking
(the name was Striking before weapon might and then got changed back to striking so there is no need to change the name)

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
