### ISSUE TITLE
Enchant Weapon - Battlemaster

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2104]
http://www.wowhead.com/spell=28004/battlemaster#comments:40
mats got changed in 2.2

Pre 2.2 materials :

2x Void Crystal
8x Large Prismatic Shard
8x Primal Water

**Comment by ccshiro** [comment]
We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
