### ISSUE TITLE
Zeppelin Debris respawn time

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2105]
Zeppelin Debris for quest [In Case of Emergency](http://www.wowhead.com/quest=10161/in-case-of-emergency) seems to respawn exceptionally fast (I timed it at 25 seconds). In places where the debris is more clustered, like the one pictured, the first piece has respawned by the time you pick others up.

I don't know what the respawn timer should be, but as far as I can tell, this almost certainly is not it.

![2015-12-12-170227_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/11762520/246fb35c-a0f2-11e5-80c2-0758af770c6b.png)

**Comment by Chulain** [comment]
prolly cuz you need 30 and there will a shitton amount of ppl on launch

**Comment by KimmoKM** [comment]
True, it might be deliberate. Then again, shouldn't #1067 address the issue without default value being off?

Anyway, up for the devs to decide (and since I couldn't find proof, I guess there is some possibility the respawn timer really should be 25 seconds and this report is invalid).

**Comment by KimmoKM** [comment]
Looks like there's a precedent in another issue: Shredder Parts in "Outland Sucks!" respawn in some 5 seconds (#965) and Shiro created a more general Dynamic Respawn Timer issue and NiM closed the one about Shredder parts.
