### ISSUE TITLE
[Slave pens] - The patrol in picture,

### ISSUE THREAD

**Issue by KMKM2696** [ccshiro/cc-buglist#2115]
![lolbug](https://cloud.githubusercontent.com/assets/16328326/11857434/1bd135c0-a450-11e5-8a80-38a4396b4b21.jpg)

Once the patrol has been pulled and there has been a wipe from the patrol said patrol will just remain in place and will no longer continue to move until pulled. Thanks.

**Comment by ccshiro** [comment]
Noticed this issue is a duplicate of #1220.
