### ISSUE TITLE
Ring of Blood double Summon

### ISSUE THREAD

**Issue by Liesara** [ccshiro/cc-buglist#2128]
Currently you can summon two different bosses at once by having two people that are at different phases of the chain accept the quest at the exact same time. Doesn't work with 2x the same boss, for example having two people that haven't done any RoB quest yet accept the quest at once will not summon the first boss twice, but once. Didn't test if you could summon more than 2 bosses, but I'd assume so. Tested with the Kodo guy (forgot his name, the first in the chain) and the twins.

**Comment by ghost** [comment]
Brokentoe is the clefthoof guy,  not kodo,  please l2p nub

**Comment by Liesara** [comment]
._. teach me senpai
