### ISSUE TITLE
The Path of Defense

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2138]
Singed Scales in warrior class quest [http://wowwiki.wikia.com/wiki/Quest:Path_of_Defense] seem to have very low drop rate: I cleared the entire Thunder Ridge twice without getting all five and having levelled several Horde warriors, I don't recall ever going through such trouble (there's no mention of particularly low drop rates in Wowhead either). Considering it's one of those quests with involved mobs regularly killed by players without the quest, I'd imagine the drop rate is screwed up.

**Comment by ccnim** [comment]
http://www.wowhead.com/item=6486/singed-scale

The first comment there seems to suggest it was pretty bad

**Comment by KimmoKM** [comment]
Huh, I didn't realize to check Wowhead comments for the item itself. I suppose it might be in the correct league after all, I'm closing this issue.
