### ISSUE TITLE
Hellfire Peninsula weird pathing behavior in cave

### ISSUE THREAD

**Issue by geekodot** [ccshiro/cc-buglist#214]
A "Stonescythe Alpha" in The Great Fissure with Blacktalon the Savage walked through the roof of the cave during his patrolling back and forth. This behavior seemed to occur whenever he walked into a certain spot. I am referring to the mob that is the farthest into the cave. Coordinates are 33,64. He did come down again after a short bit.

**Comment by rylaiii** [comment]
same issue as - https://github.com/ccshiro/cc-buglist/issues/92
