### ISSUE TITLE
Arena points penalty formula

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2141]
Pre 2.2.0: [5v5] = 1.0, [3v3] = 0.8, [2v2] = 0.7
Post 2.2.0: [5v5] = 1.0, [3v3] = 0.88, [2v2] = 0.76

Pre 2.2.0 proof: http://i.imgur.com/9O7dnNJ.png
Post 2.2.0 proof: https://web.archive.org/web/20071022051318/http://www.wowarmory.com/arena-calculator.xml

http://wowwiki.wikia.com/wiki/Patch_2.2.0

This should be changed to make PvP properly match the pre-nerfed PvE content.

EDIT: Values seem to have been changed a few more times even prior to the "pre 2.2.0" one:
http://wow.gamepedia.com/index.php?title=Arena_point&oldid=504133
&
http://wow.gamepedia.com/index.php?title=Arena_point&oldid=670669 
more info about the changes.

Seems like you got quite a lot more from 5v5 until somewhere in May 2007

**Comment by Klimpb** [comment]
One might also suggest something "non-blizzlike", like lowering the 2v2 value even more to encourage 3v3 & 5v5. But perhaps that's too crazy.

**Comment by Klimpb** [comment]
Then again people were able to obtain much higher rating on retail because of the amount of players.. But who knows, maybe it'll be the case on Corecraft too.

**Comment by Evolvee** [comment]
Imo there will be a lot of 1490-1700 ppl(PVP items are better than starting PVE items into PVE) but only few 2.2k+ so 30 min ques +0 -30 inc ...like on any other private server... the biggest problem is always amount of those 1800-2k cuz they give the "higher" players the rating they need and get it from lows.. But from my experience its always extremely separated(only 1490 and 2.1k+ players , nothing between it)

**Comment by Klimpb** [comment]
Gonna close this since it is most likely a non-issue since people will not be able to obtain as high rating as on retail which will even things out.
