### ISSUE TITLE
Melee attacks through LoS

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2143]
It is possible to melee hit through the wall even if you dont directly see the enemy... 
http://i.imgur.com/sNrMwKQ.jpg
LoS check for spell casts is fine, but melee missing... This can lead into situation where rogue with cripling poison on weapon slows you when you run around los(nagrand pillar)...

i got some possible solutions to this (adding a check for melee hits,vmaps) but i am not sure which is blizzlike...
1)  This will delay the AA if the target is behind LoS, but it refresh whole melee swing time.

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index db882c6..9e7c56b 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -2232,6 +2232,9 @@ void Unit::AttackerStateUpdate (Unit *pVictim, WeaponAttackType attType, bool ex
if (!pVictim->isAlive())
return;
- if ((attType == BASE_ATTACK || attType == OFF_ATTACK) && !IsWithinLOSInMap(pVictim))
- return;
  +
  CombatStart(pVictim);
  RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_MELEE_ATTACK);

2) This will delay the AA every 100 ms until you reach your target. (so you wont miss 3.8 seconds as warrior for melee swing) (same as error "out of range")

---

src/game/Entities/Player/Player.cpp | 4 ++--
1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/game/Entities/Player/Player.cpp b/src/game/Entities/Player/Player.cpp
index 183876a..6dc15ec 100644
--- a/src/game/Entities/Player/Player.cpp
+++ b/src/game/Entities/Player/Player.cpp
@@ -1113,7 +1113,7 @@ void Player::Update(uint32 p_time)

if (isAttackReady(BASE_ATTACK))
{
- if (!IsWithinMeleeRange(pVictim))
- if (!IsWithinMeleeRange(pVictim) || !IsWithinLOSInMap(pVictim))
  {
  setAttackTimer(BASE_ATTACK,100);
  if (m_swingErrorMsg != 1) // send single time (client auto repeat)
  @@ -1150,7 +1150,7 @@ void Player::Update(uint32 p_time)

if (haveOffhandWeapon() && isAttackReady(OFF_ATTACK))
{
- if (!IsWithinMeleeRange(pVictim))
- if (!IsWithinMeleeRange(pVictim) || !IsWithinLOSInMap(pVictim))
  setAttackTimer(OFF_ATTACK,100);
  else if (!HasInArc(2*M_PI/3, pVictim))
  setAttackTimer(OFF_ATTACK,100);
  --

**Comment by ccnim** [comment]
This is how it should work.
