### ISSUE TITLE
Guards attacking attack dummies

### ISSUE THREAD

**Issue by KMKM2696** [ccshiro/cc-buglist#2147]
http://imgur.com/poZpGn8

**Comment by KMKM2696** [comment]
Only happened after a while of that shadow priest doing a dps rotation on this attack dummy. Seconds later the guard runs upto it and starts attacking.

**Comment by Evolvee** [comment]
They also allows you to get weapon skills on them, but I think they wont be spawned on live server anyway...

**Comment by ccshiro** [comment]
Those test dummies are not a thing in TBC, they're just there to make the testing easier.
