### ISSUE TITLE
Felhunter resisted Devour Magic on enemy, did not put me in combat.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#215]
Felhunter resisted Devour Magic on enemy, did not put me in combat, it should... I think
![bug2low](https://cloud.githubusercontent.com/assets/9938017/5793481/1c1e1af4-9f45-11e4-83b3-3164360c01a1.gif)

**Comment by Gehenas** [comment]
- Pre-MoP -Resist- description on wowwiki:
  "Full resists completely negated the effect and had the same effect as Immune"
- and the corresponding qoute about -Immune- :
  "When immune to a spell or ability, a player will not be affected by neither its damage nor any secondary effect triggered by it"

If I understand it correctly, fully resisting a spell means it won't trigger combat, or anything else.

**Comment by Klimpb** [comment]
Hmm Gehenas, you might be right.. The only thing I was basing it on was my memory and the fact that when you resist the first spell you cast on a mob, he will still aggro.

**Comment by Klimpb** [comment]
This report is most likely invalid.

Proof: http://webmup.com/Bt5RD/ (mage casted pet nova and it resisted, did not put the warlock in combat.. Not sure if it could have put ONLY the mage in combat, seems unlikely.)

Edit: now that I look at it.. Since the warlock casted spell lock with the felhunter at about the same time it makes it quite a bad example, I still believe this report is invalid though.
