### ISSUE TITLE
Holy Light Down Scale

### ISSUE THREAD

**Issue by jamesdes18** [ccshiro/cc-buglist#2153]
Rank 1 and rank 2 of holy light do not scale hardly at all with +healing gear, and only heal for the just slightly over the amount according to their tool tips. Other ranks of holy light don't scale enough such as rank 7 flash of light has the same healing amount on the spell tool tip as rank 5 holy light does but for some reason heal for the same no matter your bonus to healing. Which is wrong because the casts times are completely different and longer spell casts are suppose to benefit with healing power more. Rank one flash of light is better than a rank 4 Holy light just doesn't make any sense

**Comment by Aprics** [comment]
Downranking penalty exists for that reason.
The lower the level (when you learn it) of the skill you are using is the lower the healing bonus.
Also FoL1 is no way near as strong as HL4. HL4 heals for twice as much as FoL1 for me.
Makes sense that low ranks of HL like 1 or 2 heal very low amounts as they also get penalty for a spell learned under lvl 20.

**Comment by jamesdes18** [comment]
i have 2250 +healing any my holy light rank 5 and max flash of light heal
for in general 1800. But anyways that's interesting because my flash of
light heals for 800 and that's ridiculous efficient on mana

**Comment by Aprics** [comment]
FoL is more mana efficient than HL.
And downranking in particualar.
What I am asking of you is if you think it is a bug or you know it is a bug.
HL 5 does have a way bigger penalty than max FoL which maybe is around the same as the cast time penalty on +Heal. 

downrank = (spell_maxlevel + 6) / playerlevel;
if (downrank > 1) downrank = 1;
if(spell_minlevel  < 20) 
{
  sub20downrank = 1.0 - ((20-spell_minlevel) \* 0.0375);
  if(sub20downrank < 0) sub20downrank = 0;
  downrank = downrank \* sub20downrank;
}

is the downranking calculation for 2.2.0 according to wowiki
http://wowwiki.wikia.com/wiki/Downranking

**Comment by Aprics** [comment]
I calculated it to mak it clear:

Cast Time Coefficient:

 [Cast Time of Spell] / 3.5 = [Coefficient].

http://wow.allakhazam.com/wiki/spell_coefficient_(wow)

=> HL5 has 2.5s cast time therefore 0,714

downranking coefficient =((37+6) / 70)= 0,614

That means HL5 has 0.438*Bonusheal added to the baseheal of your cast

and max FoL has 0,427*Bonusheal added.

Because the coefficiants and the baseheal of both casts are nearly identical it doesnt matter what gear you wear or no gear at all. The heal always seems to heal the same amount.

**Comment by ccshiro** [comment]
This is the effect of downranking spells in TBC. Tried HL rank 1, 2 and 5 and they all scale as intended when downranked.
