### ISSUE TITLE
Bladefist proc overwriting Assassination 4 piece set haste buff

### ISSUE THREAD

**Issue by Skibbli** [ccshiro/cc-buglist#2155]
Currently on the test server if you have the haste buff from stunning a mob from the Assassination armour set 4 piece bonus and The Bladefist procs it replaces the Assassination set buff. If you already have the Bladefist proc buff and stun something you don't get the buff from the armour set. This appears wrong to me and I can't find anywhere online that reports this to be existing behaviour so it looks like it needs correcting.

**Comment by Doppelmoral** [comment]
Tried with DST or other procs / on-use trinkets ? Should all stack

**Comment by Skibbli** [comment]
Just tested with Abacus of Violent Odds and DST and both seem to work fine with Bladefist. Just assassination armour set bonus so far but I can't test any other haste buffs.
