### ISSUE TITLE
Channeled AoEs(blizzard,rain of fire, mass dispel) got higher range than they should have

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2158]
You can cast them few yards behind green circle into red circle..:
http://imgur.com/a/fQbtH

**Comment by Klimpb** [comment]
I feel like I remember this being the case on retail, maybe it still is. If someone has a WoD account I guess they could try it..

Well you see, frostbolt has the same range as Blizzard (36yd). So I tested it out and it seems like the visual range of Blizzard is too short, not too long. I'm not sure if the spell means that 36yd would be the center of the Blizzard(where you hover your mouse and actually cast it, would make most sense imo) or if it is where the very edge of the circle touch 36yds.

Video: https://www.youtube.com/watch?v=sX_BvPAK0Mo

**Comment by KimmoKM** [comment]
In retail, I couldn't cast Hurricane any further than the green targeting area showed.

**Comment by Klimpb** [comment]
KimmoKM could you try what I tried in the video, any other spell that has the same range as Hurricane?

**Comment by KimmoKM** [comment]
Entangling Roots seems to have the same displayed range (35yd).
![2016-01-04-195857_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/12096412/e10050b6-b31d-11e5-8d88-568b56bb93ca.png)

If the targeting area is inside the mob hitbox, I can't use Hurricane.
![2016-01-04-195917_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/12096425/f74fa06a-b31d-11e5-866d-32a4a36d0873.png)

Indeed, if the green targeting circle was the same size as the red one, there wouldn't be any overlap at all with the hitbox. Instead its edge would be about fifth of the red targeting circle's diameter away from the edge of dummy hitbox. This is the furthest cast I could manage.
![2016-01-04-195920_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/12096446/0f743034-b31e-11e5-9845-97b9a4fc8462.png)

**Comment by Klimpb** [comment]
@KimmoKM Great!

I'd say it's a 1 yard difference, give or take.

Meaning that on Corecraft you're able to cast these type of AoE spells at a +1 yard range.
