### ISSUE TITLE
Fighting flight masters

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2166]
Flight masters seem to work very inconsistently. For example, the flight master involved in an old issue #432, Gorrik, has elite HP and summons wyverns like he should. However, some of the flight masters like [Jarrodenus](http://www.wowhead.com/npc=12577/jarrodenus) in Azshara and [Daelyshia](http://www.wowhead.com/npc=4267/daelyshia) have non-elite values and don't summon minions (comment on Daelyshia specifically mentions she should summon hippogryphs). In addition, while some flight masters are elite, like [Ariena Stormfeather](http://www.wowhead.com/npc=931/ariena-stormfeather) in Lakeshire, they summon incorrect types of minions. For example, Ariena summoned enraged wyverns. I believe all of them should summon the type of mob displayed next to them.

**Comment by Astixium** [comment]
Can confirm that Flightmaster Krill Bitterhue Summons Wyverns. http://i.imgur.com/2njjTR0.jpg

She has correct HP values.
