### ISSUE TITLE
[NPC] ZM - Starving Bog Lord/Giant "Event" from SpawningGlen to QuaggRidge

### ISSUE THREAD

**Issue by plebbb** [ccshiro/cc-buglist#217]
I was pleased to see this event working, however I wasn't sure about the spawning location of the patrol, or the timing itself.  The group of 5 giants spawns somewhere in the center of the Spawning Glen and proceeds to train towards the east eventually ending at the western edge of Quagg Ridge, and subsequently despawning shortly thereafter. 

On retail I remember the pack spawning very close to the eastern edge of the Spawning Glen, and not nearly as often as I saw on Corecraft(which was every few minutes).  The pack then ran across the path to the north of Watcher Leesa'Oh and despawned after some time of arrival at the end of the patrol.

**Comment by ccnim** [comment]
Fixed the timer but the rest was correct.
