### ISSUE TITLE
Trading bug/ Disappearing items

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2170]
You lose items if you get them traded to you and log off instantly after.
We transferred stuff from alts when we noticed items disappearing on the recieving alts.
It only happens  if there are no actions done by the char recieving the items after recieving them.
Engaging in combat or just moving items in your bag makes the items not disappear.

Seems like the server doesn't realise the action of recieving items via trades without any following action and therefore doesn't save them. Only after actions it notices it and saves the change.

Possibly the same issue with mailing items to yourself to transfer stuff.

**Comment by KimmoKM** [comment]
The mail issue #1167

**Comment by Lephidiles** [comment]
And the guildbank cloning of items that usually happens when logging fast in and out transferring stuff back and forth

**Comment by Lephidiles** [comment]
https://github.com/ccshiro/cc-buglist/issues/1969

i think there is one more issue about this as well but cant find it atm

**Comment by ccshiro** [comment]
Fixed this now, thanks to the clear reproduction steps. It's not the same bug as the other ones mentioned, unfortunately.
