### ISSUE TITLE
Broggok event in Blood Furnace

### ISSUE THREAD

**Issue by Gadixsp** [ccshiro/cc-buglist#218]
We found a bug with the event while doing trash and experimented with other results during the fight.

First, we found that AOE near the Fel Orc cages could aggro the Fel Orcs before the boss event was started. We pulled with both Seed of Corruption and Consecration. The Fel Orcs that aggro do damage as normal, but are not targettable and cannot be reset by running out of the room.

Second, after wiping on the (otherwise correctly working) Fel Orcs during the boss event, the packs that had been killed were targettable after reseting. This allowed us to kill the packs without starting the event.

Killing the Fel Orcs without starting the event caused the following packs to release on a timer instead of releasing when the previous pack is killed.

Unfortunately the instance reset before we had a chance to do further experiments.

**Comment by ccshiro** [comment]
@ccnim The event toggles their unit flags once it's been started the first time, but the initial flag state when they're spawned is better set in the DB as it's GUID dependent.
