### ISSUE TITLE
[Enslave Demon] Reth'hedron the Subduer

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2185]
Currently you can enslave him. He is very overpowered, can use AoE shadow bolt and destroy the whole camp, basically anything in seconds. Also has 150k hp. He should be immune to Enslave Demon and Banish, he is not immune to either at the moment

http://www.wowhead.com/npc=22357/rethhedron-the-subduer#comments

**Comment by Klimpb** [comment]
Video of a lock trying to enslave a Doomguard https://www.youtube.com/watch?v=DYfNcJMkjQc

Seems to be very random, sometimes it breaks just after a few seconds, sometimes it lasts minutes.
