### ISSUE TITLE
Boglash (level 61 elite) should be immune to fear, all snare etc.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#219]
Boglash should be immune to (according to wowhead comments):
"He is immune to chill and frost nova"
"Also immune to fear."
"He is immune to poison and to blind."
"Immune to all snare. e.g. Concussive Shot, Chill, etc."
"Soloed as a 62 mutilate rogue. He is immune to poisons, but not to stuns/gouge as mentioned earlier. Just used gouge/ks whenever they are up. I only used a lvl 45 pot."

He is not immune to fear on Corecraft
![](http://i.gyazo.com/c89ed0f50f7b8bcc98a9bacb016bdb8c.png)

**Comment by ghost** [comment]
I feared him this test,was not immune to it. Warlock fear that is.
