### ISSUE TITLE
Kuma <Hippogryph Master> @ Temple of Telhamat 25.2, 37.2

### ISSUE THREAD

**Issue by Astixium** [ccshiro/cc-buglist#2190]
[Kuma <Hippogryph Master>](http://wow.magelo.com/en/npc/18785) @ Temple of Telhamat 25.2, 37.2

His health is really low, as shown below he should have around 10k (old databases suggest 10.572), but atm it's around [835 hp](http://i.imgur.com/idj9ax0.png).

**Links to Kumas old stats** (Thanks rot)
http://wow.somepage.com/npc/18785
http://wow.magelo.com/en/npc/18785

Screenshot of killing him with less than 1350 damage, multiple times. http://i.imgur.com/phnTQd9.jpg

He also doesn't spawn any gryphons or whatever to aid him, no matter if he got one shotted or not.

**Comment by KimmoKM** [comment]
#2166 

A lot of flight masters have incorrect values right now, at least in Azeroth
