### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by gmurr30** [ccshiro/cc-buglist#2191]
Th use of the boat connecting armen vale and auberdine will cause players to fall fall the surface of it during loading screen(Its does not do the usually going out before the loading screen rather just do the loading screen while still docked.). IT will also cause you to be located in Stone Talon mountains by the map. Actual location is impossible to determine due to graphics outside the boat being invisible. Auto unstuck feature was used to get out. This was repeated with the same effect except this time the boat reach aburdine after once again repeating the above effect.

This was done on a 70 Female Draenei Paladin with riding the Great purple Elekk

**Comment by KimmoKM** [comment]
Some possibly related issues

#1845 
#1277
#1000 
#262 
#114
