### ISSUE TITLE
Expedition Point @ Outland // Hellfire Peninsula.

### ISSUE THREAD

**Issue by Astixium** [ccshiro/cc-buglist#2192]
All of the important NPCs at Expedition Point have way less health than intended. most of them should have around 50k hp (correct values on the links) but atm they have around 6k hp (screenshots)

**Forward Commander Kingston:** 
_Location:_ 71.2, 62.6
_ID Number:_ [npc=19310]
[Wowhead](http://www.wowhead.com/npc=19310/forward-commander-kingston), [Magelo](http://wow.magelo.com/en/npc/19310/Forward-Commander-Kingston) // http://i.imgur.com/T3p7Anw.jpg

**Supply Officer Shandria <General Goods & Repairs>:** 
_Location:_ 70.8, 63.2
_ID Number:_ [npc=19314]
[Wowhead](http://www.wowhead.com/npc=19314/supply-officer-shandria), [Megalo](http://wow.magelo.com/en/npc/19314/Supply-Officer-Shandria) // http://i.imgur.com/FqaPe8a.png

**Corporal Ironridge:** 
_Location:_ 70.8, 63.4
_ID Number:_ [npc=21133]
[Wowhead](http://www.wowhead.com/npc=21133/corporal-ironridge), [Magelo](http://wow.magelo.com/en/npc/21133/Corporal-Ironridge) // http://i.imgur.com/DkGLwTU.png

**Field Marshal Rohamus:** 
_Location:_ 70.8, 63.2
_ID Number:_ [npc=19316]
[Wowhead](http://www.wowhead.com/npc=19316/field-marshal-rohamus), [Magelo](http://wow.magelo.com/en/npc/19316/Field-Marshal-Rohamus) // http://prntscr.com/9rlrua
**Note:** _I'm also pretty sure that i shouldn't be able to see his speech._ http://i.imgur.com/oZonGlE.jpg

**Wing Commander Dabir'ee:** 
_Location:_ 71.4, 62.4
_ID Number:_ [npc=19409]
[Wowhead](http://www.wowhead.com/npc=19409/wing-commander-dabiree), [Magelo](http://wow.magelo.com/en/npc/19409/Wing-Commander-Dabir'ee) // http://i.imgur.com/lH2u7Su.jpg

**Comment by ChazyTheBest** [comment]
@Astixium wowhead is not a good source for hp anymore.
@ccshiro you could use [TDB](/TrinityCore/TrinityCore/releases/tag/TDB335.60) as a base to vanilla/tbc content. Their content is pretty blizzlike (100% blizzlike I'd say, they take it all from sniffs) and is almost complete. You could also contribute (if there's something you have but they don't have yet).

**Comment by Astixium** [comment]
@ChazyTheBest Wowhead is there to provide old comments, NPC numbers and exact locations of the NPCs. Magelo is there for the HP.
