### ISSUE TITLE
Primal Blessing set ponus proc - not showing model

### ISSUE THREAD

**Issue by franraknic** [ccshiro/cc-buglist#2193]
The ZG fist weapons Thekal's Grasp & Arlokk's Grasp form a set bonus proc that amongst other things gives a player a tiger-like model. The issue is that after the proc I get no model (just a gray spot on the ground), after the proc fades I still don't have a model.
Tested on Troll shaman

**Comment by Aprics** [comment]
tested it and had no issue.

troll shaman
belf hunter
troll rogue

probably client sided or some other issue please test it again and record it

**Comment by franraknic** [comment]
Deleted WTF now works on all resolutions.
Looks like it was client sided!
