### ISSUE TITLE
[Dungeon]  Ambassador Hellmaw

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2196]
When he was freed from his banish he had no movement animation at all.
He simply blinked every 1-2 seconds to a new place on his path.
After engaging this behavious stayed the same and he blinked instantly to a person that losed his fear.

After wiping he reseted and worked normally.

**Comment by Aprics** [comment]
http://www.twitch.tv/gobinizar21/v/37204655?t=33m00s
it shows his movement here
- lesser important visual bug
  the channel of the mobs around the banish pillars is not working.
  only the last two pillars are sending a beam to Ambassador Hellmaw.

**Comment by KimmoKM** [comment]
#1722 has the channelling visual issue
