### ISSUE TITLE
Shapeshift cancelled on collection

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#22]
Report:
"There is a bug with druids and collecting quest items on the ground. If you are shapeshifted it will automatically force you into the human form. I was in cat form and i was looting [Etherlithium Matrix Crystal]  for the quest  [You're Hired!]  in netherstorm (one of the first quests you get in are 52) and it switched to human form."

Note: We have no idea either way. But it felt like the kind of report that needs a bit of meat on its bone before it's fixed.

**Comment by FurioCC** [comment]
Druid in all forms can use world objects/items with cog cursor without shifting out IF it's levers or similar objects that require just manipulation for example anzu's pillar http://www.youtube.com/watch?v=LjpBsZ9kf9Q&t=4m45s and http://www.youtube.com/watch?v=p107LMj366A&t=1m18s
However if it's considered "container" which says "opening" on castbar at attempt of using it to pickup stuff, then you get "You are in shapeshift form" and nothing happens. You got to shift out - http://www.youtube.com/watch?v=mHpsxUUQwxs&t=3m34s

Mining shifts druid out. Herbing and skinning is possible in all forms.
For flightform skinning/herbing you got to be on the ground or special cursor is grayed out.

**Comment by gmurr30** [comment]
Why shouldn't druid be allowed to collect and interact with all objects in shape shift forms. All other classes can interact with anything in their combat form, so why bother limiting druids for apparent reason.

**Comment by zoofCC** [comment]
Here i found a video recorded in 2007 which shows from the point of view of the self druid, as he casts the use of the quest item for the anzhu event in tree form
https://www.youtube.com/watch?v=p107LMj366A

edit: 22Jul 2008
edit2: i noticed FurioCC has also pointed the same video before me

**Comment by zoofCC** [comment]
A druid collecting items for the quest [The Raven Stones] from 2012:
https://www.youtube.com/watch?v=iY-hP85yfMY

from     http://www.wowhead.com/quest=10988/the-raven-stones:

By Darkmanian (3,016 – 9·35) on 2008/12/19 (Patch 3.0.3)  
You can gather these (like most items) while in flight form. So you just pick a spot in Skettis and shift into caster form to blow the whistle, and shift back to flight immediately after.

By pinktoque on 2008/08/17 (Patch 2.4.3)
If you're in Flight Form and you go to use the whistle you'll automatically shapeshift out.

**Comment by arawnik** [comment]
I read some on the patch notes from tbc considering druid shapesifting and found these:

2.0.3 - Shapeshifted druids will now be able to speak to npcs while shapeshifted.

2.1.0 - Shapeshifting will no longer remove the Rotting Putrescence creature debuff.

2.1.2 - Druids in Swift Flight form can no longer loot herb nodes.

2.3.0 - If you are in a shapeshift form and try to use an ability that may only be used in caster form, you will leave the form and use that ability. This means that you can shift from one form to another in one action. If you don’t have mana to shift form, you will get an error message and remain in your current form. This can be disabled with /console autoUnshift 0

EDIT: data read straight from battle.net patch notes.

Sadly 2.3.0 patch notes didn't specify those items better. But interesting to me was that part of herbing.

**Comment by FurioCC** [comment]
The change 2.1.2 sawyl speaking about was reverted back in 2.2.0. Druid can herb in flying form, but needs to be on a ground level.

**Comment by arawnik** [comment]
I also remembered that it would've been possible towards the end again. yet I cant find this revert on any patch notes, eaven as double checking 2.2.0

**Comment by FurioCC** [comment]
It's in undocumented changes http://www.wowwiki.com/Patch_2.2.0_(undocumented_changes)
"Druids in flight form can now perform herbalism provided they are on the ground"

**Comment by Exacerbate** [comment]
I thought druids could still herb in flight form, provided that they are in range?

**Comment by arawnik** [comment]
Furio's link to undocumented changes tells that, so yes. only from 2.1.2 to 2.2.0 they couldn't.

**Comment by DeeMarie** [comment]
An article from 2007 which mentions that undocumented change:

http://www.gamefaqs.com/pc/534914-world-of-warcraft/faqs/46822

Other than caster and Moonkin form, Druids cannot use potions, elixirs, 
      or trinkets while in a form.  Luckily, due to a recent change, druids
      can speak to NPCs and interact with objects while in forms.

**Comment by ccshiro** [comment]
I went through and tried the various things stated in this thread and they all seem to work as stated by the sources. As such I'll deem this as already working as intended and will close this as invalid. Please PM me on irc if you have any further input on this.
