### ISSUE TITLE
Draw distance in arena is too low

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2204]
Should probably be the same as in Battlegrounds.
https://www.youtube.com/watch?v=i31KcfOPrIc

**Comment by Schaka** [comment]
I remember this being related to grids. I went through this with itslovelol and I think it should be possibly to see players who are in neighbouring grids too. OregonCore did a backport from TC2.

https://bitbucket.org/oregon/oregoncore/commits/all?search=grid

**Comment by ccshiro** [comment]
It's not a range issue, bgs and arenas already have the same visibility range. In other words, you are in range to see the people where you start, however, not until one of the actors move a bit will the server recheck if you can see them. So if you stand still when the gates open you won't see them from across the map, but if you run a bit forward they will appear (they will also remain if you run back to the position you didn't see them at).

**Comment by Klimpb** [comment]
Alright, tested it again and it works fine once you start arena, it just needs to be a certain distance from your last scan positon for the server to do a visibility scan.
