### ISSUE TITLE
[Karazhan] Morose trash chain pull issue.

### ISSUE THREAD

**Issue by Dallal92** [ccshiro/cc-buglist#2208]
While clearing the trash in Morose's room we noticed if you pull the 2 Ghostly Stewards on the far side of the room you will pull the table of Phantom Guests as well. However, if you pull the Phantom Guest table first you will not pull the 2 Ghostly Stewards.

![morose room trash pulls](https://cloud.githubusercontent.com/assets/14064652/12629049/e17be692-c4fa-11e5-93d6-315c874f808e.jpg)

If you look at our video capture (http://www.twitch.tv/sausage_heimer/v/37882245) at 2:35:17 you will see me shoot the closest Ghostly Steward, chain pulling the Phantom Guest table.

At 2:41:17 we pulled the Phantom Guest table first and the Ghostly Stewards did not chain pull.

**Comment by Dallal92** [comment]
Also this does not happen with the other Stewards and Guests on the other side of the room, you can see at 2:28:48 of the video.

**Comment by Aprics** [comment]
We noticed this as well. But is this a bug?
I guess they only pull because of the way they move if you pull them at a different angle.
If you have some videos from retail of this pull it would help a lot.

**Comment by Dallal92** [comment]
Pulling the Stewards at like a 90deg angle might fix it, next fresh Kara we do we will try it. I never remember having to do that in retail though, but memory is not a god source. I will try and find some videos of clearing trash when I get home.

**Comment by ccshiro** [comment]
Tried a few times on retail: https://www.youtube.com/watch?v=0TLoxKsfK2k For some reason the game kept putting me in duskwood, so gave up after only three distinct pulls.

Here are the relevant timestamps:
https://www.youtube.com/watch?v=0TLoxKsfK2k
https://youtu.be/0TLoxKsfK2k?t=139
https://youtu.be/0TLoxKsfK2k?t=289

**Comment by Aprics** [comment]
to sum up shiros videos
from the first attempt we can see they shoudn't chain at that angle (if the behaviour is the same to a lvl 70)
the second showed us that the mobs can chain but under different circumstances. 
the third showed a different angle and mob as in the attempt on CC but they did chain immediatly.

from our experience you can chain even if you pull the table at a different angle.
seems like either the aggro range for the chain is wrong or there is a position/pathfinding issue.
they also don't trigger instantly like they do on retail but with a slight delay

**Comment by Dallal92** [comment]
I hopped on my warrior on retail to try pulling from different locations with Taunt.

http://www.youtube.com/watch?v=OvGOc4Tc-qw&t=0m53s - Pulled {Skull} from the same location I did during the Karazhan stream. Pulled only the two Ghostly Stewards.
http://www.youtube.com/watch?v=OvGOc4Tc-qw&t=2m5s - Pulled {Skull} again at an extreme angle. Did not chain pull.
http://www.youtube.com/watch?v=OvGOc4Tc-qw&t=3m15s - Pulled {Skull] at an more even more extreme angle. Resulting in chain pulling the Phantom Guest table, but seems like only after the {Cross} Ghostly Steward ran very close to a Phantom Guest.
http://www.youtube.com/watch?v=OvGOc4Tc-qw&t=4m30s - Pulled {Cross} at the 'safest' angle you could. Instatly chain pulled the Phantom Guest table.
http://www.youtube.com/watch?v=OvGOc4Tc-qw&t=6m3s - Pulled {Square] at the most 'dangerous' angle you can. Did not chain pull the Ghostly Stewards.
