### ISSUE TITLE
Camera bugs when mage blinks

### ISSUE THREAD

**Issue by Dxerk** [ccshiro/cc-buglist#221]
After playing some arenas and dueling mages. I noticed that every time they blink my camera automatically changes direction and is "following" the mage. 
This seems to happen only when I'm holding down my mouse button. I don't know if it's intended, but it's annoying!

https://www.youtube.com/watch?v=44PcSGNRXl0&feature=youtu.be

**Comment by FurioCC** [comment]
Most likely related to #62

**Comment by ccshiro** [comment]
Duplicate of #62.
