### ISSUE TITLE
General Marcus Jonathan has no emotions :(

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2211]
http://www.wowhead.com/npc=466/general-marcus-jonathan#comments

He should wave or salute you back, if you /salute or /wave him first.

> By Merowlin (16,849 – 11·41·62) on 2006/09/24 (Patch 1.12.0)  
> Random fun:
> Target him and write either /salute or /wave and he will respond :)
> 
>  Also a note, he replies to /wave with the words "Greetings, citizen.", as opposed to the normal guards, who just /wave back.
> 
> If you salute him, he will salute you back. If you wave to him, he will greet you by saying "Greetings, citizen." This can be annoying to other players because if you spam /wave, he will spam his greeting, and NPCs cannot be put on ignore.

http://wow.gamepedia.com/Marcus_Jonathan

> If you saluted him, he would salute you back. If you waved to him, he would greet you by saying "Greetings, citizen".
> In the beta, if you flexed your muscles at him, he would laugh.

Now he doesnt give a shit : http://i.imgur.com/aUkqxi3.jpg
This disrupts my roleplaying experience! :(

**Comment by KimmoKM** [comment]
Related issues #682 #793

**Comment by Evolvee** [comment]
also
http://www.wowhead.com/npc=3836/mountaineer-pebblebitty#comments 
doesnt react
http://www.wowhead.com/npc=3296/orgrimmar-grunt#comments
http://www.wowhead.com/npc=68/stormwind-city-guard#comments
dont react too.. basicly all guards
