### ISSUE TITLE
[Bog Lord] [Fungal giant] throw mushroom

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2222]
When they emote "Bog Lord/Fungal giant throws a mushroom at player x", the Unstable Mushroom spawns but as a NPC that follows you. It should be a stationary Mushroom that has a poison aura that damages all nearby players.

**Comment by ccnim** [comment]
Couldn't reproduce it but I changed something that would possibly prevent this behavior. If the behavior persists you can reopen this issue.
