### ISSUE TITLE
Rogue - Poisons; Cloak of Shadows; Pets attacking in Stealth

### ISSUE THREAD

**Issue by Horrorfever** [ccshiro/cc-buglist#2227]
Alright, a couple of rogue unpleasantries I have noticed in the past two days.

1 - Shiv hit rating, or poisons.
- I may not be able to give an exact ammount, but it seems like thie shiv hit rating/poison apply rating is too low. I doubt the problem is in me considering my 5.5% hit rating + 20 spell pen cloak enchat, it feels like every 3rd Shiv is being resisted, especially the ones on openers straight out of stealth.

2 - Cloak of Shadows
- It doesn't feel like 90% in any way. Come on, 90% is a lot. Once I CoS against an opponent more than half of his spells hit me either way, especially the first one, once again - I am unable to provide actual numbers but I believe testing should reveal that it isn't 90% indeed, I know it doesn't feel like that for sure.

3- Pet's are unstealthing me 24/7
- Briefly, pet stealth detects should be looked in to, on several occassions I have the mage blinded and the water elemental gouged, I vanish (no way the pet casted before hand due of gouge) and I get a waterbolt caste at me the moment gouge fades off. It's surreal.

**Comment by Klimpb** [comment]
1. Never had this issue on my rogue, sounds strange.
2. Most likely spell delay, meaning they've already casted a spell on you but it hasn't been applied to you yet, during this time you cast cloak of shadows, making it not grant any extra resist chance for that spell.
3. https://github.com/ccshiro/cc-buglist/issues/1155

**Comment by Horrorfever** [comment]
1. It is, and it is annoying.
2. Makes sense.
3. So it is true.

Thank you.

**Comment by Liesara** [comment]
I've dueled a lot here as rogue and i haven't noticed your first point at all. When I shiv and my opponent isn't blessing of freedomed they ARE slowed every single time. Except of course I were to forget recoating my weapons. Now poison apply rate just on normal white attacks might be worth a look since I get the feeling crippling drops much too often, but that's probably just me being a pleb.
Second point is indeed most likely spell delay, and third point is indeed true and has been known for a long time. Maybe use search function next time  :)

**Comment by DarkenRal** [comment]
> Most likely spell delay, meaning they've already casted a spell on you but it hasn't been applied to you yet, during this time you cast cloak of shadows, making it not grant any extra resist chance for that spell.

Actually this part is not exactly true. When you use CloS you get short period of complete immunity to all spell effects and spell damage (at least for the whole time of delay between you press CloS and CloS buff afflicts you, maybe even longer). This allows you to "catch" spells without travel time in Immune. You can see it for example here: https://youtu.be/fT_aZfg9AP0?t=410. 

Similar interactions should be with Vanish and roots/snares (or maybe all spells?). For example here: https://youtu.be/eNDdNiOSc58?t=48 you can see that Neilyo used Vanish and got warrior's Piercing Howl (or maybe it was demo shout?) immuned. In this video it's very hard to tell if immune was before Vanish buff or right after, but it definatelly didn't breakes rogue's Vanish.

Dunno how this works on CC but i believe you will be afflicted by "instant" debuffs if your opponent "cast" it a moment later than you use CloS (but before you afflicted by CloS buff).
