### ISSUE TITLE
GCD proc when canceling a spell cast instantly

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2229]
So.. i dont know much about this but what happens is this: You click on a spell and immediately cancel it  by jump or move. Then u get GCD but thats all. It doesnt even cost mana. It might be cuz of latency or something.

https://www.youtube.com/watch?v=-IGlr9WmAWA

**Comment by Klimpb** [comment]
Channeling spells will trigger a GCD regardless if you cancel them instantly, though they should still cost mana, so I guess that's the bug.

**Comment by ccshiro** [comment]
As Sd pointed out, the bug is that sometimes the channel doesn't start even though it's been accepted because you started moving, so mana isn't consumed.
