### ISSUE TITLE
Player view distance in battlegrounds needs to be slightly increased.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#223]
The max distance on Corecraft:
![](http://i.gyazo.com/5a8614f3bea2d6995379d0c00f7ecc6c.png)
Note that I'm standing about 10 yards closer(about 15 diagonally) from where Vurtne was standing in the next picture. When my target took one step to the left(my left) he would disappear. 

The furthest distance that I've managed to find in a retail TBC video:
![](http://i.gyazo.com/dd264973056e673890db28ce3993494e.png)
Red dot is where a player is that he is able to see is(impossible to see in a screenshot, I'll include the video link), blue dot is approximately where I was standing in the previous picture.

Conclusion: The distance is almost perfect, but I'd say it needs to be increased by about 20-25 yards.

Should also note that I am not sure if it's measuring the range from where the camera itself is, or where your player is. For this reason I tried to adjust my zoom to match his.

Video: https://mega.co.nz/#!iV8ywawK!DL6A7UUlELGcV4PiYOsiCmvRT89f6KOjz3qhz1RKxU8

**Comment by ccshiro** [comment]
I put it at 240 yards, using the video you showed me (the one you linked here too). I guess it needs to be a bit higher still, though.

**Comment by testiecc** [comment]
I think it was too low elsewhere too, when we did dungeon my group members disappeared like there was a invisible wall and I think we weren't too separated afterall we run the same direction. It feels clumsy if I can't see whats ahead if there is no obstacles. suddenly something just appears or disappears ?

**Comment by ccshiro** [comment]
Increased BG distance by another 30 yards.
