### ISSUE TITLE
[World][Pathing]Tirisfal Glades

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2232]
while wandering (and maybe,just maybe, trying to solo raid UC) i came across these 2 mobs, they were stuck and stuttering in place, when i killed the hound, the pat went back to normal

![mobpathing uc3](https://cloud.githubusercontent.com/assets/13721369/12762331/f0659b96-c9ee-11e5-9fc5-ac4dc3f60e1e.png)
![mobpathing uc2](https://cloud.githubusercontent.com/assets/13721369/12762333/f06748b0-c9ee-11e5-9ee6-34404b12067a.png)
![mobpathing uc](https://cloud.githubusercontent.com/assets/13721369/12762332/f065abe0-c9ee-11e5-8ebb-932dc82581f2.png)

**Comment by KimmoKM** [comment]
Apparently this issue might be related to the guard AI #1397
