### ISSUE TITLE
Netherstorm - Gan'arg Engineer

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#2241]
[Gan'arg Engineers](http://www.wowhead.com/npc=16948) stand in one place after they throw their dynamites until their target gets in melee range.

![wowscrnshot_020316_202550](https://cloud.githubusercontent.com/assets/9568075/12794263/85fe35bc-cab4-11e5-8648-b0b5c5f771e3.jpg)

**Comment by ccnim** [comment]
Toggling on and off behavioralAI seems to be the cause.
