### ISSUE TITLE
Netherstorm - Hound of Culuthas

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#2242]
The [Double Breath](http://www.wowhead.com/spell=36406/double-breath) ability cast by the [Hounds of Culuthas](http://www.wowhead.com/npc=20141/hound-of-culuthas#abilities) do less damage than it should. At around 1:15 on [this](https://www.youtube.com/watch?v=jV9H38oZaiM) 8 year video you can see it hitting for around 220 instead of 130.

**Comment by ccnim** [comment]
7978 and the fireball from the defias pillagers also have this issue

**Comment by Canderous** [comment]
I did not want to open a different issue for this, but the [Wrath Hounds](http://www.wowhead.com/npc=20557/wrath-hound#comments) in Blade's Edge seem to have the same issue. I did not find any proof on this, but the damage of their [Double Breath](http://www.wowhead.com/spell=36406/double-breath) is the same amount that the Hound of Culuthas does currently.

The [Chaos Nova](http://www.wowhead.com/spell=36225/chaos-nova) cast by [Daughter of Destiny](http://www.wowhead.com/npc=18860/daughter-of-destiny#comments) is also interesting. A comment from 2.0.1 states "They cast Chaos Nova wich made about 900 dmg and it gave me also DoT that did damage about 90 per tick (4 ticks) to me."
