### ISSUE TITLE
Corrupted Mottled Boar too corrupted

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2254]
Please help this mottled boar that's next to the zeppelin tower outside Orgrimmar (at 50.2, 12.9)!

![corrupted beyond belief](https://fat.gfycat.com/AcidicRashKingbird.gif)

```
Movement priority queue for Corrupted Mottled Boar:
random (20) -- center loc: (1353.439941, -4616.959961, 26.493700)
```

Edit: Elder boars that can spawn there behave as a proper boar should, but corrupted ones are out of control!

**Comment by Liesara** [comment]
Young Shanghi Cat calm down. Everything will be alright.
