### ISSUE TITLE
Bounding radius of players issue -  melee & charge distance etc

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2256]
On Corecraft: http://i.imgur.com/h4dHCaS.jpg (Charge MinRange)
On retail: http://imgur.com/a/Iqwaz (link updated with better examples)

AoE spells uses P2P range, not the same as charge.

Proof that it was the same or very similar in TBC: https://www.youtube.com/watch?v=eJX6gX4roCU
melee range (7:09)
Charge (1:12)(5:02)
Only checked the first 7 mins, can probably be seen throughout the whole video.

**Comment by DarkenRal** [comment]
@SuddenDeath 
Whether the game should measure everything in one range system? Or some spells range should be measured in diffrent range systems than others? I allways thought everything should be in p2p and wowwiki says the same. But  on your screenshots both melee range and minimal charge range looks very long.

**Comment by Horrorfever** [comment]
So I was right to whine about the short charge.
