### ISSUE TITLE
[Engineering] Frost Grenade and Icy Blasting Primers recipes not available from trainer

### ISSUE THREAD

**Issue by Thorik** [ccshiro/cc-buglist#2257]
Problem:
As the title says the schematics for the frost grenade and ice blasting primers are missing from the Master Engineering Trainers found in Outland. I have checked the trainers in Honor Hold, Telredor and Area 52 and none of them offer their "train me" lists.
Solution: 
Both of the recipes should be trainable at 335 engineering skill from any Master Engineer trainer.
Evidence:
http://wowwiki.wikia.com/wiki/Frost_Grenade 
http://wowwiki.wikia.com/wiki/Icy_Blasting_Primers

**Comment by ccnim** [comment]
Added in patch 2.1
