### ISSUE TITLE
Quest - [You, robot]

### ISSUE THREAD

**Issue by Pinhastest** [ccshiro/cc-buglist#226]
Pet skill: "Smash" http://www.wowhead.com/?spell=34618 , should generate a large amount of threat, but it doesnt... Even with the bug that pet skill dont have CD i wasnt able to have agro on pet once, spamming "Smash".

Now about the elite robot:
Skill "charge" is doing too much damage got hit by ~ 6.8k - This need confirmation, but i did this quest on retail 3 weeks ago and dont remember charge hitting that much

**Comment by FurioCC** [comment]
Referencing my old report just becouse i'm salty http://pastebin.com/HYSZ3qk0
No clue if it was fixed as i completed q and never bothered to recheck.

**Comment by ccnim** [comment]
The pet was unattackable and that's why it appeared as if the smash ability did no threat but in actuality he did no threat at all.

The charge was most likely due to you not having maxed your defense skill. It hit for 1200 around 10 times on a cloth wearer.

**Comment by petaal** [comment]
Scrap reaver keeps following player after resurrect if the player dies fighting Negatron. Steps to reproduce:
1. Start the quest
2. Get Negatron's aggro with taunt or just dont attack with the Scrap reaver
3. Die
4. Walk to corpse and notice the Scrap reaver following while being ghost
5. Resurrect and notice Scrap reaver still following

Logging out fixes this.

![wowscrnshot_110415_164036](https://cloud.githubusercontent.com/assets/11743711/10941627/12ea9f20-8315-11e5-87f9-b20a4151fcf3.jpg)
![wowscrnshot_110415_164228](https://cloud.githubusercontent.com/assets/11743711/10941628/13961486-8315-11e5-889e-9898b4de8ae1.jpg)
