### ISSUE TITLE
Dun Morogh

### ISSUE THREAD

**Issue by LC-LC** [ccshiro/cc-buglist#2272]
Works better than any other server I've seen. Almost no issues, and the Mortar Brigade cutscene was awesome. Nice; am impressed. Here's what I found.

**Comment by LC-LC** [comment]
# Quest Issues
- **Supplies to Tannok** [Correct to: "Thanks for bringing this to me". The "ing" is missing]
- **Tools for Steelgrill** [Beldin Steelgrill refers to women as "lad". Check to see if he should refer to them as "lass" or another feminine noun.]
- **Beer Basted Boar Ribs** [There is an extra "w" in the text; is a typo.]

**Comment by LC-LC** [comment]
# NPC Issue
- **Old Icebeard** [Does not walk a pat. Should pat. ^^]

**Comment by ccnim** [comment]
Old Icebeard has a path, he just idles for a long time.

**Comment by ccnim** [comment]
Fixed the gossip errors
