### ISSUE TITLE
[Hunter] [Dranei] - Heroic Presence on Pets [Query]

### ISSUE THREAD

**Issue by LC-LC** [ccshiro/cc-buglist#2273]
This may or may not be an issue. Feel free to eliminate it if it is not.

Should Heroic Presence (Dranei racial) be active on hunter pets? 

There is conflicting information on our own forum from various users. If this is not already resolved, someone can investigate. I'm not an authority on hunters, so won't research what others can research more effectively.

**Comment by Evolvee** [comment]
apparently it wasnt working on their pets in 2010(or atleast the aura wasnt showing up). in 2012 they noticed it is present on their pets.
http://us.battle.net/wow/en/forum/topic/1020802266
http://forums.wow-petopia.com/viewtopic.php?f=3&t=7019
-- prolly changed in cata
http://www.mmo-champion.com/threads/779826-Heroic-Presence
Here they say the HP isnt working anymore(2010) so it means it probably worked before.

> Didn't they change it on 4.0.1 so the buff only affects yourself?
> And you say that you have checked it so i bet thats the case.

But there is a little problem that the HIT rating u have is also the same hit rating which applies to your pets... which isnt the case in TBC i believe.. this means that even if your racial isnt showing up on your pet, your pet still receives it through your total hit rating...

> As said before, your pet gets 100% of the hit rating you have. If you have 8% hit including heroic presence, your pet will have 8% as well.

**Comment by LC-LC** [comment]
ahh nice. thanks evolvee. For the record, it is showing up as a buff on my pet, so apparently working correctly. ;D

**Comment by ccshiro** [comment]
@LC-LC If you believe the issue to be resolved/invalid you can close it yourself by pressing the close button.

**Comment by ccshiro** [comment]
Closing since no further input was provided.
