### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#2274]
Hello there,

if i'm not mistaken the intention is to introduce progressively (according to patch notes) the features that BC expansion had to offer. If that is correct I've found some issues:

Mail attachments slot: The 1+11 slot features was added in patch 2.3, so we should only be seeing 1 slot per mail;

Guild Vault: same story. Added in patch 2.3 we should not be seeing/using it;

Vendor Discounts: again, the 5/10/15/20% discount feature was added in patch 2.3;

Feel free to invalid this report if these are not issues at all.

**Comment by ccnim** [comment]
The issues are known but client side.
