### ISSUE TITLE
OUTRAGEOUS AND BUGGY MELEE RANGE FEENIX MELEE ADVENTURES NERDRAGE

### ISSUE THREAD

**Issue by Horrorfever** [ccshiro/cc-buglist#2276]
Whenever a melee spell is white ((not red)technically in range) you always get the "Out of range" error upon attempt to use it against your opponent.
- Happens in pursuits  (when moving/running)
- Seems fine (bug not persisting) when idle

This has been "tested" and more-so experienced by a LOT of people that PvP on daily basis in and out of the test server.

If anyone could provide a video that'd be great.

OUTRAGE!!!!

**Comment by Horrorfever** [comment]
Literally this:
https://www.youtube.com/watch?v=YAVZn2A9Xmo

Not CC footage, but literally what's going on.

**Comment by ccnim** [comment]
https://www.youtube.com/watch?v=XgD59lIXfpY&feature=youtu.be&t=85

**Comment by Dusky1** [comment]
Its the same on CC as on the video that Nim posted. Seems like that bug was on retail too. But the question is: is it intententional to bring bugs from retail to CC or its going to be fixed?

**Comment by Horrorfever** [comment]
Even if so existing on retail, you can clearly see that the rogue got a shiv at least.

Sometimes /= Always

PS: Delay/Latency is not part of the game mechanics nor coding, it is actually an un-wanted factor in any gaming community ever.

Blizzard has regional realms, Corecraft doesn't.
RIP people not from the US?

In the end of the day ask yourselves:
Do we want the -perfect- TBC experience or -blizzlike- TBC experience?

If the answer is the second, then this is going to be a pve circle jerk ever since launch and that's about it.

More importantly, if you do plan for the -blizzlike- pve circle jerk experience over the perfect, smooth and bugless one - do please warn us beforehand. I am sure some people woudn't be interested in waisting their time even if so passively to wait for something they won't even play on.

**Comment by Dusky1** [comment]
https://www.youtube.com/watch?v=jj0pvjU7GXg#t=387

This link definitely shows it happened on Blizz servers back then in 2008. Akrios is chasing Neilyo, we can see that Neilyo is in range of Akrios's Shiv (shiv is backlighted in white), we can see that hes spamming that Shiv but it doesnt land on Neilyo until he turns back.

Are we going to experience it on CoreCraft just because it happened on retail ? Well, everyone can agree with me that internet connection was weaker and slower in 2008 and that what happens on that video is called LAG.

**Comment by DarkenRal** [comment]
@Dusky1 
And now look at what happened in reality in this moment https://youtu.be/Ts318qxKaOw?t=99. Also, AFAIK, Akrioss used his self modified client and those big red things under the target - shows approximate melee range (5yd; if your model is in the red circle at least a little = you're in melee range). And as far as i remember this videos was made on PTR and not on the live server.

> Well, everyone can agree with me that internet connection was weaker and slower in 2008 

I have the same 100mbit internet, just like back in 2007. It's not about internet connection.

@Horrorfever 

> PS: Delay/Latency is not part of the game mechanics nor coding, it is actually an un-wanted factor in any gaming community ever.

Delay was implemented by blizzard intentionally to synchronize everythin on server side (to prevent cheating(not sure in this part actually) and make it more equal for those who's playing from France and those who's playin from Greece for example).

edit: Just to clarify it for you. White spell = **on your client side** your target is in range. But it doesn't mean that you're in the range on the server or on the client side of your opponent. Akrioss is just laggin or had a really big latency at that moment.

**Comment by Schaka** [comment]
@DarkenRal keep in mind that this was always a known problem with FAST player movement. But on Corecraft (and Feenix as seen in the first link posted here) it also applies to regular movement. 

The fact is, on retail I have always been able to get my shivs off and never got away from warriors for long while being harmstring'd. On the other hand, on Corecraft it doesn't seem that way. Sometimes you're "literally standing right in the target" and for several seconds on end, can't get anything done.
