### ISSUE TITLE
(Arena) No-Timers on Partner CC

### ISSUE THREAD

**Issue by Horrorfever** [ccshiro/cc-buglist#2277]
Long story short, the duration of your partner's crown control spells/abilities over the enemy does not appear, just the CC itself.

**Comment by ccshiro** [comment]
This is how it was in TBC.

From Wowwiki:

> duration 
>     Number - The full duration of the debuff in seconds; nil if the debuff was not cast by the player. 
> timeLeft 
>     Number - Time until the debuff expires, in seconds; nil if the debuff was not cast by the player. 

See: http://wowwiki.wikia.com/wiki/API_UnitDebuff?oldid=1329456

**Comment by Horrorfever** [comment]
Wowwiki is innacurate.

**Comment by DarkenRal** [comment]
lol at that "Wowwiki is innacurate". In TBC you couldn't see debuff durations if it was casted not by yourself. Just like there were no PvP trinket use detections. That's a fact, just accept it and download some addons like NaturCombat (those got it's own timers, tracks DRs and thus can show you CC durations).

**Comment by Schaka** [comment]
Or just use BuffLib to sync with your partners and Gladdy to guess trinket CD

**Comment by DarkenRal** [comment]
@Schaka 
Isn't Gladdy requires server side support for the trinket CD?

**Comment by Schaka** [comment]
I "fixed" that through TrinketTracker back in 2014. But the recent Gladdy updates I pushed include it:
https://github.com/Schaka/gladdy

**Comment by DarkenRal** [comment]
I see, thx, i'll try it) One more little question: is there a way to make 2 announce types? I mean i like my announcements in SCT, but most of the time i also need announce to the party / raid chat.
