### ISSUE TITLE
Quest - [Dr. Boom!]

### ISSUE THREAD

**Issue by Pinhastest** [ccshiro/cc-buglist#228]
After agro Dr. Boom, he stops summoun mobs - this were working last test

The bomb Dr. Boom trow always hit no mater the distance you are from bomb target area - this need confirmation but i think we can run away from bombs

**Comment by ccnim** [comment]
The issue is in the npc_dr_boom script.

**Comment by ccshiro** [comment]
Looks like the tiny bombs are handled by the DB, they're not in the script.

Also I made a new issue for the other bug you reported (one report per issue, please):
