### ISSUE TITLE
Wizard of Oz

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#2283]
Event doesn't reset properly.

**Comment by Dallal92** [comment]
When we wiped on Oz it didn't reset properly. On the 2nd attempt (when the 1st Oz adds were standing off to the side inactive, but target-able) when the Strawman had the ignite debuff our mage was not able to cast any spell on him while he was disoriented. She didn't notice if an error message popped up, it just would not let her cast any spells on him.
