### ISSUE TITLE
Karazhan Back door and Servant door

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#2286]
Currently not working exactly how they should.

**Comment by Ickler** [comment]
IIRC from when we tested it, it now opens from the "outside" after Curator is dead. The backdoor.

While it SHOULD not be openable from the outside, you must first open it from the inside. Then you can access backdoor. Whether it was after Opera or Curator, I can't recollect.

http://eu.battle.net/wow/en/forum/topic/6133773477#9 Can be seen in this guys explanation.
He seems to think it's a bug. But much like this guy: http://eu.battle.net/wow/en/forum/topic/6133773477#18
I also remembering stealthing to the door, to open it for the rest.

"The raid also featured a back door that allowed you to skip a long trash clear if you desired. However, to unlock the door originally required opening it from the inside, which meant a member of the raid taking one for the team by running through all the mobs."
http://www.engadget.com/2014/01/03/wow-archivist-the-curse-of-karazhan/
