### ISSUE TITLE
Tooltip Bug: Druid buffs which are altered by talents do not display correct stats when applied to a player. [Very Minor]

### ISSUE THREAD

**Issue by RunicFigment** [ccshiro/cc-buglist#2287]
The tooltips for Mark of the Wild (Rank 7) and Thorns (Rank 6) are displayed in the buffs/debuffs as they are without 4/5 Improved Mark of the Wild and 2/3 Brambles respectively, despite correctly altering the stats and displaying correctly when moused over in the action bar and spellbook. It is unknown to the poster whether this applies to other buffs/ranks of said buffs, or if this issue was present in retail. This problem can be reproduced by creating a druid, leveling them to 60, and learning mentioned abilities + talents.

**Comment by ccnim** [comment]
http://www.gamefaqs.com/boards/534914-world-of-warcraft/50529668
