### ISSUE TITLE
[instance][Raid][AQ40] Wrong debuff name vs descripcion -- Mana burn

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2295]
well, as can bee seen, dont think it needs more explanation
![buff mana burn](https://cloud.githubusercontent.com/assets/13721369/12930114/bdc33f30-cf76-11e5-9b8d-2bb34ecf41b9.png)

**Comment by ccnim** [comment]
That's actually the spell. It's a mana burn + aoe death coil.
