### ISSUE TITLE
Cenarion Thicket's strange aura debuff acts like a viral disease

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2312]
1. Put a character inside of Cenarion Thicket and they'll get the debuff.
2. Bring another character close enough to target the first and they'll catch it.

![wowscrnshot_021216_001638](https://cloud.githubusercontent.com/assets/2672633/12999702/fa44ddb0-d11f-11e5-981d-c944d5375958.jpg)
(Shanghi is inside Cenarion Thicket and infecting us all the way at the Shattrath entrance)

It's just a guess, but maybe [this version](http://www.wowhead.com/spell=35956/strange-aura#comments) is being used instead of [this version](http://www.wowhead.com/spell=32407/strange-aura#comments). A comment mentions the first one with ID 35956 is from a quest where a bomb gives it to everyone within range.

**Comment by ccnim** [comment]
32407 needs to be able to apply to self
