### ISSUE TITLE
[H] Shadow Labs Missing Mobs: Cabal Assassin

### ISSUE THREAD

**Issue by Escape243** [ccshiro/cc-buglist#232]
A description of their spawning pattern is on WoWWiki: http://www.wowwiki.com/Shadow_Labyrinth
(ctrl+F: Cabal Assassin)

I'm not sure how accurate that description is, but here's a video of me checking out heroic slabs on retail.

http://www.twitch.tv/nappsleepp/c/5909611

The assassin appears towards the end at like 8 min, throughout the video I make comments on differences I observed.

Short video on normal mode, note only 3 channelers per pillar in normal mode. Not sure if this implemented correctly, have yet to test normal shadow labs.

http://www.twitch.tv/nappsleepp/c/5909854

**Comment by ccnim** [comment]
Needs debugging.
