### ISSUE TITLE
Yell range possibly too low

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2320]
According to [WowWiki](http://wowwiki.wikia.com/wiki/Chat?oldid=1556810), yell should have a 300 yard range. Currently, as soon as someone is out of sight (at about 100 yards I think), you can no longer see their yells.

**Comment by ccshiro** [comment]
Tested it on retail. The distance you should see yell at is 200 yards. (I've got an actual program to measure the exact distance of my party member, so I think wowwiki might've just overestimated the distance they were at).
