### ISSUE TITLE
Vanish bug (unstealthed)

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2324]
If I cast a spell with a travel time onto a rogue that vanishes right before the spell hits him, he doesn't get hit by he spell but also doesnt really vanish.
By that I mean he has the vansish and the spell buff on him but I can still see him and cast more spells as if he was unstealthed.

This only seemed to happen on long distances with both instant and cast time spells.
It happend about 80% of the time he was standing still and not moving.
He sometimes turned invisible later at a random point.
The chance for it to happen was way lower while the rogue was moving.
Also if the effect occured and I could see the stealth buff on him, the time it took for him actually going invisible was way slower compared to standing still.

I guess the rogue should be unstealthed if he vanishes the spell too late but should lose his vanish and stealth buff.
At the moment he still has the chance too flee if he moves away fast enough without getting another cast on him.

tl:dr 
rogue vanishes too late 
cast doesnt effect him
he stays in target
has vanish and stealth as buff
can go invis by moving

**Comment by DarkenRal** [comment]
> I guess the rogue should be unstealthed if he vanishes the spell too late but should lose his vanish and stealth buff.

Any spell with travel time can't hit on vanish even if it was used right before it "hits".

**Comment by Aprics** [comment]
@DarkenRal 
It was differently scrippted before though.
Something about half of the travel time.(they corrected it in the video)
So maybe it is bugged because of older scripts still working against newer ones.

**Comment by Horrorfever** [comment]
You are literally descriping vanishing things like blind poly and anything for that matter.

Works as intended.

If you are not careful you can lose your vanish but get the spell on you anyway.

**Comment by DarkenRal** [comment]
No, he's not. Read carefuly:

> If I cast a spell **with a travel time** onto a rogue that vanishes right before the spell hits him, he doesn't get hit by he spell but also doesnt really vanish.

**Comment by ccnim** [comment]
The cause for this is solely dependent on range.

**Comment by ccnim** [comment]
#1165 duplicate?
