### ISSUE TITLE
paladins aura and tier 2

### ISSUE THREAD

**Issue by booltoo** [ccshiro/cc-buglist#2326]
paladins can duplicate any of their auras up to 5 times by equipping 3 pieces of the tier 2 set (any piece) inside an instance

http://imgur.com/KNnsaHs

how to get the bug :
- Be a paladin with any aura on
- Be inside an instance (doesnt work outside)
- Be near a party member, if you are near one, you get 2 auras, if you are near 4, you get 5 auras
- equip and unequip 3 pieces of tier 2 
- you get the same aura 5 times

note: it is not a visual bug

sorry if this bug was already reported

**Comment by Rotbant** [comment]
Tested little more, it actualy gives +1 aura for every party member near you, when you switch 3 piece of t2 paladin gear.
