### ISSUE TITLE
Black Qiraji Resonating Crystal

### ISSUE THREAD

**Issue by botmaster5** [ccshiro/cc-buglist#2332]
(item=21176) when using the item while already mounted on it, the "mounting" cast bar animates, the mount is removed and you are on foot. however you are still "mounted" and can run @ mounted speed. you are unable to cast.

when using the item while in the "bugged" mount state, the mouting animation goes through, but then errors and displays "Interrupted"

the only way to get off the mount is to click the buff off

you are also able to use the Black Qiraji Resonating Crystal while on another mount

**Comment by Evolvee** [comment]
it shouldnt be obtainable anyway

**Comment by FurioCC** [comment]
> it shouldnt be obtainable anyway

Yes, AQ should be open and scepter questline shouldn't reward mount.
Those who want to do it can do it for rewards they get in process.

**Comment by DarkenRal** [comment]
It's actually should be obtainable. it was obtainable on retail in TBC on new opened servers but only on those servers where transfer was closed. Means you had to lvlup you character on that server first. But all new servers with opened transfer had opened AQ gates and thus you couldn't obtain Black Qiraji mount and Scarab Lord title, that's true.

**Comment by FurioCC** [comment]
Yes but this server is starting with opened gates afaik, thus it shouldn't be obtainable.

**Comment by DarkenRal** [comment]
Oh well, that's unfortunate :(
