### ISSUE TITLE
[Botanica] Laj immunities

### ISSUE THREAD

**Issue by Aprics** [ccshiro/cc-buglist#2336]
He was immune to my direct damage spells (fire and shadow) no matter of colour he was in.
He wasn't immune to the dots of the same school of magic but they didn't tick on him.

I can't remember him being immune like this last time but i think it depends on the immunity he starts with.

**Comment by ccshiro** [comment]
Went back and checked the client, he shouldn't become immune to schools, just very resistant. In each form he gains +500 resistance to one school. So, fixed the bug + made it resistance based instead of immunity.
