### ISSUE TITLE
Zaxxis Stalker - teleport and aggro problems

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2342]
1. When out of combat, [Zaxxis Stalkers](http://www.wowhead.com/npc=19642/zaxxis-stalker#comments) should sometimes teleport around the Zaxxis Raider groups in the Heap area. Currently, they do teleport to certain points (sometimes close, sometimes very far, and sometimes to the same place they are at), but then they immediately run back to where they started.
2. The 2 stalkers around [Warp-Raider Nesaad](http://www.wowhead.com/npc=19641/warp-raider-nesaad#comments) probably shouldn't teleport away to leave him unguarded. Also, 3 comments mention that if you pull one of the stalkers at Nesaad, only that one and Nesaad will aggro. Currently, only that stalker will attack.

**Comment by ccnim** [comment]
They definitely shouldn't run back but they will teleport away.
