### ISSUE TITLE
Ability to drink while being on mount.

### ISSUE THREAD

**Issue by KuroiKensai** [ccshiro/cc-buglist#235]
I was able to drink while I was mounted.

**Comment by Pinhastest** [comment]
i remember this bug on other private server, i think it worked with a macro. Dont know if is the same bug KuroiKensai

**Comment by ccnim** [comment]
Need more information. What water, what mount, where were you and so on.

**Comment by Klimpb** [comment]
He probably means he pressed the drink & mount key at the same time, so your character starts to drink while casting the mount and remains drinking while not moving when mounted?

**Comment by ccshiro** [comment]
Tried making a macro, was able to reproduce it with this kind of macro:

```
/use Moonberry Juice
/use Red Skeletal Warhorse
```
