### ISSUE TITLE
Telaar and Garadar Warden NPCs

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#2358]
[Warden Bullrok](http://www.wowhead.com/npc=18407/warden-bullrok#comments) and [Warden Moi'bff Jill](http://www.wowhead.com/npc=18408/warden-moibff-jill#comments) are supposed to be hitting very hard and be the last line of defense in Garadar and Telaar. According to wowhead comments, they should hit for around 3k on 11k armor, and around 4k on cloth.

**Comment by Evolvee** [comment]
i remember that telaar guards almost oneshoted me when i tried to take a shortcut
2.6k-4k per hit into cloth with inner fire + those autoattacks were very fast so u couldnt even get into the middle of bridge and u were down, they also couldnt be feared but im not 100% sure about this part
