### ISSUE TITLE
Quest : Triage [6622] 

### ISSUE THREAD

**Issue by Dusky1** [ccshiro/cc-buglist#2369]
I went to Hammerfall to skill up my First Aid and i cant pick up quest "Triage" from Doctor Gregory Victor. I have 225/225 First Aid Skill. There is a yellow exclamation mark on NPC when I mouseover him, but right-clicking doesnt work.
![wowscrnshot_022016_161027](https://cloud.githubusercontent.com/assets/17127512/13197367/945b3336-d7ec-11e5-88e7-1cdf6265c31c.jpg)

**Comment by ccnim** [comment]
#1138
