### ISSUE TITLE
[Mobs][Minor] Gan'arg Servant stuck in object, Hellfire Peninsula

### ISSUE THREAD

**Issue by Winns** [ccshiro/cc-buglist#237]
Just a minor bug.

[Gan'arg Servan](http://www.wowhead.com/npc=16947/ganarg-servant) stuck in object and can't attack.
http://i.imgur.com/N0oJaTI.jpg

**Comment by KuroiKensai** [comment]
I think this is global bug, not just this one mob. Some problems with geodata.

**Comment by ccshiro** [comment]
Duplicate of #192 most likely.
