### ISSUE TITLE
Sunfury Briefings

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#2373]
The drop rate for both quest items for the quest [Sunfury Briefings](http://www.wowhead.com/quest=10328/sunfury-briefings) is currently very high as it dropped on the first mob for both of the items. I think according to the wowhead comments, it was changed at a later patch to a high drop rate and was originally much lower.

Also, right now, if you are doing it in a group, everyone needs their own briefings dropped, which I'm not sure if it is correct. If the drop rate is lowered, it might be painful to get them for everyone in the group.

**Comment by ccshiro** [comment]
Fixed the drop rate to be lower. The flag that decides whether or not it drops for everyone in the party is mined from the server by mangos developers, and unlikely to be incorrect.
