### ISSUE TITLE
[Spell mechanic][minor] Positioning of Shadowstep

### ISSUE THREAD

**Issue by braide** [ccshiro/cc-buglist#238]
Shadowstep seems to put you ontop of your target in situations it can't put you behind them (like when they are faced towards a wall or cliff). If you are standing on a ledge with your back against the ledge a rogue shadowstepping you is suppose to put him behind you and hence make him fall off the ledge (currently the rogue seems to land at the same position as the target). I'm not sure how it was when shadowstepping someone with the back against a wall. 

http://www.wowwiki.com/Shadowstep here it says "Careful when utilizing this talent near cliffs, especially in Outland. An unlucky rogue might accidentally send himself plummeting.". I think it's worth looking into, though it's a minor detail (which can make quite the difference in arena).

**Comment by KuroiKensai** [comment]
Shadowstep should always put rogue to the back of the target unless it is literally impossible ( like example with wall ). This is main defence strategy when facing SS rogue at arena - to stay near the edge and force him to fall )

**Comment by tedrasiel** [comment]
in arena the rogue isnt falling if theres a wall, only in positions where the rogue can acutally fall down (bridge for example).

**Comment by ccshiro** [comment]
Reimplemented how shadowstep selects its position. It fixes the above mentioned case, but it will need a bit of testing in general now since it might break in other aspects I didn't think of.

**Comment by KuroiKensai** [comment]
Was testing it for a while last test. Seems to be okay.
