### ISSUE TITLE
Vanish Issue

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#2392]
Vanish should deselect your target before the fade.
https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=56

**Comment by DarkenRal** [comment]
No it shouldn't. It's the Stealth part that deselect you. Vanish should not have anythin with that. You can see it in video you linked, 1 moment before your timestamp (0.54). You can see that Neilyo vanished opponents Blind and wasn't even deselected. If it were how you said - it would be impossible to do Vanish-Blind trick (to break vanish and still hit your blind).

edit: dunno what your closed means, probably you already understood it :D

**Comment by ccnim** [comment]
Yeah, seems like this wasn't an issue.
