### ISSUE TITLE
Blackrock Mountain - The Seven boss

### ISSUE THREAD

**Issue by Skibbli** [ccshiro/cc-buglist#2398]
When I entered the room of the Seven the loot chest was already spawned and lootable. When I started the fight Anger'rel aggroed and his portrait was red but I got an error saying I was unable to attack that target.

After vanishing to reset the fight I tabbed out and when I tabbed back in I was dead as the other bosses continued to aggro even though the fight should have reset.

Update about the vanish part - I swam across the lava to get to the emperor and after vanishing to drop lose an add from the lava I kept going into and out of combat. I tabbed out to update this issue and when I tabbed back in Doom'rel had apparently aggroed on me from his room and killed me :(

**Comment by ccnim** [comment]
#403
