### ISSUE TITLE
Swapping weapons should reset swing timer

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#2401]
http://web.archive.org/web/20081109084638/http://elitistjerks.com/f31/t12855-working_theories_theorycrafting_2_1_a/

-- Swapping weapons will reset your swing timer and incur the global cooldown.

Edit: I'm guessing "reset" as in you will have to wait the full swing time duration before being able to attack again? Otherwise it wouldn't really make sense

**Comment by Ickler** [comment]
I think it only stops your attacks where they are, and give you the .5 sec or whatever it is initial wait time for attack. 

Say you're .1 sec from a hit firing, then you swap wep and you skip that hit + have to wait .5 sec extra for a swing. That's pretty major.

**Comment by Klimpb** [comment]
Tested it on retail: https://www.youtube.com/watch?v=4ry46KtQX_w

Seem to reset the swing timer to 0, meaning if you keep switching weapons within a time that is less than the swing time of the weapon, you will never hit the target.

Edit: resets swing timer on all weapons equipped when switching any of them.
https://youtu.be/muu1phcyNg0

**Comment by Klimpb** [comment]
https://www.youtube.com/watch?v=K_Zezh1Diy8
Not working properly, this now lets you attack once every ~2 sec with a 3.7 & 3.6 speed weapons if you time your weapon switches.

**Comment by Peonstomperx** [comment]
@SuddenDeath What about swapping thrown/bow?

**Comment by ccshiro** [comment]
@SuddenDeath weird stuff. Will take a look what might've gone wrong in the patch.

**Comment by ccshiro** [comment]
Fixed what was wrong.
