### ISSUE TITLE
Viper Sting

### ISSUE THREAD

**Issue by Dusky1** [ccshiro/cc-buglist#2405]
Hunter doesnt get the mana drained with Viper Sting. The mana is only burned

**Comment by ohfug** [comment]
it didn't give mana back until WoTLK

copy and pasted from nost forums

http://www.wowwiki.com/Drain

List of Mana Drain Spells:

Mana transfers (removed mana given to player)
-Drain Mana

Mana burns (removed mana converted to damage)
-Mana Burn

Pure mana drains (mana is lost)
-Viper Sting

# 

Also, see "The complete history of hunter stings" on YouTube.

http://youtu.be/qaKUhhSrfa8

@ 3:07 - Viper sting only gave mana in Wrath; before it just drained it.

# 

Additionally, from old wowwiki (TBC).

http://www.wowwiki.com/Viper_Sting?oldid=1344317

"Although the game description says "Drain", it does not transfer mana to the caster."

# 

Finally, a PvP video from retail Nov 2006. From 4:11-4:19, a hunter uses viper sting on a mage and gains 0 mana despite a full 8 second duration. Note the combat log during viper sting.
