### ISSUE TITLE
Armor debuffs

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#2407]
http://www.tankhard.com/2008/06/18/curse-of-recklessness-mechanics/

Seems like sunder armor, CoR and FF might stack.

http://www.warcrafthuntersunion.com/2009/05/list-of-what-raid-buffs-stack-and-do-not-stack/

**Comment by Ickler** [comment]
Yeah Sunder Armor, CoR and Fearie Fire should all definitely stack. You can find this in other EJ posts about boss armor, as well as on rogue / warr EJ threads.

http://web.archive.org/web/20071202181137/http://elitistjerks.com/498690-post35.html
http://web.archive.org/web/20081222181901/http://elitistjerks.com/f81/t22705-dps_compendium/

**Comment by ohfug** [comment]
Armor Debuff (Major):

```
Acid Spit (exotic Hunter pet)
Expose Armor (rogue)
Sunder Armor (warrior)
```

Armor Debuff (Minor)

```
Faerie Fire (druid)
Sting (Hunter pet)
Curse of Recklessness (warlock)
```

Sunder stacks with faerie fire and CoR, but faerie fire and CoR do not stack with each other.
