### ISSUE TITLE
[Hunter] Aspect of the Viper does not increase regen

### ISSUE THREAD

**Issue by TheVcelar** [ccshiro/cc-buglist#2414]
As the title says, this spell now does not increase mp5 ... with or without it, mana regen is always the same, no matter how much actual mana hunter has.

**Comment by ccshiro** [comment]
Works fine. The effect is just not showed in your character pane. The effect is quite obvious when looking at the mana you're gaining though. Given it scales with your current mana and the actual mp5 it gives you keep changing I don't think it's likely it ever showed up in your character pane.
