### ISSUE TITLE
Polymorph npc on mount

### ISSUE THREAD

**Issue by Oops73** [ccshiro/cc-buglist#242]
I tried to sheep a npc. however the npc didn't unmount.

As seen in the screenshot the bloodward is sheep on top of the mount!

**Comment by Oops73** [comment]
The screenshot didn't work i will give a link instead!
http://i.imgur.com/jkOa41c.jpg

**Comment by Bearmanpig** [comment]
I hope this is not a bug, this looks hilarious!

**Comment by ghost** [comment]
it's bug :)
