### ISSUE TITLE
Deadwind Pass - Karazhan attunement quest mobs

### ISSUE THREAD

**Issue by Canderous** [ccshiro/cc-buglist#2421]
1) [Wailing Spectres](http://www.wowhead.com/npc=12377/wailing-spectre#comments) are not casting [Cry of the Dead](http://www.wowhead.com/spell=32938/cry-of-the-dead).

2) [Damned Souls](http://www.wowhead.com/npc=12378/damned-soul#comments) should do much higher damage with their spells according to wowhead comments.

3) The melee damage done by the mobs seemed to be too little. [Unliving Caretakers](http://www.wowhead.com/npc=12379/unliving-caretaker#comments) and [Unliving Residents](http://www.wowhead.com/npc=12380/unliving-resident) definitely do much lower damage than they should. [Damned Souls](http://www.wowhead.com/npc=12378/damned-soul#comments) also do very little damage, but they are casters. [Restless Shades](http://www.wowhead.com/npc=7370/restless-shade#comments) and [Wailing Spectres](http://www.wowhead.com/npc=12377/wailing-spectre#abilities) seemed fine, but they might be doing less damage as well.

4) The loot tables are mixed with the vanilla loot tables. For example, [Unliving Residents](http://www.wowhead.com/npc=12380/unliving-resident#comments) were dropping both Runecloth, level 58 greens and Netherweave Cloth as well. The rest of the mobs might also have mixed loot tables.

5) I am unsure of this one, but [Unliving Residents](http://www.wowhead.com/npc=12380/unliving-resident#comments) seemed to have their vanilla hp amount instead of their TBC hp amount.

6) I am also not certain of this one, but I got 2 blue (vanilla) items while only doing the quests (and also stealth-skipping a lot of the mobs). The drop rate for blues might be too high or it might be related to the vanilla loot tables.

**Comment by ccnim** [comment]
Only the loot issue left which is due to the mobs being in vanilla.
