### ISSUE TITLE
Reth'hedron the Subduer doesn't use spells

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2426]
[Reth'hedron the Subduer](http://www.wowhead.com/npc=22357/rethhedron-the-subduer#abilities) currently only uses melee attacks.

https://www.youtube.com/watch?v=j9X75cZUD5U#t=30s shows him using shadow bolt and cripple.

**Comment by ccnim** [comment]
His spells seems to have been added in 2.1 when he became part of a quest line.
