### ISSUE TITLE
[Hunter] Snake Trap

### ISSUE THREAD

**Issue by Barroth** [ccshiro/cc-buglist#243]
The snakes only apply the posion to their main target, but they should target other unpoisoned targets within 8 yard range aswell.

"Snakes apply poisons with spit, not a melee attack (about 8 foot range). Also, if there are unpoisoned targets nearby, snakes will not melee, but will instead spit more poisons on that target, making snakes an excellent AoE boost"

http://www.wowwiki.com/Snake_Trap?oldid=1511307

**Comment by ccshiro** [comment]
@ccnim should be fixable in the DB me thinks.

**Comment by ccnim** [comment]
https://www.youtube.com/watch?v=60To4LaFt90 snakes apply mind-numbing poison to non-mana targets.

**Comment by Summoning01** [comment]
Snakes still aren't applying poisons to all nearby (non-poisoned) enemies, only to the closest one upon trap release. [snake_trap.mp4](https://www.youtube.com/watch?v=xWk-QXJfsPo)

> I mainly use the trap in AOE situations where the crippling poison delays mobs heading for the AOE'ers, and because I like seeing 10+ mobs turn green. [source](http://wow.allakhazam.com/forum.html?forum=243&mid=1171030346246825006)
