### ISSUE TITLE
Target Dummies immune to Siphon Life and Drain Life

### ISSUE THREAD

**Issue by ohfug** [ccshiro/cc-buglist#2433]
Not a big deal but it makes trying to test affliction kinda annoying.

**Comment by Chulain** [comment]
try sending your pet at em (i didn't test it on cc but it worked on some other server if i remember right)

**Comment by ohfug** [comment]
tried, still immune

**Comment by Schaka** [comment]
Target dummies were never actually in the game, with the exception of those "target dummies" in Theramore.

**Comment by ccshiro** [comment]
Yeah, they're a test server only thing. Removed the drain immunity anyway.
