### ISSUE TITLE
Trying to trade with someone that can't see you won't show the trade windows

### ISSUE THREAD

**Issue by Shanghi** [ccshiro/cc-buglist#2442]
1. Use prowl or stealth.
2. Sneak up on someone and don't let them see you.
3. Try to open a trade window with them.

You'll now both be trading, but the trade windows won't be shown. You can force them to be shown with `/run TradeFrame:Show()` and can complete the trade (with minor visual bugs since it didn't open properly) to verify that you're really trading. You could also walk far enough away or use `/run CloseTrade()` to force the trade to be canceled instead.

**Comment by ccshiro** [comment]
@Shanghi and I tried what happens if one of us was looking at the auction house per @Shanghi's idea. Same bug there.

Also, for mailboxes.

And for the "Block Trades" option.
