### ISSUE TITLE
[Shaman]Healing Way stacks from multiple shamans

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#245]
As title says, Healing Way talent buff stacks without limits. 4 shamans can keep the buff up on same target and healing waves are healing for 7k non crits.

**Comment by Winns** [comment]
How it should work [WoWWiki](http://www.wowwiki.com/Healing_Way?oldid=1666065).

**Comment by ghost** [comment]
gamebreaking bug, shamans are already OP, thinks makes them incredibly mana efficient.
