### ISSUE TITLE
Mind Vision

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#2459]
If I Mind Vision a target and that target moves out of my update range it will stop moving at that limit.
trying to jump the spell will cause a Interrupt if the new target is out of view range

when the target moves back in range it works fine

Note if target mounts it moves a bit more (like 3 or 4 yrds)

**Comment by Liesara** [comment]
https://github.com/ccshiro/cc-buglist/issues/1476

Range is currently normal vision range, not unlimited as the tooltip states and as it should be.
