### ISSUE TITLE
UC to Grom´Gol zepelin NPCs

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2462]
When you are about to leave the arena(zepelin starts moving), the npcs are grayed out 80%,60%,50%,20%, then they dissapear and u have to move with camera/character to see them again, but they dissapear again in a sec.

movement started: http://i.imgur.com/jOjOuha.jpg
npcs visible again: http://i.imgur.com/GYJcCQK.jpg

**Comment by Klimpb** [comment]
#114 
Duplicate I guess.
