### ISSUE TITLE
vanish after prep

### ISSUE THREAD

**Issue by teddys** [ccshiro/cc-buglist#2467]
vanish after preparation does not put you to stealth, you only get "vanish" buff

repro : vanish --> cancel stealth and vanish --> prep --> vanish --> notice you are not in stealth

**Comment by Dusky1** [comment]
Tested it a bit longer and it seems to be connected to #2468

**Comment by Dusky1** [comment]
tested it again and now it looks like you dont get stealth when u vanish after casting Garrote :O i know it sounds strange but test it :  Cast garrote and than cast Vanish.
