### ISSUE TITLE
[Racial] Mana Tap

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#249]
On CoreCraft, Mana Tap transfers mana from the target, decreasing the enemy's resource and increasing the caster's. It reads, however, "Reduces target's mana by X and charges you with Arcane energy for 10 min. This effect stacks up to 3 times." (http://wow.gamepedia.com/Mana_Tap).

This issue was first addressed by Hellground on September 27, 2014 (https://hellground.net/changelog/hellground-core/8).

I made a post there in November (http://forum.hellground.net/topic/45010-blood-elf-mana-tap-no-longer-transfers-mana/).

You know what, they may be right. But it needs further research. I did not experience it in TBC first-hand.

**Comment by Adunai** [comment]
Screenshot from CoreCraft (http://i.imgur.com/DF3ip5X.jpg).
Also, it works right, it's a magic buff but it can't be removed with the right-click (on Excalibur you can, I think, it's wrong, and you got it right).

**Comment by Danddelion** [comment]
So currently the issue with this is that if you use only Mana Tap you also gain some mana which you would normally gain only after using Arcane Torrent (http://www.wowwiki.com/Arcane_Torrent?oldid=1468718) after using Mana Tap (http://www.wowwiki.com/Mana_Tap?oldid=1422861), do I understand it correctly?

**Comment by Adunai** [comment]
@Danddelion Absolutely right.

**Comment by ghost** [comment]
Yes, the correct behaviour is for mana tap to give charges, and then the player has to use Arcane Torrent to get the resource depending on how many charges have been accumulated. 

Mana tap itself should not give a resource to the caster.

**Comment by ccshiro** [comment]
Decided to look for some proof. Here are a collection of stuff I found:

https://www.youtube.com/watch?v=arTztUW2pok#t=95 at 1 min 35 secs: This one is strange, he neither gains mana by the tap, nor does the target lose any.
https://www.youtube.com/watch?v=TngyVZB2qIE#t=42 at 42 secs: In this one the target loses mana, but the caster gains none.
https://www.youtube.com/watch?v=FJXdXvLh4LM#t=30 at 30 secs: In this one target loses again, but caster gains none.

With that I think the evidence is compelling and it's indeed a bug.

**Comment by ghost** [comment]
why close?

in none of the videos you linked it's obious that the target does _not_ lose mana
also, the caster gaining mana is w r o n g, which is why you cant see that behaviour in TBC videos; however, on CC the caster gains mana which is a bug

did you just mean that you have fixed the issue?

**Comment by ccnim** [comment]
That's indeed what he meant.
