### ISSUE TITLE
<Bandits!> quest can't be accepted (already on that quest prompt unexpected)

### ISSUE THREAD

**Issue by chaddy13qc** [ccshiro/cc-buglist#2491]
In Azuremyst Isle, after killing a Blood Elf Bandit and getting the ''Blood Elf Communication'' item begins a quest, I tried to accept it but it told me I was already on that quest. I am pretty sure that I never done it before and the quest is not appearing in my quest log as well.
![sans titre](https://cloud.githubusercontent.com/assets/17889980/13865367/099d2d4a-ec81-11e5-8832-4a8054e2cfa0.png)

**Comment by KimmoKM** [comment]
Unlike other 1-10 starting areas, Azuremyst hasn't yet received "CC treatment" so you probably should report the issues by commenting the zone issue (#365).
