### ISSUE TITLE
GetComboPoints() returning 0 after Gouge on Focus

### ISSUE THREAD

**Issue by Schaka** [ccshiro/cc-buglist#2495]
How to reproduce:
- set /focus target
- untarget your target
- hit the below macro twice (once after Gouge is on the focus target)

`/cast [target=focus] Gouge
/run ChatFrame1:AddMessage(GetComboPoints())`

**Comment by Shanghi** [comment]
I think this is normal because TBC's GetComboPoints() only tells you the amount for your current normal target, so it should be 0 when there's not one.

**Comment by Schaka** [comment]
It works for other combo-point generating moves, as well as Kidney Shot (assuming the Ruthlessness procs).

**Comment by DarkenRal** [comment]
@Schaka Is it because you're selecting your focus as a target when you have no target and try any attack on focus (except gouge, blind or some other CC abilities)? At least i get taget on my focus if i try /cast [target=focus] Kidney Shot or /cast [target=focus] Hemorrhage when i have no target.

**Comment by ccshiro** [comment]
I think what @Shanghi and @DarkenRal say is the case. Will close as invalid. If you find some proof in the opposite direction feel free to reopen the issue.
