### ISSUE TITLE
Thunder Clap Slow Effect

### ISSUE THREAD

**Issue by GPSRT** [ccshiro/cc-buglist#2496]
Thunder Clap DOES take affect to mobs and their attack speed is slowed, but Improved Thunder Clap doesn't seem to be improving that slow effect at all.

The attached screenshots show that the effect's debuff doesn't show any incremental increase in the slow effect's note (yes I waited for the debuff to fall before applying another), but I'm unable to test in great detail against mobs since I'm unable to count the frames between attacks.

![thunder clap](https://cloud.githubusercontent.com/assets/13350632/13989104/45ed4a42-f0e5-11e5-9c86-af37de043650.png)

```
  ~Borris
```

**Comment by Schaka** [comment]
Buff and debuff tooltips weren't affected by talents in TBC.

**Comment by Lephidiles** [comment]
Was about to say on irc but to late ^^

**Comment by GPSRT** [comment]
As long as it's not an issue, this shouldn't be open!
