### ISSUE TITLE
Item stats are not correct

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#250]
http://eu.battle.net/wow/en/game/patch-notes/2-1-0

Under items:
-The majority of level 70 epic items have been upgraded to reflect their intended power.
-Armor: All Burning Crusade items that spent part of their budget on increased armor have been re-evaluated. Some gained additional armor, while others gained other additional bonuses. 

http://forum.nostalrius.org/viewtopic.php?f=2&t=603 <-- They have change the stats from 1.12 to 1.4 state so its possible.

**Comment by FurioCC** [comment]
Was stated that item stats/talents/ability interactions/etc going to be as of 2.4.3 state.

**Comment by ccnim** [comment]
As FurioCC pointed out.
