### ISSUE TITLE
 [Quest] - [Bloody Vengeance] is bugged

### ISSUE THREAD

**Issue by InvisibleJon** [ccshiro/cc-buglist#2503]
One does not get kill credit for killing the summoned Urtrak. (I tried two times)

The scenario works, with summoning the human ghosts though.

http://i.imgur.com/sl9W28m.jpg

How to reproduce:
Pick up  [Bloody Vengeance].
Go to the Alliance Banner outside Zeth'Gor in HFP.
Use the Unyielding Battle Horn.
Kill Urtrak.
No credit.

**Comment by InvisibleJon** [comment]
It seems to work now, I guess you can close it.

**Comment by Chulain** [comment]
@InvisibleJon you can close your own issues
