### ISSUE TITLE
Holy Resistance

### ISSUE THREAD

**Issue by Schaka** [ccshiro/cc-buglist#2506]
I noticed Holy Resistance (causing partial resists) still exists when checking out another topic.
![Screenshot](https://cloud.githubusercontent.com/assets/14111503/9662344/7824cc1e-5235-11e5-86df-a4fbfe646e0f.jpg)

[Source](http://wowwiki.wikia.com/wiki/Holy_resistance)

**Comment by Peonstomperx** [comment]
related  #1603

**Comment by Schaka** [comment]
Because this is about holy resistance existing in the game (and leading to partial resists) as shown in the combat log. Holy damage shouldn't be resistable.

**Comment by Peonstomperx** [comment]
working as intended #1778
