### ISSUE TITLE
Fleeing NPC run at 100% speed when low HP

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#2507]
Fleeing NPC run at 100% speed when low HP

**Comment by ghost** [comment]
@Lephidiles maybe say which mob? where? when? use .movegen command?

**Comment by Lephidiles** [comment]
it is all of them atm :)

**Comment by SuddenDeath** [comment]
This report is false, tested a few mobs and they're all slowing down their speed when going low.

**Comment by ghost** [comment]
I must say you're mistaken, I just recalled I had this happen on two different mobs , however, not always happened while "fleeing"
Some mobs in the demon-full ruins in Western south HFP and some of the lesser mobs(the unbroken, not naga) surrounding the draining machines in zangarmarsh

Some of this mobs even had "supernatural" speed, going over the 100% mark

On Mon, Apr 04, 2016 at 8:45 PM, SuddenDeath < notifications@github.com [notifications@github.com] > wrote:
This report is false, tested a few mobs and they're all slowing down their speed when going low.

**Comment by Lephidiles** [comment]
humm on my palla it does not look like it although they slow down eventually.. i leave it open for now and see if i find what it is
