### ISSUE TITLE
Engineering Goggles available should not

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#251]
http://eu.battle.net/wow/en/game/patch-notes/2-1-0

-11 new epic goggles have been introduced at 350 engineering skill and are available from the trainer. They range from cloth to plate, and have a variety of stats to appeal to most talent specs. 

Should not be able to train these from the engineering trainer until BT is released.

The stats on them are stronger then T4

**Comment by ccshiro** [comment]
This has already been stated as our intent. Please don't create issues citing random patch notes. If you want to discuss stuff like this come join us on irc. The bugtracker is for issues found during testing.
