### ISSUE TITLE
Psychic Scream and jumping

### ISSUE THREAD

**Issue by wayte** [ccshiro/cc-buglist#2512]
Psychic Scream isn't landing when it should be in PvP. Moving targets essentially impossible to hit with it. 

Tested on troll and undead, disc and shadow priests vs horde players in arena. 

Double checked vs PvE mobs and it functioned as normal, arena / PvP issue?

**Comment by ConfusedCC** [comment]
#2465

**Comment by wayte** [comment]
Checked in a duel, issue is with jumping. 

Psychic scream doesn't appear to be casting from character position, rather where they were before they jumped.
