### ISSUE TITLE
High Priestess Jeklik resetting

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2514]
![2016-04-09-204836_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/14406488/8f77fdb8-feb1-11e5-857d-0d19b9f2aa72.png)

If you walk a few yards behind the position seen in the first screenshot screenshot, Jeklik suddenly disappears (no evade or anything, just disappears, although she does at least respawn instantly).

![2016-04-09-204840_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/14406492/a9208708-feb1-11e5-878c-3f143d8e797c.png)

**Comment by ccshiro** [comment]
Her leash triggered. The center point of her leash was wrong (had put it on the exit by mistake).
