### ISSUE TITLE
Transmute CD incorrect

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#252]
http://eu.battle.net/wow/en/game/patch-notes/2-1-0

-Cooldown time on Earthstorm and Skyfire Diamond transmutes has been reduced to 1 day.

Use to be 48 hours pre BT.

http://www.wowhead.com/item=25867/earthstorm-diamond#comments - Second comment.

**Comment by ccshiro** [comment]
Please don't create issues citing random patch notes. If you want to discuss stuff like this come join us on irc. The bugtracker is for issues found during testing.
