### ISSUE TITLE
Blood Fury removes other negative healing effect

### ISSUE THREAD

**Issue by Dusky1** [ccshiro/cc-buglist#2523]
When you cast Blood Fury and gets the -50% healing from it, it removes Wound Poison, Mortal Strike, Aimed-Shot and other simmilar effects.

**Comment by Summoning01** [comment]
"By Jope (335 – 1·3) on 2008/06/27 (Patch 2.4.2)  
Interesting tip for Shamans: If you use this it will remove Wound Poison, so if they get 4-5 stacks up on you, it's a good way to get it off. "
