### ISSUE TITLE
Mage Fireball incorrect speed at level 1. 

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2539]
Mage fireball starts out at it's fastest speed at 1.5 second cast at level 1. Rank 2 fireball spell cast time is increased to 2 second cast time. The spell is supposed to scale with you and as you level up. This was discovered in the BE starting zone. I believe the time for a rank 1 fireball to be cast is 2.5 seconds at level 1.

**Comment by ConfusedCC** [comment]
![fireball](https://cloud.githubusercontent.com/assets/10581981/14645505/35ebf676-0656-11e6-9d5a-08db3d836183.PNG)

http://wowwiki.wikia.com/wiki/Fireball?oldid=771637
