### ISSUE TITLE
Ironfel

### ISSUE THREAD

**Issue by GPSRT** [ccshiro/cc-buglist#2541]
With the quest "Dark Iron Legacy" (3802) in the quest log, I killed Fineous Darkvire (9056) and he did not drop the quest item Ironfel (10999) to complete the quest and obtain the Shadowforge Key (11000), the key to BRD.

![image](https://cloud.githubusercontent.com/assets/13350632/14646105/4f4125b8-0626-11e6-8895-725db3c78cbc.png)

**Comment by ghost** [comment]
Looks like you were in a raid group

**Comment by GPSRT** [comment]
Sigh.  I bow my head in shame.

I now have the key, tested and works.  Being blond sucks.
