### ISSUE TITLE
Arena doors not opening after arena start.

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#2543]
I did some skirmish 2v2 and at happened that the doors in blade's edge arena (maybe also happening in other arenas) are not opening to me. Other players were able to run through it, so the problem was not for everyone in the arena. Anyway, critical error coz it's instant lose.

**Comment by Liesara** [comment]
Pira dear, my beloved troll, i know it's much to ask but use the search function will you?
https://github.com/ccshiro/cc-buglist/issues/1784

**Comment by Piranhaz** [comment]
no i won't, i got my subjects for it
