### ISSUE TITLE
Incorrect NPC in Shattrat is spawned

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#256]
http://eu.battle.net/wow/en/game/patch-notes/2-4-0

-A representative of the Keepers of Time has been spotted at the World’s End Tavern in Shattrath. Players in good standing with the faction will be granted ease of passage to the Caverns of Time.

This NPC was added on sunwell release.
http://www.wowhead.com/npc=25967/zephyr#comments <-- should be removed

**Comment by ccnim** [comment]
Has already been removed.
