### ISSUE TITLE
arena gates

### ISSUE THREAD

**Issue by Evolvee** [ccshiro/cc-buglist#2565]
this is more like a proposal than a bug report...
can u remove the gates after arena starts? because now you can easily put totems into it and without enemy name plates, enemies cant see it

**Comment by Chulain** [comment]
i'm against this if it weren't the case on retail, i actually do make use of these doors sometimes

so if you could on retail, why not here?

**Comment by Evolvee** [comment]
sure but its abusing when u cannot target tremor totem via it.. almost the same as when u put tremor totem into pillar(for example in blade edge)

btw i dont actually think u could do this on retail, thats why im writing this, i will find some material

**Comment by Ainulatac** [comment]
I'm sorry it must be my fault but could we get a video illustrating the problem? I'm afraid I don't get the issue, remove the gates? What gates? lol. As far as I know when arena starts the gates open and there are no longer gates anywhere. Does this mean gates remain there and players can't go inside the perimeter where opposing team started? If so wasn't like that on retail at all. If it's something else excuse me, as I said I'm lost as to what's going on exactly.

**Comment by Chulain** [comment]
how is it the same, when totems are placed inside a pillar they can't be destroyed (i think?), these doors lose their LoS mechanic when they open as far as i know

**Comment by Evolvee** [comment]
they can be destroyed, you can auto attack through los

**Comment by Chulain** [comment]
dont think you can auto attack thro los on retail

**Comment by Evolvee** [comment]
i dont think so as well but ccnim thinks something else
https://github.com/ccshiro/cc-buglist/issues/2143

**Comment by somnu** [comment]
It was possible to melee auto attack through LoS on retail (this was a fundamental wow mechanic that still works in warlords of legion afaik) and also arena gates stayed there (in their open position) on retail after the arena began. I remember druids would hide inside them in stealth hoping they won't be spotted.

**Comment by booplol** [comment]
Somnu is correct. You definitely could melee attack through LoS and the gates remained open.
