### ISSUE TITLE
WSG flag mechanics are incorrect

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#257]
http://eu.battle.net/wow/en/game/patch-notes/2-4-0

Warsong Gulch

```
When both flags are held, the flag carriers will receive 50% increased damage done to them after approximately 10 minutes and 100% increased damage after approximately 15 minutes.
Flag carriers can now be tracked 45 seconds after picking up the flag.
```

incorrect for a 2.0 release

**Comment by Whatsthis880** [comment]
https://www.worldofcorecraft.com/content/faq-frequently-asked-questions
Q3:
"The game will be running 2.4.3."

**Comment by ccshiro** [comment]
Flags work as we intend them to at the moment. Please don't create issues without having played on the server. Citing random patch notes is not useful.
