### ISSUE TITLE
Warlock - Voidwalker pet HP/5

### ISSUE THREAD

**Issue by Tim02035** [ccshiro/cc-buglist#2574]
the Voidwalker pet health seems to return at a very slow rate even when out of combat.  Making use of the pet heal much more often than i remember it being on official servers at the time.  I also believe the mana returns much faster than on official TBC.  Thanks

**Comment by ghost** [comment]
You have to provide any kind of proof of the official HP/MP Reg of the Voidwalker, else this report will have zero use

**Comment by Tim02035** [comment]
Ok, unfortunately I'm not sure I know how to find that info.  Just know that it is not blizzlike the way it is now.  I'll refrain from posting anything unless I can find original data for comparison.  Thanks.
