### ISSUE TITLE
[Hellfire Peninsula][NPC] Cursed Scarab Neutral

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#2577]
The NPC Cursed Scarab | 21306 ( invis Summoning NPC 21308 ) that spawn during some Quests in Hellfire are neutral (yellow) instead of aggressive (red) 

Only 1 Scarab per Spawn is set to aggressive, the rest of the spawn doesn't aggro or fight.

**Comment by Chulain** [comment]
http://www.wowhead.com/npc=21306/cursed-scarab#comments
Some of the ones that spawn are Hostile, but the majority are Neutral. However, sometimes they will randomly change from Neutral to Hostile.
Don't worry about killing them; they despawn in about 10-20 seconds.

**Comment by ghost** [comment]
Ah, did it on 4 Characters on Retail, seems they changed it.
