### ISSUE TITLE
Potion critical strike scaling

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#2581]
**Edit:**My original claim of potions not critting turned out to be false. Further testing by Bahalol showed they can crit, and I think I figured out the reason for my incorrect results: I assumed pots scaled with spell crit while they in fact scale with physical crit on the test server. However, as no reliable source has been found (a Wowhead comment from WotLK linked below claims it's spell crit, but in WotLK critical strike ratings were combined to one and as such it'd have taken serious testing to figure out which one was used, with spell/phys crit chance being similar for all characters), I'm leaving this issue open in case someone finds proof that shows how potion crit chance scaled (if it scaled at all: it most definitely scales at retail and almost certainly scaled in WotLK, but there's no TBC/vanilla evidence that I'm aware of).

---

This issue was already discussed in closed issue #1461: healing potions currently can't crit on the test server (tested with 300 pots, not a single crit). The fact that they should is well-documented.

However, what is the crit chance? In #1461 Doppelmoral claims they should have 5% base crit chance and while no source was found for this claim as we discussed it in IRC, I do also feel this was the "conventional wisdom" back in the day. However, a comment from [WotLK](http://www.wowhead.com/item=33447/runic-healing-potion#comments:id=669747:reply=150183) claims they used spell crit so I went to retail to test this:

With 28% crit chance, out of 25 pots used, 7 were crits. With a naked character (5% crit), out of 40 potions used, only 1 crit. It's immediately clear that at least in retail WoD critical strike chance affects the potion crit chance, and since this was documented in WotLK, this probably has always been the case (I can't think of a single change that might have changed how pots work: for example, while separate spell/physical crit ratings were combined, the crit chances as a whole stayed as separate entities). Now, I do think there is some question about if the game used spell or melee crit (due to ratings being combined, spell and melee crit would have been rather similar for everyone during WotLK so I wouldn't put much weight on that comment beyond the fact that pot crit chance scales: even humans can notice a difference between 5% and 50% but 25% and 50%, no) but in the absence of thorough testing results from vanilla/TBC, scaling pot crit chance, not 5%, seems like the most reasonable choice.

In addition, I used 35 mana pots with 30% crit chance character. Not a single crit. That's how it currently works on the test server and most of everyone agrees this is how it has always been, but it's nice to have some actual numbers on the table considering the conventional wisdom of healing pot crit chance seems to have been false.

Also, while I haven't tested it yet, I thought to rescue one additional detail from the other issue: Dark Runes should be able to crit [source](warcraft.securityorg.net/Mana%20consumables-58.htm).

**Comment by Barroth** [comment]
Found a picture of a demonic rune crit: [http://www.diskusjon.no/uploads/post-59574-1167354017.jpg](http://www.diskusjon.no/uploads/post-59574-1167354017.jpg)

Apparently it can crit, but doesnt give double mana return
src:[http://www.diskusjon.no/index.php?showtopic=689082](http://www.diskusjon.no/index.php?showtopic=689082)

Healing Potion/Healthstone have pretty much the same spell traits(Spellschoolmask,Damageclass,preventiontype,spell_effect_heal) so most likely both should be able to crit, or none of them

**Comment by Bahalol** [comment]
From the test server:
![wowscrnshot_052116_005122](https://cloud.githubusercontent.com/assets/17086469/15446443/2b5c0398-1eef-11e6-82be-cadbf5f58f4c.jpg)

**Comment by Doppelmoral** [comment]
Stats were mashed up in WotLK, removing the distinction between physical and spell stats, the crit-scaling may have been introduced there. I'm still standing my ground saying pots etc had a base crit chance in TBC, and we can only settle the argument by finding any source. Btw scaling makes no sense in my eyes UNLESS all classes / specs receive a similar benefit.....

**Comment by KimmoKM** [comment]
Only the critical strike rating stats were combined, though. Physical and magical crit chance as a whole were not the same.

**Comment by Bahalol** [comment]
I'll test 100 potions today to see if I can average out a potential critical hit %. I'll compare it to my current spell critical hit %.

**Comment by Bahalol** [comment]
Out of 100 potions, 20 of the potions resulted in a critical heal. Based on this sample size, there is a 20% chance that your Super Healing potion will yield a critical heal. I tested with a spell critical chance of 4.65% and a physical critical chance of 16.68%.

Caveat: When I began testing, I forgot to remove the Mark of the Wild buff for the first 12 or so potions. The first 12 or so potions were tested with a spell critical chance of 4.88% and a physical critical chance of 17.28%. An Alchemist Stone was also equipped throughout the test.

I manually recorded each heal I received from each potion if anyone is interested in analyzing/plotting/graphing the data.

**Comment by KimmoKM** [comment]
Looks like I made a mistake in testing, assuming spell crit was used for scaling like that one comment suggested, while the potion crit chance is in fact based on physical crit on the test server and I had 0% melee crit while testing.

I can't find a definite source (and retail testing won't do because there no longer is separate physical or spell crit) but pot crit% scaling probably was based on physical crit, just like it works now. Since there still is uncertainty about this, I left the issue open in case someone has actual proof.

**Comment by Bahalol** [comment]
With the assistance of Frag, I conducted a follow-up trial with another set of 100 Super Healing Potions. This time, with a spell critical strike chance of 3.70% and a physical critical strike chance of 4.04%. My results yielded 5/100 critical heals - 5%; this correlates with the assertion that Super Healing Potions' critical strike % scales with your character's physical critical strike %.

I also have the data points for this trial if anyone is interested in further evaluating the data.

I will be conducting one more trial to confirm or disprove the existence of a cap for the critical strike % of Super Healing Potions and to further confirm the assertion.

**Comment by denman1999** [comment]
I have read and accept the content of the paste.

**Comment by Lephidiles** [comment]
https://docs.google.com/spreadsheets/d/1mDCcRAtMraOws3oljeEMGBLFNnUdVHbkQzMhL_5xIgI/pubhtml

This was tested on the test server with:
4,05% melee crit chance
1638 +Healing
12,78% spell crit

Result:
2% Crit from Healing potion
Average healing: 2093,84

**Comment by brndd** [comment]
> with a spell critical strike chance of 3.70% and a physical critical strike chance of 4.04%. My results yielded 5/100 critical heals - 5%; this correlates with the assertion that Super Healing Potions' critical strike % scales with your character's physical critical strike %.

With a stat difference that small, you would have to chug thousands of potions to get even a reasonably good guess at whether it's using spell crit or physical crit.

**Comment by Bahalol** [comment]
Had I only tested with the stats that you quoted, you would have a point but the first test and Kimmo's test indicates that physical critical strike % heavily or entirely influences the critical strike % of Super Healing Potions. I have begun my final testing with an extremely high physical strike % (52.32%) and a relatively low spell critical strike % (4.66%).

With the aforementioned stats, 41/100 of my Super Healing Potions yielded critical heals. I believe it is safe to conclude that physical critical strike % is the primary (or sole) contributor to Super Healing Potions resulting in critical heals.

**Comment by Barroth** [comment]
The healing spell of the potions got SpellSchoolMask = 1 (MASK_PHYSICAL) so they are affected by physical crit

**Comment by KimmoKM** [comment]
Well, I guess that settles it. Closing the issue.
