### ISSUE TITLE
Umbrafen Witchdoctor drops runecloth

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#259]
Umbrafen Witchdoctor (http://www.wowhead.com/npc=20115/umbrafen-witchdoctor) should drop Netherweave Cloth with a 76% chance of dropping, but instead it gaved me 2x Runecloth. And if you check the mob in wowhead, they should not even drop runecloths like at all.

**Comment by ccshiro** [comment]
Wowhead seems a bit unreliable for this, for example I was sure this mob should drop runecloth:
http://www.wowhead.com/npc=18952/bonechewer-scavenger
But it's not listed. The mob right next to it does drop runecloth:
http://www.wowhead.com/npc=19701/bonechewer-evoker

Trying on retail wowhead seems to be correct for the current game version, but it'd require more research. Our current formula is based on level and expansion, so should work well over-all. The fact that it might be wrong (would require research) for this level 60-61 mob seems irrelevant.
