### ISSUE TITLE
Warlock pet resummon

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#26]
Report:
"Resummoning pet should reset his cooldowns on all spells."

Note: This is about warlock pets in particular. For example resummoning mage's pet does indeed clear its cooldowns, we're less sure about warlock and are looking for some evidence, however.

**Comment by Thepump** [comment]
All I found so far: http://www.arenajunkies.com/topic/3166-dealing-with-double-slsl-warlocks-in-2v2/

Read the last 5 posts in the thread.
From those posts it seems like it used to work in early TBC but Blizzard seemed to have changed it later on in TBC. 

Though I'm not sure if this is proof enough, could have changed it back. Though it is unlikely.

What if the pet dies and you resummon it though? Should the cooldowns then reset?

**Comment by lynxzor** [comment]
Neilyo 9 - Hemo&Mutilate 2007-10-21
Gumbot's spell lock was on cooldown, fel domination + spell lock Kinttlol's Greater Heal @ 21:49
http://www.warcraftmovies.com/movieview.php?id=48387

**Comment by kolchax** [comment]
Apparently, it did reset in cata and only in arenas.
http://eu.battle.net/wow/en/forum/topic/2098162869

**Comment by Aeoni** [comment]
I've cut 2 clips from a video together you can watch it here.

http://youtu.be/fMQ2HkzpAws

Edit: Music is a bit loud.

**Comment by Thepump** [comment]
Aoeni what movie are those clips from?

**Comment by Aeoni** [comment]
Oh yeah heres the link to the video http://www.warcraftmovies.com/movieview.php?id=85287
The clips I posted are between 2:09 - 2:20 and 15:13 - 15:30.

I don't know if someone has uploaded the whole video on youtube. I may be upload it, but it could take a while with my internet connection.

**Comment by ccshiro** [comment]
Link PM'd to me by Mustonen: http://www.arenajunkies.com/topic/33853-spell-lock-feldom-spell-lock-how/

**Comment by Klimpb** [comment]
Talked a bit with Mustonen on IRC and what seems to be the case of that thread is that the cooldown only resets inside of arenas. 

The reason for this is probably because of when anything enters an arena "it" gets all of its cooldowns reset. Since the pet gets summoned inside of arena, the game treats it as if it were just like any other player that enters arena.
