### ISSUE TITLE
[quest] I Was A Lot Of Things...

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#2639]
tuber mounds don't disappear after calling a felboar to dig (so one mound can be used to complete the quest).
[retail](https://www.youtube.com/watch?v=uIlgWOV-_oQ)
[ptr](https://www.youtube.com/watch?v=69BLIWjB004)

**Comment by KimmoKM** [comment]
Duplicate, the first report seems to be #1625
