### ISSUE TITLE
[Visual Bug(?)] - Double Autohit after weapon enchant-proc

### ISSUE THREAD

**Issue by Jonssown** [ccshiro/cc-buglist#264]
Autohits appears to be bugging out after weapon enchant procs, see these pictures for an example:
http://imgur.com/a/KpCNO

I also tried Windfury Weapon, that didn't seem to have the same issue. However, Windfury seemed to cause spell damage (Yellow Text), not Weapon damage. I might be wrong regarding this issue though, so please comment.

EDIT: WF Text seems to be correct, it should be yellow. Source: https://www.youtube.com/watch?v=xfuX_NjI-xc

Good luck & Keep it up!

**Comment by Chulain** [comment]
visual bug, double hit happens on all private server and on retail too (not 100% sure)

check combat log next time

**Comment by ccshiro** [comment]
Unless you got the damage of two hits (when testing I don't), then this is just a client-side scrolling combat text bug that existed forever on retail.
