### ISSUE TITLE
(Event) Infernals are not spawning to fight guards outside shadowmoon village or wildhammer stronghold

### ISSUE THREAD

**Issue by ConfusedCC** [ccshiro/cc-buglist#265]
Infernals are not spawning, Shadowmoon scouts and wildhammer defenders have nothing to do.

**Comment by rylaiii** [comment]
Hey friend, 

I just wanted to say hi and show you some stuff  I've recently come across, check it  out http://nticrusaze.heidiandtimothy.com/lnwkiu

Best regards, ross.porto
