### ISSUE TITLE
Taking durability when I die in PvP

### ISSUE THREAD

**Issue by solowt** [ccshiro/cc-buglist#267]
Easy to test.  My combat log said I took 10% durability from a death in PvP and my gear was missing durability.  

I believe you shouldn't take a durability hit from dying in PvP.

**Comment by Doppelmoral** [comment]
While it is sort of implied, I still want to emphasize that your gear should loose durability in PvP combat, just not the 10% when you die.

Means while fighting other players the "normal" PvE damaging is applied (e.g. with imaginary number: 1 durability loss of weapons after 1,000 swings). Just mentioned it so durability will not accidently taken out completely of PvP activities.

**Comment by ghost** [comment]
Dying from other players should not cause durability loss. PvP combat is not related to durability at all.

**Comment by Klimpb** [comment]
What @Doppelmoral saying about the durability loss from swings/spells etc is correct(I'm fairly sure). I specifically remember having to repair my gear after playing an entire day of arena in wotlk... Or it might have been TBC, not sure. I do however know that you very slowly took durability hits.
