### ISSUE TITLE
Dead mobs following you 

### ISSUE THREAD

**Issue by solowt** [ccshiro/cc-buglist#268]
S.ome mobs are following me on the ground after I kill them.

reproduce: kill a mob, see what happens.

note: tested on the white lizard guys outside of shattrath

**Comment by deltafoxnine** [comment]
I can confirm, and apply video if necessary.

It also happens with the wolfes

**Comment by solowt** [comment]
to go further, a dead mob is currently following me, hitting me, and casting spells on me.  it's the warp stalkers outside shatt.

**Comment by jpierz** [comment]
Can also confirm. Happened on the moths as well outside shattrath.

**Comment by Fnmx** [comment]
https://www.youtube.com/watch?v=56E-5rpf140

Here's a short video of what's going on. It even looks like the wolf has the warpstalker AI.

**Comment by Chulain** [comment]
winter is coming

**Comment by Exulance** [comment]
This happened to me too, only by the Warp Stalkers outside Shatth though.

**Comment by ccshiro** [comment]
I can't reproduce this. It's possible this was the same origin as the first crash we fixed. That crash was of the kind that could cause all kinds of strange side effects. If I'm wrong and this happens again next test please reopen this issue.
