### ISSUE TITLE
rezist on lvl 63 mob  while hit caped

### ISSUE THREAD

**Issue by jovce17** [ccshiro/cc-buglist#269]
i was testing ele shaman on adds in terokar i managed to miss( rezist) on lvl 63 mob with >
6% hit chance on spells , 9 % from talents (6% from ele spec and 3 from resto spec ) 
- 3% from totem of wrath ...
  i had a total +18% hit chance ... and still manged to make a rezist hit using lightning bolt 
  http://s14.postimg.org/b125irc3l/Wo_WScrn_Shot_033115_212832.jpg

**Comment by solowt** [comment]
my understanding is that it's impossible to have a 100% chance to hit and there's always a 1% chance to miss.

Perhaps that's what happened.  Would be nice to hear from some people who are more knowledgeable on the subject than me though.

**Comment by jovce17** [comment]
actualy did some more testing  from 34 lightning bolt casts on lvl 62-63 mobs i manged to get 2 rezists ...
http://s9.postimg.org/m7r068i1b/Wo_WScrn_Shot_033115_215303.jpg
2/34 its more like a 6% not 1 % ...and its Vs lvl 62 mobs ....not 73 or BOSS

**Comment by Iliana-sc** [comment]
34 is hardly enough trials to make any kind of conclusion.

**Comment by jovce17** [comment]
@Iliana-sc  if there is 1 % chance that cant be avoided via capping then true and will need more testing but ....if its not supposed to miss vs 62 mob then its a bug

**Comment by nz54445** [comment]
This may be useful for the conversation:
http://www.wowwiki.com/Spell_hit

It's partly wotlk and partly tbc, but the main points are there.

Now i remember something ~ 5% resists when you are hit capped on bosses, but that's just me. I can not for the life of me find any attack tables. I am almost sure that against normal mobs you should not miss at all.

**Comment by tedrasiel** [comment]
when i remember right, if youre not hitcapped u can "miss" against mobs too, but the second u are , u shouldnt miss on them (if they're on your lvl- range or lower). but no proof for that one

**Comment by jovce17** [comment]
as far i can remember you need 18% to not miss on bosses 15 vs lvl 70 mobs and even less as the mobs level goes down as far i do remember you dont even need any hit rating vs lvl 66 mobs  >3 lvls bellow you ...

**Comment by nz54445** [comment]
If you look at the link it's clear that it's 17%, and I am 100% sure of that, because draenai ele shamans only need 4% hit: 9% from talents, 3% from wrath and 1% from aura = 13% + 4% = 17%.

Furthermore you only need 6% on Heroics, because no mob is higher than 72.

Bottom line is, hit can be capped and you shouldn't ever miss mobs when you are hit capped, or it should happen very very rarely. There might still be a base miss chance but i can't find the link anywhere.

**Comment by ccshiro** [comment]
Stepped through with a debugger. The scenario you described is using a 1% chance to miss, which is the intended behavior. If you want to statistically analyze this (might be a good idea in case something later down the road goes wrong), I suggest a lot more trials.
