### ISSUE TITLE
Do Expose Weakness and Imp. Hunter's Mark stack?

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#27]
Question: Does the effect of Expose Weakness and Imp. Hunter's Mark stack?

It seems natural to assume the answer is yes, but it would go against the current ruleset for stacking, indicating an exception in the current rules, or a new rule. Therefore we need evidence to implement this.

**Comment by Barroth** [comment]
According to Cheeky's Spreadsheet those two should stack.
See Table "Buff" at Target Debuffs, or "Pet Calculations":
![image](https://cloud.githubusercontent.com/assets/9391338/5132334/e79e9d34-70fb-11e4-90f5-9d3f2b6552bb.png)

For ranged attackpower it has this: 
![image](https://cloud.githubusercontent.com/assets/9391338/5132450/e8a7b7dc-70fc-11e4-91a7-ead9a612f5ff.png)

**Comment by ccshiro** [comment]
@Barroth I'm inclined to consider that enough evidence to go with it. While it could've been overlooked in the spreadsheet, it is what makes the most sense as well. Cheers.
