### ISSUE TITLE
Cannot attack mob

### ISSUE THREAD

**Issue by deltafoxnine** [ccshiro/cc-buglist#271]
Attacking a moth outside of shat, it seems like it was disappearing and reappearing. Said "Interruped" when trying to hit it.

I can supply footagea/fraps

**Comment by ccshiro** [comment]
Please do supply footage.

**Comment by deltafoxnine** [comment]
here you go http://youtu.be/El2HQBisY4U

**Comment by ccshiro** [comment]
Most likely the same underlying reason as our first crash. Can't get it to happen, so I think it's fixed. Please do try again next test, though. Just in case.
