### ISSUE TITLE
Kiting

### ISSUE THREAD

**Issue by testinkzcc2015** [ccshiro/cc-buglist#273]
I kited Fel reaver to Thallmar in hellfire peninsula and did like 1% damage to it.
I died and after I resurrected I was able to loot its corpse.
Shouln't guards killing a mob with higher damage dealt deny looting?

edit: Does it matter if I was alliance not horde, and horde guards killed it.

**Comment by Iliana-sc** [comment]
An anecdote that that I remember from playing a hunter on retail (this is by no means proof): if your pet did 100% of the damage to a mob you would get no experience or loot for that mob.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=aQDNcRefCx4

A druid kited fel reaver to Shat using rank 1 insect swarm doing what looks like a total of 20% damage and couldn't loot him at the end.

https://www.youtube.com/watch?v=AdBv9ZU-d5I

Horde kited Fel Reaver to Honor Hold and don't appear to be able to loot it after they died.
