### ISSUE TITLE
Target shows only percent of life, no number

### ISSUE THREAD

**Issue by Sakatoro** [ccshiro/cc-buglist#274]
My Target (Player or NPC) shows only the percent of the life, not the number.

**Comment by jovce17** [comment]
its is as INTENDED its TBC not WOTLK
IF you want number download mobinfo addon

**Comment by Sakatoro** [comment]
Sure? Because on all other TBC-Servers i got the hp numbers of my target, without any addons

**Comment by Sakatoro** [comment]
Checked that, sry for the wrong report
