### ISSUE TITLE
Food doesn't restore health in combat

### ISSUE THREAD

**Issue by Fnmx** [ccshiro/cc-buglist#275]
Pulling a mob with my pet after sitting down to eat makes the food stop restoring health, even though the buff is still there. Drinking works normally.

**Comment by ccshiro** [comment]
That was intentionally done at some point although I cannot remember why. Some indication that this is indeed a bug would be nice.

**Comment by Klimpb** [comment]
@ccshiro Maybe it was done because of things related to the spell delay? Like casting heal on someone who's in combat then spamming eat/drink just as it goes off?

But yeah, if you have the eat/drink buff, they should give you health/mana... Weird how it was just affecting the health though.

**Comment by tedrasiel** [comment]
so ure saying spamming drinking while casting a cast (and while casting u leave combat) and entering combat after finishing the cast + drinking then cause of the spamming wont be possible?

i know it worked on retail... even tho it can be considered a bug... it was often used by healers like shamans so they were at all able to hold their ground against restro druids and their ridicilous amount of mana reg. just sayin

**Comment by ccshiro** [comment]
@tedrasiel This is about food, not water.

I looked at it again and remembered. Food are buffs that increase your passive regeneration while active. There's no doubt that passive (unlike combat regen) should be disabled during combat. If food should be passive regen (which it is), but be exempt from the functionality of passive regen, proof needs to be provided. A video during TBC where someone is eating while in combat and still benefits from the regen would be sufficient proof for us to reinvestigate this.

**Comment by ghost** [comment]
I found this:
https://youtu.be/6DTmw7FvKCk?t=11975

It's from vanilla though patch 1.1. If you  slow down the speed you can see that the food+water ticks  but after the raptor aggros the hp stops ticking while the mana continues. So it seems like food is not supposed to work in combat? I honestly thought it did but I guess I'm brain washed from retail and faulty private servers? I've tried find something from TBC but no luck yet.

**Comment by ccshiro** [comment]
@caffeinez That's how I thought it worked. Nice that you found proof. Will close as invalid.
