### ISSUE TITLE
Quest: Assisting the Consortium shown on both Aldor and Scryer npcs but only selectable from the faction you chose

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#276]
Zone: Netherstorm
Quest: Assisting the Consortium
NPCs: Spymaster Thalodien (Scryer) and Anchorite Karja (Aldor)

Issue: Quest "!" appears above both npc's heads but is only acceptable from the NPC from the faction you have chosen. Accepting quest appears to take both. 

Is this a minor bug or how it worked in retail?

**Comment by ccshiro** [comment]
@ccnim: Added so you can check quest giver as well in the conditions (target = 1).

**Comment by rylaiii** [comment]
Hey! 

I've chosen  some interesting  links you may  find helpful,  here  is  the full list http://success.nataliebogan.com/lnqqc

Warm regards, ross.porto
