### ISSUE TITLE
Arena: Movementspeed and eye timer bug

### ISSUE THREAD

**Issue by Aeoni** [ccshiro/cc-buglist#277]
Movementspeed: While entering the arena on flying mount you don't lose all of it's speed. You can run as fast as riding a 100% ground mount. If you stealth or mount up, you'll lose the speed.

Eye timer: Eyes are spawing as soon as the arena opens.

http://youtu.be/-n7m36otB7c

**Comment by Klimpb** [comment]
Same for entering instances.

**Comment by Aeoni** [comment]
Updated my post.
