### ISSUE TITLE
Faction items' reputation requirement

### ISSUE THREAD

**Issue by petaal** [ccshiro/cc-buglist#279]
Some items which can be bought from quartermasters don't mention reputation requirements. They can't be bought with no reputation however. At least the following quartermasters and items have this issue:

Fedryen Swiftspear <Cenarion expedition quartermaster>: Earthwarden, Windcaller's Orb
![ccbug2](https://cloud.githubusercontent.com/assets/11743711/6928895/d04b34ce-d7ff-11e4-93c2-faeaac60e521.png)

Nakodu, lower city quartermaster: Gavel of unearthed secrets, Shapeshifter's signet, Trident of the Outcast Tribe

Quartermaster Enuril, Scryers: Retainer's Blade, Seer's signet, Recipe: Elixir of Major Firepowerfrom

Quartermaster Endarin, Aldor: Medallion of the lightbearer

Almaador, Sha'tar:  Gavel of pure light, A'dal's command

Karaaz, Consortium: Haramad's bargain, Guile of khoraazi

**Comment by ccnim** [comment]
Delete your cache and that should fix it.

**Comment by petaal** [comment]
Yeah that fixed it
