### ISSUE TITLE
[Druid] Mangle (cat+bear)

### ISSUE THREAD

**Issue by Isuel** [ccshiro/cc-buglist#286]
currently, mangle cat and mangle bear debuffs are stacking, making shred and other bleed effects double dip from them. it's a mangos bug, since i noticed it on other tbc servers as well.

**Comment by Isuel** [comment]
with only 1 mangle effect, shred did 800 or so dmg. with the 2 mangle effects, it did 1-1.1k

**Comment by Edialden** [comment]
I already reported this in first tests, but i hadnt found a proof that this is incorrect. It wasnt fixed since then, so i guess its not a bug ;)

**Comment by helion84** [comment]
Patch 2.0.3 (09-Jan-2007): Mangle will not stack multiple copies from multiple forms or druids anymore. This was never intended behavior.

**Comment by Isuel** [comment]
well, to be honest i wouldn't mind it stacking, it would be a cool buff to feral dps :D

**Comment by ghost** [comment]
i thought talents/abilities should be 2.4.3?

**Comment by tedrasiel** [comment]
"Patch 2.0.3 (09-Jan-2007): Mangle will not stack multiple copies from multiple forms or druids anymore. This was never intended behavior" it was changed there and never changed back... atleast for bc.

**Comment by ccshiro** [comment]
Also seems to be bugged where it can stack from multiple sources.

**Comment by Isuel** [comment]
feral druid stack in raids MUST be the new thing! forget the locks and hunters!
