### ISSUE TITLE
Forsaken characters can breathe for too long underwater.

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#288]
Forsaken Characters can breathe for 4 minutes underwater instead of 3.

![wowscrnshot_033115_222336](https://cloud.githubusercontent.com/assets/10584393/6929492/6ad9cd2a-d7fb-11e4-9419-ce462c573cce.jpg)

**Comment by Chulain** [comment]
By FlipperGandalf  on 2008/05/25 (Patch 2.4.2)  
Just to clarify:
A non-undead character can breathe under water for one minute.
An undead can therefore breath for 1min + (1min \* 3) = 4 min

www.wowhead.com/spell=5227/touch-of-the-grave#comments/
