### ISSUE TITLE
Cannibalize not working properly

### ISSUE THREAD

**Issue by somnu** [ccshiro/cc-buglist#289]
After dueling an alliance player and killing him by mistake after the duel was over, I tried to cannibalize his corpse to regain some health.

To my surprise it displayed the error message "There are no nearby corpses", here is the proof:
http://i.imgur.com/WicOaqT.jpg

I don't know if it had something to do with the fact that I was dueling the guy then he died, but it clearly isn't working properly.

To reproduce:

Duel an alliance player, win the duel and kill him immediately after winning, then try to cannibalize his corpse.

**Comment by Chulain** [comment]
duplicate

**Comment by ccshiro** [comment]
Duplicate of #266.
