### ISSUE TITLE
Ambassador Hellmaw in Shadow Labs

### ISSUE THREAD

**Issue by pmizz** [ccshiro/cc-buglist#29]
I was in a group for Heroic Shadow Labs yesterday, after we killed the last pack of channeling Orcs, the first boss Ambassador Hellmaw did not release from his banish.  We continued on and he still did not release

I am positive we had wiped on the packs of Orcs channeling right prior to hellmaw and exited the instance to summon another if this possibly messed with him.

Other notes on the Heroic include 

-No fel armaments dropping (could this be caused form no one having rep with the Aldor)
-Very very few vendor greens I am talking like 3 or 4 after 25 packs of mobs, is that right?

**Comment by pmizz** [comment]
It is also possible a sever crash happened between killing the first pack of orcs and last pack

**Comment by ghost** [comment]
Might help with fixing...
Usually on private servers, the first boss only "releases" after you kill the Fel Overseer that is room right after second boss.
And the "release" is somehow linked to him+other mobs like him in first room dying.

Link to mob:
http://www.wowhead.com/npc=18796
