### ISSUE TITLE
Mobs bugging behind trees

### ISSUE THREAD

**Issue by somnu** [ccshiro/cc-buglist#293]
I simply pulled this wolf outside shattrath and went behind a tree, as you can see from the screenshot I wasn't standing in an unreachable location or anything and the wolf just stopped following me and started evading my attacks, after a couple of seconds he deaggroed and went back to his spawn.
http://i.imgur.com/zus4C3h.jpg

**Comment by ccshiro** [comment]
Fairly sure the cause is the same as for #283.
