### ISSUE TITLE
ARENA: Not restored to full health on join

### ISSUE THREAD

**Issue by giedrius-timinskis** [ccshiro/cc-buglist#298]
Not screenshot for this one, but I was having a duel, joined arena shortly after that and didn't get restored to full health. It was a skirmish arena though (maybe ranked works different?)

**Comment by tedrasiel** [comment]
i was his mate during this skirmish. can confirm this.

**Comment by ccshiro** [comment]
Just tested, and I got regenerated to full health in skirmish as well. If this happens again, please make a recording and open a new issue, so we can figure out what exactly triggers the bug.
