### ISSUE TITLE
Speaking in Demonic when MC'd

### ISSUE THREAD

**Issue by giedrius-timinskis** [ccshiro/cc-buglist#299]
This is a funny one and I'm not entirely sure what's causing it. It happened when I typed while I was MC'd by a priest, however the priest had a warlock in his party, so that could've been causing it too. Here's a screenshot: 
http://i.imgur.com/6fQNLPs.jpg

Cheers!

**Comment by nz54445** [comment]
Curse of Tongues (from a warlock) causes you to speak in Eredar (demonic) language. If he cast it on you (which he probably did), then it's working as intended :)

While it's retail http://www.wowwiki.com/Curse_of_Tongues the information is still valid (for flavour text).

**Comment by giedrius-timinskis** [comment]
Oh I didn't know that, and that's really cool. Thanks! Closing the issue.
