### ISSUE TITLE
Pet defensive stance broke with grid rewrite

### ISSUE THREAD

**Issue by tripleslash** [ccshiro/cc-buglist#302]
When a pet is in defensive stance and somewhere out of LoS of the mob your player is currently attacking, the pet is not sent on attack (does nothing, just standing around).

Tested with Felguard on mobs near shattrath.

**Comment by ccshiro** [comment]
Seems like defensive pets broke altogether in the grid rewrite. They don't attack when the owner is attacked.

Changed your title, hope you don't mind.
