### ISSUE TITLE
Fire Shield Imp

### ISSUE THREAD

**Issue by Owsikchaosue** [ccshiro/cc-buglist#311]
when u summon imp on auto cast fire shield he cant use skill but sound i heard he try can only cast shield only on target in combat who get hit . cant cast on ur target  but when u mark unfrendly target and use shield ur imp going to target and attack him

**Comment by ccshiro** [comment]
Works as intended when I tried them. Please try again next test and reopen the issue with further instructions if it still bugs for you.
