### ISSUE TITLE
Pets do not attempt to attack from behind anymore

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#312]
Something must have messed it up since it was working before. Maybe the fix on totems?

**Comment by ccshiro** [comment]
We removed it from players. In other words it only follows behind on NPCs. We did that because if you kept spinning around as a player the mob would keep moving behind, sometimes cancelling its auto attack. Maybe this needs research though?

**Comment by leroy1** [comment]
There is a difference between trying to attack from behind and attack only from behind. Pet shouldn't stop autos while trying to get behind the target

**Comment by Klimpb** [comment]
Can watch the whole video but I'd say the parts most worth watching are:

The game that starts around 01:00 & from 06:16 onwards(watch the void walker on the paladin)

My understanding of it is that if you send your pet on a player that stands still, the pet will not try to position himself behind the target. However as soon as the player that the pet is attacking moves away far enough from the pet so the pet has to move, that's when the pet will try to position himself behind the target but also when that target stops the pet will stop behind the target. 

If you watch the game at the 1 minute mark you'll see the felguard going all over the place since the targets are moving so much. But this can also be seen in the game at 6:16.

Link: https://mega.co.nz/#!uREwiQ7K!34uCYxuruRvS4A-ABaQSoyPFvL6AwxCtjpZ5Ne_A068

**Comment by Barroth** [comment]
I actually think it is a pulse like check every few seconds when the pet is attacking and not moving.
https://youtu.be/TMNxDcMOXRs?t=135 at 2:19 the pet repositions itself, even though it finished it attackchase movement before

**Comment by ccshiro** [comment]
@Barroth If NPCs chase to a target and end up inside they will move away after a short moment if the target stays stationary. The good old, "oh crap I went too far" move*. I'm very confident that's the move the pet pulls in the movie and it's not the chase behind thing. After all, the pet went straight away from the Warlock, ending up at his side, not behind him.

\* Which does not exist on Corecraft yet, maybe I should open an issue about that.

**Comment by ccshiro** [comment]
Check 7:00 in @SuddenDeath's video. The VW is on the warrior, and the player commands it to attack the Paladin. It goes a direct path to the Paladin and does not run to his back, but end sup facing him fairly heads on. I think if anything that video proves it shouldn't happen vs players.
