### ISSUE TITLE
Pathing issues on Blade's Edge Arena ropes

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#314]
Pets having some trouble pathing across the ropes, most notable at 0:14-0:19 in the video
http://webmup.com/a0c5a/

**Comment by ghost** [comment]
new grid system - improved algorithms. xDDD
shiro, what you do not like the implementation of mangos grid?

ps g00gle translator

**Comment by ccshiro** [comment]
I've resolved this issue by changing some pathfinding behavior. We think the changes will make pathing more retail-like, but it'll need some testing. Keep your eyes open for strange pathing behaviors next test, as this change might cause some.
