### ISSUE TITLE
[Talent][Minor] Anger Management continues to give rage after combat

### ISSUE THREAD

**Issue by braide** [ccshiro/cc-buglist#318]
As the title says the Arms talent of Warrior "Anger Management" continues to give 1 rage every 3 seconds even when you're not in combat anymore. The tooltip clearly says that you only get 1 rage every 3 seconds while in combat. After about 30 seconds out of combat Anger Management stops. Happened everytime I entered combat.

The 1 rage every 3 seconds should stop instantly as you get out of combat.

**Comment by Iliana-sc** [comment]
The tooltip is wrong. This is not a bug.

**Comment by ccshiro** [comment]
As @Iliana-sc said this is not a bug, just the tooltip being wrong in Vanilla and TBC.
