### ISSUE TITLE
Missing Mob in Shattrath

### ISSUE THREAD

**Issue by bjplunk** [ccshiro/cc-buglist#319]
The mob shown in this video from retail was missing on the test server.
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Chulain** [comment]
you fucking faggot

**Comment by Sakatoro** [comment]
Movie is blocked for Germany -.- :/ Ps: Sounds like a minor bug

**Comment by ccshiro** [comment]
God damn you @bjplunk.

**Comment by bjplunk** [comment]
Github needs a like function.
