### ISSUE TITLE
Interrupting NPC spells

### ISSUE THREAD

**Issue by Zataron** [ccshiro/cc-buglist#320]
I interrupted the frostbolt of Coilskar Siren (19768) with Pummel. The NPC started casting a new frostbolt instantly, even though it should not be able to cast a spell from the same school for several seconds.

**Comment by ccshiro** [comment]
You can blanket silence the mob, preventing him from casting water bolt. However, his water bolt itself is non-interruptable. Therefore it sounds strange that you would've been able to interrupt it at all. When testing with pummel in game it works as intended; i.e. I can't interrupt it.
