### ISSUE TITLE
Incorrect mob pathing behaviours in Azeroth

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#321]
I don't know if pathfinding is deliberately disabled in the old world, but I encountered two major issues there.
1. When disengaging the mobs, instead of leashing back to their original position, mobs got stuck in the position where they dropped combat and started evading. In this example there's a number of mobs right on [top of each other](https://cloud.githubusercontent.com/assets/1533992/6944871/e4618c52-d89e-11e4-9c46-128a8dd5b954.png).
2. Mobs are often unable to find a path to the player if there is any sort of obstacle in a way (a door, 
   [the cauldron platform](https://cloud.githubusercontent.com/assets/1533992/6944991/5d945a14-d89f-11e4-92a3-263849a517ed.png) etc.)

**Comment by Wtfeater** [comment]
Quite Possibly related to this report:
https://github.com/ccshiro/cc-buglist/issues/283

**Comment by Iliana-sc** [comment]
I think this is a bug in the mob AI and not related to pathing. Default mangos mob AI is terrible and they get stuck all the time (oom, los, etc).

**Comment by ccshiro** [comment]
This is indeed not a pathing but, but an AI bug. This affects too many mobs to solve it, but Nim will be able to fix it over time as he fixes Vanilla content.
