### ISSUE TITLE
Possible issue with old world chest loot tables

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#322]
I know old world content isn't any kind of priority (as such I've refrained from reporting issues on quests or mobs) but depending on the actual severity of the issue, this one might affect the game experience to a degree that could perhaps warrant attention.

While doing various other tests, I encountered a chest, which turned out to 
[contain](https://cloud.githubusercontent.com/assets/1533992/6945247/0752e678-d8a1-11e4-89fa-4cce32953c24.png) several recipies and green items (all of them aren't visible in the picture). Perhaps this was a huge stroke of luck, I was unable to go and find other chests during the test, but if this kind of loot from chests is the norm (never mind if green or blue items tend to drop instead of recipes), players could get a not insignificant gold advantage by making additional accounts to camp these chests with, especially if there happened to be related issues like chests respawning at server restarts (another possibility I was unable to test).

**Comment by ccshiro** [comment]
The core loot selection system has been fixed to be able to fix this issue with. The data still needs to be filled in for the system to take effect. I've created a new issue for that: #421.

In other words, it won't be fixed yet, but we now can fix it.
