### ISSUE TITLE
Quest - Western Plaguelands - Defiling Uther's Tomb

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#323]
When using the quest item, Uther spawned, but you don't get quest credit (you're supposed to receive credit immediately after using the item) and the RP doesn't work (the NPC just walks around).

You can see the correct behaviour in this video: https://www.youtube.com/watch?v=lDynaDtPw6k

**Comment by nz54445** [comment]
....and as such we have left Vanilla questing in its default state. This means that Vanilla content can be progressed through, but does not provide our level of perfection. For example, most RP events, and a great deal of scripted quests (such as escort quests) are non-working. 

Should be flagged for vanilla content.

**Comment by ccnim** [comment]
Will get around to this if we have the time to otherwise it will be left as default.
