### ISSUE TITLE
Quest - Western Plaguelands - All Along the Watchtowers

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#324]
Using the provided quest item did nothing (we tried several positions, inside the keep, right at the entrance and further outside and none of them worked), at least in one of the towers (I believe it was the Northeastern one).

As seen in the video https://www.youtube.com/watch?v=an7TcjJt-ac (first time around 1:00), using the quest item gives credit instantly, displays an animation and some sort of smoke flare appears inside the tower. In addition, depending on what patch version is targeted, the mobs inside the towers were elite up until 2.3 patch (http://www.wowhead.com/quest=5098/all-along-the-watchtowers#comments:id=209261), currently they are non-elite.

**Comment by nz54445** [comment]
....and as such we have left Vanilla questing in its default state. This means that Vanilla content can be progressed through, but does not provide our level of perfection. For example, most RP events, and a great deal of scripted quests (such as escort quests) are non-working. 

Should be flagged for vanilla content.

**Comment by ccnim** [comment]
Will get around to this if we have the time to otherwise it will be left as default.
