### ISSUE TITLE
Bonestripper Tail Feather seem to be dropping too often

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#326]
Bonestripper Tail Feather ( http://www.wowhead.com/item=23387/bonestripper-tail-feather ) for the quest Trueflight Arrows ( http://www.wowhead.com/quest=9381 ) seems to be having ~80-90% droprate while it should be lower. According to the wowhead the droprate is 38% and even if it was changed since tBC I'm absolutely sure it couldn't decrease. Also there is a comment stating that they drop seldom.
Thus, the current droprate is too high.

**Comment by zixsen** [comment]
Not questioning the drop rate on this quest, but isn't it hard to determine droprates by % from wowhead? Wont it be showing incorrect values from people killing them without the quest? Or will the feathers drop for people even without the quest?

**Comment by netherspite** [comment]
Well, AFAIK, droprates = 80% for almost all the quest items in stock MaNGOS. Most of them are incorrect.
Second, I remember this quest taking way more time to complete on retail.
Third, there is a comment on wowhead stating that the droprate for those is low. While exact percent from the wowhead may be wrong, I doubt people would call 80% droprate low.

**Comment by ccnim** [comment]
I lowered it a bit.
