### ISSUE TITLE
Raging Colossus in HFP keep dropping Crimson Crystal Shard after I took the Q

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#328]
Raging Colossus in HFP kept dropping Crimson Crystal Shard (the item starting the quest) after I already accepted the quest. And even after I turned it in. I could loot it but couldn't take the quest from it.
![wowscrnshot_033115_221705](https://cloud.githubusercontent.com/assets/5777848/6951739/24fe8f18-d8c6-11e4-8bfc-743d32404348.jpg)

**Comment by ccshiro** [comment]
@ccnim Should be fixable now, use quest none as the condition.
