### ISSUE TITLE
Auto-attack on ability usage

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#35]
"Upon activating a skill on a rogue, the auto swing hits before a skill does. The swing timer should start after you do a skill on a neutral target."

Daeghan, the original reporter, pointed out to me that if you run up to a low level neutral mob and use Sinister Strike (for example) on it, the mob will die from auto attack. That made me very convinced somethings going wrong. The bug happens because SS is queued in the spell queue, whereas auto-hit is executed right away.

That made me wonder what actually happens. Is there some initial delay on the first auto attack? If so, how long is it? Or is it bound to spell delay somehow as well (this goes against our current understanding, but might be a possiblity as well)? I realize this is a difficult to determine topic (single frame stepping through rogue pvp videos might be one way to approach this), but any help would be much appreciated.

**Comment by Lobogo** [comment]
Ok, i dont know how much help this gona be, but on current retail it works exactly this way.
Your white hit is first, after that sinister strike (or whatever) hits. Funny thing is, if you do this on critter or low lvl mob, your white hit kills it, sinister is not even in combat log, but you get the combo point (might be just some stupid WoD change though)

Now, from what i remember during my early retail days, i could hit critters with yellow damage, meaning that SS hit first at that time, or auto was delayed.
http://imgur.com/OWeqciT for the retail pic.

**Comment by Barroth** [comment]
Ît could be quite possible that the first autohit has the same +500ms delay as the first autoshot to fit its animation. I've found after using charge the first autohit the warrior does is delayed by ~800-900ms. 
Taking spell delay into account, it may be very well the +500ms for the first hit. Gonna see if I find some videos showing it without charge.

**Comment by plebbb** [comment]
I would be leaning towards there being a delay on the initial auto attack, as I always destroyed critters while playing on a rogue just to see some big numbers.  The reason I believe there is a very slight delay is because I would bind /startattack to precede my yellow abilities in a macro:  Half of the time the critter would be hit by my special ability, and the other time he would die by auto attack before the special would connect.  Another example would be an ability where I did NOT apply /startattack to, Ambush, sometimes auto attack connected before the ambush actually hit.

**Comment by tedrasiel** [comment]
it works as intended. im absolutely shure, cause much of my time in front of og was used killing pigs back then, and snakes and all this shit, while waiting for someone to duell or a Bg to pop up. when going onto a mob with rightclick and running into range while spamming some bind for whatever melee attack spell, the whitehit kills it first. that also happened when targeting it with leftklick. but u could trick it by getting your rogue in a position where you 're able to use a spell, but turn your character as fast as possible to avoid autoattacks. only works with left klicking the target. was also used in pvp ( garotte + bleeding without breaking sap on target).

**Comment by Barroth** [comment]
I've done some frame to frame testing on the Pat PvP 3 Warrior video https://www.youtube.com/watch?v=HnUSYSjoRTk

Those are the results I've got:(Time to first autohit after toggling it on:)

![image](https://cloud.githubusercontent.com/assets/9391338/5424410/5c2dc4be-82ee-11e4-9408-a32f89cac1aa.png)

Those are warrior only though, gonna add some more for rogues later

Edit: Rogue results, match the warrior ones.

![image](https://cloud.githubusercontent.com/assets/9391338/5425238/9ce443be-830e-11e4-8930-8384be79a700.png)

So it looks like there should be an initial +500ms attacktimer upon starting autoattack, which goes inline with the +500ms attacktimer the hunters auto shot gets on the first shot.

**Comment by solowt** [comment]
Part of the difficulty in testing this is that yellow attacks have a slightly larger range than white attacks.  So if you run up to someone spamming a yellow, the yellow should go off first because it gets into range earlier.  But if you're right on top of them and you start a yellow, I believe you'd see the white first.  That's my recollection anyway.

**Comment by Raiilan** [comment]
When attacking a critter/low lvl mob outside orgrimmar i would like to remember that 2 out of 5 times a white attack killed it and the other 3 times the Ability damage killed it.

(i have always thinked it seems strange that the "yellow" damage didnt show up on the screen and in the combat log sometimes)

**Comment by Barroth** [comment]
Looking closer at it, it looks like it should be delayed as soon as you're out of meele range. there are some videos showing that, for example http://www.warcraftmovies.com/movieview.php?id=28533 . You can see the player walk away from its enemy some time, having autohit enabled and when he gets back into meelerange it takes a while until it hits.
