### ISSUE TITLE
Grounding dispels

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#36]
This question is partially based on a report, but I made it a tad bit broader.

Questions:
Should multi-purpose dispels (e.g., dispel magic, devour magic) by groundable by grounding totem **when used on a hostile target**?
Should offensive dispels (e.g., purge) be groundable by grounding totem?

**Comment by Barroth** [comment]
https://www.youtube.com/watch?v=UI2ci2s7Hrs#t=204 Shows how purge gets redirected to the totem. The enemy shaman casts "something"(bad quality cant really see it) and the grounding totem vanishes. And 2sec after he uses earth shock, meaning the "something" had to be purge since purge/shocks are the only instant ranged spells.

**Comment by solowt** [comment]
Shaman friend says ground works on all of these things.

I recall ground working on a mage's spellsteal.  My understanding is that it works on any targeted spell.

**Comment by fishworld** [comment]
http://www.wowblues.com/eu/bug-dispel-effects-3778918160.html

This is a post from 2008, and it seems indeed like Grounding Totem should eat the dispell. However, Purge/dispel both remove 2 effects, so does that mean the grounding totem will only eat 1?

**Comment by solowt** [comment]
That seems really unintuitive to me.  Entire spells get redirected to grounding totem.  There's no mechanic that I'm aware of that would somehow split the purge between two targets.

**Comment by tedrasiel** [comment]
i played shaman as my main through the whole of bc. grounding takes it all, pruge, spellsteal etc. and it takes purge as the whole spell, so its not splittet up. it takes any spell that needs an enemy target and it takes things like freezing trap of hunters too. thats why "clever" shamans didnt put any buffs up in shaman vs shaman duells, so the other shaman could not remove it via purge but had to kick it manually (autoattack) or with a shock, which again gave the other shaman an advantage.

**Comment by tedrasiel** [comment]
http://www.warcraftmovies.com/movieview.php?id=73041 its in s3, so not 2.4.3 , but the grounding mechanic hasnt changed. i was to bored to look for an exact time to show how it works, but there should be more than one examples to show that im right. quality is quite good too

edit: i watched it cause i love it and found proof. 4:50 -5:00.

**Comment by ccshiro** [comment]
Thanks for the input, should work as intended now.
