### ISSUE TITLE
Pathing: zigzagging does not make mobs slower

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#37]
Zigzag kiting monsters does not work. I doubt this has been reported before because few people realized it existed even on retail and it was fixed in later expacs, and it also never worked on a single private server as far as I can tell, but lately I was able to recall discussions on the subject from the Noggaholic community back in the day. I could no longer find the boards or the discussions, however.

The correct way for zigzag kiting to work would be that when a player, being pursued by a mob, quickly strafes left and right, switching directions all the time, the monster should repeat these movements but slightly slower, making the monster (in most cases) fall behind in run speed.

Proof? Difficult to find. These are very poor sources, but here's one mention (from 2009): http://www.wowguider.com/?p=29 . Wowwiki may also mention it, unless it means something else (this was written in 2008): http://www.wowwiki.com/Combat?oldid=1657206 - "Quickly strafing (sidestepping) left and right while running away will make it easier to escape mobs in pursuit."

Videos are difficult to come by. I personally remember going through the whole of Eastern Kingdoms without dying as a low level utilizing this technique in high level areas, but that's not much for evidence. Maybe somebody else can find more proof.

**Comment by huggarn** [comment]
Holy grail of kiting

**Comment by ivanprgin** [comment]
ye it was on retail. Best thing while lvling :P

**Comment by Bearmanpig** [comment]
Sounds like this might be related to the mob chase mechanic #548

**Comment by ccshiro** [comment]
Mob chase mechanic has now been reimplemented to work as it did & does on retail.
