### ISSUE TITLE
Entering wrong instance as ghost

### ISSUE THREAD

**Issue by DennisPuetz** [ccshiro/cc-buglist#40]
When ,as a ghost, entering an instance you did not die in, you get ported back to the graveyard. Happend when entering an instance in hellfire pensuela.
Not sure if bug or i am just not remembering it correctly. If so please delete.

**Comment by Iliana-sc** [comment]
not a bug, that's how it used to work. Don't have any real evidence here, but I doubt this will be a controversial topic.

**Comment by Bearmanpig** [comment]
This is indeed working as intended, though I could not find proof to support this claim. I've had a few wrong corpseruns on retail, and as far as I remember it ported me back to the GY every time. Maybe this can be verified on retail if they haven't removed corpserunning by now.

**Comment by ccshiro** [comment]
This is indeed working as intended.
