### ISSUE TITLE
Zeplin from Undercity to Grom'gol

### ISSUE THREAD

**Issue by Christarp** [ccshiro/cc-buglist#41]
When arriving at Grom'gol, jumped off Zeplin and fell through world killing me. Ended up at Dalaran in the Alteric Mountains.

**Comment by ccshiro** [comment]
I'm unable to reproduce this. However, it sounds on your report as if you were able to jump through terrain or a building with pure movement (as opposed to a spell that relocates you) then that's a client-side bug and not one we can fix. If it's involving only movement with static terrain/buildings the server has no say in how it plays out.
