### ISSUE TITLE
Grey Iron Weapons

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#420]
"Tormus is happy to receive the ore, and grateful for your aid in revenging his mentor. After a short bout of blacksmithing, 
he produces an array of Grey Iron weaponry from the ore you supplied, and offers you a choice from among them." - http://www.wowwiki.com/Grey_Iron_Weapons_quest_chain

I think this implies he's going to make the weapons on the great anvil and that's what I'll make him do for now but if anyone can find a video of this that would be nice.

**Comment by ccnim** [comment]
Found that he uses a say.
$N, I'm finished!

**Comment by bjplunk** [comment]
There is a short cut scene after completing this quest, where Tormus pounds on his anvil a bit, then offers up a Grey Iron weapon.
http://www.wowwiki.com/Quest:Ironband's_Compound
