### ISSUE TITLE
Dead mobs following you (again)

### ISSUE THREAD

**Issue by solowt** [ccshiro/cc-buglist#424]
Same issue as last test.  I noticed a dead wolf and warp stalker following me around and hitting me outside of shatt.

**Comment by Ceziar** [comment]
Lot's of crazy stuff happening after crashes. Here's a video of dead NPC attacking me, dead NPC becoming alive midfight and a gliding corpse.

https://www.youtube.com/watch?v=CoNkvcYKvnE

**Comment by ccshiro** [comment]
Pretty sure this is same as #471. Closing this one as that one has more discussion in it.
