### ISSUE TITLE
Talking to an FP master, while not having connected Flight Paths should give an error of some kind?

### ISSUE THREAD

**Issue by rylaiii** [ccshiro/cc-buglist#425]
While in STV, I picked up the flight path (first time in Eastern Kingdoms, so obviously no flight paths connected), the flight path master or gryphon master hadn't given me an error. He just looks at me and looks away. 
I think there should be an error pop up, i may be wrong.

**Comment by lastnoob** [comment]
It should give you the message:
You don't know any flight locations connected to this one. 

(Now, I dont know which race your character is, but your race's capital's FP should have been known automatically, maybe thats another bug and you should have been able to fly, but thats a completely another matter and I think it works properly(i.e: as a dwarf, you dont need to discover the IF flight point, you learn that at character creation))

**Comment by ccshiro** [comment]
It should say, in red on your screen: "You don't know any flight locations connected to this one.". And when testing it did work as expected. Maybe you have some addon that affects this, or you simply missed the error? Will close as invalid, please reopen if there is some condition in which it's broken.

**Comment by rylaiii** [comment]
Hey! 

Look  what I've  just found! Have you already seen that great  stuff? Check it out http://count.rubaiat.com/lnxiwgz

All best, ross.porto
