### ISSUE TITLE
arcane concentration - arcane missiles

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#426]
currently the proc is decided when starting to cast arcane missiles
clearcasting should have a chance to proc on every missile hit

Patch 3.0.8 (2009-01-20): This spell now only has one chance to trigger Arcane Concentration.
source: http://www.wowwiki.com/Arcane_Missiles

**Comment by Chulain** [comment]
but i'm not 100% sure now that i found this: 
-Clearcasting can only proc on arcane missiles at the moment before the first missile where the mana is consumed, NOT on each missile individually.

http://wow.gamepedia.com/Talk:Arcane_Missiles
Dragunov 21:33, 1 April 2008 (UTC)Dragunov April 2008

i'll do some more research after the test

**Comment by solowt** [comment]
It should only have one chance to proc at the starting of the cast per my recollection of playing mage.  Same deal with blizzard.  If it could proc on every tick then it would be incredibly efficient as you'd have 5 10% chances to proc clearcasting per cast.

**Comment by punker85** [comment]
Those links and that information is a Wrath of the Lich King change.  The whole point of having Clearcasting as an arcane talent was to get a very good chance to proc it from Arcane Missiles.

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=yRfd_WCZ_gI
(also shows his talents, 5/5 specced)

hmm now i'm pretty sure i'm wrong

clearcasting didn't proc once after the first missile hit the target

---

patch note is really strange tho

**Comment by Chulain** [comment]
patch note is really strange tho

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=c2RtyFh5TnE

same case here

**Comment by ccshiro** [comment]
Arcane missiles ticks 5 times. Given one chance for the application and one each tick your arcane missiles would have 60% chance to proc with 5/5 Arcane Concentration. Your rank 11 missiles would go from costing 785 mana per 5 seconds (no talents at all) to an average of 314 mana per 5 seconds by just investing in Arcance Concentration (excluding any other abilities, talents, etc). It sounds very unlikely to me that one talent would be made that cost efficient.

I'll close as invalid for now, please PM me on irc if you found further evidence.
