### ISSUE TITLE
Cannot attack mob #2

### ISSUE THREAD

**Issue by deltafoxnine** [ccshiro/cc-buglist#428]
It seems like(pretty sure it is) the samme issue as i posted on march test: https://github.com/ccshiro/cc-buglist/issues/271

Again, i can provide footage i just have a real slow upload. But it is exactly the same mobs. The aggressive are following, and hitting me while they are dead. And the none aggressive are just floating around.

**Comment by deltafoxnine** [comment]
Here are two videos show the "Ghost mob" and the "Unattackable mob"
https://www.youtube.com/watch?v=CRWLGcOitn0
https://www.youtube.com/watch?v=jizfTFNidAs

**Comment by ccshiro** [comment]
I guess it really was something else then... Hm. I will mark this as a bug and take a look at what might go wrong. Thanks.
