### ISSUE TITLE
Cost for S1 offparts @ hall of champions are wrong

### ISSUE THREAD

**Issue by Sakatoro** [ccshiro/cc-buglist#429]
Im not 100% sure because season 1 is very long time ago, but in my memory the cost for the season 1 offparts were higher.

For example: Atm the NPC sails the season1 feets for 14280honor points. wowwiki said it was 17850honor points.(this was also my memory) 

I found only this from wowwiki: http://www.wowwiki.com/Season_1_Arena_rewards 

I think the cost for the blue set and blue weapons are right and the cost for the s1 offparts are to cheap. 

Perhaps nim registered the s1 offparts from season2. Can someone research this or know it better than me?

**Comment by maxmore031** [comment]
I remember some off pieces were 17850 but I also remember that not all off pieces cost the same.

**Comment by ccnim** [comment]
Try buying it and it will show the real price. The price is client side and although we have changed it, it will still show up as the old price for you.
