### ISSUE TITLE
NPC in the air

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#431]
![wowscrnshot_042015_221650](https://cloud.githubusercontent.com/assets/12034245/7238626/63bfc484-e7ac-11e4-8366-ddc2e71d1a55.jpg)
![wowscrnshot_042015_221656](https://cloud.githubusercontent.com/assets/12034245/7238628/63c5d176-e7ac-11e4-93f6-ccca16813a53.jpg)

**Comment by PolarCookie** [comment]
This happened in arcatraz too, mobs would walk over this point and evade while being in the air.
evasion cleared as they came to the ground

![screenshot-6](https://cloud.githubusercontent.com/assets/1158801/7242426/ab7aa3e6-e7c2-11e4-95ef-346b47b72829.png)
![screenshot-7](https://cloud.githubusercontent.com/assets/1158801/7242427/ab7f305a-e7c2-11e4-9621-4a536c0f24bc.png)

**Comment by ccnim** [comment]
The cause seems to be that mobs slow down as they get low on health.

**Comment by KimmoKM** [comment]
I've noticed this happening from time to time, predominantly on mobs that attempt to flee. An extreme example might be something like the one in included picture, but mobs floating a bit when they die isn't too uncommon.

![2015-08-30-173648_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1533992/9567764/755a4b7e-4f3f-11e5-803b-b25ea6706862.png)

Perhaps this issue should be reopened?
