### ISSUE TITLE
flight master pets

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#432]
the flight master pets (gryphons & wind riders) that spawn when you attack a flight master are neutral and cant be attacked
they should be hostile
proof: https://www.youtube.com/watch?v=9sgbbC4UhyE

**Comment by Chulain** [comment]
they cannot be attacked, 100% sure now

**Comment by Shakeandbake** [comment]
I reported the neutral flight master guards last test but now i can't find the bug i reported...

**Comment by bjplunk** [comment]
https://github.com/ccshiro/cc-buglist/issues/261

**Comment by Chulain** [comment]
yeah duplicate, however i think this should be fixed as the spawned npcs can be really annoying if you cant cc/kill em
