### ISSUE TITLE
Warlock spell: Health Funnel

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#436]
You are able to cast this spell while been not in LoS of your pet, but then the spell will not heal the pet. (even though it keeps channeling). Did not manage to get a screenshot of this nor am i sure what part is the bug. That the spell should have done a los check and failed or that the spell should have healed.

**Comment by ConfusedCC** [comment]
![los healthfunnel](https://cloud.githubusercontent.com/assets/10581981/7247848/28e44abc-e80e-11e4-9da8-99c081f4baf2.JPG)
![los healthfunnel2](https://cloud.githubusercontent.com/assets/10581981/7247849/28e80242-e80e-11e4-80c9-63d310f3b299.JPG)

the spell consumes some health on initial cast when not in los, but then does nothing until the cast completes
