### ISSUE TITLE
Shaman: No aggro from aggressive totems

### ISSUE THREAD

**Issue by deltafoxnine** [ccshiro/cc-buglist#437]
It seems like my totem doesn't aggro mobs, if remember correctly they should attack it(and destroy it)

I have supplied footage: https://www.youtube.com/watch?v=bqFfs1FEtSE

**Comment by rylaiii** [comment]
http://www.wowwiki.com/Magma_Totem
as of patch 3.0.8 magma totem no longer gains threat.

**Comment by deltafoxnine** [comment]
Exactly, so it should still do threat, thx :)

**Comment by ccshiro** [comment]
Tried searing totem and magma totem, the former generates threat as expected. The second one does too, however, for some reason the threat is awarded to the Shaman.
