### ISSUE TITLE
Hunter frost trap

### ISSUE THREAD

**Issue by DaRealBoss** [ccshiro/cc-buglist#438]
When using hunter frost trap on any ground that has a slope or ramp, the visual effect seems very distorted. You can't tell the true range of the trap because the visual looks smaller than usual on slopes, unlike on flat ground. A mob can seem to be walking on un-frosted ground yet is still slowed, because the visual is messed up.

Couldn't find any retail evidence of hunters using frost traps on ramps to confirm, but it just doesn't seem right.

**Comment by Chulain** [comment]
tested on a few spots, they seem fine to me

(last picture is always corecraft)

http://imgur.com/a/WJX54

http://imgur.com/a/DUMAX

http://imgur.com/a/F8ttD

http://imgur.com/a/YoukF

retail version actually looks worse, look how the whole pillar gets affected, dont know if ppl around the pillar get slowed down tho but i doubt it

**Comment by DaRealBoss** [comment]
Ah ok so that orc hunter pic with the trap on ramp is retail? i guess its meant to look that way. nvm then

**Comment by ccshiro** [comment]
The visual is client-side. The server just informs the client where the center is and lets the client figure out the affected region itself.
