### ISSUE TITLE
stormstrike

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#440]
stormstrike visual effect is instantly but the dmg is delayed
it should be instant

evidence: https://www.youtube.com/watch?v=ZZGCUTW2_Ag&feature=player_detailpage#t=20

how it currently works: https://www.youtube.com/watch?v=zoAmM2fNd9Y&feature=youtu.be

**Comment by tedrasiel** [comment]
when ive seen it correctly, the same goes for Mutilate.

**Comment by Chulain** [comment]
sorry, forgot to add timestamp to evidence
