### ISSUE TITLE
mysteries of the light - quest (item)

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#443]
the object respawn timer is 3mins, i'm not sure but I think it's too long? 
you only need one quest item for the Q.

i've read all comments but i couldnt find anything about the respawn timer
http://www.wowhead.com/item=25938/mysteries-of-the-light

**Comment by ccnim** [comment]
Lowered it. If you find any other quest items with a long respawn timer, report it and I'll lower it.
