### ISSUE TITLE
Level 70 Elite Tauren Chieftain missing from the balcony Silvermoon

### ISSUE THREAD

**Issue by Jigodian** [ccshiro/cc-buglist#445]
Taken from http://www.wowwiki.com/Elite_Tauren_Chieftain

The Tauren Chieftains can be found at rest in Silvermoon City's Walk of Elders on a balcony overlooking the walk. Their stage manager and stage tech, Michael Schweitzer and Roitau respectively, both sit below the band. Their purpose in Silvermoon City was initially uncertain, but it has since been learned that the band is placed there as part of the Children's Week quest chain for Horde players, which begins in Shattrath City. Performing emotes to them, such as cheer, will cause them to respond in turn. The band and their manager remain friendly to Alliance players and will still respond to emotes.

http://i.imgur.com/CECGqFn.jpg

Also they are supposed to have concerts in World's End Tavern and Grim Guzzler every night at 8 PM server time.

The virtual incarnation of the band, The Tauren Chieftains, perform "Power of the Horde" inside the World's End Tavern in Shattrath City every three hours on the hour, eight shows per day. Several minutes prior to their show, Shattrath Saul will announce the band's upcoming performance. In addition, every night at 8:00 PM server time, The Tauren Chieftains perform a five-minute concert inside Blackrock Depths' Grim Guzzler. Anyone who has Direbrew's Remote from the Brewfest event can trigger a performance here at any time by talking to the roadie in charge, Ognip Blastbolt. As of Patch 4.3.0, the band now also performs at the Darkmoon Island during the Darkmoon Faire at the top of every hour.

Some youtube links:

In World's End Tavern: https://www.youtube.com/watch?v=CoKJymWSbII
Grim Guzzler: https://www.youtube.com/watch?v=U1QdWMjKdZc

**Comment by Sakatoro** [comment]
Omg, why people report something like that...cant understand

**Comment by Jigodian** [comment]
Why not? It's not something very important but it would be cool to have these features in the game.

**Comment by honuk** [comment]
wow I legit had no idea they performed in BRD that's hilarious.

**Comment by ccnim** [comment]
They were not in the game in 2.0.3.
