### ISSUE TITLE
Teleported out of the map randomly while playing

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#446]
Happened 3 times during the test, 1 time in arena while playing & 2 times outside of arena when I was alt tabbed. Seemed to be completely random.

When in arena: http://webm.land/media/5YGJ.webm

**Comment by ccshiro** [comment]
I have a feeling this is gonna be fun to debug. Looks lovely, though.

**Comment by tedrasiel** [comment]
could this be linked to the view distance? 

My screen freezed for multiple seconds inside the arena more or less randomly while having a superior setup. Some guy I was queued with , told me to lower viewing distance and it worked fine. 

I guess its something else this time, but for some reason i was thinkin about this other issue while watching the footage. Just in case it helps someway.

**Comment by ccshiro** [comment]
I think the webm might've expired, mind reupping it somewhere more permanent?

**Comment by Klimpb** [comment]
@ccshiro Updated, hopefully this one will last longer

**Comment by nz54445** [comment]
When you guys manage to debug this problem, you should take a look at #43 and #137, both of them are falling through the world issues (especially #43, since it does not seem to require a fear effect) and see if the bug can be reproduced there by the same steps. Maybe the same solution solves all three problems.

**Comment by ccshiro** [comment]
We can't figure out what happens. We will add some debug that triggers if you're teleported like that again, and hopefully it happens next test.

**Comment by flerbu** [comment]
please i want that ui.:O

**Comment by ccshiro** [comment]
Haven't had any triggers on this, I'm guessing the bug is gone? Still no clue what it was. If it happens again, you can reopen the issue.
