### ISSUE TITLE
Felhunter spell Paranoia is not auto-casting when it is on auto-cast.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#447]
Noticed it a quite a lot in arena games and I had to cast it manually.

EDIT: same with imp's Fire Shield and succubus Lesser Invisibility

**Comment by ccshiro** [comment]
Testing I noticed that:

Paranoia is not being cast until you get in combat.
Lesser Invisibility doesn't seem like it wants to get auto-casted at all.
Fire Shield seems to work correctly (maybe you have some more info on what happened prior to this one?).

**Comment by Klimpb** [comment]
@ccshiro Well I don't know much about fire shield except for the fact that it has a auto-cast function to it, which I then assume it should just keep you and/or your party buffed with it and re-applying it when it fades away.

or am I wrong here?

**Comment by ccshiro** [comment]
@SuddenDeath Yeah, it applies fire shield on any party member that gets struck. So if something melees you or anyone in your party the auto-cast will trigger.
