### ISSUE TITLE
Royal Theromoths near Shattrath, in terrokkar are bugged

### ISSUE THREAD

**Issue by lastnoob** [ccshiro/cc-buglist#449]
![wowscrnshot_042015_235645](https://cloud.githubusercontent.com/assets/1821091/7241403/fa27d496-e7b8-11e4-8bf5-8a527587fabc.jpg)
They cast a spell Wing Buffet, but they actually charge away from you to do that. Then they "meele" hit you from like 25 yards.

**Comment by rylaiii** [comment]
video provided by Ceziar - https://www.youtube.com/watch?v=CoNkvcYKvnE
happens at 1:15
