### ISSUE TITLE
One of the mobs in Funggor Cavern has pathing issues

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#451]
When you pull this mob from the upstairs he does not come to you and evades instead.
![wowscrnshot_042015_210735](https://cloud.githubusercontent.com/assets/5777848/7241740/8a589a36-e7c4-11e4-8592-2c4ce5f6e4a6.jpg)

**Comment by Lantv** [comment]
confirmed, he doesn't seem to be in the floor as I was able to hit him just fine when I walked up to him, but when I moved away and tried to kill him at range he started to evade again.
