### ISSUE TITLE
Problems with Withered Giant's Osmosis ability

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#452]
It seems like the Osmosis ability of the Withered Giants in the Dead Mire does not work.
They channel it and there is casting animation but it does not seem like damaging me or healing him.
May be it just has very small radius though, I wasn't able to get damaged by it at ~8 yards or so.

**Comment by rylaiii** [comment]
according to wowhead, the range should be 20 yards.
http://www.wowhead.com/spell=35235/osmosis

**Comment by ccshiro** [comment]
I was level 70 and got it resisted over and over, then I levelled down to 62 and the spell seems to work fine.
