### ISSUE TITLE
frost trap

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#454]
If an enemy stands in your frost trap aura you will remain in combat till he moves out of it. (you will re enter if he moves in again)

Pretty sure this is wrong, I'll look for evidence if you want.

**Comment by ccshiro** [comment]
That does sound very wrong, yes. Although having a video to prove it wouldn't hurt (so there can be no future debate how it should be :p). If it's not too much trouble finding something, that is.

**Comment by Chulain** [comment]
couldn't find anything
