### ISSUE TITLE
Weird mob behavior - Cabal Acolyte in Shadow Labyrinth

### ISSUE THREAD

**Issue by kikomir** [ccshiro/cc-buglist#459]
In the first room of the dungeon, at the end of the room to the left of the door(hallway?) leading to the next one...right next to the bonfire. After being pulled from a range, one of the Cabal Acolytes was stuck in place, clearly targeting a player but not moving to attack him for a long period of time. Happened after a Distract so that _might_ have something to do with it. This happened in heroic difficulty. Hopefully someone can reproduce or confirm.

**Comment by ccshiro** [comment]
Unable to reproduce. Next test we will have a new method of reporting mobs being stuck (so we can more easily debug what happens). If you see this bug again next test please create a new issue at that point.
