### ISSUE TITLE
Mage Blink

### ISSUE THREAD

**Issue by somnu** [ccshiro/cc-buglist#46]
Mage blink seems to be bugging, especially when fighting a player and blinking through him as he casts a spell on you. This sometimes results in the enemy player being force-turned to face you. 

I noticed this best when dueling another mage on my mage, as we were blinking through eachother trying to avoid one-another's hardcast spells we noticed that somehow although we blinked way before the spell was completed, the "casting mage" automatically had his camera-yaw turned towards the "blinking mage". 
Again this behavior is not normal, I have dueled hundreds maybe thousands of times, and I am aware when somebody turns willfully, besides I talked to others, and they experienced the same issue.

**Comment by somnu** [comment]
Apparently the random turning in player camera yaw isn't something necessarily related to blink, it just happened when i was attacking or being attacked by a hunter and his pet...

**Comment by netherspite** [comment]
Happened to me when I was not even in combat. Just was randomly circling around Thrallmar iirc.
