### ISSUE TITLE
Stuck point on aldor's rise

### ISSUE THREAD

**Issue by lorino** [ccshiro/cc-buglist#461]
I get stuck in this point of the map
http://gyazo.com/7515acca28560ed66af8752826c44fca
In this place 
http://gyazo.com/a12b7536f7e43fe8cac56190c6173301
And this is the recreation
http://gyazo.com/8fc6aca31da376eebd7fce7c51818b27

**Comment by ccshiro** [comment]
This is completely client-side and not a bug. Or rather, the bug is within the client so it happened on retail 2.4.3 as well.
