### ISSUE TITLE
cheap shot and abilities that require you to be behind them

### ISSUE THREAD

**Issue by tedrasiel** [ccshiro/cc-buglist#462]
it was reported last test allready and this time it works for kidney and solar. still doesnt work for cheap shot on mobs in front of shatt. 

edit: it tells you to attack from behind, while beein behind. in fact u have to move around them (or through them) and use these abilitys into their face (modelvise).

**Comment by Aasamath** [comment]
Still having that problem (on rogue at least) when using cc to open mobs.
No problem though when stunning mob during combat, it's just the opener.
https://www.youtube.com/watch?v=_Wd79ANeHZ8&feature=youtu.be
