### ISSUE TITLE
[Quest] The Vengeful Harbinger - not possible to complete

### ISSUE THREAD

**Issue by Chillbringer** [ccshiro/cc-buglist#465]
After killing all mobs that spawn, including the Harbinger, a Draenei Tomb Guardian should complete the ritual and the quest should be done. Instead, he disappears after a while and the quest is not possible to complete.

**Comment by rylaiii** [comment]
video of it being done (just in case) : WARNING : LOUD

https://www.youtube.com/watch?v=J4OXliKrVco
