### ISSUE TITLE
Mobs after being Cc

### ISSUE THREAD

**Issue by Poe123** [ccshiro/cc-buglist#466]
While doing heroic ramparts, after CCing a mob they would stand still and not attack. If i recall it was after a sap one time. Happened multiple times throughout the instance.

**Comment by rylaiii** [comment]
similar - #459

**Comment by ccshiro** [comment]
Unable to reproduce. Next test we will have a new method of reporting mobs being stuck (so we can more easily debug what happens). If you see this bug again next test please create a new issue at that point.
