### ISSUE TITLE
Warlock "Health Funnel"

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#47]
A warlock can die from the spell Health Funnel, but after that he can move and resurrect immediately where he is, and without any durability loss. Is that normal ?

**Comment by Whatsthis880** [comment]
In top of that, my pet doesn't die which can gives a situation like this one : http://snag.gy/k22zd.jpg

**Comment by nz54445** [comment]
Would like to add to this, as a priest the shadowfiend pet did not despawn when i died and had him out: http://pbrd.co/1wiMwfB

I don't know if this is correct behaviour or not, but i think all pets should despawn after you die.
