### ISSUE TITLE
Frost trap on Laughing skull legionaires in BF Heroic bug.

### ISSUE THREAD

**Issue by bnee** [ccshiro/cc-buglist#470]
Frost traps sometimes does not slow the Laughing skull legionaires.

Even on the trap they drop the slow for a short duration and will then get slowed again.

**Comment by rylaiii** [comment]
similar : #466

**Comment by rylaiii** [comment]
similar - #468

**Comment by ccshiro** [comment]
Since I close the linked issue I assume I fixed this? Can't remember really, but since there's been no input for quite some time now I'll assume this issue is gone.
