### ISSUE TITLE
[Sethekk Halls] Sethekk Guard Thunderclap damage

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#472]
Thunderclap (spell id #33967 on current version of Wowhead) from Sethekk Guards in heroic Sethekk Halls does about as much damage as a warrior character's thunderclap.  I believe it should be doing something in the range of 766 to 900 nature damage (or maybe more if this was ever nerfed).  Wayback Machine versions of this spell id on Wowhead report 70-79 damage but this is probably erroneous reporting.

**Comment by rylaiii** [comment]
wowhead has the dmg output to be 766-900. 
http://www.wowhead.com/spell=33967/thunderclap
not sure if this'll help : https://www.youtube.com/watch?v=6dr_ssJ5KWo
at 1:19 the tank gets hit with a thunderclap for 595. and another at 1:40 for 600.

**Comment by punker85** [comment]
On http://www.wowwiki.com/Sethekk_Halls (even in history), in the walkthrough section, Sethekk Guard is reported to have 1.7k damage for Thunderclap on a comment.  However, this might be misinformed.

Edit: I just realized the combat log on the video reports the damage as Nature damage.  Maybe it was changed from physical damage to nature damage at some point.
