### ISSUE TITLE
[Sethekk Halls] Sethekk Prophet spams its fear ability

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#475]
In heroic mode, the Prophets in Sethekk Halls continually use their fear ability (spell id #27641) multiple times within a period of 30 seconds.  The fear seems to not have a diminishing return either when it becomes recast on a player.

**Comment by ccnim** [comment]
That is the intended behavior.

**Comment by punker85** [comment]
Is it intended to have only 2-4 seconds of uptime to attack for every 6 seconds (full duration) of AoE Fear?

**Comment by meowmewo** [comment]
ah TBC, where u had to CC the mobs in dungeons.

**Comment by nz54445** [comment]
Tremor totem should work nicely here then? Otherwise CC and kill last.
