### ISSUE TITLE
[Sethekk Halls] Sethekk Spirits missing Spirit Burst AoE

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#476]
In heroic mode, the Sethekk Prophets summon a Sethekk Spirit that should be hitting any non-tank characters for 10% to 20% of their life on a slow attack speed timer.  When an attack lands, an area of effect spell should activate that does 700+ shadow damage to nearby players.  Instead, it seemed to be hitting our paladin healer with all plate gear for more than 3k damage at times and sometimes you could see/hear it swing and would do no damage at all.  The AoE spell was never cast though.

**Comment by ccnim** [comment]
The AoE spell is a proc on his auto attack and it has the spell for me on both heroic and normal.

**Comment by punker85** [comment]
I believe it should be casting that AoE with each attack though.  It is either not PROCing on every attack or the radius is too short.  I was standing withing 10-15 yards of my healer whenever he would get hit and didn't notice any auxiliary damage coming my way.  Also, I mentioned the actual damage that it does seemed a bit high.  I've read notes claiming it hits for about 1k damage on plate and crits for 2.5k on leather.  However, it was mauling our paladin healer for about 3k+ in some cases.  Please keep a watchful eye and monitor the damage.

**Comment by ccnim** [comment]
The damage and radius is from a DBC. It hits for around 500-600 dmg + the auto attack damage which is 2.5k~ shadow damage.
