### ISSUE TITLE
[Paladin] Vindication

### ISSUE THREAD

**Issue by loganbunny** [ccshiro/cc-buglist#479]
On retail TBC all raiding ret paladins would spec 1/3 into vindication because although most bosses were immune, the immune "hit" of vindication (where the text immune would pop up) would proc Judgement of Wisdom mana restoration chance on hit.

**Comment by Philosophers** [comment]
I also do recall such thing. Was looking for evidence, found this (quote from wowhead):
"It works on most raid mobs (trash) but never on any boss. the real reason to take vindication 1/3 is because its procs can proc other abilities or effects. For example a vindication proc (even on an immune mob) adds a count to darkmoon card: crusade."

**Comment by CCjudgement** [comment]
I remember this as well and if Vindication has a chance to proc Judgement of wisdom then it would be being treated as an attack, this would mean any abilities and items which are based on attacks such as Seal of Command, Seal of Righteousness, Hand of Justice and Romulo's Poison Vial should also proc off vindication which are controlled by the 0.5 second internal cd which each of these possess to ensure they dont proc off white swings which are causing vindication to occur and in turn may proc these effects as a of the swing.

**Comment by ccshiro** [comment]
@Philosophers that's a good start. We'd like some more proof if possible for this one, so we can be sure how it worked and why.

**Comment by Philosophers** [comment]
It's very hard to find evidence, I found only one thing in Italian (hic!) guide to retribution paladins 2.4.3. Using google translate:
"Justification 1/3 useless on bosses, but allows you to proc the judgment of wisdom."

Talent name was also transleted, it should be vindication, but I paste what I've got. A lot of guides do not talk about vindication, cause it's "PvP talent", but I guess this comes from little knowledge. I will continue looking, but I've spent enough time at this for today.

**Comment by CCjudgement** [comment]
Trying to find as much evidence as i can that the trigger is a physical attack and the effect creates a magic effect.
Trigger(Physical): 
http://db.valkyrie-wow.org/?spell=26021
http://wotlk.openwow.com/?spell=26016
http://www.wowhead.com/spell=26016/vindication

Effect(Magic): 
http://db.valkyrie-wow.org/?spell=26018
http://wotlk.openwow.com/spell=26017
http://www.wowhead.com/spell=26017/vindication

Trying to find as much evidence as i can that Vindication procced on hit effects.

Discussion about Vindication proccing JoW/JoL:
http://www.wowhead.com/forums&topic=18459/vindication

Discussion about Vindication proccing JoW/JoL:
http://forum.rpg.net/archive/index.php/t-381210.html

Discussion about Vindication proccing JoW/JoL:
http://translate.google.com.au/translate?hl=en&sl=fr&u=http://forums.wowmania.fr/index.php%3Fpage%3DThread%26threadID%3D19155&prev=search

Discussion about Vindication proccing JoW/JoL:
http://translate.google.com.au/translate?hl=en&sl=fr&u=http://www.rage-inside.fr/2013/06/retribution-paladin-theorycrafting.html&prev=search

Discussion about Vindication proccing JoW/JoL:
http://www.mmo-champion.com/threads/621811-Vindication-talent-on-bosses

**Comment by Philosophers** [comment]
From what I saw while surfing internet: people refer not only to judgement of wisdom but also trinkets that grants it's effects on melee hit... It makes me believe that my next statement is true:

Vindication is physical school, so it would rather be considered as melee hit. Ofc link below is post-TBC info, BUT I find no information about changing its school through patches. Will try find more solid proof.

http://www.wowhead.com/spell=26016/vindication

I have question semi-related question: all balance will be 2.4.3 or some crucial elements will be reverted? I don't know where to ask this question to get fast reliable response :)

**Comment by CCjudgement** [comment]
Paladin Raiding with Vindication (watch how many JoW procs occur and how fast (Icon on SCT))
https://www.youtube.com/watch?v=UyooXkH6mT8

**Comment by loganbunny** [comment]
Unfortunately I have little information beyond the fact that I raided as ret during retail and it was fairly widely known that 1/3 Vindication was specced for extra JoW procs. Lots of the ret paladin resources and forums from the time have been lost to the internet over the years. Checking out the wayback machine on archive.org, you could possibly check out cromfel.battlefield.fi which was a notable ret paladin forum/website

**Comment by CCjudgement** [comment]
This was confirmed as a bug and then closed without resolution did this bug get fixxed?
