### ISSUE TITLE
Guard beats dummy (Shattrath City)

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#481]
![wowscrnshot_042115_103629](https://cloud.githubusercontent.com/assets/12034245/7247457/686a4494-e812-11e4-9ff3-c4079fa91b72.jpg)

**Comment by nz54445** [comment]
Duplicate of #169, which was invalid. This should also be marked invalid.

**Comment by ccshiro** [comment]
These dummies are a special construct for the test, and do not exist normally.
