### ISSUE TITLE
[Slave Pens] Bugged Coilfang Technician 

### ISSUE THREAD

**Issue by honuk** [ccshiro/cc-buglist#484]
One of the Coilfang Technicians that pats on the bridge after the first boss evade bugged and disappeared for our group after his pat partner was sapped. It basically flew upwards and intermittently reappeared. We were eventually able to de-aggro and it reappeared and we killed it normally. Our hunter's pet also behaved strangely on the bridge.

**Comment by sandfury** [comment]
to give a clearer picture of what happened

![wowscrnshot_042115_092745](https://cloud.githubusercontent.com/assets/11744594/7330837/60a67b46-eaf7-11e4-905a-07864156dafe.jpg)
