### ISSUE TITLE
[Druid] [Rogue] Energy costs & miss/parry/dodge/block

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#485]
Hi there,
I noticed several inconsistencies in the energy cost reduction that affects missed / dodged / parried / blocked (? not sure about blocked ?) non-finishing moves. So I started testing every scenario and drew several conclusions.

Here is what I gathered :
Ability - normal cost - reduced cost - percentage of reduced cost

Druid :
Ravage - 60 - 12 - 20%
Pounce - 50 - 10 - 20%
Claw (untalented) 45 - 9 - 20%
Claw (talented) - 40 - 4 - 10%
Rake (untalented) - 40 - 8 - 20%
Rake (talented) - 35 - 3 - 10%
Shred (untalented) - 60 - 48 - 20%
Shred (1 talented) - 51 - 3 - 5.8%
Shred (2 talented) - 42 - -4 (it gives 4 energy)
Mangle (untalented) - 45 - 45 - 100% (this one is bugged)
Mangle (talented) - 40 - 40 - 100%

Rogue :

Gouge - 45 - 9 - 20%
Backstab - 60 - 12 - 20%
Ambush - 60 - 12 - 20%
Cheap Shot - 60 - 12 - 20%
Ghostly Strike - 40 - 8 - 20%
Hemo - 35 - 7 - 20%
Mutilate - 60 - 12 - 20%
Ss (untalented) - 45 - 9 - 20%
Ss (1 talented) - 42 - 6 - 14.28%
Ss (2 talented) - 40 - 4 - 10%
Kick - 25 - 25 - 100 % (I think those are bugged)
Sap (untalented) - 65 - 65 - 100%
Sap (1 talented) - 48 - 48 - 100%
Sap (2 talented) - 32 - 32 - 100%
I couldn't get to fail a shiv or a garrote, no miss no dodge no parry, not sure if normal.

There are 3 bugs I can draw out of this :
1. I believe Kick and Sap should have their energy cost reduced when failing to hit, like everything else, however I cannot find any source to support that.
2. Mangle, talented or untalented, should have its cost reduced when failing to hit, there is a source for this, in this post - https://github.com/ccshiro/cc-buglist/issues/433
3. The reduced energy is calculated wrong. I'm assuming it is calculated something like that :
Reduced cost = Current cost - Base cost \* 0.8
This results in
Reduced talented mangle cost = 42 - 60 \* 0.8 --- this means that a failed mangle will cost -4 energy, so it will give back 4 energy, instead of costing 8
Or also
Reduced 2 talented ss cost = 40 - 45 \* 0.8 --- so reduced cost is 4 instead of 8
I have no idea how the code looks but I hope I made my point, and I've no doubt you guys will know how to fix this. I'm also sure you guys will keep in mind that some abilities can also have their cost reduced by a lot of things like items & set bonuses (like how mangle's energy cost is reduced by 5 in the t6 feral set bonus, and some bosses' abilities like Felmyst).

**Comment by Isuel** [comment]
i can confirm for shred, noticed that it actually gives energy back. fun bug
