### ISSUE TITLE
Warlock pets and auto-cast

### ISSUE THREAD

**Issue by effinamon** [ccshiro/cc-buglist#487]
Issue #67 has returned. It occurs both when dismounting and summoning (imp continuously tries to cast blood-pact and the spell failed sound is played).

With the imp, de-selecting auto-cast on fire-shield un-bugs blood pact and it is cast correctly.

**Comment by Philosophers** [comment]
Auto cast on targeted skills like fel hunter devour magic or tainted blood are affected too, but it seems that fel hunter sometimes refuses to use it even after re-toggling it.

**Comment by ghost** [comment]
so if it has returned, reopen #67 , don't need to open a new one

**Comment by effinamon** [comment]
Sure. How do you do that?

**Comment by ccshiro** [comment]
I don't think this is the same bug as #67. The pet does auto-cast these spells, but after you mount and dismount he gets stuck when trying to cast them. At least that's how it appears to me. Will investigate more.
