### ISSUE TITLE
Mobs shown as having back towards you, but unable to use shred

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#489]
If you pounce and stun a target, standing behind it. It still doesn't allow you to Shred the target, as shown in picture. The exact same happens as a rogue trying to use cheap shot, backstab.

<a href="http://imgur.com/aXXcEXo"><img src="http://i.imgur.com/aXXcEXo.jpg" title="source: imgur.com" /></a>

**Comment by ghost** [comment]
#462
