### ISSUE TITLE
[NPC]: Marauding Crust Burster

### ISSUE THREAD

**Issue by Soyoen** [ccshiro/cc-buglist#49]
Hi, the Marauding Crust Burster casts a poison spell which hits between 600 to 800, it felt a tiny bit overboard at the higher damage range so I checked for old comments on the matter and this came up at (http://www.wowhead.com/npc=16857/marauding-crust-burster#comments):

"By ov3rk11l (745 – 3·5) on 2008/10/03 (Patch 2.4.3)  
these things are hardcore for mages, since they have _!@# armor and ^&_! hp, cuz all these guys do is poision, that inflicts 300+ damage, forcing us to use mana sheild. But its k, just as long as u have POM and ur fire specced it shouldnt be too hard,"

300+ damage is of course open for interpretation.

**Comment by Barroth** [comment]
800 is indeed high, but I think it is just the unnerfed 2.0.1 version of the spell :)

**Comment by ccnim** [comment]
This is actually how much damage it did in 2.0.1.
