### ISSUE TITLE
Dr Boom shouldn't have mana

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#491]
Self explanatory he should not have mana
https://www.youtube.com/watch?v=YKXaEjzYDnc

**Comment by Sakatoro** [comment]
This Video is from cata or mop. And it is absolutly wayne, mana or not, dr boom dont use it.....

**Comment by lastnoob** [comment]
https://www.youtube.com/watch?v=rd5GQdlOf4U

This is from 2007, not that this bug matters at all
