### ISSUE TITLE
(quest=10309) It's a Fel Reaver, But with Heart

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#492]
The fel reaver stands up and is animated when it should just stay down while adds come and you destroy it.
Proof:
https://www.youtube.com/watch?v=QzZM10omJxc
https://www.youtube.com/watch?v=Stc-lhpXgrk
https://www.youtube.com/watch?v=AHou5obC-DU

also the adds seem to be coming from the same spot instead of spread out spawns

**Comment by ccnim** [comment]
I'll change it so he doesn't stand up. As for the spawns they are spawning from many different positions when I tried it on the server just now.
