### ISSUE TITLE
[Loot] Mobs in Shadow Labs drops little / no Fel Armaments

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#493]
Mobs in Shadow Labs [HC] still drops close to ZERO (or zero). We again cleared up to second boss, without a single drop. This has to be incorrect drop rates.

Also went to my common farm spot on retail, at he Legion Hold in SMV. 1 hour of grind would usually equate to 4-7 fel armaments, on CC I got zero.

**Comment by Vetinari1** [comment]
In my common farm spot - near Area 52 with demons and fel hunters I got 2 fel armaments after 20 +/- minutes grind.

I can confirm shadow labs info.

**Comment by kikomir** [comment]
Are you talking about normal or heroic? We did Shadow Labyrinth yesterday (I'm guessing that's what you're referring to) on normal and we had plenty of Fel Armaments drop. We did a bit of heroic up to somewhere after first boss and I can't recall a lot of armaments drop...drop rate might be a bit low for heroic but definitely needs to be tested.

**Comment by Ickler** [comment]
Updated the post, it was in heroic.

**Comment by ghost** [comment]
you also said you had problems at Legion Hold, so this is not exclusive to heroic mob drop rates

**Comment by lastnoob** [comment]
Doesn't this apply?
NOTE3: The loot (including common to epic items, that is either an armor or weapon piece)
will not drop during this test due to us revisiting our loot selection system.

source: http://pastebin.com/KPKi6z22

**Comment by ghost** [comment]
it probably does, however needs a re-test once general loot tables have been enabled/fixed
