### ISSUE TITLE
[Karazhan] Issues during attunement quest run in the Master Cellar

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#495]
Hi guys,

I decided to test the Attunement quest for Karazhan:

Arcane Disturbances (http://www.wowhead.com/quest=9824/arcane-disturbances)
Restless Activity (http://www.wowhead.com/quest=9825/restless-activity)

For "Arcane Disturbances" nothing to say, it works as it should.
Restless Activity has a correct drop rate of the quest item (www.wowhead.com/item=24480/ghostly-essence)

but the issue here is that when you gain the amount required by the quest (10) you should stop looting them. This screenshot has ben taken after quest turn in.

![gostly essence](https://cloud.githubusercontent.com/assets/10872722/7250980/02aeb2ec-e827-11e4-8aa2-b3eedadeda2c.jpg)

I also found a pathing issue with my pet inside the Master Cellar in my way to complete Arcane Disturbances. Here is the Screenshot of the incorrect path:

![pet pathing](https://cloud.githubusercontent.com/assets/10872722/7251018/5aa17dc2-e827-11e4-8f41-2a517e6645d8.jpg)

I was not able to run a video but trust me when i say that the pet goes all the way to the first floor and remain stuck for a couple of minutes before he autounstuck due to my new positioning.

**Comment by ghost** [comment]
have they even started the important quest chains?

**Comment by Lantv** [comment]
For the first issue, normally if you kill a mob that drops a quest item before you've reached the limit it has a chance to drop the item even if other mobs you haven't looted yet have also dropped it.  Getting over the amount required is a common quest bug that happens even on live.  

Now I don't know if you looted your 10th drop and then killed another mob and got one, but if it's the situation I just described then that is actually normal for most quests bizarrely.

**Comment by mara1987** [comment]
11 quest items were the amount i still had AFTER turning the quest in. I know of that bug you mention, and you are right. But here i looted 11 quest items more.

**Comment by ccnim** [comment]
This looks like a retail issue, the item being "max stack: 20" instead of unique (10). Also the way it was implemented makes it seem like it was made like this on purpose.

Will mark as invalid, you may reopen it if you find evidence.

**Comment by mara1987** [comment]
The pathing issue still remains though
