### ISSUE TITLE
Taxi path bug [good one]

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#497]
Hello guys,

I had an issue regarding a taxi flight from Grom'gol Base Camp to Stonard. I logged out during the flight, and when i logged in again i found myself in this situation

![taxy bug](https://cloud.githubusercontent.com/assets/10872722/7251126/aae19ff0-e828-11e4-8e87-ac1916d9c374.jpg)

Obviously the correct behaviour is to continue the flight from the point where i interrupted it.
Also if i remember correctly you were not allowed to "logout" during flight, but instead you needed to force it by using the alt+f4 combo. I was able to simply log out.

After a minute of inactivity i was able to "dismount" and then run as i wished. Now every time i log in with this character i find myself stuck on this mount.

**Comment by ghost** [comment]
#499
