### ISSUE TITLE
Character stuck on windrider

### ISSUE THREAD

**Issue by fdlancer** [ccshiro/cc-buglist#499]
This is a very annyoing bug. When you buy a gryphon or a windrider from a flight master to travel to another area and you logout (or the server crashes) while doing so, you get stuck on said windrider or gryphon.
![wowscrnshot_042015_204005](https://cloud.githubusercontent.com/assets/12040589/7251026/6860dd36-e827-11e4-9b66-090d3e84db86.jpg)
You are unable to dismount or essentially to do anything. You can't aggro or attack mobs. You can't interact with npcs. I am unable to use a Hearthstone, because it says "You are still mounted". Using the unstuck command is impossble because of the same reason.
![wowscrnshot_042015_231757](https://cloud.githubusercontent.com/assets/12040589/7251068/01bdbd8c-e828-11e4-8c81-ead58295dcf4.jpg)
Tried to drown myself, but as seen in the picture, every damage gets absorbed. Jumping of the world will teleport you to the next graveyard.
Funny thing is, everytime you relog, the character changes position, apparently according to the flight path you originally took. 
I tried this with three characters on different flying paths, always the same outcome.

**Comment by ccshiro** [comment]
Just noticed #497, making this a duplicate.
