### ISSUE TITLE
Portal to OG

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#50]
The Portal to OG at the Dark Portal in Hellfire Peninsula is not clickable and therefore not usable.

http://i57.tinypic.com/f5691l.jpg

In TBC one cud use this portal to get back to OG quickly

**Comment by ghost** [comment]
Same goes for alliance portal on the other side.

**Comment by Iliana-sc** [comment]
Uh I thought they were just there for RP reasons to summon mobs out of? No hard evidence though.

**Comment by ghost** [comment]
I have spent 3 full days trying to find evidence that this is actually true since I thought I remember that I used those portals when TBC was retail. Apparently I was wrong because i did not find a single screenshot, video or post that ever spoke of using these portals. I even checked 2 other private servers (backtobasics and feenix), and both have these portals only for npc reinforcements. player characters cannot use them there. 

so I think I simply may have been mistaken in assuming those portals could be used back then to travel with player characters.

**Comment by ghost** [comment]
i have 0 memories of these portals being usable
