### ISSUE TITLE
Heroic keys reputation standing required

### ISSUE THREAD

**Issue by Philosophers** [ccshiro/cc-buglist#500]
I am not sure if it is an issue, or it is inteded, but keys to unlock heroic modes of 5man dungeons require honored standing. It is correct for patch 2.3.0 and above. 

Quote from wowwiki for auchenai key
Patch 2.3.0 (13-Nov-2007): Changed amount of reputation required.
Went from revered to honored.

link:
http://www.wowwiki.com/Auchenai_Key

Corecraft was said to be pre-nerfed TBC content, so required reputation to buy a heroic key should be revered (at least to the release of Zul'Aman) to make doing heroics, gearing and boosting alts harder.

**Comment by Iliana-sc** [comment]
Reputation requirements are cached by the client, if you played on a server that required honored then your client will still show honored even if the corecraft server requires revered. Did you delete your cache before the test?

**Comment by Philosophers** [comment]
I downloaded whole new client for tests, but I guess it is possible that uploaded client had "starting" cache. I'll look into it.

EDIT:
Yup, after cache clean it stands as it should be. Sorry, issue invalid.
