### ISSUE TITLE
Not working distance

### ISSUE THREAD

**Issue by byrsa111** [ccshiro/cc-buglist#502]
https://www.youtube.com/watch?v=Xanld-vjXes&feature=youtu.be

**Comment by Soda-88** [comment]
This is not a bug, Whirlwind is an AOE attack with 8 yards radius, other melee attacks such as Hamstring and auto-attack have 5 yards range

Whirlwind
25 rage
Instant
In a whirlwind of steel you attack up to 4 enemies within 8 yards, causing weapon damage from both melee weapons to each enemy.

**Comment by Klimpb** [comment]
Common bug on many private servers is that the bounding box/hitbox is messed up, making it possible to attack targets further away than what you're supposed to be able to. AoE fears & spells on these servers typically have a much larger radius as well.

Not sure if the range check displayed on the actionbar is client or server side, or if it ever was 100% reliable on retail either.

**Comment by byrsa111** [comment]
you are wrong, if it is available and the red means that I can apply it to the target / I play a lot of years in this game, I know how it works about 6 years old warrio  https://www.youtube.com/watch?v=91dm90ODGPw&feature=youtu.be Here it works correctly

**Comment by Klimpb** [comment]
@byrsa111 That's another private server though, and 6 years, I suppose you mean since 2009. That was Wotlk, but I suppose it would work about the same way. Still there's a lot of issues with the action bar range check, it's not reliable.

**Comment by byrsa111** [comment]
at the moment I can not provide you with a video server and the official sign as he worked there

**Comment by byrsa111** [comment]
If the spell OFF Red can apply it to AIMS  What I can not do if you look closely at the video This is complete nonsense and it should not work this way

**Comment by byrsa111** [comment]
spell glows red but I can not apply it to the target

**Comment by byrsa111** [comment]
Look very carefully what I'm trying to show you  https://www.youtube.com/watch?v=Xanld-vjXes&feature=youtu.be

**Comment by byrsa111** [comment]
This is nonsense, I can not use the spell though it is available and is not lit in red

**Comment by byrsa111** [comment]
And the paradox is that on mannequins in Shattrath everything works perfectly

**Comment by Jigodian** [comment]
Don't quote me on this but I think the issue stands with the targeted player's position and where exactly he appears to other players, not the actual range of the skill. I'm guessing the player's position isn't 100% accurate.
