### ISSUE TITLE
PALADIN blessing of sanctuary scale

### ISSUE THREAD

**Issue by Doope** [ccshiro/cc-buglist#503]
Blessing of sanctuary doesnt scale properly, it deals flat damage and seal of the crusader doesnt increase its damage
Greater blessing of sanctuary scaling seems to be working

https://youtu.be/k2o2c-Zr7vU

I found this site http://kbase.seventhflight.com/Paladin/Spell_Damage
im not sure about the numbers (its pre 2.1)
so either sanctuary should scale like the greater version of the spell or it shouldnt scale at all

**Comment by Barroth** [comment]
It should indeed not scale at all with spellpower, the greater blessing of sanctuary is missing in the spell coeff update

**Comment by ccshiro** [comment]
What @Barroth said.
