### ISSUE TITLE
PALADIN holy shield

### ISSUE THREAD

**Issue by Doope** [ccshiro/cc-buglist#505]
Holy shield block damage doesnt work on ranged mob attack. ( it should do damage on every blocked attack while holy shield is active)

it works properly when a player shoots me

**Comment by ccshiro** [comment]
What mobs and which attacks?

**Comment by Doope** [comment]
i tested it in netherstorm at manaforge duro on blood elf archers they did the usual ranged attack animation.

Archers might have wrong attack type, i have no idea, holy shield worked overall fine so its a minor bug
