### ISSUE TITLE
Pathing behavior of monsters that cannot swim near water

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#506]
Experienced some weird pathing behavior dragging mobs that can't to water. If nothing else is weird, the twitchy movement visible in the video is, although you'd also think the mob should reset if it cannot reach you in the water.

Video: http://ponkolauta.net/player.php?v=/WoW/src/1429555489979.webm&t=path_water.webm

**Comment by ccshiro** [comment]
Mobs that cannot path to you stand with you in combat for a while until they finally reset. This period is quite long. However, the twitchy movement he does is indeed strange.

**Comment by nz54445** [comment]
I did some pathing testing myself, posted it in #283 since it was open and for testing. I experienced similar pathing problems (as noted in there).
