### ISSUE TITLE
[Zangarmarsh] Missing NPC

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#513]
The following NPC is missing:

http://www.wowhead.com/npc=23373/mortog-steamhead

He is supposed to stand outside the entrance of Serpentshrine Caverns.
He was added in Patch 2.0.3 (http://wow.gamepedia.com/Mortog_Steamhead)
As for patch 2.1.0 he started selling mats to those brave enough to get Exalted reputation with Cenarion Expedition.

Screenshot as proof.
![missing npc](https://cloud.githubusercontent.com/assets/10872722/7255926/b98c312c-e84c-11e4-97bc-24c1adff73fa.JPG)

**Comment by ccnim** [comment]
Even though it says 2.0.3 his ID is way too high to be a 2.0.3 mob, look at all the surrounding mobs for example.

**Comment by mara1987** [comment]
It says 2.0.3 "Added" not "working as intended in 2.1.0".

So, maybe he was there but he didn't give any service till 2.1.0
Do you disagree?

**Comment by ccnim** [comment]
The mobs were added in batches as the patches progressed, his ID is among the 2.1 batch therefor I believe they have a typo on wowwiki.
