### ISSUE TITLE
"Chief Apothecary Hildagard" quest is offered to me at level 62.

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#517]
It is supposed to require level 67.
![wowscrnshot_042115_161001](https://cloud.githubusercontent.com/assets/5777848/7256335/280f313a-e857-11e4-9b67-2db692c2aea9.jpg)

**Comment by rylaiii** [comment]
http://www.wowhead.com/quest=11046/chief-apothecary-hildagard
