### ISSUE TITLE
[NPC] Silvermoon City Guardian

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#52]
Silvermoon City Guardians should react to emotes done by Horde (Blood Elf) paladin players. These emotes include /kiss, /rude, /shy and /eye.

At the moment, they don't react to these emotes on CoreCraft.

Links:
WoWPedia http://wow.gamepedia.com/Silvermoon_City_Guardian.
WoWHead http://www.wowhead.com/npc=16222/silvermoon-city-guardian

Screenshot from CoreCraft http://i.imgur.com/s1VxiAb.jpg.

Screenshots from retail (MoP).
/kiss http://i.imgur.com/89WLMkT.jpg
/rude start http://i.imgur.com/WjbLOpO.jpg
/rude end http://i.imgur.com/3T9cd1y.jpg
/shy http://i.imgur.com/qzKNZfC.jpg

**Comment by ccshiro** [comment]
They should all be changed to DB instead, if possible.
