### ISSUE TITLE
slow effects

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#525]
slow effects behave wrong?

you can't replace or add an extra debuff if the current slow on the target has a higher value

example: crippling (70%) on target -> wing clip (60%), concussive (50%) and hamstring (60%) cant be applied

also if target is slowed by a 60% hamstring a 60% wing clip will replace the hamstring

---

i think all debuffs should appear on the target and the strongest (highest %) should take effect, i'm not sure tho

**Comment by Soda-88** [comment]
Working as intended, for example, you can't apply Hamstring debuff on a target that is already afflicted by Crippling Poison, same goes with Mortal Strike and 5 stacks of Wound Poison. The damage from Hamstring/Mortal Strike will still be applied though and so will the Improved Hamstring if it procs.

Reference: https://www.youtube.com/watch?v=019vZI7gjNw (pay attention to Frostbolt debuff being overwritten by Crippling Poison at 5:20 for example)

**Comment by ccshiro** [comment]
This is working as intended.

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=YRD0p0oV54w&feature=player_detailpage#t=39

concussive shot applied to a player affected by frost trap

hmm maybe cause it's an aura, i'll keep looking for one with wing clip/frostbolt/hamstring/crippling on target

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=pO930U0_DpE&feature=player_detailpage#t=109

wing clip on target -> concussive shot applied

perhaps daze effects got an exception? idk

bad quality tho, i'll keep looking

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=51D6VZ_WhXo&feature=player_detailpage#t=55

hamstring on target -> concussive shot applied

pre tbc tho

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=51D6VZ_WhXo&feature=player_detailpage#t=108

also works the other way around

concussive shot -> wing clip applied

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=Z-KutVVLcfY&feature=player_detailpage#t=129

concussive shot -> frostbolt applied

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=LXvaufobICo&feature=player_detailpage#t=54

wing clip -> concussive shot applied

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=MDrPBmHCLGw&feature=player_detailpage#t=66

cone of cold -> concussive shot applied

**Comment by Chulain** [comment]
https://www.youtube.com/watch?feature=player_detailpage&v=vZtAcBu0BxU#t=122

wing clip -> concussive shot

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=9zXiP13WQOM&feature=player_detailpage#t=207

wing clip -> concussive shot applied

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=9zXiP13WQOM&feature=player_detailpage#t=411

crippling -> concussive shot applied

**Comment by Soda-88** [comment]
Concussive Shot is not a snare but a daze effect which makes it exception to the rule, same goes with Shield Bash daze effect. Piercing Howl on the other hand is a snare effect despite tooltip saying it's a dazing effect. Real daze effects share the icon with PvE daze effect, although the difference between the two is that PvP daze effects can be removed by trinkets, freedom, etc. just like any other snare effect. Another such daze effect is hunter's Concussive Barrage talent.

And as for the Frost Trap goes, it doesn't really fit into the controlled snare category, imagine people  running into Frost Traps to remove a Hamstring for example.

https://www.youtube.com/watch?v=pl20kkJjOBY&t=9m10s
9:14 rogue gets popped out of Vanish by Piercing Howl (which is a 6sec 50% snare)
9:19 rogue gets Hamstrung and by nature of debuff stacking (overwriting) replaces the Piercing Howl debuff which still had 1-2 seconds left on timer.

**Comment by ccshiro** [comment]
Reopened. As @Soda-88 said, dazes like concussive shot are supposed to be an exception. However, it seems one we had forgotten.
