### ISSUE TITLE
Quest: Fire At Will (10911)!

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#526]
The first problem: According to Wowhead comments, the objects of the quest, the gates, should die after 7 shots with the cannon. They did not seem to, although I am not completely sure whether or not I actually got in 7 shots as the cannon simply died itself unexpectedly.

The second problem: when active, the gates seem to spawn defenders infinitely. Pictured: http://i.imgur.com/0v9qERS.jpg

**Comment by ccshiro** [comment]
Tested quest. Found bugs:

Didn't get quest credit.
NPCs should disappear on evade.
