### ISSUE TITLE
Flying Fel Reaver

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#528]
Not sure what causes this but managed to get this screenshots

http://imgur.com/LBlzhI5,vlCNtsn,orxLuuf,MqUqzjO,mphbWHQ,jtcvRYd,KSLtqPa,f37CtOR,eTqurbj

**Comment by DaRealBoss** [comment]
its the un-nerfed fel reaver with a superman cloak on his back, ready to fly in on some nubs questing

**Comment by ccshiro** [comment]
I couldn't reproduce this, but I've done some changes to movement prior to looking at this. It's quite possible I ended up fixing this. Gonna move to needs testing for now.

**Comment by ccshiro** [comment]
Found what happened.
