### ISSUE TITLE
Arcane Explosion vs Stealth

### ISSUE THREAD

**Issue by Kinglundh** [ccshiro/cc-buglist#529]
Was dueling a Mage and couldnt see when he did the Arcane Explosion. This only happens while Im stealthed. I can see that the mana is being used, but not the explosion.

**Comment by tedrasiel** [comment]
while i played rogue i've seen ( or in this case havent seen) the same behaviour. on cc ofc.

**Comment by Chulain** [comment]
i'd say we keep this bug.
