### ISSUE TITLE
Intimidating Shout radius is way too long

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#535]
1. http://i.imgur.com/vpFobqJ.jpg
2. http://i.imgur.com/zlfY98c.jpg

Was able to use Intimidating Shout successfully at what looks to be about 13-15 yards. Tooltip says 8 yards, the range check on my action bar was also white(is this a server side or client side thing?, was it always 100% accurate?)

Prior to this without moving my characters I used howl of terror on my warlock at the same distance(spell says 10 yards in the tooltip) and it didn't work. Which it obviously shouldn't since it's plenty more than 10 yards. But however proves that there's something very wrong with Intimidating Shout since it even has a shorter range but worked.

Didn't test Psychic scream or other AoE spells.

**Comment by Barroth** [comment]
Initmidating shout got 10 yard range(single target fear) and a 8 yard range aoe fear

**Comment by Klimpb** [comment]
@Barroth Pet got feared too, and he was standing right next to me. Howl of terror didn't work at the same range. 

And the distance between the warrior & warlock is more than 10 yards.

**Comment by Barroth** [comment]
looks like a bug then, just stated what the spells range is^^
