### ISSUE TITLE
Revive cannot be accepted

### ISSUE THREAD

**Issue by ShuTestCC** [ccshiro/cc-buglist#536]
Situation and hopefully helping you reproduce the situation:
I was in a raid on Doomwalker the day before. When I decided to log out that day, filthy ally scum attacked me. Since it was a gank I decided not to react to it and just alt f4, well knowing that the next day I would log in as a ghost.
That's basically what happened the day before: I died from PvP after Alt-F4ing.

Next day I logged in as a ghost and ran to where I died. Not only did the map show the correct location but I am also 100% positive that it was that place near BT. As should be, the "Revive now?" window popped up when I got close. But when I clicked it, there would be no reaction. The window would stay and I couldn't revive. Next thing I noticed was that my corpse was not there (this might be different bug, though, it might have been underground - the day before Ive seen shaman totems underground near said spot).
I relogged, restarted the client with a fresh WTF folder and followed other advices my guild had to offer, but to no avail. Shiro, you had to manually resurrect me. You also teleported to me and saw my location.

**Comment by lastnoob** [comment]
Maybe you should have deleted WDB too? In other servers many death bugs are related to it, more than WTF. Regardless if it can be fixed it should be :)

**Comment by ShuTestCC** [comment]
@lastnoob No sir, it was stupid of me to not delete cache, I mustve simply overseen it.
I didn't try spirit healer, either, simply because I didn't care about the revive as much as about the bug being fixed. So I alerted shiro and then he revived me anyway. So I dont know if spirit healer would have worked.
