### ISSUE TITLE
old hillsbrad foothills

### ISSUE THREAD

**Issue by Doope** [ccshiro/cc-buglist#542]
1. Explosives: you can use your explosives only once on a barrel ( so every player has to take one from the dragon) -  I think you should be able to use it infinitely
   http://www.wowhead.com/zone=2367/old-hillsbrad-foothills#comments
   "One person needs to grab the explosives off the dragons at the beginning."
2. Durnholde Sentry:  when we engaged them, sometimes they didnt summon the 2 adds ( they properly yelled for help) - i think pulling with hunter pet causes the problem but im not sure
3. Thrall: http://i.imgur.com/GtkWeGa.jpg   After we fought this pack we stopped for 5 sec and he simply disappeared on the ramp. (he teleported back to his cage) - It seems like the follow range is too small
4. pathing: Pathfinding on "ramps" are not working the mob simply stops moving. It only happened once in durnhole to Lieutenant Drake ( i tanked him in the pit and everyone else were on the high ground, when the mage pulled the aggro the boss had no idea where to go). Pathfinding issue is insane in Blood Furnace every 5. pack is bugged. I can make some video of necessary

**Comment by ccshiro** [comment]
Please make one issue per bug you're reporting in the future. When you put multiple in it like this it becomes very hard to manage the bug tracker. As for the reports:
1. Working as intended.
2. I will test if I can reproduce that one.
3. Could use some research to figure out how long the range should be.
4. Would be nice if you could post a video, yes.

**Comment by lastnoob** [comment]
Its not exactly the same, and I forgot to test it, but...anyone tested if everyone uses their explosives at the exact same time, on the same barrel, it counts as 5? because its a very common bug on tbc servers.

**Comment by sandfury** [comment]
we tried it a couple tests ago lastnoob, it only applies once

**Comment by nz54445** [comment]
Can confirm that the bug with multiple clicks does not happen on this server, unless they broke it for some reason.

**Comment by lastnoob** [comment]
great :)

**Comment by leroy1** [comment]
As for charges I can remember from retail my group waited for me on bridge while I did 5 barrels run to setup all 5 charges as rogue. The most hard part was to avoid sentries with dogs. That was before 2.4 patch. http://www.wowwiki.com/Escape_from_Durnholde_Keep  (Diversion article)
