### ISSUE TITLE
Pet command delay proof and other things

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#549]
https://youtu.be/0xAuRkhnetk?t=2m42s
Look at the macro and how the pet acts, as well as how fast the pet switches between the targets but also that the pet never needs to move after he hits the first totem.

Tried to mimic it as much as possible, but I used more totems because I could never get the pet to attack the shaman, whatever I did it would never attack the shaman like it did in the video.

http://webmup.com/273ab/ (didn't attack searing totem because it wasn't in the macro)

Note that this was after a few attempts and this was the one where the pet acted the fastest.

Other times he wasn't as fast: http://webmup.com/8319e/

Other proof of that the pet command "update rate" should be higher: http://webmup.com/f12c4/ (same video as in one of my other reports, the spell lock the felhunter casts on the mage right at the starts interrupts the cast within 1 frame of it being casted, did some tests on corecraft and could never get it even close to 1 frame(less than 33ms)).

This video could also be evidence or at least help out with a few other things such as assisting in solving the bounding box, hit box and melee range issues, take note of the distance where the pet stops to attack the totem and how far the totems are from the shaman.

The totem distance from the shaman was the first thing that I noticed was different, I'm not sure if there's information about the totems range or if it's simply a guessed value, comparison:

Retail:
![](http://i.gyazo.com/c28d8733a4e537997d8a71f242ae3f31.png)

Corecraft:
![](http://i.gyazo.com/3ea73071084bf2f6c68a1b8e34e8098f.png)

The totems are further apart on Corecraft.

Study this footage closely and try to mimic the totem distance to the best of your ability and it could really be a helpful guideline when solving other things.

Other shaman TBC footage showing totem distance:
https://youtu.be/g5brtLZbXYE?t=3m (at 3:00-3:37 mostly)

**Comment by ccshiro** [comment]
We need more research into the Pet delay thing. In other words, footage with manually using the pet's spells, and sending the pet to attack or bringing him back. We need this to determine if it's the case that no delay existed on pets in TBC, and that's a newer addition to the game. Or if there's something else going on in this footage.

**Comment by tedrasiel** [comment]
Did u change the positioning of the totems towards the shaman who summons them?

**Comment by ccshiro** [comment]
@tedrasiel yes, that should be correct now.

**Comment by tedrasiel** [comment]
Awesome

**Comment by Karepow** [comment]
This may have been looked at already, but it looks as if from the first video that the pet auto attacks the first totem and then uses lash of pain on the second which would explain how both totems are killed so quickly. Also as mentioned previously, the totems being further away from the Shaman on Corecraft than on retail could definitely be something that affects the pet movement.

**Comment by ccshiro** [comment]
I changed my mind, since you've proven it didn't exist in two scenarios, it seems more reasonable to assume it didn't exist at all rather than keep confirming more scenarios.
