### ISSUE TITLE
Wrong spawn place after dead

### ISSUE THREAD

**Issue by Pinhastest** [ccshiro/cc-buglist#554]
As you can see on the image i died on the yellow mark and i apear as a ghost on the red mark. When i should spawn on the nearest graveyard (green mark)
![img_3648 1](https://cloud.githubusercontent.com/assets/10587278/7337154/1cd668a0-ec0e-11e4-8354-bd0abad90b17.jpg)

P.S. Didn't know how to print screen on a bootcamp mac :p

**Comment by ccshiro** [comment]
That position is supposed to be used to put your corpse at. So that when you get back to the ledge you can resurrect. If you fall down and die (or fall down as ghost) you end up at a real graveyard (i.e. not this position; this one is only supposed to be used for your corpse).
