### ISSUE TITLE
Rite of Vision

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#566]
https://youtu.be/PwXFuLB6XKI?t=49

I need help finding the emotes the wolf is using.

**Comment by nz54445** [comment]
Here you go @ccnim, you can actually read this one:

https://www.youtube.com/watch?v=Wvln5afYTFY

It says:

The Plains Vision stares to the northwest and lets out a long, drawn out howl.

When he gest there:

The Plains Vision lets forth a mighty howl.

Edit: 2:45 in the video.
