### ISSUE TITLE
World Recipe Drops

### ISSUE THREAD

**Issue by ccnim** [ccshiro/cc-buglist#568]
We're doing world drop recipes, and built a list of things to add. This is an auto-generated list and is probably a bit off atm. Looking for help to find things that shouldn't be in there, and to add things that should.

http://pastebin.com/qktqABG9

**Comment by bjplunk** [comment]
160-170 are not world drops (quick glance, some may in fact be, but most aren't)

**Comment by Javas-Lal** [comment]
So far missing, by profession:
[ENCHANTING]
1. 200 - Formula: Enchant Gloves - Skinning http://www.wowhead.com/item=11166/formula-enchant-gloves-skinning
2. 215 - Formula: Enchant Gloves - Advanced Mining http://www.wowhead.com/item=11203/formula-enchant-gloves-advanced-mining
3. 225 - Formula: Enchant Cloak - Lesser Agility http://www.wowhead.com/item=11206/formula-enchant-cloak-lesser-agility

[LEATHERWORKING]
1. 270 - Pattern: Runic Leather Gauntlets http://www.wowhead.com/item=15731/pattern-runic-leather-gauntlets
2. 275 - Pattern: Heavy Scorpid Gaunlets http://www.wowhead.com/item=15738/pattern-heavy-scorpid-gauntlets
3. 280 - Pattern: Runic Leather Belt http://www.wowhead.com/item=15745/pattern-runic-leather-belt
4. 290 - Pattern: Wicked Leather Pants http://www.wowhead.com/item=15757/pattern-wicked-leather-pants
5. 300 - Pattern: Runic Leather Pants http://www.wowhead.com/item=15765/pattern-runic-leather-pants

**Comment by Javastorm** [comment]
[LEATHERWORKING]
1. 270 - Pattern: Runic Leather Gauntlets http://www.wowhead.com/item=15731/pattern-runic-leather-gauntlets
2. 275 - Pattern: Heavy Scorpid Gaunlets http://www.wowhead.com/item=15738/pattern-heavy-scorpid-gauntlets
3. 280 - Pattern: Runic Leather Belt http://www.wowhead.com/item=15745/pattern-runic-leather-belt
4. 290 - Pattern: Wicked Leather Pants http://www.wowhead.com/item=15757/pattern-wicked-leather-pants
5. 300 - Pattern: Runic Leather Pants http://www.wowhead.com/item=15765/pattern-runic-leather-pants
Everything else looks good for Leatherworking.

**Comment by leroy1** [comment]
Does item that drop only from 1-3 specific mobs considered as world drop?

**Comment by ccnim** [comment]
@leroy1 They are not considered as world drops.

**Comment by leroy1** [comment]
Ok then drop only from specific mobs: item=11166 item=11206 item=11205 item=11203 item=11150
item=11151 item=11152 item=18257 item=12827 item=12830 item=21371 item=15738
Source used http://db.vanillagaming.org/ and wowhead comments

Comment for item=29718 and item=29714 from wowhead (This will no longer be a world drop in patch 2.3 but will instead be purchaseable at revered from the Kurenai or Mag'har) dont know how it will work for Corecraft

**Comment by ccnim** [comment]
@leroy1 Please verify with the list we have and tell me which ones we need to remove from the list or add to the list.

**Comment by leroy1** [comment]
Haven't checked what to add so just items to remove from list:
№132 http://www.wowhead.com/item=11150 (Formula: Enchant Gloves - Mining) Dark Iron Dwarves Wetlands
№133 http://www.wowhead.com/item=11151 (Formula: Enchant Gloves - Herbalism) Elementals Treants from Ashenvale and Stonetalons
№134 http://www.wowhead.com/item=11152 (Formula: Enchant Gloves - Fishing) Murlocs from Hillsbrad
№141 http://www.wowhead.com/item=11205 (Formula: Enchant Gloves - Advanced Herbalism) Swampwalkers from Swamp of Sorrows
№166 http://www.wowhead.com/item=12827 (Plans: Serenity) Stratholme
№167 http://www.wowhead.com/item=12830 (Plans: Corruption) Stratholme
№196 http://www.wowhead.com/item=18257 (Recipe: Major Rejuvenation Potion) Molten Core
№200 http://www.wowhead.com/item=21371 (Pattern: Core Felcloth Bag) Molten Core
№306 http://www.wowhead.com/item=29714 (Pattern: Drums of Restoration) see my comment above
№307 http://www.wowhead.com/item=29718 (Pattern: Drums of Speed) see my comment above
EDIT №197 http://www.wowhead.com/item=18265 (Pattern: Flarecore Wraps) Molten Core

**Comment by ccnim** [comment]
@leroy1 We will remove the ability to purchase the drum patterns from Mag'har and Kurenai and will instead put them in as world drops.

**Comment by leroy1** [comment]
Items to add:
http://www.wowhead.com/item=6342/formula-enchant-chest-minor-mana
http://www.wowhead.com/item=11039/formula-enchant-cloak-minor-agility
http://www.wowhead.com/item=12261/plans-searing-golden-blade
http://www.wowhead.com/item=15731/pattern-runic-leather-gauntlets
http://www.wowhead.com/item=8385/pattern-turtle-scale-gloves
http://www.wowhead.com/item=13492/recipe-purification-potion
http://www.wowhead.com/item=15765/pattern-runic-leather-pants
http://www.wowhead.com/item=15745/pattern-runic-leather-belt
http://www.wowhead.com/item=14506/pattern-felcloth-robe
http://www.wowhead.com/item=15757/pattern-wicked-leather-pants
http://www.wowhead.com/item=14508/pattern-felcloth-shoulders
http://www.wowhead.com/item=14504/pattern-runecloth-shoulders
http://www.wowhead.com/item=14498/pattern-runecloth-headband
http://www.wowhead.com/item=14496/pattern-felcloth-hood
http://www.wowhead.com/item=14492/pattern-felcloth-boots
http://www.wowhead.com/item=14491/pattern-runecloth-pants
http://www.wowhead.com/item=14489/pattern-frostweave-pants
http://www.wowhead.com/item=14484/pattern-brightcloth-cloak
http://www.wowhead.com/item=14479/pattern-brightcloth-gloves
http://www.wowhead.com/item=14478/pattern-brightcloth-robe
http://www.wowhead.com/item=14474/pattern-frostweave-gloves
http://www.wowhead.com/item=14470/pattern-runecloth-tunic
http://www.wowhead.com/item=14466/pattern-frostweave-tunic
http://www.wowhead.com/item=15731/pattern-runic-leather-gauntlets

Note that some of this recipes can be learnd from trainers
