### ISSUE TITLE
Shaleskin Flayer(20210) doesn't move even when being killed

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#578]
Engaged over 20 all the same result they didn't attempt to close in to attack they just died without a fight

**Comment by ccnim** [comment]
We need you to write .movegen --verbose on the target and taking a screenshot of the chat with the mob in view.

**Comment by helion84** [comment]
http://imgur.com/K6iOTFa

bug is very random some are just standing(bugged) some are working fine.

**Comment by offl** [comment]
Today this happened to me with [similar NPC](http://imgur.com/2dxlQL8).
