### ISSUE TITLE
[SPELL][MAGE]Invisibility

### ISSUE THREAD

**Issue by Stoney21** [ccshiro/cc-buglist#582]
If a warlock uses his Detect Invisibility buff DURING mage's Invisiblity buff then a mage won't be able to see the buffed target. That's not intended.

**Comment by ccshiro** [comment]
Seems to work for me. Mind describing how it all happened? Maybe there's some specific trigger.

**Comment by Stoney21** [comment]
I had a duel with a warlock. I used Invisibility and gone invisibile while he had no Detect Invisibility buff up. Then he buffed himself with it and could see me while I couldn't see him.

**Comment by ccshiro** [comment]
Oh, I read the OP wrong.
