### ISSUE TITLE
Channeling AoE Spells

### ISSUE THREAD

**Issue by Stoney21** [ccshiro/cc-buglist#583]
The locations you choose while using spells like Blizzard or Rain of Fire gets bugged that it's used on player's location instead.

**Comment by Noobzin** [comment]
I can confirm that, tried to AOE farm with mage, same issue. Doesn't matter where you cast it, it always gets channeled on top of you.

**Comment by Fraaxington** [comment]
Confirmed with Hunter's Volley spell as well. Appears to be only channeled aoe spells as stated above.
