### ISSUE TITLE
drain mana and fear

### ISSUE THREAD

**Issue by Isuel** [ccshiro/cc-buglist#587]
yet another question, should drain mana not break fears when it drains? it breaks polys, and I remember it being reported and fixed on a wotlk server.

**Comment by Edialden** [comment]
xD why you ask on these stupid questions? It should break fear. So go ahead and test it yourself, then report outcome. Dont waste dev´s time, they make tests for us to find and report bugs, not to answer your retarded questions with no proofs or tests.

**Comment by Isuel** [comment]
well, thanks for answering, because IT DOESN"T BREAK FEAR AT THIS MOMENT, so instead of being an asshole, u can actually reply nicely.

**Comment by Edialden** [comment]
Oh, my deepest apology :D.. and what about to write it as a fact and not as retarded question? it would save a lot of time for devs because they wont have to ask you for more info. AND you should create issues by following 'report guidelines' which can be also found on  pastebin. Read sticky thead first, then open ur mouth.

**Comment by Isuel** [comment]
"save a lot of time" yeah, it takes so much time for a dev to close or move the bug report while players answer the question.

**Comment by tasinx** [comment]
Definitely something fishy going on with fear. I was testing fear breaking on damage and I noticed I could put all affliction warlock dots up (UA, Siphon, Corruption, Agony, and Drain Life) on a pvp geared toon and take him from 80% to dead without fear breaking, while a minute later it would break a second after I feared. Easy to reproduce, just took doing this in duels over and over for a few minutes.

**Comment by tedrasiel** [comment]
as far as im concerned theres a maximum of dmg u can take before it breaks, and a random chance to break it everytime u deal dmg to the feared target. but whoa... not easy to find proof for that one.

**Comment by Isuel** [comment]
if i remember correctly, in wotlk u were allowed to take 10% of ur hp in damage before roots/fears broke (or before the chance of breaking became very high), and it was changed in cata to 5%. I don't know for TBC, maybe it was just a set chance of breaking on damage (that's why fears and roots in tbc can be broken by even the smallest damage, like a single dot tick)
