### ISSUE TITLE
Infernal

### ISSUE THREAD

**Issue by darkcranio** [ccshiro/cc-buglist#588]
Well I lost my screenshot but whatever. So the bug is when I summoned the Infernal, it appeared invisible. It didn't attack any NPC on command except guards, I was ally in Crossroads. Also evaded to the point where it was summoned when the timer went off, it supposed to attack me first. 
I had a succubus summoned and I was on a mount when I summoned the Infernal (hope this helps for recreate). Oh also was summoned ONE ME, the caster, not where I pointed with the spell.

**Comment by YourNewfriend** [comment]
I was able to reproduce this during the test, but only while in Shattrath.
