### ISSUE TITLE
Wand CD is on Collect Questitem CD

### ISSUE THREAD

**Issue by RealZwox** [ccshiro/cc-buglist#589]
https://www.youtube.com/watch?v=nc4HKV1ezTU

Sorry vor the Bad vid qual but my upload is atm not the best :D

**Comment by ccshiro** [comment]
I'm not sure that this is a bug, needs research.

**Comment by RealZwox** [comment]
^ same. Only wanding is on the same CD. Tryed with AE and other things.

**Comment by ccshiro** [comment]
Will close this since I don't really care how it works (since it has no real impact). If you find some evidence one way or the other, feel free to reopen the issue.
