### ISSUE TITLE
Shadowform in and out healing

### ISSUE THREAD

**Issue by wonderchipstick** [ccshiro/cc-buglist#59]
When I step out of shadowform and heal myself with a renew then I try to switch back to shadowform sometimes it "stucks" . It won't let me get into shadowform and it says "the spell is not ready yet". Once I triggered it by accident, next time I really wanted it to trigger. It happened again when I renewed then spammed shadowform and during the renew's global cooldown it bugged out. The bug could be fixed by dying.

**Comment by nz54445** [comment]
This happened to me as well, although i died and got resurrected when it stopped working. Same symptoms: "Spell is not ready yet". Solved by re logging. I could have potentially cast disc spells like PW:S, but i had no holy spells on the bar at the time.

**Comment by ccshiro** [comment]
Unable to reproduce this but I'm fairly confident of what's happening so I'll make a patch based on that.

EDIT: Reopen again if it turns out I was wrong.
