### ISSUE TITLE
[arcatraz] negaton warp-master size

### ISSUE THREAD

**Issue by PolarCookie** [ccshiro/cc-buglist#593]
when negaton warp-master creates a shadow ring that buffs and heals him, he grows in size
he grows indefinetly in size, until he is as large as the room
hitbox reaches far into the corridor leading into the room, so can't even kite properly

**Comment by PolarCookie** [comment]
some screenshots
looking up into the ceiling
![wowscrnshot_060515_194000](https://cloud.githubusercontent.com/assets/1158801/8012639/5b9e0c62-0bc3-11e5-8531-e3ae274c910f.jpg)

looking at his bottom
![wowscrnshot_060515_194003](https://cloud.githubusercontent.com/assets/1158801/8012601/27746b48-0bc3-11e5-8110-59501dd56c44.jpg)

dead after nim took care of him
![wowscrnshot_060515_194531](https://cloud.githubusercontent.com/assets/1158801/8012688/a0e95646-0bc3-11e5-8a54-f1241615662c.jpg)

**Comment by PolarCookie** [comment]
another thing, he was listed as soul devourer in combat log

**Comment by kikomir** [comment]
We encountered this too. Another problem is his size and buff stacks don't reset after a wipe so next time you pull him he starts with 5-6 stacks.
