### ISSUE TITLE
npc - demon hunter supplicants

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#596]
http://www.wowhead.com/npc=21179

These npcs are dueling eachother on top of the black temple. When pulled only one of them will engage, the other one will reset. The mob you're fighting will reset after dropping to a certain health %.

Same goes for the other mob, even if he already reset when you pulled the other one.

**Comment by sandfury** [comment]
I was there with my friend when we tried to aoe them and noticed the same issue, they will randomly disengage and start doing the animation they did before you engaged them and go back to their original position

**Comment by Chulain** [comment]
same goes for Spellbound Terrorguards dueling Demon Hunter Initiates

http://www.wowhead.com/npc=21180
http://www.wowhead.com/npc=21908

---

& the Sunfury Summoners should be linked with the Spellbound Terrorguards

"Some of these mobs have a beam controlling a Spellbound Terrorguard. I sapped this guy and the Spellbound Terrorguard disappeared (only worked when the beam is on him). Tried multiple times to be sure. So it is a good way to get rid of at least one add."

summoners: http://www.wowhead.com/npc=21505

**Comment by Chulain** [comment]
demon hunter supplicants still reset if you engage them while they're dueling

**Comment by ccshiro** [comment]
@Chulain works for me. I tried: charge, body pull and range pull (with arcane shot). How did you pull them to make them bug?

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=n2FYxFe_H30
