### ISSUE TITLE
Arcane missiles, reflecting ticks

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#6]
Should you be able to reflect individual ticks of arcane missiles?

Prefer a video or some reliable source (like arenajunkies, etc).

**Comment by Whatsthis880** [comment]
Here's a video that a friend of mine found (Adickt) : https://www.youtube.com/watch?v=4JnQaXSHzEE (at 1:50).

**Comment by ccshiro** [comment]
Thanks for that video. Will closed this as resolved as there's no doubt the video proves exactly that!
