### ISSUE TITLE
slow object respawn

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#600]
http://www.wowhead.com/quest=10422/captain-tyralius
The prison you need to unlock has a respawn time of 25min+ (server crashed) which is way too long.
I believe the object ID is 184588

key needed to open prison cell drops off Warden Icoshock id: 2077
npc respawn time: 3 mins (which is also too long imo)

**Comment by ccnim** [comment]
Object doesn't respawn even if I turn of the flags for some reason, lowered the respawn rate of all mobs and objects related.

**Comment by Chulain** [comment]
@ccnim i forgot to check,

he should say "You've saved me, fleshling! Ameer will hear of this noble act." when you free him
https://youtu.be/Yvc8XKTQV4w?t=77

**Comment by ccnim** [comment]
That's already implemented.
