### ISSUE TITLE
movement bug - Collidus the Warp-Watcher

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#602]
https://www.youtube.com/watch?v=VZLmY6vcaUw
http://i.imgur.com/D5cql2S.png

npc id: 18694

**Comment by Chulain** [comment]
sorry about quality, should be fine next time tho

**Comment by ccnim** [comment]
Rare mobs have not been done yet, I will go through them and fix them at a later date so I will close this issue.
