### ISSUE TITLE
Nuramoc(20932) has a strange out of combat movement pattern

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#607]
he seems to be trying to fly it's hard to explain and I can't video it because I wanted to see if he had other bugs https://www.youtube.com/watch?v=fhIdSr6FPXc is a video from 2007 where you can see how he casts his lightning bolt from both mouths here is a more recent and clear video https://www.youtube.com/watch?v=Mi89inIx5z8

**Comment by ccnim** [comment]
I haven't fixed rare mobs in TBC yet, so I will just close it since I will be going through them anyways.
