### ISSUE TITLE
entering water with flying mount

### ISSUE THREAD

**Issue by DennisPuetz** [ccshiro/cc-buglist#61]
when entering water with a flying mount you can not break the surface. Normal behaviour would be to get dismounted.

**Comment by Iliana-sc** [comment]
not a bug

worked like that on TBC and movement is client side anyway

**Comment by FurioCC** [comment]
I confirm that it supposed to work like that in TBC and not a bug, you could just "autofly" into water surface and keep being above surface without dismounting or forced out of flightform for druids (i personally was doing that in TBC as druid).
