### ISSUE TITLE
Skithian Windripper's buff cannot be dispelled

### ISSUE THREAD

**Issue by magikalCC** [ccshiro/cc-buglist#613]
Power of Kran'aish (magic) spell and ability costs are decreased by 5%
Couldn't spell steal.

**Comment by lynxzor** [comment]
Can't dispel and buff not available when you MC the mob either.

**Comment by ccnim** [comment]
It's actually a debuff they put on themselves, that's why you can see the blue border. Why blizzard decided to have mobs debuff themselves is unknown to me.

**Comment by lynxzor** [comment]
From wowhead:

2.1.0 "A priest can mind control the sorcerers or windrippers and cast this spell on themselves and any friendy target. It lasts for 5 minutes."

2.2.3 "can be Spell stolen from Skithian Windrippers as well"

**Comment by Yagrulol** [comment]
I had the same issue as lynxzor, healing a temporarily friendly monster was no problem but i could not dispell any effects on it as a priest when our other priest mindcontrolled a monster.
