### ISSUE TITLE
turning around in bg

### ISSUE THREAD

**Issue by DennisPuetz** [ccshiro/cc-buglist#62]
Bug happened in Arathi basin.
From Time to time you turned around as if a rouge would distract you.
Happened to many other player in this specific batleground

**Comment by Iliana-sc** [comment]
does this happen when you right click to mouse look? Do you have dual screen? I think this is some bug in the client related to dual screen or something

**Comment by Sakatoro** [comment]
i got the same problem

**Comment by DennisPuetz** [comment]
i dont have dual screen but i am playing in windowed mode, dont know if this is related

**Comment by Iliana-sc** [comment]
when the bug happens to me my mouse pointer is always in a stupid location so I'm fairly sure this is just some strange directx input bug. I thought it was because of dual screen but apparently not then.

**Comment by zoofCC** [comment]
Happened to me plenty of times today while looking for bugs. Even while flying it caused me to turn my vision like affected by rogue distraction.

**Comment by mrtveit14** [comment]
This happens frequently to me in arena aswell.

**Comment by braide** [comment]
It specifically happens when someone shadowsteps or blinks. Looks like it doesn't matter who (friend or foe) and it happens to characters around someone who used one of those spells.

**Comment by FurioCC** [comment]
Happened to me while in Steamvaults even while i'm dead.
Camera just turned around for no reason.

**Comment by Piranhaz** [comment]
Happens in BG very often, but everywhere in the world too. Camera turns around like distracted by a rogue.

**Comment by Klimpb** [comment]
Can confirm, extremely annoying. Did not exist on previous tests.

**Comment by Voodopad** [comment]
I haven't experience this on Corecraft but on other servers it happens when you turn around while right mouse clicking.

**Comment by ccshiro** [comment]
Same bug as #46.
