### ISSUE TITLE
[Rogue] Distract issues

### ISSUE THREAD

**Issue by nullfoxh** [ccshiro/cc-buglist#624]
I found a couple of issues with rogue distract:
1. Mobs face weird directions or just nudge a couple of degrees.
2. The visual "smoke" effect should show at the position clicked, not under a mob affected by distract.
3. Skill range is larger than the visual indicator (not sure if bug).

How to reproduce? See video:
http://webm.host/ff04c/

**Comment by Aldergar** [comment]
Confirmed,I was doing ramparts and a rogue used Distracting Shot a couple of times and the mobs were facing random directions.

**Comment by cdreipo** [comment]
im not sure if theis is the right place and im not 100% sure of the bug, but
after distracting and sapping the target always stays in one place and can just be ranged killed.

**Comment by nullfoxh** [comment]
cdreipo, I reported your bug as a separate issue here: https://github.com/ccshiro/cc-buglist/issues/671
