### ISSUE TITLE
(PvP) Loss of control

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#625]
Some times after losing control to a CC or Iceblock(seems to be any cc) you never regain it until you relog even after switching zones. You can't use abilities talk to npcs or mount up. We tried hard to reproduce it on purpose but it seemed random :(

**Comment by Bzmode** [comment]
managed to reproduce it http://www.twitch.tv/faleene/c/6797955 "Cannot do that while confused"

here's another example http://www.twitch.tv/faleene/c/6797961 it seems when you stack CC this happens.

**Comment by ceyscro** [comment]
Yeah that happen when you stack CC.
I noticed that with rogue's Sap, when you sap and then cheapshot or kidney, target can't move then. But with sap + blind he can, so I think it does not happen with all CC.

In this report https://github.com/ccshiro/cc-buglist/issues/592

Shiro told that it should have been fixed, isn't it?
