### ISSUE TITLE
mutli shot

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#626]
multi shot hits targets behind you
https://www.youtube.com/watch?v=T3LZWQu8fd0

---

multi shot can hit targets much further away than your max range
https://www.youtube.com/watch?v=wZWyJpvz9TA
altho i think it should add a few yards to the limit but this seems to be a bit too much? idk

**Comment by ccshiro** [comment]
Multi-shot, while looking like a cone AoE, is actually a chain lightning-type spell internally. So the second video is definitely working as intended. The first one might be a bug though.

Some video from TBC would be nice to prove it bugged.

**Comment by Chulain** [comment]
https://youtu.be/o-S9sDhN5IY?t=126

not exactly behind him but most likely within deadzone and gets hit, so it prolly hits targets behind you too if close enough to your initial target

like you said, it's probably like chain lightning

i'll keep looking tho

**Comment by Chulain** [comment]
https://youtu.be/_IiRdzvwJIg?t=111

felguard behind him doesn't get hit by multi shot even tho the lock stand close to the hunter (maybe not close enough?)

edit: however, i took another look at the video i recorded, looks like +- same distance

**Comment by Chulain** [comment]
https://youtu.be/j0iBXVpTT4c?t=110

ppl running in don't get hit by multi shot, even tho they stand close to the initial target

perhaps multi shot also depends on the hunter's position? the angle between the hunter and other players?

that's all for today i'll look for more later

**Comment by KuroiKensai** [comment]
Multi-Shot do not hit targets right BEHIND you. Thats for sure. Was playing hunter a lot and never seen that. Maybe some specific angle - yes, but not 180 degrees for sure.
Also found this topic about 2010 year Multi Shot changes:
http://www.warcrafthuntersunion.com/2010/08/multi-shot-update/
Here you can see words "Most likely you will be able to hit even targets behind you and beyond 35 yards with the “splash” damage effect." MOST LIKELY (!) Which means that this NEVER happens before 2010 year and for sure NEVER at BC times. As well as hitting targets beyond 35 yards range.

**Comment by Barroth** [comment]
Found a video showing that multishot is able to bounce farther than maxrange: https://youtu.be/aL64YWN0134?t=339 (confirmed ingame)

**Comment by Chulain** [comment]
https://youtu.be/LKYrBlSH_lo?t=271

that's proof for hitting targets within deadzone with multishot, if it ignores minimum range i'm guessing it also ignores max range

**Comment by Chulain** [comment]
https://youtu.be/LKYrBlSH_lo?t=509

two mobs in front of him, one behind, standing pretty close to the other two
the one behind him doesn't get hit

**Comment by Chulain** [comment]
im giving up, cant find any video with a hunter multi shotting a mob while another one stands behind him

its prolly possible tho

**Comment by meowmewo** [comment]
.
Here;  https://www.youtube.com/watch?v=NjSFKaWZxCQ
3:19 RIGHT before the warrior got trapped, hunter clicks Multi Shot, warrior doesnt get hit.
YOU CANT hit target behind u with multi shot.

**Comment by meowmewo** [comment]
And since OP proved with the video that Multi Shot ignores deadzone, then i think we could say that Multi shot hits targets only infront of u,

**Comment by meowmewo** [comment]
Here is the thing tho...
Here https://www.youtube.com/watch?v=ClIA0RlK1KA
At  4:37 Hunter uses MS. There is a druid "infront" of him, and he doesnt get hit. Same thing happens at 4:49. Also check 8:40
Im getting confused now how MS actually works. I guess targets have to be on an X range between each other (5-6 yards?) in order for MS to hit all. If they are far apart, MS will hit only ur main target without touching the other ones even if they are infront and in range of u.

**Comment by meowmewo** [comment]
On the video there is a part (fighting at Farm) where MS kills a critter and hits 2 other close targets. On another point MS hits 2 targets but not the same critter due to it being far from the other targets. So i guess ..YES., targets must be close..wich makes hiting target behind u impposible. BUT question is..how much is this minimal range between the targets.

**Comment by ccshiro** [comment]
@meowmewo 
https://www.youtube.com/watch?v=NjSFKaWZxCQ 3:19
This video doesn't work to prove anything. The main target of multi shot is too far away for it to bounce to the Warrior.

https://www.youtube.com/watch?v=ClIA0RlK1KA
Same thing.

As was said before, multi-shot works like a chain lightning. Not only does the target need to be behind you in the video, but the target you're shooting at needs to be within ~10 yards of the target behind you. Or, there needs to be a chain of targets that are within ~10 yards of the main target leading to the target behind you. Which is why finding a video of it is going to be difficult.

**Comment by meowmewo** [comment]
but that doesnt happen...Multi shot DOESN'T hit targets behind you.

**Comment by meowmewo** [comment]
Il keep looking non the less.

**Comment by meowmewo** [comment]
https://youtu.be/heVToV3TPpI?t=188 . Here at 3:09? Other guy is CC but it would of got Immine text or w/e, we cant see an arrow going towerds the guy behind too.
https://youtu.be/SIclL3DIO1E?t=124 He hits the pet at 2:06. Hunter is right behind him. 

I just cant find the right video. I give up. But please can check these vids, both thargets should be within 10 yards .

**Comment by Ickler** [comment]
So I don't know if this is clear from looking at the code or not, but do we know if Multi Shot can go "Via-Via" like Chain heal / Lightning? 

I seem to recall when you Multi shot a group of mobs, if you picked a mob at either side you could end up just having 2 shots fired (third target too far form initial target, but close to second target). But while aiming for the middle one, you'd always get 3 shots. 
So with this logic, a Multi shot going from the main target to someone in deadzone, then again to someone behind you shouldn't be possible anyways?

I don't know, but to me it always seemed like Multi shot only chained from initial target. Not from initial target, then to something else and onwards from that target?

**Comment by Barroth** [comment]
https://www.youtube.com/watch?v=dKx0KsCNBH4#t=452

Looks like multishot does jump the same as Chainlightning, else the jump radius gotta be very big to achieve that angle

**Comment by meowmewo** [comment]
One thing im 99.9% sure for is that multi shot doesnt hit targets behind u.

**Comment by justinbeaver** [comment]
Chain hit to target that not in line of sight.
Mage is hiding behind the pillar and hunter finished him by targeting his pet. Quite beautiful if you ask me.
![](http://i.imgur.com/gEkVdBT.jpg)
https://www.youtube.com/watch?v=m8nOaNMHZIQ&feature=youtu.be&t=333
Desctiption on youtube is incorrect, video is from retail.
WCM link http://www.warcraftmovies.com/movieview.php?id=66527
