### ISSUE TITLE
aggro'd a mob that couldn't reach me

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#627]
aggro'd a mob that couldn't reach me
http://i.imgur.com/b7X5Maa.png

targetting my pet but also happened without pet

**Comment by ccshiro** [comment]
This doesn't look like a bug, would be nice with a video to see what happens just in case.

**Comment by Chulain** [comment]
heres what happened: i flew down there and aggro'd them, dismounted and ran around a bit which caused them to reset after a second or two

**Comment by shadowraider** [comment]
maybe that sail hanged on those 2 bones which you are standing on, is not counted as a line of sight, have you tried to shoot down on the mob?

**Comment by ccshiro** [comment]
@ccnim It is working as intended that this thing does not block Aggro LoS. However, when I went there with a level 70 on retail I had to almost walk into the mobs to get them to aggro. Basically it doesn't happen on retail because these mobs seem to have lowered aggro distance.
