### ISSUE TITLE
Shamans cant cast totems while silenced

### ISSUE THREAD

**Issue by sirdouchelton** [ccshiro/cc-buglist#63]
Shamen can currently not cast totems while silenced. Totems are supposed to be a physical spell and not be affected by silence effects. This is a major bug for shamen in pvp.

Evidence can be found here:
http://www.wowwiki.com/Shaman_totem

**Comment by Iliana-sc** [comment]
That evidence does really hold up, the history page for TBC does not mention it and this post on AJ contradicts it as well (post isn't about TBC though, but it at least means it worked like this in the past)
http://www.arenajunkies.com/topic/236870-totems-and-silence/

**Comment by ktoja** [comment]
Please try to collect more evidence before closing such a major issue. Here you go, take attention to another shit talking thread http://www.mmo-champion.com/threads/1261684-Silence-applying-to-totems where people notice few times that this feature was implemented not so long ago (2013-02-08).
 I clearly remember that shaman could pop up totems while silenced in TBC.

**Comment by ktoja** [comment]
"All totems are now considered spells, and summoning totems can be prevented by silencing effects."
http://www.wowwiki.com/Patch_5.1.0

**Comment by ccshiro** [comment]
I'm looking through the spell data of the client (notice that this is data put there by Blizzard and is almost always correct), and they're marked as spells already :S.

For example, fire nova totem (id: 1535), has the following data:
School: Fire
Class: Magic
Preventable: By silence

Given this data contradicts the (otherwise seemingly reliable) evidence, I really think, with these contradicting factors, we need a video that shows this to make sure we're absolute certain there's not something else going on here.

**Comment by exltus** [comment]
You can´t cast totems while silenced on TBC. This become on WOTKL (they move totems to physical school). I can prove it by this: [here](http://rrvs.blogspot.cz/2008/06/wotlk-and-illidan.html) is article (from september 2008), that is talking about possible new features in becoming of WOTLK. In this article you can find one pretty sentence

> There's also a shaman rumor that you'll be able to cast totems while silenced due to them being moved to the physical school.

Note that they are talking about this change like about "RUMOR" - so it means, that it definitely is not working on TBC. 
And about your wiki link - here is [same page from 2008](http://web.archive.org/web/20081014051714/http://www.wowwiki.com/Shaman_totem)
, but there is nothing about totems and physical spell school. So this post is INVALID

**Comment by Barroth** [comment]
Watched quite a few videos and wasn't able to find a shaman placing totems during silence. As stated above Wotlk made totems to be a physical spell (patch 3.0.2).

**Comment by ktoja** [comment]
Somehow i garbled patches, my bad. Here's another solid evidence on silenceable totems: http://www.warcraftmovies.com/movieview.php?id=73041 at 12:37 spamming grounding while CS'ed

**Comment by ghost** [comment]
ok so this can safely be rejected as invalid

**Comment by ccshiro** [comment]
@ktoja Thank you for that video.
