### ISSUE TITLE
Escape from Firewing Point! - wrong message & weird NPC respawn time

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#631]
When you fail the quest the NPC (Isla Starmane) still thanks you for helping her escape (check the chat  on the screenshot)... 
Also, I was killing mobs here for 30 minutes and she didn't respawn. I guess her respawn timer is kinda too high.
![wowscrnshot_060515_180456](https://cloud.githubusercontent.com/assets/5777848/8019862/aabc4288-0c6c-11e5-9e30-130ac513aab1.jpg)

**Comment by ccshiro** [comment]
@ccnim This is actually your bug. The wp end event is marked as don't care if it was successful or not (might want to make sure others aren't marked incorrectly as well).
