### ISSUE TITLE
[Hunter] Steady shot 

### ISSUE THREAD

**Issue by Klvn123** [ccshiro/cc-buglist#638]
Steady shot does not add additional damage. Can fraps recount if needed, but its pretty clear it does not add any damage.

**Comment by Dpthx** [comment]
It works just fine for me. Perhaps you're not reading the tooltip, it only adds damage when the target is dazed

**Comment by Chulain** [comment]
base weapon dmg + x, additional y  against dazed
![283e8918-0c73-11e5-9b6f-44ccaa9f23d6](https://cloud.githubusercontent.com/assets/10247793/8023250/98a5b516-0d02-11e5-8e51-f9bf89d60ab3.png)

**Comment by maronics** [comment]
Actually, I can relate. 
![steadyshot](https://cloud.githubusercontent.com/assets/12777028/8020558/8ca5d866-0c7d-11e5-8d3f-9d680593193d.jpg)

Minimal difference in damage.

Edit: More testing.
![steadyshot](https://cloud.githubusercontent.com/assets/12777028/8022193/207cf648-0cc2-11e5-93ee-83c414e74481.jpg)

The little discrepancy in overall damage comes from 4p t5 which ich just realized after all those shots.

Against dazed targets, the 175 bonus damage seems to apply, the normal bonus still doesn't

**Comment by Klvn123** [comment]
if ill have a chance ill record aswel, but i did around 300k in damage and auto shot and steady shot had the same damage if you take away crit RNG. What i mean by that is that average damage of auto shots and average shots of steady shots were close to exactly same.

**Comment by TheVcelar** [comment]
works fine for me... here is calculation:
SteadyShotDamage = DamageModifiers_(150 + (WeaponDamage/WeaponSpeed)_2.8 + 0.2*RAP + [Dazed: 175]) 
dont forget armor

**Comment by Klvn123** [comment]
<a href="http://imgur.com/pA4OPgn"><img src="http://i.imgur.com/pA4OPgn.png" title="source: imgur.com" /></a>

**Comment by maronics** [comment]
Fun fact: I got 486/1132 average hit/crit with 13dps arrows, only 473/1100 with 32dps arrows over 100 steadys each. We don't even fucking know anymore.

BUT: If the bossdummy has around 7600 armor (nim wouldn't confirm/deny :3), the damage from the formula would actually fit. Then it's a tooltipissue.

**Comment by ccshiro** [comment]
Tried against a target dummy for 10 minutes, the min max and avg matches what it should be. If it's bugged in any way it's more subtle than steady shot itself just being broken.
