### ISSUE TITLE
Rogue Poison Quest: Deep Cover

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#639]
During the Quest Deep Cover You're supposed to make an npc friendly by using flares and the /salute emote. This works, and he does turn friendly but you can't turn in your quest to him. This is fixable by relogging.

**Comment by ccnim** [comment]
There is no need to report vanilla content bugs unless they are abusable. I will eventually do this quest since Im working through vanilla so I will close this issue.
