### ISSUE TITLE
[Druid Trinket] Living root of the wildheart - not proccing at all

### ISSUE THREAD

**Issue by LikeVenom** [ccshiro/cc-buglist#640]
"Equip: Your spells and attacks in each form have a chance to grant you a blessing for 15 sec."

i know SSC isn't supposed to come out on the first release, but either way, a bug is a bug. tested for about 10 minutes and didn't get any procs, regardless of doing damage in cat, bear or healing with spells.

**Comment by LikeVenom** [comment]
please delete. i've gotten some procs now. dunno why didn't they occur earlier tho and for a long while :S sorry for posting.
the proc rate is really low. got like only 2 procs in 10+ minutes, of which one of them was on casting prowl.

**Comment by ccshiro** [comment]
If you think there's no bug you can close the issue yourself. No one can actually delete it though, I think.
