### ISSUE TITLE
[Minor] Rogue poison quest: Mission: Possible But Not Probable

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#641]
For this quest you're tasked with killing some npcs, killing Grand Foreman Puzik Gallywix for his Head and looting the chest he is guarding for the item: Cache of Zanzil's Altered Mixture. The grand foreman however, seems to drop both the head and the mixture, making the chest obsolete. The chest does contain the mixture if you decide not to loot it from the Foreman though.

**Comment by ccnim** [comment]
I'm working on vanilla currently so there is no real need to report them since we haven't done it yet.
