### ISSUE TITLE
[Rogue] Sap with target moving.

### ISSUE THREAD

**Issue by ceyscro** [ccshiro/cc-buglist#642]
When a target is moving and you sap it, it still moving during a little period of time so you can't do anything on it until sap ends. Does not happen when target is not moving.

Here  the video to see the strange "movement"

https://www.youtube.com/watch?v=anDdeBUH-EE

EDIT : It does not happen every time but very often, sometimes happen with other stuns too.

**Comment by Voodopad** [comment]
Had the same issue in arena, this explains why target was far away when I was standing inside the circle.

**Comment by CarboCorecraft** [comment]
I noticed that bug as well during August 6, 2015 test. In my case target was sliding while being stunned:

https://youtu.be/XYo8ejfLjcY
