### ISSUE TITLE
Ritual of summoning not working in netherstorm

### ISSUE THREAD

**Issue by mr2tal** [ccshiro/cc-buglist#643]
Have tried using Ritual of summorning in the netherstorm, and i got the "you can not use it here" error,
Will try test in other zones too.

Image: http://imgur.com/88chexL

Tested Ritual of summoning in shattrah and it works there.

Update: works fine in any zone, except netherstorm, tested near the tempest keep and area 52

**Comment by ccshiro** [comment]
This is the intended behavior.
