### ISSUE TITLE
Unable to use spells because they person is fleeing after loosing a duel

### ISSUE THREAD

**Issue by mr2tal** [ccshiro/cc-buglist#645]
Feared a mage and won the duel while he was fleeing. after he was unable to use any spells, as he was still counting as "fleeing"

**Comment by tasinx** [comment]
Ran into the same issue, fixed after a relog.
http://oi60.tinypic.com/2u5qaz4.jpg

**Comment by matsdreyer** [comment]
I believe #656, #663 is reffering to the same same issue.

I experienced this after a death while fleeing.
Only a relog would solve the problem.

I was not able to use spells or items (hearthstone, mount).

The error message was "Can't do that while fleeing."
