### ISSUE TITLE
Hellfire Ramparts first pull pathing issue

### ISSUE THREAD

**Issue by Shanwerd** [ccshiro/cc-buglist#647]
If I distract and sap one of the guards at the bridge and engage the other one the sapped guard will remain frozen in place when sap ends

**Comment by ccshiro** [comment]
Please report movement issues as described in the paste, namely:

> Please target the NPC that is bugging, and while the bug is happening, type
> ".movegens --verbose" in chat (without quotation marks) and take a print screen
> of the output and the broken NPC visible in the screenshot.

**Comment by Shanwerd** [comment]
here the screenshot:
http://imgur.com/QIOMw0S
