### ISSUE TITLE
holy paladin t5 4 piece set bonus

### ISSUE THREAD

**Issue by Doope** [ccshiro/cc-buglist#648]
Flash of Light crit properly gives you the 0.5 cast speed for the next holy light, on the other hand Holy Light crit doesnt give you anything. It might be bugged like Druid's nature grace talent or it doesnt work at all. Seems like the buff consumes itself.

note: when i crit with holy light i cant get the effect for 1 min which is working correctly

**Comment by Twizzerious** [comment]
this may not be a bug,
Were you speced into Lights Grace in the holy talent? Because Lights grace buff will override the t4 set bonus buff. So what is probably happening is you are recieviung the t4 set buff then it is being overriden by the Lights Grace buff.

**Comment by Doope** [comment]
http://www.wowhead.com/itemset=627/crystalforge-raiment#comments

-"Does anyone know if the 4 piece set bonus stacks with Light's Grace?"
-"Yes it does and stacks with any spell haste you may actively have at the time."
-"Yes it does indeed! If you happen to have all 3 buffs up it makes holy light a 1.5Second cast, just like flash of light! Take note- set bonus procs once per minute. it funs but rarely ever see it :("

**Comment by Twizzerious** [comment]
then that is what seems to be the bug. You can replicate it by casting a holy light (non crit). this will give u the lights grace buff. Then cast divine favor - flash of light forcing it to crit. You should now have both the lights grace buff and the 4 piece bonus buff.

Right now they are not stacking. Probably should edit your post or title

**Comment by Chulain** [comment]
set bonus buff: http://www.wowhead.com/spell=43837
currently works without the talent "light's grace" however when you spec into it, the set bonus doesn't proc at all
![wow_2015_06_07_10_58_57_243](https://cloud.githubusercontent.com/assets/10247793/8023276/affce9e4-0d04-11e5-9651-00028473eb98.png)

**Comment by Wolper321** [comment]
right now these auras don't stuck (it's bug, otherwise this set bonus is useless). But other mechanic work ok (1 per minute, it works after flash heal crit too).
