### ISSUE TITLE
Movement bugs with charge/death coil

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#649]
Talked to my target on mumble as it happened, on his screen things looked just fine, but on my screen it skipped the death coil movement and just teleported him to the location after it was done.

http://webm.host/2b8c6/vid.webm

I also saw it at a few other times, often with spells combined with someone using charge.
I don't remember stuff like this happening on the previous test

**Comment by Klimpb** [comment]
Probably related: http://webm.host/44acf/vid.webm

**Comment by Danddelion** [comment]
I can confirm that to me everything looked normal with that kidney shot stun in the second video, i did not suddenly teleport to another location.
