### ISSUE TITLE
Caverns of Time Quest

### ISSUE THREAD

**Issue by nz54445** [ccshiro/cc-buglist#65]
We got a group for CoT to test out OHF. 1 of us had done the quest before, 4 of us had not done the quest before. When we took the quest, we took the quest shortly after each other, so the npc's named: custodian of time, stacked quite quickly. One of our group members did not hear whispers from it, while another got multiple whispers. The group member that did not hear whispers did not get a completed quest. Also, the custodian continued the march after the quest was completed, and continued whispering to me just as if i was on the quest. You can see it in the screenshot here:
http://pbrd.co/1wiLVul

As you can see, the whispers continue, but i am on the next quest (and also, as it is more evident, the buff timer is at 4 minutes).

**Comment by PolarCookie** [comment]
I was in this group and can add to this.
In the following picture you see me getting double whispers, at times I was getting whispers from all 4 custodians.
There is also a npc twin pair (not quest related, screenshot was taken after completing the tour) walking in the same path.

![wowscrnshot_011715_201331](https://cloud.githubusercontent.com/assets/1158801/5793425/481829da-9f43-11e4-9185-dd72379fcd11.jpg)
