### ISSUE TITLE
Devour magic doesn't remove stealth

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#650]
http://webm.host/96e64/vid.webm

Fairly sure that this is a bug.

**Comment by ccshiro** [comment]
Stealth is not a magic buff, so I don't think it should?

**Comment by Klimpb** [comment]
@ccshiro well of course but I was more thinking because the rogue got hit by a spell, kind of like curse of elements doesn't do any damage but it removes stealth.

Not sure if it's the same for devour magic.

**Comment by lynxzor** [comment]
"if you catch a rogue on proximo just as a match starts, put your pet on him and turn auto devour on so it will unstealth him from range"

http://www.arenajunkies.com/topic/19112-devour-magic-in-general/#entry151491

**Comment by robinsch** [comment]
Every spell hit should reveal stealth, there were some exceptions added in 2.3 like earthbind and mass dispel. 

https://github.com/TrinityCore/TrinityCore/issues/14819

**Comment by ccshiro** [comment]
@robinsch that's an interesting observation. Thanks.

**Comment by robinsch** [comment]
@ccshiro: Also Shadowstep should not break stealth on spell hit. (Rogue shadowsteps another rogue).
