### ISSUE TITLE
Sethekk Halls: Fear / Stun Bug

### ISSUE THREAD

**Issue by RealZwox** [ccshiro/cc-buglist#656]
Wenn you get feard by  him: http://www.wowhead.com/npc=18325/sethekk-prophet#abilities  (http://www.wowhead.com/spell=27641/fear )

At get stuned at the same time from http://www.wowhead.com/npc=18321/sethekk-talon-lord#abilities
( http://www.wowhead.com/spell=32654/talon-of-justice )

When the Fear breaks you are Bugged and can do nothing only move ( You cant do dat while fleeing )

**Comment by RealZwox** [comment]
Same for: Slave Pens

Get feard by : I cant find the Mob who fear on wowhead o.O But one Mobtype fear there

And get Rooted by: http://www.wowhead.com/npc=17961/coilfang-enchantress#abilities 
( http://www.wowhead.com/spell=32173 )

Seems if you get feard and at the same time stuned or rooted you can do nothing after fear breaks       ( You cant do dat while fleeing )

**Comment by PolarCookie** [comment]
this happened in SL and MT too, fear from the fel overseers and nexus terrors respectively
