### ISSUE TITLE
Critical Strike visual bug

### ISSUE THREAD

**Issue by KuroiKensai** [ccshiro/cc-buglist#658]
My 70 lvl nude undead rogue must have 4,18% + 5% from talent, but ingame menu show 0.00%.
When I start to put closes on - it still say 0.00 till some moment. I must have about 17% of crit, but it shows only 7%. I think % are working fine, but displayed wrong.

**Comment by KuroiKensai** [comment]
After playing for a while it started to show correct %. Dont know what was the cause, maybe insta 70 lvl.

**Comment by zixsen** [comment]
Did you have max weapon skills?

**Comment by KuroiKensai** [comment]
Dont remember. But it still was 0.00% even with 5% from talent which is not connected to weapon skills for sure.

**Comment by ccshiro** [comment]
Working as intended if you didn't have any weapon skill points.
