### ISSUE TITLE
Talents of movements imparing effect reduction on Mind Flay

### ISSUE THREAD

**Issue by sirdouchelton** [ccshiro/cc-buglist#66]
Talents like shamans toughness talent reduces Mind Flays slow from 3 to 1.5 seconds (is as it should) but it also reduces the duration and the number of damage ticks from 3 to 1. So instead of it being a 3 second channel with 3 ticks of damage it becomes a 1.5 second channel with 1 damage tick.

It should reduce the slow duration, but the overall duration and number of damage ticks should stay the same, 3 seconds and 3 ticks.

**Comment by ccshiro** [comment]
I'm quite willing to believe that these effects should NOT reduce the duration of the mind flay, but at the same time it seems strange to me that the mind flay would be affecting the target while its slow-component runs out mid-way through. Initially I would've said (with no basis, of course) that it seems logical if the reduction effect has no effect on mind flay.

Some research to prove how it actually works would be most welcome.

**Comment by Philosophers** [comment]
From my exp mind flay is not affected at all, so I decided to look for a proof.

https://www.youtube.com/watch?v=pJ1EHzyW63s

Look 3.00 +

What is happening there?
Spriest fights enh shaman (99% sham is pvp build). Mind flay cast is 3.0 sec (unchanged), shaman uses earth shock at about remaining ~0,6 sec and he is slowed briefly after mind flay fades.

Not 100% sure if this guy has this talent, but if he has at least 1 point in this video shows exaclty that mind flay is not affected by slow reduction effects. Slow is not too, as can be seen. Can't find better video.

My conclusions:
Mind flay damage ticks are not affected by slow reduction effects.
Mind flay slow duration is not affected too (my guess it kinda works like earthbind totem, applying slow over and over)

**Comment by ghost** [comment]
this indeed looks like an exception to the talent

cant think of any other channelling spell that has a 'slow' component

**Comment by ccshiro** [comment]
@Philosophers Thank you for the video. While it doesn't confirm the workings, it seems as good as an indication we'll get.

Therefore I will go with mind flay not being affected by these talents at all. And proof that that's wrong can be submitted by anyone that thinks it is indeed not correct.
