### ISSUE TITLE
Gear disappearing

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#667]
When I was equipping new item into the slot already being occupied by some other item by left clicking the item in my backpack and then clicking on the slot with the old item the old item disappeared.
It happened to me two times.
I wasn't able to reliably reproduce it though so I'm not sure what is the exact cause of the issue.
Both times when it happened I was equipping newly acquired quest reward item.

**Comment by thebigripper** [comment]
Yeah I had something similar happen to me as well. I too could not reproduce it.

**Comment by ccshiro** [comment]
I spent 3 hours trying to make this happen, by doing what's described in this issue as well as #716 and #670, but cannot for some reason.

I hope we can get this to trigger again next test, and have a video recording of it. Maybe that will shed some light on it. I will link this issue in the upcoming tests paste and ask for help, as this is a serious issue I'd like to find.

**Comment by Bzmode** [comment]
check the database for the character Plazmawave, his stats are insane after getting the internal bag error

**Comment by PolarCookie** [comment]
I had a pre-kara gear set and a t5 gear set.
When I logged on today the t5 was equipped and the pre-kara was in the bags.
I used outfitter to swap to the pre-kara, but now the t5 set had disappeared.
The empty line in my bags is where the items should have been.
I alt-f4 and log back in again.
Now my gear is as you can see it, a mix of the prekara and t5.
neck, back, weapon, shield, one ring and both trinkets are prekara and the rest is t5.

note my huge defense, the stat window says I have 598 defense rating, but manually going over my gear gives me 358 defense rating on a calculator

![wowscrnshot_070515_125415](https://cloud.githubusercontent.com/assets/1158801/8511415/0dbda2be-2315-11e5-9285-3452728075df.jpg)

![wowscrnshot_070515_130129](https://cloud.githubusercontent.com/assets/1158801/8511434/f9dc37c8-2315-11e5-84e8-5a6cf61d18dc.jpg)

being naked, I have
29 dodge rating, 15 parry rating, 50 block rating, 225 defense rating and 11480k hp
open BT right now I want to tank Illidan like this :D

**Comment by petaal** [comment]
Got this bug on video.

Before I started recording I crafted Stylin' Puple Hat and equipped it by right-clicking. It replaced the helmet I was wearing (Nordrassil Headdress). After that I bought Cowl of the Guiltless and started recording. FurioCC mentioned (https://github.com/ccshiro/cc-buglist/issues/872) that the bug may be related to having crafting window open. I can't remember surely if i had it open, but it is quite possible. Here's the video, please download (only 34 MB): https://www.dropbox.com/s/ybxdhtwe3avxivd/wow_enc.mp4?dl=1

After the video I relogged and 5 out of 6 disappeared items had reappeared in "empty" equipment slots (the missing bracer didn't reappear as I had another bracer equipped). I could also move all the equipped items normally. Here's a screenshot:

![wowscrnshot_070515_211217](https://cloud.githubusercontent.com/assets/11743711/8512971/f645bc32-2361-11e5-84ee-dfdfde4f66de.jpg)

Then I unequipped all my gear and noticed I still had bonus stats (+12 str, +25 sta, from the bracer):

![wowscrnshot_070515_211331](https://cloud.githubusercontent.com/assets/11743711/8512980/1cd5165e-2362-11e5-9673-e1889a7f5bfd.jpg)

After that I relogged again and the last missing item had reappeared:

![wowscrnshot_070515_212145](https://cloud.githubusercontent.com/assets/11743711/8512995/fb758704-2362-11e5-8083-ae67a7e1bf3c.jpg)

After I unequipped the bracer all my stats were back to normal:

![wowscrnshot_070515_212451](https://cloud.githubusercontent.com/assets/11743711/8512985/64ec5a92-2362-11e5-8442-605a19404218.jpg)

**Comment by Ickler** [comment]
I discovered the exact way / reason this occurs. Simply: spam sell something to a vendor, I made it happen just with selling two items. 

Spam selling = spam right clicking something while talking to a vendor (duh). The secret ingredient is in the spamming I think. 

Once you spam sell something, you can immediately swap pieces of your gear and the piece already equipped will be deleted, but stats kept. It looks like all but trinkets / weapons. 
This is a SS of me after doing that a couple of times.
![wowscrnshot_070515_231237](https://cloud.githubusercontent.com/assets/4713575/8513422/5ac33fdc-236b-11e5-8ee0-1b452be399e6.jpg)

**Comment by petaal** [comment]
I can confirm that this is easy to reproduce by selling items quickly. I'm not sure about the spamming being required. Managed to get this to happen by selling items fast while clicking only once per item. Nevertheless, easy to reproduce by spamming right click and selling quickly.

**Comment by xtrawelt** [comment]
Just send some flasks to an alt and they got lost. Mail was empty.

http://i.imgur.com/j6T4XQt.jpg

**Comment by darkcranio** [comment]
I think it's Kil'Jaeden stealing the items in the twisting nether.

**Comment by Lephidiles** [comment]
I lost an item during the August test.

How i lost it:

Created Bracers of Havoc + 28 slot Soulbag on my alliance priest.
Added this two to the neutral ah in Booty bay
on my second account i bought this two item as a newly created horde druid.
then immediately traded this two to my warlock horde chat on main account (same as priest)
Equipped the Soulbag and kept the item in inventory (was suppose to gem and enchant this when i got to shatt.
HSed the warlock to Shatt and when the pc had completed loading shatt i relogged to save the item
when i logged back in the Bracers of Havoc item was gone. but the soulbag was still there

@ccshiro
