### ISSUE TITLE
Warlock pets wont autocast on summon

### ISSUE THREAD

**Issue by sirdouchelton** [ccshiro/cc-buglist#67]
Imp's blood pact and Felhunters paranoia does not auto cast on demount or summon of pet, even though it is on auto cast. The imp does the sound of casting it over and over without ever casting it.

**Comment by Iliana-sc** [comment]
I can't reproduce this. Created a new lock and taught the imp blood pact. When the pet is new it does not auto cast and mounting and dismounting does not turn on auto cast (expected). After I manually turn on auto cast it stays on even after mounting with both fly and ground mounts and after relogging. Are you sure this is happening?

**Comment by effinamon** [comment]
I had the same bug. It's been working on and off from test to test. I haven't noticed the sound of casting over and over.

Note: It's not the that the castbar doesn't change to autocast. It's that the abilities (blood pact and phase shift) aren't cast/applied unless the button is pushed manually. Fireshield seems to be working correctly now.

**Comment by Iliana-sc** [comment]
Oh I actually only looked at the cast bar, I guess it needs to be looked at more properly then

**Comment by Klimpb** [comment]
can confirm.

**Comment by effinamon** [comment]
I went back and tried it again, and it looks like phase shift is functioning correctly. Although the imp doesn't cast it right away (my recollection from retail is that it used to do so almost immediately).

Bloodpact did not work.
