### ISSUE TITLE
Equipped gear disappeared

### ISSUE THREAD

**Issue by Gerelos** [ccshiro/cc-buglist#670]
I just bought a fresh full set of Light Mail armor from Nabek, the Weapons and Armor Merchant in Azure Watch, Azuremyst Isle.  As I equipped each new piece of armor from my bag by right clicking it, it successfully equipped, but covered and destroyed the armor I had been wearing, instead of switching my previous armor into my bag.  I was wearing 2 quest rewards: a Weathered Mail Tunic and some Beaten Chain Leggings, and the rest was Tarnished Chain armor from the armor vendor at the Crash Site.  The only armor piece I was wearing that successfully switched out into my bag was my chestpiece, the Weathered Mail Tunic.  I had 19 empty bag slots at the time, so I don't believe the bug is related to having a full inventory.  This wasn't a big deal at level 5, but this would be a huge deal at level 70.

**Comment by lynxzor** [comment]
#667
