### ISSUE TITLE
Cenarion Thicket, missing debuff aura

### ISSUE THREAD

**Issue by nullfoxh** [ccshiro/cc-buglist#672]
Cenarion thicket, the place right outside of shatt with the teromoths is lacking the debuff aura that that turns you green and gives you -5% stats.

How to reproduce? 
1. Go to Cenarion Thicket
2. Don't turn green

Related:
http://www.wowhead.com/spell=32407/strange-aura#comments
http://www.wowhead.com/spell=35956/strange-aura#comments

**Comment by nullfoxh** [comment]
Seems like the corpses of fallen druids in the area should also be affected by this debuff, judging by the screenshots found here: http://www.wowhead.com/quest=9971/clues-in-the-thicket#screenshots

**Comment by ccshiro** [comment]
@ccnim for some reason this spell is not in spell_area.
