### ISSUE TITLE
[Warlock] Inferno

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#677]
When casting Inferno, Infernal always spawns at the caster's feet, not where it was told to land. Also, it didn't attack Arena goblins near Ring of Trials in Nagrand, don't know if that's intended.

**Comment by lynxzor** [comment]
Related to #583

**Comment by Adunai** [comment]
Another issue is that Infernal cannot attack a target (if you issue a command "Attack") if it's in Defensive or Passive stance. If it's in Aggressive, it can attack.
Screenshot: http://i.imgur.com/SngWiLJ.jpg

**Comment by darkcranio** [comment]
Look around maybe? #588

**Comment by lynxzor** [comment]
This one is a lot easier to understand at least.

**Comment by ccshiro** [comment]
Please do not post unrelated issues as comments. I opened a new one #719. Also duplicate.
