### ISSUE TITLE
[NPC] Frezza

### ISSUE THREAD

**Issue by Adunai** [ccshiro/cc-buglist#684]
This NPC is supposed to be hostile to the Alliance, but is not flagged for PvP. Is that intended? Steamwheedle Bruisers are flagged for PvP, however.

Also, Frezza should announce the arrival of the zeppelin (as indicates a comment as of patch 2.2.0). On CoreCraft, he does not.

Screenshot (Frezza): http://i.imgur.com/1OyFyZr.jpg
Screenshot (Steamwheedle Bruiser): http://i.imgur.com/4dy8hdr.jpg

Link (Frezza): http://www.wowhead.com/npc=9564/frezza#comments:id=159416
http://www.wowhead.com/npc=9564/frezza#comments:id=362576
Link (Steamwheedle Bruiser): http://www.wowhead.com/npc=16096/steamwheedle-bruiser

I haven't looked at other zeppelin masters around the world but they can have these issues, too.

**Comment by ccshiro** [comment]
Him not being pvp flagged should be correct as those flags were sniffed by mangos back when. Also, we opted out of doing the arrival/where is the zeppelin event for now.
