### ISSUE TITLE
(Slave Pens) Pathing

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#685]
http://www.twitch.tv/faleene/c/6801439

Mage blinked through the world and the mobs evade bugged.

**Comment by ccshiro** [comment]
I tried this 16 days ago when I added the label and I could reliably reproduce it (every time), now I can't make it happen any longer. Maybe the fixing of some other pathing bug fixed this one, or I'm just really bad at it now for some reason. Anyway, I'm closing this for now, reopen if you find it again please.
