### ISSUE TITLE
Quest : "Bring Me The Egg!"

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#69]
On the second part of the quest, after lots of attempts trying to get the egg with the "Jump-a-tron 4000", I got the egg but the lvl 66 elite can not be attacked : http://snag.gy/LXFcE.jpg

**Comment by Iliana-sc** [comment]
it can if you actually wait for it to fly in, corecraft just has the RP pathing working as it should

**Comment by Whatsthis880** [comment]
You're right :) it came down after a minute or so

**Comment by Whatsthis880** [comment]
The pathing was kind of weird and took way more time than this video for instance ( https://www.youtube.com/watch?v=BRBMmwsfPP0 at 0:45) but in the end the bird was here !

**Comment by effinamon** [comment]
I have reported the same very very slow RP a while back.
