### ISSUE TITLE
(Druid) Force of Nature

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#690]
Here is how they spawned/followed on TBC in 2007 https://www.youtube.com/watch?v=Yp-mc0TiOM4

And here is on Corecraft http://www.twitch.tv/bzmodetwitch/c/6801665
http://i.imgur.com/zFe6Qb6.jpg

as you can see they stack very tightly when attacking moving and follow when they should have a slight spread

(I know the bug where they spawn on top of you instead of where you target them has been reported and is related to other similar bugs with channeled aoe spells such as blizzard and rain of fire)

**Comment by ccshiro** [comment]
Same bug as #583 (despite that report's name).
