### ISSUE TITLE
[PRIEST TALENT] Surge of Light

### ISSUE THREAD

**Issue by Oldwal** [ccshiro/cc-buglist#691]
The priest talent Surge of Light says :

"Your spell criticals have a 50% chance to cause your next smite to be instant cast, cost no mana but be incapable of a critical hit. This effect lasts 10 sec."

This is bugged since the fee instant smite actually can crit now, and this can in turn proc a new free instant cast and so forth.

**Comment by lynxzor** [comment]
Duplicate #669
