### ISSUE TITLE
SnD & LoS

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#7]
Should Slice and Dice require LoS to the target?

**Comment by sasfog** [comment]
https://www.youtube.com/watch?v=BDHZbBSwAzI#t=2m23s (2 min 23 sec)
In this video, the rogue uses Slice and Dice on the priest while he's out of sight.
https://www.youtube.com/watch?v=uFygBGEjGI4#t=8m14s (8 min 14 sec)
I'm not entirely sure whether the druid is already out of sight, but posting for possible reference.

**Comment by ccshiro** [comment]
@sasfog nice find!
