### ISSUE TITLE
Blood Furnace: trash mobs in the corridor between first and second boss started evading when kited

### ISSUE THREAD

**Issue by brndd** [ccshiro/cc-buglist#700]
(posting some bugs for another person who doesn't have a github account)

in the entrance to the green corridor between 1st and 2nd boss, mobs were stuck on evade and climbed up the wall when we tried to pull them into the room before (1st boss room)

![untitled](https://cloud.githubusercontent.com/assets/5822375/8024069/325af2b2-0d2f-11e5-9f61-13a37f9be7a2.png)

**Comment by ccshiro** [comment]
As the paste said, movement bugs must be reported with a screenshot where you show the output of ".movegens --verbose" and the bugging mob, or we won't be able to see what happened. Please try this again next test and report it properly if it happens again. Cheers.

(I couldn't make them evade, btw.)
