### ISSUE TITLE
[Item Drops] Mote of Shadow

### ISSUE THREAD

**Issue by Wtfeater** [ccshiro/cc-buglist#702]
Scorched Imps in the subzone Skald in Blade's Edge drop Motes of Shadow. According to the 2.1 patchnotes, most demons no longer drop motes of shadow. 

"Motes of Shadow now primarily drop from void creatures and have been removed from nearly all demons."
According to Wowhead, these imps are not supposed to drop this item.

http://www.wowhead.com/npc=21021/scorch-imp#comments
http://us.battle.net/wow/en/game/patch-notes/2-1-0

http://i.imgur.com/5At8Qok.jpg

**Comment by ccnim** [comment]
Since we are trying to replicate how it was in 2.0.3 this will remain. On the contrary though if you find something that shouldn't be in 2.0.3 be sure to report it.
