### ISSUE TITLE
Murkblood Idols for Vile Idolatry keep dropping after quest is completed

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#704]
Even if you already have the required amounts of Murkblood Idols they will keep dropping and will be kept in your inventory after you turn in the Q
![wowscrnshot_060715_120426](https://cloud.githubusercontent.com/assets/5777848/8024132/b403af14-0d31-11e5-9db4-e5c0295fd70c.jpg)

**Comment by netherspite** [comment]
Not a big deal anyway, if you couldn't reproduce just close and ignore it.

**Comment by ccshiro** [comment]
Tried it as well, doesn't seem like it happens for me either. Will close the issue. If you figure out what happened you can make a new one next test.
