### ISSUE TITLE
Gordawg's Imprint is empty

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#706]
Gordawg's Imprint item provided by the Gordawg for the quest Eating Damnation should contain the map with the locations of Enraged Crushers in Nagrand : http://www.wowhead.com/item=24475/gordawgs-imprint
However, it is empty:
![wowscrnshot_060715_110453](https://cloud.githubusercontent.com/assets/5777848/8024146/ecb9a82c-0d31-11e5-848e-baf1108cb2bd.jpg)

**Comment by ccnim** [comment]
The item uses page_text ID 2944 as it's content, the content uses HTML to link an image.
