### ISSUE TITLE
Quest:Dimensius the All-Devouring Npc Captain Saeed did not work

### ISSUE THREAD

**Issue by theGever** [ccshiro/cc-buglist#707]
I tried the q and I got credit for talking to the Captain but I did not get the chat bubble icon needed to start the event. The chat text was also different. As I recall in retail he says that he is waiting for the fleshling who destroyed the Warp Conduict.

**Comment by lynxzor** [comment]
It's not implemented yet #167

**Comment by theGever** [comment]
alright, since it's beenreported earlier I close it
