### ISSUE TITLE
[PET] Overaggro

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#708]
When you overaggro your pet it will try to get behind the target as it is no longer tanking. This causes the pet to run away from you while the target runs towards you. This causes the pet to come to far behind the target to manage to attack it.

https://www.youtube.com/watch?v=5ARNhe14avA

from 10 sek to 20 sek

**Comment by Klimpb** [comment]
related to #548

**Comment by Lephidiles** [comment]
@ccshiro not sure if this is on the server atm but still seems to be bugged.
