### ISSUE TITLE
Mechanic: Seals and Judgement

### ISSUE THREAD

**Issue by RettiPretty** [ccshiro/cc-buglist#71]
If you use Judgement on a target, and then you instantly reseal, the Judgement is casted from the new seal.
I guess it might be some kind of delay set on Judgement.
It's really a very short period of time, almost instant.
After years of playing paladin I learned to do this automatically and isntantly, but the seal keeps disappearing.

**Comment by ccshiro** [comment]
The following are ,ost likely duplicates, verify once this is fixed just in case: #106 #233 #234
