### ISSUE TITLE
OHF last boss conversation bug

### ISSUE THREAD

**Issue by Saxyy** [ccshiro/cc-buglist#72]
In the last part of the escort, where you ask Taretha about something, and she starts the event. We clicked on the trigger twice, and two bosses spawned and said the sentence he now says twice, making an echo. I think it is triggered if two people trigger the event at once. Also, when taretha died, you could still speak with her afterwards while she being dead.

**Comment by testiecc** [comment]
Actually not sure if we were able to speak with Taretha but she did respond voice sound when she was clicked, as if she was alive.

**Comment by Saxyy** [comment]
Two of us could click her and trigger the event, but because we did it at the same time, two events started. After triggering the event, she should not be able to be talked to anymore i think?

**Comment by testiecc** [comment]
yes, she was on the ground and created female sound voices when clicked. Also we both triggered the event indeed and had two final scene going on
