### ISSUE TITLE
Spell: Mark of the sunfury

### ISSUE THREAD

**Issue by Yagrulol** [ccshiro/cc-buglist#721]
sunfury bloodwarder
spell: mark of the sunfury
bug: inside the combat log it doesn't state when the spell fades from the character

to reproduce:
Engage a Sunfury Bloodwarder in Netherstorm, wait for it to cast mark of the sunfury on you.
Look at the combat log.

Happened 5 out of 5 times on my level 70 feral druid.

**Comment by Bzmode** [comment]
this spell also can interrupt through shields

**Comment by ccshiro** [comment]
Works for me, got this message in my combat log: "Mark of the Sunfury dissipates from Shiro."
