### ISSUE TITLE
Hunter trap visible to enemy in skirmish

### ISSUE THREAD

**Issue by Danddelion** [ccshiro/cc-buglist#726]
This happened to me in 2v2 skirmish ( i think it was Nagrand Arena); one of our enemies (I was a night elf druid) was a dwarf hunter and he put down a trap which i could clearly see (not only the animation of putting down a trap, but the trap itself as well) and therefore could easily go around it.

**Comment by Lelm8** [comment]
As long as i know you can see the trap sometimes.

**Comment by ccshiro** [comment]
To quote patch 1.10: "Hunter traps now use the same rules as stealth rather than being invisible. Detect Trap has been changed to reflect this."

**Comment by Danddelion** [comment]
I did not know this. My mistake, apologies.
