### ISSUE TITLE
Ability to form temporary creature groups in the DB

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#732]
I'm adding this so we can do the following things (and more that I'm not remembering atm):
- Implement the quest "Dimensius the All-Devouring".
- Improve upon the quest "Digging Through Bones", which doesn't work that great at the moment.
- Improve upon some events in Alterac Valley which we're not fully happy with.

**Comment by ccshiro** [comment]
Related Db issues: #733 #734 #735.

**Comment by ccnim** [comment]
#736
