### ISSUE TITLE
Sheeped makes me stuck in walk (old report forgot to post it way back)

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#777]
So i got sheeped in a WSG and the wsg ended while i was in the sheep and when i got out of the wsg and sheep broke i got stuck in walk. I had to press the walk button on the keyboard to start running again.

(again this was bugged a while ago just though i should add it for checking)

**Comment by ccshiro** [comment]
Tried being sheeped as wsg ended, did not trigger it.

**Comment by ccshiro** [comment]
Will close as no further input was provided.
