### ISSUE TITLE
Sap + cc = Cc do not work

### ISSUE THREAD

**Issue by ceyscro** [ccshiro/cc-buglist#778]
When you sap someone then stun him, the stun appears but opponent can move and use any ability.

**Comment by ceyscro** [comment]
Same issue with all spells like sap, I mean maim or gouge, when you stun or root then, opponent can move and do whatever he wants.

**Comment by Klimpb** [comment]
can confirm, it's happening when two different CCs overlap

Videos of it:
http://webm.host/4e372/vid.webm
http://webm.host/4e372/vid.webm

alt-links:
https://youtu.be/v7W_94L_1F0
https://youtu.be/HUnUHESrhA4

**Comment by dmytsuu** [comment]
same + cs doesn't stop evocation and doesn't close arcane spells
https://www.youtube.com/watch?v=mpqFoQJLL0I

**Comment by YourNewfriend** [comment]
Also seemed to happen to me when I feared + deathcoiled a monster.  It didn't retain full control, but it would hit me if I got close while it was in fear.
