### ISSUE TITLE
(Warlock) Pyroclasm

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#780]
Hellfire/firestorm neither stun

**Comment by Bzmode** [comment]
we got it to stun once so it might just be the chance is extremely off

**Comment by shadowraider** [comment]
im pretty sure i've tried this few tests ago and it worked, but something may broke

**Comment by ccshiro** [comment]
With rank 2 pyroclasm hellfire has a 0.0173333 chance per tick, rain of fire a 0.065 chance per tick and soul shard a 0.26 chance. It all adds up to 0.26 for the duration of the spell.
