### ISSUE TITLE
[Worg Hide Quiver] needs to be added

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#781]
The NPC 'Trader Narasu' should sell the item [Worg Hide Quiver] to players with an 'Honored' reputation, but it's currently missing.

Item ID: 29144
NPC ID: 20240

http://www.wowhead.com/item=29144/worg-hide-quiver#comments
By Kazzen on 2007/04/11 (Patch 2.0.12):
"[...]  Heres the ammo pouch equivalent, I have both because I like to change it up a bit, its nice to have both."

Wowwiki entry (March 6, 2007)
http://wowwiki.wikia.com/Worg_Hide_Quiver?oldid=524465
"This item is sold by Trader Narasu in Talar in Nagrand. You must also be Honored with Kurenai."

Patch 2.1.0 was implemented on the 15 May 2007, so the Wowwiki entry should be enough evidence.

**Comment by mara1987** [comment]
Please don't forget to check the Mag'har equivalent then:

http://wowwiki.wikia.com/Clefthoof_Hide_Quiver

Sold by Provisioner Nasela.

Item ID: 29143
NPC ID: 20241
