### ISSUE TITLE
Pathing after CC

### ISSUE THREAD

**Issue by darkcranio** [ccshiro/cc-buglist#783]
Well every mob that is CCable could produce this bug at least in Hellfire. So the bug is, when my FIRST frostbolt ends in a freeze proc from talent, after they stuck in their places most of the time, however if the Frostbolt proc the freeze on the second time, it doesn't stuck them.

**Comment by ccshiro** [comment]
This report is missing the .movegens screenshot, however nim and I managed to reproduce it. Here's said screenshot: http://i.imgur.com/P6mMvHw.jpg

**Comment by darkcranio** [comment]
Thanks.
