### ISSUE TITLE
Volley Animation Breaks And Doesn't Loop

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#785]
It should loop just like other spells like tranquility, and blizzard.

![image](https://cloud.githubusercontent.com/assets/13057166/8509192/08febcde-224a-11e5-89c3-46f42ba20403.png)

https://www.youtube.com/watch?v=9WTkPHpPca8

**Comment by ccshiro** [comment]
Just leaving the video you linked here so we have it for the future: https://youtu.be/FsUr3i0iecs?t=9m41s

**Comment by YourNewfriend** [comment]
vanilla/tbc
https://youtu.be/n-JF54fAnVQ?t=1m48s
https://youtu.be/n-JF54fAnVQ?t=2m56s
https://youtu.be/h0zLk0FbYwc?t=22s
https://www.youtube.com/watch?v=buDaqt3I-ZQ
https://youtu.be/uP-B_BrIwK4?t=1m19s (nelf hunter on top right)

broken on wotlk beta:
https://youtu.be/Aaf9hl_Eua8?t=26s
working on wotlk beta?
https://youtu.be/JWiZYyhVng0?t=40s

If the animation to make it loop exists in the files, then I guess it should be implemented, but if it doesn't, then whatever.

**Comment by ccshiro** [comment]
It just seems to be the bow shoot emote; not a spell animation per se. I will add the shoot emote of your bow each volley tick, and see if that looks correct.

**Comment by ccshiro** [comment]
Update: the emotes for shooting seems to have been added in wrath. The only conclusion I can see being that the volley tick spell had a client-side shoot animation if it worked prior to WotLK, and for some reason that animation wasn't on the spell in 2.4.3.

**Comment by YourNewfriend** [comment]
It seems to me like it was broken / fixed several times throughout TBC into the beginning of Wrath, and 2.4.3 might have been one of the patches where it was broken.
