### ISSUE TITLE
[Blackened Leather Spaulders] needs to be removed

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#786]
[Blackened Leather Spaulders] needs to be removed. It was added in patch 2.1.0.

Item ID: 29148

Evidence:
There is a Wowhead comment on the horde equivalent shoulders [Talbuk Hide Spaulders]
http://www.wowhead.com/item=29147/talbuk-hide-spaulders#comments
"I'm happy to announce that Kurenai gets similar shoulderpads in the 2.1.0 content patch
http://img125.imageshack.us/img125/4145/newroguevf5.jpg "

**Comment by PatchnotesTBC** [comment]
Dont think they will remove gear if i have understood correctly

**Comment by ccnim** [comment]
Seems like an oversight on Blizzards part, gonna keep these in.
