### ISSUE TITLE
Talent: Inspiring Presence

### ISSUE THREAD

**Issue by sverkersham** [ccshiro/cc-buglist#787]
> Inspiring Presence
> Racial Passive
> Instant
> Increases chance to hit with spells by 1% for you and all party members within 30 yards.

on Corecraft the buff only applies to party members and not yourself.

**Comment by ccshiro** [comment]
Not correct. The buff is only visible on other players. The draenei still get the effect, just not a visual buff. This is the correct behavior, and how it was on retail as well.
