### ISSUE TITLE
Mind control abuse

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#79]
Using my spell "Mind control" every 30 meters or so, I could bring the NPC all the way from the village behind me to here ==> http://snag.gy/iNiLH.jpg . I could have gone way further as it seems that the NPC reset its aggro at the end of each mind control. Is it normal ?

**Comment by Iliana-sc** [comment]
It works like that with any other spell as well doesn't it? Is this not just because of the normal mob kiting rules?

**Comment by ShuTestCC** [comment]
Looks normal to me. You could also kite it far away by simply attacking it every few seconds of kiting, unless it got a specific area where it automatically resets upon leaving it (like most world bosses, for example).
