### ISSUE TITLE
PvP Flag Becomes Invisible When Logging Off And On

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#791]
It's visual.  It could be that relogging does totally remove it at some point.. I'm not sure of that, but neither should be the case according to common knowledge, and this article:
http://wowwiki.wikia.com/PvP_flag

![2](https://cloud.githubusercontent.com/assets/13057166/8509256/a189e8c6-224e-11e5-8547-1fb8cd5b871a.png)

In this screenshot, my PvP flag is in fact enabled, and it isn't visible.

To reproduce: 
Log in and type /pvp (or right click the player portrait and enable it)
Log out
Log back in

**Comment by YourNewfriend** [comment]
https://youtu.be/fbOAg7mKfMU?t=1m40s

Shaman logs out, and logs back in with his PvP flag intact.

**Comment by ccshiro** [comment]
Tried on retail by turning pvp flag on in a friendly zone, then off before logging off. Results were:
- PvP flag remains on relog in friendly zone.
- PvP timer does not count down while being offline (i.e. being offline for more than 5 mins does not clear it).
- PvP timer is reset if you log off before it expires (i.e., relogging while it's still active will make it restart at 5 mins when you come back online).

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/791

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/1279

**Comment by YourNewfriend** [comment]
https://github.com/ccshiro/cc-buglist/issues/1279
