### ISSUE TITLE
[Vanilla] [Orgrimmar] Orgrimmar Guards Don't Salute

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#793]
Not a TBC issue though.

Typing /salute to them doesn't respond in an emote.

**Comment by nz54445** [comment]
Very similar to, since it already has a mention of Silvermoon guards and emotes and a topic is ongoing there. #682

**Comment by YourNewfriend** [comment]
If memory serves me right, they should pause, look at the player who saluted them, and then salute.  I'm currently looking for video proof of this

**Comment by YourNewfriend** [comment]
http://wowwiki.wikia.com/Easter_eggs?oldid=1622295
"Guards of cities will respond to some emotes such as /wave, /rude, /kiss or /salute. This does not apply to all guards though, most notably Darnassus Sentinels do not reply to emotes, and even the same guard will not always respond. However, if you ask a Darnassus Sentinel about the enchanting trainer, she may respond as if you said she was enchanting."

**Comment by KimmoKM** [comment]
I haven't gone through all of the NPCs mentioned, but these two threads discuss NPCs using emotes

http://www.gamefaqs.com/boards/534914-world-of-warcraft/51359610 (most likely from WotLK)
http://eu.battle.net/wow/en/forum/topic/2226265732 (post-Cata, but as it's been established some mobs respond to emotes, all of them probably used them from the start)
