### ISSUE TITLE
Unable To Swap Players In The Raid UI

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#794]
This is what happens.  The player Buffalowings isn't actually in group 2; the UI just bugs out.
![image](https://cloud.githubusercontent.com/assets/13057166/8509369/a0a506de-2253-11e5-825f-ba408ea62b43.png)

 People should be able to swap players in the raid UI by dragging them onto eachother.  If this doesn't work, then in a 40 man raid, a player needs to be kicked for groups to be reorganized.  I've had trouble finding video evidence of this.

**Comment by Klimpb** [comment]
Think this is a client side bug that sometimes happen, I have a faint memory of this happening on retail..

**Comment by Ickler** [comment]
This is a common client side bug, often caused by addon "ClassColors" or something like that. See if you have that addon running.

**Comment by Ickler** [comment]
I know that the addon "ClassColors" or something like that bugs it if you're in combat. But that's in all cases, not just when "hotswapping" members. Although probably not linked to this very issue.

**Comment by YourNewfriend** [comment]
http://wowwiki.wikia.com/Raid_group?direction=prev&oldid=1660257
"Firstly you can organize the raid groups by dragging the members around the window into the slots available. (Dropping a player on top of another will swap the two players)."
