### ISSUE TITLE
misdirection - volley

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#797]
volley consumes applications of misdirection, it shouldn't

https://www.youtube.com/watch?v=FsUr3i0iecs&feature=youtu.be&t=575

**Comment by Barroth** [comment]
Patch 2.2: "Volley: This spell is now affected by area damage caps. Its bonus 
   damage coefficients have also been increased. It also correctly 
   consumes charges of Misdirection."

seems like it was just bugged at some point, looks like it doesnt consume charges but still gives the pet aggro.
