### ISSUE TITLE
[Sporeggar Tabard] needs to be removed

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#798]
[Sporeggar Tabard] needs to be removed. It was added in patch 2.1.0.

Item ID: 31775
Vendor: Mycah
NPC ID: 18382

http://www.wowhead.com/item=31775/sporeggar-tabard#comments
By Saurom on 2007/05/25 (Patch 2.1.0):
"Sporeggar now has a tabard. Like the rest, it is only obtainable once someone gets exhalted."

**Comment by Chulain** [comment]
http://www.wowhead.com/item=31775
