### ISSUE TITLE
Mind Controlling A Player Wipes Them From The Aggro Table

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#799]
Mind controlling a player whether it's alliance>horde, alliance>alliance, or horde>horde shouldn't matter, and it shouldn't affect the hate list of the monster attacking the player.

Reproduction Guide:
*Create a priest
*Create a "whatever"
*"whatever" gains aggro on a mob
*command priest to cast mind control on "whatever"

Proof:
https://www.youtube.com/watch?v=OKdWeGeYS0k&feature=youtu.be&t=6m26s

**Comment by Chulain** [comment]
who's the tank

**Comment by YourNewfriend** [comment]
Whatever is the tank of course.  He gained aggro on the mob.

**Comment by Chulain** [comment]
what's the mage

**Comment by Chulain** [comment]
what's the mage

**Comment by YourNewfriend** [comment]
Not sure what should happen with monsters that are faction-aligned.  That could need a little bit of research, and it could not.
