### ISSUE TITLE
Can mace spec proc from spell attacks

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#8]
Can mace spec proc from non-white hits? This report is about gouge in particular.

**Comment by eviloncc** [comment]
http://www.wowwiki.com/Procs_per_minute. Should be helpful explains procs and instant attacks.

http://wow.allakhazam.com/forum.html?forum=243&mid=1182073326288194540. Old threat where they talk about mace stun might be helpful

**Comment by sasfog** [comment]
https://www.youtube.com/watch?v=iSH3HD1YjTk#t=23s (23 sec, there's a purple skill hit then the mace stun proc)
https://www.youtube.com/watch?v=iSH3HD1YjTk#t=13s (13 sec, after mortal strike lands, stormherald proc)

**Comment by sasfog** [comment]
Here are some possible examples for rogues, though with their fast attack speed, mace stun could have been from unshown auto attacks.
https://www.youtube.com/watch?v=_pu7JSJiYl8#t=4m33s (4 min 33 sec)
http://www.warcraftmovies.com/movieview.php?id=29670 (possible occurance at 0:52, 1:40, 5:34, 6:46, 7:30, 9:09)

**Comment by ccshiro** [comment]
@sasfog Thanks for the videos. The accumulated evidence seems to confirm that it should work as it does currently. Thanks.
