### ISSUE TITLE
losing energy on misses, dodges and parries on non-finishing moves (like mangle, shred, hemorrhage etc)

### ISSUE THREAD

**Issue by Isuel** [ccshiro/cc-buglist#80]
Whenever you miss or the target blocks, dodges or parries your special abilities, you should get back 80% of the energy of the ability, except finishing moves (which can be talented by rogues).

https://www.youtube.com/watch?v=Gqg1vEWEILU

around 3:50, the feral uses mangle on a rogue with evasion at 40 energy, then he has 34 energy left.

at 32:00, notice the rogue dodging the feral's mangle, and the feral getting from 40 energy to 32.

at around 30:00, the rogues are barely losing energy from the druid's dodges.

**Comment by Raiilan** [comment]
hmm maybe is something like hitting immune targets like in this old closed issue (maybe)

"shiv energy on immune"

https://github.com/ccshiro/cc-buglist/issues/24

**Comment by Isuel** [comment]
no, it happened to me both on players and on dummies and mobs (while i was questing)

**Comment by ccshiro** [comment]
This is already implemented. To make sure it still works nim and I did the following:
Take 2 chars, one with a lot of dodge (50%), then spam sinister strike. All dodges resulted in only a few points of energy being consumed, whereas if it hit it costed the intended amount.

Basically, seems to be working correctly already.

**Comment by Isuel** [comment]
kay, after further testing, I noticed that it only happens with mangle(cat): when it gets dodged/parried/misses/fully blocked, you lose all 40 energy of it. tested with rake, and it works fine.

**Comment by rylaiii** [comment]
Hello! 

Please check out that place with a  lot of  cool stuff, it's just awesome, take a  look http://outlook.2-stroke-porting.com/lnsevtsi

Take care, ross.porto
