### ISSUE TITLE
Players Can't Resurrect At Max Distance

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#800]
The distance at which players can resurrect, and the distance at which the dialogue to resurrect appears don't match.

![4](https://cloud.githubusercontent.com/assets/13057166/8509446/4050bc38-2258-11e5-9622-9feb1566f03c.png)
This button is a dud.  I'm unable to resurrect by accepting the Resurrect now? dialogue at the point which it appears, and a bit closer too.  Seems like it's around 3-5 yds off.

**Comment by Roarek** [comment]
I have an addon called QuestHelper that tracks objectives and the distance to them - according to it, the max distance I was able to get a "dud" resurrect button was ~36 yards. By just inching up barely (< 1 more yard) I was able to rez with the addon stating it was still ~36 yards away. I have included a video linked below. I don't know the proper distance a player is meant to rez from, however, but you can see the "dud" Accept button in action. 

https://drive.google.com/file/d/0B4ZqMxVDoS9Kak5HdXdSSFE5SHM/view?usp=sharing

**Comment by YourNewfriend** [comment]
Also affects battleground resurrection.
