### ISSUE TITLE
Trading A Player As He Trades You Simultaneously Bugs The Trade Window

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#802]
When this happens, the trade window won't appear until one participant of the trade moves away from the other participant, resulting in a "Trade Cancelled" message appearing.  They can then move back and begin trading (provided they don't trade eachother at the same time again).

Reproduction Guide:
Player 1 trades Player 2 at 0:00:30
Player 2 trades Player 1 at 0:00:30

**Comment by JayDee81** [comment]
this worked the same way on retail too

**Comment by ccshiro** [comment]
As @JayDee81 says, I remember it working like this on retail as well. Not that memory is a good source. Either way, this claim needs some proof.

**Comment by Chulain** [comment]
http://wow.allakhazam.com/forum.html?forum=21&mid=1178983195268317081
"If both people hit the trade button at the same time, it bugs out. You just have to walk away from the person until "trade canceled" comes up on your screen."
