### ISSUE TITLE
Polymorph Size Transition Is Instant

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#804]
The transformation and exit should be more graceful, like druid shapeshifting.  Currently, the size increase (when it breaks), and reduction (when it's applied) is instant.

Retail: https://youtu.be/AND-5oZBPc4?t=2m31s

**Comment by Jigodian** [comment]
Works fine for me. Tested on a lot of mobs.

https://www.youtube.com/watch?v=VZpRFCvcmbc&feature=youtu.be

**Comment by YourNewfriend** [comment]
Yea, I was just testing it on a mob with a bad size.  This is invalid.
