### ISSUE TITLE
Mechanar - Elevator

### ISSUE THREAD

**Issue by scramz** [ccshiro/cc-buglist#808]
After killing adds in front of the elevator I decided to relog. Upon coming back into game the elevator had disappeared. I tried to relog again to see if issue would fix. It would not. I went outside instance, left group and was reinvited. Elevator was showing again. 

Here is screenshot of no elevator.

![wowscrnshot_070415_174723](https://cloud.githubusercontent.com/assets/13180865/8509580/8cd0f5c6-2278-11e5-991b-7dba2656109b.jpg)

**Comment by ccshiro** [comment]
This is the same bug that plagues the deeprun tram.

**Comment by Chulain** [comment]
shiro pls 2 trams on corecraf

edit: hmm after afking at the deeprun tram for a while the trams suddenly started to work

edit 2: i logged off as soon as one tram arrived and when i returned the tram never returned, the other one was still working tho
