### ISSUE TITLE
Strange tooltip discription

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#81]
the dps test things in shattrath have a buff that heals them to full all the time

the tooltip when I mouseover is strange:

http://i60.tinypic.com/1z65yxv.jpg

i dont know if its "blizzlike" but its seems so wrong i think it belongs here

**Comment by Iliana-sc** [comment]
it's a test/debug spell that these target dummies use. you won't actually see that ever in the actual server. I guess it could happen on other tooltips too, but I haven't seen it yet.
