### ISSUE TITLE
(Halaa) Camps

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#816]
http://imgur.com/3vFPR5t

these places don't get replaced with the respective Gryphon/Wyvern camps that are used to bomb the Halaa guards

**Comment by ccshiro** [comment]
@ccnim The issues that I found: horde wyvern roots are spawned by default (should be in a despawned state), and the alliance ones aren't there at all. Which is kinda strange, since I remember it working way back, but whatever.

**Comment by ccshiro** [comment]
@ccnim Check OutdoorPvPNA.h: destroyed alliance roost are missing, and the horde ones are visible by default.
