### ISSUE TITLE
Cleave radius is too large (impossible as melee, not to get cleaved)

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#817]
Entropic Eyes and Death watchers in Arcatraz has their cleave radius too large. It's impossible for melee to avoid. Might be a general issue with cleave though, I am not sure.

Edit: Cleave is not just "hard" to avoid, it actually is impossible. Unless we talk about a dodge / parry ^^ 
We had melee standing directly behind mobs, and at absolute max melee range.

**Comment by Chulain** [comment]
http://www.wowhead.com/npc=20868/entropic-eye
2007/04/24 (Patch 2.0.12)
Has a "Tentacle Cleave" attack which acts like a normal cleave. Also appears to have a mass polymorph that turns people into frogs.

http://www.wowhead.com/npc=20867/death-watcher

**Comment by ccshiro** [comment]
Need research about how chain targeting works for cleave. Most cleaves have a target type that works like chain lighting, where it start on the main target and bounces to nearby targets. We're looking for evidence (videos, for example), of the following:
- Can cleave bounce to targets behind you; or does it ignore what's not in front of the caster? (A warrior video would work, if there's a mob behind the warrior and within melee range of the main target.)
- Can cleave, with the help of bouncing, exceed the melee range from the warrior? I.e., can it bounce between targets as long as they are within melee range of eachother, even if it goes further away from the caster? Both multi shot and chain lighting can, which have the same type of targeting. Also, on retail, the answer is currently yes if you use Heroic Strike with Glyph of Cleave. (Again a warrior video would work well here.)

**Comment by Barroth** [comment]
http://forums.elitistjerks.com/topic/22516-dps-compendium/?p=660841 states that it is a 180° angle

**Comment by ccshiro** [comment]
Okay so that answers it cannot hit stuff behind you. The bounce range question still remains.

**Comment by Skibbli** [comment]
There does appear to be a bit of range extension for the cleave bounce i.e. it can hit a target that would seem to be too far away to use a melee ability on. The rogue that gets hits by the cleave in http://www.youtube.com/watch?v=3z2nV3pRDS0&t=3m40s looks to me like he is out of melee range (it's not amazingly clear but might help). I'll continue checking for more evidence.

**Comment by Kall-DestinyAwaits** [comment]
www.wowwiki.com/Area_of_Effect 
Cone of cleave should have 70° radius not 180

**Comment by Ickler** [comment]
I think what we see in that clip is due to the movement of the warrior executing the move. 

But generally speaking if you're behind the midway point of a mobs / Boss' hitbox you were always safe from Cleaves on retail at least. Maybe Dragons have a wider cleave, I seem to recall something about that. Gonna see if I find anything to support that. But it's definitely supposed to be avoidable by standing behind the target.

**Comment by Barroth** [comment]
Tested 2 scenes ingame, if someone finds another video with a seemingly large cleave jump link it here.

From Clinda2: a 4 yard jump

![clinda2](https://cloud.githubusercontent.com/assets/9391338/8875937/acbcd0cc-321c-11e5-9afe-3267f561033b.png)

From Pat Pvp3: a 6 yard jump

![pat pvp3](https://cloud.githubusercontent.com/assets/9391338/8875943/b85214e2-321c-11e5-9268-e8ba0772d6ee.png)

**Comment by Ickler** [comment]
I actually don't think it has any connection to where the target of the player is. The base of the attack doesn't "chain" from the target, but rather from the warrior / mob itself. 
Similar thing is chain lightning (from mobs), it can't chain behind the mob itself. Which I don't know how it work on CC, I'll test that next test. 

But in general, I believe distance between targets hit are irrelevant. But warrior position is the key. Could be easily tested, if we find a video where there's 6ish yards between two targets but the warrior is in front of them instead of in between them?

**Comment by Ickler** [comment]
You can see what I mean in this video: https://youtu.be/4okg6BmVoGM?t=16 

When the boss does a Chain Lightning it doesn't chain to the other melee because they are behind boss and boss is turned away. Something I as a retail tank, remember distinctly in Sethekk halls. Turning mobs = no bouncing / chaining on the CL. 

I think the cleave works the same way, it doesn't chain though. But uses the caster as a reference.

Edit: Either that, or it could be that cleave works exactly like CL?... It chains, but only if in the front half of a mobs hitbox?

**Comment by Barroth** [comment]
Cleave, Chain lightning, multishot and other jump spells got the same mechanics. 

As said earlier in this thread it is supposed to be a 180° angle in which the jumps can hit targets, aka it cannot jump behind the caster. The video you found seems to confirm this for Chainlightning aswell, so it probably applies to most if not all jump spells.

Generally those jump spells always look for a secondary target based on the first target hit, the target calculation is done on spell cast though, not on spell hit. So for example a shaman finishes his Chainlightning cast then all jump targets get calculated(apparently they all have to be infront of the caster) and then the spell is sent flying.

Like you said it might be possible that the jumps for those melee spells start from the caster instead of the target, it's unlikely though since they got the same spell effect/mechanic in the clients spelldata.
Nonetheless it would be nice to find a video to sort it out, so a video with a warrior casting cleave at one of two targets which  stand in a straight line in front of him.

**Comment by Barroth** [comment]
Found a druid video showing swipe: https://youtu.be/WNn00AHW51k?t=99 swipe cannot hit target behind it, looks like the 2. mob thats still hit is close to 180° with the druid beeing in the center.

Also from that video: swipe jump ~ 4.5yards
![swipe_range](https://cloud.githubusercontent.com/assets/9391338/8891401/36d9b02a-3328-11e5-86bb-6e378a719200.png)

**Comment by Skibbli** [comment]
To me the question about the range extension is not whether or not 2 people that get hit by the cleave are more than melee range apart but that the 2nd person that gets hit by the cleave is out of the warrior's melee range (so if the warrior targetted them instead they would not be able to swing at them).

In the video I linked when you see the cleave animation start the rogue behind the hunter (to me) appears to be far enough away that if Clinda had tried to use it on him instead he would have gotten the out of range message.

**Comment by ghost** [comment]
@Barroth From Pat, cleave hits on a secondary target who was well out of melee range. All three were in a line, with Pat on an end, not the middle. (He was moving, but never appeared to have gotten in range of the 2nd target).
https://www.youtube.com/watch?v=HnUSYSjoRTk&t=11m40s

Image is poor, it is clearer in the video.
![pat_cleave](https://cloud.githubusercontent.com/assets/1936487/8980758/b410ae4c-3678-11e5-9df9-e81ee9591b26.png)

**Comment by Barroth** [comment]
@Saben65 very nice find, that solves it :) Tested it ingame, the distance at this spot is ~9-10 yards between the warrior and the farthest target

Summary:(Some info is from the MutliShot report)
Cleave, Swipe and Chainlightning upon cast won't consider targets behind the caster as jump-target(180° arc).Since it applies to those three spells it is likely true for other jump spells like Multi-Shot aswell.

The Jumps of Cleave, Chainlightning, multishot are targetbased meaning it jumps from target to target. Most likely true for other spells aswell.

Cleave, Chainlightning and Multi-Shot can jump out of the spells cast range.

Cleave's Jumps got a 5-6 yard range, mentioned in an elitist jerks thread and fits the ingame tests I did.

**Comment by ccshiro** [comment]
Thanks for all the help guys, great work!

**Comment by ccnim** [comment]
https://youtu.be/xT-NDyVyI7w?t=315
https://youtu.be/xT-NDyVyI7w?t=395
Rogue gets hit by cleave behind the mob.

**Comment by Barroth** [comment]
Indeed in Pve there are some npcs which can cleave targets behind them aswell.

Important to note is that most research here is for the players cleave.

We got one video, which shows that chain lightning doesn't jump behind the caster npc, and so far I've never heared of 360° chainlightnings. So I'd guess that npcs cleave mechanic is special in beeing able to hit targets all around the caster.

**Comment by ccnim** [comment]
http://wowwiki.wikia.com/Patch_2.1.0
Creatures will no longer Cleave targets that aren't in front of them.

**Comment by Ickler** [comment]
Yeah hm early on it might have had pretty wonky cleaving? Requiring both tank + melee to max melee range and be in front and in back respectively. This is not bad, as long as it IS possible to avoid. If it's hard, that's fine :) All the more awareness required from players, and I'm for that.

**Comment by ccshiro** [comment]
Should now work correctly, I put NPC cleave to the pre 2.1 behavior.

**Comment by Ickler** [comment]
That is awesome! Really excited about this mechanic, no more sleeping melee / tanks ;)
