### ISSUE TITLE
Zone-Specific Trade Channels Shouldn't Exist

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#818]
I'm quite confident that there shouldn't be a [2. Trade - Ashenvale] for example.  I'll find evidence later.

**Comment by Chulain** [comment]
yeah trade channels are only for main cities and they're all linked with eachother

**Comment by YourNewfriend** [comment]
Evidence: https://youtu.be/3WmlnB-lFkQ?t=49s

He's in a Trade channel when he's in Orgrimmar.
