### ISSUE TITLE
[Entangling Roots]

### ISSUE THREAD

**Issue by Qxcr** [ccshiro/cc-buglist#819]
I've also used the provided code in case it is somehow related to it.
I'll include as many information as I can eventhough some might not be of any relevance.

This bug can stop melee mobs from acting normal again after Entangling Roots breaks by damage or if its duration expired.

How to reproduce:
Cast a damaging spell on a mob and afterwads Entangling Roots. Now either break Entangling Roots with more casts or wait for it to expire. All this with your character holding position.

The mob will freeze and not engage the player's character. However it will still take damage and throw daggers/axes if it can. The freeze will only break if the character moves (you can actually do one or two steps without breaking the freeze), the mob starts to flee due to low hp or if the mob can close the gab with an ability (e.g. Unyielding Knights with charge or Warp Stalkers with their Backstab-like ability).

Another thing that might be worth mentioning: Clefthoof Bulls use their Hoof Stomp while they are frozen. I assume this is producible to other mobs with similar abilities.

I've also used the provided code in case it is somehow related to it.

![wowscrnshot_070515_000124](https://cloud.githubusercontent.com/assets/11213208/8509718/e21d3b84-22b4-11e5-9f31-0bbf5a700155.jpg)
![wowscrnshot_070515_001903](https://cloud.githubusercontent.com/assets/11213208/8509719/e3b173ac-22b4-11e5-8c45-517830282faa.jpg)
![wowscrnshot_070515_005908](https://cloud.githubusercontent.com/assets/11213208/8509720/e6909832-22b4-11e5-856f-f925d19a947e.jpg)
![wowscrnshot_070515_010947](https://cloud.githubusercontent.com/assets/11213208/8509721/e8666b64-22b4-11e5-9b89-7c465c71b074.jpg)

**Comment by ccshiro** [comment]
Probably same bug as #783.
