### ISSUE TITLE
pet while on flying mount

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#822]
Your pet disappears when you hop on your mount, however you can take him with you while you remain on your mount by stabling it at a stable master and retrieving it.
![wow_2015_07_05_01_29_14_524](https://cloud.githubusercontent.com/assets/10247793/8509734/cc2b1cdc-22b5-11e5-90ca-a017bff66d9a.png)

**Comment by Chulain** [comment]
bet you like my pet name

**Comment by YourNewfriend** [comment]
Should you even be able to use "penis" in a pet name..?
