### ISSUE TITLE
Battle of the Crimson Watch - Weird/Glitchy

### ISSUE THREAD

**Issue by Jonssown** [ccshiro/cc-buglist#824]
2 Issues, vid only shows 1 of'em though:

1: Quest NPC sometimes flies out to kill the mobs, even ended up dying.

2: The quest sometimes fails and the mobs despawn mid-combat.

Youtube Video (1): https://www.youtube.com/watch?v=jrIqWtNTkMQ

Cheerio
/P

**Comment by Chulain** [comment]
flying goat wtf
