### ISSUE TITLE
soul shard doesn't show up on chat for other players

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#827]
soul shard doesn't show up on chat for other players

http://i.imgur.com/PxFp3M6.png
that's a hunter from a retail video (cant find vid anymore) and it did show up for him on his chat

---

creating healthstones and probably other conjured items dont show up either

https://youtu.be/0xx54ur_AAs?t=90
it does in this video

**Comment by ccshiro** [comment]
Does it show up for anyone in your vicinity, or for other people in your party?

**Comment by darkcranio** [comment]
It is for party/raid members as any other looted items.

**Comment by ccshiro** [comment]
Also changed message to "You create: [soul shard]." Evidence: https://www.youtube.com/watch?v=Qr2OgwreCgE
