### ISSUE TITLE
Channeling Bar Gets Broken By Outranging The Caster (visual)

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#828]
For example, if I cast Eyes of the Beast, and then take my pet out of range of its master (me), and then cancel Eyes of the Beast, the channeling bar will continue.

Another example is if I cast Eagle Eye far enough, and then cancel it, the bar will continue.

![image](https://cloud.githubusercontent.com/assets/13057166/8509895/ae9b5940-2277-11e5-87a4-d5c1cf27bf8f.png)

**Comment by sverkersham** [comment]
I remember this happening on retail, also happened with Far Sight.

**Comment by YourNewfriend** [comment]
https://youtu.be/wyVWnnA9H28?t=1m52s
1:52 - 2:23

https://www.youtube.com/watch?v=Z9ULNE_hWsg&feature=youtu.be&t=6m9s
