### ISSUE TITLE
NPCs Don't Attempt To Distance Themselves From Targets

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#829]
I'm not sure of the exact way the mechanic works.

![image](https://cloud.githubusercontent.com/assets/13057166/8509906/b2104d78-2278-11e5-8621-214055ee6cbc.png)

https://www.youtube.com/watch?v=OOiyXR91xd0&feature=youtu.be&t=42s (player)
https://youtu.be/v8shrjU6LvU?t=13s (pet)

**Comment by darkcranio** [comment]
I think it falls under the NPC spreading.

**Comment by YourNewfriend** [comment]
In the first video, the tiger pet can be seen moving away from the ogre when it gets too close.  In the second video, Ambassador Flamelash can be seen moving away from the pets.

![wowscrnshot_070615_174738](https://cloud.githubusercontent.com/assets/13057166/8536511/5be6ad44-2407-11e5-970d-c98419d2a6f7.jpg)

**Comment by YourNewfriend** [comment]
https://youtu.be/SwLjJH8LXfc?t=44m30s 
https://youtu.be/SwLjJH8LXfc?t=46m5s .
https://youtu.be/OOiyXR91xd0?t=1m40s
https://youtu.be/jTSyexUNN9E?t=2m43s
https://youtu.be/zWGKVPQ2LZ8?t=1m39s

**Comment by Chulain** [comment]
also a mob once stood behind me while i didnt move after (ranged) pulling

(just a single mob not a pack)

**Comment by YourNewfriend** [comment]
https://youtu.be/FsUr3i0iecs?t=9m49s

Pack of mobs move away from the Scorpion pet.
