### ISSUE TITLE
Magus Zabraxis (Honor Hold)

### ISSUE THREAD

**Issue by snipz69** [ccshiro/cc-buglist#83]
Not sure if this is intended, but at level 70 you can't access Zabraxis' shop window to buy Reagents, only the quest she gives. Even after accepting the quest clicking her only brings up the quest progress window. You can access her shop normally at Level 60 when you're too low level for the quest.

http://i.imgur.com/fAZsEaw.jpg - Level 60
http://i.imgur.com/tIRnkl1.jpg - Levl 70
http://www.wowhead.com/npc=16829/magus-zabraxis
http://www.wowhead.com/quest=9494/fel-embers - Quest in question

**Comment by ccnim** [comment]
I cannot get her gossip to show when she is using the vendor npc flag. Could this be related to that battlemasters can't show gossip?
