### ISSUE TITLE
Resetting a Kited Mob

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#832]
I picked up a mob outside of Orgrimmar, and I was kiting the mob with Faerie Fire.  Eventually I stopped, and waited for it to reset.  It wasn't resetting, and I got impatient after about 10-15 seconds, which is when I moved, causing the mob to immediately despawn rather than run away.

It reappeared at its spawn spot.

![18d5133e-227b-11e5-9fa3-41b3e28b2ff7](https://cloud.githubusercontent.com/assets/13057166/8509966/13b1a29a-227c-11e5-927d-995122260f51.png)

**Comment by ccshiro** [comment]
This is the exactly intended behavior.
