### ISSUE TITLE
[Vanilla][Durotar] Fizzle Darkstorm

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#834]
He doesn't do his fel magic ritual, and instead just looks at the runes when he patrols over to them.

https://www.youtube.com/watch?v=FaV6oAteJGI&feature=youtu.be&t=2h42m28s

**Comment by ccnim** [comment]
I just took that for the imp he summons.

**Comment by ccnim** [comment]
What spell is he using?

**Comment by leolomi** [comment]
He is using http://db.valkyrie-wow.org/?spell=20791

**Comment by YourNewfriend** [comment]
He seems to be getting separated with his Imp Minion when he spawns.
![image](https://cloud.githubusercontent.com/assets/13057166/9188689/d4795430-3f93-11e5-9339-dd662687a647.png)

**Comment by YourNewfriend** [comment]
Was the bug even addressed, or was this simply closed?
