### ISSUE TITLE
Missing Error Text Related To Guilds

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#835]
![image](https://cloud.githubusercontent.com/assets/13057166/8509991/0aafd5de-227e-11e5-82a8-4fd9a4805eac.png)

http://wowwiki.wikia.com/WoW_Constants/Errors?direction=next&oldid=146379

Confirmed missing:
"You have joined the guild."
"You have been kicked out of the guild."

On another server I've played on, these were missing.  I was unable to investigate if they were all missing, but they probably are:

*When joining a guild:
"You have joined the guild."

*When a player is kicked, he doesn't receive this message:
"You have been kicked out of the guild."

*When creating a guild:
"%s created"

*When creating a guild:
"Congratulations, you are a founding member of %s!"

**Comment by YourNewfriend** [comment]
I'm not sure what it should look like in TBC, but in Vanilla, the message of "%s has been kicked out of the guild by %s." was relayed to the player kicked, and nothing more.

Maybe both that and "You have been kicked out of the guild." should be sent to the player kicked, but I wasn't able to establish exactly what happens in TBC.

**Comment by YourNewfriend** [comment]
https://youtu.be/JMylc2Or1Ic?t=41s
http://wowwiki.wikia.com/WoW_constants?oldid=20945

At the time, the message "You have been kicked out of the guild" should've existed, and I'm not sure why it wasn't sent to this player.

**Comment by YourNewfriend** [comment]
https://youtu.be/HniEqJf26z4?t=4m46s

The error "You have been kicked out of the guild" existed during the time period of this video, but it wasn't sent to this player.  According to the player's history, this video should've been recorded in September 2006, and the mid-2005 article of WoW constants/errors contains the error message.

"You have been kicked out of the guild."  Maybe this only happens when a player kicks himself out of a guild.

**Comment by ccshiro** [comment]
Added the following messages:
"%s created."
"Congratulations, you are a founding member of %s!"
"%s has been kicked out of the guild by %s." (for the guy that got kicked as well, didn't remove it for everyone else -- would need a video showing that part)

The rest I was unable to figure out any packet data that resulted in the mentioned errors. It's possible these errors were never used on retail (there existed error messages in the client that are unused), or that I would need to inspect the handling of the errors in the executable (which I won't do for such a minor issue).

Found a video showing how it looks when you create a guild:
https://youtu.be/1tRdeLLqSBQ?t=2558
