### ISSUE TITLE
NPC Minions Shouldn't Despawn

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#837]
Upon the death of their masters.

Evidence:
https://www.youtube.com/watch?v=FaV6oAteJGI&feature=youtu.be&t=2h53m32s
https://youtu.be/5tNj6BRgi40?t=5m19s

**Comment by PatchnotesTBC** [comment]
I really hope Corecraft will make minions die after the minions die, So many private servers have the bug where the minions survuve after the master dies

**Comment by YourNewfriend** [comment]
yea, I guess we can't have minions standing around forever.  I guess they should despawn after a little while, or maybe their master won't summon a new minion if it respawns as long as its old one is alive?

I don't see the harm in them despawning once they've dropped combat really.  It's up to the devs.

**Comment by YourNewfriend** [comment]
Missing TBC evidence atm.

**Comment by ccshiro** [comment]
Opened a research topic over at #1058. Closing this in favor for that.
