### ISSUE TITLE
Underbog Mobs bugged

### ISSUE THREAD

**Issue by rylaiii** [ccshiro/cc-buglist#840]
when engaging the Underbat(s) in The Underbog, the mobs stand still forcing the players to go to the npc, instead of the npc coming to the players. when attacking the npc, the mob stands still for quite some time not doing anyhting. Had the same issue with Fen Ray(s) in The Underbog, they evaded (reset) half way through though.
https://i.imgur.com/j0qjTQV.jpg

**Comment by lynxzor** [comment]
You need to type ".movegens --verbose" in chat when this happens to mobs.

**Comment by rylaiii** [comment]
oh darn. i completely forgot to do that. :x

**Comment by ccshiro** [comment]
Cannot reproduce, report missing .movegens output of bugged NPCs.

**Comment by petaal** [comment]
Just ran underbog. All the mobs were working fine without evading for us.
