### ISSUE TITLE
Unable to socket tidefury helm

### ISSUE THREAD

**Issue by antman94** [ccshiro/cc-buglist#844]
Tried to socket the shaman dungeon set Tidefury Helm with the meta socket which have a chance to increase cast speed, this require more blue gems than yellow and i assured myself that i had but it still wouldn't socket, just played a sound and nothing changed.

**Comment by ConfusedCC** [comment]
tried to reproduce your bug , but the meta seems to socket fine, and activate when you put on enough blue gems. https://youtu.be/BEoU0boeyaE
