### ISSUE TITLE
Auto Unstuck Can Kill Players

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#845]
I used it while I was under the ramp.

![image](https://cloud.githubusercontent.com/assets/13057166/8510486/18720f88-229d-11e5-990b-118fa986a4a8.png)

Apparently I slew myself.

**Comment by Chulain** [comment]
emo

**Comment by ccshiro** [comment]
This is intentional. Yes, it's not blizzlike, but it will be kept like this to avoid abusing this as a second hearthstone.

**Comment by darkcranio** [comment]
Yes, but on retail if the HS was on cooldown the unstuck brought you furthert about 5 yards. I don't know how could players abuse this.

**Comment by YourNewfriend** [comment]
Yea, it might be nice to have a slightly more intelligent auto unstuck, but it's really not a big deal I guess.

**Comment by Chulain** [comment]
@ccshiro 
maybe add some sort of message that appears when someone starts casting unstuck to warn them

**Comment by apetkauskas** [comment]
Suggestion: Make Auto Unstuck teleport player to the nearest graveyard. That way the whole auto unstuck system wont be abused as hearthstone, but it may actually help.
