### ISSUE TITLE
Hunter's Pet dissapears.

### ISSUE THREAD

**Issue by Bugracker** [ccshiro/cc-buglist#846]
I was atacking Rebel Camp in SV and sudennly in the middle of fight my pet dissapeared.
After fight it says ''You do not have any pet'' ;(.. .

**Comment by meowmewo** [comment]
Have u fed it?

**Comment by Bugracker** [comment]
Yes ;D I also used ''maxhappines'' command ;p
Anyway same thing happend in the middle of dungeon in Auchidoum with other pet.

**Comment by ccshiro** [comment]
Closing since no further input was provided.
