### ISSUE TITLE
[Arcatraz] Defender Corpse / Warder Corpse

### ISSUE THREAD

**Issue by Roarek** [ccshiro/cc-buglist#848]
The corpses that house the Protean Spawn (worms) should not be attackable, and instead should spawn the worms when players walk over/by them, if my memory serves correctly. 

Proof: https://www.youtube.com/watch?v=_x_uewRsxbw&t=10m20s 10min 20sec in can see the corpse isn't "aggressive" and doesn't get attacked to spawn the worms. 

Here is a recording of the event from our run on the CC test: https://drive.google.com/file/d/0B4ZqMxVDoS9KS0c3a0dJT3JYdG8/view
Side note: the sentinel's lightning also seems overtuned; not the damage of it, but the frequency. We also experienced an instance where the sentinel would attack the tank through the wall (and very far from the tank) while he was on the ramp across the room in the room where you first encounter the three eredar mobs with 2 sentinels on each side of the next hallway.

Here is a recording of me deliberately walking over and around a corpse, getting no result, then attacking it and having the worms pop out: https://drive.google.com/file/d/0B4ZqMxVDoS9KNGo3dVlHcWo2QTA/view?usp=sharing

**Comment by BeerfishWoW** [comment]
Tonight we were able to attack the Corpses again.
