### ISSUE TITLE
Priest's Holy Concentration: no buff on procc

### ISSUE THREAD

**Issue by ShuTestCC** [ccshiro/cc-buglist#85]
Holy Concentration does not grant the buff when it procs, however does play its usual animation and sound. It is not an issue of the buff simply being hidden, because the cast following the proc will consume mana as usual. I also tested thoroughly and made sure the buff would not be immediately consumed by the spell that triggered it (trigger-spell consumes mana).

Method of testing was repeatedly casting greater heal (1) while naked on self (level 70) with 23/38 Holy spec (Holy Concentration 3/3).

**Comment by ShuTestCC** [comment]
More research needed but since today's server restart clearcasting appears to work again.

**Comment by ccshiro** [comment]
Barroth told me this is still bugged, so I will reopen this for now and check it later.
