### ISSUE TITLE
[Terokkar Forest] Skettis: Talonsworn Forest-Rager Not Spawning

### ISSUE THREAD

**Issue by jleli** [ccshiro/cc-buglist#850]
It appears that the Talonsworn Forest-Rager is not spawning in Skettis.  Instead, a Mountain Colossus appears to be spawning in its place.  I think only the Talonsworn Forest-Ragers should be spawning and there should be no Mountain Colossus.

Corecraft:
![mountain colossus corecraft](https://cloud.githubusercontent.com/assets/13183589/8510592/b13f8374-22ae-11e5-82ae-94ede0e89635.PNG)

Retail:  
![wowscrnshot_070515_002421](https://cloud.githubusercontent.com/assets/13183589/8510584/0a3186c2-22ae-11e5-8322-6e3c79c9efbd.jpg)

**Comment by YourNewfriend** [comment]
http://www.wowhead.com/npc=21844/mountain-colossus#comments
"When Skettis was turned into a questing area for 2.1, the mountain colossi were removed. The Talonsworn Forest-Rager patrollers walk roughly the same routes these giants did."
