### ISSUE TITLE
Eye of Kilrogg Is Useless With An Infernal Active

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#852]
Possibly true for all enslaved demons.  Works fine with regular demons.

Reproduction Guide:
Cast Inferno
Cast Eye of Kilrogg
Attempt to move the Eye of Kilrogg

**Comment by ccshiro** [comment]
Fixed it now, doesn't seem like it'll make a huge difference though. When testing, the Infernal starts attacking me when I summon the eye, and its Immolation aura ticks and kills the Eye before I have time to do much with it.
