### ISSUE TITLE
[Quest] Ring of Blood - quest disappeared 

### ISSUE THREAD

**Issue by Voodopad** [ccshiro/cc-buglist#853]
After we failed a quest and attempted to retake it, the npc do not offer us a quest. 

 http://youtu.be/HOj_imzVsBU

Edit: quest reappeared after some time, is this a normal behavior?

**Comment by Chulain** [comment]
how long did you wait?

i think they made sure you cant spawn multiple bosses, which might be causing this issue

**Comment by Chulain** [comment]
tried this, brokentoe despawned after about 5mins, quest didn't reappear

10mins later, still nothing

**Comment by Voodopad** [comment]
I accepted quest from a friend who started it. The mark reappeared after ~5min. We failed at twins.

**Comment by ccnim** [comment]
This is intended.
