### ISSUE TITLE
UI toggles off when mounted on a ground mount, in combat and displaying the map

### ISSUE THREAD

**Issue by Batfink54** [ccshiro/cc-buglist#854]
New level 70 warlock, ground mount and rode into combat.  Pressing the M key to display the map and then ESC to remove it toggled off the user interface as if I had pressed Alt-Z.  The UI remains hidden even when dismounting.

Pressing Alt-Z with the UI hidden redisplayed it as expected.

**Comment by Chulain** [comment]
cant reproduce, maybe an addon that does this?

**Comment by Batfink54** [comment]
Indeed it does appear to be an addon.  The issue was resolved when I disabled Cartographer, of all things..
