### ISSUE TITLE
Distract locking up mobs at spot for combat duration

### ISSUE THREAD

**Issue by FurioCC** [ccshiro/cc-buglist#859]
During Heroic Steamvaults we have enountered this bug.
Pack was distracted, then Square was polymorphed (i.e. poly pull happened).

Neither of Myrmidons did move, just stood there being in combat.
.movegens --verbose for some reason told me about party member and not about NPC.

Seems similar issue to #671 

![](http://i.imgur.com/iGOxTff.jpg)

**Comment by ccshiro** [comment]
In your screenshot the movegens command is on the wrong target (notice how it says the name of the other druid in your party). However, I was able to reproduce it (happens with mobs that are group moving), so there's no need to resubmit it.
