### ISSUE TITLE
Inspiring Presence doesn't give the 1% hit buff to the draenei himself, only to the party members.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#861]
Inspiring Presence doesn't give the 1% hit buff to the draenei himself, only to the party members.

**Comment by ccshiro** [comment]
The 1% buff does not show up in your buff bar (nor should it). Make sure you get the 1% hit and then close this issue, please.

**Comment by ConfusedCC** [comment]
Removed all hit gear and checked char sheet , shows up as +0 hit
http://i.imgur.com/h3txctk.jpg

**Comment by Doppelmoral** [comment]
It doesn't show in char panel, either. You still get the 1% in actual combat when comparing meters.

**Comment by rylaiii** [comment]
Hello,

I've  found  an article where it's  written about increasing tax on goods  and services,  you may find more information  here http://motive.mcvean.ca/lnewk

ross.porto@rocketmail.com
