### ISSUE TITLE
[Shadow Labrynth] Pathing Errors

### ISSUE THREAD

**Issue by Roarek** [ccshiro/cc-buglist#863]
Throughout the very first room of the instance and a little bit of the 2nd boss' room there have been a few pathing issues with the trash. I have recorded one instance of these pathing problems, but it happened on a few pulls before this one. Even when LOSing the aggroed mob, it would stand there.

Note that the other mob was sapped and distract was used on this pull. Issue is highlighted at 1:30 and on of this recording.  https://drive.google.com/file/d/0B4ZqMxVDoS9KaWRRcGdKMHdOdzA/view

Later in the dungeon, we encountered this pathing bug. The skeletons also got stuck several times. Distract was not used on this pull, but it seems to cause these issues more frequently. https://drive.google.com/file/d/0B4ZqMxVDoS9KQ3I0eFpVUUdxUk0/view?usp=sharing

At ~2:06 in this recording you can see the whole process that leads to the pathing error. Also worthy of note in this recording is how Will of the Forsaken will not break the Charm effect that the Cabal Spellbinder casts (called Brainwashing). https://drive.google.com/file/d/0B4ZqMxVDoS9KMUxpcUJlRXdGTWc/view?usp=sharing

**Comment by ccshiro** [comment]
The movement bugs following sap/distract was fixed in another issue (possibly the skeleton one excluded as it seems to be different, but couldn't make it trigger). If you do find the skeleton one again, please type ".movegens --verbose" into chat and take a screenshot.

**Comment by ccshiro** [comment]
Closing since no further input was provided.
