### ISSUE TITLE
Warlock pets

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#864]
When warlock pets are in defensive mode they should start attack a monster as soon as you (the warlock) cast a spell on a mob. How it works now is that the pet does not attack until you (the warlock) get hit by the mob. 

The first screenshot shows that i have attacked the wolf but my imp is just standing there doing nothing.
![wowscrnshot_070515_110403](https://cloud.githubusercontent.com/assets/9117993/8511042/c381d7ce-2305-11e5-8986-b202417a1ab4.jpg)
The second screenshot shows that after the wolf attacked me, my imp starts to attack the wolf.
![wowscrnshot_070515_110407](https://cloud.githubusercontent.com/assets/9117993/8511043/c6f6dd6e-2305-11e5-947d-b930f78f6d8d.jpg)

**Comment by ccshiro** [comment]
No, you're thinking of the new assist mode that was added in patch 4.2.
