### ISSUE TITLE
[NPC] Wildlord Antelarion missing a spell

### ISSUE THREAD

**Issue by Voodopad** [ccshiro/cc-buglist#868]
Wildlord Antelarion is missing Create Felsword Gas Mask spell. I've lost my mask and after I went to speak with him I couldn't continue the quest chain. 

![wow 2015-07-05 12-39-40-163](https://cloud.githubusercontent.com/assets/10586701/8511141/edf48954-2312-11e5-81fb-37c2cf77e35d.jpg)

http://www.wowhead.com/npc=22127/wildlord-antelarion#abilities

**Comment by jovce17** [comment]
cant you just abandon and re take the Quest ?

**Comment by Voodopad** [comment]
I am on the other quest where you have to kill demons, my helm disappeared due to the item bug like  #667 when I reloged the helm was back but I've lost the mask. So I have a completed the quest but can't return it.

Quest that I can't return >>> http://www.wowhead.com/quest=10820/deceive-thy-enemy

**Comment by FurioCC** [comment]
Remove your helm and put into bag then logout and log back, that should give you mask.

**Comment by Chulain** [comment]
proof:
http://www.wowhead.com/quest=10819/felsworn-gas-mask
2007/01/25 (Patch 2.0.6)
To get another mask, talk to Wildlord Antelarion

**Comment by Voodopad** [comment]
And when I talk to Wildlord Antelarion you can't get the mask (check screen shot)
