### ISSUE TITLE
Issues with Doomwalker

### ISSUE THREAD

**Issue by FurioCC** [ccshiro/cc-buglist#87]
We had several attempts at Doomwalker outdoor boss.
(had around 15 players with enough healers to pull and see how fight goes).

Issue N1 Insane chaining ranges
However all attempts ended up quite fast due to fact that his Chain Lightning ended up jumping between players through the whole screen for sick ranges of 30 or even 40 yards, dispite everyone being all VERY WELL spread out and causing in the end Cthun-like chaining damage.
Different sources say that 8 yards supposed to be safe range http://www.mmo-champion.com/content/671, or state that chain range supposed to be within 5-10 yards http://www.wowwiki.com/Doomwalker

Issue N2 No debuff after dying to boss
Those who die to boss supposed to get http://www.wowwiki.com/Mark_of_Death for 10 minutes
Atm it doesn't happen, so you can res and technically attempt to zerg him (good luck trying with issue N1 still present).

Issue N3 Boss moving around while performing Earthquake channel.
This was mentioned by our paladin tank, i didn't notice it myself, so just passing his information.

**Comment by ccshiro** [comment]
Issue N1 has been fixed.
Issue N2 I couldn't reproduce. Whenever I died to him I got the Mark of Death on me.
Issue N3 has been fixed.

If Issue N2 persist, please make a video or such and reopen this issue.
