### ISSUE TITLE
Pet commands not working if pet is outside of vision range

### ISSUE THREAD

**Issue by petaal** [ccshiro/cc-buglist#871]
Reproducing:
- Command pet to attack a mob
- Run away until the pet is outside of your vision range
- Now pet commands like pressing "passive" or right clicking special abilities have no effect

When trying to target pet when outside of vision range unit frames show "Unknown". If you move closer to the pet so you can see it commands start working fine. Also if you wait long enough for pet to kill the mob pet comes back to you normally.

Couldn't find proof of what should happen but nevertheless i dont think this is intended.

![wowscrnshot_070515_000212](https://cloud.githubusercontent.com/assets/11743711/8511378/19c643bc-231b-11e5-8e0e-c4a6242db842.jpg)

**Comment by ccshiro** [comment]
Tried what happens on retail; as soon as you lost vision of your pet it got unsummoned.
