### ISSUE TITLE
Right clicking an item from inventory to equip it, deletes the already equipped item in that slot

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#872]
I know I've seen an issue on this before, but it's still occuring.

**Comment by FurioCC** [comment]
Confirming, it happens, can't reproduce 100% reliably though, just occasionally.

**Comment by Chulain** [comment]
duplicate https://github.com/ccshiro/cc-buglist/issues/667

**Comment by Ickler** [comment]
So, what I did was I had Leggings of Assassination on. I was crafting Hillmans Pants (LW). I right clicked Hillmans and then "Yes" for soulbinding it, and woops the Assassination legs were gone. 

Managed to do the same with belt. Then swapped around a lot of leggings and belts, and tried to unequip the items manually. It then gave me "Internal bag Error" and grayed out the items, while it stayed on my character. Then by right clicking any item, the items were replaced and deleted.

Edit: I've been trying to provoke it, but it seems weird. I do however get it to happen regularly. But it mostly happens by doing regular stuff, then randomly trying to right click gear

**Comment by Lephidiles** [comment]
have you cleared the cache before this is happening.... been trying a couple for some time during this test to make this error occure to film it but it never happens for me

**Comment by FurioCC** [comment]
Ok i managed to reproduce it more or less reliably and recorded it.
Thing with vanishing items is that while they vanish, you still keep all their stats.
This can be seen later when you unequip all items and still have bonus stats while seeming naked.

It seems to me that item vanishing is related to crafting window being opened.
It happened to me with gloves, i managed to reproduce it with boots and belt and later reproduced with pants while recording.
https://www.dropbox.com/s/voag062z2wjy6zi/2015-07-05-2046-52.flv?dl=0#
Pls download vid as you cant' see shit on preview.

**Comment by ccshiro** [comment]
Duplicate (would've been better to just respond in #667). Nice testing though.

**Comment by rylaiii** [comment]
Hey friend, 

As I got from your last message you were  looking for  that  information, I think I have found it, check it  out http://amazing.6thspot.com/lnrqe

ross.porto

**Comment by rylaiii** [comment]
Yo! 

Look what surprising and  nice stuff  I've just  came across. That's amazing, isn't  it? Just take a look here http://ntungicestu.danceandswing.biz/lnfroxal

Wishes, ross.porto

**Comment by rylaiii** [comment]
Hello friend, 

Do  you have any plans for  this summer? I think I  found something  really interesting here http://life.costaricancosmetics.com/lnnbc/00

Rushing, ross.porto
