### ISSUE TITLE
Dispels vs 100% dispel immunity

### ISSUE THREAD

**Issue by robinsch** [ccshiro/cc-buglist#873]
If you spec into 3/3 Sanctified Seals and you only have a Seal active the dispeller should get the message "Nothing to dispel." Currently you cast dispel but it has no effect.

**Comment by Chulain** [comment]
invalid, working as intended

**Comment by robinsch** [comment]
http://www.arenajunkies.com/topic/24214-sanctified-seals-and-stoicism-shed-me-some-light/

"I get told there is nothing to dispell if a seal is all a ret paladin has up if he is 3/3 sanc seals. "

**Comment by Chulain** [comment]
http://e4ae.blogspot.be/2008/07/patch-243-and-you.html
"The alternative would be to have your seals be ignored by dispel effects and have Purge start hacking away at your Blessing of Freedom, which only has 30% resistance."

yep

**Comment by robinsch** [comment]
The bug report is about the only active buff on a paladin is a seal, nothing else. Since 2.4.3 dispel effects ignore 100% dispelable aura and then the message "Nothing to dispel should appear." Just as stated in my second comment.

**Comment by robinsch** [comment]
This is currently my solution for this problem, CanCast (CheckCast?). 
![Image](http://i.gyazo.com/92220e29354af78e9aca7e0077547870.png)

**Comment by robinsch** [comment]
I have no idea how you implemented it, but if you did basicly the same I did please recheck it for triggered spells, otherwise it will remove Ambolish Poisons on first tick if there is nothing to dispel.
