### ISSUE TITLE
Old Hillsbrad Foothills: Thrall attacks Player after Mindcontroled 'Durnholde Sentry' 

### ISSUE THREAD

**Issue by RealZwox** [ccshiro/cc-buglist#874]
This time a other Mob ;)

http://i.imgur.com/QGeMUEV.jpg

Try this with all mobs while escort.

Note: Thrall only attack our Healer and the Priest.

**Comment by YourNewfriend** [comment]
lold @ "You have forced my hand!"

**Comment by ccshiro** [comment]
Seems to be a different bug this time, basically if you do a positive action to the NPC while it's MC'd you get put on thrall's threat list (assistance threat). Making it technically not MC itself that's bugged this time, but I think it can only trigger while MC is active.

**Comment by ccshiro** [comment]
Okay, it should no longer be possible to gain assistance threat (from healing, etc) on targets you are friendly with.
