### ISSUE TITLE
PvP Gems have wrong costs

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#875]
###### 

[Runed Ornate Ruby] Item ID: 28118
Current cost on Corecraft: 6885
Correct cost: 28125

http://wowwiki.wikia.com/Runed_Ornate_Ruby
"Patch 2.1.0 (22-May-2007): Cost decreased to 8100 Honor points from 28125"
http://www.wowhead.com/item=28118/brilliant-ornate-ruby#comments
By Teslar on 2007/06/09 (Patch 2.1.1):
"With the upcoming patch (live on PTR), the price for this item will be lowered to 6885 honorpoints."
###### 

[Gleaming Ornate Dawnstone] Item ID: 28120
Current cost on Corecraft: 6885
Correct cost: 28125

http://wowwiki.wikia.com/Gleaming_Ornate_Dawnstone
"Patch 2.1.0 (22-May-2007): Cost decreased to 8100 Honor points from 28125"
http://www.wowhead.com/item=28120/smooth-ornate-dawnstone#comments
By viva on 2007/09/01 (Patch 2.1.3):
"it is now 6885 honor."
###### 

[Potent Ornate Topaz] Item ID: 28123
Current cost on Corecraft: 8500
Correct cost: 10000

http://wowwiki.wikia.com/Potent_Ornate_Topaz
"Patch 2.1.0 (22-May-2007): Cost decreased to 8.500 Honor points from 10,000"
###### 

[Bold Ornate Ruby] Item ID: 28362
Current cost on Corecraft: 6885
Correct cost: 28,125

http://www.wowhead.com/item=28362/delicate-ornate-ruby#comments
By Truant on 2007/04/17 (Patch 2.0.12):
"The cost is being lowered in 2.1. Current cost: 28,125 honor points. Next patch: 10,125 honor points."
###### 

[Smooth Ornate Dawnstone] Item ID: 28119
Current cost on Corecraft: 6885
Correct cost: 28125

http://wowwiki.wikia.com/Smooth_Ornate_Dawnstone
" Patch 2.1.0 (22-May-2007): Cost decreased to 8100 Honor points from 28125"
http://www.wowhead.com/item=28119/smooth-ornate-dawnstone#comments
By Arklen on 2007/07/07 (Patch 2.1.2):
"It has been lowered yet again to 6,885 as the website indicates."
###### 

[Inscribed Ornate Topaz] Item ID: 28363
Current cost on Corecraft: 8500
Correct cost: 31500

http://wowwiki.wikia.com/Inscribed_Ornate_Topaz?oldid=596454
"Cost: 31500 honor points"
http://www.wowhead.com/item=28363/deadly-ornate-topaz#comments
By Truant on 2007/04/17 (Patch 2.0.12):
"The cost is being dropped massively in 2.1. Current cost: 31,500 honor points. Next patch: 12,500 honor points."
Szatek on 2007/06/20 (Patch 2.1.2):
"And in Arena season#2 cost is reduced to 8500"
######

**Comment by ccnim** [comment]
You need to try and buy the item to get the correct cost to show up.
