### ISSUE TITLE
SW:D backfire damage

### ISSUE THREAD

**Issue by robinsch** [ccshiro/cc-buglist#876]
is not equal to damage dealt. Hit me as paladin for 755 but hit priest for 690

**Comment by DaRealBoss** [comment]
Wierd. Tested it on a target dummy and sw;d did the same dmg

**Comment by Chulain** [comment]
could be resillience reducing dmg? 755 for a crit sounds low tho

**Comment by robinsch** [comment]
not a crit, normal damage.

**Comment by jovce17** [comment]
its reduced due to  shadow resistance buff ...

**Comment by ccshiro** [comment]
The return damage starts the same but will still be modded by any modifiers you have that reduce damage (afaik). Please make sure that your claim holds up when you don't have anything that can reduce incoming damage (talents, resistance, resilience, etc).

**Comment by robinsch** [comment]
Okay, invalid. 

https://www.youtube.com/watch?v=MdXsUkc7ZA0
15:30 swd damage was absorbed, full damage for priest.
also swd deals abit less damage (maybe because the backfire damage is a DOT and gets reduced by resilience?)
