### ISSUE TITLE
SoB hit and judgement backfire

### ISSUE THREAD

**Issue by robinsch** [ccshiro/cc-buglist#878]
Are off, melee hit priest for 39 damage, backfire dmg was 2.
Judgement hit priest for 379, backfire dmg was 117.

**Comment by ccshiro** [comment]
Judgement backlash damage for 379 should be 117 if you have righteous fury with 3/3 improved righteous fury. The backlash damage of a 39 damage proc should be 3. Might be something wrong there, but I tried it in-game atm and I'm getting the correct backlash for the proc.

**Comment by Jumpka** [comment]
The melee hit part is way off if I'm not mistaken, it says "All melee attacks deal additional Holy damage equal to 35% of normal weapon damage, but the Paladin loses health equal to 10% of the TOTAL damage inflicted" meaning it should deal 10% of both the melee hit + the seal damage.

EDIT: Barroth is right, I found some old archived comments from wowhead and it should be 10% of the bonus damage, my bad.

**Comment by Barroth** [comment]
no it is just 10% of the dmg seal of blood did.
