### ISSUE TITLE
Wrong costs: [Pendant of Dominance] and [Pendant of Triumph]

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#880]
###### 

[Pendant of Dominance] Item ID: 28245
Current cost on Corecraft: 15300 honor + 10 EOTS marks
Correct cost: 22,500 honor + 10 EOTS marks

http://www.wowhead.com/item=28245/pendant-of-dominance#comments
By Toraa on 2007/04/17 (Patch 2.0.12):
"On the PTR for 2.1, Pendant of Triumph/Dominance has been reduced in price from 22,500 to 18,000 honor points"
By Aifor on 2007/03/07 (Patch 2.0.10):
"The cost being 22,500 honor and 10 Eye of the Storm Marks of Honor"
###### 

[Pendant of Triumph] Item ID: 28244
Current cost on Corecraft: 15300 honor + 10 EOTS marks
Correct cost: 22,500 honor + 10 EOTS marks

http://www.wowhead.com/item=28245/pendant-of-dominance#comments
By Toraa on 2007/04/17 (Patch 2.0.12):
"On the PTR for 2.1, Pendant of Triumph/Dominance has been reduced in price from 22,500 to 18,000 honor points"
######

**Comment by ccnim** [comment]
Need to click on the item to get the cost to show.
