### ISSUE TITLE
crafting an item "resets" the (profession) training window

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#884]
crafting an item while talking to a profession trainer will select the first recipe on the training window

**Comment by ccshiro** [comment]
Probably client side.

**Comment by Chulain** [comment]
cant find any videos but it also happens on a wotlk client

it also happened on a cata client, not the exact same but it was some sort of "reset"

**Comment by nbetcher** [comment]
I recall this being the behavior on retail.

**Comment by Chulain** [comment]
https://www.youtube.com/watch?v=fAhCi2rQ9yc

still happens on retail
