### ISSUE TITLE
[Shaman] totems dissappearing after recasting them

### ISSUE THREAD

**Issue by Amarok-bt** [ccshiro/cc-buglist#885]
When there is very little time left on a totem (~0.2s) the new totem may disappear after casting it. It bugged out like this when i recasted Searing Totem, it might be bugged for other totems too.

**Comment by ccshiro** [comment]
I automated the recasting of Searing Totem, and timed it so it would be recast before the previous one despawned. I tried at the following time remaining:

0.6 sec
0.5 sec
0.4 sec
0.3 sec
0.2 sec
0.1 sec

None of them triggered the bug. Might be some other trigger, need more info.

**Comment by ccshiro** [comment]
Closing since no further input was provided.
