### ISSUE TITLE
[Spell] - Create Healthstone [Tooltip]

### ISSUE THREAD

**Issue by silvesterk** [ccshiro/cc-buglist#886]
The spell tooltip isn't displaying the correct information, should be 2496 instead of 2080 after taking up 2 points in Improved Healthstone. The healthstone created displays the right information though.
![wowscrnshot_070515_143113](https://cloud.githubusercontent.com/assets/12173921/8511643/dff520b0-2322-11e5-8f01-d855f7d6b6d5.jpg)

**Comment by Chulain** [comment]
related with https://github.com/ccshiro/cc-buglist/issues/175
