### ISSUE TITLE
[Movement Spellcaster Ogres Blade's Edge Mountains]

### ISSUE THREAD

**Issue by Qxcr** [ccshiro/cc-buglist#890]
This bug makes certain spellcaster mobs not engage the player in melee combat once they have used all their mana.

How to reproduce:
Use a damaging spell to get aggro on a spellcaster mob. Wait for the mob to use all its mana.

The mob will not engage close combat. It will however use its abilities once it has regenerated enough mana again. It also will not pursuit if its target moves out of casting range. It will simply stay on its position.

Tested on following mobs:

-Bloodmaul Geomancer

![wowscrnshot_070515_135954](https://cloud.githubusercontent.com/assets/11213208/8511740/9cd4dff8-2324-11e5-8f81-1a703de96709.jpg)
![wowscrnshot_070515_140025](https://cloud.githubusercontent.com/assets/11213208/8511745/9df724cc-2324-11e5-9888-b0393bc7bedb.jpg)

-Bloodmaul Shaman (This mob kept placing its totems once destroyed as it also kept using its heal ability)

![wowscrnshot_070515_140330](https://cloud.githubusercontent.com/assets/11213208/8511761/0e432460-2325-11e5-9ffd-f25de7d2b353.jpg)

-Bloodmaul Warlock (This mob didn't use its Shadow Bolt regardless of it    having regenerated enough mana again. Its minion did engage in close combat after using all its mana.)

![wowscrnshot_070515_142715](https://cloud.githubusercontent.com/assets/11213208/8511774/74b84f72-2325-11e5-81b3-e2e73f64d61a.jpg)

Edit: This issue seems to be related to the ogres in Blade's Edge Mountains only. When testing the Arakkoa spellcasters in the northwest part of Blade's Edge Mountains, the Bonechewer Evokers at Hellfire Peninsula or the Sunfury Conjurers at Netherstorm they all engaged in melee combat.

**Comment by magikalCC** [comment]
Had this issue with Bloodmaul Skirmishers and Bloodmaul Brawlers too.
