### ISSUE TITLE
Quest: The Mindless Ones

### ISSUE THREAD

**Issue by TMXa** [ccshiro/cc-buglist#892]
Quest counter stopped after i got up to
Mindless Zombie 6/8
Wretched Zombie 4/8
Warlock Undead 2-nd lvl with pet

**Comment by TMXa** [comment]
I started the quest without pet (Imp), but when I dismissed my pet, the counter started to work again.

**Comment by Chulain** [comment]
if your pet deals a lot more dmg than you, you wont get the kill credit

could you loot the mobs?

**Comment by Chulain** [comment]
tested this myself, if your pet deals 50% or more dmg than you on a mob, you won't get credits/loot from it

im not sure but i think having to deal 50% or more is too much

**Comment by Chulain** [comment]
http://wowwiki.wikia.com/Hunter_pet
It is possible to have the pet fight one mob while the Hunter attacks another. Note: the Hunter will not gain loot or experience from a mob that the pet kills solo. This is a deliberate decision by Blizzard, not a bug. If you intend on pulling multiple mobs and having your pet kill one or more of them while you focus on others, it would be best to try to get at least one shot or hit on each of the mobs and then allow your pet to do its work on them.

**Comment by Chulain** [comment]
i guess damaging them once is enough, you cant afk kill that way either

**Comment by Chulain** [comment]
related https://github.com/ccshiro/cc-buglist/issues/995

this one was first but title is misleading

**Comment by ccshiro** [comment]
I'll use the #995 one instead.
