### ISSUE TITLE
[Hula Girl Doll] needs to be removed

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#894]
[Hula Girl Doll] needs to be removed. It was added in patch 2.3.0.
Item ID: 34249

http://wowwiki.wikia.com/Hula_Girl_Doll
"Patch 2.3.0 (13-Nov-2007): Added."

**Comment by darkcranio** [comment]
Then also remove the flying machine for engi.

**Comment by ghost** [comment]
@darkcranio I checked the engi trainer. They already removed the engi mounts.

**Comment by darkcranio** [comment]
@Protcow cool, glad that someone is caring about what and what not should be in at release, also make yourself a list meanwhile, what to put back in 2.1 content later.
