### ISSUE TITLE
Prospecting eats whole stack

### ISSUE THREAD

**Issue by maronics** [ccshiro/cc-buglist#898]
The jewelcrafting spell prospecting can be used from stacks of 5 upwards. If you have bigger stacks though, it consumes the whole stack. It should just consume 5 with every use.

**Comment by Vetinari1** [comment]
Yeah it happened to me aswell. It will eat whole stack of 20 ores but it will only yield like you are prospecting on 5 ores.

What it should do is:
It should prospect only 5 ores every time, even if its in stack of 20 and then leave the rest of those ores (5, 10, 15) untouched and yield reward from those 5 ores.
