### ISSUE TITLE
Should bounding box scale with enrage spells?

### ISSUE THREAD

**Issue by ccshiro** [ccshiro/cc-buglist#9]
Should bounding box of Units scale with Enrage spells (that change your model scale)? For example, the Hulking Helboar in Hellfire Peninsula.

EDIT: Forgot to mention, but the easiest way to test this is to see if the distance the mob follows you at changes when he grows bigger. Or if he will just start being partially inside of your model.

**Comment by ccshiro** [comment]
Input by Chulain:
10:36 <Chulain> https://www.youtube.com/watch?v=W24n2wGDnI0
10:36 <Chulain> enrages at 2:58
10:37 <Chulain> the boss is a lot more often inside his model after enrage

**Comment by ccshiro** [comment]
More Input by Chulain:
11:22 <Chulain> https://www.youtube.com/watch?v=Jnu5qda5DuE in this video it changes every time the boss uses fel rage, it also looks like the boss' position adjusts to its size
11:23 <Chulain> distance between player and boss is about the same even tho he gets bigger
11:24 <Chulain> first time @ 0:38
11:24 <Chulain> 2nd 1:20

**Comment by Dpthx** [comment]
I don't know if this helps, but https://www.youtube.com/watch?v=73hjs5t4BQ0

**Comment by sasfog** [comment]
So this is from WOTLK, and they aren't really running away from her, but bouncing between the tanks with taunts.
https://www.youtube.com/watch?v=62b9SxkjRxI#t=6m8s (Enrages at around 6 min 10 sec, 20 seconds later they start bouncing her.)

**Comment by ccshiro** [comment]
Thought it was hard to judge by the videos, so I tried Gruul on retail and it seemed to indeed scale with enrage size changes.
