### ISSUE TITLE
Negaton Warp-Master - Arcatraz

### ISSUE THREAD

**Issue by craberi** [ccshiro/cc-buglist#90]
The mob used http://www.wowhead.com/spell=36813/summon-negaton-field far to frequently.

**Comment by FurioCC** [comment]
I did heroic Arcatraz 2 or 3 tests ago, mob was doing it around every 20 seconds or so, which i consider as totally normal.

**Comment by craberi** [comment]
Observed it casting the spell almost every second on this test. There was like 5-6 Negaton fields up at the same time.

**Comment by Kall-DestinyAwaits** [comment]
It looks like Negaton spam this spell http://www.wowhead.com/spell=36813 or npc http://www.wowhead.com/npc=21414/negaton-field fallowing him. Mob have 10 stacks super fast even if tank move him whole time from pull

**Comment by Catfishs** [comment]
Yes, the mob was spamming it this test. Got to 10 stacks immediatly even though tank was moving the mob around. Hard to kill.

**Comment by Catfishs** [comment]
On a side note, these mobs used to work correctly on previous tests but seems like something broke them.
