### ISSUE TITLE
Shattrath City Peacekeeper attacking Target Dummy

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#900]
Problem: Shattrath City Peacekeeper near the Southern side of the CItadel is attacking a Training Dummy endlessly. 
How to reproduce: N/A
Solution: Assign Training Dummy alliance to be allied with Shattrath City in the SQL Database
Proof: http://i.imgur.com/A5Yg9R6.jpg
Burning crusade proof: N/A

**Comment by petaal** [comment]
https://github.com/ccshiro/cc-buglist/issues/169
