### ISSUE TITLE
Cleave hitting targets behind you

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#902]
Problem: A warrior's cleave is hitting targets behind the caster. Allegedly this does not happen on retail. More research likely needed.  
How to reproduce: N/A
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675593523?t=1h19m45s
Burning crusade proof: could not find

**Comment by ConfusedCC** [comment]
wiki link: http://wowwiki.wikia.com/Cleave?direction=prev&oldid=814499
Targets/Positioning: Two targets/front

**Comment by ccshiro** [comment]
Duplicate of #817.
