### ISSUE TITLE
Items came with Patch 2.1 (help needed)

### ISSUE THREAD

**Issue by darkcranio** [ccshiro/cc-buglist#906]
So as I was seeing the reports about 2.1 items I looked after it,

The topics there are related to 2.1
http://www.mmo-champion.com/search.php?searchid=20281602

First PTR post on MMO.
http://www.mmo-champion.com/threads/601193-2-1-0-Patch-on-PTR-!-Official-patch-notes-!?highlight=patch+2.1

Additional info.
http://web.archive.org/web/20071102020545/http://www.mmo-champion.com/index.php?topic=95.0

And with the help of web archive. The exact list of what it came with 2.1
http://web.archive.org/web/20070530004512/http://www.mmo-champion.com/index.php?topic=94.0

The only problem is that the pictures aren't seeable due to robots, BUT I DID find it on curse.
Go the to last link, pick one of the pictures like "Resistance gear upgrade" look up what is the filename(just put your cursor on it) eg.:
new_resist.jpg >>> type it into google images and tada the first pictures in HD from curse. We need all of it to determine what should be NOT in the game at start. (at least from patch 2.1)

Look for these items ingame!

**Comment by PatchnotesTBC** [comment]
The Epic Googles where 2.1

**Comment by ccnim** [comment]
I would post this on the forum instead.
