### ISSUE TITLE
cant duel in thunder bluff

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#907]
cant duel in thunder bluff, you could on retail remember if i remember right

http://dezfezable.deviantart.com/art/World-of-Warcraft-Meme-82950404
Jul 18, 2008
"mmm i dont like your ignore methods! i tend to mind control them and run them off thunderbluff! haha!...if their dumb enough to accept the duel at least ^.^;"

**Comment by Chulain** [comment]
thunder bluff\* not mulgore

**Comment by ccshiro** [comment]
Based on client-data so I'm sceptical that it's broken.

**Comment by Doope** [comment]
i spent my whole life in thunder bluff and you could only duel on the battlemaster cliff area

**Comment by giedrius-timinskis** [comment]
Can confirm that, spent countless hours dueling in TB with my mage. Dueling allowed only on the battlemaster cliff area (I think it's called Hunter Rise?).

**Comment by darkcranio** [comment]
^^^^ yep

**Comment by Chulain** [comment]
must've been on a bugged pserver then, damn memory

**Comment by KimmoKM** [comment]
You were able to duel in Hunter's Rise: "Thunder Bluff is the only capital city in which player duels are permitted, becoming available when within the Hunter Rise."

http://wowwiki.wikia.com/wiki/Thunder_Bluff#Notes

**Comment by KimmoKM** [comment]
Did you test dueling in Hunter Rise?

**Comment by Chulain** [comment]
you can
