### ISSUE TITLE
[Paladin] Seal of Blood procc crit doesn't give Vengeance buff

### ISSUE THREAD

**Issue by Tolgren** [ccshiro/cc-buglist#908]
When Seal of Blood crits, it doesn't activate/refresh Vengeance.

---

SoB crit:
![wowscrnshot_070515_164303](https://cloud.githubusercontent.com/assets/13187502/8512242/dc792c0c-233a-11e5-8f87-8e245dff6ba3.jpg)

It's german, but may I translate: 
Seal of Blood from Kackspalte hits Elixir for 1068 Holy damage. (Critical)

---

Autohit crit, instant Vengeance refresh:
![wowscrnshot_070515_164308](https://cloud.githubusercontent.com/assets/13187502/8512254/0c5653fa-233b-11e5-9326-974ba7870bb5.jpg)

Kackspalte hits Elixir, does 1637 physical Damage. (Critical)
Vengeance of Kackspalte is refreshed.

---

Video proof: https://www.youtube.com/watch?v=UyooXkH6mT8
At around 4:14 the paladin crits with 1292 yellow damage. 
Since he has SoB up, Crusader Strike is still on cooldown, Judgement is still on cooldown, this leaves only SoB procc as the only possibility.
You can see the Vengeance buff has a around 25 seconds duration before getting refreshed to 30 seconds by the 1292 SoB crit.

**Comment by Ensipid** [comment]
Seal of Command crits proc vengeance so it seems to be problem with just seal of blood.
![ccvengeance](https://cloud.githubusercontent.com/assets/13189833/8513594/2c0ba2c2-2340-11e5-9d88-7af1c2ec7501.png)

**Comment by Tolgren** [comment]
Yes, SoC works fine.

**Comment by robinsch** [comment]
m_canTrigger is false
