### ISSUE TITLE
Mobs not attacking after breaking CC

### ISSUE THREAD

**Issue by Bearmanpig** [ccshiro/cc-buglist#91]
When in Ramparts Heroic today my party encountered this bug 2 times, we were able to reproduce the bug in non-HC Ramparts a third time as well.

Current situation:
After CC is broken on a mob, the mob will stop attacking the players. It will keep facing the player that has aggro, rotating on the same spot, but the mob will not leave its spot. Even attacking it or being in melee range does not change this behaviour.

This bug happened two times after a polymorph, and was reproduced a third time with warlock fear. It seemed to be quite random, and most of the time this did not occur. I'm also unsure if the CC was broken by damage, or because the time on the CC expired.

I will do more testing tomorrow to try to reliably reproduce this bug.

**Comment by Catfishs** [comment]
The same thing happened to us in Underbog.

**Comment by ccshiro** [comment]
I merged this together with #190.
