### ISSUE TITLE
Hunter: Failed taming doenst reset attack mode

### ISSUE THREAD

**Issue by Argonn** [ccshiro/cc-buglist#914]
I placed a freezing trap on the ground, and started taming a Timber Worg in Terrokar forest. The taming failed (for unknown reason) the Worg broke free from the trap (timed out) and he stood there without attacking me. I was still in combat but the worg would not attack me before i did something to him (or move).

I tried to do this with the spiders in that same place, but the taming never failed again. Will keep trying.

**Comment by Argonn** [comment]
Had it again with the spiders in that area, as long as i stood with them (and dont move or attack) they never attacked me again.

Need to research if this comes because of the freeze trap, or taming. update coming:

Update: 
Cannot seem to reproduce this by just freezing them (without the taming).
Cannot seem to reproduce this by just taming them (without the freeze trap)

So this has to do with freezing a beast, failing you tame when its frozen

The spider which my taming failed upon. Just stood there for like 1-2minutes without a single action.
http://i.imgur.com/JdLT9WI.jpg?1

**Comment by ccshiro** [comment]
Cannot reproduce. It's possible this bug had the same core reason as #819, in which case it makes sense I can't get it to happen.

**Comment by Argonn** [comment]
Maybe get an warrior to 'taunt' the beast away while taming. This should make the taming fail in general.

**Comment by Argonn** [comment]
Tried it a dozen of times during this test. Couldn't get it to bug out. Will try again with a warrior helping out.

**Comment by Argonn** [comment]
Tried it with a warrior, we couldn't reproduce the bug. But we did find a new bug.
