### ISSUE TITLE
Shooting friendly targets with wand

### ISSUE THREAD

**Issue by ConfusedCC** [ccshiro/cc-buglist#915]
You can hit friendly targets, pets/ players of the same faction/ guards of shattrath with your wand

repro: start wanding a hostile/neutral target. then click the friendly npc/player/minion

https://www.youtube.com/watch?v=E5T1SscvJwU

**Comment by Whatsthis880** [comment]
Killed my friend on the same faction with that 10/10 pls don't fix :°))
