### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by tinvujasinovic1** [ccshiro/cc-buglist#916]
Once a mage gets some haste arcane missiles tend to lose a missile once in a while (will only fire 4 instead of 5)
tested with Mind Quickening Gem - grants 330 haste 
arcane missiles tooltip says a missile will fire every 0,83 and the cast should last 4,14 wich results in 4,9880 missiles
http://imgur.com/Xk5MOiN - 10 casts, 49 missiles because one cast didnt fire 5 
http://imgur.com/NAcLWUd - tooltip

**Comment by Jigodian** [comment]
I think that has something to do with the player's latency too.
