### ISSUE TITLE
Sweeping Strike Warrior

### ISSUE THREAD

**Issue by Kinglundh** [ccshiro/cc-buglist#918]
Sweeping Strike seems not to do the correct amount of damage, When you crit for e.g 2k the bouncing damage should also be 2k, but it seems like the bouncing damage only works like a normal hit.

**Comment by Roarek** [comment]
I was also experiencing some lower values on my sweeping strike attacks, sweeping strikes should hit it's target for the same value that the target of the initial spell was hit for.

**Comment by YourNewfriend** [comment]
It doesn't ignore armour though, and I believe that it can be avoided (miss/dodge/parry/others) in TBC unlike Vanilla.

**Comment by Roarek** [comment]
@YourNewfriend That sounds completely wrong to me, I don't think there was ever a time when Sweeping Strikes could be missed/dodged/blocked/parried. It should not ignore armor.

**Comment by YourNewfriend** [comment]
Yes you're right, sweeping strikes was never changed to be subject to those.  I also meant it shouldn't ignore armour.
