### ISSUE TITLE
Serrated Blades Rogue

### ISSUE THREAD

**Issue by Kinglundh** [ccshiro/cc-buglist#919]
The "Serrated Blade" talent is wrong.

It says "Causes your attacks to ignore 0 of your target's armor" 
It should ignore 560 armor,

**Comment by Chulain** [comment]
related https://github.com/ccshiro/cc-buglist/issues/175

**Comment by Ensipid** [comment]
![ccserratedblades](https://cloud.githubusercontent.com/assets/13189833/8513259/d7f7091a-2330-11e5-933b-6225b200f5fa.png)
Seemingly just a visual bug, under hit rating you can see that you get 560 ArP.
