### ISSUE TITLE
Pathing through the ceiling 

### ISSUE THREAD

**Issue by rylaiii** [ccshiro/cc-buglist#92]
in the Warmaul Hill cave in Nagrand. 
image one of location/cave
image two of npc in cave pathing through ceiling
image three of npc where he paths through 
https://imgur.com/a/Sflyl
when he paths through the ceiling he aggros in the cave and follows the path down to the cave entrance back to his original spot.

**Comment by rylaiii** [comment]
instead of posting a new issue, ill just add onto this one through the comments since they are exactly similar or atleast appear to be.
Boulderfist Warrior (npc) pathing through the ceiling in the cave right above Halaa in Nagrand. 
image one of location/cave.
image two of npc in cave pathing through ceiling.
image three of npc where he paths through.
https://imgur.com/a/1bOvs

**Comment by ccshiro** [comment]
Note to self: check #122, #124 and #146 as well.

**Comment by ccshiro** [comment]
This one is really hard to reproduce, so it's hard to determine if my fix works or if I'm just lucky. Anyway, I think we might've solved it. If it does happen again, please reopen the issue.

**Comment by rylaiii** [comment]
the first two posts of the pathing bugs are still active on the server.
