### ISSUE TITLE
nagrand arena doors

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#920]
nagrand arena doors (prolly all arenas) spawn too slowly, i was able to walk thro before the battle begun and sap the enemy team as they entered

**Comment by Chulain** [comment]
i believe you cant make it spawn faster, but something has to be done about this as it's really game breaking, perhaps some kind of character immobilize upon entering for a few seconds? or teleporting all players back to the original spawn point before the battle begins

**Comment by ccshiro** [comment]
Nim and I tried all 3 arenas, with a speed of 10 times your normal run speed, and we could not get through the doors. We do actually root you already until the doors spawn, so what happened to you is very strange.

Anyway, if you can figure out how to do it, that'd be great.

**Comment by Chulain** [comment]
too bad i didn't manage to reproduce this bug, i hope it somehow fixed itself..

**Comment by ccshiro** [comment]
I'll close this report since no one else has mentioned it happening.
