### ISSUE TITLE
After 10 mins offline still got lead

### ISSUE THREAD

**Issue by Aisires** [ccshiro/cc-buglist#923]
Hey there,

our Tank was offline for about 10 mins but remained the leader.
Maybe due to the server crash, but still.

**Comment by Chulain** [comment]
not sure but auto pass lead was implemented in wotlk?

**Comment by ccshiro** [comment]
Auto-passing of leader is implemented on our server. It's possible there exists some condition where it doesn't trigger. Please include steps how you reliably reproduce the issue.

**Comment by Aisires** [comment]
Okay.

I were the leader of our SH Hc group. Before the first trash pack inside the dun i gave the leader to our tank.

After ca. 15 mins the server crashed. After that crash our healer was the first one online again. I was second. After several mins everyone was online again, but not our tank. We waited 10 minutes and longer but he did not come back and remained the leader. We stood in the instanze the whole time.

![lead](https://cloud.githubusercontent.com/assets/13180039/8515979/76422402-23ad-11e5-8438-666fbebe247c.jpg)

**Comment by ccshiro** [comment]
The bug is that after a server restart, auto-passing will not trigger.
