### ISSUE TITLE
Arcatraz Sentinel/Destroyed Arcatraz Sentinel - NPC 

### ISSUE THREAD

**Issue by craberi** [ccshiro/cc-buglist#93]
They seem to be missing an ability like http://www.wowhead.com/spell=36716/energy-discharge
It's there but it never hit us in our run.

**Comment by craberi** [comment]
http://www.wowhead.com/spell=36719/explode also seems to be bugged, never been hit by it, always registers as ''missed'' when it goes off.

**Comment by Catfishs** [comment]
The Destroyed Arcatraz Sentinels are bugged. They aggro and behave like normal mobs while they shouldn't. Quote from wowwiki - "Originally appear as corpses but act in the same way as the Protean Spawns, coming back to life at around 40% health and attacking. After being aggro'ed until some time after their death they regularly hit random nearby people with "Energy Discharge" for 700-1000 Arcane damage."

Currently you can target them and they don't appear as corpses and you can aggro them normally, they don't even have "dead" idle animation and they don't do the lightning thing at all. Basically the mob doesn't work at all how it should.

**Comment by Catfishs** [comment]
On a side note, these mobs used to work correctly on previous tests but seems like something broke them.

**Comment by ccnim** [comment]
The lightning is bugged but everything else is working fine for me.

**Comment by ghost** [comment]
A video where is shows how it should be, at around 7:00 forward.
https://www.youtube.com/watch?v=Al3Qyici4LA

Both the dead state, and the beam at the end.
