### ISSUE TITLE
Defencive stance pet

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#931]
When attacking a npc (hostile action) pet is suppose to start attacking as well not wait until master is attacked

https://www.youtube.com/watch?v=Yylhn3cpO0E

**Comment by Barroth** [comment]
Retails pet behaviour is quite different from tbc, see http://wowwiki.wikia.com/Defensive?oldid=1432708

This is working as intended for tbc

**Comment by ccshiro** [comment]
Duplicate of #864, as I told that guy: "No, you're thinking of the new assist mode that was added in patch 4.2."
