### ISSUE TITLE
[Arcatraz] Heroic Arcatraz Sentinels

### ISSUE THREAD

**Issue by Roarek** [ccshiro/cc-buglist#934]
The Arcatraz Sentinels should cast an explosion when they are at about 5% HP that hits everything in melee range for ~4-5k arcane. The values on these spells are varying based on where you go to look, and it is difficult to verify with video evidence as there are barely any heroic arcatraz full runs to be found. 

In our encounters, they were in fact casting this ability, but it doesn't seem that it was actually dealing damage. Watch at the end of this video as our rogue (and also our warrior tank it looks like) is not harmed by the explosion though you see its animation visually affect them - when it dies damage goes out from the discharges only: https://drive.google.com/file/d/0B4ZqMxVDoS9KcXR3eXRuSzFKaEE/view?usp=sharing

The Energy Discharge's proc frequency also seems much faster than what I remember, but there needs to be more concrete evidence and additional research to really confirm that I'm not just misremembering. 

Here is what I could find regarding the sentinels. All sources indicate that there is an explosion near it's death - "the sentinel's hands will glow blue" and will explode thereafter for arcane melee-range damage. Again, they were casting it in our encounters, but the ability didn't seem to cause damage.
http://www.wowhead.com/npc=20869/arcatraz-sentinel#abilities:mode=heroic 
http://wowwiki.wikia.com/Arcatraz_Sentinel
http://wowwiki.wikia.com/Arcatraz
http://www.tentonhammer.com/node/27022

**Comment by KevinTyrrell** [comment]
Agreed. I was in this dungeon group as the tank and those sentinels have something wrong with them for sure. At one part in the dungeon, before the final room, two sentinels guard the bridge and right now it's near impossible to get past them, even with shield wall. I think their damage value and frequency of lightning is way off. I'm still looking for proof of this though.

**Comment by ccshiro** [comment]
The discharge damage and frequency is based on spell data, which is data directly from the blizzard client.

The damage from explode does not seem to him me though, as you said.

**Comment by KevinTyrrell** [comment]
Question, how does damage calculate between heroic and normal dungeons?

**Comment by ccshiro** [comment]
@KevinTyrrell different spells.

**Comment by ccnim** [comment]
Applies to Boom Bots as well, entry: 19692
