### ISSUE TITLE
warlord kalithresh

### ISSUE THREAD

**Issue by PolarCookie** [ccshiro/cc-buglist#936]
when he activates the enrage on canisters, sometimes the channeling just stops and nothing happens, even with canister not being killed.
this happened on the first two canisters, he enraged normally on the third, we killed the fourth and got another enrage on the fifth, stacking works as it should.
the aborting channel happened on runs both the 4th and 5th of july.

**Comment by petaal** [comment]
Same thing happened for my group. We destoyed 3 cannisters but let him channel the fourth one. Kalithresh channeled for a second or two, casted spell reflection and stopped channeling. The cannister was left untouched and he didn't get the buff.
