### ISSUE TITLE
Assigned mark on mobs stays after reset / respawn

### ISSUE THREAD

**Issue by ShuTestCC** [ccshiro/cc-buglist#94]
When a mob is assigned a mark and then killed and another mob is not marked with the same icon afterwards, when the killed mob respawns it will keep the mark.

Another player from my party adds (haven't confirmed it myself):
Similarly, a mob keeps its mark even if the instance is reset and reentered. 

Assigned mark in our case was skull.

IIRC the mark should disappear in both cases.

**Comment by Bearmanpig** [comment]
I can confirm this. When fighting Vazruden in HC Ramparts we marked the two mobs that you need to kill before the boss comes down with Circle and Skull. We wiped 3 or 4 times and the mobs respawned with their marks every single time.
