### ISSUE TITLE
Pathing bug

### ISSUE THREAD

**Issue by Pinhastest** [ccshiro/cc-buglist#942]
mobs got stuck when i cross the river.
![wowscrnshot_070615_004101](https://cloud.githubusercontent.com/assets/10587278/8514159/95d82d08-237f-11e5-8755-a03a65c9ead0.jpg)

**Comment by YourNewfriend** [comment]
Some mobs shouldn't be able to swim; maybe this is implemented.

**Comment by ccshiro** [comment]
Working as intended.

**Comment by Doppelmoral** [comment]
Btw judging from the screenshot it's bugged though. Mobs that are unable to follow a player in certain territories should evade and reset.

The whole evade mechanic isn't functional on probably all private servers, one of the reasons people could solo bosses in raids with fly hacks.
