### ISSUE TITLE
Exiting The Game-Client While Falling = Swimming In Midair (visual)

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#944]
While falling, if the game client is closed, this happens for 20 seconds:

![wowscrnshot_070515_182111](https://cloud.githubusercontent.com/assets/13057166/8514420/3c53a2d4-2344-11e5-83a9-73ec676e1869.jpg)

After logging back in, the player is teleported to the floor unharmed, and then the player takes fall damage shortly after.  I don't think it should have any affect on the player other than loss of control when he exits the game client like this.

**Comment by ccshiro** [comment]
Tried on retail: If you alt+f4 you get stationary in the air (no swimming). The next time you log in you continue falling from there. However, the position you started at is saved, and you still take the full amount of fall damage as if you hadn't alt+f4'd.
