### ISSUE TITLE
[Vanilla] Orcish Guards Should Say "For the Warchief!"

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#946]
https://youtu.be/vCRJyKfm1Fs?t=37s (Kor'kron Elite + Orgrimmar Grunts)
https://youtu.be/pF9yEZLB9jk?t=4m28s (Razorhill Grunts)

Translated:
https://youtu.be/N---GFeieSk?t=1m2s

I'm not sure if it's at engage or just during combat.  In the first video, it can be seen that there are probably 50~ guards, but only 4 actually say it, so it's pretty uncommon.

Probably @ engage

**Comment by KevinTyrrell** [comment]
In your two videos, I don't see when Orc enemies say those lines. Exactly when does it happen and where should we be looking?

**Comment by YourNewfriend** [comment]
Kil Mog Throm'ka

**Comment by YourNewfriend** [comment]
https://youtu.be/yZevjt-cw54?t=26s

Seems like it's @ engage.

**Comment by YourNewfriend** [comment]
https://youtu.be/uNlRAQx0_Yw?t=5m30s Den Grunt.

I'm thinking this is Durotar/Orgrimmar-only.
