### ISSUE TITLE
Creatures not detecting flying players nearby their models.

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#947]
Problem: large creatures (all creatures?) do not detect players high in the air, even though they are within distance of their model. This will require more research but I am pretty certain that creatures would detect nearby player in this circumstance, for example. 
How to reproduce: fly into the model of a semi-large creature.
Solution: perhaps make it so the creature will aggro whether the player is a certain X, Y, or Z distance away?
Proof: http://i.imgur.com/CVZ9ZzT.jpg, http://i.imgur.com/dpD1eUl.jpg
Burning crusade proof: unfound

**Comment by Skibbli** [comment]
I noticed this when flying up to the Raging Colossi in Hellfire Peninsula - could get inside them and be just a couple of yards off the ground for them to not aggro on me.

**Comment by ccshiro** [comment]
This mechanic works fine. If it doesn't work for a particular mob it has nothing to do with the mechanic, but rather that NPCs auto-attack distance is probably too short (i.e., his model data is wrong server-side). Nim will look at the mobs you mentioned and then close this issue.

**Comment by KevinTyrrell** [comment]
I mean, I can think of over 20 mobs on the top of my head with that size and some are pretty obscure. What would you do, individually fix them one by one?

**Comment by darkcranio** [comment]
I guess.

**Comment by ccnim** [comment]
I fix the model info as I go, many have already been fixed. If you notice any other mob with a low attack radius just report it and I'll fix it.
