### ISSUE TITLE
Doom Lord Kazzak

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#948]
Problem: aggro range is much smaller than it should be and both chat messages nor sound files are played out zone wide to Hellfire Peninsula.
How to reproduce: Logon two characters and put both in Hellfire Peninsula. Have one character aggro Doom Lord Kazzak.
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675822603, http://i.imgur.com/TrG2uSC.png (no chat message)
Burning crusade proof: https://youtu.be/Ey670WwIQjA?t=18 (note that this character is level 80 or beyond), https://youtu.be/jf51zsgl-FA?t=62 (level 70, aggroed from REALLY far away), https://youtu.be/bWPlxOIxC4w?t=21 (same distance, better view)

**Comment by YourNewfriend** [comment]
Zone-wide yells:
https://youtu.be/6M07DGR599Y

**Comment by ccshiro** [comment]
Added so moving onto the platform will aggro Kazzak. The zone-wide yell works fine for me, please try it again next test if you don't mind.
