### ISSUE TITLE
Merchant Buyback

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#95]
When you sell a lot of items to the merchant (so the buy back tab gets full) the last item sold is no longer shown in quick buy back.

**Comment by Oops73** [comment]
I can confirm this!

**Comment by ghost** [comment]
why close? the buyback option should be available for the items most recently sold to the vendor

did you just mean that you have fixed the issue?

**Comment by Iliana-sc** [comment]
it's tagged as bug and closed so that means it's fixed. otherwise it would be tagged as invalid and closed.
