### ISSUE TITLE
Duel Stun Should Suspend Players In Midair

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#952]
https://youtu.be/80dk-HjCPFE?t=1m19s

Drops them atm.  It might've been changed like iceblock, but idk.

According to this, it was working (probably) correctly under a month ago: https://github.com/ccshiro/cc-buglist/issues/654

**Comment by ccshiro** [comment]
Being stunned does not prevent you falling in 2.4.
