### ISSUE TITLE
Infernals and Doomguards(unenslaved) Should Only Be Aggressive Towards PvP Flagged Targets

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#954]
I'm only referring to proximity aggro.  If a person touches one of them, or someone who's in combat with one even if he isn't PvP flagged, they're still fair game for the Infernal or Doomguard.  

https://youtu.be/yZevjt-cw54?t=43s
https://www.youtube.com/watch?v=zWGKVPQ2LZ8&feature=youtu.be&t=3m40s
https://youtu.be/yva7MbQy11g?t=3m19s
https://youtu.be/HKQX9Ne1jdA

I don't know if this should extend to the ruleset of normal monsters that are enslaved.

**Comment by YourNewfriend** [comment]
https://youtu.be/zWGKVPQ2LZ8?t=1m45s immolation aura is not affecting a player that isn't pvp flagged and isn't on its threat table.

**Comment by ccshiro** [comment]
Okay, so the conclusion I draw from these videos is the infernal/doomguard only goes for people on its threat list or targets that are pvp flagged. The caster will be on the threat list by default, and anyone else that takes aggressive actions (such as hitting it, even while banished as shown in the third video) puts you on the threat list. For the doomguard it appears as if all 5 people assisting the ritual will be put on the threat list.

**Comment by darkcranio** [comment]
Yep.
