### ISSUE TITLE
Blood elf starting zone bugs

### ISSUE THREAD

**Issue by TMXa** [ccshiro/cc-buglist#956]
Ok I think the 1st one is known, but anyways. The quest "A thrust Unendint" (manatap quest) is bugged, the counter is not counting your creature taps. 
The second is that the Tender mobs there have strangely wide range of aggro (unlike other races starting zone mobs).
And a probable 3rd one is that, when i entered the pool of water where the tenders were, One of them aggroed and stayd on the side of the pool, but then some more came and aggroed and they entered the water and started to attack me.
Tainted arcane silver drops after quest has been completed
Felendren the banished quest - quest item not droping
No resurrection sickness after spirit healer (i was lvl 5)
That's all for now

**Comment by TMXa** [comment]
Tainted arcane silver drops after quest has been completed

**Comment by ghost** [comment]
ress sickness doesn't apply for low-level chars afaik

**Comment by Chulain** [comment]
mana tap: https://github.com/ccshiro/cc-buglist/issues/830
res sickness counts for players lv 10 and higher, +1 min every level capping at 10 minutes 
try to provide screenshots for pathing bugs

**Comment by Chulain** [comment]
also try to report one bug per issue

**Comment by TMXa** [comment]
Ok, so is there anything that I can do here to help you guys out, or just close the thread?
