### ISSUE TITLE
[Rogue] Distract causing positional issues

### ISSUE THREAD

**Issue by snipz69** [ccshiro/cc-buglist#96]
While fighting some Ango'rosh Ogres, I noticed that using Distract then Cheap Shot would cause the mobs to snap and face a new position upon being stunned.
http://i.imgur.com/eiZc9Ta.jpg 
It seems to purely be a graphical issue as while they are stunned in this new position I can't do any logical positional attacks (Mutilate in this example isn't hitting despite me being behind him, but I could hit him from the front/side as that's where his back was before I stunned him). Tested it on a nearby Marshlight Bleeder and it had the same issue - it faced a different direction after Distract + Cheap Shot.

**Comment by ccshiro** [comment]
Probably the same bug as #141. This report was made before the other, but the other's title I think is closer to the root of the problem, so I'm leaving it open instead. Thanks for the report.
