### ISSUE TITLE
NPC : Painmistress Gabrissa 

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#964]
Painmistress Gabrissa's "Curse of Pain" ability does not get remove when the player falls below 50% HP (http://www.wowhead.com/npc=21309/painmistress-gabrissa#abilities ; http://www.wowhead.com/spell=38048/curse-of-pain)

**Comment by ccnim** [comment]
• Gushing Wounds -- 35321 | Should be removed on any healing effects
• Gushing Wound -- 38363 | Should be removed on any healing effects

**Comment by ccshiro** [comment]
Also, 39215.
