### ISSUE TITLE
Quest : Outland Sucks!

### ISSUE THREAD

**Issue by Whatsthis880** [ccshiro/cc-buglist#965]
The respawn time of "Shredder Spare Parts" is like 5 seconds. Bug or meant to be for server release when 9000 people will fight to get quests done ? :P

**Comment by Chulain** [comment]
outlands*

**Comment by Whatsthis880** [comment]
http://www.wowhead.com/quest=10236/outland-sucks = outland :)

**Comment by Chulain** [comment]
not according to shiro.

**Comment by ccshiro** [comment]
Opened an issue to regulate respawn timers: #1067. This one can just go back to the default respawn timer.
