### ISSUE TITLE
[Warlock] Hellfire suicide durability loss

### ISSUE THREAD

**Issue by Mephisto22** [ccshiro/cc-buglist#967]
If a warlock commits suicide with his Hellfire ability he receives durability loss. You should not lose any durability on your items. This could be labeled as minor bug. 

Proof: http://www.wowhead.com/spell=1949/hellfire#comments

  "A very useful skill, in a raid or such, if wipe is inevitable, start casting hellfire so you wont lose durability from dying."

**Comment by lynxzor** [comment]
Might need to check Divine Intervention also.
