### ISSUE TITLE
[Seer Udalo] Dead mob with left click speech

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#968]
Problem: Udalo in Arcatraz speaks to you when you left click him
How to reproduce: N/A
Solutions: unknown
Proof: http://www.twitch.tv/hatefiend/b/675931813
Burning crusade proof: http://www.wowhead.com/quest=10705/seer-udalo#comments:id=25831 (he's dead, implying no speech), "Completion
The Ashtongue Seer has been long dead.  As you turn over his body, you spot writing scrawled on the floor."  -- Implying that he is not alive to talk to you

**Comment by ccnim** [comment]
This is client side as far as I know. Need a video where you can hear the voice in patch 2.4.3.

**Comment by KevinTyrrell** [comment]
Finding a video where you could hear him or not in 2.4.3 would be next to impossible. He's dead and clearly he should not talk back, right? You can just use deductive reasoning here. 

And what do you mean by client-side? Meaning the server has nothing to do with whether this mob in particular talks or not? Does that mean it's unfixable besides installing some sort of 'patch' to user's clients? Or do you mean it could be addon/WTF/cache related? I highly doubt it is the later, but you guys would be the experts in this regard.

**Comment by ccnim** [comment]
I've tried to fix this issue before but I think it's client side and nothing we can do about it I'm afraid.
