### ISSUE TITLE
Auction house pending message stays in the mailbox

### ISSUE THREAD

**Issue by testinkzcc2015** [ccshiro/cc-buglist#969]
When auction is bought and money is getting delivered the pending message does not disappear after the time is up.
1. I set up a auction
2. somebody bought it
3. I get pending message
4. time is up and I looted the golds I acquired from selling item in aH
5. Pending message remained in mailbox

**Comment by Jigodian** [comment]
Worked fine for me.

**Comment by testinkzcc2015** [comment]
seems like overnight they were gone. Not sure for how long they should remain in the mailbox honestly, but they didn't get removed instantly atleast. 
Maybe server crash removed them or something? Can't retest because nobody is buying at AH

**Comment by Jigodian** [comment]
I don't think the pending letter should auto delete itself after the gold delivery. It auto deletes itself after 24 hours anyway. And you can delete it whenever you want before that.

This is working as intended afaik.
