### ISSUE TITLE
leaving queue closes bg/arena window

### ISSUE THREAD

**Issue by Chulain** [ccshiro/cc-buglist#971]
if you leave your queue for arena/bgs the arena/bg window will close

![wow_2015_07_06_16_52_21_004](https://cloud.githubusercontent.com/assets/10247793/8525151/696d0560-23ff-11e5-8999-d5cd424d1509.png)
talking about this window

**Comment by ccshiro** [comment]
Sounds like a client-side thing.

**Comment by Chulain** [comment]
also happens on wotlk clients

and still happens on retail
