### ISSUE TITLE
"You are in Combat"

### ISSUE THREAD

**Issue by Kinglundh** [ccshiro/cc-buglist#974]
Was playing shattered halls Heroic and when we came to the Champion mobs, some of us couldnt get out of combat, so we werent able to drink / ress etc etc.
Could it be because of we used fear on mobs through the instance before and might have feared a critter or something? :)

**Comment by Jigodian** [comment]
Did the combat state eventually disappear or did it just go on forever?

**Comment by Chulain** [comment]
critters reset after a short time as far as i know

**Comment by Kinglundh** [comment]
It went on forever, atleast 30 minutes then we called it.

**Comment by ghost** [comment]
Check combat log for any indication. Use tab to target nearby mobs, see if any is targeting you.

**Comment by Yagrulol** [comment]
As for chullians post,
Not the July4th test but the one before that i noticed that critters did not reset after a short while.
I had to kill them to get out of combat.
If nothing has changed for the critters, this could've been the issue.

**Comment by ccshiro** [comment]
Fixed in #1460.
