### ISSUE TITLE
Quest: I work... For the Horde!

### ISSUE THREAD

**Issue by xtrawelt** [ccshiro/cc-buglist#975]
Not able to collect some Salvaged Wood's

![wowscrnshot_070615_185659](https://cloud.githubusercontent.com/assets/13199996/8528162/a1e60ea2-2411-11e5-96b0-6a00c620d217.jpg)
![wowscrnshot_070615_185714](https://cloud.githubusercontent.com/assets/13199996/8528170/aac382f2-2411-11e5-9c57-2e03dec1cb21.jpg)

![wowscrnshot_070615_190225](https://cloud.githubusercontent.com/assets/13199996/8528200/e6d19d38-2411-11e5-8d48-e7c2fa25cead.jpg)
![wowscrnshot_070615_190230](https://cloud.githubusercontent.com/assets/13199996/8528204/e8200274-2411-11e5-967c-1730e11db7ea.jpg)

looks like they only work on the "hordeside" of the canyon. can't remember how it worked in retail, but since it looks like you can pick them up...

**Comment by xtrawelt** [comment]
Somthing else: 

red circles: empty containers
blue circle: items stays on the ground after picking up (but cant pick it up again, so just visual)

http://i.imgur.com/S1dhS8r.jpg
http://i.imgur.com/bWu0ciI.jpg

**Comment by Chulain** [comment]
https://github.com/ccshiro/cc-buglist/issues/434
