### ISSUE TITLE
Unbalanced Arcatraz sentinels?

### ISSUE THREAD

**Issue by ebonywolf** [ccshiro/cc-buglist#976]
I'm aware Arcatraz is one of the hardest heroic, but near the last boss there is a group with 2 sentinels together. With T5 I can barely keep the tank alive against 1 of them, and 2 of them seems to be impossible as they are immune to every cc except freezing trap and even that only lasts 3-5 seconds for some reason.

We also had no melee dps (which made it easier) but we still couldnt come anywhere close to killing them. 

Here is a video of our group getting owned a few times
https://youtu.be/ZBn1DKAzhrk

I do not have footage of how they are suppose to be, but atm I dont see how its possible to kill them in preraid gear

**Comment by ccshiro** [comment]
Just tested, these NPCs are working as intended currently.

**Comment by xtrawelt** [comment]
We did them today, bursting one of them down, wipe and doing the second. I talked to an friend who played back then and has very good memory. He said, they did it the same way at the beginning, later they just killed both. 
Yes, we have Tier 5, but probably not the best setup + everyone is just logging in, rushing through gear and talents - not even perfect.

I think they work as they should

**Comment by Chulain** [comment]
sounds tbc-like

hue hue

**Comment by descendance** [comment]
Here is what i found about them:

Originally appear as corpses but act in the same way as the Protean Spawns, they come back to life at around 40% health and attack.

 After being aggroed until some time after their death they regularly hit random nearby people with "Energy Discharge" for 700-1000 Arcane damage. 

They are immune to taunt, and many other aggro-generating or reducing abilities. They also reset agro from time to time which makes them very uncontrollable. 

When they get low on life (about 5%) their hands begin to turn blue and they stop doing anything, including moving and after some time they will explode for about 4k~5k damage. Watch out for their arcane discharges which even continues some time after their second death.

This unit is subjected to all kind of slow ability and can be freeze trapped by hunter, so kite/trap are solutions against the last Sentinel pair. This unit can be controlled by the Gnomish Universal Remote trinket, although its arcane discharges will continue to injury friendly characters nearby.

The Sentinels are also vulnerable to Cheap Shot and Kidney Shot, useful to mitigate the melee damage of the mob on your tank, as well as to stop a Sentinel that is charging your casters.

source:https://web.archive.org/web/20070323012326/http://www.wowwiki.com/Arcatraz_Sentinel

I can not find clear indication of the dmg they should do on heroic mode only thing i found is that on normal they do the arcane discharge only when they die while on heroic they do it all the time.

**Comment by ebonywolf** [comment]
Well regardless, watching the beggining of the video you can see that the tank lost 14k health in 3 seconds(about 4600 dps) Thats way beyond what a healer can achieve. Even if he could, he would steal agroo. 

I went there again with a different group, we were able to beat them only with shieldwall( we killed one and died for the other).

Still dont think this trash group is feasible in pre raid gear, unless with a very specific set of classes.

**Comment by ghost** [comment]
1. Did you try pulling just one
2. Use a CC/stun rotation on one of them while bursting the other, don't wait for threat.
3. Have your tank kite taunt, bubble tank, Misdirection+consecration half of the way
4. Slows, roots as mentioned before.

Also, wowwiki has a history function, you don't need to webarchive it. Next to edit button in the arrow down.
http://wowwiki.wikia.com/Arcatraz_Sentinel?action=history
