### ISSUE TITLE
Arena bug causing people queued for 3v3 to battle people in 2v2 que

### ISSUE THREAD

**Issue by Rehnskiold** [ccshiro/cc-buglist#98]
Title pretty much explains it. Might have happened because I had a charter for 3v3 in inventory.

**Comment by Bugreporta** [comment]
This happend to me and my partner aswell, it has nothing to do with the charter.

**Comment by Rehnskiold** [comment]
That was quick, was quite a shock to face three people.

**Comment by Bugreporta** [comment]
This is caused when people who were suppost to queue for 3v3, queues for 2v2 instead and is somehow able to enter the the game as 3.

**Comment by Klimpb** [comment]
I did about 15 2v2 games and only 1 time did it say: "You are now eligible to enter 3v3 Arena", even though we queued up for 2v2... However we did not go against 3 players.
