### ISSUE TITLE
NPCs hesitating

### ISSUE THREAD

**Issue by ebonywolf** [ccshiro/cc-buglist#980]
Problem: Npcs hesitate to move when moving to attack.

Reproduce: idk a reliable way, but the problem happened very frequently while we did dungeons. 

video proof of some events: https://youtu.be/16heIssV5go

**Comment by DaRealBoss** [comment]
You shouldve typed ".movegens --verbose"  while targetting the mob and printed a screenshot for devs. 

Idk if this is related or not but I noticed something similar on some mobs in hellfire peninsula, so I will post it here: http://imgur.com/rzd8DdC

The mobs in my case werent hesitating for as long as yours in the video, but there was a noticeable 1 second or so hesitation where the mobs would stop while i kited them around in circles for 1 second, then continue chasing me. I did not stop moving while kiting btw. This issue reminded me of the pet chase issue where the pets would lag behind players as it chased them.
