### ISSUE TITLE
[Priest] Touch of weakness

### ISSUE THREAD

**Issue by DaRealBoss** [ccshiro/cc-buglist#983]
This ability seems to be scaling too much with some effects or spellpower idk, because it seems to be doing way too much dmg atm. Its been hitting 500-600 noncrit, and even critting at some times which i dont think is blizzlike either. http://imgur.com/DkVQVQy Also tested on players and it was doing just as much.

Retail touch of weakness, go to 0:46 seconds for the first one, you can also see its dmg at the beginning of almost every match, it hits for about 250 from a priest geared in s4: https://www.youtube.com/watch?v=Fv_CJDCmGO8

**Comment by Mephisto22** [comment]
the damage coefficient of this spell should be 10% of shadow spellpower

http://wowwiki.wikia.com/Spell_power_coefficient?oldid=1549180#Priest_Coefficients
