### ISSUE TITLE
Impact

### ISSUE THREAD

**Issue by Summoning01** [ccshiro/cc-buglist#984]
When the mage talent Impact procs, the attacked mob will not continue to move toward the mage and will simply stand there indefinitely (in combat) if the mage does not move after Impact, even if the mage keeps attacking. As soon as the attacker moves, the mob will continue normally. I've only tested this on a few mobs in front of Shattrath (iirc.Timber Wolf, Dreadfang Lurker, Vicious Teromoth) and only using Scorch and Fire Blast.

**Comment by Summoning01** [comment]
Also, i don't know if this is intended behaviour, but it seems that Impact will not proc while the mage is being hit in melee range.

350 scorch(rank 1) casts, 0 Impact procs.
70 fire blast(rank 1) casts, 0 Impact procs.
110 scorch(rank 9) casts, 0 Impact procs.
Molten Armor was also on the whole time.
mobs were the same as in the previous post.

edit: today it appeared to work normally unlike yesterday.

**Comment by Chulain** [comment]
might be related with https://github.com/ccshiro/cc-buglist/issues/819
