### ISSUE TITLE
Tailoring craft proc Insightful earthstorm diamond 

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#993]
item 25901

https://www.youtube.com/watch?v=VvC8yzHXUmE

**Comment by lynxzor** [comment]
If you read the Wowhead comments it pretty much procs off everything including crafting.

http://www.wowhead.com/item=25901/insightful-earthstorm-diamond#comments

**Comment by ccshiro** [comment]
@lynxzor thanks for the research.
