### ISSUE TITLE
Pet / owner dmg

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#995]
This got fixed earlier i know and you said you set the ration after some research

however it feels a bit wrong as i sometimes cannot out dps the pet to get loot / quest count if i get resist etc 
Lord klaq in this video killed him once already there and did nt get it that try either 

https://www.youtube.com/watch?v=NhCTaC26q44

**Comment by Mephisto22** [comment]
If you cant get the loot or quest count it is a bug. But it has nothing to do with pet damage, Felguard's damage is too low btw.

**Comment by Lephidiles** [comment]
Shiro knows what i mean as he wrote the thing causing this should be an easy fix but thing is if i am correct or he will ask me to find proof

**Comment by ccshiro** [comment]
I think you're right that you need to do too much damage currently.

Research needed: If your pet solo kills an NPC, you don't get loot. This we know. The question is: how much damage does one need to do to not have the loot taken by the pet. Is hitting it once enough, or do you need to do a percent of its health?

Some responses exists in #892 already.

**Comment by Lephidiles** [comment]
https://www.youtube.com/watch?v=lyIAfF5php0&t=8m10s

wotlk video but I am not good at decrypting this kind videos. but seems to me he gets loot from all and does not look like he do to much dmg

**Comment by Lephidiles** [comment]
http://us.battle.net/wow/en/forum/topic/10137433943

According to this; this has not changed since vanillla

Retail video (wod) : https://www.youtube.com/watch?v=o0NQvGJ_vgc

Here only the pet attacks the first target and i get no loot.
next target i shoot one normal shot for about 215 damage and get loot

so it seems like tagging the npc or get on the threat list even is enough

**Comment by Lephidiles** [comment]
https://www.youtube.com/watch?v=0HKvICX9jko

This is where i only use Mend pet to get on the threat list. but still get no loot
so seems you have to do dmg but one shot is enough

**Comment by Lephidiles** [comment]
https://www.youtube.com/watch?v=qYHd-vmIdTw

This is with only a dodged auto shoot + a lot of mend pet feign death

no loot

**Comment by Lephidiles** [comment]
@ccshiro want a better source for this to not have changed since vanilla as it is very weak or do you belive as i do that he is right ?

**Comment by ccshiro** [comment]
@Lephidiles It's probably fine to make this change, yeah. Thanks.

**Comment by YourNewfriend** [comment]
I wonder if damage is required at all, and if abilities that would simply extend a mob's leash timer are enough to become eligible for loot; this is just a theory without basis.

**Comment by Chulain** [comment]
moving my evidence from the other issue here

 July 14, 2008
http://wowwiki.wikia.com/Hunter_pet?oldid=1517220
Generally, one will send the pet in from a distance and allow it to get aggro on the mob before the hunter starts shooting. It is possible to have the pet fight one mob while the hunter attacks another;[Note: the hunter will not gain loot or experience from a mob the pet kills solo]. This is a deliberate decision by Blizzard, not a bug. If you intend on pulling mutiple mobs and having your pet kill one or more of them while you focus on others then it is best to try to get at least one shot or hit on each of the mobs then allow your pet to do his/her work on them.

**Comment by KimmoKM** [comment]
That coincides with my memory. You had to do at least some damage to a mob for you to gain experience and loot from the kill. However, having played pet classes a lot, I don't recall ever receiving anything but full experience, just having hit the mob once with any damaging ability.

There was another related mechanic, however, a certain threshold of damage you'd have to do to mobs if NPCs contributed to killing them. For example, if you kited Fel Reaver to Thrallmar mages, you were in no position to loot the Reaver as you couldn't do more than some 20% of the damage without ovearaggro (in this case it's of course unimportant, using a quest item at the corpse was enough). I can't find the specifics (I think the damage threshold might have been as high as 50%) but it seems to be implemented already.

Just a thought, maybe this rule is being applied to pets incorrectly?

**Comment by tests1500** [comment]
here warlock only shoots once to get xp and loot:
http://www.youtube.com/watch?v=pJcXFjwj4QQ&t=3m18s

also felguard kinda soloes 3 npcs.
