### ISSUE TITLE
[Priest] Mind Control npcs missing abilities

### ISSUE THREAD

**Issue by magikalCC** [ccshiro/cc-buglist#996]
There are many that are missing abilities when mind controlled. Example would be Shadowy Summoners. They should be able to cast  scorch and shadow rush. Some others would be Umbrafen Oracle and Witch Doctor, Skithian Windripper.

**Comment by lynxzor** [comment]
Shadowy Summoners
By catspats31 (15,755 – 5·28·116) on 2008/02/25 (Patch 2.3.3)
When Mind Controlled, this mob uses Scorch and Shadow Rush.

![wowscrnshot_070715_152642](https://cloud.githubusercontent.com/assets/795881/8538163/c07828ae-24bc-11e5-80c9-5535f0815e42.jpg)

Skithian Windripper
By Liscadipesce (1,279 – 2·14) on 2007/06/01 (Patch 2.1.0)
These mobs can be mind controlled by a priest, and used to cast a 5 minute buff on any friendly target that reduces the cost of any ability by 5%. Whether it be mana, rage, energy. Look up the spell 'Power of Kran'aish' for more information

By Zevyr (8,034 – 5·21·52) on 2007/10/12 (Patch 2.2.3)
Uses Arakkoa Blast, Windfury, Power of Kran'aish and Regrowth

![wowscrnshot_070715_152943](https://cloud.githubusercontent.com/assets/795881/8538189/2d2612c2-24bd-11e5-8d4b-b43b631a0314.jpg)

Umbrafen buff
By catspats31 (15,755 – 5·28·116) on 2008/02/20 (Patch 2.3.3)
It's a shame that when you Mind Control them, you can't cast the buff upon yourself or your allies.

**Comment by ccnim** [comment]
Fixed the ones you linked except for the umbrafen buff guy, sounds to me like the ability isn't useable while MCd.
