### ISSUE TITLE
Swapping bags

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#997]
You are allowed to swap bags with items in the bag.

I do not think this should be possible / allowed ?

https://www.youtube.com/watch?v=AB1RVeQJhnw

**Comment by Chulain** [comment]
hmm i thought you couldn't do this on pservers but you could on retail?

**Comment by nullfoxh** [comment]
What Chulain said.  You could always swap bags with items on retail.
It's been disabled on most private servers though to avoid dupes.

**Comment by ccshiro** [comment]
You should be allowed to.
